### ISSUE TITLE
Unexpected fail of "ContributeTabTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10043]
### Description
We have unexpected fail of "ContributeTabTest" selenium test. It looks like something went wrong with a method which checks a disappearance of notifications in IDE. We should investigate and resolve this problem.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for element to no longer be visible: By.id: gwt-debug-window-preferences-scrollPanel-preferences (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.Preferences.waitPreferencesFormIsClosed(Preferences.java:226)
	at org.eclipse.che.selenium.preferences.ContributeTabTest.closeForm(ContributeTabTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:552)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:769)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Report with a reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/304/Selenium_tests_report/

**OS and version:**    
Che 6.7.0 ; Vhrome 66.0; Fedora 28

**Comment by artaleks9** [comment]
This issue is already not actual
