### ISSUE TITLE
NPEs on workspace start-up

### ISSUE THREAD

**Issue by vrubezhny** [eclipse-che/che#10083]
### Description
Several NPEs might happen on workspace startup when an JsonRpcError instance is created from an Exception with no message provided (for example, TimeoutException).

### Reproduction Steps
- Create Java Workspace
- I have created a Plain Java project and open in editor its Main.java class
- Stop and restart workspace.
- Watch dev-machine log during the workspace start up

![lsnpe](https://user-images.githubusercontent.com/620781/41534936-b049fefe-7300-11e8-9e2f-37fadb8f9a05.gif)

**OS and version:**    

**Diagnostics:** 
```
2018-06-18 11:47:12,903[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: null
java.lang.NullPointerException: null
	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.marshall(GsonJsonRpcMarshaller.java:46)
	at com.google.gson.JsonPrimitive.setValue(JsonPrimitive.java:105)
	at com.google.gson.JsonPrimitive.isPrimitiveOrString(JsonPrimitive.java:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcErrorTransmitter.transmit(JsonRpcErrorTransmitter.java:45)
	at com.google.gson.JsonPrimitive.<init>(JsonPrimitive.java:65)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:102)
	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.getError(GsonJsonRpcMarshaller.java:117)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.NullPointerException: null
	at com.google.gson.JsonPrimitive.setValue(JsonPrimitive.java:105)
	at com.google.gson.JsonPrimitive.<init>(JsonPrimitive.java:65)
2018-06-18 11:47:16,682[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: null
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at com.google.gson.JsonPrimitive.isPrimitiveOrString(JsonPrimitive.java:282)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcErrorTransmitter.transmit(JsonRpcErrorTransmitter.java:45)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.marshall(GsonJsonRpcMarshaller.java:46)
	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.getError(GsonJsonRpcMarshaller.java:117)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eivantsov** [comment]
@vrubezhny does it happen in jdt-ls branch only?

**Comment by vrubezhny** [comment]
@eivantsov I'm facing it on jdt-ls/5730_java_ls_poc branch but I believe it's a common problem that appears on master branch too. We've just added some code that makes it happen more often. 

In short, the problem happens when an Exception which is created without the error message (like many TimeoutException's for example) is being reported thru JSON RPC - The `null` message just can't be converted into a JsonPrimitive, As such we should always replace `null` error with some valuable string, orprocess it some other way.

**Comment by eivantsov** [comment]
@vrubezhny can you please close this one once a PR is merged?

**Comment by vrubezhny** [comment]
@eivantsov Sure, yes, I'll close this issue as soon as the PR #10088 is merged

**Comment by vrubezhny** [comment]
Just to make sure, @eivantsov, I don't have rights to merge anything, so please you do the merge (or anybody else who has such a right)

**Comment by eivantsov** [comment]
@vrubezhny thanks. Merged.
