### ISSUE TITLE
Websocket timeout when starting workspace

### ISSUE THREAD

**Issue by gorootde** [eclipse-che/che#10099]
### Description
I've deployed Che 6.6.2 to an azure AKS Kubernetes cluster by using the helm charts in the deploy-subfolder. Everything seems to be running fine, but as soon as I start a workspace I get  `[WARN ] [.i.k.KubernetesInternalRuntime 193]  - Failed to start Kubernetes runtime of workspace workspacetadlc06rh29anoze. Cause: Failed to start websocket` in the log files and the same message in an error dialog in the browser.

The error message is shown almost immediately after the create button was pressed.

### Reproduction Steps

1. Install helm chart
2. Login
3. Create a Workspace

**OS and version:**    
Kubernetes 1.9.6
Che 6.6.2

**Diagnostics:** 
```

2018-06-19 06:46:20,248[io-8080-exec-12]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 314]   - Starting workspace 'test/wksp-vdk8' with id 'workspacetadlc06rh29anoze' by user 'test'
2018-06-19 06:46:26,264[default.svc/...]  [WARN ] [k.c.d.i.WatchConnectionManager 192]  - Exec Failure
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory$1.intercept(KubernetesClientFactory.java:187)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 26 common frames omitted
2018-06-19 06:46:26,265[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 193]  - Failed to start Kubernetes runtime of workspace workspacetadlc06rh29anoze. Cause: Failed to start websocket
2018-06-19 06:46:27,167[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 375]   - Workspace 'test:wksp-vdk8' with id 'workspacetadlc06rh29anoze' start failed
```

**Questions**

- Which websocket connection is timing out here? Where does che try to connect to? Unfortunately there is no websocket URL in the logs.
- As I am using the default helm chart configuration: A timeout after 5-6 seconds seems to be a pretty tight configuration: How to change that timeout?

**Comment by sleshchenko** [comment]
> Which websocket connection is timing out here? Where does che try to connect to? Unfortunately there is no websocket URL in the logs.

Unfortunately stack trace doesn't have information which exactly websocket connection failed. But there is several places where Che Server establishes WebSocket connection to Kubernetes/OpenShift:
- waiting until Pod becomes RUNNING https://github.com/eclipse/che/blob/6.6.2/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java#L238
- executing several command in a container to download and launch bootstrapper 
https://github.com/eclipse/che/blob/6.6.2/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/bootstrapper/KubernetesBootstrapper.java#L153

> As I am using the default helm chart configuration: A timeout after 5-6 seconds seems to be a pretty tight configuration: How to change that timeout?

I agree that 5-6 seconds seems to be a pretty tight configuration, but I'm not sure that it is really timeout issue, at least we don't configure this one. 5-6 seconds it may be time until pods become RUNNING and then bootstrapper fails to excecute command because of failed WebSocket connection.
@davidfestal Maybe you have an idea about such configuration?
To investigate an issue more, I would try to do `exec` manually via some Rest Client with a token which is used by Che (if it's a Kubernetes instance with RBAC enabled).

**Comment by carloreggiani** [comment]
I'm exactly in the same situation, Eclipse Che 6.6.2 single user:

`helm upgrade --install 6.6.2 --namespace che --set global.ingressDomain=28350216-546d-47f5-9f13-6e5b22008f9e.westeurope.aksapp.io ./ `

The deploy in AKS seems fine, maybe the problem is in the ingress configuration?

![immagine](https://user-images.githubusercontent.com/1014429/41582942-473e3706-73a3-11e8-935c-09b7c1453055.png)

![immagine](https://user-images.githubusercontent.com/1014429/41582984-69454600-73a3-11e8-99bb-9c928141a134.png)


Looking to the logs in the pod:

```
 java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket closed 
```

**Comment by sleshchenko** [comment]
@guydaichs @perspectivus1 Guys, maybe you have seen such issue?

**Comment by gorootde** [comment]
Meanwhile I've done a little curl-ing:
```
kubectl run -it --rm aks-ssh --image=debian --serviceaccount=che
curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default/api/
```
These commands work as expected, and a valid JSON is return from the API. So the che `ServiceAccount` seems to have all permissions required.

**Comment by eivantsov** [comment]
I think @sleshchenko means to curl Che URL from within a pod.

**Comment by gorootde** [comment]
Meanwhile I've done a little curl-ing:
```
kubectl run -it --rm aks-ssh --image=debian --serviceaccount=che
curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default/api/
```
These commands work as expected, and a valid JSON is return from the API. So the che `ServiceAccount` seems to have all permissions required.


Within a remote debug session to my cluster I found out that che want's to create a watch on an ingress. The websocket created to watch it is the root cause for the timeout exception in the logfiles.
Unfortunately I am not able to upload any images here, otherwise I would have shared the object dump of the debugger.

**Comment by sleshchenko** [comment]
> I think @sleshchenko means to curl Che URL from within a pod.

@eivantsov I didn't, but it makes sense =)

**Comment by gorootde** [comment]
Che is curl'able from a pod running in the same cluster. 

The root cause seems really to be that the kubernetes API is not responding to the API calls within the timeout (See second part of my last comment here)

**Comment by gorootde** [comment]
Update:
I've tried to do a similar request then che does (just on another ingress object in the same namespace) via 

```
 kubectl exec  che-f65fb768d-tjw4f -- curl -v -i -N --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer <token>" -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Origin: https://kubernetes.default.svc:-1" -H "Sec-WebSocket-Key: <WSKey>" -H "Sec-Websocket-Version: 13" "https://kubernetes.default.svc/apis/extensions/v1beta1/namespaces/che-workspace/ingresses?fieldSelector=metadata.name%3Dingresscd8ggg9t&watch=true"
```
which works perfectly fine. The websocket is open and I can receive events.

So the only difference seems to be that che is not using curl, which leads me to the conclusion that this might be a bug in the che implementation.

@sleshchenko @eivantsov How to proceed with this issue?

**Comment by eivantsov** [comment]
@l0rd @skabashnyuk is this something that one of the teams should investigate?
