### ISSUE TITLE
Investigate reason of failing the "RollingUpdateStrategyWithEditorTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10251]
### Description
We have unexpected fail of "RollingUpdateStrategyWithEditorTest" selenium test. It looks like something went wrong with workspace starting after rolling update. We should investigate this problem and find the reason.

**Log:**
```
com.google.inject.ProvisionException:  Unable to provision, see the following errors:  1) Error in custom provider, java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Workspace name='workspacexyn5oz' start failed.   at org.eclipse.che.selenium.core.CheSeleniumSuiteModule.getWorkspace(CheSeleniumSuiteModule.java:148)   while locating org.eclipse.che.selenium.core.workspace.TestWorkspace     for field at org.eclipse.che.selenium.hotupdate.rolling.RollingUpdateStrategyWithEditorTest.workspace(RollingUpdateStrategyWithEditorTest.java:41)   while locating org.eclipse.che.selenium.hotupdate.rolling.RollingUpdateStrategyWithEditorTest  1 error 	at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:486) 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:67) 	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987) 	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.injectDependencies(SeleniumTestHandler.java:278) 	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.beforeInvocation(SeleniumTestHandler.java:242) 	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84) 	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62) 	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:603) 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:531) 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215) 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140) 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170) 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104) 	at org.testng.TestRunner.privateRun(TestRunner.java:767) 	at org.testng.TestRunner.run(TestRunner.java:617) 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343) 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305) 	at org.testng.SuiteRunner.run(SuiteRunner.java:254) 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) 	at org.testng.TestNG.run(TestNG.java:1057) 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135) 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193) 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94) 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146) 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373) 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334) 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119) 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407) Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Workspace name='workspacexyn5oz' start failed. 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceImpl.await(TestWorkspaceImpl.java:86) 	at org.eclipse.che.selenium.core.CheSeleniumSuiteModule.getWorkspace(CheSeleniumSuiteModule.java:149) 	at org.eclipse.che.selenium.core.CheSeleniumSuiteModule$$FastClassByGuice$$87827f64.invoke(<generated>) 	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264) 	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401) 	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376) 	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54) 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132) 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93) 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80) 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80) 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62) 	... 30 more Caused by: java.lang.IllegalStateException: Workspace name='workspacexyn5oz' start failed. 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceImpl.lambda$new$1(TestWorkspaceImpl.java:79) 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) Caused by: java.lang.IllegalStateException: Workspace workspacexyn5oz, status=STOPPED, expected status=RUNNING 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.waitStatus(TestWorkspaceServiceClient.java:158) 	at org.eclipse.che.selenium.core.client.TestWorkspaceServiceClient.start(TestWorkspaceServiceClient.java:207) 	at org.eclipse.che.selenium.core.workspace.TestWorkspaceImpl.lambda$new$1(TestWorkspaceImpl.java:62)
--
```
**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-multiuser-master-ocp-rolling-strategy-test/9/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
The reason is found and the problem is fixed https://github.com/eclipse/che/pull/10269
