### ISSUE TITLE
Selenium test report html page lost its styles

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10257]
### Description
Selenium test report html page is incomplete because required styles and images aren't generated:
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/272/Selenium_tests_report/
![screenshot from 2018-07-04 11-04-14](https://user-images.githubusercontent.com/1197777/42264683-09781b02-7f7a-11e8-8f80-56630661e8a6.png)

**Comment by dmytro-ndp** [comment]
Test report resources aren't generated because **maven-site-plugin** which generates test report is skipped in one of the parent pom.xml https://github.com/eclipse/che-parent/blob/master/pom.xml#L1030

**Comment by dmytro-ndp** [comment]
We need to restore links to screenshots in the report as well. To do this, we might move **target/screenshots** to the **target/site/images/**.

**Comment by dmytro-ndp** [comment]
There is a problem with registering failure in case of workspace logs is absent https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/342/consoleText: 
```
2018-09-01 22:28:35,414[pool-1-thread-1]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 328]  - Test WorkspacesListTest.checkSorting failed. Error: Known issue https://github.com/eclipse/che/issues/4242
2018-09-01 22:28:35,993[pool-1-thread-1]  [WARN ] [stOpenshiftWorkspaceLogsReader 80]   - It's impossible to get status of workspace with id='null'
org.eclipse.che.api.core.NotFoundException: Workspace with id 'null' doesn't exist
	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:270)
	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
	at org.eclipse.che.selenium.core.client.AbstractTestWorkspaceServiceClient.getById(AbstractTestWorkspaceServiceClient.java:160)
	at org.eclipse.che.selenium.core.client.AbstractTestWorkspaceServiceClient.getStatus(AbstractTestWorkspaceServiceClient.java:166)
	at org.eclipse.che.selenium.core.workspace.TestWorkspaceLogsReader.read(TestWorkspaceLogsReader.java:71)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.captureTestWorkspaceLogs(SeleniumTestHandler.java:376)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.onTestFinish(SeleniumTestHandler.java:351)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.onTestFailure(SeleniumTestHandler.java:195)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:758)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-09-01 22:28:35,994[pool-1-thread-1]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 328]  - Test WorkspacesListTest.checkSorting failed. Error: Not a directory.
2018-09-01 22:28:36,672[pool-1-thread-1]  [WARN ] [stOpenshiftWorkspaceLogsReader 80]   - It's impossible to get status of workspace with id='null'
org.eclipse.che.api.core.NotFoundException: Workspace with id 'null' doesn't exist
	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:270)
	at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:164)
	at org.eclipse.che.selenium.core.client.AbstractTestWorkspaceServiceClient.getById(AbstractTestWorkspaceServiceClient.java:160)
	at org.eclipse.che.selenium.core.client.AbstractTestWorkspaceServiceClient.getStatus(AbstractTestWorkspaceServiceClient.java:166)
	at org.eclipse.che.selenium.core.workspace.TestWorkspaceLogsReader.read(TestWorkspaceLogsReader.java:71)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.captureTestWorkspaceLogs(SeleniumTestHandler.java:376)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.onTestFinish(SeleniumTestHandler.java:351)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.onTestFailure(SeleniumTestHandler.java:195)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1244)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-1-thread-1" java.lang.IllegalArgumentException: Not a directory.
	at org.eclipse.che.commons.lang.ZipUtils.zipDir(ZipUtils.java:48)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.captureTestWorkspaceLogs(SeleniumTestHandler.java:381)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.onTestFinish(SeleniumTestHandler.java:351)
	at org.eclipse.che.selenium.core.inject.SeleniumTestHandler.onTestFailure(SeleniumTestHandler.java:195)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1244)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmytro-ndp** [comment]
@riuvshin: could you, please, pack Eclipse Che server logs (that is content of directories `ws/ocp_logs/`, `ws/che_server_logs/`) into the **ws/selenium/che-selenium-test/target/site/che_server_logs.zip** file on CI jobs https://ci.codenvycorp.com/view/qa/ and https://ci.codenvycorp.com/view/pr-builds/ so that it will be accessibly from within _Selenium test report _?
