### ISSUE TITLE
Unexpected fail of "NewWorkspacePageTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10281]
### Description
We have unexpected fail of "NewWorkspacePageTest" selenium test, it looks like something went wrong with a method which checks a stacks list. We should investigate a reason of fail and resolve it.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for presence of element located by: By.xpath: //div[@data-stack-id='openshift-default'] (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitPresence(SeleniumWebDriverHelper.java:345)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitPresence(SeleniumWebDriverHelper.java:357)
	at org.eclipse.che.selenium.pageobject.dashboard.NewWorkspace.lambda$waitStacks$14(NewWorkspace.java:727)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at org.eclipse.che.selenium.pageobject.dashboard.NewWorkspace.waitStacks(NewWorkspace.java:725)
	at org.eclipse.che.selenium.dashboard.workspaces.NewWorkspacePageTest.checkFiltersButton(NewWorkspacePageTest.java:620)
	at org.eclipse.che.selenium.dashboard.workspaces.NewWorkspacePageTest.checkOpenshiftFiltersButton(NewWorkspacePageTest.java:368)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-stack-id='openshift-default']"}
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/272/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/10297
