### ISSUE TITLE
 Unexpected fail of PhpFileEditingTest selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10330]
### Description
We have unexpected fail of **PhpFileEditingTest** selenium test. The test fails when checking expected text in Autocomplete container.  We should clarify reason and fix it.

**Log:**
```
Expected condition failed: waiting for Expected condition failed: waiting for org.eclipse.che.selenium.pageobject.CodenvyEditor$$Lambda$94/520610977@23182189 (tried for 20 second(s) with 500 MILLISECONDS interval) Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102' Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver

org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for org.eclipse.che.selenium.pageobject.CodenvyEditor$$Lambda$94/520610977@23182189 (tried for 20 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitTextIntoAutocompleteContainer(CodenvyEditor.java:683)
	at org.eclipse.che.selenium.languageserver.PhpFileEditingTest.checkCodeAssistant(PhpFileEditingTest.java:109)
	at org.eclipse.che.selenium.languageserver.PhpFileEditingTest.checkMainFeaturesPhpLS(PhpFileEditingTest.java:90)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/329/Selenium_tests_report/

**Screenshot:**
![org eclipse che selenium languageserver phpfileeditingtest checkmainfeaturesphpls_tny2w2y6](https://user-images.githubusercontent.com/7760565/42434546-32e0d548-835c-11e8-91ce-7032614f761c.png)

**Comment by SkorikSergey** [comment]
Fixed.
