### ISSUE TITLE
Question: Cannot Initialize Language Server Sidecar

### ISSUE THREAD

**Issue by Jimmyscene** [eclipse-che/che#10386]
### Description

Hey Guys, I'm trying to get a custom language-server sidecar running in che, following the docs at https://www.eclipse.org/che/docs/language-servers.html, but I'm getting an error upon creating a file with the corresponding languageRegex. I'm using @eivantsov's golang language server in the example but I plan to create my own once I get this one working. 

### Reproduction Steps
Create workspace with the following: 

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer $token' -d '{
  "environments": {
    "default": {
      "machines": {
        "app/gols": {
          "attributes": {
            "memoryLimitBytes": "2147483648"
          },
          "servers": {
            "gols": {
              "attributes": {
                "languageRegexes": "[ {\"languageId\":\"golang\", \"regex\":\".*\\\\.go$\"}]",
                "internal": "true",
                "id": "go-ls",
                "type": "ls"
              },
              "port": "5555",
              "protocol": "tcp"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {
            "CHE_MACHINE_NAME": "app/gols"
          }
        },
        "app/dev-machine": {
          "attributes": {
            "memoryLimitBytes": "2147483648"
          },
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.terminal",
            "org.eclipse.che.exec",
            "org.eclipse.che.ws-agent"
          ],
          "env": {
            "CHE_MACHINE_NAME": "app/dev-machine"
          }
        }
      },
      "recipe": {
        "type": "kubernetes",
        "content": "kind: List\nitems:\n - \n  kind: Service\n  apiVersion: v1\n  metadata:\n   name: gols-test\n  spec:\n   selector:\n    name: app\n   ports:\n    - \n     protocol: TCP\n     port: 5555\n     targetPort: 5555\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: app\n  spec:\n   containers:\n    - \n     image: eivantsov/go-lang\n     name: gols\n     ports:\n      - \n       containerPort: 5555\n       protocol: TCP\n     resources:\n      limits:\n       memory: 2048Mi\n    - \n     image: \u0027eclipse/ubuntu_jdk8:latest\u0027\n     name: dev-machine\n     resources:\n      limits:\n       memory: 2048Mi\n",
        "contentType": "text/x-yaml"
      }
    }
  },
  "defaultEnv": "default",
  "projects": [

  ],
  "name": "foobar",
  "commands": [],
  "links": []
}' 'http://che-host/api/workspace/runtime?temporary=false'
```

Step 2: Go to http://che-host/dashboard/#/ide/admin/foobar
Step 3: Create foo.go
This causes the "Initializing Language server for foo.go" dialogue to appear

Step 4: Get this error in the console:

```
2018-07-11 20:24:23,859[rverInitializer]  [ERROR] [.l.SocketCommunicationProvider 108]  - Can't establish socket connection for: serverec2mniy2-app-gols:5555
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:211)
	at org.eclipse.che.api.languageserver.SocketCommunicationProvider.getStatusChecker(SocketCommunicationProvider.java:90)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.initializeIOStreams(LanguageServerInitializer.java:155)
	at org.eclipse.che.api.languageserver.SocketCommunicationProvider.establishSocketConnectionLazily(SocketCommunicationProvider.java:101)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.initializeIOStreams(LanguageServerInitializer.java:155)
org.eclipse.che.api.languageserver.LanguageServerException: Can't establish socket connection for: serverec2mniy2-app-gols:5555
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.lambda$initialize$0(LanguageServerInitializer.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2018-07-11 20:24:23,860[rverInitializer]  [ERROR] [.a.l.LanguageServerInitializer 167]  - Can't initialize IO streams for 'go-ls'
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.eclipse.che.api.languageserver.SocketCommunicationProvider.establishSocketConnectionLazily(SocketCommunicationProvider.java:101)
	... 15 common frames omitted
2018-07-11 20:24:23,861[rverInitializer]  [INFO ] [.a.l.LanguageServerInitializer 128]  - Finished language servers initialization, file path '/projects/asdf.go'
	at java.net.Socket.connect(Socket.java:538)
	at org.eclipse.che.api.languageserver.SocketCommunicationProvider.getStatusChecker(SocketCommunicationProvider.java:90)
2018-07-11 20:24:23,861[rverInitializer]  [ERROR] [.a.l.LanguageServerInitializer 133]  - Could not initialize any server for '/projects/asdf.go'
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.lambda$initialize$0(LanguageServerInitializer.java:126)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at org.eclipse.che.api.languageserver.SocketCommunicationProvider.establishSocketConnectionLazily(SocketCommunicationProvider.java:109)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
```

Any help would be greatly appreciated!

**Comment by eivantsov** [comment]
@Jimmyscene thanks for using my image :)

It does look like a networking problem - service isn't available from within a container, when containers are in one pod.

Can you perhaps give it a shot with a recipe that has 2 pods, rather than 1 pod with containers?

**Comment by Jimmyscene** [comment]
Thanks again for your help! Is there a pre-packaged recipe with two pods I can use?

**Comment by eivantsov** [comment]
I think I have smth in one of the gists. I'll post it as soon as I find it.
