### ISSUE TITLE
FileAlreadyExistsExceptio when using SimpleJava Test Projects

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10388]
Selenium Tests using simple Java projects sometimes fail with the following exception:

java.nio.file.FileAlreadyExistsException: /home/codenvy/workspace/che-integration-tests-jdt-ls-docker/selenium/che-selenium-test/target/test-classes/projects/simple-java-project/.project
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at org.eclipse.che.selenium.core.client.TestProjectServiceClient.importProject(TestProjectServiceClient.java:146)
	at org.eclipse.che.selenium.plainjava.PlainJavaProjectConfigureClasspathTest.prepare(PlainJavaProjectConfigureClasspathTest.java:70)
<snip>

**Comment by tsmaeder** [comment]
To me it looks as if the file creation fails when the same project has been used in a different test in the same run and a .project file has already been created.
