### ISSUE TITLE
Docker mounting error when creating workspace

### ISSUE THREAD

**Issue by andrewsosa** [eclipse-che/che#10473]
### Description
The machine I'm running on has [restricted permissions in the `/home` directory](https://github.com/eclipse/che/issues/10473#issuecomment-405955844) (even for `root`). So when creating a workspace, the Che server presumably tries to mount `/home/user/eclipse-che/lib/linux_amd64/exec`, but encounters `mkdir /home/user: permission denied` (full log at below). 

Since I'm unable to grant permission to the `/home/user...`, I'd like to configure Che try mounting somewhere else. Does such a config exist? I've been reading the Che docs and Github issues for the past day and a half looking for potential solutions. 

I saw that `/home/user/eclipse-che` is the `che.home` path, but it looks like setting this via a `CHE_HOME` Docker env may have been removed, alluded to [here](https://github.com/eclipse/che/pull/2817). It also looks like moving `che.home` may have further ramifications. 

### Reproduction Steps
1. Run the `eclipse/che` Docker image successfully.
2. Disable root permissions in `/home` 
    * This one might be a bit of a conundrum -- Docker normally runs with `root` permissions, so it _should_ always be capable of this, as `root` should always be capable of anything. However, this is _not_ the case on my system. 
3. Try creating a workspace (presumably with a new machine). 

**OS and version:**    
RHEL 7, Eclipse Che 6.8.0, Docker version 18.03.1-ce. 

**Diagnostics:** 
Logs from within the workspace: 
```
[DOCKER] latest: Pulling from eclipse/ubuntu_python 
[DOCKER] Digest: sha256:dc2c37e60afc90530a6fbf5c4294d541d673614b8b316de8d9a1ed8b07729f62 
[DOCKER] Status: Image is up to date for eclipse/ubuntu_python:latest 
Error response from docker API, status: 500, message: error while creating mount source path '/home/user/eclipse-che/lib/linux_amd64/exec': mkdir /home/user: permission denied
```

Logs from `docker logs -f che`:
```
2018-07-18 13:25:49,729[nio-8080-exec-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 329]   - Starting workspace 'andrewsosa/wksp-u49k' with id 'workspaceuy7xkdo759s0a39t' by user 'andrewsosa'
2018-07-18 13:25:52,511[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 390]   - Workspace 'andrewsosa:wksp-u49k' with id 'workspaceuy7xkdo759s0a39t' start failed
2018-07-18 13:25:52,512[aceSharedPool-2]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 400]   - Error response from docker API, status: 500, message: error while creating mount source path '/home/user/eclipse-che/lib/linux_amd64/exec': mkdir /home/user: permission denied

org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Error response from docker API, status: 500, message: error while creating mount source path '/home/user/eclipse-che/lib/linux_amd64/exec': mkdir /home/user: permission denied

        at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.startContainer(DockerMachineStarter.java:215)
        at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.startMachine(DockerInternalRuntime.java:318)
        at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.internalStart(DockerInternalRuntime.java:220)
        at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:145)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:366)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:37)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.infrastructure.docker.client.exception.DockerException: Error response from docker API, status: 500, message: error while creating mount source path '/home/user/eclipse-che/lib/linux_amd64/exec': mkdir /home/user: permission denied

        at org.eclipse.che.infrastructure.docker.client.DockerConnector.getDockerException(DockerConnector.java:1528)
        at org.eclipse.che.infrastructure.docker.client.DockerConnector.startContainer(DockerConnector.java:1208)
        at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.startContainer(DockerMachineStarter.java:197)
        ... 9 common frames omitted
```

### Summary
Due to machine restrictions, Docker/`root` lacks permissions to create `/home/user/eclipse-che` and subdirs. I also probably will not be able to pre-create these directories. 

Are there configuration options which will let Docker mount this workspace volume somewhere else?

**Comment by eivantsov** [comment]
@andrewsosa `/home/user/eclipse-che/lib/linux_amd64/terminal` is a path in Che server container, and when a workspace starts it's mounted into workspace container.

I suspect it might be some RHEL security restrictions. What's your Docker version?

**Comment by andrewsosa** [comment]
I'm running Docker version 18.03.1-ce, build 9ee9f40.

Part of the issue is that this machine is attached to a corporate network, and IT has linked /home to be part of an LDAP configuration. Based off of ongoing discussions, it's possible we will not be given permissions to /home. 

I had figured that the reason Docker was throwing that error was because it's trying to use the on-disk `/home/user/eclipse-che` as a volume, which I was trying to configure to be elsewhere, perhaps `/usr/local/home/user/eclipse-che`.

**Comment by eivantsov** [comment]
@andrewsosa yes, `/home/user/eclipse-che` is created on a host machine when a ws starts - and I don't remember why we do that.

@garagatyi may remember. I suspect that might be some legacy code that is not necessary. May be mistaken though

**Comment by garagatyi** [comment]
Sorry, but I don't remember either

**Comment by andrewsosa** [comment]
@eivantsov @garagatyi Thanks for both of your help so far. Is there a config option to change the prefix to that mount path? Instead of `/home/user`, maybe `/usr/local/home/user`?

**Comment by stoddarn** [comment]
@andrewsosa I'm seeing the same issue "mkdir /home/user: permission denied."  Did you find a solution?  My /home is LDAP backed too, so I cannot create a /home/user on my host machine.  I tried to mount -v /opt/home/user:/home/user, but it did not work.

@eivantsov, does your statement mean that the creation of /home/user/* on the host machine is hardcoded and cannot be configured in the eclipse-che docker run command? 

Thanks for the help.

**Comment by skabashnyuk** [comment]
@benoitf you author of this https://github.com/eclipse/che/blob/master/dockerfiles/che/entrypoint.sh#L220-L226 part
may be you can help?

**Comment by eivantsov** [comment]
It doesn't seem to be related. I seriously don't understand why this mount happens anyway.

**Comment by skabashnyuk** [comment]
@eivantsov  you probably right, it's more about ws-agent and my link was about ws-master

**Comment by stoddarn** [comment]
@eivantsov  I found some comments in `infrastructure/docker/local/installer/WsAgentBinariesInfrastructureProvisioner.java` that seemed to apply for Windows.  

"On Windows MUST be locate in "user.home" directory in case limitation windows+docker."


@garagatyi  Is the same logic being applied for Linux?  Is that why /home/user/... is created instead of using one of the volume mounts that were defined with the CHE docker run?

**Comment by stoddarn** [comment]
A few other data points for things I've tried.

1. Add a "user" to local /etc/passwd and set it's home to /opt/home/user.  It appears the Eclipse CHE does not pull in the /etc/passwd file by default.  I still received the error as ws-agent attempted to write to /home/user/...

2a. Set the `-e CHE_USER=2018:2018` argument in the docker run command.  (2018 this is the id and group for the "user" account in /etc/passwd). At this point Eclipse CHE does appear to use the /etc/passwd file; however, I get a sudo failure and the che docker container will not start.    (error in the docker log:  "sudo: no tty present and no askpass program specified")

2b.  I updated my local /etc/sudoers file to include "user    ALL=(ALL)       NOPASSWD: ALL"; however that didn't help.

**Comment by eivantsov** [comment]
@stoddarn Windows comment makes sense for boot2docker where only user home is mounted in VM. When that code was written Docker for Windows wasn't there yet.

I will try to find some time next week to figure out why an unnecessary (I don't see how it's being used) mount is required anyway.

**Comment by eivantsov** [comment]
@garagatyi it looks like things in here https://github.com/eclipse/che/tree/master/infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/local/installer aren't used at all. 

As far as I remember we used to mount agents binaries into /mnt of a workspace container. Now, with the bootstrapper mechanism, bootstrapper binary is copied from Che server container, and then it downloads binaries of other agents served by Che itself.

As a result, such mounts are created, and Docker attempts to create non existing host dirs as root. It works fine if host /home dir is writable.

Do you think it's safe to remove that code, as well as remove things like this https://github.com/eclipse/che/blob/15d23edc91497c489c7e0ac4c15f8a41177b7167/agents/exec/installer/src/main/resources/installers/1.0.1/org.eclipse.che.exec.script.sh#L41 from installer scripts?

**Comment by garagatyi** [comment]
@eivantsov it is used in `LocalDockerModule`. I don't know whether it is safe to remove these parts and what it might break.

**Comment by andrewsosa** [comment]
@stoddarn sorry for the late response -- we went back and forth with our IT group for about a week and they finally found a solution which would create the folder. Unfortunately they did not share the details of the solution with me; ultimately it was not something I was able to solve on my own.

**Comment by stoddarn** [comment]
@andrewsosa I think I understand.  You had your IT staff create a /home/user account in LDAP (or at least the directory in the autofs/NFS mount) as a workaround?  If so, I don't believe that would be valid for my network.

@eivantsov should this issue's label be switched from kind/question to kind/bug?   IMHO it seems like if we must put files on the host, then being able to specify an alternative location (like we do for mounting the /data location) would be needed.

**Comment by unicman** [comment]
I'm also facing this issue when running eclipse che as docker container by following steps @ https://www.eclipse.org/che/docs/quick-start.html i.e. `docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /local/path:/data eclipse/che start`.

**Comment by unicman** [comment]
Agree with @stoddarn that this should be kind/bug because it is quite obvious that `/home/user` exists only inside `che` docker container and it won't be present in docker host.

**Comment by giangiangian** [comment]
I have the same issue; I am in an environment with more than 100 machines, and I need each one of them to host a single user docker instance of Eclipse Che. The /home/ directory, however, is an NFS mount, and therefore I am unable to start a workspace container for the same exact reason (and, anyway, I don't think it would be a good idea to share the same directory on 100+ different instances of Che).

Does anyone have a workaround which may be usable for my scenario? I currently am investigating on using docker-machine and a Virtualbox for each machine, however it overcomplicates the setup, and forces me to re-write from scracth many scripts for automated workspace creation and configuration.

**Comment by gorkem** [comment]
Closing due to inactivity
