### ISSUE TITLE
Che fails on hover if Language Server returns Hover object with null contents

### ISSUE THREAD

**Issue by philcolol** [eclipse-che/che#10480]
### Description
If LS returns Hover with empty list inside contents, everything works fine. 
But if it returns null inside contents field, Che fails with exception.
Is this intended behavioour?

**OS and version:**    
OS: Win10
Che: 6.6

**Diagnostics:** 
`2018-07-19 09:12:57,168[ool-10-thread-1]  [INFO ] [o.e.c.a.l.util.OperationUtil 90]     - Exception occurred in request
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$request$1(RemoteEndpoint.java:123)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:149)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:162)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at org.eclipse.che.api.languageserver.TextDocumentService$6.handleResult(TextDocumentService.java:407)
	at org.eclipse.che.api.languageserver.TextDocumentService$6.handleResult(TextDocumentService.java:391)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at java.util.ArrayList.addAll(ArrayList.java:581)
	... 14 common frames omitted
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at org.eclipse.che.api.languageserver.util.OperationUtil.lambda$doInParallel$0(OperationUtil.java:82)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
`

**Comment by eivantsov** [comment]
@philcolol what language server is in question and what would be steps to reproduce? Thank you

**Comment by philcolol** [comment]
Any language server, that returns Hover with null contents. We reproduced this on our custom LS. I created a simple example of such LS: https://github.com/philcolol/ls-examples
Steps:
1. launch che with LS-example
2. open file
3. hover on any word below line 100

**Comment by tsmaeder** [comment]
I suspect this has been fixed by updating lsp4j to 5.0
