### ISSUE TITLE
Certificates are required for https connection.

### ISSUE THREAD

**Issue by village-way** [eclipse-che/che#10507]
### Description
start tomcat by startup.sh with this errors

2018-07-23 17:55:57,747[ost-startStop-1]  [WARN ] [o.e.c.a.w.s.WorkspaceRuntimes 543]   - Not recoverable infrastructure: 'docker'
2018-07-23 17:55:57,834[ost-startStop-1]  [INFO ] [.c.i.d.c.DockerRegistryChecker 48]   - Probing registry 'http://hihop.top:5000'
2018-07-23 17:55:58,420[ost-startStop-1]  [INFO ] [.c.i.d.c.DockerRegistryChecker 53]   - Probe of registry 'http://hihop.top:5000' succeed with HTTP response code '200'
2018-07-23 17:55:58,439[ted-scheduler-0]  [ERROR] [ockerAbandonedResourcesCleaner 119]  - Failed to clean up inactive containers
java.lang.IllegalArgumentException: Certificates are required for https connection.
	at org.eclipse.che.infrastructure.docker.client.connection.TcpConnection.<init>(TcpConnection.java:40)
	at org.eclipse.che.infrastructure.docker.client.connection.DockerConnectionFactory.openConnection(DockerConnectionFactory.java:51)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.listContainers(DockerConnector.java:272)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.listContainers(DockerConnector.java:259)
	at org.eclipse.che.workspace.infrastructure.docker.monit.DockerAbandonedResourcesCleaner.cleanContainers(DockerAbandonedResourcesCleaner.java:90)
	at org.eclipse.che.workspace.infrastructure.docker.monit.DockerAbandonedResourcesCleaner.run(DockerAbandonedResourcesCleaner.java:81)
	at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-23 17:55:58,440[ted-scheduler-0]  [INFO ] [ockerAbandonedResourcesCleaner 121]  - List containers registered in the api: []
2018-07-23 17:55:58,440[ted-scheduler-0]  [ERROR] [o.e.c.c.s.e.LoggedRunnable 69]       - Certificates are required for https connection.
java.lang.IllegalArgumentException: Certificates are required for https connection.
	at org.eclipse.che.infrastructure.docker.client.connection.TcpConnection.<init>(TcpConnection.java:40)
	at org.eclipse.che.infrastructure.docker.client.connection.DockerConnectionFactory.openConnection(DockerConnectionFactory.java:51)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.getNetworks(DockerConnector.java:1238)
	at org.eclipse.che.workspace.infrastructure.docker.monit.DockerAbandonedResourcesCleaner.cleanNetworks(DockerAbandonedResourcesCleaner.java:176)
	at org.eclipse.che.workspace.infrastructure.docker.monit.DockerAbandonedResourcesCleaner.run(DockerAbandonedResourcesCleaner.java:82)
	at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-23 17:55:58,456[eStopDetector-0]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread DockerMachineStopDetector-0. Message: Certificates are required for https connection.
java.lang.IllegalArgumentException: Certificates are required for https connection.
	at org.eclipse.che.infrastructure.docker.client.connection.TcpConnection.<init>(TcpConnection.java:40)
	at org.eclipse.che.infrastructure.docker.client.connection.DockerConnectionFactory.openConnection(DockerConnectionFactory.java:51)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.getEvents(DockerConnector.java:777)
	at org.eclipse.che.workspace.infrastructure.docker.monit.DockerMachineStopDetector.lambda$detectContainersEvents$0(DockerMachineStopDetector.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Reproduction Steps
1. mvn clean install assembly-main
2. set env for che in the ~/.bash_profile
export CHE_PORT=8080
export CHE_REGISTRY_HOST=localhost
export CHE_HOME=/Volumes/Data/IdeaProjects/che/assembly/assembly-main/target/eclipse-che-6.9.0-SNAPSHOT/eclipse-che-6.9.0-SNAPSHOT
export CHE_HOST=localhost
3. execute targer/tomcat/bin/startup.sh
4. use local docker registry, just run 
`docker run -d --name registry --restart=always -p 5000:5000 registry:2`

**OS and version:**    
OS: Mac OS X 10.12.6
JAVA:  1.8.0_144-b01
GO: 10.0
MAVEN: 3.5

**Diagnostics:** 
even if can visit http://localhost:8080/dashboard  http://localhost:8080/api  http://localhost:8080/swagger/
but can not create workspaces

![image](https://user-images.githubusercontent.com/11625846/43070807-5bd9d628-8ea3-11e8-826f-cdb383b5fee8.png)

**Comment by eivantsov** [comment]
@HiDevine this is not how you are supposed to start Che. Please use syntax from documentation.

**Comment by HiDevine** [comment]
@eivantsov thank very much for your answer. now start che build from dockerfile.
but now stuck on an problem, here is the docker logs 
 [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 400]   - Error response from docker API, status: 400, message: create <no value>/workspaces/workspacewazertorxtfh7m7o: "<no value>/workspaces/workspacewazertorxtfh7m7o" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path 

what i do this the follow steps
1. `mvn clean install`   in assembyl-main
2. `./build.sh` in dockerfiles/che
3. `docker run -d -p 5000:5000 --name registry -v registry:2` to create private registry
3. `docker run -it -p 8080:8080 -p 8000:8000 -e CHE_HOST=localhost -e CHE_REGISTRY_HOST=172.20.30.216 -v /var/run/docker.sock:/var/run/docker.sock  eclipse/che-server:nightly` after build docker images successful, 172.20.30.216 is my mac os intent ip

i almost create workspace successful(in the loading page i can see the logs information flow), but this problem stuck me, i really do not know how to solve this, even if see the documentation and issues.

**Comment by HiDevine** [comment]
@eivantsov i have solved this problem by add mount local data path. just modify docker run,
`docker run -it -p 8080:8080 -e CHE_HOST=localhost -e CHE_REGISTRY_HOST=172.20.30.216 -v /var/run/docker.sock:/var/run/docker.sock -v /Users/devine/Downloads/che-data:/data  eclipse/che-server:nightly`
after created workspace, there still some error info in the console
such as 

`Machine `db` error from owner=`che` env=`default` workspace=`workspaces6tmx1x0mwvxt7sz` text=`2018-07-25T03:21:23.685680Z 0 [Note] End of list of non-natively partitioned tables` time=`2018-07-25T03:21:23.69Z`

` Machine `db` error from owner=`che` env=`default` workspace=`workspaces6tmx1x0mwvxt7sz` text=`2018-07-25T03:21:23.685680Z 0 [Note] End of list of non-natively partitioned tables` time=`2018-07-25T03:21:23.69Z`

`Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspaces6tmx1x0mwvxt7sz` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-07-25T03:21:34.328914484Z`

**Comment by eivantsov** [comment]
@HiDevine you may disregard this error. it does not affect anything.

**Comment by HiDevine** [comment]
@eivantsov thanks for you reply.
