### ISSUE TITLE
can not start up tomcat after build assembly-main module

### ISSUE THREAD

**Issue by village-way** [eclipse-che/che#10505]
### Description
after git clone the source code from github, i use `mvn clean install` in the assembly-main directory.
and execute startup.sh in the tomcat/bin directory, but tomcat failed to start up.
even if i read the doc of eclipse che , i stil can not get out how to build and run the project successful.
i have stuck this problem for one week, i really need your help thank you.

here is the logs (tomcat/logs/catalina.out)

2018-07-23 10:39:57,508[main]             [WARN ] [o.a.t.util.digester.Digester 69]     - [Se
2018-07-23 10:39:58,041[ina-startStop-1]  [ERROR] [o.a.c.core.ContainerBase 941]        - A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/agent-binaries]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/agent-binaries]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... 6 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@70144147]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4860)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4995)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 common frames omitted
Caused by: java.lang.IllegalArgumentException: The main resource set specified [/root/che/target/eclipse-che-6.8.0/eclipse-che-6.8.0/tomcat/webapps/${che.home}/lib] is not valid
	at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:749)
	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:706)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 9 common frames omitted
2018-07-23 10:39:58,041[main]             [ERROR] [o.a.c.core.ContainerBase 941]        - A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:670)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:948)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 common frames omitted
2018-07-23 10:39:58,042[main]             [ERROR] [o.a.catalina.startup.Catalina 672]   - The required Server component failed to start so Tomcat is unable to start.
org.apache.catalina.LifecycleException: Failed to start component [StandardServer[8005]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:670)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Catalina]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 7 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 9 common frames omitted
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:948)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 11 common frames omitted

### Reproduction Steps
1. git clone source code from github.com
2. cd project directory assembly/assembly-main
3. execute mvn clean install
4. cd target/eclipse-che-version/eclipse-che-version/tomcat/bin and execute startup.sh

**OS and version:**    
Apache Maven 3.5.0
Java version: 1.8.0_144,
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
go version go1.10.3 darwin/amd64

**Diagnostics:** 
even if execute setenv.sh and configtest.sh, i still get the error in the logs directory

but after i change tomcat/server.xml ${http.port} and ${che.home} with the 8080 and che home directory, i can start up tomcat ,how ever visit localhost:8080 can not show out the dashboard.

the logs in 

2018-07-23 11:40:03,868[ost-startStop-1]  [INFO ] [com.google.inject.Guice 42]          - An exception was caught and reported. Message: org.eclipse.che.inject.ConfigurationException: Property CHE_PORT is not found as system property or environment variable.
org.eclipse.che.inject.ConfigurationException: Property CHE_PORT is not found as system property or environment variable.
	at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:421)
	at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:386)
	at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:374)
	at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindConf(CheBootstrap.java:366)
	at org.eclipse.che.inject.CheBootstrap$WebInfConfiguration.configure(CheBootstrap.java:226)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-23 11:40:06,368[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4752] - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=che.auth.user_self_creation) was bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=che.auth.user_self_creation)
    for the 5th parameter of org.eclipse.che.api.user.server.UserService.<init>(UserService.java:76)
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:140)

2) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=che.docker.privileged) was bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=che.docker.privileged)
    for the 1st parameter of org.eclipse.che.workspace.infrastructure.docker.provisioner.priviliged.PrivilegedModeProvisioner.<init>(PrivilegedModeProvisioner.java:29)
  at org.eclipse.che.workspace.infrastructure.docker.DockerInfraModule.configure(DockerInfraModule.java:58) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> org.eclipse.che.workspace.infrastructure.docker.DockerInfraModule)

3) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=che.predefined.stacks.reload_on_start) was bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=che.predefined.stacks.reload_on_start)
    for the 1st parameter of org.eclipse.che.api.workspace.server.stack.StackLoader.<init>(StackLoader.java:71)
  at org.eclipse.che.api.deploy.WsMasterModule.configureSingleUserMode(WsMasterModule.java:272)
[catalina.TXT](https://github.com/eclipse/che/files/2217954/catalina.TXT)

**Comment by HiDevine** [comment]
i have solved this problem by set CHE_HOME CHE_PORT CHE_HOST CHE_REGISTRY_HOST in the ~/.bash_profile
also i update setenv.sh file with 
`[ -z "${JAVA_OPTS}" ]  && JAVA_OPTS="-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom -Dche.home=${CHE_HOME} -Dport.http=${CHE_PORT}"`
