### ISSUE TITLE
Unexpected error message in browser console after 'Close All' tabs in the Editor action

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10555]
**Reproduction Steps:**

1. Create workspace from the **Java** stack with any project.
2. Open any two or more files.
3. Close these files by "**Close All**" action in the **Editor** tab context menu.

**Expected behavior:** 
Open file tabs are closed
 
**Observed behavior:**
Open file tabs are closed but there is an error message in the browser console:
``` 
_app-0.js:2244 Thu Jul 26 16:45:31 GMT+300 2018 com.google.gwt.logging.client.LogConfiguration
SEVERE: (TypeError) : Cannot read property 'getLineCount' of null
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'getLineCount' of null
	at Unknown.mjh(OrionTextViewOverlay.java:46)
	at Unknown.Wkh(OrionEditorPresenter.java:608)
	at Unknown.ht(SchedulerImpl.java:50)
	at Unknown.$s(SchedulerImpl.java:347)
	at Unknown.lt(SchedulerImpl.java:78)
	at Unknown.ft(SchedulerImpl.java:141)
	at Unknown.Ks(Impl.java:309)
	at Unknown.Ns(Impl.java:361)
	at Unknown.anonymous(Impl.java:78)
	at Unknown.ME(StringValidator.java:66)
	at Unknown.LE(StringValidator.java:49)
	at Unknown.xE(RequestBuilder.java:292)
```
 
**Che version**: 6.9.0
**OS and version:** Fedora 28
**Che install:** DOCKER-single

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_056](https://user-images.githubusercontent.com/7760565/43265824-8efd1622-90f2-11e8-8681-bcc2674305a3.png)

**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 07 26-16-45-42](https://user-images.githubusercontent.com/7760565/43266220-7fec8c52-90f3-11e8-98d4-6825e135eada.gif)

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
