### ISSUE TITLE
Stack configuration for ARM (RP3)

### ISSUE THREAD

**Issue by gdanjou** [eclipse-che/che#10565]
Hello,

I would like to run a debian / ubuntu stack on my raspberry pi 3 but i don't find any stack exemple on INTERNET.

Can someone can give me a exemple of a working stack definition for RP3 ?

(My goal is to use eclipse che with the RUST Lang)

PS : I have followed this tutorial : https://blogs.eclipse.org/post/benjamin-cab%C3%A9/running-eclipse-che-raspberry-pi but its not working :'(

Exemple : 

> 2018-07-27 21:15:36,929[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 638]    - org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error occurs while initializing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-8.pid ] && rm /tmp/docker-exec-8.pid' EXIT; echo $$>/tmp/docker-exec-8.pid; command -v pidof >/dev/null 2>&1 && {
>     pidof che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> } || {
>     ps -fC che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> }] in docker container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c: Error response from docker API, status: 409, message: Container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c is not running
> 
> java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error occurs while initializing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-8.pid ] && rm /tmp/docker-exec-8.pid' EXIT; echo $$>/tmp/docker-exec-8.pid; command -v pidof >/dev/null 2>&1 && {
>     pidof che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> } || {
>     ps -fC che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> }] in docker container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c: Error response from docker API, status: 409, message: Container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c is not running
> 
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_65]
>         at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_65]
>         at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$startAsync$1(WorkspaceManager.java:623) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
>         at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.0.jar:5.0.0]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65]
>         at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
> Caused by: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error occurs while initializing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-8.pid ] && rm /tmp/docker-exec-8.pid' EXIT; echo $$>/tmp/docker-exec-8.pid; command -v pidof >/dev/null 2>&1 && {
>     pidof che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> } || {
>     ps -fC che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> }] in docker container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c: Error response from docker API, status: 409, message: Container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c is not running
> 
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:705) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:249) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
>         at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0.jar:5.0.0]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_65]
>         ... 3 common frames omitted
> Caused by: org.eclipse.che.api.core.ServerException: Error occurs while initializing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-8.pid ] && rm /tmp/docker-exec-8.pid' EXIT; echo $$>/tmp/docker-exec-8.pid; command -v pidof >/dev/null 2>&1 && {
>     pidof che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> } || {
>     ps -fC che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1
> }] in docker container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c: Error response from docker API, status: 409, message: Container cf14fe45410c710903ac19935ea4ace17164273b3019510ffd8b61be7c49330c is not running
> 
>         at org.eclipse.che.api.agent.server.launcher.AbstractAgentLauncher.launch(AbstractAgentLauncher.java:89) ~[che-core-api-agent-5.0.0.jar:5.0.0]
>         at org.eclipse.che.api.workspace.server.launcher.TerminalAgentLauncherImpl.launch(TerminalAgentLauncherImpl.java:49) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:633) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:716) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:674) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
>         ... 6 common frames omitted

The stack configuration : 

```
{
  "tags": [],
  "creator": "che",
  "workspaceConfig": {
    "commands": [],
    "projects": [],
    "defaultEnv": "default",
    "environments": {
      "default": {
        "recipe": {
          "contentType": "application/x-yaml",
          "type": "compose",
          "content": "services:\n dev-machine:\n  image: armhf/debian\n"
        },
        "machines": {
          "dev-machine": {
            "agents": [
              "org.eclipse.che.terminal",
              "org.eclipse.che.ws-agent",
              "org.eclipse.che.ssh"
            ],
            "servers": {},
            "attributes": {
              "memoryLimitBytes": "2147483648"
            }
          }
        }
      }
    },
    "name": "default",
    "links": []
  },
  "components": [],
  "scope": "general",
  "name": "Debian ARM",
  "id": "stack4g3hcerii6904cdb",
  "source": {
    "origin": "armhf/debian",
    "type": "image"
  },
  "description": "Debian ARM"
}
```

Thanks a lot for helping.

**Comment by eivantsov** [comment]
@mmorhun has recently experimented with Che stacks on ARM.

**Comment by gorkem** [comment]
Closing due to inactivity
