### ISSUE TITLE
Cannot import project by 'Import From Che Config...' feature

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10601]
**Reproduction Steps:**

1. Create and start workspace from the **Java** stack.
2. Import project from che config by menu **Project** -> **Import From Che Config...**
3. Click on **Choose File** button and select file with config like:
```
   {
      "source": {
        "location": "https://github.com/che-samples/web-java-spring.git",
        "type": "git",
        "parameters": {}
      },
      "description": "A basic example using Spring servlets. The app returns values entered into a submit form.",
      "links": [],
      "problems": [],
      "mixins": [],
      "name": "web-java-spring-1",
      "type": "maven",
      "path": "/web-java-spring-1",
      "attributes": {}
    }
```
4. Click on **Import** button

**Expected behavior:** 
The project imported and visible in the Project Explorer.
 
**Observed behavior:**
The project was not imported. There is '**Configuring project and cloning source code.**'event  in the **Events log** and an error message in the browser console:
``` 
Tue Jul 31 17:04:33 GMT+300 2018 com.google.gwt.logging.client.LogConfiguration
SEVERE: Exception caught: (TypeError) : Cannot read property 'f' of undefined
com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'f' of undefined
	at Unknown.Hr(Throwable.java:73)
	at Unknown.Qr(Exception.java:33)
	at Unknown.Ur(RuntimeException.java:33)
	at Unknown.gE(UmbrellaException.java:65)
	at Unknown.iE(UmbrellaException.java:26)
	at Unknown.ID(HandlerManager.java:129)
	at Unknown.Lzd(Widget.java:129)
	at Unknown.Wzd(Widget.java:127)
	at Unknown.QA(DomEvent.java:125)
	at Unknown.Nzd(Widget.java:177)
	at Unknown.Zzd(Widget.java:163)
	at Unknown.PId(DOM.java:1481)
	at Unknown.sKd(DOMImplStandard.java:317)
	at Unknown.Ks(Impl.java:309)
	at Unknown.Ns(Impl.java:361)
	at Unknown.anonymous(Impl.java:78)
	at Unknown.ME(StringValidator.java:66)
	at Unknown.LE(StringValidator.java:49)
	at Unknown.xE(RequestBuilder.java:292)
	at Unknown.W_k(AsyncRequest.java:72)
	at Unknown.$_k(MachineAsyncRequestFactory.java:129)
	at Unknown.anonymous(JsPromise.java:116)
	at Unknown.j(ImportFromConfigViewImpl.java:111)
	at Unknown.ME(StringValidator.java:66)
	at Unknown.LE(StringValidator.java:49)
	at Unknown.xE(RequestBuilder.java:292)
	at Unknown.W_k(AsyncRequest.java:72)
	at Unknown.$_k(MachineAsyncRequestFactory.java:129)
	at Unknown.anonymous(JsPromise.java:116)
	at Unknown.FD(EventBus.java:69)
```
 
**Che version**: 6.9.0
**OS and version:** Fedora 28
**Che install:** DOCKER-single

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_067](https://user-images.githubusercontent.com/7760565/43466087-6ae05936-94e7-11e8-916c-1d9d102ae7e4.png)

**Screencast:**
![screencast-172 19 20 234-8080-2018 07 31-17-18-39](https://user-images.githubusercontent.com/7760565/43465429-04822bf2-94e6-11e8-9b4a-d5f95471914b.gif)

**Comment by musienko-maxim** [comment]
duplicated
