### ISSUE TITLE
Error When Building Che in Che from tutroial

### ISSUE THREAD

**Issue by jdflemin** [eclipse-che/che#10664]
### Description
Started off having the same issue as in issue #10519 

Today I tried again and now a new problem has came up that I am not sure how to start to resolve. I follow the steps in https://www.eclipse.org/che/docs/che-in-che-quickstart.html and when I run `Deploy IDE` and `Deploy Workspace Agent` I get the below errors while compiling. 

### Reproduction Steps
I followed the steps in the tutorial mentioned above for creating a new workspace and upon selecting `Deploy IDE` or `Deploy Workspace Agent`.

**Error in console:** 
`[INFO] [1m------------------------------------------------------------------------[m`
`[INFO] [1mBuilding Plugin ServerService :: Che Assembly :: IDE Assembly 6.10.0-SNAPSHOT[m`
`[INFO] [1m------------------------------------------------------------------------[m`
`[WARNING] The POM for org.eclipse.che.core:che-core-dynamodule-maven-plugin:jar:6.10.0-SNAPSHOT is missing, no dependency information available`
`[INFO] [1m------------------------------------------------------------------------[m`
`[INFO] [1mReactor Summary:[m`
`[INFO] `
`[INFO] Plugin ServerService :: Parent pom ................. [1;32mSUCCESS[m [ 17.031 s]`
`[INFO] Plugin ServerService :: Plugins ::  Parent ......... [1;32mSUCCESS[m [  0.034 s]`
`[INFO] Plugin ServerService :: Plugin :: Parent ........... [1;32mSUCCESS[m [  1.126 s]`
`[INFO] Plugin ServerService :: Plugin :: IDE .............. [1;32mSUCCESS[m [ 16.307 s]`
`[INFO] Plugin ServerService :: Che Assembly :: Assembly Parent [1;32mSUCCESS[m [  0.083 s]`
`[INFO] Plugin ServerService :: Che Assembly :: IDE Assembly [1;31mFAILURE[m [  0.008 s]`
`[INFO] [1m------------------------------------------------------------------------[m`
`[INFO] [1;31mBUILD FAILURE[m`
`[INFO] [1m------------------------------------------------------------------------[m`
`[INFO] Total time: 36.768 s`
`[INFO] Finished at: 2018-08-03T16:42:28Z`
`[INFO] Final Memory: 44M/90M`
`[INFO] [1m------------------------------------------------------------------------[m`
`[ERROR] Plugin org.eclipse.che.core:che-core-dynamodule-maven-plugin:6.10.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.che.core:che-core-dynamodule-maven-plugin:jar:6.10.0-SNAPSHOT -> [1m[Help 1][m`
`[ERROR] `
`[ERROR] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.`
`[ERROR] Re-run Maven using the [1m-X[m switch to enable full debug logging.`
`[ERROR]` 
`[ERROR] For more information about the errors and possible solutions, please read the following articles:`
`[ERROR] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException`

**Error in console - full stack trace:**
`[ERROR] Plugin org.eclipse.che.core:che-core-dynamodule-maven-plugin:6.10.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.che.core:che-core-dynamodule-maven-plugin:jar:6.10.0-SNAPSHOT -> [1m[Help 1][m
org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.che.core:che-core-dynamodule-maven-plugin:6.10.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.che.core:che-core-dynamodule-maven-plugin:jar:6.10.0-SNAPSHOT
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:128)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:182)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:286)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:241)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleMappingDelegate.calculateLifecycleMappings(DefaultLifecycleMappingDelegate.java:111)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:266)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:218)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:127)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:145)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:97)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:111)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.eclipse.che.core:che-core-dynamodule-maven-plugin:jar:6.10.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:303)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:124)
	... 27 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.eclipse.che.core:che-core-dynamodule-maven-plugin:jar:6.10.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:443)
	... 31 more
[ERROR] 
[ERROR] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException`

Anything anyone can suggest to get this up and going would be greatly appreciated!

**Comment by eivantsov** [comment]
@skabashnyuk perhaps you will be quicker in diagnosing

```
[ERROR] Plugin org.eclipse.che.core:che-core-dynamodule-maven-plugin:6.10.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.che.core:che-core-dynamodule-maven-plugin:jar:6.10.0-SNAPSHOT
```

**Comment by skabashnyuk** [comment]
@jdflemin sorry. We had an issue in a code. It was fixed in https://github.com/che-samples/che-ide-server-extension/pull/18 Please try again.
