### ISSUE TITLE
[Language server]  Sometimes Hover popup window does not appear

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10674]
### Description
We have unexpected fail of **YamlFileEditingTest** selenium test. The test fails when checking expected text from hover popup.  We should clarify reason and fix it.

### Remarks
Randomly reproducing
**Related selenium tests:** YamlFileEditingTest, GolangFileEditingTest

**Reproduction Steps:**
1. Create workspace through Dashboard based on **Node** stack with any project. 
2. Enable **Yaml** language server and start the workspace.
3. Set YAML schema: 
    - menu **Profile** -> **Preferences**. 
    - select **Yaml** -> click 'Add Schema Url' button -> type "**kubernetes**".
4. Create "**openshift.yaml**" file and add content:
```
apiVersion: v1
kind: PersistentVolume
metadata:
```
4. Move the mouse pointer over the ```kind: PersistentVolume``` text  several times.

**Expected result:**
Hover popup with text ``` Kind is a string value representing the REST resource this object represents.```appeared on every move.

**Actual result:** 
After some movement the Hover pop-up window doesn't appear. There is an error message in the browser console(see screenshot).

**Screenshot:**
![selection_097](https://user-images.githubusercontent.com/7760565/44531099-98c5cc00-a6f8-11e8-8a19-ecd880ef7dd9.png)

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/309/Selenium_20tests_20report/

<details>

<summary>**Log:**</summary>
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of [[RemoteWebDriver: chrome on LINUX (64c1f911-8538-412f-90a8-1d790b81b40a)] -> xpath: //div[@class='textviewTooltip'][last()]] (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:158)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.lambda$waitTextContains$7(SeleniumWebDriverHelper.java:746)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitTextContains(SeleniumWebDriverHelper.java:744)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitTextContains(SeleniumWebDriverHelper.java:758)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitTextInHoverPopup(CodenvyEditor.java:444)
	at org.eclipse.che.selenium.languageserver.YamlFileEditingTest.checkHoverFeature(YamlFileEditingTest.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
</details>

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
