### ISSUE TITLE
Unexpected fail of "OpenExternalLibraryFileAfterRefreshTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10723]
### Description
We have unexpected fail of the "OpenExternalLibraryFileAfterRefreshTest" selenium test which reproduced randomly. It looks like something went wrong with a method which checks external libraries. We should investigate and fix this problem.

**Logs:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.xpath: //div[@id='gwt-debug-projectTree']//div[text()='servlet-api-2.5.jar'] (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:137)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitVisibilityByName(ProjectExplorer.java:449)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitVisibilityByName(ProjectExplorer.java:416)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.openItemByVisibleNameInExplorer(ProjectExplorer.java:586)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.openSeveralItemsByVisibleNameInExplorer(ProjectExplorer.java:603)
	at org.eclipse.che.selenium.projectexplorer.dependencies.OpenExternalLibraryFileAfterRefreshTest.openFileFromExternalLibraryAndCheckDisplayedText(OpenExternalLibraryFileAfterRefreshTest.java:85)
	at org.eclipse.che.selenium.projectexplorer.dependencies.OpenExternalLibraryFileAfterRefreshTest.shouldOpenTheSameFileAfterRefreshBrowser(OpenExternalLibraryFileAfterRefreshTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/366/Selenium_20tests_20report/

**OS and version:**    
Che 6.10.0 ; Chrome 63.0 ; Fedora 28

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/10727
