### ISSUE TITLE
Yo generator doesn't work in Theia image

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#10756]
### Description
Theia docker image has build-in yo generator. However it doesn't work and fall with the following error:
```
/projects # yo
/usr/local/lib/node_modules/yo/node_modules/write-file-atomic/index.js:197
    throw err
    ^

Error: EACCES: permission denied, open '/home/theia/.config/insight-nodejs/insight-yo.json.4135311943'
    at Object.fs.openSync (fs.js:646:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/yo/node_modules/write-file-atomic/index.js:180:17)
    at Conf.set store [as store] (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:142:19)
    at Conf.set (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:64:14)
    at Insight.set optOut [as optOut] (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:56:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:198:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

### Reproduction Steps
Just run `yo` in workspace from standard stack (docker Theia image).

### Environment

Che version: `6.10.0-SNAPSHOT`
Theia image: `eclipse/che-theia:0.4.0-next.b17727c1-nightly`

**Comment by sunix** [comment]
![eclipse che theia_factory_test_3 - google chrome_150](https://user-images.githubusercontent.com/650571/44036964-74977dde-9f13-11e8-8d51-77dbc5e91c07.png)
weird

**Comment by benoitf** [comment]
@mmorhun AFAIK it's working with theia image 0.3.13-nightly ?

**Comment by benoitf** [comment]
https://github.com/eclipse/che/blob/c5e92e7156439c9ed8f1475b50944572e337aa6f/ide/che-core-ide-stacks/src/main/resources/stacks.json is fine. Maybe your che data folder is old then stacks are not updated

**Comment by mmorhun** [comment]
@benoitf yes you are right. I forgot to delete old config.

**Comment by mmorhun** [comment]
More testing shows that it still has some troubles. Yo starts, user can choose options, but finally it failed on generation phase with the following error:
```
   create package.json
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/projects/test/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at write (/projects/theia-generator-plugin/node_modules/mem-fs-editor/lib/actions/commit.js:14:6)
    at DestroyableTransform._transform (/projects/theia-generator-plugin/node_modules/mem-fs-editor/lib/actions/commit.js:43:7)
    at DestroyableTransform.Transform._read (/projects/theia-generator-plugin/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/projects/theia-generator-plugin/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/projects/theia-generator-plugin/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/projects/theia-generator-plugin/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/projects/theia-generator-plugin/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/projects/theia-generator-plugin/node_modules/readable-stream/lib/_stream_readable.js:619:20)
```

**Comment by sunix** [comment]
yes got this as well :(

**Comment by sunix** [comment]
for some reasons, yo use user `1000` to create files even if you are root
```
sh-4.2# ls -ll
total 268
-rw-r--r--.   1 1000 root     45 Aug 14 13:56 README.md
drwxr-xr-x.   2 1000 root   4096 Aug 14 13:56 dist
drwxr-xr-x. 612 1000 root  20480 Aug 14 13:56 node_modules
-rw-r--r--.   1 1000 root   1117 Aug 14 13:56 package.json
drwxr-xr-x.   2 1000 root   4096 Aug 14 13:56 src
-rw-r--r--.   1 1000 root  49651 Aug 14 13:56 test_plugin.theia
-rw-r--r--.   1 1000 root    522 Aug 14 13:56 tsconfig.json
-rw-r--r--.   1 1000 root    753 Aug 14 13:56 tsfmt.json
-rw-r--r--.   1 1000 root   1257 Aug 14 13:56 webpack.config.js
-rw-r--r--.   1 1000 root 171261 Aug 14 13:56 yarn.lock
sh-4.2# whoami
root
sh-4.2#
```

**Comment by mmorhun** [comment]
The problem with `yo` is still actual for docker infrastructure.

**Comment by mmorhun** [comment]
I can confirm that the problem with yo is in using root user on docker infrastructure.

**Comment by eivantsov** [comment]
@mmorhun do you expect me to fix it?

**Comment by mmorhun** [comment]
@eivantsov no, I am working on it. I assigned you because you did some work before.

**Comment by eivantsov** [comment]
Gotcha! Feel free to ask questions if any. But the issue is straightforward. We need a user in that image.

**Comment by mmorhun** [comment]
Fixed
