### ISSUE TITLE
No end-user indicator when Keycloak user has no email

### ISSUE THREAD

**Issue by aidenkeating** [eclipse-che/che#10768]
### Description
Hey guys,

When using Che with Keycloak as an Identity Provider and the Keycloak users email is null there is nothing to tell the end user that there's a problem. Instead Che stays at its loading screen. 

* Is the user email actually required?
* Could an indicator to the end-user that something has gone wrong be added.

### Reproduction Steps
* Follow through this guide: https://www.eclipse.org/che/docs/openshift-multi-user.html
* Have a Keycloak user with no email set, try to login
* Che stays at its loading screen, pod logs are in the diagnostics section

**OS and version:**    
```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

**Diagnostics:** 
```
2018-08-14 09:55:36,300[nio-8080-exec-3]  [ERROR] [o.a.c.c.C.[.[.[/api].[default] 245]  - Servlet.service() for servlet [default] in context with path [/api] threw exception
--
  | java.lang.NullPointerException: Required non-null email
  | at java.util.Objects.requireNonNull(Objects.java:228)
  | at org.eclipse.che.api.user.server.UserManager.getByEmail(UserManager.java:184)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.getUserByEmail(KeycloakUserManager.java:160)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.getOrCreateUser(KeycloakUserManager.java:112)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:91)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:121)
  | at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:129)
  | at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
  | at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:423)
  | at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)
```

**Comment by mshaposhnik** [comment]
Fixed in https://github.com/eclipse/che/pull/10889
