### ISSUE TITLE
Beaglebone Che

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1081]
I am trying to run che natively on beaglebone with arch linux. I am using usb0 connected to a remote windows machine. I go to 192.168.7.2:8080 and can get the webpage to load but errors at starting workspace agent. Below is the error code I am getting. Is there an ip address I need to set in the config file? 

che.properties:
# machine.docker.local_node_host=NULL

machine.docker.local_node_host=192.168.7.2
# I tried both of the following.
# machine.docker.che_api.endpoint=http://che-host:${SERVER_PORT}/ide/api

machine.docker.che_api.endpoint=http://192.168.7.2:${SERVER_PORT}/ide/api

Did this per another post I saw just in case
[root@alarm eclipse-che]# ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 Feb 22 08:40 /var/run/docker.sock
[root@alarm eclipse-che]# chmod 666 /var/run/docker.sock
[root@alarm eclipse-che]# ls -l /var/run/docker.sock
srw-rw-rw- 1 root docker 0 Feb 22 08:40 /var/run/docker.sock

when running JAVA_HOME=/usr/lib/jvm/java-8-openjdk/jre/ bin/che.sh --skip:uid
`
2016-04-19 08:32:12,778[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 598971 ms
2016-04-19 08:32:51,472[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 162]      - Creating machine [ws = workspace6szmky53zekoj0xb: env = HelloBeagleBoard: machine = ws-machine]
2016-04-19 08:32:52,371[kspaceManager-0]  [ERROR] [o.e.c.a.m.s.u.RecipeDownloader 82]   - Removal of recipe file /usr/share/eclipse-che/tomcat/temp/recipe280953514124065759.tmp failed.
2016-04-19 08:33:00,879[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 537]    - Failed writing 8192 bytes
org.eclipse.che.api.machine.server.exception.MachineException: Failed writing 8192 bytes
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:402) ~[che-core-api-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:339) ~[che-core-api-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:163) ~[che-core-api-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.createMachine(WorkspaceRuntimes.java:490) ~[che-core-api-workspace-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:411) ~[che-core-api-workspace-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:368) ~[che-core-api-workspace-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:180) ~[che-core-api-workspace-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:522) ~[che-core-api-workspace-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Failed writing 8192 bytes
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.buildImage(DockerInstanceProvider.java:318) ~[che-plugin-docker-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.local.interceptor.EnableOfflineDockerMachineBuildInterceptor.invoke(EnableOfflineDockerMachineBuildInterceptor.java:58) ~[che-plugin-docker-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:221) ~[che-plugin-docker-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:362) ~[che-core-api-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        ... 11 common frames omitted
Caused by: java.io.IOException: Failed writing 8192 bytes
        at org.eclipse.che.plugin.docker.client.connection.UnixSocketOutputStream.write(UnixSocketOutputStream.java:50) ~[che-plugin-docker-client-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_77]
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126) ~[na:1.8.0_77]
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:74) ~[guava-18.0.jar:na]
        at org.eclipse.che.plugin.docker.client.connection.DockerConnection$StreamEntity.writeTo(DockerConnection.java:114) ~[che-plugin-docker-client-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.connection.UnixSocketConnection.request(UnixSocketConnection.java:53) ~[che-plugin-docker-client-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.connection.DockerConnection.request(DockerConnection.java:85) ~[che-plugin-docker-client-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.DockerConnector.doBuildImage(DockerConnector.java:868) ~[che-plugin-docker-client-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:214) ~[che-plugin-docker-client-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.buildImage(DockerInstanceProvider.java:310) ~[che-plugin-docker-machine-4.2.0-RC1-SNAPSHOT.jar:4.2.0-RC1-SNAPSHOT]
        ... 14 common frames omitted
`

`[root@alarm ~]# ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:88ff:fe72:1961  prefixlen 64  scopeid 0x20<link>
        ether 02:42:88:72:19:61  txqueuelen 0  (Ethernet)
        RX packets 22  bytes 1544 (1.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 89  bytes 6572 (6.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 84:eb:18:e5:4e:0a  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 175

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 107  bytes 8277 (8.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 107  bytes 8277 (8.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

usb0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.7.2  netmask 255.255.255.0  broadcast 192.168.7.255
        inet6 fe80::fcfa:1dff:fe73:5d1a  prefixlen 64  scopeid 0x20<link>
        ether fe:fa:1d:73:5d:1a  txqueuelen 1000  (Ethernet)
        RX packets 621105  bytes 843986329 (804.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 140937  bytes 20853497 (19.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

**Comment by james10174** [comment]
[root@alarm ~]# pacman -Q docker
docker 1:1.10.3-1

**Comment by james10174** [comment]
Sorry for better format use the following link.
[http://pastebin.com/ZUF4wVuz](url)

**Comment by TylerJewell** [comment]
My initial guess is that the Beagle board you are using is an ARM architecture, and it's likely that the workspace creation is failing because the default Docker images are not compiled for that architecture.  The default recipes pull from images on DockerHub that are compiled for a particular architecture.  @eivantsov and @garagatyi have more experience on this topic.

**Comment by james10174** [comment]
Think you got me in the right direction. I am going to try the following for RPi but should be able to get it working for beaglebone.

[https://blog.benjamin-cabe.com/2016/04/01/running-eclipse-che-on-a-raspberry-pi#Updating_Che8217s_built-in_stacks_to_be_ARM-compatible](url)

**Comment by TylerJewell** [comment]
@james10174 We are also about to make a number of merges that could help you.  We are working on compatibility for ARTIK devices, which also have an ARM device.  Our objective is to provide great management of the device, but not run Che on the device.  What we are doing:
1. Creating a new kind of SSH machine.
2. You can add / remove devices that are connected via SSH.
3. When connecting a device, we will place an ARM-compiled web terminal onto the device.  This will provide direct console access from within the IDE onto the device.  The Che server would be running on your desktop or another server.
4. We then have an SCP service for pushing / pulling devices onto / from the device.

At a minimum, you should be able to reuse the new web terminal capabilities that we are packaging to run those on the beaglebone and connect back to an IDE not running on the device.

**Comment by james10174** [comment]
@TylerJewell Trying to grasp how che and docker workspaces work on different architectures. If I had che running on my windows pc where would the java code be compiled? Would I need a java cross compiler for arm 7 on windows pc?

**Comment by james10174** [comment]
@TylerJewell I do have a linux amd64 pc setup with che at home. I think I can get the scp and ssh setup separately but I just need to know how the docker image/containers are created for arm7.

**Comment by TylerJewell** [comment]
There are three essential pieces to Che:
1. Che server.
2. Workspace
3. Browser

The Che server runs on a JVM.  It is responsible for CRUDing workspaces.
Workspaces are powered by Docker containers, and launched by a Docker daemon.  

Your project files are stored in long term storage (on the Che server on disk) and then mounted into the workspace runtime when the workspace is started.  All file operations take place within the workspace (inside the container).

Inside the workspace -- during its initialization --, we do the following:
1. We inject a web-terminal, which provides HTTP access to shells on the container.
2. We inject another che agent, a JVM process that makes certain commands available over REST
3. We launch sshd within the workspace.

The che-agent communicates back to the Che server.
The Che server lets the browser know where the che-agent and terminal IP:PORT is.
The browser then communicates to the workspace through che-agent and terminal over web sockets and HTTP.

When you do a compilation, the browser sends the compilation command over web sockets into the che-agent, running inside the container.  The command is then launched as a process within the container itself.  And then that command has local access to the project files, which were mounted into the container.

Any changes to the project files are then synchronized to long term storage (on the che server).  In the case of Che, this is just a direct mount between workspace container and che server.  In codenvy, where workspaces are distributed, this is done over rsync protocol.

So, to support a new architecture, the first thing is that workspaces must run on this architecture:
1. The Dockerfiles for those workspaces need to be compiled into images that support that architecture.  And then when the workspace starts, use this new image instead of the standard ones.
2. And the terminal that we inject into the workspace itself when the workspace is started needs to be compiled to support the underlying architecture.

This assumes that you want the workspace itself running _on the device_.  This is different from what we did for ARTIK.  For ARTIK, we:
1. Have che server running on laptop.
2. Have che workspace container also running on laptop.
3. Have the workspace make an SSH connection to the ARTIK device with an SSH Machine.
4. We then install our terminal onto the device, but leave the workspace on laptop.
5. All commands are then remotely sent to the device and we stream their output back to browser.
6. We then have an SCP service to move files from the workspace container onto the device.

**Comment by TylerJewell** [comment]
If you were wanting to duplicate the configuration that we are doing for ARTIK for Beaglebone, I think it should be fairly straight forward.  We probably would need to complete our 4.2. release cycle this week as it would introduce the SCP, SSH machine services along with pre-compiled binaries of the terminal.  We could then walk you through a similar custom assembly for Beaglebone (or it may just work out of the box, too).  Does Beaglebone support on-device SSH?

**Comment by ghost** [comment]
@james10174 `Failed writing 8192 bytes` is an error that we have reproduced on Ubuntu 16 - https://github.com/eclipse/che/issues/745. So, looks like so far nothing ARM specific. But then yeah, you should use ARM docker images.

**Comment by james10174** [comment]
@TylerJewell Not sure what on-device ssh means. I can ssh through OTG usb. I use m_multi to make the OTG usb act like a network device on windows machine. I had to install drivers on windows from [http://beagleboard.org/getting-started](url) step 2.

**Comment by james10174** [comment]
@TylerJewell My end goal is to have che embedded in beaglebone. For others who could be using my beaglebone in the future, I would like them to be able to plug any windows machine into it, install beaglebone drivers, and open the ip:8080 for the IDE. I want to give others the ability to reprogram the beaglebone with having to install or setup che on their pc. For my own development though I would love a faster approach with the end/future result of having che embedded in beaglebone. Not sure if the ARTIK example you gave above is intended to always have the pc and beaglebone connected. If not, I think your approach above could work better for me.

**Comment by TylerJewell** [comment]
If your goal is to have Che running on the device itself, then:
1. You will need to make sure that the docker images pulled by the workspace are compiled for ARM.
2. You then need to make sure that the terminal that is injected into the container is also compiled for ARM.
3. You then have your stacks in the dashboard use the ARM-compiled images instead of the defaults.

This should cover the core use case of running on the device itself.  Then as long as end user has IP address of the device, they can reference ip:8080 in browser and Che will run.

We'll need to pull in @eivantsov or @garagatyi to help provide specifics on anything you need to do to make these two things happen easier.

**Comment by ghost** [comment]
@james10174 @TylerJewell  so far, we're dealing with a different issue. The error does not even let a docker container attempt to start. And it has been reproduced on Ubuntu 16.

**Comment by james10174** [comment]
@eivantsov I downgraded my docker version to 1.9.1 and it got past the error. It's currently downloading so we will see how that goes. Using kartben/armhf-che-jdk8 instead of codenvy/ubuntu_jdk8 following the guide at [https://blog.benjamin-cabe.com/2016/04/01/running-eclipse-che-on-a-raspberry-pi](url)

@TylerJewell Is there a way to connect che to a running workspace in docker? What I would like to do eventually is get docker machine running first and then connect che to docker workspace later after che server starts up(ide.war :) ).

**Comment by TylerJewell** [comment]
You are thinking about somehow launching the Che workspace container, and then after the Che server restarts, have the Che server pick up detection of that?  I don't think that would work well, though not sure that anyone has thought about that scenario.  What you are really asking, I think is if the workspaces will continue to operate if the Che server recycles itself.  

@garagatyi - what do you think about this?

**Comment by garagatyi** [comment]
Hi. @TylerJewell I've thought about that, but it is really big and complex task. As it is not in road map I'm not sure when it can be implemented.

**Comment by james10174** [comment]
@TylerJewell I think I can just start che without it running workspace but have the release docker version running on the beaglebone at boot. When someone opens che from browser I can make a script that when they execute the run command it will shutdown the release version thats running and start che's debug version. I will have an additional run command in che that will remove and install release version. I can actually start che after system boot using and light weight web application say at port 8081 that will redirect browser to 8080 after che starts up.

**Comment by TylerJewell** [comment]
@james10174 That is fairly clever.  +1

**Comment by james10174** [comment]
Sorry to keep posting on this bug listing but another thing that might interest others using arm is docker arm emulation on windows 8+. My thought is that you can have a windows che server that compiles and then sends docker container to arm sbc such as beaglebone or raspberry pi via scp. Then run command in che that starts docker container on sbc. I am pretty new with docker and che so sorry if I am saying anything incorrect in the process. One of the biggest headaches with arm development is how slow compile times are and dealing with cross compiling. I will of course keep everyone posted on my progress. [http://blog.hypriot.com/post/close-encounters-of-the-third-kind/](url)

**Comment by james10174** [comment]
Got it into workspace and created project! Having other issues but will post another bug for that.

![image](https://cloud.githubusercontent.com/assets/16562450/14694044/682832d8-072a-11e6-94e1-8f4316bdca8b.png)
