### ISSUE TITLE
GWT exited with status 137 following "Develop Your First Plugin Usign Che"

### ISSUE THREAD

**Issue by sathibault** [eclipse-che/che#10829]
### Description

I'm getting this GWT error at the "Deploy IDE" command step of the tutorial at https://www.eclipse.org/che/docs/che-in-che-quickstart.html.

### Reproduction Steps

Follow above tutorial.

**OS and version:**    

The eclipse/che-server:6.9.0 image on Windows for Docker on Windows 10.

**Diagnostics:** 

```
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-8:compile (default) on project assembly-ide-war: GWT exited with status 137 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-8:compile (default) on project assembly-ide-war: GWT exited with status 137
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: GWT exited with status 137
        at net.ltgt.gwt.maven.CommandLine.execute(CommandLine.java:50)
        at net.ltgt.gwt.maven.CompileMojo.execute(CompileMojo.java:202)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
```

**Comment by sathibault** [comment]
I've gotten past this error by increasing the Docker for Windows memory setting to 4096 MB.

However, I know run into a new error:
```
[ERROR] Failed to execute goal [32morg.apache.maven.plugins:maven-war-plugin:3.1.0:war[m [1m(default-war)[m on project [36massembly-wsagent-war[m: [1;31mFailed to copy file for overlay [ id org.eclipse.che:assembly-wsagent-war][m: Failed to copy full contents from /projects/che-ide-server-extension/assembly/assembly-wsagent-war/target/war/work/org.eclipse.che/assembly-wsagent-war/WEB-INF/lib/validation-api-1.1.0.Final.jar to /projects/che-ide-server-extension/assembly/assembly-wsagent-war/target/assembly-wsagent-war-6.10.0-SNAPSHOT/WEB-INF/lib/validation-api-1.1.0.Final.jar -> [1m[Help 1][m

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal [32morg.apache.maven.plugins:maven-war-plugin:3.1.0:war[m [1m(default-war)[m on project [36massembly-wsagent-war[m: [1;31mFailed to copy file for overlay [ id org.eclipse.che:assembly-wsagent-war][m

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)

	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)

	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)

	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)

	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)

	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)

	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)

	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)

	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)

	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)

	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)

	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)

	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)

	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to copy file for overlay [ id org.eclipse.che:assembly-wsagent-war]

	at org.apache.maven.plugins.war.packaging.OverlayPackagingTask.performPackaging(OverlayPackagingTask.java:101)

	at org.apache.maven.plugins.war.AbstractWarMojo.buildWebapp(AbstractWarMojo.java:526)

	at org.apache.maven.plugins.war.AbstractWarMojo.buildExplodedWebapp(AbstractWarMojo.java:442)

	at org.apache.maven.plugins.war.WarMojo.performPackaging(WarMojo.java:234)

	at org.apache.maven.plugins.war.WarMojo.execute(WarMojo.java:197)

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)

	... 20 more

Caused by: java.io.IOException: Failed to copy full contents from /projects/che-ide-server-extension/assembly/assembly-wsagent-war/target/war/work/org.eclipse.che/assembly-wsagent-war/WEB-INF/lib/validation-api-1.1.0.Final.jar to /projects/che-ide-server-extension/assembly/assembly-wsagent-war/target/assembly-wsagent-war-6.10.0-SNAPSHOT/WEB-INF/lib/validation-api-1.1.0.Final.jar

	at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:1101)

	at org.apache.maven.plugins.war.packaging.AbstractWarPackagingTask.copyFile(AbstractWarPackagingTask.java:369)

	at org.apache.maven.plugins.war.packaging.AbstractWarPackagingTask$1.registered(AbstractWarPackagingTask.java:168)

	at org.apache.maven.plugins.war.util.WebappStructure.registerFile(WebappStructure.java:202)

	at org.apache.maven.plugins.war.packaging.AbstractWarPackagingTask.copyFile(AbstractWarPackagingTask.java:162)

	at org.apache.maven.plugins.war.packaging.AbstractWarPackagingTask.copyFiles(AbstractWarPackagingTask.java:116)

	at org.apache.maven.plugins.war.packaging.AbstractWarPackagingTask.copyFiles(AbstractWarPackagingTask.java:139)

	at org.apache.maven.plugins.war.packaging.OverlayPackagingTask.performPackaging(OverlayPackagingTask.java:85)

	... 26 more

**Comment by eivantsov** [comment]
@sathibault I failed to reproduce on a Linux machine. I suspect this is a bug related to Win fs mount into a Docker VM:

![image](https://user-images.githubusercontent.com/5337267/46272973-34e6bc80-c55c-11e8-803b-8676e1f4871f.png)

And I do not think the tutorial in docs has been verified to work on Windows.
