### ISSUE TITLE
Unexpected fail of CreateFactoryFromUiWithKeepDirTest selenium test 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10852]
### Description
We have unexpected fail of **CreateFactoryFromUiWithKeepDirTest** selenium test. The test sometimes fails when trying to open test project in the **Project Explorer** after updating project configuration. We should clarify reason and fix it.

**Failed selenium test:** CreateFactoryFromUiWithKeepDirTest

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.xpath: //div[@path='/FactoryFromUiWithKeepDirTest3p/complete']/div (tried for 120 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:137)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitItem(ProjectExplorer.java:296)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitItem(ProjectExplorer.java:284)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitAndSelectItem(ProjectExplorer.java:484)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitAndSelectItem(ProjectExplorer.java:473)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.openItemByPath(ProjectExplorer.java:553)
	at org.eclipse.che.selenium.factory.CreateFactoryFromUiWithKeepDirTest.setUpModuleForFactory(CreateFactoryFromUiWithKeepDirTest.java:122)
	at org.eclipse.che.selenium.factory.CreateFactoryFromUiWithKeepDirTest.createFactoryFromUiWithKeepDirTest(CreateFactoryFromUiWithKeepDirTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/324/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.factoryCreateFactoryFromUiWithKeepDirTest

**Screenshot:**
![org eclipse che selenium factory createfactoryfromuiwithkeepdirtest createfactoryfromuiwithkeepdirtest_32nzu69h](https://user-images.githubusercontent.com/7760565/44345251-797e3300-a49b-11e8-9925-8b3e36543d6a.png)

**Comment by SkorikSergey** [comment]
Not reproduced in CHE 6.14.0-SNAPSHOT.
