### ISSUE TITLE
Unexpected fail of WorkingWithTerminalTest selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10854]
### Description
We have unexpected fail of **WorkingWithTerminalTest** selenium test. The test sometimes fails because terminal content is broken(see screenshots). We should clarify reason and fix it.

**Failed selenium test:** WorkingWithTerminalTest

**Log:**
```
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.eclipse.che.selenium.pageobject.CheTerminal$$Lambda$212/1988260557@24d76b15 (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:205)
	at org.eclipse.che.selenium.pageobject.CheTerminal.waitTextInTerminal(CheTerminal.java:183)
	at org.eclipse.che.selenium.pageobject.CheTerminal.waitTextInFirstTerminal(CheTerminal.java:193)
	at org.eclipse.che.selenium.miscellaneous.WorkingWithTerminalTest.shouldResizeTerminal(WorkingWithTerminalTest.java:181)
	... 13 more
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.miscellaneousWorkingWithTerminalTest
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.miscellaneousWorkingWithTerminalTest

**Screenshot:**
![org eclipse che selenium miscellaneous workingwithterminaltest shouldnavigatetomc_8mi7imfl](https://user-images.githubusercontent.com/7760565/44348222-85b9be80-a4a2-11e8-982b-0e2481db030f.png)

![org eclipse che selenium miscellaneous workingwithterminaltest shouldresizeterminal_2yqftqko](https://user-images.githubusercontent.com/7760565/44348223-86525500-a4a2-11e8-854d-6b41378c92be.png)

![org eclipse che selenium miscellaneous workingwithterminaltest shouldresizeterminal_b2ezg1gu 1](https://user-images.githubusercontent.com/7760565/44409650-73f01e00-a56b-11e8-9850-6169576f251e.png)

**Comment by rhopp** [comment]
Not relevant anymore. Closing.
