### ISSUE TITLE
[Multiuser] Cannot create a new project after deleting an existing project

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10865]
**Reproduction Steps:**
1. Create and start workspace through **Dashboard** based on **Java** stack with "**web-java-spring**" project. 
2. Delete the "**web-java-spring**" project.
3. Try to create a new project by **Create New Project** feature from "web-java-spring" sample.

**Expected result:**
Project created.

**Actual result:**
There is error information dialog with ```The user does not have permission to configure workspace with id 'workspacerxgwsyiip2dgyfqp'``` message.
 
**Che version**: 6.10.0-SNAPSHOT
**OS and version:** Fedora 28
**Che install:** OCP-multiuser

<details>
<summary>Browser console log:</summary>

```
2018/08/21 10:07:05 Start new terminal.
2018-08-21 10:07:39,517[equestProcessor]  [ERROR] [o.e.c.p.m.s.c.MavenWorkspace 154]    - Can't add new project: /ws
	at org.eclipse.che.api.project.server.impl.ValidatingProjectManager.setType(ValidatingProjectManager.java:253)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at org.eclipse.che.plugin.maven.server.core.MavenWorkspace$2.projectUpdated(MavenWorkspace.java:106)
	at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.access$100(MavenWorkspace.java:61)
	at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.lambda$createNewProjects$0(MavenWorkspace.java:148)
	at org.eclipse.che.api.project.server.impl.SynchronizingProjectManager.setType(SynchronizingProjectManager.java:189)
	at java.util.HashMap$KeySet.forEach(HashMap.java:933)
	at org.eclipse.che.api.project.server.impl.WorkspaceProjectSynchronizer.synchronize(WorkspaceProjectSynchronizer.java:109)
	at org.eclipse.che.api.project.server.impl.WorkspaceProjectSynchronizer.update(WorkspaceProjectSynchronizer.java:163)
	at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.createNewProjects(MavenWorkspace.java:144)
org.eclipse.che.api.core.ServerException: The user does not have permission to configure workspace with id 'workspacerxgwsyiip2dgyfqp'
	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.lambda$createListenersDispatcher$0(MavenProjectManager.java:103)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.proxy.$Proxy68.projectUpdated(Unknown Source)
	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager$UpdateState.fireUpdate(MavenProjectManager.java:554)
	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.update(MavenProjectManager.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at org.eclipse.che.plugin.maven.server.projecttype.handler.MavenProjectInitHandler.initializeClasspath(MavenProjectInitHandler.java:42)
	at org.eclipse.che.plugin.java.server.projecttype.AbstractJavaInitHandler.onProjectInitialized(AbstractJavaInitHandler.java:62)
	at org.eclipse.che.api.project.server.impl.ExecutiveProjectManager.fireInitHandlers(ExecutiveProjectManager.java:423)
	at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.update(MavenWorkspace.java:180)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)
	at org.eclipse.che.api.project.server.impl.ProjectJsonRpcServiceBackEnd.createBatchProjects(ProjectJsonRpcServiceBackEnd.java:103)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.handle(RequestHandlerManager.java:365)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at org.eclipse.che.api.project.server.impl.ProjectJsonRpcServiceBackEnd.createBatchProjectsInternally(ProjectJsonRpcServiceBackEnd.java:263)
	at org.eclipse.che.api.project.server.impl.ProjectJsonRpcServiceBackEnd.perform(ProjectJsonRpcServiceBackEnd.java:313)
	at org.eclipse.che.api.project.server.impl.ValidatingProjectManager.update(ValidatingProjectManager.java:179)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
	at org.eclipse.che.api.project.server.impl.SynchronizingProjectManager.update(SynchronizingProjectManager.java:126)
	at org.eclipse.che.api.project.server.impl.ExecutiveProjectManager.update(ExecutiveProjectManager.java:174)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.access$1100(RequestHandlerManager.java:351)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.eclipse.che.api.project.server.impl.WorkspaceProjectSynchronizer.update(WorkspaceProjectSynchronizer.java:163)
org.eclipse.che.api.core.ServerException: The user does not have permission to configure workspace with id 'workspacerxgwsyiip2dgyfqp'
	at org.eclipse.che.api.git.GitCheckoutDetector.lambda$fsEventConsumer$2(GitCheckoutDetector.java:142)
	at org.eclipse.che.api.project.server.impl.ValidatingProjectManager.setType(ValidatingProjectManager.java:253)
	at org.eclipse.che.api.watcher.server.impl.FileTreeWalker.lambda$updateFsTreeAndAcceptConsumables$3(FileTreeWalker.java:206)
	at org.eclipse.che.api.watcher.server.impl.FileWatcherByPathMatcher.accept(FileWatcherByPathMatcher.java:32)
	at org.eclipse.che.api.watcher.server.impl.FileWatcherByPathMatcher.accept(FileWatcherByPathMatcher.java:84)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.che.api.watcher.server.impl.FileTreeWalker.updateFsTreeAndAcceptConsumables(FileTreeWalker.java:206)
	at org.eclipse.che.api.watcher.server.impl.FileTreeWalker.access$600(FileTreeWalker.java:46)
2018-08-21 10:07:40,562[ted-scheduler-9]  [ERROR] [o.e.c.a.g.GitCheckoutDetector 147]   - Error trying to read /ws/.git/HEAD file and broadcast it
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at org.eclipse.che.api.watcher.server.impl.FileTreeWalker.walk(FileTreeWalker.java:148)
	at org.eclipse.che.api.watcher.server.impl.FileTreeWalker$2.visitFile(FileTreeWalker.java:174)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at org.eclipse.che.api.watcher.server.impl.FileTreeWalker$2.visitFile(FileTreeWalker.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.api.project.server.impl.SynchronizingProjectManager.setType(SynchronizingProjectManager.java:189)
	at org.eclipse.che.api.project.server.impl.WorkspaceProjectSynchronizer.synchronize(WorkspaceProjectSynchronizer.java:109)

```
</details>

**Screenshot:**
![selection_095](https://user-images.githubusercontent.com/7760565/44395844-cddced80-a543-11e8-90f0-1fb09227bd0d.png)

**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 08 21-13-07-47_1](https://user-images.githubusercontent.com/7760565/44396136-afc3bd00-a544-11e8-9d05-0301bb647756.gif)

**Comment by eivantsov** [comment]
@SkorikSergey I cannot reproduce. Can you check it once again?

**Comment by SkorikSergey** [comment]
For now I cannot reproduce this issue.
