### ISSUE TITLE
OKD 3.10: Random workspace start failures due to lack of privileges of che service account

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#10916]
### Description

CI test revealed the following problem:

At times, randomly, when starting a workspace, Che server attempt to do it in a namespace outside eclipse-che namespace. As a result, workspace start fails since such objects cannot be created as che service account does not have cluster-admin privileges. 

Logs below say that at first there's an issue with cleaning up workspace resources. And then, the subsequent start of a new workspace fails, because a request is made to create a new namespace, as if Che server is configured with `CHE_INFRA_OPENSHIFT_PROJECT=''`

```
2018-08-26 19:46:57,904[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 498]   - Error occurs on workspace 'che/workspacetvrd7v' with id 'workspaceaz2pw1tdfr77makx' stopped by user 'che'. Error: {}
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Error(s) occurs while cleaning up the namespace. Operation: [patch]  for kind: [Deployment]  with name: [workspaceaz2pw1tdfr77makx.dockerimage]  in namespace: [eclipse-che]  failed.
    at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:192)
    at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:99)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:455)
    at org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:180)
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:478)
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
2018-08-26 19:46:58,001[er-ThreadPool-2]  [ERROR] [e.c.w.i.k.n.p.PVCSubPathHelper 155]  - Unable to perform '[rm, -rf, /tmp/job_mount/workspaceaz2pw1tdfr77makx]' command for the workspace 'workspaceaz2pw1tdfr77makx' cause: 'Failure executing: POST at: https://172.29.4.74:8443/apis/project.openshift.io/v1/projectrequests. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:eclipse-che:che" cannot create projectrequests.project.openshift.io at the cluster scope: You may not request a new project via this API.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.'
2018-08-26 19:46:58,033[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 272]    - Workspace 'workspaceaz2pw1tdfr77makx' removed by user 'che'
2018-08-26 19:47:00,020[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'che/workspace9ibrsf' with id 'workspacewmu3k70ku4chevdj' created by user 'che'
2018-08-26 19:47:00,547[nio-8080-exec-3]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 345]   - Failure executing: POST at: https://172.29.4.74:8443/apis/project.openshift.io/v1/projectrequests. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:eclipse-che:che" cannot create projectrequests.project.openshift.io at the cluster scope: You may not request a new project via this API.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Failure executing: POST at: https://172.29.4.74:8443/apis/project.openshift.io/v1/projectrequests. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:eclipse-che:che" cannot create projectrequests.project.openshift.io at the cluster scope: You may not request a new project via this API.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
```

**Comment by dmytro-ndp** [comment]
If you are talking about https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/373/testReport/junit/org.eclipse.che.selenium.languageserver/ results the tests failed at the stage of creation test workspaces by using dedicated non-default templates: they includes ls-installers and are using special docker images:
- https://github.com/eclipse/che/blob/6.10.0/selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_cpp_gcc.json
- https://github.com/eclipse/che/blob/6.10.0/selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_go.json
- https://github.com/eclipse/che/blob/6.10.0/selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/eclipse_nodejs.json
- https://github.com/eclipse/che/blob/6.10.0/selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_with_c_sharp_lsp.json
- https://github.com/eclipse/che/blob/6.10.0/selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_jdk8_with_camel_ls.json
- https://github.com/eclipse/che/blob/6.10.0/selenium/che-selenium-test/src/test/resources/templates/workspace/openshift/ubuntu_python.json

**Comment by garagatyi** [comment]
@eivantsov we have an [issue](https://github.com/eclipse/che/issues/11582) for OS 3.11. Does it make sense to close this one?

**Comment by eivantsov** [comment]
Yeah, I think we can skip 3.10
