### ISSUE TITLE
[Language server] Python language server features do not work correctly with a file after renaming it

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10935]
**Reproduction Steps:**
1. Create and start workspace through **Dashboard** based on **Python** stack with "**console-python3-simple**" project. 
2. Open "**main.py**" file, check that language server initialized and works:
    - make some mistake and check that code validation feature works;
    - move mouser pointer on "**print**" text in line 1 and check that hover feature works.
3. Rename this file and check language server functionality again.

**Expected result:**
Language server functionality works as expected.

**Actual result:**
Code validation feature doesn't work. 
If add a new line, there will be an exception in **dev-machine** console(see below).
The language server will work with this file correctly after renaming it to previous name or reopening. 

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 27-16-46-06](https://user-images.githubusercontent.com/7760565/44663295-ccfefc80-aa18-11e8-9404-aaecc1112150.gif)

**Exception in dev-machine console when new line was added:**
```
2018-08-27 13:37:36,518[ool-11-thread-1]  [INFO ] [o.e.c.a.l.util.OperationUtil 91]     - Exception occurred in request
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: ValueError: `line` parameter is not in a valid range.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:162)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$request$1(RemoteEndpoint.java:121)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:149)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dkuleshov** [comment]
Should be fixed by https://github.com/eclipse/che/pull/11483 please recheck after it is merged.
