### ISSUE TITLE
[Language server] Golang language server features do not work with a file correctly after renaming it 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10936]
**Reproduction Steps:**
1. Create and start workspace through **Dashboard** based on **Go** stack with "**desktop-go-simple**" project. 
2. Open "**main.go**" file, check that language server initialized and works:
    - make some mistake and check that code validation feature works;
    - move mouser pointer on "**Printf**" text in line 9 and check that hover feature works.
3. Rename this file and check language server functionality again.

**Expected result:**
Language server functionality works as expected.

**Actual result:**
Language server functionality doesn't work. 
There are error in **dev-machine** - ```Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/hover failed with message: Document file:///projects/web-go-simple/main1.go has not been opened.) ```
The language server will work with this file correctly after renaming it to previous name or reopening. 

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 27-17-47-55](https://user-images.githubusercontent.com/7760565/44666666-911c6500-aa21-11e8-801d-82bae64da3a0.gif)

**Exception in dev-machine console after file renaming:**
```
2018-08-27 14:44:15,330[ool-11-thread-1]  [INFO ] [o.e.c.a.l.util.OperationUtil 91]     - Exception occurred in request
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/hover failed with message: Document file:///projects/desktop-go-simple/main2.go has not been opened.
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:162)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$request$1(RemoteEndpoint.java:121)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:149)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/hover failed with message: Document file:///projects/desktop-go-simple/main2.go has not been opened.
	... 11 common frames omitted
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$request$1(RemoteEndpoint.java:121)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
2018-08-27 14:44:18,915[ool-11-thread-1]  [INFO ] [o.e.c.a.l.util.OperationUtil 91]     - Exception occurred in request
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:162)
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/hover failed with message: Document file:///projects/desktop-go-simple/main2.go has not been opened.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 11 common frames omitted
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/hover failed with message: Document file:///projects/desktop-go-simple/main2.go has not been opened.
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
2018-08-27 14:44:19,623[ool-11-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - [lspserver] (node:2730) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: Document file:///projects/desktop-go-simple/main2.go has not been opened.
2018-08-27 14:44:20,679[ool-11-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - [lspserver] (node:2730) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 28): Error: Document file:///projects/desktop-go-simple/main2.go has not been opened.
```

**Comment by dkuleshov** [comment]
Should be fixed by https://github.com/eclipse/che/pull/11483 please recheck after it is merged.
