### ISSUE TITLE
Unexpected fail of "	RollingUpdateStrategyWithWorkspacesStartStopTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10966]
### Description
We have unexpected fail of "RollingUpdateStrategyWithWorkspacesStartStopTest" selenium test. It looks like something went wrong with a method which checks workspace status. We should investigate and fix this problem.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for org.eclipse.che.selenium.pageobject.dashboard.workspaces.Workspaces$1@56465f59 (tried for 240 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.dashboard.workspaces.Workspaces.waitWorkspaceStatus(Workspaces.java:125)
	at org.eclipse.che.selenium.hotupdate.rolling.RollingUpdateStrategyWithWorkspacesStartStopTest.startStopWorkspaceFunctionsShouldBeAvailableDuringRollingUpdate(RollingUpdateStrategyWithWorkspacesStartStopTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-multiuser-master-ocp-rolling-strategy-test/73/Selenium_20tests_20report/

**Screenshot:**
![dfsf](https://user-images.githubusercontent.com/22724619/44731065-0a33bf00-aaeb-11e8-9214-12c86107df1c.png)

**OS and version:**    
Che 6.11.0 ; Chrome 63.0 ; Fedora 28

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/10967
