### ISSUE TITLE
404 after install

### ISSUE THREAD

**Issue by GHostlyFOX** [eclipse-che/che#110]
After installing and running in the browser address on port 8080. In response comes a 404 error.

OS: CentOS 6.7
JDK: 1.8.0

When you start seeing errors:

```
2015-12-07 15:08:39,838[ost-startStop-1]  [INFO ] [com.google.inject.Guice 42]          - An exception was caught and reported. Message: org.eclipse.che.inject.ConfigurationException: Property HOSTNAME%%.* is not found as system property or environment variable.
org.eclipse.che.inject.ConfigurationException: Property HOSTNAME%%.* is not found as system property or environment variable.
    at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:243) ~[che-core-commons-inject-4.0.0-M5-SNAPSHOT.jar:4.0.0-M5-SNAPSHOT]
    at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:214) ~[che-core-commons-inject-4.0.0-M5-SNAPSHOT.jar:4.0.0-M5-SNAPSHOT]
    at org.eclipse.che.inject.CheBootstrap$ExtConfiguration.configure(CheBootstrap.java:160) ~[che-core-commons-inject-4.0.0-M5-SNAPSHOT.jar:4.0.0-M5-SNAPSHOT]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
    at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198) ~[guice-4.0.jar:na]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) [guice-4.0.jar:na]
    at com.google.inject.Guice.createInjector(Guice.java:96) [guice-4.0.jar:na]
    at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137) [everrest-integration-guice-1.10.0.jar:na]
    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) [guice-servlet-4.0.jar:na]
    at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:84) [everrest-integration-guice-1.10.0.jar:na]
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738) [catalina.jar:8.0.28]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181) [catalina.jar:8.0.28]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.28]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.28]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.28]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.28]
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.28]
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798) [catalina.jar:8.0.28]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_60]
    at java.lang.Thread.run(Unknown Source) [na:1.8.0_60]
2015-12-07 15:08:40,557[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/che] 4744] - Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CodenvyBootstrap
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: Property HOSTNAME%%.* is not found as system property or environment variable.
  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)

1 error
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.0.jar:na]
    at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0.jar:na]
    at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137) ~[everrest-integration-guice-1.10.0.jar:na]
    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) ~[guice-servlet-4.0.jar:na]
    at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:84) ~[everrest-integration-guice-1.10.0.jar:na]
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738) [catalina.jar:8.0.28]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181) [catalina.jar:8.0.28]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.28]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.28]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.28]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.28]
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.28]
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798) [catalina.jar:8.0.28]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_60]
    at java.lang.Thread.run(Unknown Source) [na:1.8.0_60]
Caused by: org.eclipse.che.inject.ConfigurationException: Property HOSTNAME%%.* is not found as system property or environment variable.
    at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:243) ~[che-core-commons-inject-4.0.0-M5-SNAPSHOT.jar:4.0.0-M5-SNAPSHOT]
    at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:214) ~[che-core-commons-inject-4.0.0-M5-SNAPSHOT.jar:4.0.0-M5-SNAPSHOT]
    at org.eclipse.che.inject.CheBootstrap$ExtConfiguration.configure(CheBootstrap.java:160) ~[che-core-commons-inject-4.0.0-M5-SNAPSHOT.jar:4.0.0-M5-SNAPSHOT]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
    at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198) ~[guice-4.0.jar:na]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0.jar:na]
    ... 17 common frames omitted
2015-12-07 15:08:40,943[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5182]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
2015-12-07 15:08:41,861[ost-startStop-1]  [INFO ] [o.a.c.u.SessionIdGeneratorBase 241]  - Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [914] milliseconds.
2015-12-07 15:08:41,862[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5233]     - Context [/che] startup failed due to previous errors
2015-12-07 15:08:41,880[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/che/assembly-sdk/target/assembly-sdk-4.0.0-M5-SNAPSHOT/assembly-sdk-4.0.0-M5-SNAPSHOT/webapps/che.war has finished in 8,899 ms
2015-12-07 15:08:41,881[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/che/assembly-sdk/target/assembly-sdk-4.0.0-M5-SNAPSHOT/assembly-sdk-4.0.0-M5-SNAPSHOT/webapps/dashboard.war
2015-12-07 15:08:41,964[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/che/assembly-sdk/target/assembly-sdk-4.0.0-M5-SNAPSHOT/assembly-sdk-4.0.0-M5-SNAPSHOT/webapps/dashboard.war has finished in 83 ms
2015-12-07 15:08:41,965[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1036]       - Deploying web application directory /home/che/assembly-sdk/target/assembly-sdk-4.0.0-M5-SNAPSHOT/assembly-sdk-4.0.0-M5-SNAPSHOT/webapps/ROOT
2015-12-07 15:08:42,028[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1152]       - Deployment of web application directory /home/che/assembly-sdk/target/assembly-sdk-4.0.0-M5-SNAPSHOT/assembly-sdk-4.0.0-M5-SNAPSHOT/webapps/ROOT has finished in 63 ms
2015-12-07 15:08:42,037[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 469]  - Starting ProtocolHandler ["http-nio-8080"]
2015-12-07 15:08:42,046[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 9483 ms
```

**Comment by GHostlyFOX** [comment]
```
HTTP Status 404 - /che

type Status report

message /che

description The requested resource is not available.

Apache Tomcat/8.0.28
```

**Comment by ghost** [comment]
Hello,

Have you exported CHE_LOCAL_CONF_DIR and tried to use external configuration for Che?

It looks like our bootstrap script is trying to get a value for a Che property that uses another system property that cannot be found in your system.

What's the output for the following command?

echo HOSTNAME%%.*

**Comment by GHostlyFOX** [comment]
CHE_LOCAL_CONF_DIR did not help.

echo HOSTNAME%%.\* returns nothing.

**Comment by ghost** [comment]
These are configuration files that we use when booting Che:

https://github.com/codenvy/che/blob/4.0/assembly-sdk-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties
https://github.com/codenvy/che/blob/4.0/assembly-machine-war/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties

None of them features the abovementioned property.

When asking about exporting CHE_LOCAL_CONF_DIR, I wanted to ask if you tried to override the default configuration?

**Comment by TylerJewell** [comment]
We have just restructured the Che assembly and fixed a number of issues that were causing certain environment variables to be configured incorrectly.  Could you build from source following the instructions on our home page at http://eclipse.org/che.

**Comment by GHostlyFOX** [comment]
Reinstall. Launched.

```
http://localhost:8080/api/user/inrole?role=user&scope=system&scopeId= Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/user/inrole?role=admin&scope=system&scopeId= Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/profile Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/profile/prefs Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/im/artifacts Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/user Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/account Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/analytics/log/session-usage Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:7 Object
http://localhost:8080/api/ Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/admin/ Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/user Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/user/inrole?role=admin&scope=system&scopeId= Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/user/inrole?role=user&scope=system&scopeId= Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/api/account Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by GHostlyFOX** [comment]
```
HTTP Status 404 - /che/api/

type Status report

message /che/api/

description The requested resource is not available.

Apache Tomcat/8.0.28
```

**Comment by GHostlyFOX** [comment]
Errors during installation:

```
file:/root/.m2/repository/commons-fileupload/commons-fileupload/1.2.1/commons-fileupload-1.2.1.jar
13:39:18.951 [org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.main()] WARN  org.reflections.Reflections - could not create Dir using directory from url file:/home/che/assembly-sdk-war/target/classes. skipping.
java.lang.NullPointerException: null
    at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:233) ~[reflections-0.9.9.jar:na]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:97) [reflections-0.9.9.jar:na]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:90) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.scan(Reflections.java:236) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.scan(Reflections.java:203) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.<init>(Reflections.java:128) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.<init>(Reflections.java:169) [reflections-0.9.9.jar:na]
    at org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.findDtoFactoryVisitors(DtoFactoryVisitorRegistryGenerator.java:85) [che-core-ide-generators-4.0.0-M6-SNAPSHOT.jar:4.0.0-M6-SNAPSHOT]
    at org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.main(DtoFactoryVisitorRegistryGenerator.java:69) [che-core-ide-generators-4.0.0-M6-SNAPSHOT.jar:4.0.0-M6-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293) [exec-maven-plugin-1.4.0.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
13:39:18.952 [org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.main()] WARN  org.reflections.Reflections - could not create Dir using commons_vfs2 from url file:/home/che/assembly-sdk-war/target/classes. skipping.
java.lang.NoClassDefFoundError: org/apache/commons/vfs2/VFS
    at org.reflections.vfs.Vfs$DefaultUrlTypes$7.matches(Vfs.java:281) ~[reflections-0.9.9.jar:na]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:97) [reflections-0.9.9.jar:na]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:90) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.scan(Reflections.java:236) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.scan(Reflections.java:203) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.<init>(Reflections.java:128) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.<init>(Reflections.java:169) [reflections-0.9.9.jar:na]
    at org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.findDtoFactoryVisitors(DtoFactoryVisitorRegistryGenerator.java:85) [che-core-ide-generators-4.0.0-M6-SNAPSHOT.jar:4.0.0-M6-SNAPSHOT]
    at org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.main(DtoFactoryVisitorRegistryGenerator.java:69) [che-core-ide-generators-4.0.0-M6-SNAPSHOT.jar:4.0.0-M6-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293) [exec-maven-plugin-1.4.0.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs2.VFS
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_65]
    ... 15 common frames omitted
13:39:18.953 [org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.main()] WARN  org.reflections.Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/home/che/assembly-sdk-war/target/classes]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:108) ~[reflections-0.9.9.jar:na]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:90) ~[reflections-0.9.9.jar:na]
    at org.reflections.Reflections.scan(Reflections.java:236) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.scan(Reflections.java:203) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.<init>(Reflections.java:128) [reflections-0.9.9.jar:na]
    at org.reflections.Reflections.<init>(Reflections.java:169) [reflections-0.9.9.jar:na]
    at org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.findDtoFactoryVisitors(DtoFactoryVisitorRegistryGenerator.java:85) [che-core-ide-generators-4.0.0-M6-SNAPSHOT.jar:4.0.0-M6-SNAPSHOT]
    at org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.main(DtoFactoryVisitorRegistryGenerator.java:69) [che-core-ide-generators-4.0.0-M6-SNAPSHOT.jar:4.0.0-M6-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293) [exec-maven-plugin-1.4.0.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
13:39:20.537 [org.eclipse.che.util.DtoFactoryVisitorRegistryGenerator.main()] INFO  org.reflections.Reflections - Reflections took 2233 ms to scan 144 urls, producing 7450 keys and 34834 values
```

```
[INFO] Compiling 5 source files to /home/che/assembly-sdk-war/target/classes
warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.7'
1 warning
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (buildnumber) @ assembly-sdk-war ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
[INFO] Executed tasks
```

```
Dec 17, 2015 1:39:58 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://maven.codenvycorp.com:443: The target server failed to respond
Dec 17, 2015 1:39:58 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://maven.codenvycorp.com:443
```

```
[WARNING] Unknown file extension: /home/che/assembly-sdk/src/assembly/webapps/ROOT/WEB-INF/rewrite.config
[WARNING] Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions.
```

```
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'org.eclipse.che.examples:*'

[INFO] Copying files to /home/che/assembly-sdk/target/eclipse-che-4.0.0-M6-SNAPSHOT
[WARNING] Assembly file: /home/che/assembly-sdk/target/eclipse-che-4.0.0-M6-SNAPSHOT is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'org.eclipse.che.examples:*'

[INFO] Building zip: /home/che/assembly-sdk/target/eclipse-che-4.0.0-M6-SNAPSHOT.zip
Cleaning up unclosed ZipFile for archive /root/.m2/repository/org/eclipse/che/terminal/che-websocket-terminal/1.3-SNAPSHOT/che-websocket-terminal-1.3-SNAPSHOT.zip
Cleaning up unclosed ZipFile for archive /root/.m2/repository/org/eclipse/che/terminal/che-websocket-terminal/1.3-SNAPSHOT/che-websocket-terminal-1.3-SNAPSHOT.zip
Cleaning up unclosed ZipFile for archive /root/.m2/repository/org/eclipse/che/terminal/che-websocket-terminal/1.3-SNAPSHOT/che-websocket-terminal-1.3-SNAPSHOT.zip
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'org.eclipse.che.examples:*'
```

**Comment by ghost** [comment]
Any additional details on how to reproduce? Just built it on a clean CentOS 7.1 machine with Java 1.8 and Maven 3.3.3

**Comment by fulup-bzh** [comment]
Moving HOSTNAME=basename to  fullname  dns name resolve my 404 issue on OpenSuse-42. export HOSTNAME=host.domain.ext unfortunately the compilation from source code also fail. 

Effectively instruction to build from a naked standard distro would be nice.

**Comment by ghost** [comment]
@fulup-bzh can you elaborate on the hostname issues?

Che can be build with JDK 1.8 and Maven 3.1+. No further setup required. And at least 4GB RAM.

**Comment by fulup-bzh** [comment]
For HOSTNAME is't easy. If HOSTNAME="SNOOPY" it fails, if  hostname="SNOOPY.IOT.BZH" it works.

Building on a fresh OpenSuse-42 fails
- OpenJDK Runtime Environment (build 1.8.0_60-b27)
- Apache Maven 3.3.9

**Comment by ghost** [comment]
It should be Oracle JDK.

As to hostname, are you trying to launch Che remotely?

**Comment by fulup-bzh** [comment]
I was trying localhost but obviously my hostname was not set by DNS and not localhost. But even with localhost if your HOSTNAME is not fully defined it does not work.

For Oracle JDK, it was effectively the issue. This being said having to install Oracle Java is painful and hard to automate because of licence agreement. Would be nice if like for you Plugins you could support standard OpenJDK as shipped out of the box with any modern Linux distro.

Thank for the support.

**Comment by TylerJewell** [comment]
We've added a networking page to docs which should help avoid these issues in the future. We now also support openjdk for developing plug-ins.  I am going to close this issue now.  Feel free to reopen if this repeats.
