### ISSUE TITLE
Workspace startup fails spuriously in jdt.ls selenium tests

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11029]
Every couple of days, a large number of tests are not executed because workspaces fail to start up. I haven't been able to determine a pattern in which workspace fail to start, but there are two failure modes:
1. WSMaster seems to be restarted randomly. @riuvshin has reduced the parallel threads on our ci job to 2, and that seems to have alleviated the problem (i.e. havent' seen this failure mode since)
2. Docker failures:
```
2018-08-31 03:16:19,642[nio-8080-exec-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 331]   - Starting workspace 'che/workspace72c3jy' with id 'workspacevyoudao0uulzxxy6' by user 'che'
2018-08-31 03:16:20,020[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 392]   - Workspace 'che:workspacesjq8h2' with id 'workspace7p4un7k1sj9t8b6u' start failed
2018-08-31 03:16:20,021[aceSharedPool-2]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 402]   - Error response from docker API, status: 500, message: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 29\""


org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Error response from docker API, status: 500, message: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 29\""


	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.startContainer(DockerMachineStarter.java:216)
	at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.startMachine(DockerInternalRuntime.java:319)
	at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.internalStart(DockerInternalRuntime.java:221)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:146)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:368)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.infrastructure.docker.client.exception.DockerException: Error response from docker API, status: 500, message: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 29\""


	at org.eclipse.che.infrastructure.docker.client.DockerConnector.getDockerException(DockerConnector.java:1529)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.startContainer(DockerConnector.java:1209)
	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.startContainer(DockerMachineStarter.java:198)
	... 9 common frames omitted
```

Cursory googling seems this is related to kernel startup parameters? 

This is a real problem for us because we basically lose a day where we cannot say if our fixes worked.

**Comment by rhopp** [comment]
As selenium tests are being slowly decomissioned, I'm closing this one. 
@tsmaeder If you disagree, please reopen.
