### ISSUE TITLE
Unexpected fail of "WorkspaceDetailsMachineActionsTest" selenium test on docker infrastructure

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11089]
### Description
We have unexpected fail of "WorkspaceDetailsMachineActionsTest" selenium test on docker infrastructure. The test fails when check that a machine recipe in the **Edit the machine** window equals to "**eclipse/ubuntu_jdk8**" but found "**FROM eclipse/ubuntu_jdk8**". So we should investigate and resolve this problem.

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/399/Selenium_20tests_20report/

**Logs:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper$$Lambda$120/1892837893@22dd25b2 (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitSuccessCondition(SeleniumWebDriverHelper.java:1385)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitSuccessCondition(SeleniumWebDriverHelper.java:1394)
	at org.eclipse.che.selenium.pageobject.dashboard.workspaces.EditMachineForm.waitRecipeText(EditMachineForm.java:220)
	at org.eclipse.che.selenium.dashboard.workspaces.details.WorkspaceDetailsMachineActionsTest.checkEditOfMachineName(WorkspaceDetailsMachineActionsTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Screenshot:**
![org eclipse che selenium dashboard workspaces details workspacedetailsmachineactionstest checkeditofmachinename_time-1536179140938-millis](https://user-images.githubusercontent.com/7760565/45142242-b434da80-b1c0-11e8-81fd-662848945e09.png)

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11102
