### ISSUE TITLE
Unexpected fail of "CheckErrorsWarningsTabTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11086]
### Description
We have unexpected fail of "CheckErrorsWarningsTabTest" selenium test. It looks like something went wrong with a method which checks appears of the warning marker in the editor. So we should investigate and resolve this problem.

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/347/Selenium_20tests_20report/

**Logs:**
```
java.lang.AssertionError: expected [13] but found [12]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at org.eclipse.che.selenium.preferences.CheckErrorsWarningsTabTest.errorsWarningTest(CheckErrorsWarningsTabTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**Screenshot:**
![sss](https://user-images.githubusercontent.com/22724619/45140814-b8f78f80-b1bc-11e8-96ee-30850c5d8369.png)

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11099
