### ISSUE TITLE
Unexpected fail of FindUsagesBaseOperationTest selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11171]
### Description
We have unexpected fail of **FindUsagesBaseOperationTest** selenium test. The test  fails because cannot open a node in **Find Usage** panel. We should clarify reason and fix it.

**Failed selenium test:** FindUsagesBaseOperationTest

**Report with reproduced problem:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.xpath: //div[@id='gwt-debug-findUsages-panel']//div[text()='handleRequest(HttpServletRequest, HttpServletResponse)']/preceding::*[local-name()='svg'][2] (tried for 5 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.FindUsages.clickOnIconNodeInFindUsagesPanel(FindUsages.java:122)
	at org.eclipse.che.selenium.miscellaneous.FindUsagesBaseOperationTest.checkFindUsagesBaseOperation(FindUsagesBaseOperationTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Screenshot:**
![org eclipse che selenium miscellaneous findusagesbaseoperationtest checkfindusagesbaseoperation_time-1536631059775-millis](https://user-images.githubusercontent.com/7760565/45363301-d58e3000-b5df-11e8-97bf-fae11fdc257d.png)

**Comment by SkorikSergey** [comment]
We need to rework "FindUsages" selenium page object to use "SeleniumWebDriverHelper" class. It can fix instability.

**Comment by SkorikSergey** [comment]
Not reproduced.
