### ISSUE TITLE
Go to symbol feature do not show items with enabled C# language server

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#11258]
### Reproduction Steps
- Create a workspace based on .Net stack
- Create `dotnet-web-simple` project from IDE wizard
- Wait message about successfully initialization of the language server and appearance `bin` and `obj` folders
- Launch Assistant -> Go To Symbol
**Expected result:** The widget should show the file structure (namespace, methods, class)
**Actual result:** The widget is empty
**Additional info:**
![screencast-nimbus-screenshot everhelper me-2018 09 18-14-41-25](https://user-images.githubusercontent.com/1640058/45685185-358d5500-bb51-11e8-99f9-fb378501e41e.gif)

<details>

<summary>ws-agent-logs: </summary>

```
-------------------------
After invoking `Go To Symbol` we have exception on the dev/ console like:    
`Failed to handle notification textDocument/documentSymbol
  at OmniSharp.LanguageServerProtocol.Handlers.DocumentSymbolHandler+<Handle>d__6.MoveNext () [0x000b2] in <0bc4b0c0e112430cb137de284133b50d>:0 
2018-09-18 13:36:05,825[ool-11-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - [crit]: OmniSharp.Extensions.LanguageServer.LspRequestRouter
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.LanguageServerProtocol.Helpers.ToUri (System.String fileName) [0x00000] in <0bc4b0c0e112430cb137de284133b50d>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.LanguageServerProtocol.Handlers.DocumentSymbolHandler.ToDocumentSymbol (OmniSharp.Models.MembersTree.FileMemberElement node, System.Collections.Generic.List`1[T] symbolInformationContainer, System.String containerName) [0x0003e] in <0bc4b0c0e112430cb137de284133b50d>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.Extensions.LanguageServer.LspRequestRouter+<RouteRequest>d__11.MoveNext () [0x00161] in <43976da1155b4e5492c57f3d85e24f0e>:0 
--- End of stack trace from previous location where exception was thrown ---
2018-09-18 13:36:05,844[ool-11-thread-1]  [INFO ] [o.e.c.a.l.util.OperationUtil 91]     - Exception occurred in request
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal Error
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:162)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$request$1(RemoteEndpoint.java:121)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:149)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal Error
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	... 11 common frames omitted
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)`
```
</details>

<details>
<summary>js-console-logs: </summary>
Error computing hover tooltip
built-codeEdit-amd.js:27590 TypeError: Cannot read property 'a' of null
    at aQl (_app-0.js:19624)
    at $Hl._Hl [as lF] (_app-0.js:19362)
    at Object.computeHoverInfo (_app-0.js:10160)
    at DeferredService.computeHoverInfo (built-codeEdit-amd.js:44749)
    at Hover.<anonymous> (built-codeEdit-amd.js:35384)
    at Array.forEach (<anonymous>)
    at Hover.computeHoverInfo (built-codeEdit-amd.js:35380)
    at Tooltip._processInfo (built-codeEdit-amd.js:27560)
    at Tooltip.onHover (built-codeEdit-amd.js:27440)
    at built-codeEdit-amd.js:32315
built-codeEdit-amd.js:27589 Error computing hover tooltip
built-codeEdit-amd.js:27590 TypeError: Cannot read property 'a' of null
    at aQl (_app-0.js:19624)
    at $Hl._Hl [as lF] (_app-0.js:19362)
    at Object.computeHoverInfo (_app-0.js:10160)
    at DeferredService.computeHoverInfo (built-codeEdit-amd.js:44749)
    at Hover.<anonymous> (built-codeEdit-amd.js:35384)
    at Array.forEach (<anonymous>)
    at Hover.computeHoverInfo (built-codeEdit-amd.js:35380)
    at Tooltip._processInfo (built-codeEdit-amd.js:27560)
    at Tooltip.onHover (built-codeEdit-amd.js:27440)
    at built-codeEdit-amd.js:32315
```
</details>



**Diagnostics:**

**Comment by tsmaeder** [comment]
This seems to be a failure in the language server implementation. The format of the parameters to the "documentSymbol" call has not changed recently and it works with other language server. Likely not our bug.

**Comment by vkuznyetsov** [comment]
this bug is actual in 6.18.0-SNAPSHOT Can we try to update ls?

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
