### ISSUE TITLE
Unexpected fail of "CheckWorkingWithTabsByUsingContextMenuTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11276]
### Description
We have unexpected fail of "CheckWorkingWithTabsByUsingContextMenuTest" selenium test. It looks like something went wrong with method which checks editor tab appears. We should investigate and resolve this problem.

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/364/Selenium_20tests_20report/

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of all elements located by By.xpath: //div[@id='gwt-debug-multiSplitPanel-tabsPanel']//div[text()='htmlFile.html'] (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave7.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibilityOfAllElements(SeleniumWebDriverHelper.java:201)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitTabIsPresent(CodenvyEditor.java:1293)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitTabIsPresent(CodenvyEditor.java:1282)
	at org.eclipse.che.selenium.editor.CheckWorkingWithTabsByUsingContextMenuTest.checkWorkingWithTabsByUsingContextMenu(CheckWorkingWithTabsByUsingContextMenuTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Attachment**
![ggg](https://user-images.githubusercontent.com/22724619/45739530-e94b1f00-bbfb-11e8-8fd3-c39675e15d76.png)

**OS and version:**    
Che 6.12.0 ; Fedora 28 ; Chrome 69.0

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11277

**Comment by Ohrimenko1988** [comment]
Still actual.
Report with a reproduced problem:
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/364/Selenium_20tests_20report/

**Comment by Ohrimenko1988** [comment]
The bug has not been reproduced in the fresh report:
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/367/Selenium_20tests_20report/
