### ISSUE TITLE
Che in Che deployed on Docker: OOM can happen if host VM has not enough memory compared to requested for Che workspace

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11338]
### Reproduction Steps
- create a workspace using Che stack
- import eclipse che
- use command: "Deploy workspace agent"

**OS and version:**    
Che 6.11.1
docker
windows 10

**Diagnostics:** 

the preview url is giving a 404

end of log:
```
[INFO] [1m--- [0;32mmaven-compiler-plugin:3.7.0:testCompile[m [1m(default-testCompile)[m @ [36mche-core-api-project[0;1m ---[m
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /projects/che/wsagent/che-core-api-project/target/test-classes
/projects/che/wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/impl/handlers/CreateBaseProjectTypeHandlerTest.java:16: warning: [deprecation] Matchers in org.mockito has been deprecated
import static org.mockito.Matchers.any;
                         ^
/projects/che/wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/impl/handlers/CreateBaseProjectTypeHandlerTest.java:17: warning: [deprecation] Matchers in org.mockito has been deprecated
import static org.mockito.Matchers.eq;
                         ^
/projects/che/wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/search/MediaTypesExcludeMatcherTest.java:17: warning: [deprecation] Matchers in org.mockito has been deprecated
import static org.mockito.Matchers.anyString;
                         ^
/projects/che/wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/search/SearcherTest.java:479: warning: [DefaultCharset] Implicit use of the platform default charset, which can result in e.g. non-ASCII characters being silently replaced with '?' in many environments
      Files.write(content.getBytes(), lastUpdatedFile.toFile());
                                  ^
    (see http://errorprone.info/bugpattern/DefaultCharset)
  Did you mean 'Files.write(content.getBytes(UTF_8), lastUpdatedFile.toFile());' or 'Files.write(content.getBytes(Charset.defaultCharset()), lastUpdatedFile.toFile());'?
/projects/che/wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/fs/server/impl/FsOperationsTest.java:403: warning: [DefaultCharset] Implicit use of the platform default charset, which can result in e.g. non-ASCII characters being silently replaced with '?' in many environments
    try (PrintWriter p = new PrintWriter(fsOperations.write(file.toPath()))) {
                         ^
    (see http://errorprone.info/bugpattern/DefaultCharset)
  Did you mean 'try (PrintWriter p = new PrintWriter(new BufferedWriter(new OutputStreamWriter(fsOperations.write(file.toPath()), UTF_8)))) {' or 'try (PrintWriter p = new PrintWriter(new BufferedWriter(new OutputStreamWriter(fsOperations.write(file.toPath()), Charset.defaultCharset())))) {'?
5 warnings
[INFO] 
[INFO] [1m--- [0;32mmaven-surefire-plugin:2.20.1:test[m [1m(default-test)[m @ [36mche-core-api-project[0;1m ---[m
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running [1mTestSuite[m
Exception in thread "LuceneSearcherInitThread" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:541)
	at java.lang.StringBuilder.append(StringBuilder.java:175)
	at java.lang.StringBuilder.append(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:488)
	at java.lang.StringBuilder.append(StringBuilder.java:166)
	at java.lang.StringBuilder.append(StringBuilder.java:76)
	at com.google.common.io.CharStreams.copy(CharStreams.java:76)
	at com.google.common.io.CharStreams.toStringBuilder(CharStreams.java:105)
	at com.google.common.io.CharStreams.toString(CharStreams.java:92)
	at org.eclipse.che.api.search.server.impl.LuceneSearcher.addFile(LuceneSearcher.java:409)
	at org.eclipse.che.api.search.server.impl.LuceneSearcher.access$000(LuceneSearcher.java:98)
	at org.eclipse.che.api.search.server.impl.LuceneSearcher$1.visitFile(LuceneSearcher.java:371)
	at org.eclipse.che.api.search.server.impl.LuceneSearcher$1.visitFile(LuceneSearcher.java:368)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.eclipse.che.api.search.server.impl.LuceneSearcher.add(LuceneSearcher.java:366)
	at org.eclipse.che.api.search.server.impl.LuceneSearcher.lambda$initialize$0(LuceneSearcher.java:158)
	at org.eclipse.che.api.search.server.impl.LuceneSearcher$$Lambda$26/1296928719.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
2018-09-25 07:35:59,338[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 66]   - Attribute name conflict. Project type child could not be registered as attribute declaration parent_const is duplicated in its ancestor(s).
2018-09-25 07:35:59,347[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 66]   - Attribute name conflict. Project type child could not be registered as attribute declaration parent_const is duplicated in its ancestor(s).
2018-09-25 07:35:59,374[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 164]  - Could not register Project Type ID is null or invalid (only Alphanumeric, dash, point and underscore allowed): org.eclipse.che.api.project.server.type.ProjectTypeTest$4
2018-09-25 07:35:59,375[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 171]  - Could not register Project Type with null or empty display name: id2
2018-09-25 07:35:59,375[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 164]  - Could not register Project Type ID is null or invalid (only Alphanumeric, dash, point and underscore allowed): org.eclipse.che.api.project.server.type.ProjectTypeTest$2
2018-09-25 07:35:59,376[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 164]  - Could not register Project Type ID is null or invalid (only Alphanumeric, dash, point and underscore allowed): org.eclipse.che.api.project.server.type.ProjectTypeTest$3
2018-09-25 07:35:59,376[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 171]  - Could not register Project Type with null or empty display name: id1
2018-09-25 07:35:59,386[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 164]  - Could not register Project Type ID is null or invalid (only Alphanumeric, dash, point and underscore allowed): org.eclipse.che.api.project.server.type.ProjectTypeTest$4
2018-09-25 07:35:59,387[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 171]  - Could not register Project Type with null or empty display name: id2
2018-09-25 07:35:59,388[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 164]  - Could not register Project Type ID is null or invalid (only Alphanumeric, dash, point and underscore allowed): org.eclipse.che.api.project.server.type.ProjectTypeTest$2
2018-09-25 07:35:59,388[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 164]  - Could not register Project Type ID is null or invalid (only Alphanumeric, dash, point and underscore allowed): org.eclipse.che.api.project.server.type.ProjectTypeTest$3
2018-09-25 07:35:59,390[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 171]  - Could not register Project Type with null or empty display name: id1
2018-09-25 07:35:59,390[main]             [ERROR] [.c.a.p.s.t.ProjectTypeRegistry 204]  - Could not register Project Type: notRegParent : Unregistered parent Type: i-parent
```

**Comment by eivantsov** [comment]
@apupier how much RAM does your Docker VM have?

**Comment by apupier** [comment]
> how much RAM does your Docker VM have?

it had default values. I just checked and it is 2G which seems far too low for the 7G indicated for the workspace. But how is it possible to allocate 7G workspace when the host vm has only 2G?

**Comment by eivantsov** [comment]
Che does not check available memory.

**Comment by apupier** [comment]
seems that it would be great; it would avoid to have OOM.

**Comment by eivantsov** [comment]
@apupier when on OpenShift the infrastructure does it for you:

![image](https://user-images.githubusercontent.com/5337267/46273906-18e51a00-c560-11e8-9c9d-80801b89fad4.png)

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
