### ISSUE TITLE
Unexpected fail of CreateWorkspaceFromNodeStackTest selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11419]
### Description
We have unexpected fail of **CreateWorkspaceFromNodeStackTest** selenium test. The test sometimes fails because "web-nodejs-simple:run" processes tab is not active after refreshing web page . We should clarify reason and fix it.

**Failed selenium test:** CreateWorkspaceFromNodeStackTest

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //div[@active]//a[@href]' (tried for 20 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.Consoles.waitPreviewUrlIsPresent(Consoles.java:429)
	at org.eclipse.che.selenium.stack.CreateWorkspaceFromNodeStackTest.checkWebNodejsSimpleProjectCommands(CreateWorkspaceFromNodeStackTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/426/Selenium_20tests_20report/

**Screenshot:**
![org eclipse che selenium stack createworkspacefromnodestacktest checkwebnodejssimpleprojectcommands_time-1538342296292-millis](https://user-images.githubusercontent.com/7760565/46276975-62d2fd80-c56a-11e8-81b3-12fedc223daf.png)

**Comment by SkorikSergey** [comment]
This issue is still reproduces in Che 6.17.0-SNAPSHOT.

**Comment by rhopp** [comment]
Not relevant anymore. Closing.
