### ISSUE TITLE
Unexpected fail of "TheiaBuildPluginTest" selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11416]
### Description
We have unexpected fail of "TheiaBuildPluginTest" selenium test. It looks like something went wrong with a method which checks the editor tab appearance. We should investigate and resolve this problem. 

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.xpath: //ul[@class='p-TabBar-content']//li[@title='Untitled.txt'] (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave7.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:144)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:154)
	at org.eclipse.che.selenium.pageobject.theia.TheiaEditor.waitEditorTab(TheiaEditor.java:74)
	at org.eclipse.che.selenium.pageobject.theia.TheiaTerminal.getTerminalOutput(TheiaTerminal.java:143)
	at org.eclipse.che.selenium.pageobject.theia.TheiaTerminal.lambda$waitTerminalOutput$0(TheiaTerminal.java:122)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.lambda$waitSuccessCondition$24(SeleniumWebDriverHelper.java:1439)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitSuccessCondition(SeleniumWebDriverHelper.java:1439)
	at org.eclipse.che.selenium.pageobject.theia.TheiaTerminal.waitTerminalOutput(TheiaTerminal.java:121)
	at org.eclipse.che.selenium.theia.TheiaBuildPluginTest.pluginShouldBeBuilt(TheiaBuildPluginTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[@class='p-TabBar-content']//li[@title='Untitled.txt']"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 3.10.0-862.11.6.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 28 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave7.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=LINUX, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:45503}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706), userDataDir=/tmp/.org.chromium.Chromium.swsnHT}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=68.0.3440.106, browserConnectionEnabled=false, nativeEvents=true, webdriver.remote.sessionid=aae256edfc25afff71a43d52817e9097, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: aae256edfc25afff71a43d52817e9097
*** Element info: {Using=xpath, value=//ul[@class='p-TabBar-content']//li[@title='Untitled.txt']}
	at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at org.eclipse.che.selenium.core.SeleniumWebDriver.findElement(SeleniumWebDriver.java:133)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
```
**Screenshot:**
![retret](https://user-images.githubusercontent.com/22724619/46274564-914cda80-c562-11e8-9967-20dcc52e58f7.png)

**Report with a reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/377/Selenium_20tests_20report/

**Comment by Ohrimenko1988** [comment]
Still actual https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/378/Selenium_20tests_20report/

**Comment by Ohrimenko1988** [comment]
The reason is detected. The "DEPLOY_CHE_PLUGIN_REGISTRY=true" variable should be exported in the CI job configuration.

**Comment by Ohrimenko1988** [comment]
The new reason of fail. It looks like something went wrong with method which waits "New Dialog" form appears.

**Log**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper$$Lambda$86/1820825920@2f9ec6fe (tried for 60 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave7.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitSuccessCondition(SeleniumWebDriverHelper.java:1439)
	at org.eclipse.che.selenium.pageobject.theia.TheiaTerminal.waitTerminalOutput(TheiaTerminal.java:125)
	at org.eclipse.che.selenium.theia.TheiaBuildPluginTest.pluginShouldBeBuilt(TheiaBuildPluginTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``` 

**Report with reproduced problem**
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/383/Selenium_20tests_20report/

**Screenshot**
![qwe](https://user-images.githubusercontent.com/22724619/46595198-eac38500-cadf-11e8-97f2-51b594cbb193.png)

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11523
