### ISSUE TITLE
[JDT LS] Cannot launch tests after git importing of maven project

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#11511]
### Reproduction Steps
* Import maven project into IDE: https://github.com/Tarrantella/EclipseCheTestRepo-2eiob.git
* Set the project as maven
* Wait resolving dependencies and initialization of LS.
* Expand tree to `/EclipseCheTestRepo-2eiob/src/test/java/org/eclipse/che/examples` path
* Select for example `org.eclipse.che.examples` package
* Invoke context menu. Run Test -> Run TestNG Test
**Expected result:** Tests from the package should be run. The result should be shown in the test result widget. 
**Actual result:** We have event like `Running Tests... Unexpected error`. In the widget console next exceptions:
``` java
Exception in thread "main" java.lang.NoClassDefFoundError: org/testng/TestNG
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.testng.CheTestNGLauncher.main(CheTestNGLauncher.java:37)
Caused by: java.lang.ClassNotFoundException: org.testng.TestNG
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

![screencast-che-eclipse-che 172 19 20 240 nip io-2018 10 05-14-30-14](https://user-images.githubusercontent.com/1640058/46532937-88823e80-c8ab-11e8-8e74-853b9737886b.gif)

**Additional info:** 
*Web socket data:*
`To Test Server:` `{"jsonrpc":"2.0","method":"testing/runTest","id":"8","params":{"listOfTestClasses":[],"contextType":"FOLDER","filePath":"/EclipseCheTestRepo-2eiob/src/test/java/org/eclipse/che/examples","projectPath":"/EclipseCheTestRepo-2eiob","cursorOffset":0,"frameworkName":"testng","debugModeEnable":false}}`

`From Test Server:` `{"jsonrpc":"2.0","id":"8","error":{"code":-27104,"message":"Unexpected error"}}`

**OS and version:**    OpenShift multiuser, JDT LS assembly,  Che 6.12.0 ; Chrome 68; Fedora 28;

**Comment by musienko-maxim** [comment]
Looks like in this case i did not wait for resolving dependencies. After full resolving all works as well.
