### ISSUE TITLE
Starting 30 workspaces concurrentyly,sometime one or two workspace can not start up

### ISSUE THREAD

**Issue by liubin10** [eclipse-che/che#11548]
### Description
 
Hi
When I start 30 workspaces concurrently through testing tool, sometimes one or two workspaces can not start up.
And If I raise to 100 starting, the che server will broken down and restart.
So Whether Che can not operate high concurrently ?

**Comment by liubin10** [comment]
Hello,@skabashnyuk
Sorry, the log file is too large.
There are some error below that I picked up from log.Hope these can help you.

2018-10-12 15:28:33,572[equestProcessor]  [DEBUG] [.e.c.a.c.j.c.RequestDispatcher 41]   - Dispatching request: org.eclipse.che.api.core.jsonrpc.commons.JsonRpcRequest@5c84f551, endpoint: 1619938822<-:->master-websocket-endpoint
2018-10-12 15:28:33,572[equestProcessor]  [DEBUG] [.e.c.a.c.j.c.RequestDispatcher 53]   - Request has no ID -> it is a notification
2018-10-12 15:28:33,573[equestProcessor]  [DEBUG] [o.e.c.a.c.n.EventService 106]        - Publish event {"time":"2018-10-12T15:28:32.785462869+08:00","text":"Exec Agent binary will be downloaded remotely","runtimeId":{"ownerId":"41a05f45bc0f40fdbc610c017385debb","envName":"default","workspaceId":"workspacejdvdv291zqubt4xf"},"stream":"STDOUT","installer":"org.eclipse.che.exec","machineName":"dev-machine"} for org.eclipse.che.api.core.notification.RemoteSubscriptionManager$$Lambda$134/586563773@544aec54
2018-10-12 15:28:33,573[equestProcessor]  [DEBUG] [o.e.c.a.c.n.EventService 106]        - Publish event {"time":"2018-10-12T15:28:32.785462869+08:00","text":"Exec Agent binary will be downloaded remotely","runtimeId":{"ownerId":"41a05f45bc0f40fdbc610c017385debb","envName":"default","workspaceId":"workspacejdvdv291zqubt4xf"},"stream":"STDOUT","installer":"org.eclipse.che.exec","machineName":"dev-machine"} for org.eclipse.che.api.logger.ErrorInstallerLogEventLogger@3e2cb5c
2018-10-12 15:28:34,789[ei.com:8080/...]  [WARN ] [k.c.d.i.WatchConnectionManager 192]  - Exec Failure
java.net.SocketTimeoutException: sent ping but didn't receive pong within 1000ms (after 305 successful ping/pongs)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:545)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:529)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2018-10-12 15:28:34,789[ei.com:8080/...]  [WARN ] [k.c.d.i.WatchConnectionManager 192]  - Exec Failure
java.net.SocketTimeoutException: sent ping but didn't receive pong within 1000ms (after 17 successful ping/pongs)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:545)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:529)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


2018-10-12 15:28:17,760[io-8080-exec-13]  [DEBUG] [a.c.w.i.BasicWebSocketEndpoint 130]  - Web socket session error
2018-10-12 15:28:17,761[io-8080-exec-13]  [DEBUG] [a.c.w.i.BasicWebSocketEndpoint 131]  - Endpoint: 1559702741<-:->master-websocket-endpoint
2018-10-12 15:28:17,761[io-8080-exec-13]  [DEBUG] [a.c.w.i.BasicWebSocketEndpoint 132]  - Error: {}
java.io.IOException: Unable to unwrap data, invalid status [CLOSED]
	at org.apache.tomcat.util.net.SecureNioChannel.read(SecureNioChannel.java:618)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1248)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1221)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1194)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:72)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2018-10-12 15:28:17,762[io-8080-exec-13]  [DEBUG]

2018-10-12 15:28:11,710[ted-scheduler-0]  [DEBUG] [o.e.c.c.s.e.LoggedRunnable 54]       - Invoking run method of class org.eclipse.che.multiuser.api.workspace.activity.MultiUserWorkspaceActivityManager instance org.eclipse.che.multiuser.api.workspace.activity.MultiUserWorkspaceActivityManager@49077dd8
2018-10-12 15:28:11,727[ted-scheduler-0]  [DEBUG] [o.e.c.c.s.e.LoggedRunnable 59]       - Method of class org.eclipse.che.multiuser.api.workspace.activity.MultiUserWorkspaceActivityManager instance org.eclipse.che.multiuser.api.workspace.activity.MultiUserWorkspaceActivityManager@49077dd8 complete  at 0  sec
2018-10-12 15:28:14,194[ei.com:8080/...]  [WARN ] [k.c.d.i.WatchConnectionManager 192]  - Exec Failure
java.net.SocketTimeoutException: sent ping but didn't receive pong within 1000ms (after 303 successful ping/pongs)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:545)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:529)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


2018-10-12 15:27:40,505[o-8080-exec-273]  [WARN ] [c.h.c.a.client.util.IamCasUtil 582]  - no project info
2018-10-12 15:27:41,532[o-8080-exec-293]  [WARN ] [c.h.c.a.client.util.IamCasUtil 582]  - no project info
2018-10-12 15:27:41,685[ei.com:8080/...]  [ERROR] [k.c.d.i.WatchConnectionManager 267]  - Invalid event type
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.parseLong(Long.java:631)
	at java.text.DigitList.getLong(DigitList.java:195)
	at java.text.DecimalFormat.parse(DecimalFormat.java:2051)
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2162)
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at org.eclipse.che.workspace.infrastructure.kubernetes.util.ContainerEvents.convertEventTimestampToDate(ContainerEvents.java:34)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesPods$4.happenedAfterWatcherInitialization(KubernetesPods.java:360)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesPods$4.eventReceived(KubernetesPods.java:339)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesPods$4.eventReceived(KubernetesPods.java:315)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:227)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
