### ISSUE TITLE
Transaction rollback exception in JSON_RPC subsystem

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11601]
### Description
We got next exception:
<details>

```
javax.persistence.RollbackException: Transaction "rolled back" because transaction was set to RollbackOnly.
    at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:143)
    at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:75)
    at org.eclipse.che.multiuser.api.permission.server.PermissionsManager.exists(PermissionsManager.java:197)
    at org.eclipse.che.multiuser.api.permission.server.PermissionCheckerImpl.hasPermission(PermissionCheckerImpl.java:35)
    at org.eclipse.che.multiuser.api.permission.server.AuthorizedSubject.hasPermission(AuthorizedSubject.java:49)
    at org.eclipse.che.multiuser.machine.authentication.server.MachineTokenAuthorizedSubject.hasPermission(MachineTokenAuthorizedSubject.java:41)
    at org.eclipse.che.multiuser.permission.workspace.server.filters.InstallerServicePermissionFilter.doAccept(InstallerServicePermissionFilter.java:65)
    at org.eclipse.che.multiuser.api.permission.server.jsonrpc.JsonRpcPermissionsFilterAdapter.accept(JsonRpcPermissionsFilterAdapter.java:29)
    at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.filter(RequestHandlerManager.java:293)
    at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.access$2400(RequestHandlerManager.java:48)
    at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToNoneHandler.handle(RequestHandlerManager.java:404)
    at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToNoneHandler.access$1700(RequestHandlerManager.java:393)
    at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:254)
    at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:56)
    at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
    at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
</details>
@skabashnyuk suggested that we have a bug in the reusage of transactions in the JSON_RPC initiated threads.

Aditional details: https://errortracking.prod-preview.openshift.io/openshift_io/che6master/issues/8746/

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
In this particular case, we have such log because `rollbackOnly` is missing for `Transactional` annotation on https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/multiuser/api/che-multiuser-api-permission/src/main/java/org/eclipse/che/multiuser/api/permission/server/jpa/AbstractJpaPermissionsDao.java#L61 and the same time Database exception is rethrown as `ServerException` here https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/spi/jpa/JpaWorkerDao.java#L88
It's needed to revise `rollbackOn` values on all `@Transtactional` we use.
Note this exception is not related to JSON RPC at all.
