### ISSUE TITLE
Adapt the "TheiaBuildPluginTest" selenium test to the new terminal tab titles

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11604]
### Description
We have unexpected fail of "TheiaBuildPluginTest" selenium test. It looks like a template of the tab title was changed. We should adapt existed test to the new behavior.

**Log**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.xpath: //div[@class='p-TabBar-tabLabel' and text()='Remote terminal 0'] (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:144)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:154)
	at org.eclipse.che.selenium.pageobject.theia.TheiaTerminal.waitTab(TheiaTerminal.java:113)
	at org.eclipse.che.selenium.theia.TheiaBuildPluginTest.pluginShouldBeBuilt(TheiaBuildPluginTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Screenshot**
![ffff](https://user-images.githubusercontent.com/22724619/46852900-3d18e480-ce05-11e8-9a12-a43a02568672.png)

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11607
