### ISSUE TITLE
Unexpected fail of selenium tests from 'refactor.types' package 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11779]
### Description
We have unexpected fail of selenium tests from "**refactor.types**" package. The tests sometimes fail because a class tab in the **Editor** unexpectedly closes after this class renaming. We should clarify reason and fix it.

**Failed selenium test:** GenericsTest, RenameTypeTest, TestAnnotationTest, TestEnumerationsTest.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //div[@id='gwt-debug-editorPartStack-contentPanel']//div[@active]//div[@class='textviewContent' and @contenteditable='true']' (tried for 20 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:169)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitActive(CodenvyEditor.java:369)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitActive(CodenvyEditor.java:374)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.getVisibleTextFromEditor(CodenvyEditor.java:383)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.lambda$waitTextIntoEditor$4(CodenvyEditor.java:480)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.lambda$waitForText$3(CodenvyEditor.java:468)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitForText(CodenvyEditor.java:465)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitTextIntoEditor(CodenvyEditor.java:480)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.waitTextIntoEditor(CodenvyEditor.java:489)
	at org.eclipse.che.selenium.refactor.types.RenameTypeTest.testCase(RenameTypeTest.java:204)
	at org.eclipse.che.selenium.refactor.types.RenameTypeTest.test9(RenameTypeTest.java:154)
```
**Browser logs:**
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/413/Selenium_20tests_20report/webdriver-logs/org.eclipse.che.selenium.refactor.types.RenameTypeTest.test4_time-1541027611614-millis.log

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/410/Selenium_20tests_20report/

**Screenshot:**
![org eclipse che selenium refactor types renametypetest test9_time-1540811792617-millis](https://user-images.githubusercontent.com/7760565/47723460-3db2d700-dc5d-11e8-981b-bd681dd551a5.png)

**Comment by SkorikSergey** [comment]
Fixed by https://github.com/eclipse/che/pull/12086.
