### ISSUE TITLE
Sometimes jdt.ls is failed to initialize on che.openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#11856]
### Description
Sometimes jdt.ls is failed to initialize on che.openshift.io
Original issue - https://github.com/openshiftio/openshift.io/issues/4507

### Reproduction Steps
Steps to reproduce:
- create & start workspace via UD (user dashboard) based on `vertx` stack with `vertx-health-check-booster`
- Once workspace is started there are error logs in the `dev-machine` console:

```
Message: Updating workspace folders: Adding 1 folder(s), removing 0 folders.
2018-10-30 17:33:44,156[ool-13-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - Oct 30, 2018 5:33:44 PM Error updating workspace folders
2018-10-30 17:33:44,163[kspaceUpdater-0]  [ERROR] [.c.p.j.l.WorkspaceSynchronizer 59]   - Failed to update workspace. Result code: '0', message: 'Error updating workspace folders'. Added projects: '[file:///projects/vertx-health-checks-booster]', removed projects: '[]'
2018-10-30 17:33:44,166[ool-13-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - Oct 30, 2018 5:33:44 PM Error updating workspace folders
Could not set the project description for 'health-check-vertx' because the project description file (.project) is out of sync with the file system.
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1262)
org.eclipse.core.internal.resources.ResourceException(/health-check-vertx)[274]: java.lang.Exception: Could not set the project description for 'health-check-vertx' because the project description file (.project) is out of sync with the file system.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.m2e.core.project.configurator.AbstractProjectConfigurator.addNature(AbstractProjectConfigurator.java:177)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.m2e.core.project.configurator.AbstractProjectConfigurator.addNature(AbstractProjectConfigurator.java:161)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:144)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.addJavaNature(AbstractJavaProjectConfigurator.java:191)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:153)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$3.runInWorkspace(ProjectsManager.java:164)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:133)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:134)
 
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:128)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)

```

- ERROR: open any java file and try to do content assist via `Cntrl - space` - Intellisense does not work and there is an NPE error message in dev machine logs. 

```
 Exception occurred in request
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
Caused by: java.lang.NullPointerException: null
	... 13 common frames omitted
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at org.eclipse.che.api.languageserver.util.OperationUtil.lambda$doInParallel$0(OperationUtil.java:83)
	at org.eclipse.che.api.languageserver.TextDocumentService$6.handleResult(TextDocumentService.java:461)
	at org.eclipse.che.api.languageserver.TextDocumentService$6.handleResult(TextDocumentService.java:478)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
```

 
Also, sometimes the error after workspace startup looks the following way:

```
failed to scan /projects
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5706)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:221)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:114)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:128)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
Java Model Exception: Core Exception [code 0] Failed to scan /projects
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5749)
	... 15 more
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:52)
Caused by: java.nio.file.NoSuchFileException: /projects/console-java-simple/.git/index.lock
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
```

**OS and version:**    

che.openshift.io / 6.13.0

**Comment by ibuziuk** [comment]
@tsmaeder @fbricon your input might be really valuable

**Comment by gorkem** [comment]
I also see this, it almost feels like it will recover if there was a way to clean the project and reimport.

**Comment by Katka92** [comment]
Today I've seen this issue too. I saw this ```failed to scan /projects``` error. When I restarted workspace all worked fine.

**Comment by Katka92** [comment]
Hi guys, any progress here? I'm still facing this issue, as from today:
![screenshot from 2019-01-03 10-10-36](https://user-images.githubusercontent.com/29278800/50630372-e2dd7a80-0f40-11e9-9e4d-9c3147489921.png)

**Comment by Katka92** [comment]
Hi @tsmaeder I have the same feeling from the behaviour I can see in dashboard. Today I've tried to reproduce that. This error shows up when project was still being imported as shown in screenshot [1]. Once the project was loaded it writes more logs here [2]. Can it happen that clonning project is not finished when scan happens?

[1]
![screenshot from 2019-01-16 13-56-20_1](https://user-images.githubusercontent.com/29278800/51250642-4fbc3000-1997-11e9-8ad1-2f60ea8ae369.png)

[2]
![screenshot from 2019-01-16 13-57-00_2](https://user-images.githubusercontent.com/29278800/51250646-55197a80-1997-11e9-907c-9455404aff52.png)

**Comment by fbricon** [comment]
do you use Eclipse's smart project importer after the git clone? Definitely looks like 2 processes are touching the same files

**Comment by Katka92** [comment]
I am not sure what is the process behind, but what I do is that I try to create workspace via dashboard - I click ``Create Worksapce``` button, choose a codebase, select project to import (vertx-http-booster one) and click on a button to create and open that workspace. That's all. Then I'm waiting for the workspace to start and to import the project and I can see these errors.

**Comment by tsmaeder** [comment]
The strange things is that it seems to fail when updating the project description. This means writing to the .project file (at org.eclipse.core.internal.resources.Project.setDescription() (Project.java#1262). 
However this is a file that jdt.ls creates itself, it is not created by the git checkout.

**Comment by ibuziuk** [comment]
@invincibleJai  maybe you could help? Does the analytics server touch the `.project` file (AFAIK it is not the case)

**Comment by invincibleJai** [comment]
@ibuziuk @tsmaeder for analytics LS, we just register for `pom.xml/package.json/requiremts.txt` and based on events like `onDidOpenTextDocument`, files content are being parsed to get dependency and it's version. we are not doing any write to any file. Not sure why is this the case as nothing has been changed in che from a long time. Let us know if you feel something is wrong.

**Comment by ibuziuk** [comment]
@invincibleJai thanks for update - currently it was just an assumption that two ls (bayesian and java) could access the same resources at the point of time, which would produce race condition conflict (based on your comment it looks like it is not the case and byesian LS does nothing with `.project` file)
