### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#11893]
### Description

It should not be uncaught expception.

### Reproduction Steps

Open new workspace.
But it may be caused by timing issues.

**OS and version:**    

ChromeOS Version 70.0.3538.76 (Official Build) (64-bit)

Che nightly build.

**Diagnostics:** 

```
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at a.send (https://che-camino.c.pizzafactory.jp/workspace-loader/loader/bundle.js:1:12170)
    at e.send (https://che-camino.c.pizzafactory.jp/workspace-loader/loader/bundle.js:1:9115)
    at e.request (https://che-camino.c.pizzafactory.jp/workspace-loader/loader/bundle.js:1:969)
    at e.request (https://che-camino.c.pizzafactory.jp/workspace-loader/loader/bundle.js:1:15982)
    at e.fetchClientId (https://che-camino.c.pizzafactory.jp/workspace-loader/loader/bundle.js:1:14937)
    at https://che-camino.c.pizzafactory.jp/workspace-loader/loader/bundle.js:1:14055
send @ index.js:189
e.send @ websocket-client.ts:102
e.request @ json-rpc-client.ts:117
e.request @ che-json-rpc-api-service.ts:85
e.fetchClientId @ che-json-rpc-master-api.ts:220
(anonymous) @ che-json-rpc-master-api.ts:123
Promise.then (async)
e.connect @ che-json-rpc-master-api.ts:122
(anonymous) @ che-json-rpc-master-api.ts:51
(anonymous) @ websocket-client.ts:107
e.callHandlers @ websocket-client.ts:107
(anonymous) @ websocket-client.ts:51
```

**Comment by skabashnyuk** [comment]
Is this reproducible?

**Comment by monaka** [comment]
Yes in my environment, Azure AKS. Possibly environment depend. I'm not sure but I suspect it is caused by Ingress. Since it requires a few minutes to respond Ingress. I'm writing patches now.

**Comment by skabashnyuk** [comment]
@vitaliy-guliy @evidolob @ashumilova wdyt? Looks like this comes from workspace-loader app.
