### ISSUE TITLE
Provide warning/errors when two projects with same artifactid are present in the same workspace

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11912]
### Description

I imported https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/projects using a Che java stack using Che 6.13.1 (was reported to me also with 6.9) using this commit https://github.com/RedHatWorkshops/dayinthelife-integration/commit/82919e47354aea6833b22d9b58caedf14ad22640

the module is recognized as a Maven project, the java folder seems to be recognized
there are some errors in dev-machine output.

### Reproduction Steps
- create a workspace using Java che stack
- click on "import project"
- use https://github.com/RedHatWorkshops/dayinthelife-integration as URL
![image](https://user-images.githubusercontent.com/1105127/48352519-22988c00-e68d-11e8-87f0-7352b3ed320f.png)
- use "blank" as top-level is just a container directory
- go to projects folder
- right-click on location-gateway for instance and then "Convert to project" and choose Maven
- wait..... that "Importing Maven projects" is finished
- open CamelRoutes.java file
--> there is no completion avilable
```
2018/11/12 14:10:01 Start new terminal.
2018-11-12 14:10:05,128[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: Init...
2018-11-12 14:10:05,193[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 0% Starting Java Language Server 
2018-11-12 14:10:05,202[rverInitializer]  [WARN ] [o.e.l.j.s.GenericEndpoint 171]       - Unsupported notification method: json/schemaAssociations
2018-11-12 14:10:05,265[rverInitializer]  [WARN ] [o.e.l.j.s.GenericEndpoint 171]       - Unsupported notification method: json/schemaAssociations
2018-11-12 14:10:05,269[rverInitializer]  [INFO ] [.a.l.LanguageServerInitializer 222]  - Initialized language server 'org.eclipse.che.plugin.java.languageserver'
2018-11-12 14:10:05,358[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 20% Starting Java Language Server 
2018-11-12 14:10:06,603[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 37% Starting Java Language Server 
2018-11-12 14:10:06,611[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server 
2018-11-12 14:10:06,611[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server 
2018-11-12 14:10:06,615[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Started: Ready
2018-11-12 14:10:06,708[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server 
2018-11-12 14:11:57,143[pool-9-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Message: Updating workspace folders: Adding 1 folder(s), removing 0 folders.
2018-11-12 14:11:57,846[pool-9-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - Nov 12, 2018 2:11:57 PM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
Project for 'file:///projects/dayinthelife-integration' not found
java.lang.IllegalArgumentException: Project for 'file:///projects/dayinthelife-integration' not found
	at org.eclipse.che.jdt.ls.extension.core.internal.CheDelegateCommandHandler.executeCommand(CheDelegateCommandHandler.java:118)
	at org.eclipse.che.jdt.ls.extension.core.internal.plain.GetSourceFoldersCommand.execute(GetSourceFoldersCommand.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:433)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:764)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
2018-11-12 14:11:57,851[pool-9-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - Nov 12, 2018 2:11:57 PM Error in calling delegate command handler
 
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.jdt.ls.extension.core.internal.CheDelegateCommandHandler.executeCommand(CheDelegateCommandHandler.java:118)
	at org.eclipse.che.jdt.ls.extension.core.internal.plain.GetSourceFoldersCommand.execute(GetSourceFoldersCommand.java:47)
java.lang.IllegalArgumentException: Project for 'file:///projects/dayinthelife-integration' not found
Project for 'file:///projects/dayinthelife-integration' not found
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:433)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:764)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
 
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
```

the java Language Server is marked as activated:
![image](https://user-images.githubusercontent.com/1105127/48355098-8c1b9900-e693-11e8-8901-8549bf72cde4.png)

**OS and version:**    

Che 6.13.1

**Diagnostics:**

**Comment by tsmaeder** [comment]
The project is malformed as far as jdt.ls is concerned: jdt.ls does not support having the same maven project (by artifact id) in the workspace. The projects projects/location-gateway, projects/location-service and /support/location-service all have the same artifact id.
The underlying problem is that the eclipse resource name is encoded in the .project file, so just mounting the projects at an arbitrary location would change the name people see when opening the project in an eclipse instance.

**Comment by apupier** [comment]
> The project is malformed as far as jdt.ls is concerned: jdt.ls does not support having the same maven project (by artifact id) in the workspace. The projects projects/location-gateway, projects/location-service and /support/location-service all have the same artifact id.

effectively, just by changing the id is fixing the issue.
I will change in the repository.
Would it be possible to have a warning or an error reported in Che UI when it happens?

**Comment by tsmaeder** [comment]
> Would it be possible to have a warning or an error reported in Che UI when it happens?

Currently, we have no back channel for this case. That code should be refactored, long-term, but not sure when that will happen.
