### ISSUE TITLE
Workspace is going to be STOPPED. Reason: Container of machine 'dev-machine' unexpectedly stopped. Please check that container is designed to run in non-interactive terminal.

### ISSUE THREAD

**Issue by nbon12** [eclipse-che/che#11985]
### Description
![workspace_stopped](https://user-images.githubusercontent.com/17408265/48728767-e83a6c00-ec03-11e8-9cf1-9dedd83c4f36.png)
The workspace suddenly stops with no warning. This happens frequently, about once or twice per hour. This happens while I am coding in a workspace, or if I'm browsing on another tab in Chrome and come back.
This happens on both single-user and multi-user Che.
So far I noticed this happens to blank projects and Java projects.

### Reproduction Steps
Use Che in Docker for a couple of hours and it will suddenly happen.

**OS and version:**
Che Version: 6.13.1 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"

**Diagnostics:** 
Eclipse Che logs do not show anything for the event. It's a silent failure.

> 2018-11-19 19:12:02,895[aceSharedPool-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 364]   - Workspace 'nb:data-service-ide' with id 'workspace8383n00uhxitcyjv' started by user 'nb'
>2018-11-19 19:58:27,304[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 322]   - Starting workspace 'nb/data-service-ide' with id 'workspace8383n00uhxitcyjv' by user 'nb'

The workspace shut down at 19:58:00 but the logs show nothing for the failure. The logs only show when I started the workspace again at 19:58:27. The docker container disappeared from the "docker ps" list.

>
> 2018-11-19 19:58:27,304[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 322]   - Starting workspace 'nb/data-service-ide' with id 'workspace8383n00uhxitcyjv' by user 'nb'
> 2018-11-19 19:58:27,977[ImagesBuilder-0]  [WARN ] [.d.ParallelDockerImagesBuilder 299]  - Failed to check image eclipse/ubuntu_jdk8 availability. Cause: Error response from docker API, status: 500, message: Invalid filter 'reference'
> 
> org.eclipse.che.infrastructure.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Invalid filter 'reference'
> 
>         at org.eclipse.che.infrastructure.docker.client.DockerConnector.getDockerException(DockerConnector.java:1529)
>         at org.eclipse.che.infrastructure.docker.client.DockerConnector.listImages(DockerConnector.java:247)
>         at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.isDockerImageExistLocally(ParallelDockerImagesBuilder.java:294)
>         at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.pullImage(ParallelDockerImagesBuilder.java:267)
>         at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.prepareImage(ParallelDockerImagesBuilder.java:179)
>         at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.lambda$prepareImages$0(ParallelDockerImagesBuilder.java:127)
>         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:748)
> 2018-11-19 19:58:46,503[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 364]   - Workspace 'nb:data-service-ide' with id 'workspace8383n00uhxitcyjv' started by user 'nb'

**Comment by skabashnyuk** [comment]
@nbon12 is there any guide on how to reproduce this?

**Comment by nbon12** [comment]
Using Eclipse Che within Docker: Start any workspace, wait for it to suddenly stop about 30-60 minutes later, while you're still working inside it.

**Comment by skabashnyuk** [comment]
Do you use IDE at that time?

**Comment by didier1969** [comment]
I am getting same error message here too, on a fresh install with multi-user/keycloak. The difference for me is that the workspaces simply don't start (or stop immediately). No way to access the CHE code editor.

When I ran the diagnostic, I got following messages:

> Create Workspace
> EventChannel : {"status":"STARTING","prevStatus":"STOPPED","workspaceId":"workspace0fs470dp8bck0ydu"}
> StatusChannel : {"eventType":"STARTING","identity":{"ownerId":"b07e3a58-ed50-4a6e-be17-fcf49ff8b242","envName":"diagnostics","workspaceId":"workspace0fs470dp8bck0ydu"},"machineName":"dev-machine"}
> EventChannel : {"error":"Workspace is going to be STOPPED. Reason: Container of machine 'dev-machine' unexpectedly stopped. Please, check that container is designed to run in non-interactive terminal.","status":"STOPPING","prevStatus":"STARTING","workspaceId":"workspace0fs470dp8bck0ydu"}
> StatusChannel : {"eventType":"STOPPED","identity":{"ownerId":"b07e3a58-ed50-4a6e-be17-fcf49ff8b242","envName":"diagnostics","workspaceId":"workspace0fs470dp8bck0ydu"},"machineName":"dev-machine"}
> EventChannel : {"error":"Constructing of URI of server failed. Error: Expected hostname at index 5: ws://:32987/wsagent","status":"STOPPED","prevStatus":"STARTING","workspaceId":"workspace0fs470dp8bck0ydu"}
> EventChannel : {"error":"Workspace is stopped. Reason: Container of machine 'dev-machine' unexpectedly stopped. Please, check that container is designed to run in non-interactive terminal.","status":"STOPPED","workspaceId":"workspace0fs470dp8bck0ydu"}

**Comment by nbon12** [comment]
Yes, I was using the IDE at the time it stops.

**Comment by skabashnyuk** [comment]
@didier1969 your issues is a bit different than this one (this issue is about an unexpected stop of workspace, you are about problem with start). Please create a new issue.

@nbon12 can we get more logs of the workspace master?

**Comment by gorkem** [comment]
closing due to inactivity
