### ISSUE TITLE
Unexpected fail of "TheiaBuildPluginTest" and "RenameProjectTest" selenium tests

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11997]
### Description
We have unexpected fail of "TheiaBuildPluginTest" and "RenameProjectTest" selenium tests. It looks like something went wrong with a method which switches into the frame. We should investigate and resolve this problem. 

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.id: theia-app-shell' (tried for 240 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:172)
	at org.eclipse.che.selenium.pageobject.theia.TheiaIde.waitTheiaIde(TheiaIde.java:137)
	at org.eclipse.che.selenium.theia.TheiaBuildPluginTest.prepare(TheiaBuildPluginTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:552)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Screenshot:**
![wwew](https://user-images.githubusercontent.com/22724619/48768482-d4553f80-ecc1-11e8-8c91-4ccdafacb3a3.png)

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/433/Selenium_20tests_20report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/12001
