### ISSUE TITLE
https required

### ISSUE THREAD

**Issue by irwinai** [eclipse-che/che#120]
Exception in thread "DockerInstanceStopDetector-0" java.lang.IllegalArgumentException: Certificates are required for https connection.
        at org.eclipse.che.plugin.docker.client.connection.TcpConnection.<init>(TcpConnection.java:41)
        at org.eclipse.che.plugin.docker.client.connection.DockerConnectionFactory.openConnection(DockerConnectionFactory.java:52)
        at org.eclipse.che.plugin.docker.client.DockerConnector.getEvents(DockerConnector.java:766)
        at org.eclipse.che.plugin.docker.machine.DockerInstanceStopDetector.lambda$detectContainersEvents$2(DockerInstanceStopDetector.java:107)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by irwinai** [comment]
2015-12-12 12:10:56,848[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 164]      - Creating machine [ws = workspaceom7xd42z3anu66jy: env = wksp-14gp: machine = dev-machine]
Exception in thread "WorkspaceManager-0" java.lang.IllegalArgumentException: Certificates are required for https connection.
        at org.eclipse.che.plugin.docker.client.connection.TcpConnection.<init>(TcpConnection.java:41)
        at org.eclipse.che.plugin.docker.client.connection.DockerConnectionFactory.openConnection(DockerConnectionFactory.java:52)
        at org.eclipse.che.plugin.docker.client.DockerConnector.doBuildImage(DockerConnector.java:824)
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:258)
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:230)
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.buildImage(DockerInstanceProvider.java:313)
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:236)
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:357)
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:334)
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:165)
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:388)
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:361)
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:141)
        at org.eclipse.che.api.workspace.server.WorkspaceManager.startWorkspaceSync(WorkspaceManager.java:509)
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$startWorkspaceAsync$2(WorkspaceManager.java:491)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by irwinai** [comment]
what's the problem

**Comment by ghost** [comment]
Are you using Windows? It looks like Docker Toolbox isn't properly configured. Can you run Docker commands in your shell? Smth like docker info.

**Comment by ghost** [comment]
Any update on this? Did you manage to run Che?

**Comment by aaronbartell** [comment]
Having the same issue.  I am running this _outside_ of Docker on the [IBM i operating system](http://bit.ly/ibmi-operating-system) (Docker isn't supported).

**EDIT:** I am able to get Che running on port 8080 and get this error when I attempt to create a new project.  It stops on step 2:

![](http://content.screencast.com/users/AaronBartell/folders/Snagit/media/79b4fdd5-384a-4449-91e5-94819d170765/2016-01-06_14-55-45.png)

**Comment by TylerJewell** [comment]
Closing this issue.  The Che scripts have been updated to detect a valid Docker configuration and will friendly fail in any situation where Docker is not configured, or when Che cannot create a VM that can host Docker in it.
