### ISSUE TITLE
Deploy che server Pod failed on openshfit OKD 3.11 with mulit user deployment

### ISSUE THREAD

**Issue by Caplost** [eclipse-che/che#12033]
useing  ./deploy_che.sh --multiuser command to auto deploy success

but eclipse/che-server:nightly image deploy fail.

it shows 
```
Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration 
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:70)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:53)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
...
Caused by: java.net.UnknownHostException: keycloak-eclipse-che.openshift.qycloud.com.cn
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
```
<details>
<summary>Full Che Server Logs</summary>

```
Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration 
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:70)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:53)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
Caused by: java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration 
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:104)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings$$FastClassByGuice$$e0d0786b.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: keycloak-eclipse-che.openshift.qycloud.com.cn
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.URL.openStream(URL.java:1045)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:97)
	... 33 more
145) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration 
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:70)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:53)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.<init>(KeycloakServiceClient.java:72)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.class(KeycloakServiceClient.java:66)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient
    for the 1st parameter of org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.<init>(IdentityProviderConfigFactory.java:76)
  at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.class(IdentityProviderConfigFactory.java:58)
  while locating org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory
  while locating org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientConfigFactory
    for the 1st parameter of org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.<init>(OpenShiftClientFactory.java:70)
  at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.class(OpenShiftClientFactory.java:70)
  while locating org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory
    for the 4th parameter of org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironmentFactory.<init>(OpenShiftEnvironmentFactory.java:82)
  while locating org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironmentFactory
  while locating org.eclipse.che.api.workspace.server.spi.environment.InternalEnvironmentFactory annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=65, type=MAPBINDER, keyType=java.lang.String)
  at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInfraModule.configure(OpenShiftInfraModule.java:73) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInfraModule -> com.google.inject.multibindings.MapBinder$RealMapBinder)
  while locating java.util.Map<java.lang.String, org.eclipse.che.api.workspace.server.spi.environment.InternalEnvironmentFactory>
    for the 2nd parameter of org.eclipse.che.api.workspace.server.WorkspaceRuntimes.<init>(WorkspaceRuntimes.java:145)
  at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.class(WorkspaceRuntimes.java:93)
  while locating org.eclipse.che.api.workspace.server.WorkspaceRuntimes
    for the 1st parameter of org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator.<init>(WorkspaceLinksGenerator.java:49)
  at org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator.class(WorkspaceLinksGenerator.java:49)
  while locating org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator
Caused by: java.lang.RuntimeException (same stack trace as error #31)
146) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration 
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:70)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:53)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 2nd parameter of org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.<init>(IdentityProviderConfigFactory.java:76)
  at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.class(IdentityProviderConfigFactory.java:58)
  while locating org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory
  while locating org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientConfigFactory
    for the 1st parameter of org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.<init>(OpenShiftClientFactory.java:70)
  at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.class(OpenShiftClientFactory.java:70)
  while locating org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory
    for the 4th parameter of org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironmentFactory.<init>(OpenShiftEnvironmentFactory.java:82)
  while locating org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironmentFactory
  while locating org.eclipse.che.api.workspace.server.spi.environment.InternalEnvironmentFactory annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=65, type=MAPBINDER, keyType=java.lang.String)
  at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInfraModule.configure(OpenShiftInfraModule.java:73) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInfraModule -> com.google.inject.multibindings.MapBinder$RealMapBinder)
  while locating java.util.Map<java.lang.String, org.eclipse.che.api.workspace.server.spi.environment.InternalEnvironmentFactory>
    for the 2nd parameter of org.eclipse.che.api.workspace.server.WorkspaceRuntimes.<init>(WorkspaceRuntimes.java:145)
  at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.class(WorkspaceRuntimes.java:93)
  while locating org.eclipse.che.api.workspace.server.WorkspaceRuntimes
    for the 1st parameter of org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator.<init>(WorkspaceLinksGenerator.java:49)
  at org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator.class(WorkspaceLinksGenerator.java:49)
  while locating org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator
Caused by: java.lang.RuntimeException (same stack trace as error #32)
147) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration 
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:70)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:53)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakProfileRetriever.<init>(KeycloakProfileRetriever.java:39)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakProfileRetriever.class(KeycloakProfileRetriever.java:32)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakProfileRetriever
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.dao.KeycloakProfileDao.<init>(KeycloakProfileDao.java:38)
  while locating org.eclipse.che.multiuser.keycloak.server.dao.KeycloakProfileDao
  while locating org.eclipse.che.api.user.server.spi.ProfileDao
    for the 2nd parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.<init>(KeycloakUserManager.java:58)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.class(KeycloakUserManager.java:58)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager
  while locating org.eclipse.che.multiuser.api.account.personal.PersonalAccountUserManager
  while locating org.eclipse.che.api.user.server.UserManager
    for the 2nd parameter of org.eclipse.che.multiuser.machine.authentication.server.MachineTokenRegistry.<init>(MachineTokenRegistry.java:57)
  at org.eclipse.che.multiuser.machine.authentication.server.MachineTokenRegistry.class(MachineTokenRegistry.java:57)
  while locating org.eclipse.che.multiuser.machine.authentication.server.MachineTokenRegistry
    for the 2nd parameter of org.eclipse.che.multiuser.machine.authentication.server.MachineTokenProviderImpl.<init>(MachineTokenProviderImpl.java:46)
  at org.eclipse.che.multiuser.machine.authentication.server.MachineTokenProviderImpl.class(MachineTokenProviderImpl.java:46)
  while locating org.eclipse.che.multiuser.machine.authentication.server.MachineTokenProviderImpl
  while locating org.eclipse.che.api.workspace.server.token.MachineTokenProvider
    for the 1st parameter of org.eclipse.che.api.workspace.server.spi.provision.env.MachineTokenEnvVarProvider.<init>(MachineTokenEnvVarProvider.java:34)
  while locating org.eclipse.che.api.workspace.server.spi.provision.env.MachineTokenEnvVarProvider
  while locating org.eclipse.che.api.workspace.server.spi.provision.env.EnvVarProvider annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=16, type=MULTIBINDER, keyType=)
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:174) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<org.eclipse.che.api.workspace.server.spi.provision.env.EnvVarProvider>
    for the 1st parameter of org.eclipse.che.api.workspace.server.spi.provision.env.EnvVarEnvironmentProvisioner.<init>(EnvVarEnvironmentProvisioner.java:37)
  while locating org.eclipse.che.api.workspace.server.spi.provision.env.EnvVarEnvironmentProvisioner
  while locating org.eclipse.che.api.workspace.server.spi.provision.InternalEnvironmentProvisioner annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=10, type=MULTIBINDER, keyType=)
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:167) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<org.eclipse.che.api.workspace.server.spi.provision.InternalEnvironmentProvisioner>
    for the 3rd parameter of org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInfrastructure.<init>(OpenShiftInfrastructure.java:53)
  at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInfrastructure.class(OpenShiftInfrastructure.java:37)
  while locating org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInfrastructure
  while locating org.eclipse.che.api.workspace.server.spi.RuntimeInfrastructure
    for the 3rd parameter of org.eclipse.che.api.workspace.server.WorkspaceRuntimes.<init>(WorkspaceRuntimes.java:145)
  at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.class(WorkspaceRuntimes.java:93)
  while locating org.eclipse.che.api.workspace.server.WorkspaceRuntimes
    for the 1st parameter of org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator.<init>(WorkspaceLinksGenerator.java:49)
  at org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator.class(WorkspaceLinksGenerator.java:49)
  while locating org.eclipse.che.api.workspace.server.WorkspaceLinksGenerator
Caused by: java.lang.RuntimeException (same stack trace as error #33)
147 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-11-23 02:35:26,943[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5208]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
2018-11-23 02:35:26,947[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5259]     - Context [/api] startup failed due to previous errors
2018-11-23 02:35:27,085[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [33,145] ms
2018-11-23 02:35:27,099[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war]
2018-11-23 02:35:27,740[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war] has finished in [641] ms
2018-11-23 02:35:27,757[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
2018-11-23 02:35:28,015[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war] has finished in [257] ms
2018-11-23 02:35:28,027[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/workspace-loader.war]
2018-11-23 02:35:28,164[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/workspace-loader.war] has finished in [137] ms
2018-11-23 02:35:28,222[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-8080"]
2018-11-23 02:35:28,311[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 37594 ms
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-1,EclipseLinkCommandChannel,che-10-ztvwf-1786"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-1,RemoteSubscriptionChannel,che-10-ztvwf-17696"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-1,WorkspaceStateCache,che-10-ztvwf-35788"
Received SIGTERM
Stopping Che server running on localhost:8080
2018-11-23 02:36:04,833[main]             [INFO ] [o.a.c.core.StandardServer 524]       - A valid shutdown command was received via the shutdown port. Stopping the Server instance.
2018-11-23 02:36:04,836[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 658]  - Pausing ProtocolHandler ["http-nio-8080"]
2018-11-23 02:36:04,889[main]             [INFO ] [o.a.c.core.StandardService 477]      - Stopping service [Catalina]
2018-11-23 02:36:04,963[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 687]  - Stopping ProtocolHandler ["http-nio-8080"]
2018-11-23 02:36:04,966[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 707]  - Destroying ProtocolHandler ["http-nio-8080"]
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-3,EclipseLinkCommandChannel,che-10-ztvwf-1786"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-2,WorkspaceLocks,che-10-ztvwf-23638"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-3,RemoteSubscriptionChannel,che-10-ztvwf-17696"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-4,EclipseLinkCommandChannel,che-10-ztvwf-1786"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-3,WorkspaceStateCache,che-10-ztvwf-35788"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-2,RemoteSubscriptionChannel,che-10-ztvwf-17696"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-2,EclipseLinkCommandChannel,che-10-ztvwf-1786"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-3,WorkspaceLocks,che-10-ztvwf-23638"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-4,WorkspaceStateCache,che-10-ztvwf-35788"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-4,WorkspaceLocks,che-10-ztvwf-23638"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-4,RemoteSubscriptionChannel,che-10-ztvwf-17696"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-5,EclipseLinkCommandChannel,che-10-ztvwf-1786"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-5,WorkspaceStateCache,che-10-ztvwf-35788"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-5,RemoteSubscriptionChannel,che-10-ztvwf-17696"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "INT-6,WorkspaceStateCache,che-10-ztvwf-35788"
```
</details>

The content of http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration
<details>
<summary>Keycloak Openid Configuration</summary>

```json
{"issuer":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che","authorization_endpoint":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/protocol/openid-connect/auth","token_endpoint":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/protocol/openid-connect/token","token_introspection_endpoint":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/protocol/openid-connect/token/introspect","userinfo_endpoint":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/protocol/openid-connect/userinfo","end_session_endpoint":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/protocol/openid-connect/logout","jwks_uri":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/protocol/openid-connect/certs","check_session_iframe":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["RS256"],"userinfo_signing_alg_values_supported":["RS256"],"request_object_signing_alg_values_supported":["none","RS256"],"response_modes_supported":["query","fragment","form_post"],"registration_endpoint":"http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post"],"token_endpoint_auth_signing_alg_values_supported":["RS256"],"claims_supported":["sub","iss","auth_time","name","given_name","family_name","preferred_username","email"],"claim_types_supported":["normal"],"claims_parameter_supported":false,"scopes_supported":["openid","offline_access"],"request_parameter_supported":true,"request_uri_parameter_supported":true}
```
</details>
 
**OS and version:**    
openshift okd : 3.11
docker version : 1.13

**Comment by eivantsov** [comment]
@Caplost are you behind a proxy? Che server cannot reach this url.

**Comment by Caplost** [comment]
@eivantsov Thank you for your reply ！

I have not use proxy ，keycloak access just use  OKD router .

another thing I found is when it creating Che server container , access it use okd terminal run command curl  http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration. it  shows cannot resolve the url. But useing Debug in Terminal of okd pod curl command works ok.

is that means when creating che server container it cannot access internet ?  run curl http://www.google.com also  shows cannot resolve the url 

I checked the dns  /etc/resolv.conf  it's the same as other pod which can access keycloak;

another things  I miss ？

**Comment by Caplost** [comment]
anyone deploy Eclipse Che  on OKD 3.11 ?

**Comment by Caplost** [comment]
@eivantsov single-user  eclipse/che-server  image deploy success  on OKD 3.11

**Comment by eivantsov** [comment]
Yes, Che is ok with OKD 3.11

I'd try just deploy some image like nginx, expose a service and curl its route from within the pod.

There's a networking issue that you need to solve.

**Comment by skabashnyuk** [comment]
@Caplost are you using minishift? OS of the host?

**Comment by eivantsov** [comment]
@skabashnyuk it's a public instance with a real DNS http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration

@Caplost i highly recommend running the test I have suggested. Let's take Che out of equation for a moment. Just deploy nginx, expose service and try to curl its route from within the pod.

**Comment by Caplost** [comment]
@eivantsov che-server cannot access any public url ,
but I change  the link [http://keycloak-eclipse-che.openshift.qycloud.com.cn/auth/realms/che/.well-known/openid-configuration](url)   to [http://keycloak-eclipse-che.keycloak:5050/auth/realms/che/.well-known/openid-configuration](url) which use service name  the Che-server successfully started!
 it  seems like a networking issue which che-serve podr Can't access public network。

**Comment by eivantsov** [comment]
It's just a mere k8s deployment. You need to find out what the issue is.

By the way, having a url with a service name won't work, since this url should be accessible to clients, ie browsers that users will open to access Che.

**Comment by Caplost** [comment]
I recommend replacing  the auth link which CHE_KEYCLOAK_AUTH__SERVER__URL set， use serviceName by default ? Don't use the subdomain of the cluster.

I cannot find there any differ from other pod on network setting 。

**Comment by Caplost** [comment]
@eivantsov Thank you for your patience.

**Comment by Caplost** [comment]
@eivantsov Should it use the url with a service name just at che-server get auth from keycloak server ?
the keycloak pod works fine, browsers auth use public url of keycloak ruote ?

**Comment by eivantsov** [comment]
Yes, I was thinking about it too. But you have got connectivity issues in your cluster anyway, it does not solve the initial problem

**Comment by Caplost** [comment]
I don't know why it works for other pods which can curl public network , just che-server not :weary:

**Comment by Caplost** [comment]
@eivantsov I try eclipse/che-server with tag nightly-centos it works ok ,but eclipse/che-server:nightly still not work.

**Comment by fishingwind** [comment]
> I don't know why it works for other pods which can curl public network , just che-server not

Hi, Caplost 
Do you've resolved your problem? I'm facing the same exception. The retrieving url has no port, which means 80 and is not accessable. If I curl with port 8080 it's OK.

**Comment by Caplost** [comment]
@fishingwind you can change eclipse/che-server:nightly which is default docker image to eclipse/che-server:nightly-centos ,it may the docker image problem.

**Comment by SockenSalat** [comment]
I expierence the same problem on our test cluster which is version 17.3 and has been setup using kubeadm.

fetching the said URL with curl works fine from containers deployed on the same node.
