### ISSUE TITLE
'Organize Imports' shortcut corrupts the file contents

### ISSUE THREAD

**Issue by praneethgayam** [eclipse-che/che#12100]
### Description
Pressing the key ctrl+alt+o (short key for organize imports) multiple times corrupts the file and leaves the [editor](url) in unusable state.

### Reproduction Steps
1. Create java(maven) project
2. Open a java file and add an unused import (ex: import java.util.ArrayList)
3. Key in: ctrl+alt+o multiple times
    - The first key press actually removes the unused import BUT
    - The following organize-import commands are NOT ignored.. INSTEAD it keeps deleting random lines from the code
    - It also leaves the editor in an unrecoverable state. At some point editor ends up with multiple lines with line-number as 0(zero)
    - Undo (ctrl+z) tries to undo the changes but the contents are never recovered to the original state

![issue-with-organize-imports](https://user-images.githubusercontent.com/367134/49370042-0b434080-f719-11e8-928c-8dd789cf65a1.gif)

Attached gif demonstrates
1. Content corruption when organize import(ctrl+alt+o) is issued multiple times
2. Failure to recover the contents back through undo(ctro+z)

**OS and version:**    
OS: Mac
Version: 6.9.0 & 6.12.2

**Diagnostics:** 
```
2018-12-03 09:38:11,647[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: String index out of range: -84
java.lang.StringIndexOutOfBoundsException: String index out of range: -84
        at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:756)
        at java.lang.StringBuilder.delete(StringBuilder.java:244)
        at org.eclipse.che.api.editor.server.impl.EditorWorkingCopy.applyChanges(EditorWorkingCopy.java:139)
        at org.eclipse.che.api.editor.server.impl.EditorWorkingCopyManager.onEditorContentUpdated(EditorWorkingCopyManager.java:115)
        at org.eclipse.che.api.editor.server.impl.EditorChangesTracker.lambda$configureHandler$0(EditorChangesTracker.java:44)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:329)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:316)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:213)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
        at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
        at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-12-03 09:38:54,619[equestProcessor]  [ERROR] [e.s.i.EditorWorkingCopyManager 305]  - Can't update file, item does not exist: /challenge-ej1188h1dig/project/.che/workingCopies/challenge-ej1188h1dig.project.s
rc.main.java.com.tcs.fresco.model.Bank.java
2018-12-03 09:38:54,620[equestProcessor]  [ERROR] [e.s.i.EditorWorkingCopyManager 199]  - Can not handle file operation: Can not create recovery file for /challenge-ej1188h1dig/project/src/main/java/com/tcs/fres
co/model/Bank.java
2018-12-03 09:39:12,995[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: null
java.lang.StringIndexOutOfBoundsException: null
        at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:760)
        at java.lang.StringBuilder.delete(StringBuilder.java:244)
        at org.eclipse.che.api.editor.server.impl.EditorWorkingCopy.applyChanges(EditorWorkingCopy.java:139)
        at org.eclipse.che.api.editor.server.impl.EditorWorkingCopyManager.onEditorContentUpdated(EditorWorkingCopyManager.java:115)
        at org.eclipse.che.api.editor.server.impl.EditorChangesTracker.lambda$configureHandler$0(EditorChangesTracker.java:44)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:329)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:316)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:213)
        at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
        at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
        at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by tsmaeder** [comment]
Looks like the buffer contents are out of sync between back end and front end.
