### ISSUE TITLE
Error in Building Che-Theia after adding an Extension

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#12120]
Hi,
I tried extending che-theia by adding a new language extension to `src/extensions.json` and I got an error while building `che/dockerfiles/theia` using the command `sudo docker build -t eclipse/che-theia:0.3.16-nightly --build-arg THEIA_VERSIO=0.3.16 .` in Ubuntu 18.04.
I added the theia-xtext extension to extensions.json and it appears as below: -
```
{
    "extensions": [
        {
            "name": "github-extension",
            "source": "https://github.com/eclipse/che-theia-github-plugin",
            "folder": "github-extension",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "che-theia-ssh-extension",
            "source": "https://github.com/eclipse/che-theia-ssh-plugin",
            "folder": "ssh-extension",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "theia-machines-extension",
            "source": "https://github.com/eclipse/che-theia-machines-plugin.git",
            "folder": "theia-machines-extension",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "@eclipse-che/theia-factory-extension",
            "source": "https://github.com/eclipse/che-theia-factory-extension.git",
            "folder": "che-theia-factory",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "@eclipse-che/theia-dashboard-extension",
            "source": "https://github.com/eclipse/che-theia-dashboard-extension.git",
            "folder": "theia-dashboard-extension",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "@eclipse-che/che-theia-hosted-plugin-manager-extension",
            "source": "https://github.com/eclipse/che-theia-hosted-plugin-manager-extension.git",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "@eclipse-che/theia-java-extension",
            "source": "https://github.com/eclipse/che-theia-java-plugin",
            "folder": "che-theia-java-extension",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "che-theia-terminal",
            "source": "https://github.com/eclipse/che-theia-terminal-extension.git",
            "folder": "che-theia-terminal",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "@eclipse-che/theia-task-extension",
            "source": "https://github.com/eclipse/che-theia-task-plugin.git",
            "folder": "che-theia-task-extension",
            "checkoutTo": "master",
            "type": "git"
        },
        {
            "name": "@eclipse-che/theia-activity-tracker",
            "source": "https://github.com/eclipse/che-theia-activity-tracker.git",
            "folder": "che-theia-activity-tracker",
            "checkoutTo": "master",
            "type": "git"
        },
	{
            "name": "@eclipse-che/theia-xtext",
            "source": "https://github.com/theia-ide/theia-xtext.git",
            "folder": "che-theia-xtext",
            "checkoutTo": "master",
            "type": "git"
        }
]
}
```

When I run the above said command in the terminal, I get the below error at the end of a build of approximately and hour.
```
.
.
.
Write generated resolutions to the package.json /home/theia/package.json
/usr/bin/electron-packager -> /usr/lib/node_modules/electron-packager/cli.js
+ electron-packager@13.0.0
added 233 packages from 141 contributors in 66.774s
>>> Cloning repository: https://github.com/eclipse/che-theia-github-plugin
Cloning into '/home/theia/extensions/github-extension'...
>>> Checkout repository to: master
Already on 'master'
There is a build folder defined github-extension
Generate versions for extension:  /home/theia/extensions/github-extension/github-extension
Removing parent files
{ Error: ENOENT: no such file or directory, unlink '/home/theia/extensions/github-extension/lerna.json'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at buildExtension (/home/theia/add-extensions.js:126:16)
    at addExtensions (/home/theia/add-extensions.js:69:9)
    at Object.<anonymous> (/home/theia/add-extensions.js:43:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/home/theia/extensions/github-extension/lerna.json' }
Failed to build extension located in:  /home/theia/extensions/github-extension/github-extension
The command '/bin/sh -c ${HOME}/setup.sh' returned a non-zero code: 6
```

Can anyone please let me know how to correct this? I would really appreciate it.
Thanks!

**Comment by sr229** [comment]
Heya @SharkJ was this done in-container, or in your host?

**Comment by SharkJ** [comment]
Hi @sr229, I cloned the git repo, changed the che-theia directory as mentioned above, and built it in Ubuntu Virtual Box. Is it really possible extend Che Theia by the method I tried?
Thanks!

**Comment by sr229** [comment]
@SharkJ was your user named `theia` ? I got a hunch this might be an issue of hardcoded paths

**Comment by sunix** [comment]
@SharkJ we are introducing new script to build che-theia: https://www.npmjs.com/package/@eclipse-che/theia-generator . At the moment the list of extension is hard coded but we have plans to provide a custom extensions list. cc @benoitf

**Comment by gorkem** [comment]
I do not think this is still valid, please reopen if you think it is valid
