### ISSUE TITLE
Theia Tasks Run fails on Che 7 Kubernetes workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12125]
### Description

On minikube, in a Che 7 workspace, `Task Run` fails. No error/success message is shown to the user. The following error log appears multiple times in the theia-ide container logs:

``` 
root ERROR Uncaught Exception:  Error: Unexpected server response: 301
root ERROR Error: Unexpected server response: 301
    at ClientRequest.req.on (/home/theia/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
```

It works on minishift/ocp instead.   

### Reproduction Steps

- Deploy Single user Che on local minikube as [described in the doc](https://www.eclipse.org/che/docs/che-6/kubernetes-single-user.html)
- Create a workspace based on `Che 7 Dev` stack
- Add a command in the config like this one:
```
    {
      "commandLine": "echo Hello",
      "name": "Hello",
      "type": "che",
      "attributes": {}
    }
```
- Start the workspace and run the task

**Comment by AndrienkoAleksandr** [comment]
It would be nice to write ete tests for tasks extension to track that this extension(plugin in the future) was not broken after update Theia version in the image. @benoitf What do You think?

**Comment by l0rd** [comment]
@AndrienkoAleksandr yes adding a test would be important cc @rhopp @vkuznyetsov @dmytro-ndp

**Comment by benoitf** [comment]
Hello @AndrienkoAleksandr , yes tests are important, but I think i'm the only one to add/write tests for now :-)
