### ISSUE TITLE
Fix build of selenium tests to be comply with new version of guava

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#12184]
### Description
There is [PR](https://github.com/eclipse/che-parent/pull/93) which renewed dependencies and caused [dependence conflict in selenium tests project](https://gist.github.com/skabashnyuk/b0590d7061929a4bdc051bfa58ddca56), which in turn, still depend on older  version of guava:
```
[ERROR] warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.8'
/Users/sj/dev/src/redhat/che/selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ConfigureClasspath.java:[109,8] error: reference to until is ambiguous
  both method until(Predicate<T>) in FluentWait and method <V>until(Function<? super T,V>) in FluentWait match
  where T,V are type-variables:
    T extends Object declared in class FluentWait
    V extends Object declared in method <V>until(Function<? super T,V>)
[ERROR] /Users/sj/dev/src/redhat/che/selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/ConfigureClasspath.java:[119,8] error: reference to until is ambiguous
  both method until(Predicate<T>) in FluentWait and method <V>until(Function<? super T,V>) in FluentWait match
  where T,V are type-variables:
    T extends Object declared in class FluentWait
    V extends Object declared in method <V>until(Function<? super T,V>)
...
```

The problem is reproduced when build with `-Dskip-validate-sources` parameter only.

**Comment by dmytro-ndp** [comment]
Fixup 1: setting `<org.seleniumhq.selenium.version>3.0.1</org.seleniumhq.selenium.version>` version produced next type of warnings in time of execution the tests:
```
2018-12-14 10:20:42,861[pool-1-thread-1]  [WARN ] [o.o.s.s.ui.ExpectedConditions 898]   - WebDriverException thrown by findElement(By.id: gwt-debug-projectTree)
org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: gwt-debug-projectTree
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.1.0', revision: 'b94c902', time: '2017-02-16 12:21:31 -0800'
System info: host: 'dhcp-10-40-5-98.brq.redhat.com', ip: '10.40.5.98', os.name: 'Linux', os.arch: 'amd64', os.version: '4.17.9-200.fc28.x86_64', java.version: '1.8.0_111'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:234)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:151)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitProjectExplorer(ProjectExplorer.java:273)
	at org.eclipse.che.selenium.pageobject.Ide.waitOpenedWorkspaceIsReadyToUse(Ide.java:74)
	at org.eclipse.che.selenium.pageobject.Ide.waitOpenedWorkspaceIsReadyToUse(Ide.java:70)
	at org.eclipse.che.selenium.miscellaneous.DialogAboutTest.dialogAboutTest(DialogAboutTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmytro-ndp** [comment]
E2E tests doesn't build this selenium framework version 3.2.0:
```
[INFO] Compiling 190 source files to /home/ndp/projects/che/selenium/che-selenium-test/target/classes
warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.8'
/home/ndp/projects/che/selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Consoles.java:446: error: method until in class FluentWait<T> cannot be applied to given types;
      appStartDriverWait.until(
                        ^
  required: Function<? super WebDriver,V>
  found: Predicate<WebDriver>
  reason: cannot infer type-variable(s) V
    (argument mismatch; Predicate<WebDriver> cannot be converted to Function<? super WebDriver,V>)
  where V,T are type-variables:
    V extends Object declared in method <V>until(Function<? super T,V>)
    T extends Object declared in class FluentWait
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
1 warning
```
