### ISSUE TITLE
Cannot create project “java.lang.IllegalStateException: Workspace configuration has not been received yet”

### ISSUE THREAD

**Issue by lishoujun** [eclipse-che/che#12320]
### Description

docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /root/che:/data -e CHE_HOST=XXXXXX eclipse/che start
I can create workspace but cannot create project, when i click parent path,console print:

Wed Jan 02 12:05:48 GMT+800 2019 com.google.gwt.logging.client.LogConfiguration
SEVERE: Exception caught: Workspace configuration has not been received yet
com.google.gwt.event.shared.UmbrellaException: Exception caught: Workspace configuration has not been received yet
	at Unknown.bu(Throwable.java:73)
	at Unknown.ku(Exception.java:33)
	at Unknown.ou(RuntimeException.java:33)
	at Unknown.CG(UmbrellaException.java:65)
	at Unknown.EG(UmbrellaException.java:26)
	at Unknown.cG(HandlerManager.java:129)
	at Unknown.GDd(Widget.java:129)
	at Unknown.RDd(Widget.java:127)
	at Unknown.kD(DomEvent.java:125)
	at Unknown.IDd(Widget.java:177)
	at Unknown.UDd(Widget.java:163)
	at Unknown.KMd(DOM.java:1481)
	at Unknown.nOd(DOMImplStandard.java:317)
	at Unknown.ev(Impl.java:309)
	at Unknown.hv(Impl.java:361)
	at Unknown.anonymous(Impl.java:78)
Caused by: java.lang.IllegalStateException: Workspace configuration has not been received yet
	at Unknown.au(Throwable.java:66)
	at Unknown.ju(Exception.java:29)
	at Unknown.nu(RuntimeException.java:29)
	at Unknown.G7d(IllegalStateException.java:28)
	at Unknown.hc(Preconditions.java:507)
	at Unknown.Imh(AppContextImpl.java:341)
	at Unknown.rZj(CategoriesPagePresenter.java:205)
	at Unknown.d$j(CategoriesPageViewImpl.java:158)
	at Unknown.BD(ClickEvent.java:56)
	at Unknown.kG(GwtEvent.java:76)
	at Unknown.cG(SimpleEventBus.java:88)
	at Unknown.GDd(Widget.java:129)
	at Unknown.RDd(Widget.java:127)
	at Unknown.kD(DomEvent.java:125)
	at Unknown.IDd(Widget.java:177)
	at Unknown.UDd(Widget.java:163)
	at Unknown.KMd(DOM.java:1481)
	at Unknown.nOd(DOMImplStandard.java:317)
	at Unknown.ev(Impl.java:309)
	at Unknown.hv(Impl.java:361)
	at Unknown.anonymous(Impl.java:78)

**OS and version:**    
ubuntu 14.04 docker 17
**Diagnostics:**

**Comment by skabashnyuk** [comment]
Due to the lack of/limited availability Docker infrastructure maintainers, I recommend testing the same on Kubernetes/OpenShift.
