### ISSUE TITLE
./deploy_che.sh is failing due to changes introduced in CorsFilter

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#12346]
./deploy_che.sh is currently failing with 

```
javax.servlet.ServletException: It is not allowed to configure supportsCredentials=[true] when allowedOrigins=[*]
--
  | at org.apache.catalina.filters.CorsFilter.parseAndStore(CorsFilter.java:786)
  | at org.apache.catalina.filters.CorsFilter.init(CorsFilter.java:182)
  | at org.eclipse.che.api.core.cors.CheCorsFilter.init(CheCorsFilter.java:47)
  | at com.google.inject.servlet.FilterDefinition.init(FilterDefinition.java:110)
  | at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:98)
  | at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:232)
  | at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
  | at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
  | at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
  | at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4637)
  | at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5282)
  | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
  | at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
  | at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
  | at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
  | at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
  | at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
```

**Comment by ibuziuk** [comment]
Need to remove `CHE_WSAGENT_CORS_ALLOWED__ORIGINS` from the template (it will be automatically detected and set based on workspace master domain)

**Comment by mkuznyetsov** [comment]
Hi, I cannot see how this failure is related to removal of that variable.

if deploy.sh is failing, and these are logs from Che Server. Then I guess `CHE_WSAGENT_CORS_ALLOWED__ORIGINS` is not at fault here since it is related to WS Agent.

The way I see Che start may fail that way, is if only somebody configured `CHE_CORS_ALLOW__CREDENTIALS=true` and `CHE_CORS_ALLOWED_ORIGINS=*`, which is disallowed by Tomcat.

Perhaps old configuration (from Che 6.15) is used to run Che, which has those values? 
In Che 6.16 the default configuration has changed to appropriate values

**Comment by ibuziuk** [comment]
@mkuznyetsov sorry, false alarm. I was using obsolete version of che :/
Closing
