### ISSUE TITLE
Initialization Timeout Error in LS-Sidecar

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#12345]
Hi,

I have created a somewhat large xtext project of a DSL named client. I tried to implement it to Eclipse Che as a sidecar, and I get an initialization timeout error when creating a file with my DSL's extension (.client). 

This is the error that I'm getting in the dev-machine terminal: -
```
2019/01/07 11:16:33 Start new terminal.
2019-01-07 11:17:12,233[rverInitializer]  [ERROR] [.a.l.LanguageServerInitializer 231]  - Can't initialize language server for 'client-ls'
java.util.concurrent.TimeoutException: null
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.initializeServerInstance(LanguageServerInitializer.java:213)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.lambda$null$0(LanguageServerInitializer.java:127)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at org.eclipse.che.api.languageserver.LanguageServerInitializer.lambda$initialize$1(LanguageServerInitializer.java:131)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
2019/01/07 11:17:22 Failed to send websocket message: , due to occurred error websocket: close sent
2019/01/07 11:17:22 Error occurs on sending ping message to websocket. websocket: close sent
```

Below is an error I get in client-language-server-ls terminal: -

```
Exception in thread "main" 
Exception: com.google.inject.internal.util.$ComputationException thrown from the UncaughtExceptionHandler in thread "main"
```

This is the raw config I used to implement my Sidecar: -

```
{
  "id": "client",
  "scope": "general",
  "description": "New client Stack",
  "id": "stackoagu6iqbdkatncv3",
  "creator": "che",
  "tags": [
    "Java 1.8",
    "client 1.0"
  ],
  "workspaceConfig": {
    "attributes": {},
    "description": "string",
    "defaultEnv": "default",
    "environments": {
        "default": {
          "machines": {
            "client-language-server-ls": {
              "env": {},
              "volumes": {},
              "installers": [],
              "servers": {
                "client-ls": {
                  "attributes": {
                    "languageRegexes": "[ {\"languageId\":\"clientlang\", \"regex\":\".*\\\\.client$\"}]",
                    "internal": "true",
                    "id": "client-ls",
                    "type": "ls"
                  },
                  "protocol": "tcp",
                  "port": "4417"
                }
              },
              "attributes": {
                "memoryLimitBytes": "2147483648"
              }
            },
            "dev-machine": {
              "env": {},
              "volumes": {},
              "installers": [
                "org.eclipse.che.terminal",
                "org.eclipse.che.ws-agent"
              ],
              "servers": {},
              "attributes": {
                "memoryLimitBytes": "2147483648"
              }
            }
          },
          "recipe": {
            "contentType": "text/x-yaml",
            "type": "compose",
            "content": "services:\n client-language-server-ls:\n  image: sharkj/client\n  mem_limit: 1073741824\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n   - client-language-server-ls\n"
          }
        }
    },
    "commands": [],
    "projects": [],
    "name": "default",
    "links": []
  },
  "components": [],
  "name": "client",
  "links": []
}
```

Could you please let me know what the error might be? I implemented a similar DSL for a comparatively smaller project using the same process and it worked fine. 

Reagards!

**Comment by SharkJ** [comment]
The error was due to the large number of classes and methods in my Xtext project from which I generated the .jar file to create this language server sidecar. While I had the problem, the MWE2 workflow had the below code snippet: -

parserGenerator{
     options = }
          classSplitting = true
          fieldsPerClass = "100"
          methodsPerClass = "100"
     }
}

After I changed the values of 'fieldsPerClass' and 'methodsPerClass' to "300", the error was gone.
