### ISSUE TITLE
Che on OpenShift will no longer start

### ISSUE THREAD

**Issue by donenocode** [eclipse-che/che#12348]
### Description
An existing Che installation on OpenShift Origin development system was working nicely but the entire OpenShift cluster was shutdown for a number of days.
Upon starting up the OpenShift nodes and subsequently starting Che, it fails to start.
The Keycloak and Postgres PODS both start cleanly but the Che pod ends up in a CrashLoopBackOff.

The version of Che is 'latest' (actually 6.16.0) (_the version from 27th Dec 2018_). Previous to this shutdown and failure the version was also set to latest with the actual version being 6.15.0

The latest version of the 'latest' docker image will have been pulled when Che was restarted.

I did note there is a PR related to the CORS settings recently that may (or may not) be related (PR #12046 )

### Logs
Some Logs from the event:
`
2019-01-07 12:02:35,038[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4643] - Exception starting filter [guiceFilter]
javax.servlet.ServletException: It is not allowed to configure supportsCredentials=[true] when allowedOrigins=[*]
	at org.apache.catalina.filters.CorsFilter.parseAndStore(CorsFilter.java:786)
	at org.apache.catalina.filters.CorsFilter.init(CorsFilter.java:182)
	at org.eclipse.che.api.core.cors.CheCorsFilter.init(CheCorsFilter.java:47)
	at com.google.inject.servlet.FilterDefinition.init(FilterDefinition.java:110)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:98)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:232)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4637)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5282)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-01-07 12:02:35,039[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5283]     - One or more Filters failed to start. Full details will be found in the appropriate container log file
`

Some of the ENV variables that matter:
`
CHE_CORS_ALLOWED__ORIGINS='*'
CHE_CORS_ALLOW__CREDENTIALS='true'
CHE_CORS_ENABLED='true'
`

looking in the '**deploy/openshift/templates/che-server-template.yaml**' it appears the default value for '**CHE_CORS_ALLOW__CREDENTIALS**' should be '**false**'
The error message above would also appear to back-this assumption up also.

I haven't changed this and am not clear how it has changed?
I haven't tried changing it as I am not clear on it effect and also not clear how this setting was changed.

**Comment by donenocode** [comment]
Just noticed the previous version for '**deploy/openshift/templates/che-server-template.yaml**' had '**CHE_CORS_ALLOW__CREDENTIALS**' with a value of  '**true**'

**Comment by donenocode** [comment]
I change the env variable on the deployment and re-deployed Che and it now starts up.
The next issue is now I cannot create projects in workspaces. No project types/samples are listed when clicking the 'Create Project...' link 
The 'Import Project...' link also does not work :(

**Comment by slemeur** [comment]
cc @skabashnyuk

**Comment by mkuznyetsov** [comment]
Hello @donenocode 

Yes, that WS Agent problem sounds like CORS is misconfigured - CORS filter must be set that way, that it would allow requests with credentials, and originated from WS Masters domain

Now, on default Che 6.16 this shouldn't happen, as default configuration in openshift templates 
Perhaps what is happening is that old configuration (openshift template) of Che 6.15 is used, which doesn't work with Che 6.16

There is supposed to be docs and release notes related to it, but I cannot see that being published atm, I can point you to raw text on GitHub
https://github.com/eclipse/che-docs/pull/643/files
