### ISSUE TITLE
The content assist doesn't work after an error log occurred.

### ISSUE THREAD

**Issue by ondrx** [eclipse-che/che#12450]
# Description #

The content assist doesn't work after an error log occurred.

## Reproduction Steps: ##

* Create TypeScript project
* Create new file
* Type in the editor

```typescript
    class TestClass{
        public  m1(){
        }
        public m2(){
        }
    };
    let t = new TestClass();
    t.
```
* Set the cursor on the "t." expression and call the content assist (Press Ctrl+Space)  
The Content assist displays.

* Fix the code

```typescript
    class TestClass{
        public  m1(){
        }
        public m2(){
        }
    };
    // instantiate non-existent class
    let t = new xx();
    t.
```

* Set the cursor on the "t." expression and call the content assist (Press Ctrl+Space)  
An Error log occurs.  
**Log:**
```
    [ERROR] [j.j.ConcurrentMessageProcessor 86]   - java.lang.IllegalStateException: Expected a name but was NULL at line 1 column 41 path $.result  
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a name but was NULL at line 1 column 41 path $.result
        at com.google.gson.Gson.fromJson(Gson.java:900)
        at com.google.gson.Gson.fromJson(Gson.java:853)
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at com.google.gson.Gson.fromJson(Gson.java:774)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:148)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
	    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	    at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.read(MessageTypeAdapterFactory.java:61)
	    at com.google.gson.Gson.fromJson(Gson.java:888)
	    at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.read(MessageTypeAdapterFactory.java:84)
	    at com.google.gson.stream.JsonReader.nextName(JsonReader.java:789)
	    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	    at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:78)
    Caused by: java.lang.IllegalStateException: Expected a name but was NULL at line 1 column 41 path $.result
        ... 12 common frames omitted
```

* Fix the code correctly "let t = new TestClass();"

```typescript
    class TestClass{
        public  m1(){
        }
        public m2(){
        }
    };
    // let t = new xx();
    let t = new TestClass();
    t.
```

* Set the cursor on the "t." expression and call the content assist (Press Ctrl+Space)  
The content assist doesn't display.(Nothing happens.)

## Expected behavior: ##

* The Content assist displays

## Observed behavior: ##

* The content assist doesn't display

**Che version:** 6.8.0  
**OS and version:** CentOS Linux release 7.6.1810 (Core)

**Comment by slemeur** [comment]
Won't fix in Che 6.
This would be nicely enhanced in Che 7
