### ISSUE TITLE
Fail to build theia dockerimage module

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12452]
### Description
The following CI test jobs fail because of error in Theia, TheiaDev modules:
https://github.com/eclipse/che/pull/12335#issuecomment-454810864
https://github.com/eclipse/che/pull/12421#issuecomment-454985674
https://github.com/eclipse/che/pull/12335#issuecomment-455056826

### Reproduction Steps
Execute `mvn clean install -Pintegration` in che project or directly in [dockerfiles/theia](https://github.com/eclipse/che/tree/master/dockerfiles/theia)
**OS and version:**    

**Diagnostics:** 
<details>
<summary>One of the job logs fragment</summary>

```
$ yarn run clean && yarn run build
$ rimraf lib
$ yarn run format-code && yarn run compile && yarn run compileWorker
$ tsfmt -r
$ tsc
src/node/che-task-service.ts(45,13): error TS2322: Type 'CheTask' is not assignable to type 'Task'.
  Types of property 'getRuntimeInfo' are incompatible.
    Type '() => Promise<TaskInfo>' is not assignable to type '() => TaskInfo'.
src/node/che-task-service.ts(84,11): error TS2416: Property 'getRuntimeInfo' in type 'CheTask' is not assignable to the same property in base type 'Task'.
  Type '() => Promise<TaskInfo>' is not assignable to type '() => TaskInfo'.
    Type 'Promise<TaskInfo>' is not assignable to type 'TaskInfo'.
      Property 'taskId' is missing in type 'Promise<TaskInfo>'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/home/theia-dev/theia-source-code/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 1,
  killed: false,
  stdout: '$ yarn run clean && yarn run build\n$ rimraf lib\n$ yarn run format-code && yarn run compile && yarn run compileWorker\n$ tsfmt -r\n$ tsc\nsrc/node/che-task-service.ts(45,13): error TS2322: Type \'CheTask\' is not assignable to type \'Task\'.\n  Types of property \'getRuntimeInfo\' are incompatible.\n    Type \'() => Promise<TaskInfo>\' is not assignable to type \'() => TaskInfo\'.\nsrc/node/che-task-service.ts(84,11): error TS2416: Property \'getRuntimeInfo\' in type \'CheTask\' is not assignable to the same property in base type \'Task\'.\n  Type \'() => Promise<TaskInfo>\' is not assignable to type \'() => TaskInfo\'.\n    Type \'Promise<TaskInfo>\' is not assignable to type \'TaskInfo\'.\n      Property \'taskId\' is missing in type \'Promise<TaskInfo>\'.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error Command failed with exit code 2.\nerror Command failed with exit code 1.\nerror Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run prepare',
  timedOut: false,
  exitCode: 1 }
[0m[91merror Command failed with exit code 1.
[0minfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[91merror Command failed with exit code 1.
[0minfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[JENKINS] Archiving disabled
```
</details>

**Comment by sleshchenko** [comment]
I've labeled it as `blocker` since it prevent to get tests report on PRs. So, no PR can be merged before this issue will be fixed.

**Comment by vitaliy-guliy** [comment]
This [PR](https://github.com/eclipse/che-theia/pull/27) mush fix the build.

**Comment by garagatyi** [comment]
Removed blocker label as there is no activity recently. Apparently, not so blocking anymore.
