### ISSUE TITLE
VS Code xml extension not working with error UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'editor.autoClosingBrackets' of undefined

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#12536]
### Description

try to use xml features from vs code xml extension vscode:extension/redhat.vscode-xml

### Reproduction Steps

- open command palette
- use command "Deploy: deploy plugin by id"
- in log there is:
```
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer: PluginVsCodeFileHandler { unpackedFolder: '/tmp/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'vscode:extension/redhat.vscode-xml',
     pluginId: 'vscode:extension/redhat.vscode-xml',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath: '/tmp/vscode-extension-marketplace/vscode_extension_redhat_vscode_xml.vsix',
     initPath: '/tmp/vscode-extension-marketplace/vscode_extension_redhat_vscode_xml.vsix',
     resolved: true,
     resolvedByName: 'VsCodePluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix
root INFO accepting packagejson with engines { vscode: '^1.27.0' }
root INFO HostedPluginServerImpl/ asking to deploy the backend Plugin /tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension and model is { id: 'redhat.vscode-xml',
  name: 'vscode-xml',
  publisher: 'redhat',
  version: '0.3.0',
  displayName: 'XML',
  description: 'XML Language Support by Red Hat',
  engine: { type: 'vscode', version: '^1.27.0' },
  entryPoint:
   { backend: '/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/out/src/extension' },
  contributes:
   { configuration:
      { type: 'object',
        title: 'XML configuration',
        properties: [Object] } } }
root INFO [hosted-plugin: 203] PLUGIN_HOST(203) starting instance

root INFO [hosted-plugin: 203] PLUGIN_HOST(203): PluginManagerExtImpl/init()
PLUGIN_HOST(203): initializing(/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)

root INFO [hosted-plugin: 203] PLUGIN_HOST(203): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/out/src/extension)

root ERROR [hosted-plugin: 203] (node:203) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'editor.autoClosingBrackets' of undefined
    at verifyAutoClosing (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/out/src/extension.js:127:47)
    at didChangeConfiguration (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/out/src/extension.js:59:29)
    at ConfigurationFeature.onDidChangeConfiguration (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1488:15)
    at ConfigurationFeature.register (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1449:18)
    at ConfigurationFeature.initialize (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1435:18)
    at LanguageClient.initializeFeatures (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/node_modules/vscode-languageclient/lib/client.js:2297:21)
    at connection.initialize.then (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/node_modules/vscode-languageclient/lib/client.js:2002:18)
    at <anonymous>
(node:203) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

root ERROR [hosted-plugin: 203] (node:203) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**OS and version:**   

windows
 docker run -it -p 3000:3000 -v "C:/Users/Aurelien Pupier/theia:/home/project:cached" theiaide/theia-full:0.3.18

**Diagnostics:**

**Comment by vrubezhny** [comment]
Depends on https://github.com/theia-ide/theia/issues/3540

**Comment by apupier** [comment]
@vrubezhny https://github.com/theia-ide/theia/issues/3540 is marked as fixed. Can we close this issue then? or more work is required? or not yet available in the Che version?

**Comment by apupier** [comment]
seems there is still a notification error:

![image](https://user-images.githubusercontent.com/1105127/55876931-085dce00-5b99-11e9-8a04-2abed53975a8.png)

even if the xml extension is installed and seems to work

**Comment by tsmaeder** [comment]
Need to understand why we get the notification and whether it is harmless.

**Comment by tolusha** [comment]
It is a warning showing that several settings are responsible for the save action.
https://github.com/redhat-developer/vscode-xml/blob/master/src/extension.ts#L139

```
function verifyAutoClosing() {
  let configXML = workspace.getConfiguration();
  let closeTags = configXML.get("xml.completion.autoCloseTags");
  let closeBrackets = configXML.get("[xml]")["editor.autoClosingBrackets"];
  if (closeTags && closeBrackets != "never") {
    window.showWarningMessage(
      "The [xml].editor.autoClosingBrackets setting conflicts with xml.completion.autoCloseTags. It's recommended to disable it.",
      "Disable",
      "Ignore").then((selection) => {
        if (selection == "Disable") {
          let scopeInfo : ScopeInfo = getScopeLevel("", "[xml]");
          workspace.getConfiguration().update("[xml]", { "editor.autoClosingBrackets": "never" }, scopeInfo.configurationTarget).then(
            () => console.log('[xml].editor.autoClosingBrackets globally set to never'),
            (error) => console.log(error)
          );
        }
        else if(selection == "Ignore") {
          ignoreAutoCloseTags = true;
        }
      });
  }
}
```

**Comment by tolusha** [comment]
But the warning itself shouldn't be shown because `closeBrackets` is undefined. 
So, it should be
```
if (closeTags && closeBrackets && closeBrackets != "never") {
```
