### ISSUE TITLE
Workspace doesn't start if recipe contains initContainers, che log gives NPE

### ISSUE THREAD

**Issue by vtawniya** [eclipse-che/che#12893]
### Description
If the recipe contains initContainers then workspace doesn't start. Icon beside workspace name flickers few times and none of the resources get created inside workspace namespace.

### Reproduction Steps
You can use the following stack to reproduce the issue:
```
{
      "name": "Dummy",
      "components": [],
      "tags": [
        "Kubernetes"
      ],
      "id": "dummy-hub-stack",
      "workspaceConfig": {
        "defaultEnv": "default",
        "environments": {
          "default": {
            "machines": {
              "hub-tooling/hub-theia-ide": {
                "attributes": {
                  "memoryLimitBytes": "2147483648"
                },
                "servers": {
                  "theia": {
                    "attributes": {
                      "type": "ide"
                    },
                    "port": "3000",
                    "path": "/",
                    "protocol": "http"
                  },
                  "theia-dev": {
                    "attributes": {
                      "type": "ide-dev"
                    },
                    "port": "3030",
                    "protocol": "http"
                  }
                },
                "volumes": {
                  "projects": {
                    "path": "/projects"
                  }
                },
                "installers": [],
                "env": {
                   "USE_LOCAL_GIT":"true",
                   "COMPILE_TOOLS_MACHINE_NAME":"hub-tooling/dummy-tools"
                }
              },
              "hub-tooling/machine-exec": {
                "attributes": {
                  "memoryLimitBytes": "536870912"
                },
                "servers": {
                  "machine-exec": {
                    "attributes": {
                      "type": "terminal"
                    },
                    "port": "4444",
                    "protocol": "ws"
                  }
                },
                "volumes": {},
                "installers": [],
                "env": {}
              },
              "hub-tooling/dummy-tools": {
                "attributes": {
                  "memoryLimitBytes": "1073741824"
                },
                "servers": {},
                "volumes": {
                  "projects": {
                    "path": "/projects"
                  }
                },
                "installers": [],
                "env": {}
              }
            },
            "recipe": {
              "type": "kubernetes",
              "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: hub-tooling\n  spec:\n   volumes:\n    - \n     name: cfg\n     emptyDir: {}\n   initContainers:\n    - \n     image: 'busybox:latest'\n     name: attach-file\n     command: ['/bin/sh', '-c', 'echo abcdef > /cfg/xyzFile']\n     resources: {}\n   containers:\n    - \n     image: 'theiaide/theia:latest'\n     name: hub-theia-ide\n     resources:\n      limits:\n       memory: 1024Mi\n    - \n     image: 'busybox:latest'\n     name: dummy-tools\n     command: ['/bin/sh', '-c', '[ -f /cfg/xyzFile ] && cp /cfg/xyzFile /xyzFile; tail -f /dev/null']\n     volumeMounts:\n      - \n       name: cfg\n       mountPath: /cfg\n     resources:\n      limits:\n       memory: 1024Mi\n    - \n     image: 'wsskeleton/che-machine-exec:latest'\n     name: machine-exec\n     resources:\n      limits:\n       memory: 512Mi\n",
              "contentType": "text/x-yaml"
            }
          }
        },
        "projects": [],
        "name": "default",
        "attributes": {},
        "commands": [],
        "links": []
      },
      "description": "Dummy Tooling",
      "creator": "Dummy Software",
      "scope": "general",
      "links": []
    }

```

**OS and version:**    
OS: CentOS 7
K8s: 1.11.0
Che: 6.14
Docker: 18.03.1-ce

**Diagnostics:** 
Also you will be able to observe this error in che pod's logs:
```
2019-03-15 06:17:56,187[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 322]   - Starting workspace 'admin/wksp-bkza' with id 'workspacexm16quej4q2327us' by user 'admin'
2019-03-15 06:17:56,202[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 226]  - Failed to start Kubernetes runtime of workspace workspacexm16quej4q2327us. Cause: null
2019-03-15 06:17:56,255[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 383]   - Workspace 'admin:wksp-bkza' with id 'workspacexm16quej4q2327us' start failed
2019-03-15 06:17:56,294[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 393]   - null
org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: null
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:710)
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:248)
        at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:148)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:359)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.CommonPVCStrategy.provision(CommonPVCStrategy.java:123)
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesEnvironmentProvisioner$KubernetesEnvironmentProvisionerImpl.provision(KubernetesEnvironmentProvisioner.java:122)
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:181)
        ... 7 common frames omitted
2019-03-15 06:17:56,317[aceSharedPool-0]  [WARN ] [o.e.c.a.w.s.WorkspaceManager 433]    - Cannot set error status of the workspace workspacexm16quej4q2327us. Error is: null
```

**Comment by sleshchenko** [comment]
@vtawniya Thanks for reporting a bug. I hope it is not actual for the latest 6.x/7.x versions, but it is needed to check.

**Comment by monaka** [comment]
I checked the recipe on my instance based on 7.0.0-beta-2.0-SNAPSHOT.
(Strictly my instance is patched. but I think my patches will not affect to this issue).

Init Container was fallen down to `CrashLoopBackoff`. And there was no NPE on Che-server.
@vtawniya Could you upgrade your Che instance to the latest ? 

```
Init Containers:
  attach-file:
    Container ID:  docker://3e67cb264320e3e53d8191e492f5342a59fbf21d189076e45cee0fe3721e96bf
    Image:         busybox:latest
    Image ID:      docker-pullable://busybox@sha256:061ca9704a714ee3e8b80523ec720c64f6209ad3f97c0ff7cb9ec7d19f15149f
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      echo abcdef > /cfg/xyzFile
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 21 Mar 2019 03:51:20 +0000
      Finished:     Thu, 21 Mar 2019 03:51:20 +0000
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from che-workspace-token-2pc2t (ro)
```

```
$ kubectl logs --namespace=banco workspace3kh3qjowtnded5by.hub-tooling-58b6bcb78b-gkjd4 -c attach-file
/bin/sh: can't create /cfg/xyzFile: nonexistent directory
```

**Comment by amisevsk** [comment]
Testing the init container directly, it fails to start with
```
/bin/sh: can't create /cfg/xyzFile: nonexistent directory
```

yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: init-test
spec:
  containers:
  - name: attach-file
    image: 'busybox:latest'
    command: ['/bin/sh', '-c', 'echo abcdef > /cfg/xyzFile']
  restartPolicy: OnFailure
```

**Comment by vtawniya** [comment]
> Testing the init container directly, it fails to start with
> 
> ```
> /bin/sh: can't create /cfg/xyzFile: nonexistent directory
> ```
> yaml:
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: init-test
> spec:
>   containers:
>   - name: attach-file
>     image: 'busybox:latest'
>     command: ['/bin/sh', '-c', 'echo abcdef > /cfg/xyzFile']
>   restartPolicy: OnFailure
> ```

Seems when I narrowed down the issue to initContainers, I removed other things. I was suppose to leave volumeMount for that directory (cfg) in the recipe. But even if you if you do a simple echo in initContainer, you will still see the same issue.

**Comment by vtawniya** [comment]
> I checked the recipe on my instance based on 7.0.0-beta-2.0-SNAPSHOT.
> (Strictly my instance is patched. but I think my patches will not affect to this issue).
> 
> Init Container was fallen down to `CrashLoopBackoff`. And there was no NPE on Che-server.
> @vtawniya Could you upgrade your Che instance to the latest ?
> 
> ```
> Init Containers:
>   attach-file:
>     Container ID:  docker://3e67cb264320e3e53d8191e492f5342a59fbf21d189076e45cee0fe3721e96bf
>     Image:         busybox:latest
>     Image ID:      docker-pullable://busybox@sha256:061ca9704a714ee3e8b80523ec720c64f6209ad3f97c0ff7cb9ec7d19f15149f
>     Port:          <none>
>     Host Port:     <none>
>     Command:
>       /bin/sh
>       -c
>       echo abcdef > /cfg/xyzFile
>     State:          Waiting
>       Reason:       CrashLoopBackOff
>     Last State:     Terminated
>       Reason:       Error
>       Exit Code:    1
>       Started:      Thu, 21 Mar 2019 03:51:20 +0000
>       Finished:     Thu, 21 Mar 2019 03:51:20 +0000
>     Ready:          False
>     Restart Count:  3
>     Environment:    <none>
>     Mounts:
>       /var/run/secrets/kubernetes.io/serviceaccount from che-workspace-token-2pc2t (ro)
> ```
> ```
> $ kubectl logs --namespace=banco workspace3kh3qjowtnded5by.hub-tooling-58b6bcb78b-gkjd4 -c attach-file
> /bin/sh: can't create /cfg/xyzFile: nonexistent directory
> ```

We have been using 16.14 version for a considerably complex and big project, and I am afraid we can't directly jump to 17 at this stage (it being beta is also one factor).
Did someone gave it a try in 16 version to confirm the issue ?
