### ISSUE TITLE
WebSocket che-host failed

### ISSUE THREAD

**Issue by segg21** [eclipse-che/che#1293]
Sorry for bothering, but i've been up for the past 5+ hours and cannot get this working

I have everything working, until it comes to injecting and starting the workspace agent. It says paste the below stacktrace so here it goes

```
[STDOUT] 2016-05-19 05:44:21,611[ventBusClient-0] [WARN ] [.c.a.c.n.WSocketEventBusClient 256] - Not able to connect to ws://che-host:8080/ide/api/eventbus/?token=dummy_token because Connection timeout. Retrying 
[STDOUT] 2016-05-19 05:44:21,620[ost-startStop-1] [INFO] [piEndpointAccessibilityChecker 74] - Workspace /etc/hosts: 127.0.0.1  localhost
[STDOUT] ::1    localhost ip6-localhost ip6-loopback
[STDOUT] fe00::0    ip6-localnet
[STDOUT] ff00::0    ip6-mcastprefix
[STDOUT] ff02::1    ip6-allnodes
[STDOUT] ff02::2    ip6-allrouters
[STDOUT] 192.168.99.1   che-host
[STDOUT] 172.17.0.2 efd3e104f3d8
[STDOUT]
```

It never gets passed this part

> Deploying web application archive /home/user/che/ws-agent/webapps/ide.war

I've uninstalled everything, been trying to tickle with it to get it working and nothing.

I've managed to increase my timeout since it says that things might be running slow, But i guess not. After that this happens.

```
Unable to start workspace agent. Error when trying to start the workspace agent: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
```

Also, everytime when I run che after being closed it says this

```
Could not find an existing docker machine.
Creating docker machine named default... Please be patient, this takes a couple minutes the first time.
```

Then, when I load the che **localhost:8080** nothing is saved that was previously created. How can I load whats default instead of it creating one every single time?

Thanks for the support

**Comment by ddementieva** [comment]
Can you run Che again and try to reach it at 192.168.99.1:8080? If not, run `ipconfig` command and share the output.

**Comment by segg21** [comment]
@ddementieva I can access http://192.168.99.1:8080/dashboard

I was using localhost:8080. Was that the problem?

**Comment by segg21** [comment]
@ddementieva 

```
Wireless LAN adapter Wi-Fi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 7:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Ethernet 3:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::586b:4eca:a68f:b0b8%7
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::99ae:f1b1:da4b:41cc%15
   IPv4 Address. . . . . . . . . . . : 192.168.99.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::d1d7:7a2c:193d:305b%11
   IPv4 Address. . . . . . . . . . . : 192.168.0.128
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1
```

**Comment by segg21** [comment]
### Error update

```
916] - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[STDOUT] 2016-05-19 12:54:20,447[ost-startStop-1] [ERROR] [piEndpointAccessibilityChecker 62] - connect timed out
[STDOUT] java.net.SocketTimeoutException: connect timed out
[STDOUT] at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_65]
[STDOUT] at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_65]
[STDOUT] at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_65]
[STDOUT] at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_65]
[STDOUT] at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_65]
[STDOUT] at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_65]
[STDOUT] at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.http.HttpClient.(HttpClient.java:211) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_65]
[STDOUT] at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_65]
[STDOUT] at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_65]
[STDOUT] at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:234) ~[che-core-api-core-4.0.1.jar:4.0.1]
[STDOUT] at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:144) ~[che-core-api-core-4.0.1.jar:4.0.1]
[STDOUT] at org.eclipse.che.wsagent.server.ApiEndpointAccessibilityChecker.start(ApiEndpointAccessibilityChecker.java:57) ~[classes/:4.0.1]
[STDOUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
[STDOUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
[STDOUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
[STDOUT] at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
[STDOUT] at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44) [che-core-commons-inject-4.0.1.jar:4.0.1]
[STDOUT] at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) [guice-4.0.jar:na]
[STDOUT] at com.google.inject.Guice.createInjector(Guice.java:96) [guice-4.0.jar:na]
[STDOUT] at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137) [everrest-integration-guice-1.12.1.jar:na]
[STDOUT] at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) [guice-servlet-4.0.jar:na]
[STDOUT] at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:84) [everrest-integration-guice-1.12.1.jar:na]
[STDOUT] at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4793) [catalina.jar:8.0.29]
[STDOUT] at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236) [catalina.jar:8.0.29]
[STDOUT] at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.29]
[STDOUT] at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.29]
[STDOUT] at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.29]
[STDOUT] at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.29]
[STDOUT] at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.29]
[STDOUT] at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795) [catalina.jar:8.0.29]
[STDOUT] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
[STDOUT] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
[STDOUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
[STDOUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
[STDOUT] at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
[STDOUT] 2016-05-19 12:54:20,460[ost-startStop-1] [ERROR] [piEndpointAccessibilityChecker 65] - The workspace agent has attempted to start, but it is unable to ping the Che server at http://che-host:8080/ide/api/
[STDOUT] 2016-05-19 12:54:20,471[ost-startStop-1] [ERROR] [piEndpointAccessibilityChecker 66] - The workspace agent has been forcefully stopped. This error happens when the agent cannot resolve the location of the Che server. This error can usually be fixed with additional configuration settings in /conf/che.properties. The Che server will stop this workspace after a short timeout. You can get help by posting your config, stacktrace and workspace /etc/hosts below as a GitHub issue.
[STDOUT] 2016-05-19 12:54:20,500[ost-startStop-1] [INFO] [piEndpointAccessibilityChecker 74] - Workspace /etc/hosts: 127.0.0.1  localhost
[STDOUT] ::1    localhost ip6-localhost ip6-loopback
[STDOUT] fe00::0    ip6-localnet
[STDOUT] ff00::0    ip6-mcastprefix
[STDOUT] ff02::1    ip6-allnodes
[STDOUT] ff02::2    ip6-allrouters
[STDOUT] 192.168.99.1   che-host
[STDOUT] 172.17.0.2 3da495eefd33
[STDOUT] 
[ERROR] Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
```

### Che console

```
 2016-05-19 06:34:34,089[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\dashboard.war
2016-05-19 06:34:35,408[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\dashboard.war has finished in 1,318 ms
2016-05-19 06:34:35,430[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\ide.war
2016-05-19 06:34:57,458[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
2016-05-19 06:35:04,984[ost-startStop-1]  [INFO ] [.c.p.d.c.DockerRegistryChecker 43]   - Probing registry 'http://localhost:5000'
2016-05-19 06:35:06,277[ost-startStop-1]  [WARN ] [.c.p.d.c.DockerRegistryChecker 50]   - Docker registry http://localhost:5000 is not available, which means that you won't be able to save snapshots of your workspaces.
How to configure registry?
        Local registry  -> https://docs.docker.com/registry/
        Remote registry -> set up 'docker.registry.auth.*' properties
2016-05-19 06:35:11,062[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\ide.war has finished in 35,632 ms
2016-05-19 06:35:11,068[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\swagger.war
2016-05-19 06:35:11,421[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\swagger.war has finished in 354 ms
2016-05-19 06:35:11,445[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1036]       - Deploying web application directory C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\ROOT
2016-05-19 06:35:11,882[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1152]       - Deployment of web application directory C:\Users\LegitSoulja\Desktop\eclipse-che-4.0.1\tomcat\webapps\ROOT has finished in 438 ms
2016-05-19 06:35:11,898[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-8080"]
2016-05-19 06:35:11,933[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 38221 ms
2016-05-19 06:37:02,220[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 140]    - EVENT#workspace-created# WS#wksp-5nhi# WS-ID#workspaceymrb6xdv96p77gep# USER#che#
2016-05-19 06:37:03,541[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = workspaceymrb6xdv96p77gep: env = wksp-5nhi: machine = ws-machine]
2016-05-19 06:56:38,014[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 610]    - Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
org.eclipse.che.api.machine.server.exception.MachineException: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:396) ~[che-core-api-machine-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:333) ~[che-core-api-machine-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:167) ~[che-core-api-machine-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:421) ~[che-core-api-workspace-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:320) ~[che-core-api-workspace-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:146) ~[che-core-api-workspace-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:637) ~[che-core-api-workspace-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:608) ~[che-core-api-workspace-4.0.1.jar:4.0.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.1.jar:4.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_91]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
        at org.eclipse.che.api.machine.server.WsAgentLauncherImpl.startWsAgent(WsAgentLauncherImpl.java:107) ~[che-core-api-machine-4.0.1.jar:4.0.1]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:366) ~[che-core-api-machine-4.0.1.jar:4.0.1]
        ... 11 common frames omitted
```

**Comment by ddementieva** [comment]
It seems there is some problem with network.

What happens if you run:
`docker-machine ssh che`
`docker run -ti codenvy/ubuntu_jdk8`
When in the container run:
`curl -v http://192.168.99.1:8080/dashboard`
and
curl -v http://${eth0}:8080/dashboard.

Also try to ping google in the container: `ping google.com`.

**Comment by segg21** [comment]
@ddementieva I figured out my problem. It was my firewall. It's all fixed now. Thanks

**Comment by TylerJewell** [comment]
@LegitSoulja -- cool.  What project are you working on @LegitSoulja?

**Comment by segg21** [comment]
@TylerJewell I currently have my own vps, and im doing hosting for this for a community. 

I was looking for a web/cloud based IDE and I discovered this and I started working with this and actually this is what im looking for. Mainly this is for development use for github. Strictly for running services, and debugging, and development for the team.
