### ISSUE TITLE
Subtle issue during workspace startup in che 7 beta 2 if `CHE_WEBSOCKET_ENDPOINT__MINOR` is not set

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#12968]
### Description
Subtle issue in che 7 beta 2 if `CHE_WEBSOCKET_ENDPOINT__MINOR` is not set:
Not setting  `CHE_WEBSOCKET_ENDPOINT__MINOR` enddpoint results in subtle error during workspace creation e.g. https://github.com/redhat-developer/rh-che/pull/1294#issuecomment-475910313

![image](https://user-images.githubusercontent.com/1461122/54872314-55345d00-4dc2-11e9-8c25-e3f84df01372.png)

```
2019-03-23 22:14:47,681[penshift.io/...]  [WARN ] [k.c.d.i.WatchConnectionManager 201]  - Exec Failure
--
  | java.io.EOFException: null
  | at okio.RealBufferedSource.require(RealBufferedSource.java:60)
  | at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
  | at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
  | at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
  | at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
  | at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
  | at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
  | at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | 2019-03-23 22:16:02,124[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 242]  - Failed to start Kubernetes runtime of workspace workspaceb3cmnd7yympzfuyt. Cause: Waiting for Kubernetes environment 'default' of the workspace'workspaceb3cmnd7yympzfuyt' reached timeout
```

Should we consider fail fast during che-server startup when the property is not set with a clear error message ?

**Comment by ibuziuk** [comment]
@skabashnyuk wdyt?

**Comment by skabashnyuk** [comment]
hard to say
