### ISSUE TITLE
Dashboard build failure.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12985]
### Description

Recent native builds on the master branch are failed.

### Reproduction Steps

```
cd dashboard
mvn package -Pnative
```

**OS and version:**    

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

**Diagnostics:** 

```
main:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.087 s
[INFO] Finished at: 2019-03-27T01:02:00+00:00
[INFO] Final Memory: 30M/1029M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (install-deps) on project che-dashboard-war: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "yarn": error=2, No such file or directory
[ERROR] around Ant part ...<exec failonerror="true" dir="/home/muranaka/che/dashboard" executable="yarn">... @ 4:81 in /home/muranaka/che/dashboard/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by monaka** [comment]
I think this is caused by #12955 .

**Comment by skabashnyuk** [comment]
I had failed dashboard build too today.
```
   [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 597 of 611 SUCCESS (0 secs / 52.686 secs)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 598 of 611 SUCCESS (0 secs / 52.804 secs)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 599 of 611 SUCCESS (0 secs / 52.924 secs)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 600 of 611 SUCCESS (0 secs / 53.051 secs)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 601 of 611 SUCCESS (0 secs / 53.194 secs)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 602 of 611 SUCCESS (0 secs / 53.349 secs)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 603 of 611 SUCCESS (0 secs / 53.473 secs)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 604 of 611 SUCCESS (0 secs / 53.601 secs)
     [exec] 27 03 2019 07:30:08.908:ERROR [launcher]: PhantomJS crashed.
     [exec]
     [exec] 27 03 2019 07:31:08.940:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
     [exec] 27 03 2019 07:32:08.894:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
     [exec] 27 03 2019 07:32:08.902:ERROR [launcher]: PhantomJS failed 2 times (timeout). Giving up.
     [exec] [07:32:08] 'test' errored after 3.23 min
     [exec] [07:32:08] Error: Failed 1 tests.
     [exec]     at /dashboard/gulp/unit-tests.js:53:22
     [exec]     at removeAllListeners (/dashboard/node_modules/karma/lib/server.js:336:7)
     [exec]     at Server.<anonymous> (/dashboard/node_modules/karma/lib/server.js:347:9)
     [exec]     at Object.onceWrapper (events.js:313:30)
     [exec]     at emitNone (events.js:111:20)
     [exec]     at Server.emit (events.js:208:7)
     [exec]     at emitCloseNT (net.js:1664:8)
     [exec]     at _combinedTickCallback (internal/process/next_tick.js:136:11)
     [exec]     at process._tickCallback (internal/process/next_tick.js:181:9)
     [exec] 27 03 2019 07:32:18.877:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (1 times)
     [exec] PhantomJS 2.1.1 (Linux 0.0.0): Executed 604 of 611 DISCONNECTED (3 mins 12.476 secs / 53.601 secs)
     [exec] 27 03 2019 07:33:18.820:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
     [exec] 27 03 2019 07:33:18.828:ERROR [launcher]: PhantomJS failed 2 times (timeout). Giving up.
     [exec] [07:33:18] 'test' errored after 4.4 min
     [exec] [07:33:18] Error: Failed 1 tests.
     [exec]     at /dashboard/gulp/unit-tests.js:53:22
     [exec]     at removeAllListeners (/dashboard/node_modules/karma/lib/server.js:336:7)
     [exec]     at /dashboard/node_modules/karma/lib/server.js:347:9
     [exec]     at Server.close (net.js:1613:9)
     [exec]     at Object.onceWrapper (events.js:313:30)
     [exec]     at emitNone (events.js:106:13)
     [exec]     at Server.emit (events.js:208:7)
     [exec]     at emitCloseNT (net.js:1664:8)
     [exec]     at _combinedTickCallback (internal/process/next_tick.js:136:11)
     [exec]     at process._tickCallback (internal/process/next_tick.js:181:9)
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] The command '/bin/sh -c yarn build && yarn test' returned a non-zero code: 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Che Parent 7.0.0-beta-3.0-SNAPSHOT:
[INFO]
[INFO] Che Parent ......................................... SUCCESS [  1.587 s]
[INFO] Che Core Parent .................................... SUCCESS [  0.046 s]
```
@ashumilova @benoitf can you comment?

**Comment by monaka** [comment]
@skabashnyuk It looks your PhantomJS was crashed in your case. I tried to reproduce and I couldn't. Just my guess but it may be caused by memory exhaust.

**Comment by monaka** [comment]
Close as #13052 was merged.
