### ISSUE TITLE
Error when starting workspace [Question]

### ISSUE THREAD

**Issue by feliwyn** [eclipse-che/che#1302]
Hi,

I want to trying Che... But impossible for me to start a workspace.

I'm running it on Archlinux, and I have this error when i trying to `run` my workspace.

I have trying 2 types of installation.
Docker, Server. For zipfile, or after compiling from source. Always get this error. :<

```

2016-05-19 20:37:23,714[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 162]      - Creating machine [ws = workspacemnox5w985n16cqt9: env = wksp-4de9: machine = ws-machine]
2016-05-19 20:37:23,719[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 549]    - Unable build docker based machine, Dockerfile found but it doesn't contain base image.
org.eclipse.che.api.machine.server.exception.MachineException: Unable build docker based machine, Dockerfile found but it doesn't contain base image.
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:405) ~[che-core-api-machine-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:342) ~[che-core-api-machine-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:166) ~[che-core-api-machine-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.createMachine(WorkspaceRuntimes.java:490) ~[che-core-api-workspace-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:411) ~[che-core-api-workspace-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:368) ~[che-core-api-workspace-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:180) ~[che-core-api-workspace-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:533) ~[che-core-api-workspace-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: org.eclipse.che.api.machine.server.exception.InvalidRecipeException: Unable build docker based machine, Dockerfile found but it doesn't contain base image.
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.parseRecipe(DockerInstanceProvider.java:275) ~[che-plugin-docker-machine-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:219) ~[che-plugin-docker-machine-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:365) ~[che-core-api-machine-4.3.0-RC1-SNAPSHOT.jar:4.3.0-RC1-SNAPSHOT]
        ... 11 common frames omitted

```

**Comment by ghost** [comment]
@feliwyn what kind of workspace do you start? A custom one? Or have you chosen one of the ready to go stacks in User Dashboard?

**Comment by feliwyn** [comment]
Thank's for reply.

I've try all ready to go.

**Comment by ghost** [comment]
@feliwyn can you reproduce it with 4.2.2?

What you can also do it to go to `http://localhost:8080/api/recipe` and grab any recipe to see if it has some content it in - `http://localhost:8080/ide/api/recipe/${recipe-id}/script`

**Comment by james10174** [comment]
@feliwyn Try `docker run -ti codenvy/ubuntu_jdk8 /bin/bash` from your archlinux shell.  Maybe it's a docker install issue or internet issue.

**Comment by feliwyn** [comment]
@eivantsov if 4.2.2 is the nigthly version, i have same error

@james10174 I want to use che as server. I hate docker :P! So, the command line download me the image, and start the shell

**Comment by TylerJewell** [comment]
@feliwyn If you are running the nightly, then that is 4.3.0-RC1-SNAPSHOT, which has a large number of bug fixes.

**Comment by james10174** [comment]
@feliwyn How are you starting Che server. Can you give your command line arguments if you have any.

**Comment by feliwyn** [comment]
@TylerJewell  & @james10174 

  415  wget https://install.codenvycorp.com/che/eclipse-che-nightly.zip
  416  unzip eclipse-che-nightly.zip
  417  cd eclipse-che-4.3.0-RC1-SNAPSHOT
  418  bin/che.sh run

Then i can see : Server startup in 5419 ms

**Comment by ghost** [comment]
@feliwyn I need to summarize some info to help you out. Can you please answer the following questions?
1. Do you run Che locally or remotely? If it is a remote instance of Che, how do you access it? IP/hostname?
2. Can you check http://localhost:8080/api/recipe and grab any recipe to see if it has some content it in - http://localhost:8080/ide/api/recipe/${recipe-id}/script (if it's not localhost, then IP/hostname).

**Comment by feliwyn** [comment]
1. I run Che remotly. A dedibox. So, i have try using proxy by nginx, and by the port 8080. (http://remoteip:8080/)
   I have try the arg -r:MYREMOTEIP and nothing have changed...
2. this? "http://62.210.xx.xx:8080/wsmaster/api/recipe/recipe_debian/script

**Comment by ghost** [comment]
Yes, this URL. Do you see any content there when access in a browser? Also, you may want to wget it from the instance where Che is launched.

**Comment by feliwyn** [comment]
I see : FROM codenvy/debian_jdk8

**Comment by ghost** [comment]
Can you also wget this script from within the instance?

Also, do you have an opportunity to run Che on Ubuntu and see if it makes any difference? I do not think this is OS specific issue though.

**Comment by feliwyn** [comment]
Hm... I can try on virtual machine a bit later.

**Comment by james10174** [comment]
@feliwyn Did you run 'docker run -ti codenvy/ubuntu_jdk8 /bin/bash' on your dedicated che server box or on the machine you use with your web browser? Also have you tried to create a custom stack in che. If not copy and paste [https://raw.githubusercontent.com/codenvy/dockerfiles/master/ubuntu_jdk8/Dockerfile](url).
Also what version of java are you running. I had trouble with openjdk using archlinux myself. Try the following if running che with openjdk. Change  /root/.bashrc to /home/<username>/.bashrc.

wget  --no-cookies  --no-check-certificate  --header "Cookie: oraclelicense=accept-securebackup-cookie"  "http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-x64.tar.gz"
tar -xzvf jdk-8u91-linux-x64.tar.gz -C /opt/
export JAVA_HOME=/opt/jdk1.8.0_91
echo "export JAVA_HOME=/opt/jdk1.8.0_91/" >> /root/.bashrc

**Comment by feliwyn** [comment]
@james10174 I running with openjdk, so i have tried with the oracle JDK, same error :<
With stack ready, and the linked one

Also, have this error : 

`[ERROR] [o.e.c.a.w.s.WorkspaceManager 549]    - Failed writing 8192 bytes`

**Comment by james10174** [comment]
@feliwyn The new error might be related to this open bug [https://github.com/eclipse/che/issues/745](url) . How much ram do you have on your server machine? 
Stick with oracle JDK. I know I had issues with openjdk.

**Comment by ddementieva** [comment]
Closing this issue. Will track https://github.com/eclipse/che/issues/745
