### ISSUE TITLE
WFLYDR0006: Directory /opt/jboss/keycloak/standalone/tmp is not writable

### ISSUE THREAD

**Issue by bryanxtong** [eclipse-che/che#13086]
### Description

I tried to install che in docker in a red hat linux host and when I started it, It keeps sending error messages to the console.
version : 'eclipse/che:7.0.0-beta-2.0'

### Reproduction Steps
just run the command 
docker run -it -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /data/.che-multiuser:/data eclipse/che start --fast

**OS and version:**    
Linux bigdata 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Diagnostics:** 

The below is docker logs  "docker logs -f che_keycloak_1"
```
02:01:11,805 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
02:01:12,060 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
02:01:12,190 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: Keycloak 3.4.3.Final (WildFly Core 3.0.8.Final) starting
02:01:12,199 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.as: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1978) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_151]
Caused by: java.lang.IllegalStateException: WFLYDR0006: Directory /opt/jboss/keycloak/standalone/tmp is not writable
        at org.jboss.as.repository.ContentRepositoryImpl.checkDirectory(ContentRepositoryImpl.java:101)
        at org.jboss.as.repository.ContentRepositoryImpl.<init>(ContentRepositoryImpl.java:85)
        at org.jboss.as.repository.ContentRepository$Factory.addService(ContentRepository.java:185)
        at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:145) [wildfly-server-3.0.8.Final.jar:3.0.8.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        ... 3 more

java.util.concurrent.ExecutionException: Operation failed
        at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
        at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
        at org.jboss.as.server.Main.main(Main.java:108)
        at org.jboss.modules.Module.run(Module.java:344)
        at org.jboss.modules.Main.main(Main.java:525)
Caused by: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1978)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: WFLYDR0006: Directory /opt/jboss/keycloak/standalone/tmp is not writable
        at org.jboss.as.repository.ContentRepositoryImpl.checkDirectory(ContentRepositoryImpl.java:101)
        at org.jboss.as.repository.ContentRepositoryImpl.<init>(ContentRepositoryImpl.java:85)
        at org.jboss.as.repository.ContentRepository$Factory.addService(ContentRepository.java:185)
        at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:145)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955)
        ... 3 more
02:01:12,203 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
```

**Comment by bryanxtong** [comment]
Hello, this red hat linux is an instance created by openstack. 
ip: 192.168.0.14
elastic ip: 10.157.166.142
an older version of docker instance jboss/keycloak-openshift:3.3.0.CR2-3 has no such problem.

**Comment by bryanxtong** [comment]
Can someone provide some clue？ as the same happens even for 6.19.0.
