### ISSUE TITLE
CI E2E selenium tests jobs stuck on the command "ocp.sh --destroy" on OpenShift 3.11 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#13322]
### Description
There are E2E selenium test jobs on CI which stuck after the movement to OpenShift 3.11 by default (PR https://github.com/eclipse/che/pull/12357) at the step:
```
bash ${WORKSPACE}/deploy/openshift/ocp.sh --destroy
```
For example: https://ci.codenvycorp.com/job/che-integration-tests-multiuser-master-ocp/615/console
```
[che-integration-tests-multiuser-master-ocp] $ /bin/bash /tmp/jenkins5296940920537614680.sh
Logged into "https://172.29.4.74:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
  * eclipse-che
    kube-dns
    kube-proxy
    kube-public
    kube-system
    myproject
    openshift
    openshift-apiserver
    openshift-controller-manager
    openshift-core-operators
    openshift-infra
    openshift-node
    openshift-service-cert-signer
    openshift-web-console

Using project "eclipse-che".
  adding: che-server-pod.log (deflated 96%)
  adding: keycloak.log (deflated 78%)
  adding: ocp-events.log (deflated 93%)
  adding: postgres.log (deflated 65%)
Logged into "https://172.29.4.74:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
  * eclipse-che
    kube-dns
    kube-proxy
    kube-public
    kube-system
    myproject
    openshift
    openshift-apiserver
    openshift-controller-manager
    openshift-core-operators
    openshift-infra
    openshift-node
    openshift-service-cert-signer
    openshift-web-console

Using project "eclipse-che".
persistentvolumeclaim "che-data-volume" deleted
persistentvolumeclaim "claim-che-workspace" deleted
persistentvolumeclaim "keycloak-data" deleted
persistentvolumeclaim "keycloak-log" deleted
persistentvolumeclaim "postgres-data" deleted
[PostBuildScript] - [ERROR] Problem occurred: java.lang.InterruptedException
```

**_Possible solution_**: use another command to remove OpenShfit containers:
```
docker rm -f $(docker ps -aq)
```

**Comment by skryzhny** [comment]
Updated jobs, waiting night cycle to ensure it fixed the problem.

**Comment by dmytro-ndp** [comment]
It helped partly because there are mount volumes remained and should be un-mount in advance https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/1792/console:
```
Building remotely on qa-slave-1 in workspace /home/codenvy/workspace/che-pullrequests-test-ocp
Wiping out workspace first.
java.nio.file.FileSystemException: /home/codenvy/workspace/che-pullrequests-test-ocp/openshift.local.clusterup/openshift.local.volumes/pods: Operation not permitted
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:238)
    at sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:260)
    at java.nio.file.Files.setPosixFilePermissions(Files.java:2045)
    at hudson.Util.makeWritable(Util.java:337)
    at hudson.Util.tryOnceDeleteFile(Util.java:297)
    at hudson.Util.deleteFile(Util.java:272)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to qa-slave-1
        at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
        at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
        at hudson.remoting.Channel.call(Channel.java:955)
        at hudson.FilePath.act(FilePath.java:1036)
        at hudson.FilePath.act(FilePath.java:1025)
        at hudson.FilePath.deleteContents(FilePath.java:1250)
        at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:30)
        at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1183)
        at hudson.scm.SCM.checkout(SCM.java:504)
        at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
        at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
        at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
        at hudson.model.Run.execute(Run.java:1794)
        at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:429)
```

Possible fixup:
```
sudo umount $(mount | grep "openshift.local.clusterup" | awk '{if(NR>0) print $3}')
```

**Comment by sunix** [comment]
Hello, it seems the PR has been merged,
I am closing it but feel free to reopen it if this is not finished

**Comment by dmytro-ndp** [comment]
[PR](https://github.com/eclipse/che/pull/13351) was kind of workaround (don't use OKD 3.11 by default). That PR didn't fix the issue, and the issue is still actual.
So, there should be another reason to close the issue.
