### ISSUE TITLE
Stabilize E2E Happy path tests on kubernetes (minikube) infra in Central CI

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13473]
We should stop using slave9 from codenvycorp CI and switch to CentralCI resources, until we figure out, where will all jobs crom codenvycorp ci migrate.

**Comment by rhopp** [comment]
I guess this should be implemented as a pipeline job:
![image](https://user-images.githubusercontent.com/1215011/59029608-fa59c000-885e-11e9-83cf-9ef4da9da003.png)

**Comment by dmytro-ndp** [comment]
Current state:
#### minikube start error:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Happy-Path-Tests/1449/
<details>
 <summary>minikube start error log</summary>
 <pre>
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
 output: [init] Using Kubernetes version: v1.14.3
[preflight] Running pre-flight checks
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.1. Latest validated version: 18.09
	[WARNING Hostname]: hostname "minikube" could not be reached
	[WARNING Hostname]: hostname "minikube": lookup minikube on 10.11.5.19:53: no such host
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
.: exit status 1
 </pre>
</details>

#### Plugin runtime crashed unexpectedly
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Happy-Path-Tests/1457/
<details>
 <summary>Validation of workspace build and run error log</summary>
 <pre>
       Build application:
     TimeoutError: Wait timed out after 220450ms
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
  From: Task: <anonymous wait>
      at scheduleWait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/home/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Editor.<anonymous> (/home/e2e/pageobjects/ide/Editor.ts:176:45)
      at Generator.next (<anonymous>)
      at fulfilled (/home/e2e/dist/pageobjects/ide/Editor.js:16:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
 </pre>
</details>
![screenshot-Build_application_2019 09 04](https://user-images.githubusercontent.com/1197777/64238440-1a088f00-cf07-11e9-9af7-3666ffb0cf1d.png)

#### Validation of debug functionality error
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Happy-Path-Tests/1453/console
<details>
 <summary>Validation of debug functionality error log</summary>
 <pre>
1) Validation of debug functionality
       Launch debug:
     TimeoutError: Waiting until element is visible
Wait timed out after 180001ms
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: Waiting until element is visible
      at scheduleWait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/home/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at DriverHelper.<anonymous> (/home/e2e/utils/DriverHelper.ts:87:61)
      at Generator.next (<anonymous>)
      at fulfilled (/home/e2e/dist/utils/DriverHelper.js:16:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: <anonymous>
      at pollCondition (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2191:7
      at new ManagedPromise (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at ControlFlow.promise (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2505:12)
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2190:22
      at TaskQueue.execute_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: <anonymous wait>
      at scheduleWait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/home/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Ide.<anonymous> (/home/e2e/pageobjects/ide/Ide.ts:54:45)
      at Generator.next (<anonymous>)
      at /home/e2e/dist/pageobjects/ide/Ide.js:19:71
      at new Promise (<anonymous>)
      at __awaiter (/home/e2e/dist/pageobjects/ide/Ide.js:15:12)
      at Ide.waitNotificationAndClickOnButton (/home/e2e/dist/pageobjects/ide/Ide.js:67:16)
      at Ide.<anonymous> (/home/e2e/pageobjects/ide/Ide.ts:80:20)
      at Generator.next (<anonymous>)
      at fulfilled (/home/e2e/dist/pageobjects/ide/Ide.js:16:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
 </pre>
</details>
![screenshot-Build_application_2019 09 04_2](https://user-images.githubusercontent.com/1197777/64238645-79669f00-cf07-11e9-9528-7c7c1fb0fc9a.png)

**Comment by dmytro-ndp** [comment]
Current state:
- minikube start fails sometimes on upshift instance:
```
X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap

: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
 output: [init] Using Kubernetes version: v1.14.3
[preflight] Running pre-flight checks
	[WARNING Firewalld]: firewalld is active, please ensure ports [8443 10250] are open or your cluster may not function correctly
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.2. Latest validated version: 18.09
	[WARNING Hostname]: hostname "minikube" could not be reached
	[WARNING Hostname]: hostname "minikube": lookup minikube on 10.11.5.19:53: no such host
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
```
Possible fixup - to rearrange more memory for minikube.

- https://github.com/eclipse/che/issues/14714 - in progress

**Comment by dmytro-ndp** [comment]
Current status:
- minikube start failire on upshift instance is still actual https://github.com/eclipse/che/issues/14902
- https://github.com/eclipse/che/issues/14714 - has been fixed
