### ISSUE TITLE
Create jenkins job  for checking HappyPath scenario with creation ws. from devfile.

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13523]
### Description
The scenario is described in the step 3 of: https://github.com/eclipse/che/issues/12728
The related job: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che7-e2e-tests/job/CHE-7-Happy-Path-Tests/

On this moment the job is unstable because we have some issues:
* https://github.com/eclipse/che/issues/13498
* https://github.com/che-incubator/chectl/issues/145
Sometimes we get errors like:
```
[04:19:28] → Error: connect ECONNREFUSED 192.168.39.119:8443
11:19:29 [04:19:28] Che pod bootstrap [failed]
11:19:29 [04:19:28] → Error: connect ECONNREFUSED 192.168.39.119:8443
11:19:29 [04:19:28] ✅  Post installation checklist [failed]
11:19:29 [04:19:28] → Error: connect ECONNREFUSED 192.168.39.119:8443
11:19:29 Error: Error: connect ECONNREFUSED 192.168.39.119:8443
11:19:29     at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
11:19:29     at Generator.throw (<anonymous>)
11:19:29     at rejected (/snapshot/chectl/node_modules/tslib/tslib.js:108:69)
11:19:29 Build step 'Execute shell' marked build as failure
```
------
```
22:50:05 [15:50:04] → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
22:50:05 [15:50:04] Che pod bootstrap [failed]
22:50:05 [15:50:04] → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
22:50:05 [15:50:04] ✅  Post installation checklist [failed]
22:50:05 [15:50:04] → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
22:50:05 Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000
22:50:05     at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
22:50:05     at Generator.next (<anonymous>)
22:50:05     at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:104:62)
22:50:05 Build step 'Execute shell' marked build as failure
```
We should stabilize this job, fix and implement possible workarounds for this

**Comment by musienko-maxim** [comment]
So we tried to apply other tactics for launching tests. I made short investigation problems and i made sure, that minikube with nested virtualization works too slowly. For instance: after minikube ssh and pulling an image the timeout was about 30-40 min. After that i tried to avoid nested virtualization. The most simple solution as for me was using param for minikube like `--vm-driver=none`. We tried it on Amazon instance (UpShift was broken) and after fixing  a lot of infrastructure issues, we got stable job  https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-mini/.
So on this moment it like as proof on concept and i guess it can be applied on UpShift infra on regular basis.

**Comment by musienko-maxim** [comment]
On the  https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-mini/ job the behavior of HappyPath test is stable. The infrastructure problem which we've had with nested virtualisation is not reproduced. I think we can close this issue
