### ISSUE TITLE
 Error starting che 7 multiuser

### ISSUE THREAD

**Issue by tomevision** [eclipse-che/che#13575]
i was trying to start che 7 multiuser on my virtual machine but it gives me this issues

 PostgreSQL pod bootstrap [started]
 scheduling [started]
 scheduling [failed]
→ ERR_UNEXPECTED_PHASE: Running (Pending expected)
 PostgreSQL pod bootstrap [failed]
 → ERR_UNEXPECTED_PHASE: Running (Pending expected)
✅  Post installation checklist [failed]
 → ERR_UNEXPECTED_PHASE: Running (Pending expected)
Error: ERR_UNEXPECTED_PHASE: Running (Pending expected)
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:104:62)

    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/chectl/node_modules/tslib/tslib.js:105:69)

**Comment by z0r0** [comment]
I'm experiencing this as well.
