### ISSUE TITLE
Theia can't open files located in a sidecar container

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#13614]
### Reproduction Steps

1. Start workspace with a Typescrip plugin.
2. Goto preferences and set `typescript.tsserver.trace` to `verbose`
3. Try to run command `Open TS server log file`
4. Server log file can't be opened

**OS and version:**    
Che-7.0.0-CR2

**Diagnostics:** 
LS sends request to Theia to open a log file but Theia can't find the file because it is located in a side-car container.

https://github.com/eclipse/che/issues/13428

**Comment by tolusha** [comment]
It is turned out to be a more general issue when plugin sends request to Theia to open an file that exists only in a sidecar container.

```
errors.ts:81 Uncaught Error: 'file:///usr/include/c%2B%2B/8/iostream' has not been found.

Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1742008)
    at e.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1918534)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1917105
    at Object.next (https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1917210)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1916123
    at new Promise (<anonymous>)
    at T1Xs.a (https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1915900)
    at e.readContents (https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1918393)
    at new e (https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:4146586)
    at e.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.80ec0f4ae0530039ebdd.js:1:1456739)
Caused by: Error: 'file:///usr/include/c%2B%2B/8/iostream' has not been found.
    at FileSystemNode.<anonymous> (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:160:64)
    at step (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:58)
    at https://cdn.jsdelivr.net/npm/@typefox/monaco-editor-core@0.14.6/min/vs/editor/editor.main.js:158:350
```

**Comment by tolusha** [comment]
It is relatively easy to redirect a request to retrieve content from a side-car container, but we have to take into account that redirection matters only for files that are not available from a Theia container.

**Comment by tsmaeder** [comment]
An approach would be to rewrite some URIs (those not under /projects) when we get them from plugins and redispatch them to the plugin containers for resolving contents, etc. We should start a conversation about this on che-dev and do a spike first.

**Comment by tolusha** [comment]
The solution might be accomplished in following steps. (It has been tested yet)


1. Override scheme by adding a sidecar identifier (which is basically a machine name)
https://github.com/eclipse/che-theia/blob/ab/sidecarcontent/extensions/eclipse-che-theia-plugin-remote/src/node/content-container-aware.ts#L14

2. Binding content resolver to handle all those kind of schemes
https://github.com/eclipse/che-theia/blob/ab/sidecarcontent/extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-resource.ts#L49

3.  Sending request to a sidecar container to retrieve the content
https://github.com/eclipse/che-theia/blob/ab/sidecarcontent/extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-content-resolver-main.ts#L27

**Comment by tsmaeder** [comment]
@tolusha but if I understand correctly, the file being opened is, for example as a result of a "goto definition" request, which is not going through "open document". 
I think the approach should be to change all api calls that return URI's to return an uri that is specific to the sidecar (unless it's a uri that is in a known shared area)

**Comment by tolusha** [comment]
It probably will require to override some other API calls but I don't know for sure which ones.

**Comment by tsmaeder** [comment]
@tolusha all of them which return a URI.

**Comment by tolusha** [comment]
It is possible to open files from a sidecar container in the Theia

1. Override scheme by adding a sidecar identifier (which is basically a machine name)
https://github.com/eclipse/che-theia/blob/ab/scc/extensions/eclipse-che-theia-plugin-remote/src/node/content-container-aware.ts#L15

2. Binding content resolver to handle all those kind of schemes
https://github.com/eclipse/che-theia/blob/ab/scc/extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-resource.ts#L22

3.  Sending request to a sidecar container to retrieve the content
https://github.com/eclipse/che-theia/blob/ab/scc/extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-content-reader-main.ts#L14

4. Retrieve content in a sidecar container
https://github.com/eclipse/che-theia/blob/ab/scc/extensions/eclipse-che-theia-plugin-ext/src/plugin/che-sidecar-content-reader.ts#L15

![Screenshot from 2019-08-30 11-28-56](https://user-images.githubusercontent.com/1640675/64019310-7b131a00-cb37-11e9-8867-50b3d76715c5.png)

**Comment by tolusha** [comment]
We still have issue with gotoDefinition for c/c++ plugin
```
root INFO {exception: null, error: Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (http://routejunfjjtr-che.192.168.9…, promise: n.C…s.d…e._creator, handler: undefined, id: 6, …}error: Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:12:923880)
    at e.<anonymous> (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:150903)
    at http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:149492
    at Object.next (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:149597)
    at http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:148510
    at new Promise (<anonymous>)
    at a (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:148287)
    at e.readContents (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:150762)
    at new e (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:473498)
    at e.<anonymous> (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:12:768245)
Caused by: Error: 'file:///usr/include/c%2B%2B/8/iostream' has not been found.
    at FileSystemNode.<anonymous> (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:162:64)
    at step (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:58)exception: nullhandler: undefinedid: 6parent: undefinedpromise: n.Class.derive._creator {_creator: null, _nextState: null, _state: {…}, _value: Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (http://routejunfjjtr-che.192.168.9…, _listeners: null, …}__proto__: Object
editor.main.js:158 Uncaught Error: 'file:///usr/include/c%2B%2B/8/iostream' has not been found.

Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:12:923880)
    at e.<anonymous> (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:150903)
    at http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:149492
    at Object.next (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:149597)
    at http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:148510
    at new Promise (<anonymous>)
    at a (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:148287)
    at e.readContents (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:150762)
    at new e (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:30:473498)
    at e.<anonymous> (http://routejunfjjtr-che.192.168.99.100.nip.io/bundle.js:12:768245)
Caused by: Error: 'file:///usr/include/c%2B%2B/8/iostream' has not been found.
    at FileSystemNode.<anonymous> (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:162:64)
    at step (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:58)
    at http://routejunfjjtr-che.192.168.99.100.nip.io/vs/editor/editor.main.js:158:350
```

**Comment by tsmaeder** [comment]
@tolusha yes, we need to override all requests that return an uri from a sidecar, like "references", "definitions", etc, etc. We will not be able to catch them all (for example, if uri's are inside command parameters, which are unknown to us), but most of them.

**Comment by tsmaeder** [comment]
I think handling uri's in the languages namespace would go a long way: https://code.visualstudio.com/api/references/vscode-api#languages

**Comment by tsmaeder** [comment]
We'll start by fixing the issue with the C++ plugin and provide a PR for that (definitions provider).

**Comment by tolusha** [comment]
I've added overriding definition provider [1] and it allowed `gotoDefinition` feature works.

[1]  https://github.com/eclipse/che-theia/blob/ab/scc/extensions/eclipse-che-theia-plugin-remote/src/node/languages-container-aware.ts#L22

![Screenshot from 2019-09-18 13-51-04](https://user-images.githubusercontent.com/1640675/65143208-1273da80-da1d-11e9-9135-0d3c5d6b4173.png)
