### ISSUE TITLE
Errors in Che Theia container log when start a terminal

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13630]
### Description

When start a terminal in Che Theia, a lot of error logs appears in the Che Theia IDE logs:

```
root ERROR Request getCwdURI failed with error: terminal "1" does not exist Error: terminal "1" does not exist
  at ShellTerminalServer.<anonymous> (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:117:27)
  at step (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:59:23)
  at Object.next (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:40:53)
  at /home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:34:71
  at new Promise (<anonymous>)
  at __awaiter (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:30:12)
  at ShellTerminalServer.BaseTerminalServer.getCwdURI (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:112:16)
  at JsonRpcProxyFactory.<anonymous> (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:217:73)
  at step (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:47:23)
  at Object.next (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:28:53)
```
The error is repeated many times.

### Reproduction Steps

1. Create a workspace with Che Theia editor and start it.
2. Open a terminal in any container
3. See `theia-ide` container logs.

**Comment by mmorhun** [comment]
During investigation I found that the error is not directly related to hosted instance and happens on terminal creation
