### ISSUE TITLE
Impossible to restart Che from chectl

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13656]
### Description
```
 ✖ Updating Helm Chart dependencies
      → Error: Unable to move current charts to tmp dir: rename /Users/slemeur/Library/Caches/chectl/templ
…
      Deploying Che Helm Chart
Error: Command failed: /bin/sh -c helm dependencies update --skip-refresh /Users/slemeur/Library/Caches/chectl/templates/kubernetes/helm/che/
Error: Unable to move current charts to tmp dir: rename /Users/slemeur/Library/Caches/chectl/templates/kubernetes/helm/che/charts /Users/slemeur/Library/Caches/chectl/templates/kubernetes/helm/che/tmpcharts: file exists
    at makeError (/snapshot/chectl/node_modules/execa/index.js:174:9)
    at module.exports.Promise.all.then.arr (/snapshot/chectl/node_modules/execa/index.js:278:16)
```

Doing a chectl delete did not help.

### Reproduction Steps
- chectl server:stop
- chectl server:delete
- chectl server:start

**OS and version:**    
chectl/0.0.2-6631177 darwin-x64 node-v10.15.3

**Diagnostics:**

**Comment by benoitf** [comment]
seems to be linked to https://github.com/helm/helm/issues/5567

what's your helm version


you may try to remove the whole chectl cache
```
rm -rf /Users/slemeur/Library/Caches/chectl/
```

**Comment by slemeur** [comment]
Worked
