### ISSUE TITLE
Impossible to start workspaces on minikube che7-rc3

### ISSUE THREAD

**Issue by fErten** [eclipse-che/che#13685]
### Description

Unable to start a workspace with che7 deployed on minikube.

Che is deployed on a Ubuntu virtual machine using minikube with --vm-driver=none (docker as a driver) Installation is successful with chectl however I am not able to start workspace or successfully see workspace configuration.

### Reproduction Steps
1 -- installation process
````
minikube start --vm-driver=none --cpus 2 --memory 4096
chectl server:start --multiuser
````
2 - create a worksapce from dasboard

**OS and version:**    
minikube: v1.2.0
chectl: chectl/0.0.2-8139730 linux-x64 node-v10.4.1
eclipse/che-server: nightly -- 7.0.0-rc-3.0-SNAPSHOT 

**Diagnostics:** 

I get the error;

````
Press F5 or click here to try again.
Cleaning /plugins dir
Starting Init Plugin Broker
Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.openshift.io/plugins/che-incubator/typescript/latest/meta.yaml': Downloading https://che-plugin-registry.openshift.io/plugins/che-incubator/typescript/latest/meta.yaml failed. Status code 404. Response body: 



Not Found

The requested URL /plugins/che-incubator/typescript/latest/meta.yaml was not found on this server.



Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspace1w2gjjgyznjsxiww failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.openshift.io/plugins/che-incubator/typescript/latest/meta.yaml': Downloading https://che-plugin-registry.openshift.io/plugins/che-incubator/typescript/latest/meta.yaml failed. Status code 404. Response body: 



Not Found

The requested URL /plugins/che-incubator/typescript/latest/meta.yaml was not found on this server.

"
````

![image](https://user-images.githubusercontent.com/31271774/60590418-3455ad80-9d9c-11e9-84a2-09049578c096.png)

Workspace configuration also does not work properly, all properties are shown as null

![image](https://user-images.githubusercontent.com/31271774/60590484-62d38880-9d9c-11e9-9cf8-e0a423ac0432.png)

**Comment by slemeur** [comment]
Hi @fErten. Thanks for reporting the issue. We are currently having issues to deploy che in multiuser on minikube: https://github.com/eclipse/che/issues/13625

Are you facing the same issue when trying with a single-user Che?

**Comment by benoitf** [comment]
it's related to https://github.com/che-incubator/chectl/issues/92

**Comment by benoitf** [comment]
changing assignee as @l0rd is already working on it

**Comment by benoitf** [comment]
@slemeur using single user is working as it's using helm and not the che-operator

**Comment by fErten** [comment]
@slemeur for the single user I am not even able to install che susccesfully, deploying helm chart fails, the error i am having is ;
```
Error: Command failed: /bin/sh -c helm upgrade --install che --force --namespace che --set global.ingressDomain=192.168.3.159.nip.io --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace=che   /home/user/.cache/chectl/templates/kubernetes/helm/che/
E0703 14:22:23.596736    8353 portforward.go:400] an error occurred forwarding 42137 -> 44134: error forwarding port 44134 to pod 45045a96d04e5cd9a86b2a799cfdd6b652fd8d6fa8c09b4aca13b5095e802e79, uid : unable to do port forwarding: socat not found.
E0703 14:22:24.603699    8353 portforward.go:400] an error occurred forwarding 42137 -> 44134: error forwarding port 44134 to pod 45045a96d04e5cd9a86b2a799cfdd6b652fd8d6fa8c09b4aca13b5095e802e79, uid : unable to do port forwarding: socat not found.
E0703 14:22:26.399211    8353 portforward.go:400] an error occurred forwarding 42137 -> 44134: error forwarding port 44134 to pod 45045a96d04e5cd9a86b2a799cfdd6b652fd8d6fa8c09b4aca13b5095e802e79, uid : unable to do port forwarding: socat not found.
E0703 14:22:59.262942    8353 portforward.go:340] error creating error stream for port 42137 -> 44134: Timeout occured
E0703 14:23:23.124267    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:23:49.337865    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:24:21.433321    8353 portforward.go:340] error creating error stream for port 42137 -> 44134: Timeout occured
E0703 14:25:01.147929    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:25:58.517130    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:27:06.108560    8353 portforward.go:340] error creating error stream for port 42137 -> 44134: Timeout occured
E0703 14:27:53.634942    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:28:14.635583    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:28:36.230979    8353 portforward.go:340] error creating error stream for port 42137 -> 44134: Timeout occured
E0703 14:28:58.479687    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:29:22.076857    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:29:49.008115    8353 portforward.go:340] error creating error stream for port 42137 -> 44134: Timeout occured
E0703 14:30:18.545916    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:30:58.595352    8353 portforward.go:362] error creating forwarding stream for port 42137 -> 44134: Timeout occured
E0703 14:31:56.830502    8353 portforward.go:340] error creating error stream for port 42137 -> 44134: Timeout occured
Error: UPGRADE FAILED: context deadline exceeded
UPGRADE FAILED
Error: context deadline exceeded
    at makeError (/snapshot/chectl/node_modules/execa/index.js:174:9)
    at module.exports.Promise.all.then.arr (/snapshot/chectl/node_modules/execa/index.js:278:16)

```

**Comment by l0rd** [comment]
@benoitf why do you think that it's related to the operator? The default installer on minikube should be `helm` even with `--multiuser` right?

**Comment by benoitf** [comment]
I think error on previous registries URL have been fixed in all installers helm, operator and minishift-addons

**Comment by benoitf** [comment]
Please reopen if not fixed but with the latest `chectl` it can't be reproduced
