### ISSUE TITLE
cat: can't open '/proc/net/tcp6': No such file or directory

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13749]
### Description

It looks the-theia can't access `/proc/net/tcp6` in the instance running as non-root.

### Reproduction Steps

1. Run as the non-root instance
2. Start workspace
3. Check logs from `che-theia` container.

**OS and version:**    

7.0.0-RC-2.0-SNAPSHOT

**Diagnostics:** 

```
root ERROR [hosted-plugin: 54] (node:54) UnhandledPromiseRejectionWarning: Error: Unable to execut
e the command cat /proc/net/tcp6: Error: Command failed: cat /proc/net/tcp6
cat: can't open '/proc/net/tcp6': No such file or directory

    at new CliError (/tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/cli-error.js:32:28)
    at /tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/command.js:69:40
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
```

**Comment by monaka** [comment]
I close this as eclipse/che-theia#315 was merged.
