### ISSUE TITLE
[no port available in range [7800 .. 7850]]che-server deploy error

### ISSUE THREAD

**Issue by yuqaf1989** [eclipse-che/che#13841]
when I try to deploy che 7 on k8s via helm command: `helm upgrade --install che-multi --namespace eclipse -f ./values/default-host.yaml --set global.ingressDomain=che-eclipse.my-nginx-nginx-ingress-controller.default.svc.cluster.local ./`. Deployment of keycloak and postgres are OK, but che-server can not startup, I found the error blow, It seems that jgroup can not bind port to ipv6 address.

## Summary
errro log:
```
2019-07-13 01:59:30,508[ost-startStop-1]  [ERROR] [.c.c.d.j.g.GuiceJpaInitializer 37]   - Persistence service was already initialized.
java.lang.IllegalStateException: Persistence service was already initialized.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.inject.persist.jpa.JpaPersistService.start(JpaPersistService.java:106)
	at org.eclipse.che.core.db.jpa.guice.GuiceJpaInitializer.init(GuiceJpaInitializer.java:35)
	at org.eclipse.che.core.db.DBInitializer.<init>(DBInitializer.java:68)
	at org.eclipse.che.core.db.DBInitializer$$FastClassByGuice$$411a5c44.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-13 01:59:30,556[ost-startStop-1]  [INFO ] [unknown.jul.logger 49]               - namespace [eclipse] set; clustering enabled
2019-07-13 01:59:30,566[ost-startStop-1]  [INFO ] [unknown.jul.logger 49]               - Starting UndertowServer on port 8888 for channel address: che-7799f86d55-thkkc-62682
2019-07-13 01:59:30,572[ost-startStop-1]  [INFO ] [unknown.jul.logger 49]               - UndertowServer reused (pre-existing).
2019-07-13 01:59:30,589[ost-startStop-1]  [ERROR] [butedRemoteSubscriptionStorage 58]   - Unable to create distributed event subscriptions map.
java.net.BindException: no port available in range [7800 .. 7850] (bind_addr=/fe80:0:0:0:c0af:76ff:fe80:cb03%eth0)
```
`addr=/fe80:0:0:0:c0af:76ff:fe80:cb03%eth0` is the default ipv6 interface

## Relevant information
che-version: `nightly`
k8s-version: `v1.14.2`
os version: `debian 9`

**Comment by skabashnyuk** [comment]
are there any other exceptions in the log?

**Comment by yuqaf1989** [comment]
keycloak looks OK. I can login keycloak via /auth . And there were  no other logs from keycloak while deploying che.  I also set log level to DEBUG, but error logs are same.

**Comment by skabashnyuk** [comment]
can you provide logs from Che-master?

**Comment by yuqaf1989** [comment]
I can't access into che-master(http 503), the state of che pod is `Readiness probe failed: HTTP probe failed with statuscode: 500`

**Comment by nickboldt** [comment]
The officially supported way to deploy che is with chectl. Can you try that instead of using raw helm commands?

https://github.com/che-incubator/chectl#chectl-serverstart

**Comment by yuqaf1989** [comment]
Try to deploy via chectl again , the same error occured again.
chectl info below:
```
./chectl_c server:start -b che-eclipse.my-nginx-nginx-ingress-controller.default.svc.cluster.local -p k8s -m
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify remote kubernetes status...done.
    ✔ Verify domain is set...set to che-eclipse.my-nginx-nginx-ingress-controller.default.svc.cluster.local.
  ✔ 🏃‍  Running Helm to install Che
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...it already exist.
    ✔ Create Tiller Service Account...it already exist.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...it already exist.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Che Helm Chart...done.
  ❯ ✅  Post installation checklist
    ❯ PostgreSQL pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Keycloak pod bootstrap
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:107:62)

```
