### ISSUE TITLE
Happy Path test is sometimes failing on "Error highlighting" step

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13865]
It seems, that the test was not able to type the text, which should trigger the error highlight.

Stacktrace:
```
14:35:45   1) Language server validation
14:35:45        Error highlighting:
14:35:45      TimeoutError: Wait timed out after 300021ms
14:35:45       at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
14:35:45       at ManagedPromise.invokeCallback_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
14:35:45       at TaskQueue.execute_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
14:35:45       at TaskQueue.executeNext_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
14:35:45       at asyncRun (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
14:35:45       at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
14:35:45       at <anonymous>
14:35:45       at process._tickCallback (internal/process/next_tick.js:188:7)
14:35:45   From: Task: <anonymous wait>
14:35:45       at scheduleWait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
14:35:45       at ControlFlow.wait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
14:35:45       at thenableWebDriverProxy.wait (/home/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
14:35:45       at DriverHelper.<anonymous> (/home/e2e/dist/utils/DriverHelper.js:155:36)
14:35:45       at Generator.next (<anonymous>)
14:35:45       at /home/e2e/dist/utils/DriverHelper.js:19:71
14:35:45       at new Promise (<anonymous>)
14:35:45       at __awaiter (/home/e2e/dist/utils/DriverHelper.js:15:12)
14:35:45       at DriverHelper.waitDisappearanceWithTimeout (/home/e2e/dist/utils/DriverHelper.js:154:16)
14:35:45       at Editor.<anonymous> (/home/e2e/dist/pageobjects/ide/Editor.js:232:37)
14:35:45       at Generator.next (<anonymous>)
14:35:45       at fulfilled (/home/e2e/dist/pageobjects/ide/Editor.js:16:58)
14:35:45       at <anonymous>
14:35:45       at process._tickCallback (internal/process/next_tick.js:188:7)
```

Example run of such failure: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Happy-Path-Tests/343/

Screenshot:
![image](https://user-images.githubusercontent.com/1215011/61296682-e2b91400-a7da-11e9-9b2f-d96f50ec7348.png)

**Comment by SkorikSergey** [comment]
Error highlighting notification 
![ErrorHighligtinh](https://user-images.githubusercontent.com/7760565/61776258-5672a680-ae03-11e9-8a35-4c3ae85d239b.png)

**Comment by musienko-maxim** [comment]
In the selenium test undo `operations (ctrl+z)` was replaced with removing a content with `Back Space` keys. Looks like the failure in the test is disappeared bu the problem with undo operation still actual

**Comment by rhopp** [comment]
We haven't seen this issue in some time. Considering resolved - closing now - feel free to reopen, if it happens again.
