### ISSUE TITLE
Happy Path test sometimes fail on "Validation of debug functionality"

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13864]
Stacktrace:
```
11:44:15   Validation of debug functionality
11:44:18     ✓ Open file and activate breakpoint (3606ms)
11:46:31     1) Launch debug
11:46:31 
11:46:31 
11:46:31   20 passing (6m)
11:46:31   1 pending
11:46:31   1 failing
11:46:31 
11:46:31   1) Validation of debug functionality
11:46:31        Launch debug:
11:46:31      TimeoutError: Waiting for element to be located By(xpath, //div[@class='theia-Notification' and contains(@id,'Redirect is now enabled on port 8080')])
11:46:31 Wait timed out after 120009ms
11:46:31       at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
11:46:31       at ManagedPromise.invokeCallback_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
11:46:31       at TaskQueue.execute_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
11:46:31       at TaskQueue.executeNext_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
11:46:31       at asyncRun (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
11:46:31       at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
11:46:31       at <anonymous>
11:46:31       at process._tickCallback (internal/process/next_tick.js:188:7)
11:46:31   From: Task: Waiting for element to be located By(xpath, //div[@class='theia-Notification' and contains(@id,'Redirect is now enabled on port 8080')])
11:46:31       at scheduleWait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
11:46:31       at ControlFlow.wait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
11:46:31       at thenableWebDriverProxy.wait (/home/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
11:46:31       at DriverHelper.<anonymous> (/home/e2e/dist/utils/DriverHelper.js:82:54)
11:46:31       at Generator.next (<anonymous>)
11:46:31       at /home/e2e/dist/utils/DriverHelper.js:19:71
11:46:31       at new Promise (<anonymous>)
11:46:31       at __awaiter (/home/e2e/dist/utils/DriverHelper.js:15:12)
11:46:31       at DriverHelper.waitVisibility (/home/e2e/dist/utils/DriverHelper.js:78:16)
11:46:31       at Ide.<anonymous> (/home/e2e/dist/pageobjects/ide/Ide.js:59:37)
11:46:31       at Generator.next (<anonymous>)
11:46:31       at /home/e2e/dist/pageobjects/ide/Ide.js:19:71
11:46:31       at new Promise (<anonymous>)
11:46:31       at __awaiter (/home/e2e/dist/pageobjects/ide/Ide.js:15:12)
11:46:31       at Ide.waitNotification (/home/e2e/dist/pageobjects/ide/Ide.js:57:16)
11:46:31       at Ide.<anonymous> (/home/e2e/dist/pageobjects/ide/Ide.js:70:24)
11:46:31       at Generator.next (<anonymous>)
11:46:31       at /home/e2e/dist/pageobjects/ide/Ide.js:19:71
11:46:31       at new Promise (<anonymous>)
11:46:31       at __awaiter (/home/e2e/dist/pageobjects/ide/Ide.js:15:12)
11:46:31       at Ide.waitNotificationAndOpenLink (/home/e2e/dist/pageobjects/ide/Ide.js:69:16)
11:46:31       at Object.<anonymous> (/home/e2e/dist/tests/e2e_happy_path/HappyPath.spec.js:187:19)
11:46:31       at Generator.next (<anonymous>)
11:46:31       at fulfilled (/home/e2e/dist/tests/e2e_happy_path/HappyPath.spec.js:13:58)
11:46:31       at <anonymous>
11:46:31       at process._tickCallback (internal/process/next_tick.js:188:7)
```

Example of failed build: https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-mini/406/console

Sadly, no screenshot was archived (I don't know why)

**Comment by SkorikSergey** [comment]
HappyPath sometimes test fails when trying to click on ```yes``` button of "```A new process is now listening on port 8080 but this port is not exposed in the workspace as a server. Would you want to add a redirect for this port so it becomes available```" notification(see screenshot). 
After clicking the notification is still visible but other notification for open application link should appears.

![Selection_239](https://user-images.githubusercontent.com/7760565/61699969-8c9d2100-ad44-11e9-871a-db1c8f1534c5.png)

**Comment by Ohrimenko1988** [comment]
Related problem https://github.com/eclipse/che/issues/14121

**Comment by rhopp** [comment]
We haven't seen this issue in some time. Closing now - feel free to reopen, if it happens again.
