### ISSUE TITLE
Running "chectl server:start" on Centos machine returns "Error: Cannot find module '/usr/local/bin/chectl/lib/commands/server/start'"

### ISSUE THREAD

**Issue by bryantson** [eclipse-che/che#13872]
I downloaded "chectl-v0.0.2-68f8872-linux-x64.tar.gz", untarred it, and move to the PATH. Running the following command:

```chectl server:start```

returns the following error:
```
Error: Cannot find module '/usr/local/bin/chectl/lib/commands/server/start'
    at fetch (/usr/local/bin/chectl/node_modules/@oclif/config/lib/plugin.js:97:31)
    at Plugin.findCommand (/usr/local/bin/chectl/node_modules/@oclif/config/lib/plugin.js:115:21)
    at Object.load (/usr/local/bin/chectl/node_modules/@oclif/config/lib/plugin.js:48:72)
    at Config.runCommand (/usr/local/bin/chectl/node_modules/@oclif/config/lib/config.js:149:27)
    at Main.run (/usr/local/bin/chectl/node_modules/@oclif/command/lib/main.js:21:27)
    at Main._run (/usr/local/bin/chectl/node_modules/@oclif/command/lib/command.js:44:31)
```
However, the chectl directory does not contain any "lib" folder but only node_modules, templates, bin, and other executable and script ifles.

**Comment by benoitf** [comment]
ok, for now use as workaround the chectl-linux binary from releases page

**Comment by slemeur** [comment]
As there is a workaround, I labelling it as 7.1.0 issue
