### ISSUE TITLE
Cannot deploy Che on minishift using operator

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#13881]
### Describe the bug
It's impossible to me to deploy Che on `minishift` using operator

The first I start `minishift` with 4cpus, 10GB RAM and 20GB disk space
```
minishift start --memory=10GB --cpus=4 --disk-size=20GB
```

Then I downloaded the latest version of chectl and tried to deploy Che using operator
```
./chectl-linux server:start --platform=minishift --installer=operator
```
Chectl failed with the following error
```
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ ./chectl-linux server:start --platform=minishift --installer=operator
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
    ✔ Retrieving minishift IP and domain for routes URLs...192.168.99.100.nip.io.
  ❯ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...done.
    ✔ Create ServiceAccount che-operator in namespace che...done.
    ✖ Create Role che-operator in namespace che
      → ERROR: It looks like you don't have enough privileges. You need to grant more privileges to current user or use a different user. If you are using minishift you can "oc login -u system:admin"
      Create RoleBinding che-operator in namespace che
      Create CRD checlusters.org.eclipse.che
      Waiting 5 seconds for the new Kubernetes resources to get flushed
      Create deployment che-operator in namespace che
      Create Che Cluster eclipse-che in namespace che
 ›   Error: ERROR: It looks like you don't have enough privileges. You need to grant more privileges to current user or use a different user. If you are using minishift you can "oc login -u system:admin"
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ 
```

I want to pay attention that the latest version of chectl (20190716105045) does not deploy Che using helm
```
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ ./chectl-linux server:start --platform=minishift
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
    ✔ Retrieving minishift IP and domain for routes URLs...192.168.99.100.nip.io.
  ✔ 🏃‍  Running the Che minishift-addon
    ✔ Check minishift version...done.
    ✔ Check logged...done.
    ✔ Check che addon is available...done.
    ✔ Apply Che addon...done.
  ❯ ✅  Post installation checklist
    ❯ Che pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:107:62)
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ 
```

Actually it's not clear the problem with chectl or with minishift.
The last time when I was able to deploy Che I used minishift 1.34.0 and chectl release 20190712093149

**Comment by benoitf** [comment]
for minishift you've to do what is said in the error message 

```
✖ Create Role che-operator in namespace che
      → ERROR: It looks like you don't have enough privileges. You need to grant more privileges to current user or use a different user. If you are using minishift you can "oc login -u system:admin"
```

so do
`oc login -u system:admin`

and restart chectl command with operator

**Comment by vitaliy-guliy** [comment]
The first case is working fine when I do `oc login -u system:admin` 
I suppose when the parameter `--installer=operator` is specified, the chectl should login to os automatically.

**Comment by benoitf** [comment]
@vitaliy-guliy the cli is assuming you're correctly logged on all platforms

**Comment by vitaliy-guliy** [comment]
@benoitf this is not mentioned in the chectl documentation and at the first glance it looks like a bug.

**Comment by tsmaeder** [comment]
Can we fix the doc, please? Takes 2 minutes for someone who is familiar with the code.

**Comment by vitaliy-guliy** [comment]
I still have strange output when deploying Che on minishift using helm, but Che become working

```
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ ./chectl-linux server:start --platform=minishift
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
    ✔ Retrieving minishift IP and domain for routes URLs...192.168.99.100.nip.io.
  ✔ 🏃‍  Running the Che minishift-addon
    ✔ Check minishift version...done.
    ✔ Check logged...done.
    ✔ Check che addon is available...done.
    ✔ Apply Che addon...done.
  ❯ ✅  Post installation checklist
    ❯ Che pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:107:62)
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ 
```

**Comment by benoitf** [comment]
@vitaliy-guliy in that case there is a bug, chectl should report an error that minishift/helm is not possible

@tsmaeder AFAIK it's a question issue, not a doc task so please create a new issue

**Comment by vitaliy-guliy** [comment]
Link with https://github.com/eclipse/che/issues/13928

**Comment by benoitf** [comment]
>> still have strange output when deploying Che on minishift using helm, but Che become working
```
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ ./chectl-linux server:start --platform=minishift
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
    ✔ Retrieving minishift IP and domain for routes URLs...192.168.99.100.nip.io.
  ✔ 🏃‍  Running the Che minishift-addon
    ✔ Check minishift version...done.
    ✔ Check logged...done.
    ✔ Check che addon is available...done.
    ✔ Apply Che addon...done.
  ❯ ✅  Post installation checklist
    ❯ Che pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:107:62)
vitaliy@vitaliy-ThinkPad-P50 ~/bin $ 

```


Hello, in fact in this case it didn't used helm but minishift addon.

We need to probably display the installer/platform used in traces

**Comment by vitaliy-guliy** [comment]
The same error for minikube

![Screenshot from 2019-07-22 09-51-44](https://user-images.githubusercontent.com/1655894/61615505-77ea5b80-ac66-11e9-8fec-8ae472a15e36.png)

**Comment by benoitf** [comment]
@vitaliy-guliy what is the `chectl` binary version that you're using ?

**Comment by benoitf** [comment]
@vitaliy-guliy could you download the latest ?

**Comment by vitaliy-guliy** [comment]
At friday I tested it on the latest `clectl`.

**Comment by vitaliy-guliy** [comment]
I checked twice using the latest `chectl`.

![Screenshot from 2019-07-22 14-09-40](https://user-images.githubusercontent.com/1655894/61631998-1806ab80-ac8c-11e9-8818-2a44e839db57.png)

**Comment by slemeur** [comment]
have you tried to cleanup before. like `chectl server:delete` ?

**Comment by vitaliy-guliy** [comment]
@slemeur yes. I deleted the whole machine.
```
minishift stop
minishift delete
minishift start --memory=10GB --cpus=4 --disk-size=20GB
./chectl-linux server:start --platform=minishift --installer=operator
```

**Comment by bryantson** [comment]
I encountered the same issue when TLS and self-signed cert options was used. The issue went away if I did it without:

`chectl server:start --platform=minishift --installer=operator 
`

**Comment by tolusha** [comment]
I don't think it is relevant anymore.
It is possible to deploy Che on minishift using operator.
