### ISSUE TITLE
"Your registry is invalid" when trying to change to "Visual Studio Code plugins"

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13904]
### Describe the bug

cannot use Visual Studio Code registry

in Che theia log:
```
root ERROR Request getPlugins failed with error: marketplacePlugins.map is not a function TypeError: marketplacePlugins.map is not a function
    at ChePluginServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:182:77)
    at step (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:41:23)
    at Object.next (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:22:53)
    at fulfilled (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:13:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root ERROR Request getPlugins failed with error: marketplacePlugins.map is not a function TypeError: marketplacePlugins.map is not a function
    at ChePluginServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:182:77)
    at step (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:41:23)
    at Object.next (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:22:53)
    at fulfilled (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:13:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

- start a workspace
- View -> Che plugins
- click on the 3 dots and Change registry
- Choose "Visual Studio Code plugins"
--> 
![image](https://user-images.githubusercontent.com/1105127/61462386-d9fb4600-a972-11e9-92c3-88ee505f6883.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl  `chectl server:start -a operator`
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
@apupier Che version?

**Comment by apupier** [comment]
> @apupier Che version?

Che-Theia@4ef1d89 using Theia@4ef1d89

**Comment by tsmaeder** [comment]
Treating this as 7.0 unless we don't care about this feature.

**Comment by vitaliy-guliy** [comment]
This registry was not working from the start and is added only for [demo](https://youtu.be/2_GPZb1_Hew?t=221). It demonstrated a way how we could connect to the vscode marketplace to get a list of available vscode extensions.
I will remove it, it's few lines of code.
Sorry guys for confusing.

**Comment by vitaliy-guliy** [comment]
Fixed
