### ISSUE TITLE
NPE in DisconnectRequestHandler.destroyDebugSession(DisconnectRequestHandler.java:28)

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13967]
### Describe the bug

I have an NPE in Language Support for Java Output log

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

Che-Theia@4ef1d89 using Theia@4ef1d89

### Steps to reproduce

don't know
was playing with a Springboot app, clicking Debug from the Application.java main method

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/1105127/61701875-22ce4880-ad3f-11e9-81ed-8eb22f0e4f5b.png)

### Installation method
   - [x] chectl  with -a operator
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

```
[Error - 9:34:31 AM] Jul 23, 2019 9:34:31 AM [error response][disconnect]: java.lang.NullPointerException
null
java.lang.NullPointerException
	at com.microsoft.java.debug.core.adapter.handler.DisconnectRequestHandler.destroyDebugSession(DisconnectRequestHandler.java:28)
	at com.microsoft.java.debug.core.adapter.handler.AbstractDisconnectRequestHandler.handle(AbstractDisconnectRequestHandler.java:42)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:84)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Error - 9:36:33 AM] Jul 23, 2019 9:36:33 AM [error response][disconnect]: java.lang.NullPointerException
null
java.lang.NullPointerException
	at com.microsoft.java.debug.core.adapter.handler.DisconnectRequestHandler.destroyDebugSession(DisconnectRequestHandler.java:28)
	at com.microsoft.java.debug.core.adapter.handler.AbstractDisconnectRequestHandler.handle(AbstractDisconnectRequestHandler.java:42)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:84)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Error - 9:37:35 AM] Error: The command 'editor.action.formatSelection' cannot be executed. There are no active handlers available for the command.
[Error - 9:38:02 AM] Jul 23, 2019 9:38:02 AM [error response][disconnect]: java.lang.NullPointerException
null
java.lang.NullPointerException
	at com.microsoft.java.debug.core.adapter.handler.DisconnectRequestHandler.destroyDebugSession(DisconnectRequestHandler.java:28)
	at com.microsoft.java.debug.core.adapter.handler.AbstractDisconnectRequestHandler.handle(AbstractDisconnectRequestHandler.java:42)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:84)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by apupier** [comment]
I think that it happens when clicking on the red square to stop debug inside the Debug View

**Comment by nickboldt** [comment]
Does this prevent you from doing anything, or is it just log clutter that should be cleaned up (error should be caught better) ?

**Comment by slemeur** [comment]
@tsmaeder : this lands into your team backlog, as something to try to reproduce. 
As the steps to reproduce the issue are unclear -> backlog of 7.x

**Comment by apupier** [comment]
> Does this prevent you from doing anything, or is it just log clutter that should be cleaned up (error should be caught better) ?

I detected no functional problem

**Comment by tsmaeder** [comment]
Need to analyze whether this is something that may happen (because timeout or something similar). If yes, write out a reasonable log message that makes clear this is nothing to worry about. If this is a problem, fix it or if too complicate defer for later implementation
