### ISSUE TITLE
che-theia/generator tests fail inside container without git user.name and user.email

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14056]
### Describe the bug
che-theia/generator tests fail in the env without git config user.name and user.email.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create workspace from devfile https://github.com/eclipse/che-theia/blob/master/devfiles/che-theia-all.devfile.yaml.
2. When factory complete cloning projects:
```shell
cd /projects/che-theia && yarn
```
3. che-theia build Fail, because che-theia generator tests:
<details>
  <summary>Che-theia generator tests output</summary>

```
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions7054oW6jJCimRwz4/che-theia/source-code1/folder2 to /tmp/tmpExtensions7054oW6jJCimRwz4/packages/@che-folder2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Skipping cloning sources for /tmp/tmpExtensions7054gE3LN0O7mL2M/source-code1 already provided...
@eclipse-che/theia-generator:   ● Test Extensions › test init sources generator
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › test init sources generator
@eclipse-che/theia-generator:     Unable to execute the command git clone file:///tmp/tmpExtensions7054NFJuv820m7w3/source-code2 source-code2: Error: Command failed: git clone file:///tmp/tmpExtensions7054NFJuv820m7w3/source-code2 source-code2
@eclipse-che/theia-generator:     Cloning into 'source-code2'...
@eclipse-che/theia-generator:     fatal: '/tmp/tmpExtensions7054NFJuv820m7w3/source-code2' does not appear to be a git repository
@eclipse-che/theia-generator:     fatal: Could not read from remote repository.
@eclipse-che/theia-generator:     Please make sure you have the correct access rights
@eclipse-che/theia-generator:     and the repository exists.
@eclipse-che/theia-generator:       at cp.exec (src/command.ts:887:32)
@eclipse-che/theia-generator:   ● Test Extensions › extension with empty dependencies
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › extensions with dev mode
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › extensions with dev mode
@eclipse-che/theia-generator:     Unable to execute the command git clone file:///tmp/tmpExtensions7054tQ7qV4H7iL5c/source-code2 source-code2: Error: Command failed: git clone file:///tmp/tmpExtensions7054tQ7qV4H7iL5c/source-code2 source-code2
@eclipse-che/theia-generator:     Cloning into 'source-code2'...
@eclipse-che/theia-generator:     fatal: '/tmp/tmpExtensions7054tQ7qV4H7iL5c/source-code2' does not appear to be a git repository
@eclipse-che/theia-generator:     fatal: Could not read from remote repository.
@eclipse-che/theia-generator:     Please make sure you have the correct access rights
@eclipse-che/theia-generator:     and the repository exists.
@eclipse-che/theia-generator:       at cp.exec (src/command.ts:887:32)
@eclipse-che/theia-generator:   ● Test Extensions › use provided extensions
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › use provided extensions
@eclipse-che/theia-generator:     Error
@eclipse-che/theia-generator:       Error: ENOENT: no such file or directory, ensureSymlink '/tmp/tmpExtensions7054GuMGSVH6dtjp/che-theia/source-code1/folder1'
@eclipse-che/theia-generator:   ● Test Extensions › use default extensions
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › use default extensions
@eclipse-che/theia-generator:     Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
@eclipse-che/theia-generator:       199 |     });
@eclipse-che/theia-generator:       200 | 
@eclipse-che/theia-generator:     > 201 |     test('use default extensions', async () => {
@eclipse-che/theia-generator:           |     ^
@eclipse-che/theia-generator:       202 |         const initSources = new InitSources(assemblyExamplePath, packagesFolderTmp, pluginsFolderTmp, cheTheiaFolderTmp, assemblyFolderTmp, THEIA_DUMMY_VERSION);
@eclipse-che/theia-generator:       203 |         await initSources.readConfigurationAndGenerate(undefined, false);
@eclipse-che/theia-generator:       204 |         expect(fs.readdirSync(packagesFolderTmp).length).toBeGreaterThan(0);
@eclipse-che/theia-generator:       at Spec (../node_modules/jest-cli/node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
@eclipse-che/theia-generator:       at Suite.Object.<anonymous>.describe (tests/init-sources/init-sources.spec.ts:201:5)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:22:1)
@eclipse-che/theia-generator:   ● Test Extensions › use provided extensions with dev mode
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › use provided extensions with dev mode
@eclipse-che/theia-generator:     Unable to execute the command git checkout -f master: Error: Command failed: git checkout -f master
@eclipse-che/theia-generator:     error: pathspec 'master' did not match any file(s) known to git
@eclipse-che/theia-generator:       at cp.exec (src/command.ts:887:32)
@eclipse-che/theia-generator:   ● Test Extensions › use default extensions with dev mode
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › throw error if path to configuration does not exist
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › default extension uri is unreachable
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › test command options
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › use extensions and plugins
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › use extensions and plugins
@eclipse-che/theia-generator:     Error
@eclipse-che/theia-generator:       Error: ENOENT: no such file or directory, ensureSymlink '/tmp/tmpExtensions7054oW6jJCimRwz4/che-theia/source-code1/folder1'
@eclipse-che/theia-generator:   ● Test Extensions › aliases replace with local source folder
@eclipse-che/theia-generator:     Unable to execute the command git clone https://github.com/eclipse/che-theia che-theia: Error: Command failed: git clone https://github.com/eclipse/che-theia che-theia
@eclipse-che/theia-generator:     Cloning into 'che-theia'...
@eclipse-che/theia-generator:     fatal: unable to open /tmp/tmpExtensions70540N7igdqp385O/che-theia/che-theia/.git/objects/pack/tmp_pack_iigwXe: No such file or directory
@eclipse-che/theia-generator:     fatal: index-pack failed
@eclipse-che/theia-generator:       at cp.exec (src/command.ts:887:32)
@eclipse-che/theia-generator:   ● Test Extensions › aliases replace with local source folder
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator:   ● Test Extensions › should skip clonning if source is an existing folder (and not a git uri to clone) and use it as the clonedDir
@eclipse-che/theia-generator:     Command failed: git commit -m "Init repo"
@eclipse-che/theia-generator:     *** Please tell me who you are.
@eclipse-che/theia-generator:     Run
@eclipse-che/theia-generator:       git config --global user.email "you@example.com"
@eclipse-che/theia-generator:       git config --global user.name "Your Name"
@eclipse-che/theia-generator:     to set your account's default identity.
@eclipse-che/theia-generator:     Omit --global to set the identity only in this repository.
@eclipse-che/theia-generator:     fatal: empty ident name (for <theia-dev@workspaceo2g9p082pdnt4ucd.workspace-78868dd45c-p5g8g>) not allowed
@eclipse-che/theia-generator:       67 |         cp.execSync('git init', { cwd: path });
@eclipse-che/theia-generator:       68 |         cp.execSync(`git add ${path}`, { cwd: path });
@eclipse-che/theia-generator:     > 69 |         cp.execSync(`git commit -m "Init repo"`, { cwd: path });
@eclipse-che/theia-generator:          |            ^
@eclipse-che/theia-generator:       70 | 
@eclipse-che/theia-generator:       71 |     }
@eclipse-che/theia-generator:       72 | 
@eclipse-che/theia-generator:       at initGit (tests/init-sources/init-sources.spec.ts:69:12)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:59:9)
@eclipse-che/theia-generator:       at fulfilled (tests/init-sources/init-sources.spec.ts:13:58)
@eclipse-che/theia-generator: ------------------------|----------|----------|----------|----------|-------------------|
@eclipse-che/theia-generator: File                    |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
@eclipse-che/theia-generator: ------------------------|----------|----------|----------|----------|-------------------|
@eclipse-che/theia-generator: All files               |    89.72 |    89.26 |    90.38 |    89.82 |                   |
@eclipse-che/theia-generator:  src                    |     87.5 |       80 |     87.8 |    87.63 |                   |
@eclipse-che/theia-generator:   cdn.ts                |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   clean.ts              |      100 |       75 |      100 |      100 |                46 |
@eclipse-che/theia-generator:   cli-error.ts          |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   command.ts            |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   index.ts              |        0 |      100 |      100 |        0 |             12,13 |
@eclipse-che/theia-generator:   init-sources.ts       |    64.66 |    53.33 |    64.29 |    65.35 |... 55,256,257,260 |
@eclipse-che/theia-generator:   init.ts               |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   logger.ts             |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   production.ts         |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   repository.ts         |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   yarn.ts               |      100 |    96.15 |      100 |      100 |               115 |
@eclipse-che/theia-generator:  src/cdn                |     95.8 |      100 |      100 |    95.68 |                   |
@eclipse-che/theia-generator:   base.ts               |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   bootstrap.ts          |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   html-template.ts      |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   webpack-customizer.ts |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   webpack-loader.ts     |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   webpack.config.ts     |        0 |      100 |      100 |        0 | 11,13,14,38,40,43 |
@eclipse-che/theia-generator: ------------------------|----------|----------|----------|----------|-------------------|
@eclipse-che/theia-generator: Test Suites: 1 failed, 14 passed, 15 total
@eclipse-che/theia-generator: Tests:       13 failed, 59 passed, 72 total
```

</details>

### Expected behavior
Build che-theia should be fine, all tests inside workspace container should be successfully passed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by slemeur** [comment]
Closing as this has been fixed on master: https://github.com/eclipse/che-theia/pull/382
