### ISSUE TITLE
Fix Happy path tests to run against Che with next version for default plugins.

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14248]
### Problem + solution
There is PR merged into the Che master to use next version for default plugins https://github.com/eclipse/che/pull/14247. 
Our Happy path tests should be aligned to the Theia next version https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/83/artifact/e2e/report/
![screenshot-Wait_workspace_running_state](https://user-images.githubusercontent.com/1197777/63093714-ee7d2f00-bf6e-11e9-9cea-175eacaeb997.png)
```
13:07:53   1) Validation of workspace start
13:07:53        Wait workspace running state:
13:07:53      TimeoutError: Waiting for element to be located By(xpath, (//ul[@class='p-TabBar-content']//li[@title='Explorer'])[1])
13:07:53 Wait timed out after 240003ms
13:07:53       at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
13:07:53       at ManagedPromise.invokeCallback_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
13:07:53       at TaskQueue.execute_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
13:07:53       at TaskQueue.executeNext_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
13:07:53       at asyncRun (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
13:07:53       at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
13:07:53       at <anonymous>
13:07:53       at process._tickCallback (internal/process/next_tick.js:188:7)
13:07:53   From: Task: Waiting for element to be located By(xpath, (//ul[@class='p-TabBar-content']//li[@title='Explorer'])[1])
13:07:53       at scheduleWait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
13:07:53       at ControlFlow.wait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
```

**Comment by musienko-maxim** [comment]
The last job was successful: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/200/
