### ISSUE TITLE
Internal server error when I try to add preferences for chePlugin component

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#14289]
### Describe the bug
Internal server error when I try to add preferences for chePlugin component

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Try to create a workspace from the devfile https://github.com/eclipse/che/issues/13698#issuecomment-518595214
2. Internal server error is observed

### Expected behavior
Devfile validation should pass

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2019-08-20 09-52-55](https://user-images.githubusercontent.com/1640675/63324224-4ed5ed00-c330-11e9-9bd6-b10ba723ed00.png)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
```

java.lang.RuntimeException: Unable to invoke no-args constructor for interface java.io.Serializable. Registering an InstanceCreator with Gson for this type may fix this problem.
--
  | at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
  | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
  | at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
  | at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
  | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:63)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
  | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
  | at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
  | at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
  | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:63)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
  | at com.google.gson.Gson.fromJson(Gson.java:927)
  | at com.google.gson.Gson.fromJson(Gson.java:865)
  | at org.eclipse.che.dto.server.DtoFactory.createDtoFromJson(DtoFactory.java:227)
  | at org.eclipse.che.dto.server.DtoFactory.createDtoFromJson(DtoFactory.java:240)
  | at org.eclipse.che.api.core.rest.CheJsonProvider.readFrom(CheJsonProvider.java:123)
  | at org.eclipse.che.api.core.rest.MessageBodyAdapterInterceptor.invoke(MessageBodyAdapterInterceptor.java:55)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.makeMethodParameters(DefaultMethodInvoker.java:113)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:58)
  | at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
  | at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
  | at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
  | at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
  | at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
  | at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
  | at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
  | at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
  | at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
  | at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:53)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:151)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:70)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:108)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
  | at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
  | at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:58)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
  | at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: java.io.Serializable
  | at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
  | at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
  | at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
  | ... 72 common frames omitted
```

**Comment by ibuziuk** [comment]
@mkuznyetsov I see there is already a Draft PR https://github.com/eclipse/che/pull/14306
Could you please assign the issue and set the correct milestone
