### ISSUE TITLE
chectl installation through operator throws "Cannot read property 'message' of undefined"

### ISSUE THREAD

**Issue by bryantson** [eclipse-che/che#14303]
Running the following installation command using chectl throws the error message:

`
chectl server:start -a operator -b some_openshift_domain -p openshift
`

**ERROR MESSAGE:**

[10:03:01] ✈️  Openshift preflight checklist [started]                                                                                                                        [10:03:01] Verify if oc is installed [started]                                                                                                                               [10:03:01] Verify if oc is installed...done. [title changed]                                                                                                                 [10:03:01] Verify if oc is installed...done. [completed]                                                                                                                     [10:03:01] Verify if openshift is running [started]                                                                                                                          [10:03:02] Verify if openshift is running...done. [title changed]                                                                                                            [10:03:02] Verify if openshift is running...done. [completed]                                                                                                                [10:03:02] ✈️  Openshift preflight checklist [completed]                                                                                                                      [10:03:02] 🏃‍  Running the Che Operator [started]                                                                                                                            [10:03:02] Copying operator resources [started]                                                                                                                              [10:03:02] Copying operator resources...done. [title changed]                                                                                                                [10:03:02] Copying operator resources...done. [completed]                                                                                                                    [10:03:02] Create Namespace (che) [started]                                                                                                                                  [10:03:03] Create Namespace (che)...done. [title changed]                                                                                                                    [10:03:03] Create Namespace (che)...done. [completed]                                                                                                                        [10:03:03] Create ServiceAccount che-operator in namespace che [started]                                                                                                     [10:03:03] Create ServiceAccount che-operator in namespace che [failed]                                                                                                      [10:03:03] → Cannot read property 'message' of undefined                                                                                                                     [10:03:03] 🏃‍  Running the Che Operator [failed]                                                                                                                             [10:03:03] → Cannot read property 'message' of undefined                                                                                                                     TypeError: Cannot read property 'message' of undefined                                                                                                                           at KubeHelper. (C:/Users/bson0/Tools/chectl/lib/api/kube.js:141:40)                                                                                               at Generator.throw ()                                                                                                                                             at rejected (C:/Users/bson0/Tools/chectl/node_modules/tslib/tslib.js:108:69)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/5396174/63443941-4f878580-c3fb-11e9-8760-0b958645cbc5.png)

### Installation method
   - [x ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [x ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

oc version prints out:
oc. v.3.11.129

Server is v3.11.82
openshift v3.11.82
kubernete: v1.11.0+d4cacc0

**Comment by sleshchenko** [comment]
For some reason, command that creates service account failed, maybe you don't have enough permissions. I've prepared a PR that would show the original error that happens https://github.com/che-incubator/chectl/pull/258

**Comment by sleshchenko** [comment]
@bryantson Are you able to do the same with the newest chectl https://github.com/che-incubator/chectl/releases/tag/20190822122043 ?

**Comment by ibuziuk** [comment]
@bryantson any updates? have you tried with the latest chectl version?
