### ISSUE TITLE
Github plugin installation fails

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#14319]
### Describe the bug

Github plugin installation fails, Git extension fails as well if the GitHub plugin is turned on. 
This happens because the GitHub plugin has vscode git extension in it's plugin dependencies. Since https://github.com/theia-ide/theia/commit/2d4c8457c09cc6ca37fc5480d14eb080a74ed85a was merged Theia automatically installs dependent plugins, but the vscode git extension is not located in the vscode marketplace. 
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a workspace with the GitHub plugin turned on.
**WRONG:** 
Git plugin doesn't work:
![screenshot-che-che 192 168 39 215 nip io-2019 08 23-10-07-48](https://user-images.githubusercontent.com/7668752/63573392-e08e6600-c58d-11e9-96a0-edb54f1553f5.png)
The error is shown in the log console:
```
root ERROR TypeError: Cannot read property 'versions' of undefined
    at Request._callback (/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:129:55)
    at Request.self.callback (/home/theia/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/theia/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/theia/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
root ERROR Uncaught Exception:  Error: No extension
root ERROR Error: No extension
    at Request._callback (/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:120:44)
    at Request.self.callback (/home/theia/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/theia/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/theia/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
https://github.com/theia-ide/theia/issues/5993

**Comment by ibuziuk** [comment]
@vinokurig removing `need-triage` label, please set a milestone based on the team priorities

**Comment by ibuziuk** [comment]
oh, looks like it is part of https://github.com/eclipse/che/issues/14295 - moving to `7.2.0`
