### ISSUE TITLE
Update screencatcher in the e2e folder for avoiding errors

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14384]
### Is your task related to a problem? Please describe.
When we test application with several windows the screencatcher throws errors when main window closed.
```
(node:114) UnhandledPromiseRejectionWarning: NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=76.0.3809.87)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '1730bb5a9bcd', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.0.16-100.fc28.x86_64', java.version: '1.8.0_222'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/tmp/e2e/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/tmp/e2e/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/tmp/e2e/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.takeScreenshot()
    at thenableWebDriverProxy.schedule (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at thenableWebDriverProxy.takeScreenshot (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:1085:17)
    at ScreenCatcher.<anonymous> (/tmp/e2e/utils/ScreenCatcher.ts:42:72)
    at Generator.next (<anonymous>)
    at /tmp/e2e/dist/utils/ScreenCatcher.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/e2e/dist/utils/ScreenCatcher.js:15:12)
    at ScreenCatcher.catchScreen (/tmp/e2e/dist/utils/ScreenCatcher.js:66:16)
    at ScreenCatcher.<anonymous> (/tmp/e2e/utils/ScreenCatcher.ts:38:20)
    at Generator.next (<anonymous>)
    at /tmp/e2e/dist/utils/ScreenCatcher.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/e2e/dist/utils/ScreenCatcher.js:15:12)
    at ScreenCatcher.catchMethodScreen (/tmp/e2e/dist/utils/ScreenCatcher.js:49:16)
    at Runner.<anonymous> (/tmp/e2e/driver/CheReporter.ts:77:29)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/e2e/dist/driver/CheReporter.js:4:58)
    at <anonymous>
(node:114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Describe the solution you'd like
Update screencatcher for avoiding this kind of problem when main window closed

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/14394
