### ISSUE TITLE
Keycloak is failing to start in Kubernetes

### ISSUE THREAD

**Issue by rguskov** [eclipse-che/che#14406]
Trying to start Che 6.19.0 in multi-user mode on Kubernetes cluster (not minikube). Keycloak pod is failing with the below error. The postgres pod is up. PVs and PV claims are all configured.
```
Configuring Keycloak by modifying realm and user templates...
Creating Admin user...
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
Starting Keycloak server...
User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'
-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.dir=/scripts/ -Djboss.bind.address=0.0.0.0
WARNING: POSTGRES_DATABASE variable name is DEPRECATED replace with DB_DATABASE
WARNING: POSTGRES_USER variable name is DEPRECATED replace with DB_USER
WARNING: POSTGRES_PASSWORD variable name is DEPRECATED replace with DB_PASSWORD

  Using PostgreSQL database


Cannot start embedded server: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE": java.lang.reflect.InvocationTargetException: /opt/jboss/keycloak/standalone/log/server.log (Permission denied)
Cannot start embedded server: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE": java.lang.reflect.InvocationTargetException: /opt/jboss/keycloak/standalone/log/server.log (Permission denied)

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/keycloak

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true 

Failed to read or configure the org.jboss.logmanager.LogManager
java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE"
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:117)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:336)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:289)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:298)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:170)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:132)
	at java.util.logging.LogManager$3.run(LogManager.java:399)
	at java.util.logging.LogManager$3.run(LogManager.java:396)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at org.jboss.modules.Main.main(Main.java:523)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:115)
	... 17 more
Caused by: java.io.FileNotFoundException: /opt/jboss/keycloak/standalone/log/server.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.jboss.logmanager.handlers.FileHandler.setFile(FileHandler.java:151)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setFile(PeriodicRotatingFileHandler.java:104)
	at org.jboss.logmanager.handlers.FileHandler.setFileName(FileHandler.java:189)
	at org.jboss.logmanager.handlers.FileHandler.<init>(FileHandler.java:119)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.<init>(PeriodicRotatingFileHandler.java:72)
	... 22 more
java.lang.IllegalStateException: WFLYSRV0126: Could not create server content directory: /opt/jboss/keycloak/standalone/data/content
	at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:491)
	at org.jboss.as.server.Main.determineEnvironment(Main.java:388)
	at org.jboss.as.server.Main.main(Main.java:96)
	at org.jboss.modules.Module.run(Module.java:352)
	at org.jboss.modules.Module.run(Module.java:320)
	at org.jboss.modules.Main.main(Main.java:593)
```

**Comment by l0rd** [comment]
@rguskov thank you for raising this issue. You are deploying version 6.19.0 of Che. Why not 7.0.0 that is the latest and greatest? And if you want to stick with 6.x why not 6.19.5?

I would recommend that you try first with one of those versions and then, if your problem persist, you should provide us more details to figure out what is happening:
- How are you installing Che? Provide the exact command.
- What is the version of Kubernetes that you are using? On prem or on a cloud provider?
- Provide the versions of the image of Postgres, Keycloak and other Che components that are pulled during Che deployment

**Comment by rguskov** [comment]
I started evaluating Che some time ago in Minikube so it was 6.19.0 at that time. Then tried it on a remote cluster and came up with that keycloak issue. 

Now followed your advice and tried 7.0.0. Failing to install. The cluster is not new. It is a preexisting one with all the service accounts and roles already configured. So might be the case something is missing here or not configured as expected by Che. But I'm not sure what exactly.

chectl server:start --platform=k8s --installer=helm --domain=${CHE_DOMAIN} --multiuser --tls
  ❯ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ✖ Verify remote kubernetes status
      → E_PLATFORM_NOT_READY: Error: serviceaccounts is forbidden: User "system:anonymous" cannot list serviceaccounts in the namespace "default"
      Verify domain is set
 ›   Error: E_PLATFORM_NOT_READY: Error: serviceaccounts is forbidden: User "system:anonymous" cannot list serviceaccounts in the namespace "default"

**Comment by rguskov** [comment]
I also tried 6.19.5 and it has the same issue as 6.19.0 on a remote Kubernetes cluster on AWS.

In the multi-az setup Keycloak may get PVCs in different zones. Che setup does not let specify the storage class as a parameter to force both PVCs be created in one availability zone. And fixing this issue with PVCs manually does not help. Keycloak keeps complaining on permissions.

**Comment by amisevsk** [comment]
@rguskov It looks like `kubectl` is not configured to talk to `minikube`.

**Comment by rguskov** [comment]
Hi,

Thank you for your help.

As I mentioned earlier it is a remote kubernetes cluster on AWS. Nothing to do with minikube.

I managed to deploy and start 7.1.0 in the cluster but workspaces fail to start regardless of the stack chosen. This is all the logs I'm seeing for the workspace pod:

Error from server (BadRequest): container "eclipse-che-unified-plugin-broker-v0-20" in pod "workspace439877h8dhwl1939.che-plugin-broker" is waiting to start: PodInitializing

Describing the workspace pod gives this:

Events:
  Type     Reason                  Age   From                                                        Message
  ----     ------                  ----  ----                                                        -------
  Normal   Scheduled               65s   default-scheduler                                           Successfully assigned train/workspace439877h8dhwl1939.che-plugin-broker to ip-XXX-XX-XXX-XXX.ap-southeast-2.compute.internal
  Warning  FailedAttachVolume      65s   attachdetach-controller                                     Multi-Attach error for volume "pvc-9955208f-d83e-11e9-8488-0a8a9e2972ea" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulAttachVolume  55s   attachdetach-controller                                     AttachVolume.Attach succeeded for volume "pvc-9955208f-d83e-11e9-8488-0a8a9e2972ea"
  Normal   Pulling                 48s   kubelet, ip-XXX-XX-XXX-XXX.ap-southeast-2.compute.internal  pulling image "eclipse/che-init-plugin-broker:v0.20"
  Normal   Pulled                  42s   kubelet, ip-XXX-XX-XXX-XXX.ap-southeast-2.compute.internal  Successfully pulled image "eclipse/che-init-plugin-broker:v0.20"
  Normal   Created                 42s   kubelet, ip-XXX-XX-XXX-XXX.ap-southeast-2.compute.internal  Created container
  Normal   Started                 42s   kubelet, ip-XXX-XX-XXX-XXX.ap-southeast-2.compute.internal  Started container

Anybody can tell me what it is waiting for and why the workspace is not starting? What other pod or container? Keycloak is up, devfile-registry is up, plugin-registry is up. After an obvious timeout the workspace pod is killed by kubernetes and not restored anymore unless refreshing the workspace page.

**Comment by rguskov** [comment]
Seems like I found the error itself. But I cannot explain why I am getting it. Any thoughts? 

2019/09/18 03:50:31 Broker configuration
2019/09/18 03:50:31   Push endpoint: ws://che-XXXXXXX/api/websocket
2019/09/18 03:50:31   Auth enabled: true
2019/09/18 03:50:31   Runtime ID:
2019/09/18 03:50:31     Workspace: workspace439877h8dhwl1939
2019/09/18 03:50:31     Environment: default
2019/09/18 03:50:31     OwnerId: 99382f62-cc1c-4225-987f-43399fdc9a36
2019/09/18 03:50:31 Couldn't connect to endpoint 'ws://che-XXXXXXX/api/websocket', due to error 'websocket: bad handshake'

**Comment by rguskov** [comment]
Closing this issue as the keycloak issue is now resolved and the last one is open as a separate issue https://github.com/eclipse/che/issues/14606
