### ISSUE TITLE
"Updating Helm Chart dependencies" steps not working when username contains space

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14461]
From chectl created by [apupier](https://github.com/apupier): che-incubator/chectl#95  

```
    × Updating Helm Chart dependencies
      → Error: could not find C:\Users\Aurelien: FindFirstFile C:\Users\Aurelien: The system cannot find the file speci
f…
      Deploying Che Helm Chart
Error: Command failed: C:/WINDOWS/system32/cmd.exe /q /s /c "helm dependencies update --skip-refresh C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che/"
Error: could not find C:/Users/Aurelien: FindFirstFile C:/Users/Aurelien: The system cannot find the file specified.
    at makeError (C:/snapshot/chectl/node_modules/execa/index.js:174:9)
    at module.exports.Promise.all.then.arr (C:/snapshot/chectl/node_modules/execa/index.js:278:16)
```

**Comment by benoitf** [comment]
I tried a few things without success.

I tried to simply enclose with " https://github.com/che-incubator/chectl/blob/e6a6b561db55e118c7fe660256d1c7e9929e2893/src/installers/helm.ts#L148

`await execa.shell(`helm dependencies update --skip-refresh "${destDir}"`, { timeout: execTimeout })`

unfortunately it doesn't work because the command is already enclosed with double-quotes

```
× Updating Helm Chart dependencies
      → Error: could not find C:\Users\Aurelien Pupier\AppData\Local\chectl\templates\kubernetes\helm\che": GetFileAttributesEx C:\Users\Aurelien Pupier\AppData\Local\chectl\templates\kubernetes\helm\che": T
h…
      Deploying Che Helm Chart
Error: Command failed: C:/WINDOWS/system32/cmd.exe /q /s /c "helm dependencies update --skip-refresh "C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che/""
Error: could not find C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che": GetFileAttributesEx C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che": The filename, directory name, or volume label syntax is incorrect.
    at makeError (C:/git/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (C:/git/chectl/node_modules/execa/index.js:278:16)
```

**Comment by benoitf** [comment]
also tried to ask for no interpretation of double-quotes directly with a ^ (as seems to be suggested here https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/ )

`await execa.shell(`helm dependencies update --skip-refresh ^"${destDir}^"`, { timeout: execTimeout })`

it doesn't work either

```
× Updating Helm Chart dependencies
      → Error: could not find C:\Users\Aurelien Pupier\AppData\Local\chectl\templates\kubernetes\helm\che": GetFileAttributesEx C:\Users\Aurelien Pupier\AppData\Local\chectl\templates\kubernetes\helm\che": The
f…
      Deploying Che Helm Chart
Error: Command failed: C:/WINDOWS/system32/cmd.exe /q /s /c "helm dependencies update --skip-refresh ^"C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che/^""
Error: could not find C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che": GetFileAttributesEx C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che": The filename, directory name, or volume label syntax is incorrect.
    at makeError (C:/git/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (C:/git/chectl/node_modules/execa/index.js:278:16)
```

**Comment by benoitf** [comment]
@apupier can you please try using `\"${destDir}\"` (using `\` to escape the quotes)?

**Comment by benoitf** [comment]
suspecting that the /s option provided by the execa dependency is ignoring the quotes.

```
/S    Strip " quote characters from command.
         If command starts with a quote, the first and last quote chars in command
         will be removed, whether /s is specified or not.
```

https://ss64.com/nt/cmd.html

**Comment by benoitf** [comment]
> @apupier can you please try using `\"${destDir}\"` (using `\` to escape the quotes)?

it seems to keep the last double-quote inside the path

```
    × Updating Helm Chart dependencies
      → Error: could not find C:\Users\Aurelien Pupier\AppData\Local\chectl\templates\kubernetes\helm\che": GetFileAttributesEx C:\Users\Aurelien Pupier\Ap
p…
      Deploying Che Helm Chart
Error: Command failed: C:/WINDOWS/system32/cmd.exe /q /s /c "helm dependencies update --skip-refresh "C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che/""
Error: could not find C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che": GetFileAttributesEx C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che": The filename, directory name, or volume label syntax is incorrect.
    at makeError (C:/git/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (C:/git/chectl/node_modules/execa/index.js:278:16)
```

**Comment by benoitf** [comment]
unbeliveable, it is goign to next step when using:

` await execa.shell(`helm dependencies update --skip-refresh\\"${destDir}`, { timeout: execTimeout })`

```
 √ Updating Helm Chart dependencies...done.
    × Deploying Che Helm Chart
      → Error: This command needs 2 arguments: release name, chart path
Error: Command failed: C:/WINDOWS/system32/cmd.exe /q /s /c "helm upgrade --install che --force --namespace che --set global.ingressDomain=192.168.1.27.nip.io --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace=che   C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che/"
Error: This command needs 2 arguments: release name, chart path
    at makeError (C:/git/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (C:/git/chectl/node_modules/execa/index.js:278:16)
```

(where I need to apply the same kind of fix)

**Comment by benoitf** [comment]
applying same fix (adding a single escaped double-quote before ${destdir} ) on line 165 for command to upgrade, lead to another kind of error:

```
    × Deploying Che Helm Chart
      → Error: configmaps is forbidden: User "system:serviceaccount:kube-system:tiller" cannot list resource "configmaps" in API group "" in the namespace 
"…
Error: Command failed: C:/WINDOWS/system32/cmd.exe /q /s /c "helm upgrade --install che --force --namespace che --set global.ingressDomain=192.168.1.27.nip.io --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace=che   "C:/Users/Aurelien Pupier/AppData/Local/chectl/templates/kubernetes/helm/che/"
Error: UPGRADE FAILED: configmaps is forbidden: User "system:serviceaccount:kube-system:tiller" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
UPGRADE FAILED
ROLLING BACK
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:tiller" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
    at makeError (C:/git/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (C:/git/chectl/node_modules/execa/index.js:278:16)
```
