### ISSUE TITLE
E2E Happy path test failed when build application

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14486]
### Describe the bug
There is Happy path test which validates workspace build and run. It failed on waiting of `[INFO] BUILD SUCCESS` in build output. Build didn't start because there was additional popup appeared on screen after the task `che: build-file-output` had entered:
![screenshot-Build_application_2019-09-09](https://user-images.githubusercontent.com/1197777/64526958-5f64fc00-d30d-11e9-98f5-5dacf9b519e4.png)

<details>
 <summary>Happy path tests log</summary>
 <pre>
################## Launch Information ##################

      TS_SELENIUM_BASE_URL: http://che-che.10.0.151.28.nip.io
      TS_SELENIUM_HEADLESS: true

      TS_SELENIUM_DEFAULT_ATTEMPTS: 5
      TS_SELENIUM_DEFAULT_POLLING: 1000
      TS_SELENIUM_DEFAULT_TIMEOUT: 300000

      TS_SELENIUM_LANGUAGE_SERVER_START_TIMEOUT: 180000
      TS_SELENIUM_LOAD_PAGE_TIMEOUT: 240000
      TS_SELENIUM_START_WORKSPACE_TIMEOUT: 240000
      TS_SELENIUM_WORKSPACE_STATUS_ATTEMPTS: 90
      TS_SELENIUM_WORKSPACE_STATUS_POLLING: 20000
      TS_SELENIUM_PLUGIN_PRECENCE_ATTEMPTS: 20
      TS_SELENIUM_PLUGIN_PRECENCE_POLLING: 2000
      TS_SELENIUM_HAPPY_PATH_WORKSPACE_NAME: petclinic-dev-environment
      TS_SELENIUM_USERNAME: che
      TS_SELENIUM_PASSWORD: 
      TS_SELENIUM_DELAY_BETWEEN_SCREENSHOTS: 1000
      TS_SELENIUM_REPORT_FOLDER: ./report
      TS_SELENIUM_EXECUTION_SCREENCAST: true
      DELETE_SCREENCAST_IF_TEST_PASS: true
      TS_SELENIUM_REMOTE_DRIVER_URL: 

########################################################
      

  Validation of workspace start
(node:100) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    ✓ Open workspace (768ms)
    ✓ Wait workspace running state (103473ms)
    ✓ Wait until project is imported (14463ms)

  Language server validation
    ✓ Java LS initialization (140616ms)
    ✓ Error highlighting (5526ms)
    ✓ Autocomplete (4684ms)
    ✓ Suggestion (5040ms)
    ✓ Codenavigation (6075ms)
    - Yaml LS initialization

  Validation of workspace build and run
    1) Build application

  8 passing (10m)
  1 pending
  1 failing

  1) Validation of workspace build and run
       Build application:
     TimeoutError: Waiting for element to be located By(css selector, div[id='/projects/petclinic:/projects/petclinic/build-output.txt'])
Wait timed out after 300009ms
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /home/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: Waiting for element to be located By(css selector, div[id='/projects/petclinic:/projects/petclinic/build-output.txt'])
      at scheduleWait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/home/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/home/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at DriverHelper.<anonymous> (/home/e2e/utils/DriverHelper.ts:84:62)
      at Generator.next (<anonymous>)
      at /home/e2e/dist/utils/DriverHelper.js:19:71
      at new Promise (<anonymous>)
      at __awaiter (/home/e2e/dist/utils/DriverHelper.js:15:12)
      at DriverHelper.waitVisibility (/home/e2e/dist/utils/DriverHelper.js:78:16)
      at DriverHelper.<anonymous> (/home/e2e/utils/DriverHelper.ts:185:52)
      at Generator.next (<anonymous>)
      at /home/e2e/dist/utils/DriverHelper.js:19:71
      at new Promise (<anonymous>)
      at __awaiter (/home/e2e/dist/utils/DriverHelper.js:15:12)
      at DriverHelper.waitAndClick (/home/e2e/dist/utils/DriverHelper.js:171:16)
      at ProjectTree.<anonymous> (/home/e2e/pageobjects/ide/ProjectTree.ts:79:33)
      at Generator.next (<anonymous>)
      at fulfilled (/home/e2e/dist/pageobjects/ide/ProjectTree.js:16:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 </pre>
</details>

Build details: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/90/

Screencast: https://youtu.be/lPz_Gg2PpJU

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### E2E happy path tests
from https://github.com/eclipse/che master

### Che-Theia version
from https://github.com/eclipse/che-theia master

### Steps to reproduce
https://github.com/eclipse/che/blob/master/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] CRW CI

**Comment by rhopp** [comment]
Cause: https://github.com/theia-ide/theia/pull/5877 -> We need to adapt to this in our tests.

**Comment by l0rd** [comment]
Yes I agree with @rhopp here: this looks like an enhancement. We should adapt tests.

**Comment by rhopp** [comment]
Assigning Maxim, as he is already working on this. What's the status & estimate, @musienko-maxim ?
