### ISSUE TITLE
[che-theia] test failures in eclipse-che/theia-generator

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14566]
### Describe the bug

Since Sept 11, I can no longer build che-theia in Jenkins (CRW CI).

Today, I cleaned my git checkout of che-theia, updated to master, and the build failed locally too.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify: commit sha b437664 from https://github.com/eclipse/che-theia/tree/b437664ef3bfc6606778754d757179ca6cab8e6e

### Steps to reproduce

Do this:
```
$➔ yarn --version && npm --version
1.16.0
6.11.1

$ git clone https://github.com/eclipse/che-theia && cd che-theia && ./build.sh
```

### Expected behavior

A clean build, no failing tests or compilation failures

### Environment
   - [x ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x ] other (please specify) - build from https://github.com/redhat-developer/codeready-workspaces/blob/master/theia/Jenkinsfile 
   - [ ] other: please specify

### Additional context

Partial local build log:

```
@eclipse-che/theia-generator: FAIL tests/init-sources/init-sources.spec.ts (29.476s)
@eclipse-che/theia-generator:   ● Console
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242U4DkYhWF36Rj/source-code1...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242U4DkYhWF36Rj/source-code2...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242U4DkYhWF36Rj/che-theia/source-code1/folder1 to /tmp/tmpExtensions18242U4DkYhWF36Rj/packages/@che-folder1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242U4DkYhWF36Rj/che-theia/source-code1/folder2 to /tmp/tmpExtensions18242U4DkYhWF36Rj/packages/@che-folder2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242U4DkYhWF36Rj/che-theia/source-code2 to /tmp/tmpExtensions18242U4DkYhWF36Rj/packages/@che-source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242U4DkYhWF36Rj/che-theia/source-code1 to /tmp/tmpExtensions18242U4DkYhWF36Rj/plugins/source-code1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242U4DkYhWF36Rj/che-theia/source-code2 to /tmp/tmpExtensions18242U4DkYhWF36Rj/plugins/source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242lpiKthODiFDo/source-code1...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242lpiKthODiFDo/source-code2...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242lpiKthODiFDo/che-theia/source-code1/folder1 to /tmp/tmpExtensions18242lpiKthODiFDo/packages/@che-folder1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242lpiKthODiFDo/che-theia/source-code1/folder2 to /tmp/tmpExtensions18242lpiKthODiFDo/packages/@che-folder2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242lpiKthODiFDo/che-theia/source-code1 to /tmp/tmpExtensions18242lpiKthODiFDo/plugins/source-code1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242lpiKthODiFDo/che-theia/source-code2 to /tmp/tmpExtensions18242lpiKthODiFDo/packages/@che-source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242lpiKthODiFDo/che-theia/source-code2 to /tmp/tmpExtensions18242lpiKthODiFDo/plugins/source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions182425IJszoE3xCLg/source-code1...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions182425IJszoE3xCLg/source-code2...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions182425IJszoE3xCLg/che-theia/source-code1/folder1 to /tmp/tmpExtensions182425IJszoE3xCLg/packages/@che-folder1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions182425IJszoE3xCLg/che-theia/source-code1/folder2 to /tmp/tmpExtensions182425IJszoE3xCLg/packages/@che-folder2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions182425IJszoE3xCLg/che-theia/source-code1 to /tmp/tmpExtensions182425IJszoE3xCLg/plugins/source-code1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions182425IJszoE3xCLg/che-theia/source-code2 to /tmp/tmpExtensions182425IJszoE3xCLg/packages/@che-source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions182425IJszoE3xCLg/che-theia/source-code2 to /tmp/tmpExtensions182425IJszoE3xCLg/plugins/source-code2
@eclipse-che/theia-generator:     console.log src/logger.ts:184
@eclipse-che/theia-generator:       Config wasn't provided, downloading default...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning https://github.com/eclipse/che-theia...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242kspYj9dHTkrb/source-code1...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242kspYj9dHTkrb/source-code2...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242kspYj9dHTkrb/che-theia/source-code1/folder1 to /tmp/tmpExtensions18242kspYj9dHTkrb/packages/@che-folder1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242kspYj9dHTkrb/che-theia/source-code1/folder2 to /tmp/tmpExtensions18242kspYj9dHTkrb/packages/@che-folder2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242kspYj9dHTkrb/che-theia/source-code2 to /tmp/tmpExtensions18242kspYj9dHTkrb/packages/@che-source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242kspYj9dHTkrb/che-theia/source-code1 to /tmp/tmpExtensions18242kspYj9dHTkrb/plugins/source-code1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242kspYj9dHTkrb/che-theia/source-code2 to /tmp/tmpExtensions18242kspYj9dHTkrb/plugins/source-code2
@eclipse-che/theia-generator:     console.log src/logger.ts:184
@eclipse-che/theia-generator:       Config wasn't provided, downloading default...
@eclipse-che/theia-generator:     console.log src/logger.ts:184
@eclipse-che/theia-generator:       Config wasn't provided, downloading default...
@eclipse-che/theia-generator:     console.error ../node_modules/jsdom/lib/jsdom/virtual-console.js:29
@eclipse-che/theia-generator:       Error: Error: getaddrinfo ENOTFOUND foobarfoo.com foobarfoo.com:443
@eclipse-che/theia-generator:           at Object.dispatchError (/home/nboldt/5-Che/0.github_upstream/che-theia/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
@eclipse-che/theia-generator:           at Request.client.on.err (/home/nboldt/5-Che/0.github_upstream/che-theia/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
@eclipse-che/theia-generator:           at Request.emit (events.js:194:15)
@eclipse-che/theia-generator:           at Request.onRequestError (/home/nboldt/5-Che/0.github_upstream/che-theia/node_modules/request/request.js:881:8)
@eclipse-che/theia-generator:           at ClientRequest.emit (events.js:189:13)
@eclipse-che/theia-generator:           at TLSSocket.socketErrorListener (_http_client.js:392:9)
@eclipse-che/theia-generator:           at TLSSocket.emit (events.js:189:13)
@eclipse-che/theia-generator:           at emitErrorNT (internal/streams/destroy.js:82:8)
@eclipse-che/theia-generator:           at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
@eclipse-che/theia-generator:           at process._tickCallback (internal/process/next_tick.js:63:19) undefined
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242CMfJCd3XrSjG/source-code1...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Cloning file:///tmp/tmpExtensions18242CMfJCd3XrSjG/source-code2...
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242CMfJCd3XrSjG/che-theia/source-code1/folder1 to /tmp/tmpExtensions18242CMfJCd3XrSjG/packages/@che-folder1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242CMfJCd3XrSjG/che-theia/source-code1/folder2 to /tmp/tmpExtensions18242CMfJCd3XrSjG/packages/@che-folder2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242CMfJCd3XrSjG/che-theia/source-code1/plugin-folder1 to /tmp/tmpExtensions18242CMfJCd3XrSjG/plugins/plugin-folder1
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242CMfJCd3XrSjG/che-theia/source-code1/plugin-folder2 to /tmp/tmpExtensions18242CMfJCd3XrSjG/plugins/plugin-folder2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242CMfJCd3XrSjG/che-theia/source-code2 to /tmp/tmpExtensions18242CMfJCd3XrSjG/packages/@che-source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Creating symlink from /tmp/tmpExtensions18242CMfJCd3XrSjG/che-theia/source-code2 to /tmp/tmpExtensions18242CMfJCd3XrSjG/plugins/source-code2
@eclipse-che/theia-generator:     console.info src/logger.ts:190
@eclipse-che/theia-generator:       Skipping cloning sources for /tmp/tmpExtensions18242oKBqfabFr9Fb/source-code1 already provided...
@eclipse-che/theia-generator:   ● Test Extensions › use default extensions
@eclipse-che/theia-generator:     Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
@eclipse-che/theia-generator:       201 |     });
@eclipse-che/theia-generator:       202 | 
@eclipse-che/theia-generator:     > 203 |     test('use default extensions', async () => {
@eclipse-che/theia-generator:           |     ^
@eclipse-che/theia-generator:       204 |         const initSources = new InitSources(assemblyExamplePath, packagesFolderTmp, pluginsFolderTmp, cheTheiaFolderTmp, assemblyFolderTmp, THEIA_DUMMY_VERSION);
@eclipse-che/theia-generator:       205 |         await initSources.readConfigurationAndGenerate(undefined, false);
@eclipse-che/theia-generator:       206 |         expect(fs.readdirSync(packagesFolderTmp).length).toBeGreaterThan(0);
@eclipse-che/theia-generator:       at Spec (../node_modules/jest-cli/node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
@eclipse-che/theia-generator:       at Suite.Object.<anonymous>.describe (tests/init-sources/init-sources.spec.ts:203:5)
@eclipse-che/theia-generator:       at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:22:1)
@eclipse-che/theia-generator:   ● Test Extensions › use provided extensions with dev mode
@eclipse-che/theia-generator:     Unable to execute the command git checkout -f master: Error: spawn /bin/sh ENOENT
@eclipse-che/theia-generator:       at cp.exec (src/command.ts:887:32)
@eclipse-che/theia-dashboard-extension: yarn run v1.16.0
@eclipse-che/theia-dashboard-extension: $ yarn clean && yarn build
task-plugin: Packaging of plugin
task-plugin: 🔍 Validating...✔️ 
@eclipse-che/theia-dashboard-extension: $ rimraf lib
@eclipse-che/theia-dashboard-extension: $ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile"
@eclipse-che/theia-generator: ------------------------|----------|----------|----------|----------|-------------------|
@eclipse-che/theia-generator: File                    |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
@eclipse-che/theia-generator: ------------------------|----------|----------|----------|----------|-------------------|
@eclipse-che/theia-generator: All files               |    98.13 |    96.64 |      100 |    98.04 |                   |
@eclipse-che/theia-generator:  src                    |    98.98 |    93.75 |      100 |    98.92 |                   |
@eclipse-che/theia-generator:   cdn.ts                |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   clean.ts              |      100 |       75 |      100 |      100 |                46 |
@eclipse-che/theia-generator:   cli-error.ts          |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   command.ts            |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   index.ts              |        0 |      100 |      100 |        0 |             12,13 |
@eclipse-che/theia-generator:   init-sources.ts       |     98.5 |       90 |      100 |    98.43 |           106,107 |
@eclipse-che/theia-generator:   init.ts               |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   logger.ts             |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   production.ts         |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   repository.ts         |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   yarn.ts               |      100 |    96.15 |      100 |      100 |               115 |
@eclipse-che/theia-generator:  src/cdn                |     95.8 |      100 |      100 |    95.68 |                   |
@eclipse-che/theia-generator:   base.ts               |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   bootstrap.ts          |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   html-template.ts      |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   webpack-customizer.ts |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   webpack-loader.ts     |      100 |      100 |      100 |      100 |                   |
@eclipse-che/theia-generator:   webpack.config.ts     |        0 |      100 |      100 |        0 | 11,13,14,38,40,43 |
@eclipse-che/theia-generator: ------------------------|----------|----------|----------|----------|-------------------|
@eclipse-che/theia-generator: Test Suites: 1 failed, 14 passed, 15 total
@eclipse-che/theia-generator: Tests:       2 failed, 70 passed, 72 total
@eclipse-che/theia-generator: Snapshots:   0 total
@eclipse-che/theia-generator: Time:        39.783s, estimated 49s
@eclipse-che/theia-generator: Ran all test suites.
@eclipse-che/theia-generator: error Command failed with exit code 1.
@eclipse-che/theia-generator: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@eclipse-che/theia-generator: error Command failed with exit code 1.
@eclipse-che/theia-generator: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@eclipse-che/theia-generator: error Command failed with exit code 1.
@eclipse-che/theia-generator: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prepare exited 1 in '@eclipse-che/theia-generator'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by nickboldt** [comment]
The Jenkins-based failure seems to be related to missing yarn/npm deps:

```
[4/4] Building fresh packages...
error /mnt/hudson_workspace/workspace/crw-theia_master/che-theia/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /mnt/hudson_workspace/workspace/crw-theia_master/che-theia/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
gyp ERR! stack     at TLSSocket.emit (events.js:189:13)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:633:8)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/mnt/hudson_workspace/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-10.15.3/bin/node" "/mnt/hudson_workspace/workspace/crw-theia_master/che-theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/hudson_workspace/workspace/crw-theia_master/che-theia/node_modules/nsfw
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
```

**Comment by dmytro-ndp** [comment]
This issue duplicates #14560

**Comment by nickboldt** [comment]
Yes, dupe.
