### ISSUE TITLE
Build of che-theia failed on the "Building fresh packages..." step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14560]
### Describe the bug
Build of che-theia failed on the "Building fresh packages..." step:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/128/console
```
[4/4] Building fresh packages...
error /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.9.0 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.9.0/node-v10.9.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1047:34)
gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:629:8)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/mnt/hudson_workspace/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-10.9.0/bin/node" "/mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/oniguruma
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Che-theia version
- from master branch

### Steps to reproduce
`build.sh --pr --skip-tests`

### Environment
CodereadyWorkspaces Central CI

**Comment by dmytro-ndp** [comment]
It might be a `nodejs-10.9.0` specific problem.
Will try to re-build with `nodejs-10.15.3`.

**Comment by dmytro-ndp** [comment]
It failed on `nodejs-10.15.3` as well:
```
[4/4] Building fresh packages...
error /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
gyp ERR! stack     at TLSSocket.emit (events.js:189:13)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:633:8)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/mnt/hudson_workspace/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-10.15.3/bin/node" "/mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/oniguruma
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by dmytro-ndp** [comment]
Build does work on Codenvy CI:
- https://ci.codenvycorp.com/job/che-theia-next/
So, something wrong with CRW CCI

**Comment by nickboldt** [comment]
I suspect this is a consequence of CRW-360 and https://issues.jboss.org/browse/CRW-344 not being fully implemented.

**Comment by dmytro-ndp** [comment]
@rhopp found out the reason of failure - private npm registry with actually forbidden ssl which we had started using on CRW Central CI few days ago.

**Comment by dmytro-ndp** [comment]
Temporary workaround:
```
rm ~/.npmrc
rm ~/.yarnrc
```

**Comment by dmytro-ndp** [comment]
So, solution is to set environment variable:
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
```
