### ISSUE TITLE
chectl: che 7 install on OpenShift fails if project already exists

### ISSUE THREAD

**Issue by sare** [eclipse-che/che#14581]
I tried to install che on OpenShift 3.11 according to the quick start documentation (https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-3-using-the-operator/) and ran into the issue, that the installation fails, if the project (in this case "che") already exists, the installation will fail.

```chectl server:start --platform=openshift --installer=operator --domain=apps.openshift --tls --self-signed-cert
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
  ❯ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✖ Create Namespace (che)
      → Error from server (AlreadyExists): project.project.openshift.io "che" already exists
      Create ServiceAccount che-operator in namespace che
      Create Role che-operator in namespace che
      Create ClusterRole che-operator
      Create RoleBinding che-operator in namespace che
      Create ClusterRoleBinding che-operator
      Create CRD checlusters.org.eclipse.che
      Waiting 5 seconds for the new Kubernetes resources to get flushed
      Create deployment che-operator in namespace che
      Create Che Cluster eclipse-che in namespace che
Error: Command failed: /bin/sh -c oc new-project che
Error from server (AlreadyExists): project.project.openshift.io "che" already exists
    at makeError (~/che7/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (~/che7/chectl/node_modules/execa/index.js:278:16)
```

However we are using self-signed-certificates and if I unterstand the chectl README correctly I have to preprovision the project with a secret called "self-signed-cert" which holds the CA, in order for the installation to succeed?

If I try to install che 7 without preprovisioning the project, it fails with "→ Error: unable to verify the first certificate"

```chectl server:start --platform=openshift --installer=operator --domain=apps.openshift --tls --self-signed-cert -n che
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
  ❯ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...done.
    ✖ Create ServiceAccount che-operator in namespace che
      → Error: unable to verify the first certificate
      Create Role che-operator in namespace che
      Create ClusterRole che-operator
      Create RoleBinding che-operator in namespace che
      Create ClusterRoleBinding che-operator
      Create CRD checlusters.org.eclipse.che
      Waiting 5 seconds for the new Kubernetes resources to get flushed
      Create deployment che-operator in namespace che
      Create Che Cluster eclipse-che in namespace che
Error: Error: unable to verify the first certificate
    at KubeHelper.wrapK8sClientError (~/che7/chectl/lib/api/kube.js:1155:20)
    at KubeHelper.<anonymous> (~/che7/chectl/lib/api/kube.js:138:28)
    at Generator.throw (<anonymous>)
    at rejected (~/che7/chectl/node_modules/tslib/tslib.js:108:69)
```

**Comment by sleshchenko** [comment]
Sounds like a bug.
