### ISSUE TITLE
Error while building Che-Theia docker image

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#14628]
### Describe the bug

Error occurs when executing `./build.sh --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=master --tag:next --branch:master --git-ref:refs\\/heads\\/master` in `/che-theia/dockerfiles/theia` directory:
```
{ Error: Command failed: yarn run prepare
error Command failed with exit code 1.
error Command failed with exit code 1.

$ yarn clean && yarn build
$ rimraf lib
$ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint:fix" "yarn compile"
[compile] $ tsc
[format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
[lint] $ tslint -c ../../configs/tslint.json --fix --project .
[format] yarn format exited with code 0
[lint] yarn lint:fix exited with code 0
[compile] src/node/plugin-remote-init.ts(214,52): error TS2339: Property 'stopContext' does not exist on type 'PluginHostRPC'.
[compile] error Command failed with exit code 2.
[compile] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[compile] yarn compile exited with code 2
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/home/theia-dev/theia-source-code/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '$ yarn clean && yarn build\n$ rimraf lib\n$ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint:fix" "yarn compile"\n[compile] $ tsc\n[format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json\n[lint] $ tslint -c ../../configs/tslint.json --fix --project .\n[format] yarn format exited with code 0\n[lint] yarn lint:fix exited with code 0\n[compile] src/node/plugin-remote-init.ts(214,52): error TS2339: Property \'stopContext\' does not exist on type \'PluginHostRPC\'.\n[compile] error Command failed with exit code 2.\n[compile] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n[compile] yarn compile exited with code 2\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr:
   'error Command failed with exit code 1.\nerror Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run prepare',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn' returned a non-zero code: 1
```
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
I would say a duplicate of https://github.com/eclipse/che/issues/14618

**Comment by vinokurig** [comment]
Closing as a duplicate
