### ISSUE TITLE
Error:  Failed to load plugins: Erro:request "getDeployedPluginIds' when a plugin is provided with a reference to meta.yaml file

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#14805]
### Describe the bug
when using a component referencing a meta.yaml file like

```
  - id: >-
      https://raw.githubusercontent.com/apupier/che-plugin-registry/camelk/v3/plugins/redhat/vscode-camelk/latest/meta.yaml
    memoryLimit: 1G
    type: chePlugin
```
During first load, there is no complaint. The pod log is fine:
```
Starting the deployer with the list of resolvers [ LocalDirectoryPluginDeployerResolver {},
  GithubPluginDeployerResolver { unpackedFolder: '/tmp/github-remote' },
  HttpPluginDeployerResolver { unpackedFolder: '/tmp/http-remote' },
  VsCodePluginDeployerResolver { vscodeExtensionsFolder: '/tmp/vscode-extension-marketplace' } ]
Theia Endpoint 22/pid listening on port 2506
Found the list of default plugins ID on env: undefined
Found the list of plugins ID on env: local-dir:///plugins/sidecars/redhat_vscode_camelk_latest
Found the list of default plugins ID from CLI: undefined
unzipping the VS Code extension 'redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix' to directory: /tmp/vscode-unpacked/redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix
unzipping the VS Code extension 'redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix' to directory: /tmp/vscode-unpacked/redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix
PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix
Resolving "redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix" as a VS Code extension...
Resolved "redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix" to a VS Code extension "vscode-camelk@0.0.9" with engines: { vscode: '^1.33.0' }
PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix
Resolving "redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix" as a VS Code extension...
Resolved "redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix" to a VS Code extension "vscode-kubernetes-tools@1.0.0" with engines: { vscode: '^1.31.0' }
unzipping the VS Code extension 'redhat_vscode_yaml.vsix' to directory: /tmp/vscode-unpacked/redhat_vscode_yaml.vsix
PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat_vscode_yaml.vsix
Resolving "vscode:extension/redhat.vscode-yaml" as a VS Code extension...
Resolved "vscode:extension/redhat.vscode-yaml" to a VS Code extension "vscode-yaml@0.5.3" with engines: { vscode: '^1.31.0' }
the accepted plugins are []
the acceptedFrontendPlugins plugins are []
the acceptedBackendPlugins plugins are [ PluginDeployerEntryImpl {
    originId: 'local-dir:///plugins/sidecars/redhat_vscode_camelk_latest',
    pluginId:
     'redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix',
    map: Map { 'package.json' => [Object] },
    changes:
     [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
    acceptedTypes: [ 1 ],
    currentPath:
     '/tmp/vscode-unpacked/redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix/extension',
    initPath:
     '/plugins/sidecars/redhat_vscode_camelk_latest/redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix',
    resolved: true,
    resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  PluginDeployerEntryImpl {
    originId: 'local-dir:///plugins/sidecars/redhat_vscode_camelk_latest',
    pluginId:
     'redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix',
    map: Map { 'package.json' => [Object] },
    changes:
     [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
    acceptedTypes: [ 1 ],
    currentPath:
     '/tmp/vscode-unpacked/redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix/extension',
    initPath:
     '/plugins/sidecars/redhat_vscode_camelk_latest/redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix',
    resolved: true,
    resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  PluginDeployerEntryImpl {
    originId: 'vscode:extension/redhat.vscode-yaml',
    pluginId: 'vscode:extension/redhat.vscode-yaml',
    map: Map { 'package.json' => [Object] },
    changes:
     [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
    acceptedTypes: [ 1 ],
    currentPath: '/tmp/vscode-unpacked/redhat_vscode_yaml.vsix/extension',
    initPath: '/tmp/vscode-extension-marketplace/redhat_vscode_yaml.vsix',
    resolved: true,
    resolvedByName: 'VsCodePluginDeployerResolver' } ]
local path to deploy on remote instance [ '/tmp/vscode-unpacked/redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix/extension',
  '/tmp/vscode-unpacked/redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix/extension',
  '/tmp/vscode-unpacked/redhat_vscode_yaml.vsix/extension' ]
Backend plug-in "vscode-camelk@0.0.9" from "/tmp/vscode-unpacked/redhat.vscode-camelk.latest.ejskikaxwe.vscode-camelk-0.0.9-86.vsix/extension/out/extension is now available"
Backend plug-in "vscode-kubernetes-tools@1.0.0" from "/tmp/vscode-unpacked/redhat.vscode-camelk.latest.elastnllsu.vscode-kubernetes-tools-1.0.0.vsix/extension/out/src/extension is now available"
Backend plug-in "vscode-yaml@0.5.3" from "/tmp/vscode-unpacked/redhat_vscode_yaml.vsix/extension/out/src/extension is now available"
```

if refreshing the page, there is an error in browser console log:

```
root ERROR Failed to load plugins: Error: Request 'getDeployedPluginIds' failed
    at Proxy.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.3f7e45e….js:1:1789599)
    at e.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.3f7e45e….js:1:2465936)
```

In combination of another issue forbidding to see Extension on first load but requiring a refresh as  indicated in [this comment](https://github.com/eclipse/che/issues/14748#issuecomment-539427275), it is making it unusable.

### Che version
 - latest

### Steps to reproduce

1. Add Workspace
2. Select "Apache Camel based on SpringBoot
3. Click "Create and proceed editing"
4. Go to DevFile
5. Add in components
```
  - id: >-
      https://raw.githubusercontent.com/apupier/che-plugin-registry/camelk/v3/plugins/redhat/vscode-camelk/latest/meta.yaml
    memoryLimit: 1G
    type: chePlugin
```
6. Open Workspace
7. wait...
8. hit refresh
9. Check browser console log

### Runtime

```
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [x] chectl 
chectl server:start -p minikube -a operator

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS

**Comment by l0rd** [comment]
@apupier when providing an external link to the `meta.yaml` you should use `reference` instead of `id `:

```yaml
  - reference: https://raw.githubusercontent.com/apupier/che-plugin-registry/camelk/v3/plugins/redhat/vscode-camelk/latest/meta.yaml
    memoryLimit: 1G
    type: chePlugin
```

Maybe the error is related to that?

**Comment by apupier** [comment]
I tried using "reference" instead of "id", I have the exact same behavior

**Comment by benoitf** [comment]
@apupier is that your che-theia image is using the same theia version than your sidecar image with theia endpoint image running inside ?

**Comment by apupier** [comment]
it was surely due to a mismatch of images.
The [Docker image used](https://hub.docker.com/r/apupier/che-remote-plugin-camelk-tooling) was build 9 days ago, just when the [new protocol was setup](https://github.com/eclipse/che-theia/commit/ea358e52754ab3c191f6c3d74807203c2db44836). I rebuilt the image and I don't reproduce.

Thanks for the help!
