### ISSUE TITLE
[Analyze] Inappropriate workplace start cancelation sequence

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14815]
### Is your task related to a problem? Please describe.
I've noticed in logs some strange reaction of che master on workspace start cancellation process.
```
October 8th 2019, 03:22:35.704 - Workspace 'osiotest-workspace-2/1570497755132' with id 'workspace42198jmp43fbijvj' created by user 'osiotest-workspace-2'
October 8th 2019, 03:22:45.716 - Starting workspace 'osiotest-workspace-2/1570497755132' with id 'workspace42198jmp43fbijvj' by user 'osiotest-workspace-2'
October 8th 2019, 03:27:47.296 - Failed to start Kubernetes runtime of workspace workspace42198jmp43fbijvj. Cause: Runtime start for identity 'workspace: workspace42198jmp43fbijvj, environment: default, ownerId: 528d0388-97de-4b3c-b4fb-3d010c54f14a' is interrupted
October 8th 2019, 03:27:47.341 - Workspace 'osiotest-workspace-2/1570497755132' with id 'workspace42198jmp43fbijvj' is stopping by user 'osiotest-workspace-2'
October 8th 2019, 03:27:49.116 - Workspace 'osiotest-workspace-2:1570497755132' with id 'workspace42198jmp43fbijvj' start interrupted
October 8th 2019, 03:27:49.136 - No workspace start time recorded for workspace workspace42198jmp43fbijvj  org.eclipse.che.api.metrics.WorkspaceStartTrackerMeterBinder
October 8th 2019, 03:27:54.260 - Workspace 'workspace42198jmp43fbijvj' removed by user 'osiotest-workspace-2'
October 8th 2019, 03:31:10.379 - Error occurred during fetching of runtime for stopping workspace with id 'workspace42198jmp43fbijvj' by user 'osiotest-workspace-2'.  WorkspaceSharedPool-1

   Error: No active runtime is found
    org.eclipse.che.api.workspace.server.WorkspaceRuntimes. - WorkspaceSharedPool-1
    org.eclipse.che.api.core.ServerException: No active runtime is found
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.getInternalRuntime(WorkspaceRuntimes.java:343)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:891)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

October 8th 2019, 03:31:10.388 - Failed to record workspace activity. Workspace: workspace42198jmp43fbijvj, status: STOPPED	 org.eclipse.che.api.workspace.activity.WorkspaceActivityManager

org.eclipse.che.api.core.ServerException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table "che_workspace_activity" violates foreign key constraint "ws_activity_workspace_id"
  Detail: Key (workspace_id)=(workspace42198jmp43fbijvj) is not present in table "workspace".
Error Code: 0
Call: INSERT INTO che_workspace_activity (workspace_id, created, expiration, last_running, last_starting, last_stopped, last_stopping, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	bind => [8 parameters bound]
Query: InsertObjectQuery(WorkspaceActivity{workspaceId='workspace42198jmp43fbijvj', created=null, lastStarting=null, lastRunning=null, lastStopping=null, lastStopped=1570498270381, expiration=null, status=STOPPED})
	at org.eclipse.che.api.workspace.activity.JpaWorkspaceActivityDao.doUpdate(JpaWorkspaceActivityDao.java:258)
	at org.eclipse.che.api.workspace.activity.JpaWorkspaceActivityDao.doUpdate(JpaWorkspaceActivityDao.java:226)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:64)
	at org.eclipse.che.api.workspace.activity.JpaWorkspaceActivityDao.setStatusChangeTime(JpaWorkspaceActivityDao.java:147)
	at org.eclipse.che.api.workspace.activity.WorkspaceActivityManager$UpdateStatusChangedTimestampSubscriber.onEvent(WorkspaceActivityManager.java:183)
	at org.eclipse.che.api.workspace.activity.WorkspaceActivityManager$UpdateStatusChangedTimestampSubscriber.onEvent(WorkspaceActivityManager.java:173)
	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:108)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.publishWorkspaceStatusEvent(WorkspaceRuntimes.java:722)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$700(WorkspaceRuntimes.java:102)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:933)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.core.db.jpa.IntegrityConstraintViolat
```
In this sequance actions at October 8th 2019, 03:27:49.136 and  October 8th 2019, 03:31:10.379, October 8th 2019, 03:31:10.388 - should not happen or should happen in a different way.

### Describe the solution you'd like
n/a

### Describe alternatives you've considered
n/a
### Additional context
Workspace found during jaeger traces analyzing(more then 200sec).

**Comment by skabashnyuk** [comment]
no longer reproduced.
