### ISSUE TITLE
[che-theia] remote plugins failed to run because of error "No matching bindings found for serviceIdentifier: Symbol(ILogger)"

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14918]
### Describe the bug
Remote plugins failed to run because of error:
```
Error while starting endpoint:  Error: No matching bindings found for serviceIdentifier: Symbol(ILogger)
    at _validateActiveBindingCount (/home/theia/node_modules/inversify/lib/planning/planner.js:62:23)
    at _getActiveBindings (/home/theia/node_modules/inversify/lib/planning/planner.js:48:5)
    at _createSubRequests (/home/theia/node_modules/inversify/lib/planning/planner.js:91:26)
    at /home/theia/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
    at /home/theia/node_modules/inversify/lib/planning/planner.js:114:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/theia/node_modules/inversify/lib/planning/planner.js:94:20)
    at Object.plan (/home/theia/node_modules/inversify/lib/planning/planner.js:136:9)
    at /home/theia/node_modules/inversify/lib/container/container.js:317:37
```

### Plugin containers logs
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/pre-release/job/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/22/artifact/logs-and-configs/workspace-logs/

### Devfile to create workspace
https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che/7.3.0/happy-path-workspace.yaml

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: 7.3.0.RC

### Che-theia / remote plugins version
7.3.0

### Steps to reproduce
https://github.com/eclipse/che/blob/master/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by dmytro-ndp** [comment]
There problem has been fixed after rebuild of che-theia images https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/pre-release/job/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/24/
