### ISSUE TITLE
Multi-user Mysql TCK fails on CI

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#14939]
### Describe the bug
On our CI servers, I've noticed a bug that I am not able to reproduce locally. Seems like we might be closing down the connections too soon during the TCK tests.

```
12:10:09 [ERROR] 1) Error injecting constructor, org.eclipse.che.core.db.schema.SchemaInitializationException:
12:10:09 [ERROR] Error restoring current schema to its original setting
12:10:09 [ERROR] ------------------------------------------------------
12:10:09 [ERROR] SQL State  : 08003
12:10:09 [ERROR] Error Code : 0
12:10:09 [ERROR] Message    : No operations allowed after connection closed.
12:10:09 [ERROR] 
12:10:09 [ERROR] at org.eclipse.che.core.db.DBInitializer.<init>(DBInitializer.java:63)
12:10:09 [ERROR] at MultiuserMySqlTckModule.configure(MultiuserMySqlTckModule.java:118) (via modules: org.eclipse.che.commons.test.tck.TckListener$CompoundModule -> MultiuserMySqlTckModule)
12:10:09 [ERROR] while locating org.eclipse.che.core.db.DBInitializer
12:10:09 [ERROR] 
12:10:09 [ERROR] 1 error
12:10:09 [ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
12:10:09 [ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
12:10:09 [ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
12:10:09 [ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
12:10:09 [ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
12:10:09 [ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
12:10:09 [ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
12:10:09 [ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
12:10:09 [ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
12:10:09 [ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
12:10:09 [ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
12:10:09 [ERROR] at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
12:10:09 [ERROR] at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
12:10:09 [ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:10:09 [ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12:10:09 [ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:10:09 [ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
12:10:09 [ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
12:10:09 [ERROR] at java.lang.Thread.run(Thread.java:745)
```

### Che version
 - [x] latest (7.4.0-SNAPSHOT)

### Steps to reproduce

Run Che serve build with the integration tests.

### Expected behavior
Integration tests pass

### Notes
This is intermittent and actually quite rare. I have no idea what the cause might be.

**Comment by ibuziuk** [comment]
@metlos what is the CI you are referring to and what are the TCK tests?

**Comment by metlos** [comment]
CI is our CI and TCK tests are tests within the che server that run a set of tests on multiple DBs.

**Comment by metlos** [comment]
Added a note to the description about the fact that this is a rare occurrence.

**Comment by skabashnyuk** [comment]
See more info in description https://github.com/eclipse/che/issues/15287#issue-527234529

**Comment by gazarenkov** [comment]
@metlos @skabashnyuk still actual or can be closed?

**Comment by skabashnyuk** [comment]
No longer relevant for devworkspaces.

**Comment by benoitf** [comment]
could you explain why it's not relevant for DevWorkspaces ?
AFAIk postgreSQL database is still there

**Comment by skabashnyuk** [comment]
It makes sense to remove it. not to fix it.
