### ISSUE TITLE
Workspace cannot start in airgap mode because the workspace container names are too long

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#14958]
### Describe the bug

When running in airgap mode, the che server uses the fully qualified image name for the containers running inside a workspace pod (e.g. `default-image-registry-openshift-image-registry.svc.cluster.local-myplugin`).  This goes over the 63 character limit imposed here https://github.com/eclipse/che/blob/e598e2279b4b35f9684b9f2540adc91bcd7885da/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Names.java#L32

When you add `cheLogLevel: DEBUG` to your `CheCluster` CR, you see these messages when trying to start a workspace:

```
2019-10-22 21:18:18,310[aceSharedPool-2]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 864]   - The container name exceeds the allowed limit of 63 characters.                                                                                      
org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: The container name exceeds the allowed limit of 63 characters.                                                                                                      
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:805)                                                                                                           at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:263)                                                                                                            at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)                                                                                                                                           
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:830)                                                                                                                            
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)                                                                                                                               
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)                                                                                                                                                   
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                                                            at java.lang.Thread.run(Thread.java:748)                                                                                                                                                                                              
Caused by: java.lang.IllegalArgumentException: The container name exceeds the allowed limit of 63 characters.                                                                                                                                         at org.eclipse.che.workspace.infrastructure.kubernetes.Names.machineName(Names.java:126)                                                                                                                                                      at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.BrokerEnvironmentFactory.createBrokerConfig(BrokerEnvironmentFactory.java:236)                                                                          
        at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.BrokerEnvironmentFactory.create(BrokerEnvironmentFactory.java:127)                                                                                      
        at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:106)                                                                                                                 at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:79)                                            
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:178)                                                                                                    
        ... 7 common frames omitted 
```                                                                            

I think the problem is maybe how the plugin-registry updates the image names in airgap mode, but I am not 100% sure (plugin-registry logs):
```
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/latest/meta.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to che
Checking meta /var/www/html/v3/plugins/redhat/vscode-wsdl2rest/0.0.9/meta.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to che
Checking meta /var/www/html/v3/plugins/redhat/vscode-wsdl2rest/latest/meta.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to che
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.3.0/meta.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to che
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.5.1/meta.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to che
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.7.0/meta.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to che
```

One way to work around this is to use a shorter registry URL/org combination, but that is not really tenable long-term.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.3.0

### Steps to reproduce

+ Create a new `CheCluster`
+ Add a `airGapContainerRegistryHostname` and `airGapContainerRegistryOrganization` that is > 63 characters.
+ Apply the CR 
+ After everything is deployed, try to start a workspace

### Expected behavior

The workspace should start normally using images from the airgap registry

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)

This should affect all deployments, as it is a che-server name limit

### Screenshots
![container name limit](https://user-images.githubusercontent.com/1291508/67335414-46915e00-f4e9-11e9-869c-bf11eef8be9d.png)

### Installation method
   - [ ] chectl 
   - [x] che-operator version 7.3.0
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer, but will affect all operator-based deployments
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by l0rd** [comment]
Not sure why we are using the registry details to generate the container name but that looks like a bug. Setting severity P1 as that may prevent Che usage completely for some customers.

**Comment by ibuziuk** [comment]
closing as done
