### ISSUE TITLE
Error: contexts[16].context.cluster is missing

### ISSUE THREAD

**Issue by LouisKottmann** [eclipse-che/che#14968]
### Describe the bug

When running ```chectl server:start --installer=helm --platform=k8s --tls --domain=code.mydomain.com --multiuser``` with a proper kubernetes config file, KUBECONFIG variable set, I get:

```
Error: contexts[16].context.cluster is missing
    at /usr/local/lib/chectl/node_modules/@kubernetes/client-node/dist/config_types.js:75:19
    at Function._.map._.collect (/usr/local/lib/chectl/node_modules/underscore/underscore.js:205:24)
    at Object.newContexts (/usr/local/lib/chectl/node_modules/@kubernetes/client-node/dist/config_types.js:63:14)
    at KubeConfig.loadFromString (/usr/local/lib/chectl/node_modules/@kubernetes/client-node/dist/config.js:95:40)
    at KubeConfig.loadFromFile (/usr/local/lib/chectl/node_modules/@kubernetes/client-node/dist/config.js:65:14)
    at KubeConfig.loadFromDefault (/usr/local/lib/chectl/node_modules/@kubernetes/client-node/dist/config.js:189:18)
    at new KubeHelper (/usr/local/lib/chectl/lib/api/kube.js:23:21)
    at new CheTasks (/usr/local/lib/chectl/lib/tasks/che.js:24:21)
    at Start.<anonymous> (/usr/local/lib/chectl/lib/commands/server/start.js:101:30)
    at Generator.next (<anonymous>)
```

Mind you, my .kube/config has several clusters merged in it, but I did set the current context to the appropriate cluster.

### Che version

 - [x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior

It should have installed che

### Runtime
   - [ x] kubernetes (include output of `kubectl version`) --> v1.14.7
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environmentv1.14.7
   - [ ] my computer 
       - [ ] Windows
       - [ x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [x ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by LouisKottmann** [comment]
I tried the command again on another computer that should have been identical and it worked fine.
Machines be trippin'

**Comment by Richard87** [comment]
I had the same error, it turned out the context was faulty (in my case, context[1], in above context[16])

When I removed the faulty context and related cluster/user info, it works perfectly again :)
