### ISSUE TITLE
Update VSCode Tooling for Apache Camel K from 0.0.9 to 0.0.10

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15086]
### Is your enhancement related to a problem? Please describe.

seems that the some features of the VS Code Tooling for Apache Camel is not working when Che is installed on latest version of minikube

### Additional context

requires to update also the docker file in che-theia to pick a newer kamel

if using command-line:
```
sh-5.0$ kamel install
panic: user: unknown userid 1724

goroutine 1 [running]:
github.com/apache/camel-k/pkg/client.getDefaultKubeConfigFile(0xc000556d60, 0x7fd33837ba62)
        /home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/client/client.go:135 +0xe1
github.com/apache/camel-k/pkg/client.GetCurrentNamespace(0x0, 0x0, 0xc0000d7800, 0xc0000d7500, 0xc00049fd68, 0xc00049fd68)
        /home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/client/client.go:143 +0x602
github.com/apache/camel-k/pkg/cmd.(*RootCmdOptions).preRun(0xc000530e00, 0xc00013c780, 0x2658198, 0x0, 0x0, 0x0, 0x0)
        /home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/cmd/root.go:75 +0x55
github.com/spf13/cobra.(*Command).execute(0xc00013c780, 0x2658198, 0x0, 0x0, 0xc00013c780, 0x2658198)
        /home/nferraro/gopaths/camel-k/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:741 +0x570
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f6c80, 0x0, 0xc0001f6c80, 0x0)
        /home/nferraro/gopaths/camel-k/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /home/nferraro/gopaths/camel-k/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/cmd/kamel/main.go:43 +0x172
```

in Output --> Apache Camel K;

```
Refreshing Apache Camel K Integrations view using kubectl failed. Error: panic:  
Refreshing Apache Camel K Integrations view using kubectl failed. Error: panic: user: unknown userid 1724
goroutine 1 [running]:
github.com/apache/camel-k/pkg/client.getDefaultKubeConfigFile(0xc0005da070, 0x7eff1835e010)
	/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/client/client.go:135 +0xe1
github.com/apache/camel-k/pkg/client.GetCurrentNamespace(0x0, 0x0, 0xc000202500, 0xc000202600, 0xc0005d7d68, 0xc0005d7d68)
	/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/client/client.go:143 +0x602
github.com/apache/camel-k/pkg/cmd.(*RootCmdOptions).preRun(0xc00059c980 
```

**Comment by apupier** [comment]
merged
