### ISSUE TITLE
[Happy Path] The "Happy Path" scenario sometimes fails on the "Validation of workspace build and run" step 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#15166]
### Describe the bug
[Happy Path] The "Happy Path" scenario sometimes fails on the "Validation of workspace build and run" step 

```
  ✓ Run application (25457ms)
15:29:46         ▼ PreviewWidget.waitContentAvailable By(xpath, //div[@class='container-fluid']//h2[text()='Welcome'])
15:29:46         ▼ PreviewWidget.waitAndSwitchToWidgetFrame
15:29:46         ▼ PreviewWidget.switchBackToIdeFrame
15:29:46         ▼ Ide.waitAndSwitchToIdeFrame
15:29:46         ▼ PreviewWidget.refreshPage
15:29:46         ▼ PreviewWidget.waitAndSwitchToWidgetFrame
15:29:59         ▼ PreviewWidget.switchBackToIdeFrame
15:29:59         ▼ Ide.waitAndSwitchToIdeFrame
15:29:59         ▼ PreviewWidget.refreshPage
15:29:59         ▼ PreviewWidget.waitAndSwitchToWidgetFrame
15:30:09         ▼ PreviewWidget.switchBackToIdeFrame
15:30:09         ▼ Ide.waitAndSwitchToIdeFrame
15:30:09         ▼ PreviewWidget.refreshPage
15:30:09         ▼ PreviewWidget.waitAndSwitchToWidgetFrame
15:30:19         ▼ PreviewWidget.switchBackToIdeFrame
15:30:19         ▼ Ide.waitAndSwitchToIdeFrame
15:30:19         ▼ PreviewWidget.refreshPage
15:30:19         ▼ PreviewWidget.waitAndSwitchToWidgetFrame
15:30:29         ▼ PreviewWidget.switchBackToIdeFrame
15:30:29         ▼ Ide.waitAndSwitchToIdeFrame
15:30:29         ▼ PreviewWidget.refreshPage
15:30:29         ▼ PreviewWidget.waitAndSwitchToWidgetFrame
15:30:39         ▼ PreviewWidget.switchBackToIdeFrame
15:30:39         ▼ Ide.waitAndSwitchToIdeFrame
15:30:39         ▼ PreviewWidget.refreshPage
15:30:39         ▼ PreviewWidget.waitAndSwitchToWidgetFrame
15:30:49     1) Check the running application
15:30:49 
15:30:49 
15:30:49   10 passing (6m)
15:30:49   1 pending
15:30:49   1 failing
15:30:49 
15:30:49   1) Validation of workspace build and run
15:30:49        Check the running application:
15:30:49      TimeoutError: Wait timed out after 62409ms
15:30:49       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
15:30:49       at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
15:30:49       at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
15:30:49       at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
15:30:49       at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
15:30:49       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
15:30:49       at <anonymous>
15:30:49   From: Task: <anonymous wait>
15:30:49       at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
15:30:49       at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
15:30:49       at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
15:30:49       at PreviewWidget.<anonymous> (/tmp/e2e/pageobjects/ide/PreviewWidget.ts:50:45)
15:30:49       at Generator.next (<anonymous>)
15:30:49       at fulfilled (/tmp/e2e/dist/pageobjects/ide/PreviewWidget.js:17:58)
15:30:49       at <anonymous>
15:30:49       at process._tickCallback (internal/process/next_tick.js:188:7)
```
### Che version

 - [ ] latest
 - [ x ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ x ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![445578_242275324_product-1000x1000](https://user-images.githubusercontent.com/22724619/68662394-61358080-0545-11ea-8eeb-be0f19b0c1c9.png)

### Installation method
   - [ x ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ x ] other (please specify) 
   - [ ] other: please specify

**Comment by Ohrimenko1988** [comment]
Outdated
