### ISSUE TITLE
After launching an application the preview URL widget does not appear

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#15173]
### Describe the bug
* After clicking on the Open Link notification the Preview URL app. does not open

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![openlink-bug](https://user-images.githubusercontent.com/1640058/68677331-99988700-0564-11ea-93e0-3add68fe6b66.gif)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by musienko-maxim** [comment]
Looks like it depend on latest changes from CHE-THEIA : 
The theia log exception:
```
root ERROR [hosted-plugin: 51] Promise rejection not handled in one second: Error: Unknown actor CheTaskMain
With stack trace: Error: Unknown actor CheTaskMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:249:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:240:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:204:31)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:173:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:280:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root INFO [nsfw-watcher: 126] Started watching: /projects/petclinic/result-build.txt
root INFO [hosted-plugin: 143] redirecting connections from 127.0.0.1:13131 to localhost:8080
root INFO [hosted-plugin: 143] The port 8080 is now listening on interface 0.0.0.0
root ERROR [hosted-plugin: 51] Promise rejection not handled in one second: Error: Unknown actor MessageRegistryMain
With stack trace: Error: Unknown actor MessageRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:249:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:240:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:204:31)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:173:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:280:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root ERROR [hosted-plugin: 143] Promise rejection not handled in one second: TypeError: e.startsWith is not a function
With stack trace: TypeError: e.startsWith is not a function
    at e.canHandle (http://serverju33ehde-theia-ide4ht-server-3100.192.168.99.226.nip.io/bundle.js:12:957753)
    at http://serverju33ehde-theia-ide4ht-server-3100.192.168.99.226.nip.io/bundle.js:12:956717
    at http://serverju33ehde-theia-ide4ht-server-3100.192.168.99.226.nip.io/bundle.js:12:1038078
    at http://serverju33ehde-theia-ide4ht-server-3100.192.168.99.226.nip.io/bundle.js:12:1037680
    at Object.next (http://serverju33ehde-theia-ide4ht-server-3100.192.168.99.226.nip.io/bundle.js:12:1037785)
    at a (http://serverju33ehde-theia-ide4ht-server-3100.192.168.99.226.nip.io/bundle.js:12:1036531)
```

**Comment by RomanNikitenko** [comment]
@musienko-maxim 
looks like it's duplicate https://github.com/eclipse/che/issues/15172

wdyt?

**Comment by musienko-maxim** [comment]
yes, i've closed https://github.com/eclipse/che/issues/15172

**Comment by vparfonov** [comment]
Will take to the current sprint as unplanned and try to fix it

**Comment by RomanNikitenko** [comment]
We use plugin API and execution of [the command](https://github.com/eclipse-theia/theia/blob/83c59134268f1c45789f2ba8fe88567d10cdc22d/packages/mini-browser/src/browser/mini-browser-open-handler.ts#L45) to open preview panel. 
I investigated the issue, the regression was caused by [the changes](https://github.com/eclipse-theia/theia/pull/5590/files#diff-280ddf8bd3c3f719bbbdc998df11dd33R110).
Fixed in theia repo.

**Comment by l0rd** [comment]
Set as a blocker because this issue affects our Happy Path PR check

**Comment by musienko-maxim** [comment]
Checked on minikube infra manually the bug is fixed
