### ISSUE TITLE
Deployment via Chectl fails when running from wrong directory on Windows

### ISSUE THREAD

**Issue by cbos** [eclipse-che/che#15225]
```
PS C:\Users\cbos> chectl server:start --platform=docker-desktop --domain=10.153.242.101.nip.io
  √ Verify Kubernetes API...OK
  √ 👀  Looking for an already existing Che instance
    √ Verify if Che is deployed into namespace "che"...it is not
  √ ✈️  Docker Desktop preflight checklist
    √ Verify if kubectl is installed
    √ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    √ Verify remote kubernetes status...done.
    √ Verify if nginx ingress is installed
    ↓ Installing nginx ingress [skipped]
      → Ngninx ingress is already setup.
    √ Verify domain is set...set to 10.153.242.101.nip.io.
  > 🏃‍  Running Helm to install Che
    √ Verify if helm is installed
    √ Create Tiller Role Binding...it already exists.
    √ Create Tiller Service Account...it already exists.
    × Create Tiller RBAC
      → ENOENT: no such file or directory, open 'templates\kubernetes\helm\che\tiller-rbac.yaml'
      Create Tiller Service
      Preparing Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Che Helm Chart
Error: ENOENT: no such file or directory, open 'templates/kubernetes/helm/che/tiller-rbac.yaml'
    at HelmTasks.<anonymous> (C:/Users/cbos/AppData/Local/chectl/client/0.0.20191118-next.0a37a83/lib/tasks/installers/helm.js:187:36)
    at Generator.next (<anonymous>)
    at C:/Users/cbos/AppData/Local/chectl/client/0.0.20191118-next.0a37a83/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:/Users/cbos/AppData/Local/chectl/client/0.0.20191118-next.0a37a83/node_modules/tslib/tslib.js:106:16)
    at HelmTasks.createTillerRBAC (C:/Users/cbos/AppData/Local/chectl/client/0.0.20191118-next.0a37a83/lib/tasks/installers/helm.js:185:24)
    at HelmTasks.<anonymous> (C:/Users/cbos/AppData/Local/chectl/client/0.0.20191118-next.0a37a83/lib/tasks/installers/helm.js:96:96)
    at Generator.next (<anonymous>)
```

When I change my working directory to: C:\ProgramData\chectl\chectl\ it is working fine
```
PS C:\Users\cbos> cd C:\ProgramData\chectl\chectl\
PS C:\ProgramData\chectl\chectl> chectl server:start --platform=docker-desktop --domain=10.153.242.101.nip.io

...
    √ Create Tiller Service Account...it already exists.
    √ Create Tiller RBAC
    √ Create Tiller Service...it already exists.
    √ Preparing Che Helm Chart...done.
    √ Updating Helm Chart dependencies...done.
    √ Deploying Che Helm Chart...done.
...
```
So it looks like the lookup of 'templates\kubernetes\helm\che\tiller-rbac.yaml' is done relative to the start of the command, rather then installation of Chectl.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by l0rd** [comment]
@cbos thanks for reporting this. @benoitf do you know if that's an error that we have always had or is it a regression?

**Comment by benoitf** [comment]
I think it may be an error we always had.

**Comment by CyborTronik** [comment]
Getting almost the same behaviour. just stops at `Preparing Che Helm Chart` step. Moving forward after doing `cd C:\ProgramData\chectl\chectl\`

**Comment by tolusha** [comment]
Fixed in recent versions.
