### ISSUE TITLE
Sometimes cannot restart a workspace with NPE in KubernetesDeployments$CreateWatcher.eventReceived and KubernetesInternalRuntime.storeStartingMachine

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15319]
### Describe the bug
on second start, the workspace fails to start with `Error: Failed to run the workspace: "An exception occurred."`

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace (java-maven fo rinstance)
2. Wait that the workspace has started
3. Stop the workspace
4. Try to open again the workspace

### Expected behavior
workspace to be able to start several times

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

### Installation method
   - [x] chectl ` chectl server:install -p minikube`
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by apupier** [comment]
in che-host, there is this erro rin log:

```
2019-11-26 12:37:25,047[ceSharedPool-10]  [WARN ] [.i.k.KubernetesInternalRuntime 250]  - Failed to start Kubernetes runtime of workspace workspacef9nw7aetu2z0zn22. Cause: null
2019-11-26 12:37:26,313[ceSharedPool-10]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 854]   - Workspace 'che:wksp-n9et' with id 'workspacef9nw7aetu2z0zn22' start failed
2019-11-26 12:37:26,314[ceSharedPool-10]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 864]   - An exception occurred.
org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: An exception occurred.
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:814)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:272)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:830)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.storeStartingMachine(KubernetesInternalRuntime.java:716)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.doStartMachine(KubernetesInternalRuntime.java:691)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.startMachines(KubernetesInternalRuntime.java:603)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:208)
	... 7 common frames omitted
```

**Comment by apupier** [comment]
also:

```
java.lang.NullPointerException: null
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$CreateWatcher.eventReceived(KubernetesDeployments.java:967)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$CreateWatcher.eventReceived(KubernetesDeployments.java:951)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:232)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by skabashnyuk** [comment]
Che version?

**Comment by apupier** [comment]
Theia@8f867f2 using Theia@98ac397 Built 11/26/2019, 9:40:08 AM

**Comment by skabashnyuk** [comment]
>Theia@8f867f2 using Theia@98ac397 Built 11/26/2019, 9:40:08 AM

Che server version?

**Comment by skabashnyuk** [comment]
- #15319 (comment) is this a first exception in the logs?
 - Can you provide workspace json?

**Comment by apupier** [comment]
> * #15319 (comment) is this a first exception in the logs?

yes, see full log: https://pastebin.com/ydpjMdie

> * Can you provide workspace json?
> * Is this reproducible task?

I reproduced it 4 out 4  times. 2 times with the default java-maven stack. 2 times with a custom stack https://raw.githubusercontent.com/apupier/che-devfile-registry/14831-ApacheCamelKStack/devfiles/apache-camel-k/devfile.yaml

**Comment by skabashnyuk** [comment]
>I reproduced it 4 out 4 times

I mean do you know the steps to reproduce on another environment?

**Comment by apupier** [comment]
> > I reproduced it 4 out 4 times
> 
> I mean do you know the steps to reproduce on another environment?

I have access only to a minikube environment, so cannot try for other environments of the Che installation but the steps to reproduce are quite simple to test  when there is an access to other environments.

or do you mean with other stacks?

**Comment by skabashnyuk** [comment]
@apupier I still need Che server version. That might be important data.

**Comment by skabashnyuk** [comment]
Like this
<img width="679" alt="Знімок екрана  о 18 25 54" src="https://user-images.githubusercontent.com/1614429/69657295-3b969400-107a-11ea-99f8-cc8e4309ba41.png">

**Comment by l0rd** [comment]
I am not able to reproduce it on minikube using nightly. That can be related to the specific version you are using (7.4.0 or 7.3.2?) hence it should not be a blocker for 7.5.0 release.

**Comment by apupier** [comment]
I'm using 7.5.0-SNAPSHOT.
I recreated my whole Minikube instance after calling `chectl update latest` yesterday.

**Comment by apupier** [comment]
I recreated again this morning after a `chectl update next` and I don't reproduce anymore

**Comment by apupier** [comment]
I just reproduced it, with the same instance.

The main difference that I can think of is that I installed Camel K in Che namespace

**Comment by skabashnyuk** [comment]
I've tested https://raw.githubusercontent.com/apupier/che-devfile-registry/14831-ApacheCamelKStack/devfiles/apache-camel-k/devfile.yaml on Openshift installed with che-operator. It works correctly I think.

<img width="1671" alt="Знімок екрана  о 17 06 06" src="https://user-images.githubusercontent.com/1614429/69739644-5cbdba00-1138-11ea-8402-53ad579d4044.png">
@apupier  can you try to setup che with che-operator?

**Comment by apupier** [comment]
> I've tested https://raw.githubusercontent.com/apupier/che-devfile-registry/14831-ApacheCamelKStack/devfiles/apache-camel-k/devfile.yaml on Openshift installed with che-operator. It works correctly I think.

you need to provide a kubeconfig (for instance with `chectl workspace:inject`) and then call `kamel install` in terminal of the vscode-camelk container.
Then to restart.


> can you try to setup che with che-operator?

I will try

**Comment by skabashnyuk** [comment]
>I think you need to install Camel K.
you need to provide a kubeconfig (for instance with chectl workspace:inject) and then call kamel install in terminal of the vscode-camelk container.
Then to restart.

Not sure I understand what do you mean by installing Camel K. 
 I've
 -  took `crc` https://github.com/code-ready/crc 
 - started che with  `chectl server:start --platform=crc  --installer=operator`
 - Created worksapce with factory `http://che-che.apps-crc.testing/f?url=https://raw.githubusercontent.com/apupier/che-devfile-registry/14831-ApacheCamelKStack/devfiles/apache-camel-k/devfile.yaml`

**Comment by apupier** [comment]
> * took `crc` https://github.com/code-ready/crc
> * started che with  `chectl server:start --platform=crc  --installer=operator`
> * Created worksapce with factory `http://che-che.apps-crc.testing/f?url=https://raw.githubusercontent.com/apupier/che-devfile-registry/14831-ApacheCamelKStack/devfiles/apache-camel-k/devfile.yaml`

then:
you need to provide a kubeconfig (for instance with chectl workspace:inject) and then call kamel install in terminal of the vscode-camelk container.
Then to restart.

with the provided stack, there are tools to access Camel K but Camel K itself is not already installed.

**Comment by apupier** [comment]
so retried today and I cannot reproduce.

I retried with operator and with helm
I retried with Camel K instance started and even a Camel K integration deployed.

Then I really don't know what are the steps to reproduce. the thing is that I ended up 2 times in this state. It was failing for 2 different stacks.

**Comment by skabashnyuk** [comment]
@apupier can you share a workspace json of failing workspace, next time?

**Comment by apupier** [comment]
> can you share a workspace json of failing workspace, next time?

how can I get a workspace json?
it is with the "export as a file"  in the overview page of the workspace?

**Comment by skabashnyuk** [comment]
```GET /api/workspace/{workspaceid}```

**Comment by metlos** [comment]
I failed to figure out how this is happening from just staring at the code and wasn't able to reproduce locally. If you're willing to help us diagnose this, could you please replace the che server image with `quay.io/lkrejci/che-server:7.4.0-issue-15319`? It's a custom image where I've added some additional logging in places I hope we could get some more info. The workspace config that @skabashnyuk mentioned would also be super helpful.

I'd really appreciate if you were able to produce the server logs from the custom image when starting a workspace experiencing this issue along with its workspace config.

**Comment by metlos** [comment]
The code for the che server in the above mentioned image is here: https://github.com/metlos/che/tree/7.4.0-for-15319
