### ISSUE TITLE
[PSQLException] ERROR: update or delete on table 'workspace' violates foreign key constraint 'ws_expiration_workspace_id' on table 'che_workspace_expiration'

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15352]
### Describe the bug
```
{"@timestamp":"2019-11-28T08:01:16.756+00:00","@version":1,"message":"Couldn't remove free resources limit before account 'XXXXX' is removed","logger_name":"org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao","thread_name":"http-nio-8080-exec-3","level":"ERROR","level_value":40000,"stack_trace":"org.eclipse.che.api.core.ServerException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
Error Code: 0
Call: SELECT account_id FROM che_free_resources_limit WHERE (account_id = ?)
\tbind => [1 parameter bound]
Query: ReadObjectQuery(name=\"readFreeResourcesLimitImpl\" referenceClass=FreeResourcesLimitImpl sql=\"SELECT account_id FROM che_free_resources_limit WHERE (account_id = ?)\")
at org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao.remove(JpaFreeResourcesLimitDao.java:102)
at org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao$RemoveFreeResourcesLimitSubscriber.onEvent(JpaFreeResourcesLimitDao.java:169)
at org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao$RemoveFreeResourcesLimitSubscriber.onEvent(JpaFreeResourcesLimitDao.java:150)
at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:108)
at org.eclipse.che.account.api.AccountManager.remove(AccountManager.java:110)
at org.eclipse.che.multiuser.api.account.personal.PersonalAccountUserManager.remove(PersonalAccountUserManager.java:81)
at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager$$EnhancerByGuice$$cbfdc7b2.CGLIB$remove$3(<generated>)
at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager$$EnhancerByGuice$$cbfdc7b2$$FastClassByGuice$$177ee3c9.invoke(<generated>)
at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:64)
at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager$$EnhancerByGuice$$cbfdc7b2.remove(<generated>)
at org.eclipse.che.api.user.server.UserService.remove(UserService.java:213)
at sun.reflect.GeneratedMethodAccessor773.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
at org.eclipse.che.core.metrics.ApiResponseMetricFilter.doFilter(ApiResponseMetricFilter.java:46)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:53)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:151)
at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter$$EnhancerByGuice$$13fefe1f.CGLIB$doFilter$0(<generated>)
at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter$$EnhancerByGuice$$13fefe1f$$FastClassByGuice$$893054a1.invoke(<generated>)
at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:51)
at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter$$EnhancerByGuice$$13fefe1f.doFilter(<generated>)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:70)
at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$$EnhancerByGuice$$d4d76de5.CGLIB$doFilter$0(<generated>)
at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$$EnhancerByGuice$$d4d76de5$$FastClassByGuice$$f08095ab.invoke(<generated>)
at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:51)
at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$$EnhancerByGuice$$d4d76de5.doFilter(<generated>)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:114)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:188)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
Error Code: 0
Call: SELECT account_id FROM che_free_resources_limit WHERE (account_id = ?)
\tbind => [1 parameter bound]
Query: ReadObjectQuery(name=\"readFreeResourcesLimitImpl\" referenceClass=FreeResourcesLimitImpl sql=\"SELECT account_id FROM che_free_resources_limit WHERE (account_id = ?)\")
at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1650)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:683)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099)
at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:313)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectOneRow(DatasourceCallQueryMechanism.java:764)
at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRowFromTable(ExpressionQueryMechanism.java:2822)
at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRow(ExpressionQueryMechanism.java:2775)
at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:561)
at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232)
at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191)
at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:447)
at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830)
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.executeQuery(EntityManagerImpl.java:1012)
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.findInternal(EntityManagerImpl.java:954)
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:830)
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:696)
at org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao.doRemove(JpaFreeResourcesLimitDao.java:109)
at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:56)
at org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao.remove(JpaFreeResourcesLimitDao.java:100)
at org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao$RemoveFreeResourcesLimitSubscriber.onEvent(JpaFreeResourcesLimitDao.java:169)
at org.eclipse.che.multiuser.resource.spi.jpa.JpaFreeResourcesLimitDao$RemoveFreeResourcesLimitSubscriber.onEvent(JpaFreeResourcesLimitDao.java:150)
at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:108)
at org.eclipse.che.account.api.AccountManager.remove(AccountManager.java:110)
at org.eclipse.che.multiuser.api.account.personal.PersonalAccountUserManager.remove(PersonalAccountUserManager.java:81)
at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:64)
at org.eclipse.che.api.user.server.UserService.remove(UserService.java:213)
at sun.reflect.GeneratedMethodAccessor773.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
at org.eclipse.che.core.metrics.ApiResponseMetricFilter.doFilter(ApiResponseMetricFilter.java:46)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:53)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:151)
at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:51)
at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:70)
at com.redhat.che.wsmaster.deploy.DisableAuthenticationInterceptor.invoke(DisableAuthenticationInterceptor.java:51)
\t... 28 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:107)
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:107)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1015)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:651)
\t... 87 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table \"workspace\" violates foreign key constraint \"ws_expiration_workspace_id\" on table \"che_workspace_expiration\"
  Detail: Key (id)=(workspaceXXXX) is still referenced from table \"che_workspace_expiration\".
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:121)
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:121)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:970)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:640)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099)
at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:313)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.deleteObject(DatasourceCallQueryMechanism.java:243)
at org.eclipse.persistence.internal.queries.StatementQueryMechanism.deleteObject(StatementQueryMechanism.java:106)
at org.eclipse.persistence.queries.DeleteObjectQuery.executeDatabaseQuery(DeleteObjectQuery.java:220)
at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:810)
at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:110)
at org.eclipse.persistence.queries.DeleteObjectQuery.executeInUnitOfWorkObjectLevelModifyQuery(DeleteObjectQuery.java:121)
at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:87)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830)
at org.eclipse.persistence.internal.sessions.CommitManager.deleteAllObjects(CommitManager.java:344)
at org.eclipse.persistence.internal.sessions.CommitManager.deleteAllObjects(CommitManager.java:298)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1498)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithPreBuiltChangeSet(UnitOfWorkImpl.java:1641)
at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:457)
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:975)
at org.eclipse.che.multiuser.permission.workspace.server.spi.jpa.MultiuserJpaWorkspaceDao.doRemove(MultiuserJpaWorkspaceDao.java:259)
at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:56)
at org.eclipse.che.multiuser.permission.workspace.server.spi.jpa.MultiuserJpaWorkspaceDao.remove(MultiuserJpaWorkspaceDao.java:105)
at org.eclipse.che.api.workspace.server.WorkspaceManager.removeWorkspace(WorkspaceManager.java:345)
at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:60)
at org.eclipse.che.api.workspace.server.jpa.JpaWorkspaceDao$RemoveWorkspaceBeforeAccountRemovedEventSubscriber.onCascadeEvent(JpaWorkspaceDao.java:289)
at org.eclipse.che.api.workspace.server.jpa.JpaWorkspaceDao$RemoveWorkspaceBeforeAccountRemovedEventSubscriber.onCascadeEvent(JpaWorkspaceDao.java:265)
at org.eclipse.che.core.db.cascade.CascadeEventSubscriber.onEvent(CascadeEventSubscriber.java:29)
at org.eclipse.che.core.db.cascade.CascadeEventSubscriber.onEvent(CascadeEventSubscriber.java:24)
\t... 60 common frames omitted
","identity_id":"d24f3189-94df-4fd2-86b8-8f957251de03"}


```

### Che version
7.3.x

### Steps to reproduce
n/a
### Expected behavior
PSQLException should not happen in this form

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
n/a

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [X] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [X] Linux
       - [ ] macOS
   - [ ] Cloud
       - [X] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
https://github.com/eclipse/che/issues/15248

**Comment by skabashnyuk** [comment]
From what I can see `che_workspace_expiration` is a deprecated table https://github.com/eclipse/che/blob/b38ae91affb33509f1c599e28224f84d1678425f/wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceExpiration.java#L24-L29 and we don't have cascade removal of the rows from this table before workspace removal. https://github.com/eclipse/che/blob/b38ae91affb33509f1c599e28224f84d1678425f/wsmaster/che-core-api-workspace-activity/src/main/java/org/eclipse/che/api/workspace/activity/WorkspaceActivityManager.java#L112-L119
.
What I can recommend.
  1. with next update just delete this table at all che_workspace_expiration with WorkspaceExpiration
  2. As a temporary workaround `DELETE * from che_workspace_expiration`
