### ISSUE TITLE
[che-theia] Stabilize plugin tests that fail due to timeout (use more mocks)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15418]
The crw-theia build has failed 4 times in the last couple days due to test timeouts being exceeded.

```
● Test Extensions › use default extensions
    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
      201 |     });
      202 | 
    > 203 |     test('use default extensions', async () => {
          |     ^
      204 |         const initSources = new InitSources(assemblyExamplePath, packagesFolderTmp, pluginsFolderTmp, cheTheiaFolderTmp, assemblyFolderTmp, THEIA_DUMMY_VERSION);
      205 |         await initSources.readConfigurationAndGenerate(undefined, false);
      206 |         expect(fs.readdirSync(packagesFolderTmp).length).toBeGreaterThan(0);
      at Spec (../node_modules/jest-cli/node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Suite.Object.<anonymous>.describe (tests/init-sources/init-sources.spec.ts:203:5)
      at Object.<anonymous> (tests/init-sources/init-sources.spec.ts:22:1)
```

and also:

```
@eclipse-che/theia-factory-plugin:   ● Test git commands › get git current branch after checkout
@eclipse-che/theia-factory-plugin:     Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.
```

Florent says:

> this test is fragile, as timeout has already been increased
https://github.com/eclipse/che-theia/blob/9bc035a3e2acb19627faf1f0a74121675a1dc855/generator/tests/init-sources/init-sources.spec.ts#L25

Workaround:

> you can replace
> `test('use default extensions', async () => {`
> by
> `test.skip('use default extensions', async () => {`

Also affected is this test: `get git current branch after checkout`. Possibly others.

For now I'll comment out tests but in future it would be better if the tests didn't fail when the internet is being slow.

**Comment by nickboldt** [comment]
Links to console logs with failures:

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/413/parsed_console/

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/411/parsed_console/

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/410/parsed_console/
