### ISSUE TITLE
chectl fails to provision Che with tls option

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#15411]
### Describe the bug
When try to deploy Che server on minishift with `--tls` option, chectl fails with timeout error.

### Che version
nightly

### Steps to reproduce

1. Create minishift instance with command: `minishift start --vm-driver=virtualbox --cpus=4 --memory=10240 --disk-size=50GB --docker-opt userland-proxy=false`
2. Run `chectl server:start --multiuser --tls --platform=openshift`
3. After some time it fails with timeout error

<details>
<summary> chectl logs: </summary>

```
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
  ✔ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...done.
    ✔ Create ServiceAccount che-operator in namespace che...done.
    ✔ Create Role che-operator in namespace che...done.
    ✔ Create ClusterRole che-operator...done.
    ✔ Create RoleBinding che-operator in namespace che...done.
    ✔ Create ClusterRoleBinding che-operator...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...done.
    ✔ Create Che Cluster eclipse-che in namespace che...done.
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Keycloak pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✖ starting
        → ERR_TIMEOUT: Timeout set to pod ready timeout 130000
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod ready timeout 130000
    at KubeHelper.<anonymous> (~/.local/share/chectl/client/0.0.20191127-next.97b31fb/lib/api/kube.js:615:19)
    at Generator.next (<anonymous>)
    at fulfilled (~/.local/share/chectl/client/0.0.20191127-next.97b31fb/node_modules/tslib/tslib.js:107:62)
```

</details>

### Expected behavior
Che is deployed with default cluster certificates in use (at least that's what chectl [docs says](https://github.com/che-incubator/chectl#chectl-serverstart)).

### Runtime
minishift v1.34.1+c2ff9cb

**Comment by tolusha** [comment]
@mmorhun Can we close it when https://github.com/che-incubator/chectl/pull/476 is merged?

**Comment by mmorhun** [comment]
@tolusha I think we may close it when TLS by default is finished.
