### ISSUE TITLE
POD Fail to run : devfile-registry-XXXXXX

### ISSUE THREAD

**Issue by iamnogada** [eclipse-che/che#15567]
### Describe the bug

Cannot run pod: devfile-registry-........in namespace che
(with 7.3.0 this pod is running)

### Che version

 - [ ] latest
 - [ ] nightly
 - [7.6.0 ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ V] Openshift (include output of `oc version 4.2`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ X] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [X ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
Hello, do you have more output of error ?

**Comment by tolusha** [comment]
https://www.eclipse.org/che/docs/che-7/retrieving-che-logs/

**Comment by iamnogada** [comment]
Well, I found out the version confliction.
For making it work, so I did version down to work with 7.3.0

Later on I will try it on 7.6.0 and capture log and then share for teams~

**Comment by iamnogada** [comment]
I deploy codewind wroskpace using "http://<che ingress domain>/f?url=https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/devfiles/0.7.0/devfile.yaml"

It is guided in https://www.eclipse.org/codewind/mdt-che-installinfo.html



<img width="1402" alt="스크린샷 2020-01-09 오후 7 54 38" src="https://user-images.githubusercontent.com/13878666/72061876-04bec980-331a-11ea-9cf0-1de8bd05589f.png">

**Comment by iamnogada** [comment]
Message From webconsole of che
After failure, pod disappeared
-------
Pulling image "eclipse/che-init-plugin-broker:v0.24"
Successfully pulled image "eclipse/che-init-plugin-broker:v0.24"
Created container che-init-plugin-broker-v0-24
Started container che-init-plugin-broker-v0-24
Starting Init Plugin Broker
Cleaning /plugins dir
Pulling image "eclipse/che-unified-plugin-broker:v0.24"
Successfully pulled image "eclipse/che-unified-plugin-broker:v0.24"
Created container che-unified-plugin-broker-v0-24
Started container che-unified-plugin-broker-v0-24
Downloading VS Code extension for plugin ''
Unified Che Plugin Broker
Starting VS Code and Theia plugins processing
Starting Che plugins and editor processing
List of plugins and editors to install
- eclipse/CodewindPlugin/0.7.0 - Enables iterative development and deployment in Che
- eclipse/codewind-plugin/0.7.0 - Codewind Extension for Theia
- eclipse/che-machine-exec-plugin/7.6.0 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
- eclipse/che-theia/latest - Eclipse Theia
All plugins have been successfully processed
Error: Failed to run the workspace: "Duplicate key ComponentImpl{id='null', alias='codewind-sidecar', type='chePlugin', preferences={}, registryUrl='null', reference='null', referenceContent='null', selector={}, entrypoints=[], image='null', memoryLimit='null', mountSources=null, command=[], args=[], volumes=[], env=[], endpoints=[]}"
-------


<img width="1262" alt="스크린샷 2020-01-09 오후 8 04 45" src="https://user-images.githubusercontent.com/13878666/72062700-a7c41300-331b-11ea-9656-f4985343764e.png">

**Comment by skabashnyuk** [comment]
Confirmed bug.
```
2020-01-09 11:24:36,620[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 907]   - Duplicate key ComponentImpl{id='null', alias='codewind-sidecar', type='chePlugin', preferences={}, registryUrl='null', reference='null', referenceContent='null', selector={}, entrypoints=[], image='null', memoryLimit='null', mountSources=null, command=[], args=[], volumes=[], env=[], endpoints=[]}
org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Duplicate key ComponentImpl{id='null', alias='codewind-sidecar', type='chePlugin', preferences={}, registryUrl='null', reference='null', referenceContent='null', selector={}, entrypoints=[], image='null', memoryLimit='null', mountSources=null, command=[], args=[], volumes=[], env=[], endpoints=[]}
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:815)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:274)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:873)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Duplicate key ComponentImpl{id='null', alias='codewind-sidecar', type='chePlugin', preferences={}, registryUrl='null', reference='null', referenceContent='null', selector={}, entrypoints=[], image='null', memoryLimit='null', mountSources=null, command=[], args=[], volumes=[], env=[], endpoints=[]}
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.KubernetesPluginsToolingApplier.apply(KubernetesPluginsToolingApplier.java:134)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:82)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:182)
	... 7 common frames omitted
```

**Comment by skabashnyuk** [comment]
@iamnogada according to https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#specifying-a-component-by-linking-to-its-descriptor try to use  `reference` instead of `id` like this:
```yaml
---
apiVersion: 1.0.0
metadata:
  generateName: codewind-
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/latest
  - alias: codewind-sidecar
    type: chePlugin
    reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/plugins/codewind/codewind-sidecar/0.7.0/meta.yaml
  - alias: codewind-theia
    type: chePlugin
    reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/plugins/codewind/codewind-theia/0.7.0/meta.yaml
```

**Comment by iamnogada** [comment]
I will test after current working done.
Thanks for your work.
