### ISSUE TITLE
EnvVars.extractReferencedVariables fails when using valueFrom in devfile

### ISSUE THREAD

**Issue by mingfang** [eclipse-che/che#15570]
If my devfile have a component of `type: kubernetes` and the pod has an env using the valueFrom(https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api) like this
```
env:
- name: NAMESPACE
  valueFrom:                                                                                  
    fieldRef:                                                                     
      apiVersion: v1                                                                       
      fieldPath: metadata.namespace
```

then I'm getting an error here 

https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/EnvVars.java#L87

```
Caused by: java.lang.NullPointerException: null                                               
     at java.util.regex.Matcher.getTextLength(Matcher.java:1283)                               
     at java.util.regex.Matcher.reset(Matcher.java:309)                                        
     at java.util.regex.Matcher.<init>(Matcher.java:229)                                       
     at java.util.regex.Pattern.matcher(Pattern.java:1093)                                     
     at org.eclipse.che.workspace.infrastructure.kubernetes.util.EnvVars.extractReferencedVariables(EnvVars.java:87)                                                                            
     at org.eclipse.che.commons.lang.TopologicalSort.sort(TopologicalSort.java:96)             
     at org.eclipse.che.workspace.infrastructure.kubernetes.provision.env.EnvVarsConverter.provision(EnvVarsConverter.java:77)                                                                  
     at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesEnvironmentProvisioner$KubernetesEnvironmentProvisionerImpl.provision(KubernetesEnvironmentProvisioner.java:140)          
     at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:199)      
```

**Comment by skabashnyuk** [comment]
@mingfang can you please provide a full devfile to test?

**Comment by mingfang** [comment]
@skabashnyuk 
This is a gist that demonstrates the problem https://gist.github.com/mingfang/a224c04d8df9a066efe8291f40b715bc

The problem is caused by line 36.
