### ISSUE TITLE
Che Theia docker build is failed

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15695]
Docker build of Che Theia is failed.
See the CI logs https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-nightly/39/console

**Comment by vzhukovskii** [comment]
Console output on starting theia in che-theia docker image:

```
Failed to start the backend application.
{ Error: Cannot find module 'async-limiter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/theia/node_modules/ws/lib/permessage-deflate.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
/home/theia/node_modules/@theia/core/lib/node/main.js:56
    throw reason;
    ^
Error: Cannot find module 'async-limiter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/theia/node_modules/ws/lib/permessage-deflate.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
