### ISSUE TITLE
Java Language Server does not support custom packaging

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#15694]
If I clone some single-module maven project with non standard `packaging` and update project type to Maven (Project->Update Project Configuration) and try to reimport then as result import will fail with the error:
```
2020-01-14 16:35:32,214[ool-10-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 74]      - Jan 14, 2020 4:35:32 PM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
Project for 'file:///projects/sample' not found
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.LibraryNavigation.getProjectDependencyJars(LibraryNavigation.java:123)
java.lang.IllegalArgumentException: Project for 'file:///projects/sample' not found
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.ProjectExternalLibraryCommand.execute(ProjectExternalLibraryCommand.java:42)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.che.jdt.ls.extension.core.internal.CheDelegateCommandHandler.executeCommand(CheDelegateCommandHandler.java:118)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
2020-01-14 16:35:32,228[ool-10-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 74]      - Jan 14, 2020 4:35:32 PM Error in calling delegate command handler
 
java.lang.IllegalArgumentException: Project for 'file:///projects/sample' not found
Project for 'file:///projects/sample' not found
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:451)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.jdt.ls.extension.core.internal.CheDelegateCommandHandler.executeCommand(CheDelegateCommandHandler.java:118)
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.ProjectExternalLibraryCommand.execute(ProjectExternalLibraryCommand.java:42)
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.LibraryNavigation.getProjectDependencyJars(LibraryNavigation.java:123)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:451)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
 
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
java.lang.IllegalArgumentException: Project for 'file:///projects/sample' not found
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.ProjectExternalLibraryCommand.execute(ProjectExternalLibraryCommand.java:42)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:451)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.che.jdt.ls.extension.core.internal.CheDelegateCommandHandler.executeCommand(CheDelegateCommandHandler.java:118)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
2020-01-14 16:35:33,693[ool-10-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 74]      - Jan 14, 2020 4:35:33 PM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
Project for 'file:///projects/sample' not found
java.lang.IllegalArgumentException: Project for 'file:///projects/sample' not found
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.LibraryNavigation.getProjectDependencyJars(LibraryNavigation.java:123)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.LibraryNavigation.getProjectDependencyJars(LibraryNavigation.java:123)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:451)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at org.eclipse.che.jdt.ls.extension.core.internal.CheDelegateCommandHandler.executeCommand(CheDelegateCommandHandler.java:118)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.che.jdt.ls.extension.core.internal.externallibrary.ProjectExternalLibraryCommand.execute(ProjectExternalLibraryCommand.java:42)
2020-01-14 16:35:33,695[ool-10-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 74]      - Jan 14, 2020 4:35:33 PM Error in calling delegate command handler
Project for 'file:///projects/sample' not found
 
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
``` 
 If I remove `<packaging>mypackagingtype</packaging>` and repeat reimport operation then it will be finished successfully. After that, I can change pom's `packaging` back and it will work as expected: any changes will provoke successful reimports. 

### Che version
 - [ ] 6.19.6

### Steps to reproduce
1. 
```
CHE_IP=$(docker run --net=host eclipse/che-ip:6.19.0)
docker run -p 18080:18080 -e CHE_HOST=localhost -e CHE_IP="${CHE_IP}" -e CHE_PORT=18080 --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/me:/data eclipse/che-server:6.19.6 
```
2. Clone/import/create project with non-standard packaging in pom.
3. Update project type to Maven (Project->Update Project Configuration )
3. Try to reimport

AR: exception in `dev-machine` tab and libraries tree is empty

**Comment by l0rd** [comment]
@gorshkov-leonid thanks for reporting this issue but we are not maintaining Che v6.x anymore. Can you try with latest Che version?

cc @tsmaeder

**Comment by IveJ** [comment]
Thanks.

**Comment by gorshkov-leonid** [comment]
Thanks, but I am sure that it is bug, event if this version is not maintained. Som may be better to leave `kind/bug` label

**Comment by gorshkov-leonid** [comment]
The question about migration to Che 7 is too complex. What I want is to bump version of Che to 6 because it is closer to custom build with 6.6.

**Comment by ericwill** [comment]
Che 6 is no longer maintained, nor is it supported. If you face an issue migrating to Che 7, please file an issue and someone will assist you.
