### ISSUE TITLE
Why is workspace startup so slow?

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#15789]
We have recently switched from docker infra Che 6 to K8s Che 7. We are running a multi-user install via helm with a 300GB EBS disk/PV as our workspace storage.

One massive pain point is the time it takes to start-up workspaces each day, it is taking a minimum of **5 minutes** just to start up and sometimes our team need to start ~10 a day each which means they are waiting nearly an hour throughout the day just for workspaces to start. Once running, however, everything is fast.

So far, we have set all available ImagePullPolicy configs to IfNotPresent (which seems to have very little overall impact).

The two slowest parts of WS startup appear to be:

1. At the very beginning, before any logs are shown in the browser (this stage can last at least a couple of minutes)

2. After the "Started container verifier" step:

![screenshot-nimbusweb me-2020 01](https://user-images.githubusercontent.com/1720090/72904443-d2a06500-3d26-11ea-94d9-fec3e4bdf479.png)

What can be done to improve this? Is EBS partly to blame?

**Comment by skabashnyuk** [comment]
@davidwindell Do you have access to workspace's k8s events?

**Comment by skabashnyuk** [comment]
@davidwindell you may want to use something like this https://github.com/redhat-developer/kubernetes-image-puller/tree/master/deploy  to prepull the most used images.
 
CC @ibuziuk @l0rd

**Comment by davidwindell** [comment]
@skabashnyuk it doesn't seem to be slow during any of the image pulling stages (most of them we have set to IfNotPresent anyway. I think the problem is probably around EBS but I can't prove this at the moment.

**Comment by amisevsk** [comment]
@davidwindell To test the EBS hypothesis, you could try starting the workspaces without volumes by adding
```
attributes:
  persistVolumes: 'false'
```
to a workspace devfile (or use the ephemeral mode toggle in the overview page). When persistVolumes is disabled, Che will use `emptyDir` volumes instead of PVs. If there is some mount issue or similar, then workspaces should start more quickly.

**Comment by skabashnyuk** [comment]
@davidwindell can you enable monitoring and get some data from grafana?  https://www.eclipse.org/che/docs/che-7/monitoring-che/

**Comment by davidwindell** [comment]
So with ephemeral mode, workspaces are starting up super fast.

I guess that means it has to be storage attachment related and, as I outlined in #15809, we are often (but not always) seeing the errors: 

```
AttachVolume.Attach succeeded for volume "pvc-208dba8a-42b9-4338-8349-ef5a2b0339b4" 
Unable to attach or mount volumes: unmounted volumes=[claim-che-workspace], unattached volumes=[broker-config-volumejlrxay workspacea125yqx3rm9tvevv-sshprivatekeys ssshkeyconfigvolume gitconfigvolume claim-che-workspace che-workspace-token-2dswp]: timed out waiting for the condition
Error: Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'FailedMount', 'Unable to attach or mount volumes: unmounted volumes=[claim-che-workspace], unattached volumes=[broker-config-volumejlrxay workspacea125yqx3rm9tvevv-sshprivatekeys ssshkeyconfigvolume gitconfigvolume claim-che-workspace che-workspace-token-2dswp]: timed out waiting for the condition', 'workspacea125yqx3rm9tvevv.che-plugin-broker'"
```

Clearly there's something not right but I have very limited knowledge of K8's to actually work this out deeper.

**Comment by davidwindell** [comment]
I've switched now to `local` disk storage, and I am still seeing the same slow gaps in startup. For example (from kubelet logs) there is still a 2 minute gap for example when nothing at all seems to happen:

```
I0131 01:13:59.546557   23601 reconciler.go:252] operationExecutor.MountVolume started for volume "che-workspace-token-2dswp" (UniqueName: "kubernetes.io/secret/c3842f38-1c3e-4506-859b-ed14d5c4f104-che-workspace-token-2dswp") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.546599   23601 reconciler.go:252] operationExecutor.MountVolume started for volume "workspace5z0n5wcridublhah-sshprivatekeys" (UniqueName: "kubernetes.io/secret/c3842f38-1c3e-4506-859b-ed14d5c4f104-workspace5z0n5wcridublhah-sshprivatekeys") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.546624   23601 reconciler.go:252] operationExecutor.MountVolume started for volume "gitconfigvolume" (UniqueName: "kubernetes.io/configmap/c3842f38-1c3e-4506-859b-ed14d5c4f104-gitconfigvolume") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.546650   23601 reconciler.go:252] operationExecutor.MountVolume started for volume "remote-endpoint" (UniqueName: "kubernetes.io/empty-dir/c3842f38-1c3e-4506-859b-ed14d5c4f104-remote-endpoint") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.546687   23601 reconciler.go:252] operationExecutor.MountVolume started for volume "che-workspaces" (UniqueName: "kubernetes.io/local-volume/che-workspaces") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.546726   23601 reconciler.go:252] operationExecutor.MountVolume started for volume "ssshkeyconfigvolume" (UniqueName: "kubernetes.io/configmap/c3842f38-1c3e-4506-859b-ed14d5c4f104-ssshkeyconfigvolume") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.547572   23601 operation_generator.go:697] MountVolume.MountDevice succeeded for volume "che-workspaces" (UniqueName: "kubernetes.io/local-volume/che-workspaces") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") device mount path "/che"
I0131 01:13:59.547594   23601 operation_generator.go:744] MountVolume.SetUp succeeded for volume "gitconfigvolume" (UniqueName: "kubernetes.io/configmap/c3842f38-1c3e-4506-859b-ed14d5c4f104-gitconfigvolume") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.547606   23601 operation_generator.go:744] MountVolume.SetUp succeeded for volume "ssshkeyconfigvolume" (UniqueName: "kubernetes.io/configmap/c3842f38-1c3e-4506-859b-ed14d5c4f104-ssshkeyconfigvolume") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.547609   23601 operation_generator.go:744] MountVolume.SetUp succeeded for volume "remote-endpoint" (UniqueName: "kubernetes.io/empty-dir/c3842f38-1c3e-4506-859b-ed14d5c4f104-remote-endpoint") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.550525   23601 operation_generator.go:744] MountVolume.SetUp succeeded for volume "che-workspace-token-2dswp" (UniqueName: "kubernetes.io/secret/c3842f38-1c3e-4506-859b-ed14d5c4f104-che-workspace-token-2dswp") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:13:59.550818   23601 operation_generator.go:744] MountVolume.SetUp succeeded for volume "workspace5z0n5wcridublhah-sshprivatekeys" (UniqueName: "kubernetes.io/secret/c3842f38-1c3e-4506-859b-ed14d5c4f104-workspace5z0n5wcridublhah-sshprivatekeys") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:14:00.115159   23601 kubelet.go:1946] SyncLoop (PLEG): "workspace5z0n5wcridublhah.che-jwtproxy-65db65fff6-qx8g9_che(c8cad73d-0ac9-4171-a63d-6bcdf0beaee8)", event: &pleg.PodLifecycleEvent{ID:"c8cad73d-0ac9-4171-a63d-6bcdf0beaee8", Type:"ContainerStarted", Data:"92c953a5bd075cd0bf0dccab5fa080d3a0a5a5492fe18d183b6fe4de0b802b22"}
I0131 01:14:00.152614   23601 kubelet.go:1908] SyncLoop (UPDATE, "api"): "workspace5z0n5wcridublhah.che-jwtproxy-65db65fff6-qx8g9_che(c8cad73d-0ac9-4171-a63d-6bcdf0beaee8)"
I0131 01:14:00.173232   23601 provider.go:98] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
I0131 01:14:01.320387   23601 kube_docker_client.go:345] Stop pulling image "quay.io/eclipse/che-jwtproxy:dbd0578": "Status: Image is up to date for quay.io/eclipse/che-jwtproxy:dbd0578"
I0131 01:14:02.173403   23601 kubelet.go:1946] SyncLoop (PLEG): "workspace5z0n5wcridublhah.che-jwtproxy-65db65fff6-qx8g9_che(c8cad73d-0ac9-4171-a63d-6bcdf0beaee8)", event: &pleg.PodLifecycleEvent{ID:"c8cad73d-0ac9-4171-a63d-6bcdf0beaee8", Type:"ContainerStarted", Data:"688b75bdb3e1aade168d15b535276d8c815e8d40abb56ea1a0282ad477862d29"}
I0131 01:14:08.236201   23601 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0131 01:15:54.754633   23601 operation_generator.go:744] MountVolume.SetUp succeeded for volume "che-workspaces" (UniqueName: "kubernetes.io/local-volume/che-workspaces") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:15:54.803375   23601 kuberuntime_manager.go:409] No sandbox for pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)" can be found. Need to start a new one
I0131 01:15:55.277682   23601 kubelet.go:1908] SyncLoop (UPDATE, "api"): "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)"
E0131 01:15:55.354809   23601 remote_runtime.go:295] ContainerStatus "a30cfd37777658a92ae64bf324dac9835be78abd44b7cfa17c6526df95f349bf" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: a30cfd37777658a92ae64bf324dac9835be78abd44b7cfa17c6526df95f349bf
E0131 01:15:55.354852   23601 kuberuntime_manager.go:935] getPodContainerStatuses for pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)" failed: rpc error: code = Unknown desc = Error: No such container: a30cfd37777658a92ae64bf324dac9835be78abd44b7cfa17c6526df95f349bf
I0131 01:15:56.381880   23601 kubelet.go:1946] SyncLoop (PLEG): "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)", event: &pleg.PodLifecycleEvent{ID:"c3842f38-1c3e-4506-859b-ed14d5c4f104", Type:"ContainerDied", Data:"a30cfd37777658a92ae64bf324dac9835be78abd44b7cfa17c6526df95f349bf"}
I0131 01:15:56.381997   23601 kubelet.go:1946] SyncLoop (PLEG): "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)", event: &pleg.PodLifecycleEvent{ID:"c3842f38-1c3e-4506-859b-ed14d5c4f104", Type:"ContainerStarted", Data:"9ae241d1bb8ae461f44d9dec079572cf572870531f0a624b886b1068ae70e456"}
I0131 01:15:57.453110   23601 kubelet.go:1946] SyncLoop (PLEG): "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)", event: &pleg.PodLifecycleEvent{ID:"c3842f38-1c3e-4506-859b-ed14d5c4f104", Type:"ContainerStarted", Data:"ef65c27d23e13e54f883f3295bfa937513adfca5da71a4edd12b6a39c2ae126d"}
I0131 01:15:57.453170   23601 kubelet.go:1946] SyncLoop (PLEG): "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)", event: &pleg.PodLifecycleEvent{ID:"c3842f38-1c3e-4506-859b-ed14d5c4f104", Type:"ContainerStarted", Data:"43057ee8d2e97840e32141dc4b713b4bb0b8320c565f258f69f78870aaf1069f"}
I0131 01:15:58.492686   23601 kubelet.go:1946] SyncLoop (PLEG): "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c_che(c3842f38-1c3e-4506-859b-ed14d5c4f104)", event: &pleg.PodLifecycleEvent{ID:"c3842f38-1c3e-4506-859b-ed14d5c4f104", Type:"ContainerStarted", Data:"b6bf0f616b0a3ae881af9e99e6a9861085a4f18bd6b819bbbddc2167fa281959"}
```

**Comment by davidwindell** [comment]
Could this be a clue? I've just seen hundreds of repeated entries in the Che logs of the below at the same time:

```
2020-01-31 01:11:39,861[//10.43.0.1/...]  [ERROR] [k.c.d.i.WatchConnectionManager 268]  - Invalid event type
java.lang.IllegalArgumentException: Pod event timestamp can not be blank
	at org.eclipse.che.workspace.infrastructure.kubernetes.util.PodEvents.convertEventTimestampToDate(PodEvents.java:35)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.happenedAfterWatcherInitialization(KubernetesDeployments.java:570)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.eventReceived(KubernetesDeployments.java:530)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.eventReceived(KubernetesDeployments.java:509)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:232)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by skabashnyuk** [comment]
>there is still a 2 minute gap for example when nothing at all seems to happen:

I interpret this as a slow volume "che-workspaces"  mount
```
I0131 01:13:59.546687   23601 reconciler.go:252] operationExecutor.MountVolume started for volume "che-workspaces" (UniqueName: "kubernetes.io/local-volume/che-workspaces") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
I0131 01:15:54.754633   23601 operation_generator.go:744] MountVolume.SetUp succeeded for volume "che-workspaces" (UniqueName: "kubernetes.io/local-volume/che-workspaces") pod "workspace5z0n5wcridublhah.outeredge-dev-f78d6fc66-45r8c" (UID: "c3842f38-1c3e-4506-859b-ed14d5c4f104") 
```


>I've just seen hundreds of repeated entries in the Che logs of the below at the same time:

I think it's related to your k8s version https://github.com/eclipse/che/issues/15395

**Comment by davidwindell** [comment]
I've upgraded to K8s 1.17 and am experimenting more with the EBS volume mounted directly to the node and then using local storage type - will report back when under heavy traffic next week. 

Is there any chance at all that those timestamp errors could slow down startup times though? I'm seeing hundreds of them even after upgrading to K8s 1.17.

**Comment by davidwindell** [comment]
Can confirm that switching to `local` K8's storage fixes the startup times. This is still using a mounted EBS disk however on the node itself.

That being said, we still get the `Unable to attach or mount volumes: unmounted volumes=[claim-che-workspace]...timed out waiting for the condition` _unless_ we have a random alpine POD mounting the volume on the same node. I have no idea why though, it feels to me like Che is doing something with attaching storage that isn't working.

**Comment by amisevsk** [comment]
This is starting to go beyond my knowledge of kubernetes, but Che, as far as I know, is just using the k8s API to 
1. Create PVCs if they do not exist
2. Create deployments with volumes included as normal, via the java [kubernetes-client](https://github.com/fabric8io/kubernetes-client). 

The only thing I can think of is contention for the volume, since I believe EBS volumes are RWO.

**Comment by davidwindell** [comment]
Shall I close this for now? I'm happy with the workaround of having a pod hanging around with a simple mound of the che-workspaces volume. 

Could you put some weight behind #15395? It would be great to get the library updated in case it helps.
