### ISSUE TITLE
minishift/CRC fail to start workspace created with namespace.default=<workspaceid>-che

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15780]
### Describe the bug
CRC/Minishift: Unable to start workspace for che configured with env:

```
che.infra.kubernetes.namespace.default=<workspaceid>-che
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy multiuser che using helm. (Because che-operator not ready yet) with configured `che.infra.kubernetes.namespace.default=<workspaceid>-che`
2. Create new workspace from stack
3. Try to launch workspace

### Expected behavior
workspace should start.

### Actual behavior
Workspace fail to start. 
<details>

<summary>Che server logs:</summary>

```
2020-01-22 09:06:38,610[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 469]   - Starting workspace 'admin/golang-eji08' with id 'workspacefmxp59t67nkrylnt' by user 'admin'
--
  | 2020-01-22 09:06:38,771[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 252]  - Failed to start Kubernetes runtime of workspace workspacefmxp59t67nkrylnt. Cause: Failure executing: PUT at: https://172.30.0.1/apis/project.openshift.io/v1/projects/workspacefmxp59t67nkrylnt-che . Message: Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels[che-managed], message=Invalid value: "true": field is immutable, , try updating the namespace, reason=FieldValueInvalid, additionalProperties={})], group=project.openshift.io, kind=Project, name=workspacefmxp59t67nkrylnt-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | 2020-01-22 09:06:39,295[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 897]   - Workspace 'admin:golang-eji08' with id 'workspacefmxp59t67nkrylnt' start failed
  | 2020-01-22 09:36:53,968[nio-8080-exec-3]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 484]   - Failure executing: PUT at: https://172.30.0.1/apis/project.openshift.io/v1/projects/workspacefmxp59t67nkrylnt-che . Message: Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels[che-managed], message=Invalid value: "true": field is immutable, , try updating the namespace, reason=FieldValueInvalid, additionalProperties={})], group=project.openshift.io, kind=Project, name=workspacefmxp59t67nkrylnt-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Failure executing: PUT at: https://172.30.0.1/apis/project.openshift.io/v1/projects/workspacefmxp59t67nkrylnt-che . Message: Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels[che-managed], message=Invalid value: "true": field is immutable, , try updating the namespace, reason=FieldValueInvalid, additionalProperties={})], group=project.openshift.io, kind=Project, name=workspacefmxp59t67nkrylnt-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.update(OpenShiftProject.java:193)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.prepare(OpenShiftProject.java:120)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProjectFactory.getOrCreate(OpenShiftProjectFactory.java:86)
  | at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftRuntimeContext.getRuntime(OpenShiftRuntimeContext.java:69)
  | at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftRuntimeContext.getRuntime(OpenShiftRuntimeContext.java:31)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startAsync(WorkspaceRuntimes.java:456)
  | at org.eclipse.che.api.workspace.server.WorkspaceManager.startAsync(WorkspaceManager.java:465)
  | at org.eclipse.che.api.workspace.server.WorkspaceManager.startWorkspace(WorkspaceManager.java:373)
  | at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager.startWorkspace(LimitsCheckingWorkspaceManager.java:132)
  | at org.eclipse.che.api.workspace.server.WorkspaceService.startById(WorkspaceService.java:454)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
  | at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
  | at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
  | at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
  | at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
  | at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
  | at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
  | at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
  | at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
  | at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
  | at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:49)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:125)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter.doFilter(KeycloakEnvironmentInitializationFilter.java:88)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:76)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.30.0.1/apis/project.openshift.io/v1/projects/workspacefmxp59t67nkrylnt-che . Message: Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels[che-managed], message=Invalid value: "true": field is immutable, , try updating the namespace, reason=FieldValueInvalid, additionalProperties={})], group=project.openshift.io, kind=Project, name=workspacefmxp59t67nkrylnt-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:415)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:261)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:243)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:785)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:109)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:104)
  | at io.fabric8.openshift.api.model.DoneableProject.done(DoneableProject.java:27)
  | at io.fabric8.openshift.api.model.DoneableProject.done(DoneableProject.java:6)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:116)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:37)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:420)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:415)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.update(OpenShiftProject.java:186)
  | ... 58 common frames omitted
  | 2020-01-22 10:07:54,202[nio-8080-exec-9]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 484]   - Failure executing: PUT at: https://172.30.0.1/apis/project.openshift.io/v1/projects/workspacefmxp59t67nkrylnt-che . Message: Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels[che-managed], message=Invalid value: "true": field is immutable, , try updating the namespace, reason=FieldValueInvalid, additionalProperties={})], group=project.openshift.io, kind=Project, name=workspacefmxp59t67nkrylnt-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Failure executing: PUT at: https://172.30.0.1/apis/project.openshift.io/v1/projects/workspacefmxp59t67nkrylnt-che . Message: Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels[che-managed], message=Invalid value: "true": field is immutable, , try updating the namespace, reason=FieldValueInvalid, additionalProperties={})], group=project.openshift.io, kind=Project, name=workspacefmxp59t67nkrylnt-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.update(OpenShiftProject.java:193)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.prepare(OpenShiftProject.java:120)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProjectFactory.getOrCreate(OpenShiftProjectFactory.java:86)
  | at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftRuntimeContext.getRuntime(OpenShiftRuntimeContext.java:69)
  | at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftRuntimeContext.getRuntime(OpenShiftRuntimeContext.java:31)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startAsync(WorkspaceRuntimes.java:456)
  | at org.eclipse.che.api.workspace.server.WorkspaceManager.startAsync(WorkspaceManager.java:465)
  | at org.eclipse.che.api.workspace.server.WorkspaceManager.startWorkspace(WorkspaceManager.java:373)
  | at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager.startWorkspace(LimitsCheckingWorkspaceManager.java:132)
  | at org.eclipse.che.api.workspace.server.WorkspaceService.startById(WorkspaceService.java:454)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
  | at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
  | at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
  | at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
  | at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
  | at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
  | at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
  | at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
  | at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
  | at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
  | at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
  | at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
  | at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:49)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:125)
  | at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter.doFilter(KeycloakEnvironmentInitializationFilter.java:88)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:76)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
  | at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
  | at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
  | at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.30.0.1/apis/project.openshift.io/v1/projects/workspacefmxp59t67nkrylnt-che . Message: Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels[che-managed], message=Invalid value: "true": field is immutable, , try updating the namespace, reason=FieldValueInvalid, additionalProperties={})], group=project.openshift.io, kind=Project, name=workspacefmxp59t67nkrylnt-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Project.project.openshift.io "workspacefmxp59t67nkrylnt-che" is invalid: metadata.labels[che-managed]: Invalid value: "true": field is immutable, , try updating the namespace, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:415)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:261)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:243)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:785)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:109)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:104)
  | at io.fabric8.openshift.api.model.DoneableProject.done(DoneableProject.java:27)
  | at io.fabric8.openshift.api.model.DoneableProject.done(DoneableProject.java:6)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:116)
  | at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:37)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:420)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:415)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.update(OpenShiftProject.java:186)
  | ... 58 common frames omitted
```

</details>

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by AndrienkoAleksandr** [comment]
I reproduced the same issue with CRC.

**Comment by skabashnyuk** [comment]
@AndrienkoAleksandr is this issue reproduced with che-operator?

**Comment by AndrienkoAleksandr** [comment]
Yes, with changes: https://github.com/eclipse/che-operator/pull/156

**Comment by tolusha** [comment]
The PR https://github.com/eclipse/che-operator/pull/156/ is closed. The issue isn't relevant.
