### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: update or delete on table "che_k8s_runtime"

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15800]
### Describe the bug
DB error in logs
```
org.eclipse.che.api.workspace.server.spi.InfrastructureException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "che_k8s_runtime" violates foreign key constraint "fk_k8s_runtime_workspace_id" on table "k8s_runtime_command"
  Detail: Key (workspace_id)=(workspaceid) is still referenced from table "k8s_runtime_command".
Error Code: 0
Call: DELETE FROM che_k8s_runtime WHERE (workspace_id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(KubernetesRuntimeState{workspaceId='workspaceid', envName='default', ownerId='userid', namespace='usernamespace-che', status=STOPPING})
	at org.eclipse.che.workspace.infrastructure.kubernetes.cache.jpa.JpaKubernetesRuntimeStateCache.remove(JpaKubernetesRuntimeStateCache.java:167)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.markStopped(KubernetesInternalRuntime.java:768)
	at org.eclipse.che.workspace.infrastructure.kubernetes.RuntimeHangingDetector.handleHangingStoppingRuntime(RuntimeHangingDetector.java:158)
	at org.eclipse.che.workspace.infrastructure.kubernetes.RuntimeHangingDetector$WaitStatusChangedTask.lambda$run$0(RuntimeHangingDetector.java:223)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.core.db.jpa.IntegrityConstraintViolationException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "che_k8s_runtime" violates foreign key constraint "fk_k8s_runtime_workspace_id" on table "k8s_runtime_command"
  Detail: Key (workspace_id)=(workspaceid) is still referenced from table "k8s_runtime_command".
Error Code: 0
Call: DELETE FROM che_k8s_runtime WHERE (workspace_id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(KubernetesRuntimeState{workspaceId='workspaceid', envName='default', ownerId='userid', namespace='usernamespace-che', status=STOPPING})
	at org.eclipse.che.core.db.postgresql.jpa.eclipselink.PostgreSqlExceptionHandler.handleException(PostgreSqlExceptionHandler.java:36)
	at org.eclipse.persistence.internal.sessions.AbstractSession.handleException(AbstractSession.java:3261)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1944)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830)
	at org.eclipse.persistence.internal.sessions.CommitManager.deleteAllObjects(CommitManager.java:344)
	at org.eclipse.persistence.internal.sessions.CommitManager.deleteAllObjects(CommitManager.java:298)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1498)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1585)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:280)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1222)
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:136)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:85)
	at org.eclipse.che.workspace.infrastructure.kubernetes.cache.jpa.JpaKubernetesRuntimeStateCache.remove(JpaKubernetesRuntimeStateCache.java:165)
	... 9 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "che_k8s_runtime" violates foreign key constraint "fk_k8s_runtime_workspace_id" on table "k8s_runtime_command"
  Detail: Key (workspace_id)=(workspaceid) is still referenced from table "k8s_runtime_command".
Error Code: 0
Call: DELETE FROM che_k8s_runtime WHERE (workspace_id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(KubernetesRuntimeState{workspaceId='workspaceid', envName='default', ownerId='userid', namespace='usernamespace-che', status=STOPPING})
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1650)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:906)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:970)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:640)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:313)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.deleteObject(DatasourceCallQueryMechanism.java:243)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.deleteObject(StatementQueryMechanism.java:106)
	at org.eclipse.persistence.queries.DeleteObjectQuery.executeDatabaseQuery(DeleteObjectQuery.java:220)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:810)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:110)
	at org.eclipse.persistence.queries.DeleteObjectQuery.executeInUnitOfWorkObjectLevelModifyQuery(DeleteObjectQuery.java:121)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:87)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
	... 20 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "che_k8s_runtime" violates foreign key constraint "fk_k8s_runtime_workspace_id" on table "k8s_runtime_command"
  Detail: Key (workspace_id)=(workspaceid) is still referenced from table "k8s_runtime_command".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:121)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:121)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
	... 37 common frames omitted
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other:  7.7.1b

### Steps to reproduce

unknown

### Expected behavior
 no errors
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
n/a

**Comment by tsmaeder** [comment]
Does this have any impact on Che behaviour?

**Comment by skabashnyuk** [comment]
@tsmaeder hard to say for sure.
