### ISSUE TITLE
How can I expose a port to public and enable external java websocket client (that sits in a local pc) communication

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#16014]
(Please refer to https://github.com/eclipse/che/issues/15897)
Within a che workspace pod, I have a dedicated container with exposed port to enable communication with external apps that can use its service. Thank you all for help ! I was able to get the public url as http... (when i set protocol: 'http' for the endpoint) and open it in a browser and it worked !

I changed the implementation of the server app in the container and the endpoint type to websocket.
The devfile yaml portion for this container is:
```
-  
    type: dockerimage
    alias: dedicated-container
    image: 879521958254.dkr.ecr.us-east-1.amazonaws.com/dedicated-container-image2:latest
    memoryLimit: 1024Mi
    endpoints:
      - name: 'helloworld'
        port: 6000
        attributes:
           secure: 'false'
           protocol: ws
    mountSources: true 
```

when I try to use the endpoint protocol type as websocket (protocol: 'ws' & secure: 'false'), I get an url like this:
```
"servers": {
          "helloworld": {
            "url": "wss://server2q809nz0-dedicated-container-server-6000.mydomain.com/",
            "attributes": {
              "secure": "false",
              "port": "6000"
            },
            "status": "UNKNOWN"
          }
        }
```

<details>
  <summary>Here is the java websocket client</summary>

```

	WebSocketClient simpleWebSocketClient =
	    new StandardWebSocketClient();
	List<Transport> transports = new ArrayList<>(1);
	transports.add(new WebSocketTransport(simpleWebSocketClient));

	SockJsClient sockJsClient = new SockJsClient(transports);
	WebSocketStompClient stompClient =
	    new WebSocketStompClient(sockJsClient);
	stompClient.setMessageConverter(new MappingJackson2MessageConverter());

	String url = "wss://server2q809nz0-dedicated-container-server-6000.mydomain.com/chat/";
	String userId = "spring-" + ThreadLocalRandom.current().nextInt(1, 99);
	StompSessionHandler sessionHandler = new MyStompSessionHandler(userId);
	
	final WebSocketHttpHeaders headers = new WebSocketHttpHeaders();
	headers.add("Authorization", "Bearer <<machine token here>>");
	
	StompSession session = stompClient.connect(url, headers, sessionHandler).get();
```
</details>

I get an exception in the call stompClient.connect().
<details>
  <summary>Exception Log:</summary>

```

00:25:00.891 [main] DEBUG org.springframework.web.socket.sockjs.client.RestTemplateXhrTransport - Executing SockJS Info request, url=https://server2q809nz0-dedicated-container-server-6000.mydomain.com/chat/info
00:25:04.590 [main] DEBUG org.springframework.web.client.RestTemplate - Created GET request for "https://server2q809nz0-dedicated-container-server-6000.mydomain.com/chat/info"
00:25:08.534 [main] DEBUG org.springframework.web.client.RestTemplate - GET request for "https://server2q809nz0-dedicated-container-server-6000.mydomain.com/chat/info" resulted in 200 (null)
00:25:08.563 [main] DEBUG org.springframework.web.socket.sockjs.client.WebSocketTransport - Starting WebSocket session url=wss://server2q809nz0-dedicated-container-server-6000.mydomain.com/chat/921/0fc9bec2e7b34b798d7b7492f0477120/websocket
00:25:08.563 [main] DEBUG org.springframework.web.socket.client.standard.StandardWebSocketClient - Connecting to wss://server2q809nz0-dedicated-container-server-6000.mydomain.com/chat/921/0fc9bec2e7b34b798d7b7492f0477120/websocket
00:25:09.233 [SimpleAsyncTaskExecutor-1] ERROR org.springframework.web.socket.sockjs.client.DefaultTransportRequest - No more fallback transports after TransportRequest[url=wss://server2q809nz0-dedicated-container-server-6000.mydomain.com/chat/921/0fc9bec2e7b34b798d7b7492f0477120/websocket]
javax.websocket.DeploymentException: The HTTP request to initiate the WebSocket connection failed
	at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:392)
	at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:150)
	at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.get(AsyncChannelWrapperSecure.java:510)
	at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:336)
	... 4 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WebSocketSslHandshakeThread.run(AsyncChannelWrapperSecure.java:371)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WebSocketSslHandshakeThread.run(AsyncChannelWrapperSecure.java:397)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:289)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
	... 7 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
	... 13 common frames omitted
00:25:09.234 [SimpleAsyncTaskExecutor-1] DEBUG org.springframework.messaging.simp.stomp.DefaultStompSession - Failed to connect session id=dc74d342-7db9-166c-faa5-7d24561dd0d5
javax.websocket.DeploymentException: The HTTP request to initiate the WebSocket connection failed
	at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:392)
	at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:150)
	at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.get(AsyncChannelWrapperSecure.java:510)
	at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:336)
	... 4 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WebSocketSslHandshakeThread.run(AsyncChannelWrapperSecure.java:371)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WebSocketSslHandshakeThread.run(AsyncChannelWrapperSecure.java:397)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:289)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
	... 7 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
	... 13 common frames omitted

```
</details>

I believe that I'm missing some authentication procedure (in addition to using the machine token) or cookies ?

**Comment by svkr2k** [comment]
In chrome debugger tool, when i typed this in console:
`ws = new WebSocket("wss://server2v4p7rik-dedicated-container-server-6000.mydomain.com/chat");`
i got the error:
`VM313:1 WebSocket connection to 'wss://server2v4p7rik-dedicated-container-server-6000.mydomain.com/chat' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`

**Comment by tsmaeder** [comment]
I added label "wsmaster" as it seems related to how our workspaces translate to pods. I think we're missing an "area" label.

**Comment by skabashnyuk** [comment]
@svkr2k hello. Can you keep `protocol: http` and try to connect with WebSocket?

**Comment by svkr2k** [comment]
In the client side, I'm using StandardWebSocketClient. While handshaking, it is trying to extract port number from the URL, but container's public url doesnt have port number at the end:
```
	private int getPort(URI uri) {
		if (uri.getPort() == -1) {
	        String scheme = uri.getScheme().toLowerCase(Locale.ENGLISH);
	        return ("wss".equals(scheme) ? 443 : 80);
		}
		return uri.getPort();
	}
```

**Comment by svkr2k** [comment]
Finally, i was able to establish communication between the server (running within a workspace) and a client running in local pc. the following were the issues that were addressed:
1. Used a dedicated container in workspace ("dockerimage" type) that exposed port 443 as websocket server
2. Added all necessary certificates (domain name certificate, issuing authotiry certificate, ingress controller certificate) to the keystore on the client side.

**Comment by svkr2k** [comment]
Hi @skabashnyuk , all.

After configuring the devfile as shown above, I was able to see that the link `wss://server2v4p7rik-dedicated-container-server-443.mydomain.com/`available and was able to connect using a websocker client ! Thank you all for the support.

The issue I'm facing regarding this is that the websocket communication gets disconnected after approximately 15 minutes, after which i'm no longer able to communicate with it.
So, i had to kill the workspace and recreate it and connect to the websocket url again to perform my tests.

Can you guide me to solve this issue ?
