### ISSUE TITLE
E2E happy path tests fail on 'Build application' step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16125]
### Describe the bug
E2E Happy path tests failed being run against Multiuser Eclipse Che on minikube 1.1.1:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/2163/console
```
  Validation of workspace build and run
        ▼ TopMenu.selectOption "Terminal"
        ▼ TopMenu.clickOnTopMenuButton "Terminal"
        ▼ Ide.closeAllNotifications
        ▼ NotificationCenter.open
        ▼ NotificationCenter.clickIconOnStatusBar
        ▼ NotificationCenter.waitOpening
        ▼ NotificationCenter.closeAll
        ▼ NotificationCenter.clickCloseAllNotificationsButton
        ▼ NotificationCenter.waitClearNotificationsList
        ▼ TopMenu.clickOnSubmenuItem "Run Task..."
        ▼ QuickOpenContainer.waitContainer
        ▼ QuickOpenContainer.clickOnContainerItem "build-file-output"
        ▼ QuickOpenContainer.waitContainer
        ▼ QuickOpenContainer.waitContainerDisappearance
        ▼ QuickOpenContainer.clickOnContainerItem "Continue without scanning the task output"
        ▼ QuickOpenContainer.waitContainer
        ▼ QuickOpenContainer.waitContainerDisappearance
        ▼ ProjectTree.expandPathAndOpenFile "petclinic" filename: result-build-output.txt
        ▼ ProjectTree.expandPath "petclinic"
        ▼ ProjectTree.expandItem "petclinic"
        ▼ ProjectTree.waitItemExpanded "petclinic"
        ▼ ProjectTree.clickOnItem "petclinic/result-build-output.txt"
    1) Build application


  8 passing (8m)
  1 pending
  1 failing

  1) Validation of workspace build and run
       Build application:
     TimeoutError: Waiting for element to be located By(css selector, div[id='/projects:/projects/petclinic/result-build-output.txt'])
Wait timed out after 220017ms
```
Che-theia container error:
```
root ERROR Failed to create terminal widget. Cause:  Error: No matching bindings found for serviceIdentifier: Symbol(TerminalSearchWidgetFactory)
    at http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:53:54922
    at _ (http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:53:55219)
    at e (http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:53:55798)
    at http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:53:56332
    at Array.forEach (<anonymous>)
    at http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:53:56311
    at Array.forEach (<anonymous>)
    at e (http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:53:55858)
    at Object.UvhB.t.plan (http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:53:56373)
    at http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/vendors.0f7ca0f7f4c382c00635.js:8:559902
root ERROR [hosted-plugin: 48] Promise rejection not handled in one second: Error: Failed to create terminal. Cause: Error: Unable to create new terminal for machine: maven-container , reason: Error: Failed to create terminal. Cause: Error: Unable to create new terminal for machine: maven-container
With stack trace: Error: Failed to create terminal. Cause: Error: Unable to create new terminal for machine: maven-container
    at e.<anonymous> (http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/theia.fce0fbff7c747edc3de8.js:1:1908433)
    at http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/theia.fce0fbff7c747edc3de8.js:1:1906079
    at Object.throw (http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/theia.fce0fbff7c747edc3de8.js:1:1906184)
    at s (http://serveru2zofz1z-jwtproxy-webviews.10.0.101.111.nip.io/theia.fce0fbff7c747edc3de8.js:1:1904978)
```

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: from [PR](https://github.com/eclipse/che/pull/16006)

### Steps to reproduce
https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Reference
https://github.com/eclipse-theia/theia/pull/5471

### Screenshots
![screenshot-Build_application (2)](https://user-images.githubusercontent.com/1197777/75240205-a5831e80-57cc-11ea-98a3-6ebfc9394763.png)

### Screencast
https://youtu.be/MFowugpVv5E

### Installation method
   - [x] chectl:next with operator installer
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

### Additional context
[Happy path nightly tests passed successfully ](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/980/).

**Comment by AndrienkoAleksandr** [comment]
https://github.com/eclipse/che-theia/pull/635

**Comment by RomanNikitenko** [comment]
The fix https://github.com/eclipse/che-theia/pull/635 was merged.

**Comment by AndrienkoAleksandr** [comment]
@dmytro-ndp , reopen please, I issue is still actual
