### ISSUE TITLE
 Can't create machine from snapshot.

### ISSUE THREAD

**Issue by lhwong** [eclipse-che/che#1612]
Hi,

I created a workspace with custom stack by writting my own stack in the textarea.
Stop the che server
Start the che server
Upon clicking on Run button to start a workspace created above, I got the following error:  Can't create machine from snapshot.

Version 4.3.4 on Windows

I use default properties
machine.docker.snapshot_use_registry=false
workspace.runtime.auto_snapshot=true
workspace.runtime.auto_restore=true

Detail trace:
###### 

On Windows, Che projects can only reside in %userprofile% due
to limitations of Docker. On this computer, %userprofile% is
C:\Users\User
###### 

Docker machine named che already exists...
Setting environment variables for machine che...
Docker is configured to use docker-machine named che with IP 192.168.99.100...
###### ######## HOW TO CONNECT YOUR CHE CLIENT

After Che server has booted, you can connect your clients by:
1. Open browser to http://192.168.99.100:8080, or:
2. Open native chromium app.
###### 

Using CATALINA_BASE:   /C/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat
Using CATALINA_HOME:   /C/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat
Using CATALINA_TMPDIR: /C/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/temp
Using JRE_HOME:        /C/Java/jdk1.8.0_73
Using CLASSPATH:       /C/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/conf/:/C/Java/jdk1.8.0_73/lib/tools.jar:/C/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/bin/bootstrap.jar:/C/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/bin/tomcat-juli.jar
2016-06-30 11:13:25,342[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32
2016-06-30 11:13:25,345[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC
2016-06-30 11:13:25,346[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0
2016-06-30 11:13:25,346[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Windows 10
2016-06-30 11:13:25,347[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            10.0
2016-06-30 11:13:25,350[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2016-06-30 11:13:25,351[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             C:\Java\jdk1.8.0_73\jre
2016-06-30 11:13:25,355[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_73-b02
2016-06-30 11:13:25,356[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2016-06-30 11:13:25,359[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat
2016-06-30 11:13:25,360[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat
2016-06-30 11:13:25,363[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/conf/logging.properties
2016-06-30 11:13:25,365[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2016-06-30 11:13:25,366[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
2016-06-30 11:13:25,369[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
2016-06-30 11:13:25,370[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
2016-06-30 11:13:25,373[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2016-06-30 11:13:25,375[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4
2016-06-30 11:13:25,377[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/logs/
2016-06-30 11:13:25,380[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2016-06-30 11:13:25,382[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2016-06-30 11:13:25,384[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2016-06-30 11:13:25,386[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2016-06-30 11:13:25,388[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/conf/
2016-06-30 11:13:25,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/endorsed
2016-06-30 11:13:25,391[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat
2016-06-30 11:13:25,392[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat
2016-06-30 11:13:25,396[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=C:/Users/User/AppData/Local/Programs/ECLIPS~1/ECLIPS~1.4/tomcat/temp
2016-06-30 11:13:25,568[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-8080"]
2016-06-30 11:13:25,660[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2016-06-30 11:13:25,664[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 658 ms
2016-06-30 11:13:25,729[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
2016-06-30 11:13:25,731[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
2016-06-30 11:13:25,732[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32
2016-06-30 11:13:25,803[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\dashboard.war
2016-06-30 11:13:26,430[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\dashboard.war has finished in 622 ms
2016-06-30 11:13:26,434[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\ide.war
2016-06-30 11:13:26,759[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\ide.war has finished in 325 ms
2016-06-30 11:13:26,761[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\swagger.war
2016-06-30 11:13:26,908[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\swagger.war has finished in 147 ms
2016-06-30 11:13:26,914[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\wsmaster.war
2016-06-30 11:13:31,171[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
2016-06-30 11:13:33,554[ost-startStop-1]  [INFO ] [.c.p.d.c.DockerRegistryChecker 43]   - Probing registry 'http://localhost:5000'
2016-06-30 11:13:34,559[ost-startStop-1]  [WARN ] [.c.p.d.c.DockerRegistryChecker 50]   - Docker registry http://localhost:5000 is not available, which means that you won't be able to save snapshots of your workspaces.
How to configure registry?
        Local registry  -> https://docs.docker.com/registry/
        Remote registry -> set up 'docker.registry.auth.*' properties
2016-06-30 11:13:34,914[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\wsmaster.war has finished in 8,000 ms
2016-06-30 11:13:34,917[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\ROOT
2016-06-30 11:13:35,033[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory C:\Users\User\AppData\Local\Programs\Eclipse Che\eclipse-che-4.3.4\tomcat\webapps\ROOT has finished in 116 ms
2016-06-30 11:13:35,038[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-8080"]
2016-06-30 11:13:35,050[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 9384 ms
2016-06-30 11:13:57,637[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 205]      - Recovering machine [ws = workspacekfax3mcm4rraw8t6: env = kie-server: machine = ws-machine] from snapshot
2016-06-30 11:13:57,703[kspaceManager-0]  [ERROR] [c.p.d.m.DockerInstanceProvider 327]  - Error response from docker API, status: 404, message: no such id: o5sr1u69sr4jihfz:latest

org.eclipse.che.plugin.docker.client.DockerException: Error response from docker API, status: 404, message: no such id: o5sr1u69sr4jihfz:latest

```
    at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1686) ~[che-plugin-docker-client-4.3.4.jar:4.3.4]
    at org.eclipse.che.plugin.docker.client.DockerConnector.tag(DockerConnector.java:1270) ~[che-plugin-docker-client-4.3.4.jar:4.3.4]
    at org.eclipse.che.plugin.docker.client.DockerConnector.tag(DockerConnector.java:1258) ~[che-plugin-docker-client-4.3.4.jar:4.3.4]
    at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstanceFromImage(DockerInstanceProvider.java:325) [che-plugin-docker-machine-4.3.4.jar:4.3.4]
    at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:295) [che-plugin-docker-machine-4.3.4.jar:4.3.4]
    at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:358) [che-core-api-machine-4.3.4.jar:4.3.4]
    at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:334) [che-core-api-machine-4.3.4.jar:4.3.4]
    at org.eclipse.che.api.machine.server.MachineManager.recoverMachine(MachineManager.java:206) [che-core-api-machine-4.3.4.jar:4.3.4]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:580) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:533) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.3.4.jar:4.3.4]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
```

2016-06-30 11:13:57,711[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 549]    - Can't create machine from snapshot.
org.eclipse.che.api.machine.server.exception.MachineException: Can't create machine from snapshot.
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:395) ~[che-core-api-machine-4.3.4.jar:4.3.4]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:334) ~[che-core-api-machine-4.3.4.jar:4.3.4]
        at org.eclipse.che.api.machine.server.MachineManager.recoverMachine(MachineManager.java:206) ~[che-core-api-machine-4.3.4.jar:4.3.4]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:580) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:533) ~[che-core-api-workspace-4.3.4.jar:4.3.4]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.3.4.jar:4.3.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Can't create machine from snapshot.
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstanceFromImage(DockerInstanceProvider.java:328) ~[che-plugin-docker-machine-4.3.4.jar:4.3.4]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:295) ~[che-plugin-docker-machine-4.3.4.jar:4.3.4]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:358) ~[che-core-api-machine-4.3.4.jar:4.3.4]
        ... 10 common frames omitted

**Comment by TylerJewell** [comment]
@garagtyi

**Comment by lhwong** [comment]
If I don't stop eclipse che server, restoring of snapshot works fine after restarting the workspace (see log below). If I stop the eclipse che and then start it up and run the workspace I got the error message in previous message.

2016-06-30 12:21:03,100[kspaceManager-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 566]    - Workspace 'che:kie-server' with id 'workspacer28wbno2vqbtdsfj' is being stopped by user 'che'
2016-06-30 12:21:03,102[kspaceManager-6]  [INFO ] [o.e.c.a.m.s.MachineManager 799]      - Creating snapshot of machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine name = ws-machine: machine id = machinevpjifzuj8ugreih3]
2016-06-30 12:21:08,878[kspaceManager-6]  [INFO ] [o.e.c.a.m.s.MachineManager 823]      - Snapshot of machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine name = ws-machine: machine id = machinevpjifzuj8ugreih3] was successfully created, its id is 'snapshot54705zyq55qmhyzk'
2016-06-30 12:21:08,880[kspaceManager-6]  [INFO ] [o.e.c.a.m.s.MachineManager 845]      - Destroying machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine name = ws-machine: machine id = machinevpjifzuj8ugreih3]
2016-06-30 12:21:09,572[kspaceManager-6]  [INFO ] [o.e.c.a.m.s.MachineManager 857]      - Machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine name = ws-machine: machine id = machinevpjifzuj8ugreih3] was successfully destroyed
2016-06-30 12:21:09,573[kspaceManager-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 585]    - Workspace 'che:kie-server' with id 'workspacer28wbno2vqbtdsfj' stopped by user 'che'
2016-06-30 12:21:31,676[kspaceManager-6]  [INFO ] [o.e.c.a.m.s.MachineManager 205]      - Recovering machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine = ws-machine] from snapshot
2016-06-30 12:21:32,396[kspaceManager-6]  [INFO ] [c.p.d.m.DockerInstanceProvider 562]  - Machine with id 'machinel372f3xpzlwpfhuo' backed by container '6fe15bef5096b9302a3969e4c3da2f5423db053d4092fc585f985d9f20998265' has been deployed on node '192.168.99.100'
2016-06-30 12:22:02,504[kspaceManager-6]  [INFO ] [o.e.c.a.m.s.MachineManager 211]      - Machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine = ws-machine] was successfully recovered, its id 'machinel372f3xpzlwpfhuo'
2016-06-30 12:22:02,506[kspaceManager-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 534]    - Workspace 'che:kie-server' with id 'workspacer28wbno2vqbtdsfj' started by user 'che'
2016-06-30 12:22:30,369[nio-8080-exec-1]  [WARN ] [o.e.c.p.d.m.DockerInstance 183]      - Machine process 1 exists in container but missing in processes map
2016-06-30 12:22:30,371[nio-8080-exec-1]  [WARN ] [o.e.c.p.d.m.DockerInstance 183]      - Machine process 3 exists in container but missing in processes map
2016-06-30 12:23:39,241[main]             [INFO ] [o.a.c.core.StandardServer 502]       - A valid shutdown command was received via the shutdown port. Stopping the Server instance.
2016-06-30 12:23:39,243[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 485]  - Pausing ProtocolHandler ["http-nio-8080"]
2016-06-30 12:23:39,297[main]             [INFO ] [o.a.c.core.StandardService 496]      - Stopping service Catalina
2016-06-30 12:23:39,518[estroyMachine-0]  [INFO ] [o.e.c.a.m.s.MachineManager 845]      - Destroying machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine name = ws-machine: machine id = machinel372f3xpzlwpfhuo]
2016-06-30 12:23:40,343[estroyMachine-0]  [INFO ] [o.e.c.a.m.s.MachineManager 857]      - Machine [ws = workspacer28wbno2vqbtdsfj: env = kie-server: machine name = ws-machine: machine id = machinel372f3xpzlwpfhuo] was successfully destroyed
2016-06-30 12:23:40,357[ost-startStop-2]  [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-06-30 12:23:40,381[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 514]  - Stopping ProtocolHandler ["http-nio-8080"]
2016-06-30 12:23:40,437[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 529]  - Destroying ProtocolHandler ["http-nio-8080"]

**Comment by garagatyi** [comment]
@akorneta

**Comment by ghost** [comment]
This commit fixes it - https://github.com/eclipse/che/commit/ec461af679cd9d4f62f089fc2dda6ce7a7251455

You may want to try a nightly build to verify the error's gone. I cannot reproduce it with the latest master.

**Comment by lhwong** [comment]
Works on nightly build eclipse-che-4.5.0-RC1-SNAPSHOT

Thank you very much!

**Comment by lhwong** [comment]
Failed intermittently. 

2016-06-30 17:06:52,689[kspaceManager-0]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 552]    - Workspace 'che:kie-server' with id 'workspacebarim0iv6ixmsosm' started by user 'che'
2016-06-30 17:14:24,717[kspaceManager-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 584]    - Workspace 'che:kie-server' with id 'workspacebarim0iv6ixmsosm' is being stopped by user 'che'
2016-06-30 17:14:24,724[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 817]      - Creating snapshot of machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine name = ws-machine: machine id = machine5w52du544ephjjtl]
2016-06-30 17:14:28,957[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 841]      - Snapshot of machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine name = ws-machine: machine id = machine5w52du544ephjjtl] was successfully created, its id is 'snapshotpjsqxk9muhhc0d06'
2016-06-30 17:14:28,959[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 863]      - Destroying machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine name = ws-machine: machine id = machine5w52du544ephjjtl]
2016-06-30 17:14:29,641[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 875]      - Machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine name = ws-machine: machine id = machine5w52du544ephjjtl] was successfully destroyed
2016-06-30 17:14:29,642[kspaceManager-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 603]    - Workspace 'che:kie-server' with id 'workspacebarim0iv6ixmsosm' stopped by user 'che'
2016-06-30 17:14:45,941[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 207]      - Recovering machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine = ws-machine] from snapshot
2016-06-30 17:14:46,752[kspaceManager-1]  [INFO ] [c.p.d.m.DockerInstanceProvider 578]  - Machine with id 'machinebhq39ugetbtdyz45' backed by container '29eef80f98c7163926965b53e246c758bcadfbff64eb332da50ed29cf69ee276' has been deployed on node '192.168.99.100'
2016-06-30 17:15:16,853[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 213]      - Machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine = ws-machine] was successfully recovered, its id 'machinebhq39ugetbtdyz45'
2016-06-30 17:15:16,857[kspaceManager-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 552]    - Workspace 'che:kie-server' with id 'workspacebarim0iv6ixmsosm' started by user 'che'
2016-06-30 17:15:23,060[nio-8080-exec-7]  [WARN ] [o.e.c.p.d.m.DockerInstance 181]      - Machine process 1 exists in container but missing in processes map
2016-06-30 17:15:52,778[main]             [INFO ] [o.a.c.core.StandardServer 502]       - A valid shutdown command was received via the shutdown port. Stopping the Server instance.
2016-06-30 17:15:52,779[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 485]  - Pausing ProtocolHandler ["http-nio-8080"]
2016-06-30 17:15:52,833[main]             [INFO ] [o.a.c.core.StandardService 496]      - Stopping service Catalina
2016-06-30 17:15:52,880[ost-startStop-2]  [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-06-30 17:15:52,887[estroyMachine-0]  [INFO ] [o.e.c.a.m.s.MachineManager 863]      - Destroying machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine name = ws-machine: machine id = machinebhq39ugetbtdyz45]
2016-06-30 17:15:53,626[estroyMachine-0]  [INFO ] [o.e.c.a.m.s.MachineManager 875]      - Machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine name = ws-machine: machine id = machinebhq39ugetbtdyz45] was successfully destroyed
2016-06-30 17:15:53,769[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 514]  - Stopping ProtocolHandler ["http-nio-8080"]
2016-06-30 17:15:53,780[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 529]  - Destroying ProtocolHandler ["http-nio-8080"]

**Upon starting up**

2016-06-30 17:16:35,032[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 9467 ms
2016-06-30 17:16:38,062[nio-8080-exec-1]  [WARN ] [i.ContainerResponse$BodyWriter 90]   - Client has aborted connection. Response writing omitted.
2016-06-30 17:16:47,735[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 207]      - Recovering machine [ws = workspacebarim0iv6ixmsosm: env = kie-server: machine = ws-machine] from snapshot
2016-06-30 17:16:47,793[kspaceManager-0]  [ERROR] [o.e.c.a.m.s.MachineManager 347]      - Image of snapshot for machine ws-machine not found. Machine will be created from origin source

**Comment by lhwong** [comment]
Correction: If without stopping the workspace before stopping che server then loading of snapshot will fail upon next startup. If stop the workspace fist before stopping che server then works fine.

**Comment by ddementieva** [comment]
Currently you need to stop workspaces manually with `Workspace > Stop` option to save changes after the Che stop. This is considered a normal way to stop a workspace.

**Comment by lhwong** [comment]
if I don't stop workspaces manually with `Workspace > Stop` option, I expect no new snapshot will be  created and upon startup the **last saved snapshot** should be loaded. 

Will there be option to choose which snapshot to load if more than one  snapshots were created?

**Comment by ghost** [comment]
yes, we're thinking of various scenarios and behaviors. Current behavior isn't ideal.
