### ISSUE TITLE
Workspace start fails due to Duplicate key when referencing a plugin twice

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#16202]
### Describe the bug

When starting a workspace on che that references a plugin twice, the workspace fails with a duplicate key error.  This particular example adds the woopra telemetry plugin URL as a `chePlugin` when it is already added in the background by the default workspace editor plugins.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Add a reference component to a devfile:
```yaml
- type: chePlugin
  reference: "https://static.developers.redhat.com/che/theia_artifacts/che-workspace-telemetry-woopra-backend/0.0.1/meta.yaml"
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
affects all installation methods

### Environment
all environments

### Eclipse Che Logs
```

workspacezmmm5q8tx8mef2z0



{
  "links": {
    "self": "https://che.openshift.io/api/workspace/workspacezmmm5q8tx8mef2z0",
    "ide": "https://che.openshift.io/rhn-gps-tgeorge/wksp-q5q9"
  },
  "attributes": {
    "org.eclipse.che.runtimes_id": "runtimeshf40edd62dmvu5kq",
    "stopped_by": "activity-checker",
    "infrastructureNamespace": "rhn-gps-tgeorge-che",
    "stopped": "1583007938289",
    "created": "1578937764819",
    "stoppedAbnormally": "true",
    "errorMessage": "Duplicate key ComponentImpl{id='redhat-developer/che-workspace-telemetry-woopra-backend/0.0.1', alias='null', type='chePlugin', preferences={}, registryUrl='null', reference='https://static.developers.redhat.com/che/theia_artifacts/che-workspace-telemetry-woopra-backend/0.0.1/meta.yaml', referenceContent='null', selector={}, entrypoints=[], image='null', memoryLimit='null', mountSources=null, command=[], args=[], volumes=[], env=[], endpoints=[]}",
    "stackName": "Go",
    "updated": "1583007932683"
  },
  "namespace": "rhn-gps-tgeorge",
  "temporary": false,
  "id": "workspacezmmm5q8tx8mef2z0",
  "status": "STOPPED",
  "devfile": {
    "metadata": {
      "name": "wksp-q5q9"
    },
    "projects": [
      {
        "name": "example",
        "source": {
          "location": "https://github.com/golang/example.git",
          "type": "git"
        },
        "clonePath": "src/github.com/golang/example/"
      }
    ],
    "attributes": {
      "persistVolumes": "false"
    },
    "components": [
      {
        "type": "chePlugin",
        "reference": "https://static.developers.redhat.com/che/theia_artifacts/che-workspace-telemetry-woopra-backend/0.0.1/meta.yaml"
      },
      {
        "id": "ms-vscode/go/latest",
        "memoryLimit": "512Mi",
        "type": "chePlugin",
        "alias": "go-plugin"
      },
      {
        "mountSources": true,
        "endpoints": [
          {
            "name": "8080/tcp",
            "port": 8080
          }
        ],
        "memoryLimit": "512Mi",
        "type": "dockerimage",
        "alias": "go-cli",
        "image": "quay.io/eclipse/che-golang-1.12:nightly",
        "env": [
          {
            "value": "/go:$(CHE_PROJECTS_ROOT)",
            "name": "GOPATH"
          },
          {
            "value": "/tmp/.cache",
            "name": "GOCACHE"
          }
        ]
      },
      {
        "id": "eclipse/che-theia/next",
        "type": "cheEditor"
      }
    ],
    "apiVersion": "1.0.0",
    "commands": [
      {
        "name": "run current file",
        "actions": [
          {
            "workdir": "${fileDirname}",
            "type": "exec",
            "command": "go get -d && go run ${file}",
            "component": "go-cli"
          }
        ]
      },
      {
        "name": "run outyet",
        "actions": [
          {
            "workdir": "${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet",
            "type": "exec",
            "command": "go get -d && go run main.go",
            "component": "go-cli"
          }
        ]
      },
      {
        "name": "stop outyet",
        "actions": [
          {
            "type": "exec",
            "command": "kill $(pidof go)",
            "component": "go-cli"
          }
        ]
      },
      {
        "name": "test outyet",
        "actions": [
          {
            "workdir": "${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet",
            "type": "exec",
            "command": "go test",
            "component": "go-cli"
          }
        ]
      },
      {
        "name": "Debug current file",
        "actions": [
          {
            "referenceContent": "{\n  \"version\": \"0.2.0\",\n  \"configurations\": [\n    {\n      \"name\": \"Debug current file\",\n      \"type\": \"go\",\n      \"request\": \"launch\",\n      \"mode\": \"auto\",\n      \"program\": \"${fileDirname}\",\n    },\n  ]\n}\n",
            "type": "vscode-launch"
          }
        ]
      }
    ]
  }
}




org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Duplicate key ComponentImpl{id='redhat-developer/che-workspace-telemetry-woopra-backend/0.0.1', alias='null', type='chePlugin', preferences={}, registryUrl='null', reference='https://static.developers.redhat.com/che/theia_artifacts/che-workspace-telemetry-woopra-backend/0.0.1/meta.yaml', referenceContent='null', selector={}, entrypoints=[], image='null', memoryLimit='null', mountSources=null, command=[], args=[], volumes=[], env=[], endpoints=[]}
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:815)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:274)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:883)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:30)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Duplicate key ComponentImpl{id='redhat-developer/che-workspace-telemetry-woopra-backend/0.0.1', alias='null', type='chePlugin', preferences={}, registryUrl='null', reference='https://static.developers.redhat.com/che/theia_artifacts/che-workspace-telemetry-woopra-backend/0.0.1/meta.yaml', referenceContent='null', selector={}, entrypoints=[], image='null', memoryLimit='null', mountSources=null, command=[], args=[], volumes=[], env=[], endpoints=[]}
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.KubernetesPluginsToolingApplier.apply(KubernetesPluginsToolingApplier.java:134)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:82)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:182)
	... 11 common frames omitted
```

**Comment by tsmaeder** [comment]
@tomgeorge so what should the behaviour be?

**Comment by ibuziuk** [comment]
> @tomgeorge so what should the behaviour be?

@tsmaeder fail faster + better error message

**Comment by tsmaeder** [comment]
@ibuziuk your guess or do you know?

**Comment by tomgeorge** [comment]
I agree with Ilya.  If possible it should prevent the user from adding a duplicate plugin with a notification, or it should fail with a clear error message .

**Comment by ibuziuk** [comment]
Closing. The issue should be fixed on workspaces.openshift.com
