### ISSUE TITLE
Could not start workspace wksp-JavaEE. Reason: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

### ISSUE THREAD

**Issue by zaozaool** [eclipse-che/che#1621]
Hi @benoitf @TylerJewell 

Description of problem: 
Could not start workspace wksp-JavaEE. Reason: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.
Che version: 4.4.0
Che install directory: /home/scm/che
Docker version: 

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

Java version: 

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /home/scm/apache-maven-3.3.9
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /home/scm/jdk1.8.0_92/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-92-generic", arch: "amd64", family: "unix"
```

Environment details (AWS, VirtualBox, physical, etc.): 

```
Ubuntu Trusty
scm@nj-jiangsz1-de:~$ uname -a
Linux nj-jiangsz1-de 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

How reproducible:
Steps to Reproduce:
1. `cd /home/scm/che/assembly/assembly-main/target/eclipse-che-4.4.0/eclipse-che-4.4.0`
2. `bin/che.sh run` success.
3. New workspace and project on chrome, and prompt:
 "Could not start workspace wksp-JavaEE. Reason: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist."

Actual Results:
error message is

```
2016-07-01 13:27:56,290[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 567]    - Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

org.eclipse.che.api.machine.server.exception.MachineException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:413) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:165) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:551) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.4.0.jar:4.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:590) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:317) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:376) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        ... 10 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1697) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.client.DockerConnector.doStartContainer(DockerConnector.java:1623) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.client.DockerConnector.startContainer(DockerConnector.java:442) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:573) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        ... 12 common frames omitted
2016-07-01 13:32:32,701[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 161]      - Creating machine [ws = workspacef7ybg6h2xdhz19zv: env = default: machine = default]
2016-07-01 13:32:46,559[kspaceManager-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 567]    - Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

org.eclipse.che.api.machine.server.exception.MachineException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:413) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:165) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:551) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.4.0.jar:4.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:590) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:317) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:376) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        ... 10 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1697) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.client.DockerConnector.doStartContainer(DockerConnector.java:1623) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.client.DockerConnector.startContainer(DockerConnector.java:442) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:573) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        ... 12 common frames omitted
```

Expected Results: obviously

**Comment by garagatyi** [comment]
Can you describe how you created the workspace.

**Comment by zaozaool** [comment]
Step 1: Click "New Project"
![image](https://cloud.githubusercontent.com/assets/10701999/16514915/65dcc8cc-3fa1-11e6-93d3-98756a9c6640.png)

Step 2: Choose
![image](https://cloud.githubusercontent.com/assets/10701999/16514996/d5be5be2-3fa1-11e6-987d-dacdb71b007f.png)

Step 3: Click " Create workspace and project"
![image](https://cloud.githubusercontent.com/assets/10701999/16515037/196221bc-3fa2-11e6-866a-4258ea359ae8.png)

waiting a minite, prompt this:
![image](https://cloud.githubusercontent.com/assets/10701999/16515081/6dbec5ee-3fa2-11e6-9437-6a2d6cc6c734.png)

Log:

```
2016-07-01 15:40:19,349[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 707]    - Workspace 'che:wksp-ohg9' with id 'workspaceni1fbs9chj40ykq6' created by user 'che'
2016-07-01 15:40:20,428[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 161]      - Creating machine [ws = workspaceni1fbs9chj40ykq6: env = default: machine = default]
2016-07-01 15:40:45,709[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 567]    - Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

org.eclipse.che.api.machine.server.exception.MachineException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:413) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:165) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:551) ~[che-core-api-workspace-4.4.0.jar:4.4.0]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.4.0.jar:4.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:590) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:317) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:376) ~[che-core-api-machine-4.4.0.jar:4.4.0]
        ... 10 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 404, message: Container command '/bin/sh' not found or does not exist.

        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1697) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.client.DockerConnector.doStartContainer(DockerConnector.java:1623) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.client.DockerConnector.startContainer(DockerConnector.java:442) ~[che-plugin-docker-client-4.4.0.jar:4.4.0]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:573) ~[che-plugin-docker-machine-4.4.0.jar:4.4.0]
        ... 12 common frames omitted

```

**Comment by ghost** [comment]
@zaozaool can you manually run the following?

`docker run -ti codenvy/ubuntu_jdk8`

Expected result - it should hang because of `tail -f` in CMD.

**Comment by zaozaool** [comment]
Which path?
My che install directory is `/home/scm/che`.

when run `docker run -ti codenvy/ubuntu_jdk8` it always prompt 

```
docker: Error response from daemon: Container command '/bin/sh' not found or does not exist..
```

whatever in path `/home/scm/che` or `/home/scm/che/assembly/assembly-main/target/eclipse-che-4.4.0/eclipse-che-4.4.0`

Is it my docker's problem?

```
scm@nj-jiangsz1-de:~/che/assembly/assembly-main/target/eclipse-che-4.4.0/eclipse-che-4.4.0$ pwd
/home/scm/che/assembly/assembly-main/target/eclipse-che-4.4.0/eclipse-che-4.4.0
scm@nj-jiangsz1-de:~/che/assembly/assembly-main/target/eclipse-che-4.4.0/eclipse-che-4.4.0$ docker run -ti codenvy/ubuntu_jdk8
docker: Error response from daemon: Container command '/bin/sh' not found or does not exist..
scm@nj-jiangsz1-de:~/che/assembly/assembly-main/target/eclipse-che-4.4.0/eclipse-che-4.4.0$ 
```

**Comment by ddementieva** [comment]
@zaozaool if `docker run -ti codenvy/ubuntu_jdk8 bash` or `docker run -ti codenvy/ubuntu_jdk8` return the error it does seems like a Docker related issue since Che does not come into play in this case.

**Comment by zaozaool** [comment]
I fixed it with docker.
Another question: how to change the key bindings?

**Comment by ghost** [comment]
@zaozaool unfortunately, key bindings aren't configurable now.

**Comment by zaozaool** [comment]
OK, thank you very much.

Some key bingings are conflicting with chrome, such as Ctrl+Alt+N.

I'm looking forward the improvement about it.
