### ISSUE TITLE
Unable to create and start a workspace using minikube due to "Server 'theia' in container 'theia-idet0b' not available."

### ISSUE THREAD

**Issue by stianlagstad** [eclipse-che/che#16244]
### Describe the bug
I'm trying to follow https://www.eclipse.org/che/docs/che-7/running-che-locally/, using minikube with virtualbox (8192 memory), and I'm stuck on the `Error: Failed to run the workspace: "Server 'theia' in container 'theia-idet0b' not available."` error when trying to create a workspace. The workspace I'm trying to use is the Spring Boot with petclinic starter.

### Che version
```
➜ chectl version
chectl/7.9.0 linux-x64 node-v10.19.0
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
➜ minikube version
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff
```

### Steps to reproduce

1. `minikube config set vm-driver virtualbox`
1. `minikube start --memory=8192`
1. `chectl server:start --platform minikube`
1. Open http://che-che.192.168.99.101.nip.io/dashboard/#/
1. Click "Get Started" in the left-hand menu
1. Select the "Java Spring Boot" project with the description "Java stack with OpenJDK and Spring Boot Petclinic demo application"
1. Watch the workspace being created.. logs:
```
Saving log of installed plugins
All plugin artifacts have been successfully downloaded
Pulling image "quay.io/eclipse/che-java8-maven:7.9.0"
Successfully pulled image "quay.io/eclipse/che-java8-maven:7.9.0"
Created container tools
Started container tools
Pulling image "quay.io/eclipse/che-sidecar-java:8-0cfbacb"
Successfully pulled image "quay.io/eclipse/che-sidecar-java:8-0cfbacb"
Created container vscode-java39c
Started container vscode-java39c
Pulling image "quay.io/eclipse/che-machine-exec:7.9.0"
Successfully pulled image "quay.io/eclipse/che-machine-exec:7.9.0"
Created container che-machine-execxgz
Started container che-machine-execxgz
Pulling image "quay.io/eclipse/che-theia:7.9.0"
Successfully pulled image "quay.io/eclipse/che-theia:7.9.0"
Created container theia-idet0b
Started container theia-idet0b
Error: Failed to run the workspace: "Server 'theia' in container 'theia-idet0b' not available."
```

### Expected behavior
I expected the workspace to be created, so that I could try developing with che.

### Runtime
   - [X] kubernetes (include output of `kubectl version`)

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
   - [x] minikube (include output of `minikube version` and `kubectl version`)

```
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff
```

### Screenshots
NA

### Installation method
   - [X]

chectl was installed following instructions from https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/ . I used the command `bash <(curl -sL  https://www.eclipse.org/che/chectl/)`.

### Environment
   - [X] my computer
       - [X] Linux. Ubuntu 18.04.4 LTS

### Eclipse Che Logs
Please let me know if I should provide this.

### Additional context
Nothing more to add.

**Comment by tolusha** [comment]
@stianlagstad 
Thank you for reporting. I've reproduced the issue and will try to find a fix

**Comment by stianlagstad** [comment]
@tolusha Thank you for confirming! Let me know if there's anything I can do.

**Comment by tolusha** [comment]
It seems some k8s events have no timestamp and che server print errors
```
2020-03-05 15:50:48,366[//10.96.0.1/...]  [ERROR] [k.c.d.i.WatchConnectionManager 268]  - Invalid event type
java.lang.IllegalArgumentException: Pod event timestamp can not be blank
<------>at org.eclipse.che.workspace.infrastructure.kubernetes.util.PodEvents.convertEventTimestampToDate(PodEvents.java:35)
<------>at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.happenedAfterWatcherInitialization(KubernetesDeployments.java:570)
<------>at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.eventReceived(KubernetesDeployments.java:530)
<------>at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.eventReceived(KubernetesDeployments.java:509)
<------>at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
<------>at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:232)
<------>at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
<------>at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
<------>at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
<------>at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
<------>at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
<------>at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
<------>at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
<------>at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
<------>at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
<------>at java.lang.Thread.run(Thread.java:748)
```

**Comment by tolusha** [comment]
/cc
@skabashnyuk

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/15395

**Comment by tolusha** [comment]
could you try a different installation method
`chectl server:start --platform minikube  --installer operator`

**Comment by stianlagstad** [comment]
That opened a user login/registration form at http://che-che.192.168.99.101.nip.io instead of getting directly into che. That's to be expected? I just registered a dummy user and was taken into che.

Aaand I was able to create a workspace from that spring boot petclinic-starter this time :)

**Comment by tolusha** [comment]
> That opened a user login/registration

yes, operator deploys che in multi-user mode

**Comment by stianlagstad** [comment]
BTW, when trying to stop the server:
```
➜ chectl server:stop         
  ✔ Verify Kubernetes API...OK
  ✔ Verify if Eclipse Che is deployed into namespace "che"
    ✔ Found running che deployment
    ✔ Found running postgres deployment
    ✔ Found running keycloak deployment
    ✔ Found running plugin registry deployment
    ✔ Found running devfile registry deployment
  ✔ Check Eclipse Che server status...RUNNING (auth enabled)
  ✖ Stop Eclipse Che server and wait until it's ready to shutdown
    → For instructions to retrieve a valid access token refer to https://www.eclipse.org/che/docs/che-6/authentication.html
    Scale "che" deployment to zero
    Wait until Eclipse Che pod is deleted
    Scale "keycloak" deployment to zero
    Wait until Keycloak pod is deleted
    Scale "postgres" deployment to zero
    Wait until Postgres pod is deleted
    Scale "devfile registry" deployment to zero
    Wait until Devfile registry pod is deleted
    Scale "plugin registry" deployment to zero
    Wait until Plugin registry pod is deleted
 ›   Error: E_AUTH_REQUIRED - Eclipse Che authentication is enabled and an access token need to be provided (flag --access-token).
 ›   For instructions to retrieve a valid access token refer to https://www.eclipse.org/che/docs/che-6/authentication.html
```

That URL (https://www.eclipse.org/che/docs/che-6/authentication.html) does not work. Where can I learn how to authenticate against the server?

**Comment by tolusha** [comment]
The link to the doc has been fixed in the next version of chectl.
https://www.eclipse.org/che/docs/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.html

**Comment by tolusha** [comment]
Works with `chectl 7.10`

**Comment by TrXtR** [comment]
This leads to a 404
https://www.eclipse.org/che/docs/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.html

**Comment by metlos** [comment]
The docs have been completely revamped. I believe the new URL is this:
https://www.eclipse.org/che/docs/che-7/administration-guide/authenticating-users/#authenticating-to-the-che-server-using-openid_authenticating-to-the-che-server
