### ISSUE TITLE
Can't build che-theia from scratch - fails on @eclipse-che/github-auth-plugin 

### ISSUE THREAD

**Issue by va1erian** [eclipse-che/che#16282]
Hello,

I'm trying to build a patched version of che-theia to diagnose an internal deployment of Che 7 that doesn't work properly on our env.

When running yarn I'm getting the following error:
```
yarn install v1.22.0
warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
[1/4] Resolving packages...
success Already up-to-date.
$ lerna run prepare
lerna notice cli v3.20.2
lerna info Executing command in 19 packages: "yarn run prepare"
@eclipse-che/che-theia-hosted-plugin-manager-extension: yarn run v1.22.0
@eclipse-che/theia-plugin-ext: yarn run v1.22.0
@eclipse-che/theia-terminal: yarn run v1.22.0
@eclipse-che/theia-remote: yarn run v1.22.0
@eclipse-che/theia-plugin-ext: $ yarn clean && yarn build
@eclipse-che/che-theia-hosted-plugin-manager-extension: $ yarn clean && yarn build
@eclipse-che/theia-terminal: $ yarn run clean && yarn run build
@eclipse-che/theia-remote: $ yarn clean && yarn build
@eclipse-che/theia-plugin-ext: $ rimraf lib
@eclipse-che/theia-terminal: $ rimraf lib
@eclipse-che/che-theia-hosted-plugin-manager-extension: $ rimraf lib
@eclipse-che/theia-remote: $ rimraf lib
@eclipse-che/theia-remote: $ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint:fix" "yarn compile"
@eclipse-che/theia-terminal: $ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile"
@eclipse-che/che-theia-hosted-plugin-manager-extension: $ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile"
@eclipse-che/theia-plugin-ext: $ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile" && yarn run compileWorker
@eclipse-che/theia-remote: [lint] $ tslint -c ../../configs/tslint.json --fix --project .
@eclipse-che/che-theia-hosted-plugin-manager-extension: [format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
@eclipse-che/theia-remote: [compile] $ tsc
@eclipse-che/che-theia-hosted-plugin-manager-extension: [lint] $ tslint -c ../../configs/tslint.json --project tsconfig.json
@eclipse-che/theia-remote: [format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
@eclipse-che/theia-terminal: [lint] $ tslint -c ../../configs/tslint.json --project tsconfig.json
@eclipse-che/theia-terminal: [format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
@eclipse-che/theia-terminal: [compile] $ tsc
@eclipse-che/che-theia-hosted-plugin-manager-extension: [compile] $ tsc
@eclipse-che/theia-plugin-ext: [format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
@eclipse-che/theia-plugin-ext: [lint] $ tslint -c ../../configs/tslint.json --project tsconfig.json
@eclipse-che/theia-plugin-ext: [compile] $ tsc
@eclipse-che/che-theia-hosted-plugin-manager-extension: [format] yarn format exited with code 0
@eclipse-che/theia-terminal: [format] yarn format exited with code 0
@eclipse-che/theia-remote: [format] yarn format exited with code 0
@eclipse-che/theia-plugin-ext: [format] yarn format exited with code 0
@eclipse-che/che-theia-hosted-plugin-manager-extension: [compile] yarn compile exited with code 0
@eclipse-che/che-theia-hosted-plugin-manager-extension: [lint] yarn lint exited with code 0
@eclipse-che/che-theia-hosted-plugin-manager-extension: Done in 18.30s.
@eclipse-che/theia-generator: yarn run v1.22.0
@eclipse-che/theia-generator: warning package.json: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: $ yarn run clean && yarn run build
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-remote: [lint] yarn lint:fix exited with code 0
@eclipse-che/theia-generator: warning package.json: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-terminal: [lint] yarn lint exited with code 0
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: $ rimraf dist
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-terminal: [compile] yarn compile exited with code 0
@eclipse-che/theia-terminal: Done in 22.13s.
@eclipse-che/theia-generator: warning package.json: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: $ yarn run compile && yarn run format-code && yarn run tslint-fix && yarn run test
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-containers-plugin: yarn run v1.22.0
@eclipse-che/theia-remote: [compile] yarn compile exited with code 0
@eclipse-che/theia-remote: Done in 23.21s.
@eclipse-che/theia-containers-plugin: warning @eclipse-che/theia-containers-plugin@0.0.2: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/theia-containers-plugin: $ yarn clean && yarn build
@eclipse-che/theia-generator: warning package.json: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: $ tsc && chmod +x dist/index.js
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/github-auth-plugin: yarn run v1.22.0
@eclipse-che/github-auth-plugin: warning @eclipse-che/github-auth-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/github-auth-plugin: $ yarn run clean && yarn run build
@eclipse-che/theia-containers-plugin: warning @eclipse-che/theia-containers-plugin@0.0.2: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/theia-containers-plugin: $ rimraf lib
@eclipse-che/github-auth-plugin: warning @eclipse-che/github-auth-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/github-auth-plugin: $ rimraf lib
@eclipse-che/theia-plugin-ext: [lint] yarn lint exited with code 0
@eclipse-che/theia-containers-plugin: warning @eclipse-che/theia-containers-plugin@0.0.2: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/theia-containers-plugin: $ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile" && theia-plugin pack
@eclipse-che/github-auth-plugin: warning @eclipse-che/github-auth-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/github-auth-plugin: $ yarn lint:fix && concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile" && theia-plugin pack
@eclipse-che/github-auth-plugin: warning @eclipse-che/github-auth-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/github-auth-plugin: $ tslint -c ../../configs/tslint.json --fix --project .
@eclipse-che/theia-containers-plugin: [format] warning @eclipse-che/theia-containers-plugin@0.0.2: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/theia-containers-plugin: [format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
@eclipse-che/theia-containers-plugin: [lint] warning @eclipse-che/theia-containers-plugin@0.0.2: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/theia-containers-plugin: [lint] $ tslint -c ../../configs/tslint.json --project tsconfig.json
@eclipse-che/theia-containers-plugin: [compile] warning @eclipse-che/theia-containers-plugin@0.0.2: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/theia-containers-plugin: [compile] $ tsc
@eclipse-che/theia-containers-plugin: [format] yarn format exited with code 0
@eclipse-che/theia-plugin-ext: [compile] yarn compile exited with code 0
@eclipse-che/theia-plugin-ext: $ webpack-cli --config webpack.config.js
@eclipse-che/theia-plugin-ext: clean-webpack-plugin: /home/hadrien/repos/che-theia/extensions/eclipse-che-theia-plugin-ext/lib/webworker has been removed.
@eclipse-che/theia-generator: warning package.json: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: $ tsfmt -r
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/github-auth-plugin: [compile] warning @eclipse-che/github-auth-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/github-auth-plugin: [compile] $ tsc
@eclipse-che/github-auth-plugin: [format] warning @eclipse-che/github-auth-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/github-auth-plugin: [format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
@eclipse-che/theia-containers-plugin: [lint] yarn lint exited with code 0
@eclipse-che/github-auth-plugin: [lint] warning @eclipse-che/github-auth-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
@eclipse-che/github-auth-plugin: [lint] $ tslint -c ../../configs/tslint.json --project tsconfig.json
@eclipse-che/theia-containers-plugin: [compile] yarn compile exited with code 0
@eclipse-che/theia-containers-plugin: Packaging of plugin
@eclipse-che/theia-containers-plugin: 🔍 Validating...✔️ 
@eclipse-che/github-auth-plugin: [format] yarn format exited with code 0
@eclipse-che/theia-generator: warning package.json: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/theia-generator: $ tslint --fix --project .
@eclipse-che/theia-generator: warning @eclipse-che/theia-generator@0.0.1: Invalid bin entry for "che:theia" (in "@eclipse-che/theia-generator").
@eclipse-che/github-auth-plugin: [lint] yarn lint exited with code 0
@eclipse-che/github-auth-plugin: [compile] yarn compile exited with code 0
@eclipse-che/theia-containers-plugin: 🗂  Getting dependencies...❌️ 
@eclipse-che/theia-containers-plugin: Error: Not able to get yarn workspaces when executing yarn workspaces info --json. Found {
@eclipse-che/theia-containers-plugin:   "@eclipse-che/che-theia-hosted-plugin-manager-extension": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/che-theia-hosted-plugin-manager-extension",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-about": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-about",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/theia-plugin-ext"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-activity-tracker": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-activity-tracker",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/theia-plugin-ext"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-dashboard-extension": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-dashboard",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/theia-plugin-ext"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-git-provisioner": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-git-provisioner",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/theia-plugin-ext",
@eclipse-che/theia-containers-plugin:       "@eclipse-che/theia-user-preferences-synchronizer"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-plugin-ext": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-plugin-ext",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-remote": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-plugin-remote",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/plugin": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-preferences-provider-extension": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-preferences-provider-extension",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/theia-plugin-ext"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-terminal": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-terminal",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-user-preferences-synchronizer": {
@eclipse-che/theia-containers-plugin:     "location": "extensions/eclipse-che-theia-user-preferences",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/theia-plugin-ext"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-containers-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/containers-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/github-auth-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/github-auth-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/ports-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/ports-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ]
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-ssh-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/ssh-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "task-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/task-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/telemetry-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/telemetry-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/welcome-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/welcome-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/workspace-plugin": {
@eclipse-che/theia-containers-plugin:     "location": "plugins/workspace-plugin",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [
@eclipse-che/theia-containers-plugin:       "@eclipse-che/plugin"
@eclipse-che/theia-containers-plugin:     ],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   },
@eclipse-che/theia-containers-plugin:   "@eclipse-che/theia-generator": {
@eclipse-che/theia-containers-plugin:     "location": "generator",
@eclipse-che/theia-containers-plugin:     "workspaceDependencies": [],
@eclipse-che/theia-containers-plugin:     "mismatchedWorkspaceDependencies": []
@eclipse-che/theia-containers-plugin:   }
@eclipse-che/theia-containers-plugin: }
@eclipse-che/theia-containers-plugin:     at Yarn.<anonymous> (/home/hadrien/repos/che-theia/node_modules/@theia/plugin-packager/dist/yarn.js:80:27)
@eclipse-che/theia-containers-plugin:     at Generator.next (<anonymous>)
@eclipse-che/theia-containers-plugin:     at fulfilled (/home/hadrien/repos/che-theia/node_modules/@theia/plugin-packager/dist/yarn.js:13:58)
@eclipse-che/theia-containers-plugin:     at process._tickCallback (internal/process/next_tick.js:68:7)
@eclipse-che/theia-containers-plugin: error Command failed with exit code 1.
@eclipse-che/theia-containers-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@eclipse-che/theia-containers-plugin: error Command failed with exit code 1.
@eclipse-che/theia-containers-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is there something I'm doing wrong? My understanding was that running build.sh was sufficient once the prerequisites are installed.

**Comment by ibuziuk** [comment]
@artem could you please take a look ?

**Comment by va1erian** [comment]
I think the main issue is that I wasn't building che-theia in a che-theia-dev container which contain the che:theia executable. I was able to run yarn successfully but now I also need to bring the docker client manually in the container which is a bit awkward, is there a better approach? My goal is to build a che-theia image with some additionals logs to diagnose connectivity issues.

**Comment by azatsarynnyy** [comment]
Hello @va1erian 
Could you try to build with yarn 1.17.0?
I suspect we need to adapt Che Theia to be able to build it with the latest yarn.

**Comment by va1erian** [comment]
Thanks for the replies. I was able to build che-theia with a couple of additional logs using the latest che-theia-dev image. I still had to bring and configure docker manually which is kind of weird, maybe it's here in an openshift env?

Anyway, the issue was the theia backend to che REST requests were going to the proxy. Theia works much better now in our env with the proper configuration, but I still have some issues related to the devfiles - Theia and the workspace are completely empty and miss the placeholder files and the configured actions.
