### ISSUE TITLE
Error: Failed to run the workspace: "An exception occurred."

### ISSUE THREAD

**Issue by polkaudio124** [eclipse-che/che#16363]
Hi,

anyone encounter the following error before?

I have deployed eclipseche on azure kubernetes. This error is encountered after i stop and start a workspace.

i also noticed that after a certain time, i am able to start up the same workspace successfully.

![start-workspace-error](https://user-images.githubusercontent.com/30489534/76719393-a4faf980-6774-11ea-9239-b770715b8de5.PNG)

```
2020-03-16 02:47:24,236[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 479]   - Starting workspace 'cheadmin/workspace-2' with id 'workspacecvrpitdovsl7jdwv' by user 'cheadmin'
2020-03-16 02:48:25,251[://10.0.0.1/...]  [WARN ] [k.c.d.i.WatchConnectionManager 201]  - Exec Failure
java.lang.NullPointerException: null
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$CreateWatcher.eventReceived(KubernetesDeployments.java:1000)
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$CreateWatcher.eventReceived(KubernetesDeployments.java:984)
        at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:232)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-16 02:48:26,482[://10.0.0.1/...]  [WARN ] [k.c.d.i.WatchConnectionManager 201]  - Exec Failure
java.lang.NullPointerException: null
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$CreateWatcher.eventReceived(KubernetesDeployments.java:1000)
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$CreateWatcher.eventReceived(KubernetesDeployments.java:984)
        at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:232)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-16 02:48:27,585[ceSharedPool-17]  [WARN ] [.i.k.KubernetesInternalRuntime 252]  - Failed to start Kubernetes runtime of workspace workspacecvrpitdovsl7jdwv. Cause: null
2020-03-16 02:48:28,774[ceSharedPool-17]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 907]   - Workspace 'cheadmin:workspace-2' with id 'workspacecvrpitdovsl7jdwv' start failed
2020-03-16 02:48:28,775[ceSharedPool-17]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 917]   - An exception occurred.
org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: An exception occurred.
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.wrapAndRethrow(KubernetesInternalRuntime.java:815)
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:274)
        at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:883)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.storeStartingMachine(KubernetesInternalRuntime.java:718)
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.doStartMachine(KubernetesInternalRuntime.java:693)
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.startMachines(KubernetesInternalRuntime.java:605)
        at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:210)
        ... 7 common frames omitted
```

**Comment by skabashnyuk** [comment]
@polkaudio124 thank you for this report. Can you please provide more details about this accident according to the bug template.

**Comment by mbenitez1607** [comment]
Similar issue was just seen by a customer

**Comment by skabashnyuk** [comment]
@mbenitez1607 Do we have an access to the details?
