### ISSUE TITLE
Che Theia can't reach Che plugin registry behind the proxy with TLS support

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16482]
### Describe the bug
Plugins view is empty behind the proxy in CRW 2.1.0.RC3 based on Eclipse Che 7.9.2 with TLS support:
![Screenshot from 2020-03-26 16-00-20](https://user-images.githubusercontent.com/1197777/77818185-1c1b8080-70d9-11ea-9749-8bc3c5f068b1.png)

Theia image: quay.io/crw/theia-rhel8:2.1-23

Proxy settings:
```
  CHE_WORKSPACE_HTTPS__PROXY: 'http://10.0.148.146:3128'
  CHE_WORKSPACE_HTTP__PROXY: 'http://10.0.148.146:3128'
```

[Downstream issue](https://issues.redhat.com/browse/CRW-720).

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: CRW 2.1.0.RC3 based on Eclipse Che 7.9.2

### Steps to reproduce
1. Start workspace
2. Open Plugins View

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: OCP 3.11

### Installation method
   - [x] crwctl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
```
2020-03-26 13:58:55.402 root ERROR [hosted-plugin: 50] Promise rejection not handled in one second: Error: Failed to show text document [object Object] , reason: Error: Failed to show text document [object Object]
With stack trace: Error: Failed to show text document [object Object]
    at Object.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:252:43)
    at step (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:58:23)
    at Object.next (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:39:53)
    at fulfilled (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:30:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
2020-03-26 13:58:58.454 root INFO Cannot access the registry Params: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new ClientRequest (_http_client.js:120:11)
    at Object.request (http.js:42:10)
    at RedirectableRequest._performRequest (/home/theia/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/home/theia/node_modules/follow-redirects/index.js:66:8)
    at Object.wrappedProtocol.request (/home/theia/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/node_modules/axios/lib/adapters/http.js:180:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/node_modules/axios/lib/adapters/http.js:20:10)
    at dispatchRequest (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/node_modules/axios/lib/core/dispatchRequest.js:59:10)
2020-03-26 13:58:58.666 root INFO Unable to read plugin registry Params: https://plugin-registry-crw-crwctl-with-proxy.apps.ocp311-2.crw/v3/plugins/ 
```

**Comment by azatsarynnyy** [comment]
[AxiosInstance in che-plugin-service](https://github.com/eclipse/che-theia/blob/413db364f965bd314dba858c3bc9236a34aeac06/extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts#L109-L123) should be configured in a similar way as it's done for [che-workspace-client](https://github.com/eclipse/che-workspace-client/pull/28/files#diff-f41e9d04a45c83f3b6f6e630f10117feR55-R105) by the PR https://github.com/eclipse/che-workspace-client/pull/28
