### ISSUE TITLE
devfile with k8s component with 2 pods that have container with same name fails to start

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#16558]
### Describe the bug
Having devfile with valid kubernetes component that have 2 pods with a container with same name fails to start with `Error: Failed to start the workspace: "Environment contains machines that are missing in recipe: p2/c1"`.
k8s recipe:
```
          kind: List
          items:
          - kind: Pod
            apiVersion: v1
            metadata:
              name: p1
            spec:
              containers:
                - name: c1
                  image: quay.io/eclipse/che-golang-1.12:nightly
          - kind: Pod
            apiVersion: v1
            metadata:
              name: p2
            spec:
              containers:
                - name: c1
                  image: quay.io/eclipse/che-golang-1.12:nightly
```

Also ugly exception in che server log is visible only on DEBUG level.

### Che version
 - [x] nightly

### Steps to reproduce

1. start workspace with this devfile
```
---
apiVersion: 1.0.0
metadata:
  generateName: k8s-component-
projects:
  - name: dummy-http-server
    source:
      type: git
      location: "https://github.com/sparkoo/dummy-http-server.git"
components:
  - type: kubernetes
    alias: go-k8s
    referenceContent: |
          kind: List
          items:
          - kind: Pod
            apiVersion: v1
            metadata:
              name: p1
            spec:
              containers:
                - name: c1
                  image: quay.io/eclipse/che-golang-1.12:nightly
          - kind: Pod
            apiVersion: v1
            metadata:
              name: p2
            spec:
              containers:
                - name: c1
                  image: quay.io/eclipse/che-golang-1.12:nightly

```

2. see workspace fail with `Error: Failed to start the workspace: "Environment contains machines that are missing in recipe: p2/c1"`

### Expected behavior
workspace should start of proper error should be displayed. Also exception in che-server log should be visible with INFO log level.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

```
[~] λ minikube version
minikube version: v1.9.2
commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393
[~] λ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer
       - [x] Linux

### Eclipse Che Logs

<details>
<summary>exception</summary>

```

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.api.local.filters.EnvironmentInitializationFilter.doFilter(EnvironmentInitializationFilter.java:59)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ConflictException: Environment contains machines that are missing in recipe: p2/c1
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startAsync(WorkspaceManager.java:443)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startWorkspace(WorkspaceManager.java:373)
	at org.eclipse.che.api.workspace.server.WorkspaceService.startById(WorkspaceService.java:469)
	... 44 common frames omitted
Caused by: org.eclipse.che.api.core.ValidationException: Environment contains machines that are missing in recipe: p2/c1
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentValidator.checkArgument(KubernetesEnvironmentValidator.java:55)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentPodsValidator.ensureConfiguredMachinesHaveContainers(KubernetesEnvironmentPodsValidator.java:98)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentPodsValidator.validate(KubernetesEnvironmentPodsValidator.java:41)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentValidator.validate(KubernetesEnvironmentValidator.java:39)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentFactory.doCreate(KubernetesEnvironmentFactory.java:145)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentFactory.doCreate(KubernetesEnvironmentFactory.java:53)
	at org.eclipse.che.api.workspace.server.spi.environment.InternalEnvironmentFactory.create(InternalEnvironmentFactory.java:108)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.createInternalEnvironment(WorkspaceRuntimes.java:779)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.validate(WorkspaceRuntimes.java:267)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startAsync(WorkspaceManager.java:441)
	... 46 common frames omitted
2020-04-06 18:11:24,829[io-8080-exec-10]  [DEBUG] [o.e.c.impl.RequestHandlerImpl 121]   - InternalException occurs
org.everrest.core.impl.InternalException: org.eclipse.che.api.core.ConflictException: Environment contains machines that are missing in recipe: p2/c1
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:156)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.api.local.filters.EnvironmentInitializationFilter.doFilter(EnvironmentInitializationFilter.java:59)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ConflictException: Environment contains machines that are missing in recipe: p2/c1
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startAsync(WorkspaceManager.java:443)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startWorkspace(WorkspaceManager.java:373)
	at org.eclipse.che.api.workspace.server.WorkspaceService.startById(WorkspaceService.java:469)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	... 39 common frames omitted
Caused by: org.eclipse.che.api.core.ValidationException: Environment contains machines that are missing in recipe: p2/c1
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentValidator.checkArgument(KubernetesEnvironmentValidator.java:55)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentPodsValidator.ensureConfiguredMachinesHaveContainers(KubernetesEnvironmentPodsValidator.java:98)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentPodsValidator.validate(KubernetesEnvironmentPodsValidator.java:41)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentValidator.validate(KubernetesEnvironmentValidator.java:39)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentFactory.doCreate(KubernetesEnvironmentFactory.java:145)
	at org.eclipse.che.workspace.infrastructure.kubernetes.environment.KubernetesEnvironmentFactory.doCreate(KubernetesEnvironmentFactory.java:53)
	at org.eclipse.che.api.workspace.server.spi.environment.InternalEnvironmentFactory.create(InternalEnvironmentFactory.java:108)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.createInternalEnvironment(WorkspaceRuntimes.java:779)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.validate(WorkspaceRuntimes.java:267)
	at org.eclipse.che.api.workspace.server.WorkspaceManager.startAsync(WorkspaceManager.java:441)
	... 46 common frames omitted
</details>

### Additional context
<!-- Add any other context about the problem here. -->

**Comment by azatsarynnyy** [comment]
setting it as P2 as it looks like a minor issue to me, but feel free to re-prioritize it as you think is more accurately

**Comment by rromannissen** [comment]
I have reproduced it with two different Deployment objects that have the same container name in spec.template.spec.containers[n].name. The scenario is a project with several microservices, with each one of them requiring a dedicated postgresql instance. Each of these instances were created by using an instantiation of the postgresql-ephemeral template from OCP. Can be fixed easily by changing the container name on each Deployment definition, but the error message is a bit confusing.
