### ISSUE TITLE
Failed to deploy Eclipse Che on minikube 1.8.x

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16637]
### Describe the bug
Failed to deploy Eclipse Che on minikube 1.8.x
`chectl server:start --installer=operator --platform=minikube`
che-server logs:
```
) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: https://keycloak-che.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:70)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:53)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakProfileRetriever.<init>(KeycloakProfileRetriever.java:40)
```

kubectl get ingress -n che
```
NAME               HOSTS                                        ADDRESS   PORTS     AGE
che                che-che.192.168.99.100.nip.io                          80, 443   5m31s
devfile-registry   devfile-registry-che.192.168.99.100.nip.io             80, 443   3m52s
keycloak           keycloak-che.192.168.99.100.nip.io                     80, 443   5m31s
plugin-registry    plugin-registry-che.192.168.99.100.nip.io              80, 443   3m24s
```

### Che version

 - [x] nightly

### Runtime
   - [x] minikube 1.8.2 (include output of `minikube version` and `kubectl version`)
`minikube1.8.2 start --cpus 4 --memory 10240 --disk-size=50GB --vm-driver=virtualbox`

### Installation method
   - [x] chectl 
```bash
$ chectl version
chectl/0.0.20200417-next.2a7a009 linux-x64 node-v10.20.1
```

### Environment
   - [x] my computer
       - [x] Linux

**Comment by tolusha** [comment]
```bash
minikube1.8.2 addons list
|-----------------------------|----------|--------------|
|         ADDON NAME          | PROFILE  |    STATUS    |
|-----------------------------|----------|--------------|
| dashboard                   | minikube | disabled     |
| default-storageclass        | minikube | enabled ✅   |
| efk                         | minikube | disabled     |
| freshpod                    | minikube | disabled     |
| gvisor                      | minikube | disabled     |
| helm-tiller                 | minikube | disabled     |
| ingress                     | minikube | disabled     |
| ingress-dns                 | minikube | disabled     |
| istio                       | minikube | disabled     |
| istio-provisioner           | minikube | disabled     |
| logviewer                   | minikube | disabled     |
| metrics-server              | minikube | disabled     |
| nvidia-driver-installer     | minikube | disabled     |
| nvidia-gpu-device-plugin    | minikube | disabled     |
| registry                    | minikube | disabled     |
| registry-creds              | minikube | disabled     |
| storage-provisioner         | minikube | enabled ✅   |
| storage-provisioner-gluster | minikube | disabled     |
|-----------------------------|----------|--------------|
```

**Comment by tolusha** [comment]
Enabling ingress addon fixes the problem

**Comment by tolusha** [comment]
`chectl` behaves correctly and enables ingress addon.

The problem is that I started minikube using `minikube1.8.2` binaries... and chectl used `minikube` binaries to detect if addon is enabled.

**Comment by tolusha** [comment]
Problem is solved after renaming `minikube1.8.2` to `minikube`
