### ISSUE TITLE
EOFException  with BlockingInputStreamPumper 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16755]
### Describe the bug
Stacktrace in logs
```
java.io.EOFException: null
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:303)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:469)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:449)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
	at java.io.InputStream.read(InputStream.java:101)
	at io.fabric8.kubernetes.client.utils.BlockingInputStreamPumper.run(BlockingInputStreamPumper.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other:  7.12

### Steps to reproduce
Unknown

### Expected behavior
No error.
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
n/a
### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
not reproduced
