### ISSUE TITLE
Operation: [delete]  for kind: [ConfigMap]  with name: [ws-XXX-gitconfig]  in namespace: [YYY-che]  failed

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16758]
### Describe the bug
Error in che server logs
```
org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Operation: [delete]  for kind: [ConfigMap]  with name: [wsww-gitconfig]  in namespace: [XXX-che]  failed.
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesConfigsMaps.delete(KubernetesConfigsMaps.java:70)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.DeployBroker.execute(DeployBroker.java:150)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.PrepareStorage.execute(PrepareStorage.java:76)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.ListenBrokerEvents.execute(ListenBrokerEvents.java:63)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:127)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager$$EnhancerByGuice$$c9f03270.CGLIB$getTooling$0(<generated>)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager$$EnhancerByGuice$$c9f03270$$FastClassByGuice$$f276b0f8.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager$$EnhancerByGuice$$c9f03270.getTooling(<generated>)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:83)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner$$EnhancerByGuice$$7a4ab3c.CGLIB$provision$0(<generated>)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner$$EnhancerByGuice$$7a4ab3c$$FastClassByGuice$$3352454f.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner$$EnhancerByGuice$$7a4ab3c.provision(<generated>)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:193)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInternalRuntime$$EnhancerByGuice$$63910304.CGLIB$start$26(<generated>)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInternalRuntime$$EnhancerByGuice$$63910304$$FastClassByGuice$$41236812.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:61)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInternalRuntime$$EnhancerByGuice$$63910304.start(<generated>)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:920)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:30)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [ConfigMap]  with name: [wsww-gitconfig]  in namespace: [XXX-che]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:725)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:645)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:70)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:691)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteList(BaseOperation.java:730)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:655)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:70)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesConfigsMaps.delete(KubernetesConfigsMaps.java:68)
	... 40 common frames omitted
Caused by: java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.java:146)
	at okio.Okio$1.write(Okio.java:76)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
	at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.lambda$buildKubernetesInterceptor$0(OpenShiftClientFactory.java:202)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:469)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:231)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:722)
	... 47 common frames omitted
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [X] other: 7.12

### Steps to reproduce
unknown

### Expected behavior
No error.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [X] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
not reproduced after https://github.com/eclipse/che/pull/16498
