### ISSUE TITLE
cannot build crw-theia from 7.13.x che-theia

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16844]
crw-theia fails to build che-theia from the 7.12.x branch. Container build dies with:

```
Step 24/56 : RUN che-theia cdn --theia="${CDN_PREFIX}" --monaco="${MONACO_CDN_PREFIX}"
 ---> Running in ab185a713694
Removing intermediate container ab185a713694
 ---> a66b3a794cac
Step 25/56 : RUN yarn global add node-gyp && node-gyp install &&     sed -i ${HOME}/theia-source-code/package.json -e 's@node-gyp install@echo skip node-gyp install@'
 ---> Running in 7744cd8bcf9d
yarn global v1.21.1
[1/4] Resolving packages...
error Package "" refers to a non-existing file '"/home/theia-dev/eclipse-che-theia-generator"'.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
The command '/bin/sh -c yarn global add node-gyp && node-gyp install &&     sed -i ${HOME}/theia-source-code/package.json -e 's@node-gyp install@echo skip node-gyp install@'' returned a non-zero code: 1
```
-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/579/console

Did something change between 7.9.x and 7.12.x re: the theia-generator?

https://github.com/eclipse/che-theia/blob/7.12.x/dockerfiles/theia-dev/build.sh#L16-L17
https://github.com/eclipse/che-theia/blob/7.12.x/dockerfiles/theia-dev/Dockerfile#L37
https://github.com/eclipse/che-theia/blob/7.12.x/dockerfiles/theia-dev/Dockerfile#L48

**Comment by azatsarynnyy** [comment]
looks related to the recent @benoitf's changes https://github.com/eclipse/che-theia/commit/d178ce2e5453037b392387d9a785bd6637f4558b

**Comment by nickboldt** [comment]
for whatever reason, the result of this change is that  `/home/theia-dev/`  in the theia build contains

```
/home/theia-dev/loader.patch
/home/theia-dev/theia-source-code.tgz
/home/theia-dev/patches
/home/theia-dev/theia-source-code
```

but no 

```
/home/theia-dev/eclipse-che-theia-generator
```

**Comment by benoitf** [comment]
the result of the build never container that folder
The generator folder is generated by build.sh script before building the image

**Comment by nickboldt** [comment]
so... can you throw me a PR or point at the failing code in che-theia or crw-theia? or are you leaving me to figure this one out? :D

**Comment by benoitf** [comment]
@nickboldt https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia-dev/build.sh#L36

**Comment by nickboldt** [comment]
Gave up trying to make the unpacked folder work and instead did this (tested in 7.12.x branch):

https://github.com/eclipse/che-theia/pull/740

**Comment by nickboldt** [comment]
new problem...

```
20:55:57 Step 35/59 : RUN if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn ${YARN_FLAGS}
20:55:57  ---> Running in d38545ed0121
20:55:57 yarn install v1.21.1
20:55:57 $ echo skip node-gyp install
20:55:57 skip node-gyp install
20:55:57 [1/5] Validating package.json...
20:55:57 [2/5] Resolving packages...
20:55:57 warning Resolution field "electron@7.0.0" is incompatible with requested version "electron@^4.2.11"
20:55:57 [3/5] Fetching packages...
20:55:58 info fsevents@2.1.2: The platform "linux" is incompatible with this module.
20:55:58 info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
20:55:58 warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
20:55:58 warning vscode-languageclient@6.1.0: The engine "vscode" appears to be invalid.
20:55:58 info fsevents@1.2.11: The platform "linux" is incompatible with this module.
20:55:58 info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
20:55:58 [4/5] Linking dependencies...
20:55:58 warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @theia/cli > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @eclipse-che/theia-assembly > html-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
20:55:58 warning "workspace-aggregator-acba22a5-c6b0-473e-b772-c2246cec2029 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
20:55:58 warning Workspaces can only be enabled in private projects.
20:56:10 [5/5] Building fresh packages...
20:56:16 error /home/theia-dev/theia-source-code/node_modules/drivelist: Command failed.
20:56:16 Exit code: 1
20:56:16 Command: prebuild-install || node-gyp rebuild
20:56:16 Arguments: 
20:56:16 Directory: /home/theia-dev/theia-source-code/node_modules/drivelist
20:56:16 Output:
20:56:16 prebuild-install WARN install No prebuilt binaries found (target=10.19.0 runtime=node arch=x64 platform=linux)
20:56:16 gyp info it worked if it ends with ok
20:56:16 gyp info using node-gyp@6.1.0
20:56:16 gyp info using node@10.19.0 | linux | x64
20:56:16 gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
...
```

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/591/console

**Comment by nickboldt** [comment]
```
13:41:10 warning Workspaces can only be enabled in private projects.
13:41:23 [5/5] Building fresh packages...
13:41:23 error /home/theia-dev/theia-source-code/node_modules/nsfw: Command failed.
13:41:23 Exit code: 1
13:41:23 Command: node-gyp rebuild
13:41:23 Arguments: 
13:41:23 Directory: /home/theia-dev/theia-source-code/node_modules/nsfw
13:41:23 Output:
13:41:23 gyp info it worked if it ends with ok
13:41:23 gyp info using node-gyp@6.1.0
13:41:23 gyp info using node@10.19.0 | linux | x64
13:41:23 gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
13:41:23 gyp WARN install got an error, rolling back install
13:41:23 gyp ERR! configure error 
13:41:23 gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
13:41:23 gyp ERR! stack     at afterTarball (/home/theia-dev/theia-source-code/node_modules/electron-rebuild/node_modules/node-gyp/lib/install.js:212:21)
13:41:23 gyp ERR! System Linux 3.10.0-957.el7.x86_64
13:41:23 gyp ERR! command "/usr/bin/node" "/home/theia-dev/theia-source-code/node_modules/.bin/node-gyp" "rebuild"
13:41:23 gyp ERR! cwd /home/theia-dev/theia-source-code/node_modules/nsfw
13:41:23 gyp ERR! node -v v10.19.0
13:41:23 gyp ERR! node-gyp -v v6.1.0
13:41:23 gyp ERR! not ok
```
-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/596/consoleFull

Seems like we're getting random missing content. Could be colliding parallel builds on the same node.

**Comment by nickboldt** [comment]
and again with only one build per node:

```
14:37:16 warning Workspaces can only be enabled in private projects.
14:37:31 [5/5] Building fresh packages...
14:37:32 error /home/theia-dev/theia-source-code/node_modules/@theia/electron: Command failed.
14:37:32 Exit code: 127
14:37:32 Command: node scripts/post-install.js
14:37:32 Arguments: 
14:37:32 Directory: /home/theia-dev/theia-source-code/node_modules/@theia/electron
14:37:32 Output:
14:37:32 gyp info it worked if it ends with ok
14:37:32 gyp info using node-gyp@3.8.0
14:37:32 gyp info using node@10.19.0 | linux | x64
14:37:32 gyp WARN install got an error, rolling back install
14:37:32 gyp ERR! configure error 
14:37:32 gyp ERR! stack Error: incorrect header check
14:37:32 gyp ERR! stack     at Zlib.zlibOnError [as onerror] (zlib.js:164:17)
14:37:32 gyp ERR! System Linux 3.10.0-957.el7.x86_64
14:37:32 gyp ERR! command "/usr/bin/node" "/home/theia-dev/theia-source-code/dev-packages/electron/node-gyp-cli.js" "rebuild"
14:37:32 gyp ERR! cwd /home/theia-dev/theia-source-code/dev-packages/electron/native
14:37:32 gyp ERR! node -v v10.19.0
14:37:32 gyp ERR! node-gyp -v v3.8.0
14:37:32 gyp ERR! not ok 
14:37:32 Error: "../node-gyp-cli.js" exited with 1
14:37:32     at ChildProcess.subprocess.once (/home/theia-dev/theia-source-code/dev-packages/electron/scripts/post-install.js:36:40)
14:37:32     at Object.onceWrapper (events.js:286:20)
14:37:32     at ChildProcess.emit (events.js:198:13)
14:37:32     at maybeClose (internal/child_process.js:982:16)
14:37:32     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14:37:32 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
14:37:34 The command '/bin/sh -c if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn ${YARN_FLAGS}' returned a non-zero code: 127
``` 
-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/597/consoleFull

**Comment by nickboldt** [comment]
and again in step 35/59:

```
Step 35/59 : RUN if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn ${YARN_FLAGS}
 ---> Running in 1e0ebcebad74
yarn install v1.21.1
$ echo skip node-gyp install
skip node-gyp install
[1/5] Validating package.json...
[2/5] Resolving packages...
[91mwarning Resolution field "electron@7.0.0" is incompatible with requested version "electron@^4.2.11"
[0m[3/5] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[91mwarning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
[0m[91mwarning vscode-languageclient@6.1.0: The engine "vscode" appears to be invalid.
[0minfo fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[91mwarning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
[0m[91mwarning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[0m[91mwarning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @theia/cli > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
[0m[91mwarning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
[0m[91mwarning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
[0m[91mwarning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
[0m[91mwarning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @eclipse-che/theia-assembly > html-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
[0m[91mwarning "workspace-aggregator-63aa18d4-5532-4ef0-abbe-bea2a2e76946 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[0m[91mwarning Workspaces can only be enabled in private projects.
[0m[5/5] Building fresh packages...
[91merror /home/theia-dev/theia-source-code/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/theia-dev/theia-source-code/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.19.0 | linux | x64
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
gyp ERR! stack     at afterTarball (/home/theia-dev/theia-source-code/node_modules/electron-rebuild/node_modules/node-gyp/lib/install.js:212:21)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/usr/bin/node" "/home/theia-dev/theia-source-code/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/theia-dev/theia-source-code/node_modules/nsfw
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
[0minfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn ${YARN_FLAGS}' returned a non-zero code: 1
++ grep 'a non-zero code:' /tmp/CHE_THEIA_IMAGE_NAME_buildlog.txt
```

**Comment by nickboldt** [comment]
slightly better...

```
15:46:52 Step 35/60 : RUN echo "" > /etc/resolv.conf || true
15:46:52  ---> Running in c5ae7e714325
15:46:52 Removing intermediate container c5ae7e714325
15:46:52  ---> 14721f5972b2
15:46:52 Step 36/60 : RUN if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn ${YARN_FLAGS}
15:46:52  ---> Running in 7382cf75e7d8
15:46:52 yarn install v1.21.1
15:46:52 $ echo skip node-gyp install
15:46:52 skip node-gyp install
15:46:52 [1/5] Validating package.json...
15:46:52 [2/5] Resolving packages...
15:46:52 warning Resolution field "electron@7.0.0" is incompatible with requested version "electron@^4.2.11"
15:46:52 [3/5] Fetching packages...
15:46:53 info fsevents@2.1.2: The platform "linux" is incompatible with this module.
15:46:53 info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
15:46:53 warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
15:46:53 warning vscode-languageclient@6.1.0: The engine "vscode" appears to be invalid.
15:46:53 info fsevents@1.2.11: The platform "linux" is incompatible with this module.
15:46:53 info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
15:46:53 [4/5] Linking dependencies...
15:46:53 warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @theia/cli > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @eclipse-che/theia-assembly > html-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
15:46:53 warning "workspace-aggregator-06067d22-3aff-44b8-800e-6a19a06a53c3 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
15:46:54 warning Workspaces can only be enabled in private projects.
15:47:09 [5/5] Building fresh packages...
15:47:09 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
15:47:09 error /home/theia-dev/theia-source-code/node_modules/@theia/electron: Command failed.
15:47:09 Exit code: 127
15:47:09 Command: node scripts/post-install.js
15:47:09 Arguments: 
15:47:09 Directory: /home/theia-dev/theia-source-code/node_modules/@theia/electron
15:47:09 Output:
15:47:09 gyp info it worked if it ends with ok
15:47:09 gyp info using node-gyp@3.8.0
15:47:09 gyp info using node@10.19.0 | linux | x64
15:47:09 gyp WARN install got an error, rolling back install
15:47:09 gyp ERR! configure error 
15:47:09 gyp ERR! stack Error: incorrect header check
15:47:09 gyp ERR! stack     at Zlib.zlibOnError [as onerror] (zlib.js:164:17)
15:47:09 gyp ERR! System Linux 3.10.0-957.el7.x86_64
15:47:09 gyp ERR! command "/usr/bin/node" "/home/theia-dev/theia-source-code/dev-packages/electron/node-gyp-cli.js" "rebuild"
15:47:09 gyp ERR! cwd /home/theia-dev/theia-source-code/dev-packages/electron/native
```
-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/603/console

But we're still obviously depending on and trying to build electron. 

Help me @benoitf, you're my only hope.

**Comment by nickboldt** [comment]
@azatsarynnyy Any advice here?

**Comment by azatsarynnyy** [comment]
@nickboldt there were two PRs to get rid of electron in Che Theia:
- https://github.com/eclipse/che-theia/pull/726/files
- https://github.com/eclipse/che-theia/pull/732/files

This may help you to apply something similar to CRW Theia.

**Comment by nickboldt** [comment]
Um, thanks. Unfortunately that's a bit like saying "the city you're looking for contains the letter A. Here's a map of Europe. Good luck." :( Please remember that I don't write typescript on a daily basis so I have no idea what's failing or why. 

I don't know how those changes might have impacted in the crw-theia build overlays or the all-in-one build.sh script that orchestrates it. I don't see anywhere in the crw theia build where we explicitly do anything fun with electron beyond what's done in the online che-theia build.

All I know is that I can build:

* theia-dev ubi (online, collect tarballs)
* theia-dev ubi-brew (offline, dry run for Brew)
* theia ubi (online, collect tarballs)

But it fails on

* theia ubi-brew (offline)

Also I'm wondering ... if we removed electron, why do we still do this?

* https://github.com/eclipse/che-theia/blob/7.13.x/dockerfiles/theia/docker/ubi8/builder-post-clone.dockerfile
* https://github.com/redhat-developer/codeready-workspaces-theia/blob/master/conf/theia/ubi8-brew/builder-post-clone.dockerfile

And do I still need to collect /home/theia-dev/.cache? 

https://github.com/redhat-developer/codeready-workspaces-theia/blob/master/build.sh#L331-L347

**Comment by nickboldt** [comment]
Having moved up to be based on 7.13.x branch of che-theia, I'm now seeing that this section of hte build script is failing:

```
  ${DOCKER} build -t ${CHE_THEIA_IMAGE_NAME} . ${DOCKERFLAGS} \
    --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} --build-arg THEIA_GITHUB_REPO=${THEIA_GITHUB_REPO} --build-arg THEIA_COMMIT_SHA=${THEIA_COMMIT_SHA} \
    2>&1 | tee /tmp/CHE_THEIA_IMAGE_NAME_buildlog.txt
```
https://github.com/redhat-developer/codeready-workspaces-theia/blob/master/build.sh#L384-L399

And the failure is:

```
13:59:56 Step 27/65 : RUN yarn global add node-gyp
13:59:56  ---> Running in 74b5453e6a2c
13:59:56 yarn global v1.21.1
13:59:56 [1/4] Resolving packages...
13:59:56 info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
13:59:56 error Package "" refers to a non-existing file '"/home/theia-dev/eclipse-che-theia-generator"'.
13:59:57 The command '/bin/sh -c yarn global add node-gyp' returned a non-zero code: 1
```
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/608/consoleFull

**Comment by nickboldt** [comment]
And the good news is that I can reproduce the failure locally too.

1. check out crw-theia
2. build.sh

```
git clone git@github.com:redhat-developer/codeready-workspaces-theia.git crw-theia
cd crw-theia
./build.sh --nv 10.20.1 --ctb master --tb master --tgr eclipse-theia/theia --all | tee log.txt
```

**Comment by azatsarynnyy** [comment]
> Also I'm wondering ... if we removed electron, why do we still do this?
> 
> * https://github.com/eclipse/che-theia/blob/7.13.x/dockerfiles/theia/docker/ubi8/builder-post-clone.dockerfile
> * https://github.com/redhat-developer/codeready-workspaces-theia/blob/master/conf/theia/ubi8-brew/builder-post-clone.dockerfile

I guess these sed manipulations aren't needed anymore. WDYT @benoitf?

**Comment by azatsarynnyy** [comment]
> And the good news is that I can reproduce the failure locally too.
> 
> 1. check out crw-theia
> 2. build.sh
> 
> ```
> git clone git@github.com:redhat-developer/codeready-workspaces-theia.git crw-theia
> cd crw-theia
> ./build.sh --nv 10.20.1 --ctb master --tb master --tgr eclipse-theia/theia --all | tee log.txt
> ```

I've run it on my side and the build doesn't move further than
```
STEP 14: RUN nexe -v &&     nexe node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote.js ${NEXE_FLAGS} -o ${HOME}/plugin-remote-endpoint
3.3.2
ℹ nexe 3.3.2
✔ Already downloaded...
⠴ Compiling Node...
```
already more than 30 min. on that stage

**Comment by azatsarynnyy** [comment]
...and still at the same stage
curious why it's so quick on upstream, che-theia...

**Comment by azatsarynnyy** [comment]
the build is finished locally
```
...
Dockerfiles and tarballs generated. See the following folder(s) for content to upload to pkgs.devel.redhat.com:
 - /home/artem/github/redhat-developer/codeready-workspaces-theia/dockerfiles/theia-dev
 - /home/artem/github/redhat-developer/codeready-workspaces-theia/dockerfiles/theia
 - /home/artem/github/redhat-developer/codeready-workspaces-theia/dockerfiles/theia-endpoint-runtime-binary
```

**Comment by nickboldt** [comment]
If I skip the theia ubi-brew step, we get further...

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/612/parsed_console/

But then I have problems downstream in Brew:

* theia-dev: `11:13:16 2020-05-15 15:13:10,419 - atomic_reactor.plugins.imagebuilder - INFO - --> COPY asset-unpacked-generator ${HOME}/eclipse-che-theia-generator`

* theia-endpoint: https://github.com/eclipse/che/issues/16951

**Comment by benoitf** [comment]
fixed: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/622/

**Comment by nickboldt** [comment]
Latest fail in brew:

```
2020-05-20 15:28:16,490 - atomic_reactor.plugins.imagebuilder - INFO - --> RUN yarn global add node-gyp
2020-05-20 15:28:17,177 - atomic_reactor.plugins.imagebuilder - INFO - yarn global v1.21.1
2020-05-20 15:28:17,286 - atomic_reactor.plugins.imagebuilder - INFO - [1/4] Resolving packages...
2020-05-20 15:28:17,301 - atomic_reactor.plugins.imagebuilder - INFO - error Package "" refers to a non-existing file '"/home/theia-dev/eclipse-che-theia-generator"'.
2020-05-20 15:28:17,302 - atomic_reactor.plugins.imagebuilder - INFO - info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
2020-05-20 15:28:17,668 - atomic_reactor.plugins.imagebuilder - INFO - running 'yarn global add node-gyp' failed with exit code 1
2020-05-20 15:28:17,669 - atomic_reactor.plugin - ERROR - Build step plugin imagebuilder failed: image build failed (rc=1): running 'yarn global add node-gyp' failed with exit code 1
```

**Comment by nickboldt** [comment]
theia build was successful in Brew:

http://download.eng.bos.redhat.com/brewroot/work/tasks/9558/28739558/x86_64.log

(for x86_64 anyway).

Commenting out s390x and ppc64le for theia and endpoint and kicking it again...

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/get-sources-rhpkg-container-build/3803/ (success!)

And then the endpoint...

```
16:14:12 COPY asset-theia-endpoint-runtime-pre-assembly-nodejs-static.tar.gz asset-theia-endpoint-runtime-binary-yarn.tar.gz asset-node-src.tar.gz /tmp/
16:14:12 RUN tar xzf /tmp/asset-theia-endpoint-runtime-binary-yarn.tar.gz -C / && rm -f /tmp/asset-theia-endpoint-runtime-binary-yarn.tar.gz && \
16:14:12     export NODE_VERSION=$(node --version | sed -s 's/v//') && mkdir -p "/home/theia/.nexe/${NODE_VERSION}" && tar zxf /tmp/asset-node-src.tar.gz --strip-components=1 -C "/home/theia/.nexe/${NODE_VERSION}" && \
16:14:12     tar zxf /tmp/asset-theia-endpoint-runtime-pre-assembly-nodejs-static.tar.gz -C "/home/theia/"
```

**Comment by nickboldt** [comment]
new tarball added to get-sources-jenkins.sh script...

and we have a green build:

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/get-sources-rhpkg-container-build/3806/console

`registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-theia-rhel8:2.2-1`
