### ISSUE TITLE
Project cloning fails in proxy environment

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17017]
### Describe the bug
1. Deploy Eclipse Che in OpenShift cluster with proxy configuration.
2. Start a workspace.
3. Project cloning failed
```
Extension-Host:Couldn't clone https://github.com/golang/example.git Error: Cloning into '/projects/src/github.com/golang/example'...
fatal: unable to access 'https://github.com/golang/example.git/': Failed to connect to github.com port 443: Operation timed out
    at ChildProcess.<anonymous> (/tmp/theia-unpacked/eclipse_che_workspace_plugin.theia/lib/exec.js:77:36)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
```

### Some investigation
Some thoughts. It is possible to clone the project in the terminal of theia container. `http_proxy` and `https_proxy` env vars present. When the command to clone the project is executed [1] the env are overridden by `askpassEnv`. That's why it fails.

[1] https://github.com/eclipse/che-theia/blob/54f39d621663f597639f4336e80d8d8430083d82/plugins/workspace-plugin/src/exec.ts#L14

### Che version

 - [x] nightly

### Runtime
   - [x] Openshift (include output of `oc version`) 4.x

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
`chectl server:start  --platform openshift --installer operator --self-signed-cert` 
     * provide an output of `chectl version` command
```bash
chectl version
chectl/0.0.20200526-next.86e0f65 linux-x64 node-v10.20.1
```

**Comment by ericwill** [comment]
We'll be taking this one in our next sprint, I believe it's a regression from #16401.
