### ISSUE TITLE
Angular extension pack

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#17109]
Can you please add Angular essential extension pack? https://marketplace.visualstudio.com/items?itemName=johnpapa.angular-essentials It'll make a great difference...

Thanks a lot!
Adham

**Comment by SDAdham** [comment]
I added Angular Language Service but this is what I get in the extension's output:
```
[Error - 11:22:15 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
  Code: -32603 
[Error - 11:22:15 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
  Code: -32603 
[Error - 11:22:15 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
  Code: -32603 
[Error - 11:22:15 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
  Code: -32603 
[Error - 11:22:15 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
  Code: -32603 
/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/node_modules/typescript/lib/tsserverlibrary.js:139878
                this.resolutionCache.startRecordingFilesWithChangedResolutions();
                                     ^

TypeError: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
    at ConfiguredProject.Project.updateGraph (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/node_modules/typescript/lib/tsserverlibrary.js:139878:38)
    at ConfiguredProject.updateGraph (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/node_modules/typescript/lib/tsserverlibrary.js:140804:63)
    at Object.updateProjectIfDirty (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/node_modules/typescript/lib/tsserverlibrary.js:141226:45)
    at ConfiguredProject.Project.getLanguageService (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/node_modules/typescript/lib/tsserverlibrary.js:139540:28)
    at ProjectService.getDefaultLanguageService (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/server/index.js:867:25)
    at Session.sendPendingDiagnostics (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/server/index.js:1024:47)
    at Timeout.diagnosticsTimeout.setTimeout [as _onTimeout] (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/server/index.js:1009:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
[Info  - 11:22:16 AM] Connection to server got closed. Server will 
```

**Comment by l0rd** [comment]
@azatsarynnyy is that failing because of an API is missing Theia side? Have we planned some work on it?

**Comment by azatsarynnyy** [comment]
It fails not because of some missing APIs but because of `Angular Language Service` depends on `typescript` and the extension can not find TS. There was similar issue https://github.com/angular/vscode-ng-language-service/issues/594
Seems TS should be placed in one of the pre-defined location https://github.com/angular/vscode-ng-language-service#versioning

**Comment by azatsarynnyy** [comment]
Maybe, it depends on whether the extension is running in a separate sidecar or in theia-ide sidecar.
@SDAdham if you run it in a dedicated sidecar, could you try running it in theia-ide container?

**Comment by SDAdham** [comment]
Hello @azatsarynnyy , how can I run it in a dedicated sidecar? Can you please provide an example?

**Comment by azatsarynnyy** [comment]
@SDAdham just remove [`spec.containers`](https://github.com/eclipse/che-plugin-registry/blob/41ef2f3d1abf9393b13f2ed8b77c154ad24702fe/v3/plugins/scalameta/metals/1.9.0/meta.yaml#L14) in your `meta.yaml`

**Comment by SDAdham** [comment]
Hello @azatsarynnyy , here is my `meta.yaml` file, I never had `spec.containers` defined:
```
apiVersion: v2
publisher: johnpapa
name: Angular2
version: 9.1.2
type: VS Code extension
displayName: Angular Snippets (Version 9)
title: Angular Snippets (Version 9)
description: Angular version 9 snippets by John Papa
icon: https://github.com/johnpapa/vscode-angular-snippets/blob/master/images/angular-shield.png?raw=true
repository: https://github.com/johnpapa/vscode-angular-snippets
category: Snippet
firstPublicationDate: '2020-03-26'
spec:
  extensions:
    - https://<url>/v3/plugins/johnpapa/Angular2/9.1.2/johnpapa.Angular2-9.1.2.vsix
```

**Comment by azatsarynnyy** [comment]
Based on the `meta.yaml` and this error message
```
TypeError: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
    at ConfiguredProject.Project.updateGraph (/tmp/vscode-unpacked/angular.ng-template.0.901.9.qkbhtgbqoq.Angular.ng-template-0.901.9.vsix/extension/node_modules/typescript/lib/tsserverlibrary.js:139878:38)
```
I think the issue is related to a proper set-up of the extension and TypeScript package https://github.com/angular/vscode-ng-language-service#versioning

I guess Plugins Team can consider adding Angular Plugin to Che Plugin Registry in the future.
cc @ericwill
