### ISSUE TITLE
[chectl] Cannot delete server

### ISSUE THREAD

**Issue by bendavis78** [eclipse-che/che#17375]
### Describe the bug
When I try to delete the server using `chectl server:delete`, I get an error with no useful information.

### Che version
Latest

### Steps to reproduce
Run `chectl server:delete`

### Expected behavior
Chectl server is deleted

### Runtime
kubernetes on Azure. Installed using the following command:

    chectl server:start --installer=helm --platform=k8s --domain=ide.boldidea.org --multiuser

### Environment
Using chectl on linux.

### Command output
```
$ chectl server:delete
› Current Kubernetes context: 'eclipse-che'
You're going to remove Eclipse Che server in namespace 'che' on server 'https://eclipse-ch-eclipsecheresour-207977-ace59654.hcp.southcentralus.azmk8s.io:443'. If you want to continue - press Y: y 
  ✔ Verify Kubernetes API...OK
  ✔ Verify if Eclipse Che is deployed into namespace "che"
  ✔ Check Eclipse Che server status...RUNNING (auth enabled)
  ✖ Delete the Custom Resource of type checlusters.org.eclipse.che
    → [object Object]
    Delete role binding che-operator
    Delete role che-operator
    Delete cluster role binding che-operator
    Delete cluster role che-operator
    Delete server and workspace rolebindings
    Delete service accounts che-operator
    Delete PVC che-operator
    Check if OLM is pre-installed on the platform
    Delete(OLM) custom catalog source eclipse-che-custom-catalog-source
    Delete all deployments
    Delete all services
    Delete all ingresses
    Delete configmaps for Eclipse Che server and operator
    Delete rolebindings che, che-workspace-exec and che-workspace-view
    Delete service accounts che, che-workspace
    Delete PVC postgres-data and che-data-volume
    Purge Eclipse Che Helm chart
    Wait until Eclipse Che pod is deleted
    Wait until Keycloak pod is deleted
    Wait until Postgres pod is deleted
    Wait until Devfile registry pod is deleted
    Wait until Plugin registry pod is deleted
Error: [object Object]
    at KubeHelper.wrapK8sClientError (/usr/local/lib/chectl/lib/api/kube.js:2084:20)
    at KubeHelper.<anonymous> (/usr/local/lib/chectl/lib/api/kube.js:1310:28)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/chectl/node_modules/tslib/tslib.js:108:69)
```

Using chectl 7.14.2

*Kubernetes info*:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-01T16:28:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tolusha** [comment]
@bendavis78
Could you provide more details by updating the description of the issue?

**Comment by vzhukovskii** [comment]
Have the same problem:

```
➜  bin git:(master) ✗ ./run server:delete --skip-deletion-check --skip-kubernetes-health-check
› Current Kubernetes context: 'minikube'
  ↓ Verify Kubernetes API [skipped]
  ✔ Verify if Eclipse Che is deployed into namespace "che"
  ✔ Check Eclipse Che server status...RUNNING (auth disabled)
  ✖ Delete the Custom Resource of type checlusters.org.eclipse.che
    → [object Object]
    Delete role binding che-operator
    Delete role che-operator
    Delete cluster role binding che-operator
    Delete cluster role che-operator
    Delete server and workspace rolebindings
    Delete service accounts che-operator
    Delete PVC che-operator
    Check if OLM is pre-installed on the platform
    Delete(OLM) custom catalog source eclipse-che-custom-catalog-source
    Delete all deployments
    Delete all services
    Delete all ingresses
    Delete configmaps for Eclipse Che server and operator
    Delete rolebindings che, che-workspace-exec and che-workspace-view
    Delete service accounts che, che-workspace
    Delete PVC postgres-data and che-data-volume
    Purge Eclipse Che Helm chart
    Wait until Eclipse Che pod is deleted
    Wait until Devfile registry pod is deleted
    Wait until Plugin registry pod is deleted
Error: [object Object]
    at KubeHelper.wrapK8sClientError (/Users/vlad/Development/chectl/src/api/kube.ts:2037:17)
    at KubeHelper.<anonymous> (/Users/vlad/Development/chectl/src/api/kube.ts:1295:18)
    at Generator.throw (<anonymous>)
    at rejected (/Users/vlad/Development/chectl/src/api/kube.ts:15:65)
```

Server was deployed with the following command:
```
./run server:start --platform=minikube --installer=helm
```

Minikube version:
```
➜  bin git:(master) ✗ minikube version
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1
```

chectl was built from latest revision: https://github.com/che-incubator/chectl/commit/22d296cad4ab63c17ca4ca3cec20f7942a2b493f

**Comment by bendavis78** [comment]
@tolusha I've updated the description. Let me know if that's enough information.

**Comment by tolusha** [comment]
@bendavis78 
I see. thank you.
Fixed by https://github.com/che-incubator/chectl/pull/789
