### ISSUE TITLE
HTML LS can't start

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17381]
### Describe the bug
HTML Language Server is provided to Che Theia though the VS Code built-in extension
https://github.com/eclipse/che-theia/blob/727b6c5a1e650a1357652610b48482a9cc5c9bae/generator/src/templates/theiaPlugins.json#L20

When opening any HTML file, Che Theia shows the error notifications, see the attached screenshots.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Open any HTML file in Che Theia.

### Expected behavior
HTML language features as an autocomplete, hovers, etc. should be provided.

### Screenshots
![image](https://user-images.githubusercontent.com/1636395/87292750-f2f8f180-c509-11ea-8999-dc06a0c24d7b.png)

### Eclipse Che Logs
From HTML Language Server output channel:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:473959)
    at n (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:158)
    at Object.<anonymous> (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:520451)
    at n (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:158)
    at Object.<anonymous> (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:38535)
    at n (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:158)
[Error - 10:08:00 AM] Connection to server got closed. Server will not be restarted.
```

### Additional context
Note, `s.languages.registerOnTypeRenameProvider is not a function` is a known upstream issue https://github.com/eclipse-theia/theia/issues/7987. **Despite that error, HTML LS starts in upstream Theia.**

I've tried with several different versions of `html-language-features` and the result is the same.

First, need to check this path https://github.com/microsoft/vscode/blob/182db07de2745fe3a6369f4ad80ae930e006a99b/extensions/html-language-features/server/src/modes/javascriptLibs.ts#L12

**Comment by shahar-h** [comment]
See: https://github.com/eclipse-theia/theia/pull/8224
