### ISSUE TITLE
Che-theia 7.15.x doesn't compile as part of crw-theia

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17388]
Appears to be a compilation problem building che-theia as crw-theia. Perhaps a lockfile needs updating? 

Has the base version of node changed again? we use 

```
NODE_VERSION=10.19.0
YARN_VERSION=1.17.3
```

and we end up with this failure. Do we need to move to node 10.21.0 and yarn 1.21.1?

```
Step 40/66 : RUN if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     cd plugins && ./foreach_yarn
 ---> Running in 99b7e5e5f8e6

✍️  Process plugin containers-plugin

✍️  Running `yarn` on /home/theia-dev/theia-source-code/plugins/containers-plugin
yarn install v1.21.1
[1/4] Resolving packages...
warning Resolution field "nsfw@1.2.7" is incompatible with requested version "nsfw@^1.2.9"
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
warning @eclipse-che/theia-containers-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
warning @eclipse-che/github-auth-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
warning @eclipse-che/ports-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
warning @eclipse-che/theia-ssh-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
warning task-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
warning @eclipse-che/telemetry-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
warning @eclipse-che/welcome-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
warning @eclipse-che/workspace-plugin@7.15.2: The engine "theiaPlugin" appears to be invalid.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
warning vscode-languageclient@6.1.3: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "tslint@>= 4 < 6".
warning " > ts-jest@22.4.3" has incorrect peer dependency "typescript@2.x".
warning "workspace-aggregator-5b284a2b-3093-4e7d-ba47-09cbbefd8e3f > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-5b284a2b-3093-4e7d-ba47-09cbbefd8e3f > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-5b284a2b-3093-4e7d-ba47-09cbbefd8e3f > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-5b284a2b-3093-4e7d-ba47-09cbbefd8e3f > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
error /home/theia-dev/theia-source-code/che-theia/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/theia-dev/theia-source-code/che-theia/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@10.21.0 | linux | x64
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/theia-dev/theia-source-code/che-theia/node_modules/oniguruma/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/theia-dev/.cache/node-gyp/10.21.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/theia-dev/.cache/node-gyp/10.21.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/theia-dev/.cache/node-gyp/10.21.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/theia-dev/theia-source-code/che-theia/node_modules/oniguruma',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 392, in LoadTargetBuildFile
    includes, True, check)
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 264, in LoadOneBuildFile
    aux_data, includes, check)
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 301, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 244, in LoadOneBuildFile
    None)
  File "/home/theia-dev/.cache/node-gyp/10.21.0/include/node/common.gypi", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/theia-dev/theia-source-code/che-theia/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/usr/bin/node" "/home/theia-dev/theia-source-code/che-theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/theia-dev/theia-source-code/che-theia/node_modules/oniguruma
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     cd plugins && ./foreach_yarn' returned a non-zero code: 1
```

-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/675/consoleText

**Comment by nickboldt** [comment]
Possible solution:

https://github.com/redhat-developer/codeready-workspaces-theia/pull/19

but also need to get these centos RPMs into pkgs.devel repo so they can be installed when building in Brew. So we would have to fetch them and include them as `asset-*` files as part of the crw-theia `build.sh` script.

**Comment by azatsarynnyy** [comment]
From the commit history, I see that:
- yarn was upgraded from 1.17.3 to 1.21.1 in `7.11`
https://github.com/eclipse/che-theia/commit/11dafd373d31645398df308e5e4677b3cac53020#diff-b22accedd99922542bde73879c257601L2
- last time node image has been changed in `7.14`
https://github.com/eclipse/che-theia/commit/da57beef5610738f471d3482c26a0f027407e25a

Let's try with https://github.com/redhat-developer/codeready-workspaces-theia/pull/19

**Comment by nickboldt** [comment]
well, that's weird. Respun it today and it Just Worked. *smdh* I hate node.
