### ISSUE TITLE
Openshift connector is breaking the workspace startup

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17492]
### Describe the bug
When openshift connector is activated, the workspace can't be started anymore.

### Che version

 - [x] 7.15.2 (installed through the operatorhub)

### Steps to reproduce
- Create a new workspace with the Quarkus stack.
- Add the openshift connector plugin from the dashboard and restart
-  The workspace cannot start the workspace. It is looping with back-off

### Runtime
   - [x] Openshift 4.4 (rhpds)

### Screenshots
![image](https://user-images.githubusercontent.com/650571/88564206-39367080-d033-11ea-8cec-a435b4706413.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Additional
Couldn't reproduce in RedHat dogfooding instance and che.openshift.io

**Comment by ericwill** [comment]
I can't reproduce this, do you still see it Sun?

**Comment by sunix** [comment]
Yes I saw it a few weeks ago on RHPDS installed with the Che operator

**Comment by sunix** [comment]
OK I have found more information in the che server logs:
Note that the last line, i have tried with previous version of the plugin, and managed to load the workspace.

```
2020-10-26 14:01:58,173[aceSharedPool-1]  [ERROR] [.IdentityProviderConfigFactory 190]  - Cannot retrieve User OpenShift token from the 'openshift-v4' identity provider
org.eclipse.che.api.core.BadRequestException: Invalid token.
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.doRequest(KeycloakServiceClient.java:197)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.getIdentityProviderToken(KeycloakServiceClient.java:135)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.personalizeConfig(IdentityProviderConfigFactory.java:173)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.buildConfig(IdentityProviderConfigFactory.java:167)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.buildConfig(OpenShiftClientFactory.java:142)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.createOC(OpenShiftClientFactory.java:96)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftRoutes.delete(OpenShiftRoutes.java:84)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:216)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:148)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.cleanUp(KubernetesInternalRuntime.java:281)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:263)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:960)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-10-26 14:01:58,177[aceSharedPool-1]  [ERROR] [.IdentityProviderConfigFactory 190]  - Cannot retrieve User OpenShift token from the 'openshift-v4' identity provider
org.eclipse.che.api.core.BadRequestException: Invalid token.
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.doRequest(KeycloakServiceClient.java:197)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.getIdentityProviderToken(KeycloakServiceClient.java:135)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.personalizeConfig(IdentityProviderConfigFactory.java:173)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.buildConfig(IdentityProviderConfigFactory.java:167)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.buildConfig(OpenShiftClientFactory.java:142)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:89)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesServices.delete(KubernetesServices.java:86)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:216)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:148)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.cleanUp(KubernetesInternalRuntime.java:281)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:263)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:960)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-10-26 14:01:58,180[aceSharedPool-1]  [ERROR] [.IdentityProviderConfigFactory 190]  - Cannot retrieve User OpenShift token from the 'openshift-v4' identity provider
org.eclipse.che.api.core.BadRequestException: Invalid token.
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.doRequest(KeycloakServiceClient.java:197)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.getIdentityProviderToken(KeycloakServiceClient.java:135)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.personalizeConfig(IdentityProviderConfigFactory.java:173)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.buildConfig(IdentityProviderConfigFactory.java:167)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.buildConfig(OpenShiftClientFactory.java:142)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:89)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.delete(KubernetesDeployments.java:872)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:216)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:148)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.cleanUp(KubernetesInternalRuntime.java:281)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:263)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:960)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-10-26 14:01:58,183[aceSharedPool-1]  [ERROR] [.IdentityProviderConfigFactory 190]  - Cannot retrieve User OpenShift token from the 'openshift-v4' identity provider
org.eclipse.che.api.core.BadRequestException: Invalid token.
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.doRequest(KeycloakServiceClient.java:197)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.getIdentityProviderToken(KeycloakServiceClient.java:135)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.personalizeConfig(IdentityProviderConfigFactory.java:173)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.buildConfig(IdentityProviderConfigFactory.java:167)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.buildConfig(OpenShiftClientFactory.java:142)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:89)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesSecrets.delete(KubernetesSecrets.java:86)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:216)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:148)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.cleanUp(KubernetesInternalRuntime.java:281)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:263)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:960)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-10-26 14:01:58,186[aceSharedPool-1]  [ERROR] [.IdentityProviderConfigFactory 190]  - Cannot retrieve User OpenShift token from the 'openshift-v4' identity provider
org.eclipse.che.api.core.BadRequestException: Invalid token.
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.doRequest(KeycloakServiceClient.java:197)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.getIdentityProviderToken(KeycloakServiceClient.java:135)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.personalizeConfig(IdentityProviderConfigFactory.java:173)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.buildConfig(IdentityProviderConfigFactory.java:167)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.buildConfig(OpenShiftClientFactory.java:142)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesClientFactory.create(KubernetesClientFactory.java:89)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesConfigsMaps.delete(KubernetesConfigsMaps.java:87)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:216)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:148)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.cleanUp(KubernetesInternalRuntime.java:281)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:263)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:960)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-10-26 14:01:58,186[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 265]  - Failed to clean up namespace after workspace 'workspacewlvkp3gz15so5p6j' start failing. Cause: Error(s) occurs while cleaning up the namespace. Your session has expired. 
Please <a href='javascript:location.reload();' target='_top'>login</a> to Che again to get access to your OpenShift account Your session has expired. 
Please <a href='javascript:location.reload();' target='_top'>login</a> to Che again to get access to your OpenShift account Your session has expired. 
Please <a href='javascript:location.reload();' target='_top'>login</a> to Che again to get access to your OpenShift account Your session has expired. 
Please <a href='javascript:location.reload();' target='_top'>login</a> to Che again to get access to your OpenShift account Your session has expired. 
Please <a href='javascript:location.reload();' target='_top'>login</a> to Che again to get access to your OpenShift account
2020-10-26 14:01:58,249[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 984]   - Workspace 'user1:postit-app-nut4u' with id 'workspacewlvkp3gz15so5p6j' start failed
2020-10-26 15:45:07,364[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'user1/postit-app-nut4u' with id 'workspacewlvkp3gz15so5p6j' by user 'user1'
2020-10-26 15:50:04,343[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 965]   - Workspace 'user1:postit-app-nut4u' with id 'workspacewlvkp3gz15so5p6j' started by user 'user1'
2020-10-26 16:10:51,779[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 541]   - Workspace 'user1/postit-app-nut4u' with id 'workspacewlvkp3gz15so5p6j' is stopping by user 'user1'
2020-10-26 16:10:52,488[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 1030]  - Workspace 'user1/postit-app-nut4u' with id 'workspacewlvkp3gz15so5p6j' is stopped by user 'user1'
2020-10-26 16:11:07,709[nio-8080-exec-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'user1/postit-app-nut4u' with id 'workspacewlvkp3gz15so5p6j' by user 'user1'
2020-10-26 16:12:29,930[aceSharedPool-4]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 965]   - Workspace 'user1:postit-app-nut4u' with id 'workspacewlvkp3gz15so5p6j' started by user 'user1
```

**Comment by sunix** [comment]
I still can reproduce it. Installation on openshift-4 from the operatorhub

**Comment by sleshchenko** [comment]
it seems to be che plugin broker related issue
```
2021/02/16 09:03:26 Processing plugin redhat/vscode-openshift-connector/latest
2021/02/16 09:03:26   Installing plugin extension 1/4
2021/02/16 09:03:26     Downloading plugin from https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-openshift-tools/vscode-openshift-connector-0.2.0.vsix
2021/02/16 09:04:51 Trying to send event of type 'broker/log' to closed tunnel 'tunnel-1'
```

**Comment by sunix** [comment]
@sleshchenko I have a quickfix: replacing the url to download.jboss.org with openvsix.org.

```yaml
https://github.com/sunix/scratch-kubernetes/blob/master/devfile.yaml#L75-L77
```

**Comment by sunix** [comment]
Closing that issue as it is not related to the openshift connector plugin itself. Created a new issue: https://github.com/eclipse/che/issues/19080

**Comment by benoitf** [comment]
@sunix we wanted to embed vsix files as well in the plug-in registry image
