### ISSUE TITLE
Clean up ending slash in TS_SELENIUM_BASE_URL when run E2E typescript selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17533]
### Is your task related to a problem? Please describe.
There is E2E tests variable `TS_SELENIUM_BASE_URL` which accepts URL with ending slash, like https://codeready-crw-crwctl-tls-oauth.apps.ocp311.crw/

Ending slash "**/**" in turn breaks removal of test workspace, because produces incorrect URL of keycloak token endpoint, with double slashes `//auth`:
```
16:01:22 Property DELETE_WORKSPACE_ON_FAILED_TEST se to true - trying to stop and delete running workspace.
16:01:22 (node:140) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
16:01:22     at createError (/tmp/e2e-codeready/node_modules/axios/lib/core/createError.js:16:15)
16:01:22     at settle (/tmp/e2e-codeready/node_modules/axios/lib/core/settle.js:18:12)
16:01:22     at IncomingMessage.handleStreamEnd (/tmp/e2e-codeready/node_modules/axios/lib/adapters/http.js:192:11)
16:01:22     at emitNone (events.js:111:20)
16:01:22     at IncomingMessage.emit (events.js:208:7)
16:01:22     at endReadableNT (_stream_readable.js:1064:12)
16:01:22     at _combinedTickCallback (internal/process/next_tick.js:138:11)
16:01:22     at process._tickCallback (internal/process/next_tick.js:180:9)
16:01:22 (node:140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
16:01:22 Can not get bearer token. URL used: https://keycloak-crw-crwctl-tls-oauth.apps.ocp311.crw//auth/realms/codeready/protocol/openid-connect/token
16:01:22 Getting id of running workspaces failed. URL used: api/workspace
```

### Describe the solution you'd like
Remove ending slash "**/**" when handle `TS_SELENIUM_BASE_URL` inside the test.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/17539
