### ISSUE TITLE
Running workspace results in IOException: Docker image build failed

### ISSUE THREAD

**Issue by LeeAdcock** [eclipse-che/che#1766]
Running che and docker both installed natively on an RHEL 7.2 server running in EC2. The che server starts successfully, but when starting a Ready-To-Go or custom workspace, it eventually fails with the message "Docker image build failed" and the stack trace below.

**Reproduction Steps:**
1. Install Che
2. Connect in browser and create workspace using one of the default stacks, example: Java.
3. Select the workspace and attempt to run it.

**Expected behavior:**

Expect docker to image to start and be available through Eclipse Che.

**Observed behavior:**

Eclipse Che displays workspace in "starting" state forever.  Following is printed to the console on the Che server.

```
    org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed
            at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:413) ~[che-core-api-machine-4.4.2.jar:4.4.2]
            at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) ~[che-core-api-machine-4.4.2.jar:4.4.2]
            at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:165) ~[che-core-api-machine-4.4.2.jar:4.4.2]
            at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
            at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
            at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
            at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:551) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
            at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.4.2.jar:4.4.2]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
            at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
    Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed
            at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.buildImage(DockerInstanceProvider.java:416) ~[che-plugin-docker-machine-4.4.2.jar:4.4.2]
            at org.eclipse.che.plugin.docker.machine.local.interceptor.EnableOfflineDockerMachineBuildInterceptor.invoke(EnableOfflineDockerMachineBuildInterceptor.java:64) ~[che-plugin-docker-machine-4.]
            at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:315) ~[che-plugin-docker-machine-4.4.2.jar:4.4.2]
            at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:376) ~[che-core-api-machine-4.4.2.jar:4.4.2]
            ... 10 common frames omitted
    Caused by: java.io.IOException: Docker image build failed
            at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:1196) ~[che-plugin-docker-client-4.4.2.jar:4.4.2]
            at org.eclipse.che.plugin.docker.client.DockerConnector.doBuildImage(DockerConnector.java:1092) ~[che-plugin-docker-client-4.4.2.jar:4.4.2]
            at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:290) ~[che-plugin-docker-client-4.4.2.jar:4.4.2]
            at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.buildImage(DockerInstanceProvider.java:408) ~[che-plugin-docker-machine-4.4.2.jar:4.4.2]
            ... 13 common frames omitted
```

**Che version:**    4.4.2
**OS and version:** Red Hat 7.2
**Docker version:** 1.10.3
**Che install:**    server (zip)

**Additional information:**
- I am using the default host uri for the docker daemon.
- My access to the outside Internet from this box is very restricted, and requires the use of a non-transparent proxy, which I believe I have configured correctly.
- This is my first attempt at installing and running my own Che server, so I apologize if this is user error. Would be helpful if the error message would point me in the right direction.

**Comment by TylerJewell** [comment]
@LeeAdcock - thanks for reporting this issue. I do not think we have witnessed this issue previously. If you are willing to take some extra steps we would like some debugging help. 

First, have you attempted to upgrade to Docker 1.11 and run the server?  I do not anticipate that this fixes the issue, but have some questions about this.

Second, which user identity did you run Che under?

Third, have you attempted to build Che's workspace images using docker on the command line?  It's a bit more work, but would like to diagnose whether this is a docker issue for your RHEL instance or not.

**Comment by ghost** [comment]
@LeeAdcock I do not believe it is RHEL specific issue. @TylerJewell has suggested the right thing to do - give it a try with the Docker command line. Smth simple - `docker pull busybox`. If Docker cannot reach DockerHub, it's most likely a proxy issue and this is the page you may want to take a look at in this case - https://docs.docker.com/engine/admin/systemd/#http-proxy

**Comment by LeeAdcock** [comment]
@TylerJewell (1) I'm not able to upgrade to 1.11 given some corporate restrictions. (2) I'm running manually che.sh as the ec2-user, which is setup with UID 1000. (3) I've successfully built and run the workspace from the command line using docker directly.

I don't seem to have the right proxy access to get to the public dockyard, but can reach our internal dockyard and run images from the command line successfully - though not from Che.

**Comment by ghost** [comment]
@LeeAdcock you need to configure Docker then to be able to pull Che images from DockerHub.

**Comment by ghost** [comment]
@LeeAdcock any update on this please?

**Comment by ghost** [comment]
@LeeAdcock I am closing this issue. Feel free to reopen if the issue persists.

**Comment by LeeAdcock** [comment]
Sorry for the delay getting back to you on this, I appreciate the help but got pulled in another direction.

I was able to get past this issue by pulling the source for the docker image from codenvy/dockerfiles and making the necessary adjustments to get it to build successfully. Mainly due to our corporate network I needed to put some additional proxy configuration in place, and make some adjustments to work around being unable to get to the public dockerhub.

_Now that I believe the docker image is starting successfully_, I'm still seeing a timeout error reaching the workspace agent.  Everything is running on a single AWS instance, and the security group is wide open. I would not be at all surprised if it is again something proxy related.  I've attempted to quickly connect to the docker container after it is started by Che to find logs or other clues as to why the agent may not be able to install or start successfully. Netstat indicates only port 22 is open, but I'm unsure of where to find any logs.

I can open a new issue, or can you share any pointers on confirming the agent is installed? Or where I could find documentation on the install agent process? I really do appreciate the help.

**Comment by TylerJewell** [comment]
@eivantsov @l0rd - this is an interesting scenario.

**Comment by l0rd** [comment]
@LeeAdcock Can you provide the complete che-server log and the command line used to start Che?

Anyway if your read "timeout reaching the workspace agent" in the logs of the che-server it means that the server cannot ping the workspace. That's not related to your corporate network. Having #2402 merge should help fixing these these scenarios.

**Comment by ghost** [comment]
@LeeAdcock @l0rd It is usually the firewall that the server cannot reach ws-agent.

You are running Che server natively, correct? Logs will definitely help. I am pretty sure it's `Fail pinging ws-agent at http://.....`

**Comment by LeeAdcock** [comment]
fyi @MattRoop

**Comment by LeeAdcock** [comment]
```
[ec2-user@ip-10-205-73-161 bin]$ ./che.sh

############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
#############################################################

Using CATALINA_BASE:   /data/eclipse-che-4.4.2/tomcat
Using CATALINA_HOME:   /data/eclipse-che-4.4.2/tomcat
Using CATALINA_TMPDIR: /data/eclipse-che-4.4.2/tomcat/temp
Using JRE_HOME:        /
Using CLASSPATH:       /data/eclipse-che-4.4.2/tomcat/conf/://lib/tools.jar:/data/eclipse-che-4.4.2/tomcat/bin/bootstrap.jar:/data/eclipse-che-4.4.2/tomcat/bin/tomcat-juli.jar
2016-09-23 21:22:21,381[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32
2016-09-23 21:22:21,383[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC
2016-09-23 21:22:21,383[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0
2016-09-23 21:22:21,384[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2016-09-23 21:22:21,384[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-327.36.1.el7.x86_64
2016-09-23 21:22:21,384[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2016-09-23 21:22:21,384[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-1.b14.el7_2.x86_64/jre
2016-09-23 21:22:21,384[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_102-b14
2016-09-23 21:22:21,384[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2016-09-23 21:22:21,385[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /data/eclipse-che-4.4.2/tomcat
2016-09-23 21:22:21,385[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /data/eclipse-che-4.4.2/tomcat
2016-09-23 21:22:21,386[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/data/eclipse-che-4.4.2/tomcat/conf/logging.pr
2016-09-23 21:22:21,386[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2016-09-23 21:22:21,386[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
2016-09-23 21:22:21,386[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
2016-09-23 21:22:21,386[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
2016-09-23 21:22:21,386[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2016-09-23 21:22:21,387[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/data/eclipse-che-4.4.2
2016-09-23 21:22:21,387[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/data/eclipse-che-4.4.2/tomcat/logs/
2016-09-23 21:22:21,387[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2016-09-23 21:22:21,387[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2016-09-23 21:22:21,387[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2016-09-23 21:22:21,388[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2016-09-23 21:22:21,388[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/data/eclipse-che-4.4.2/conf/
2016-09-23 21:22:21,388[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/data/eclipse-che-4.4.2/tomcat/endorsed
2016-09-23 21:22:21,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/data/eclipse-che-4.4.2/tomcat
2016-09-23 21:22:21,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/data/eclipse-che-4.4.2/tomcat
2016-09-23 21:22:21,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/data/eclipse-che-4.4.2/tomcat/temp
2016-09-23 21:22:21,440[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-8080"]
2016-09-23 21:22:21,449[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2016-09-23 21:22:21,451[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 254 ms
2016-09-23 21:22:21,490[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for th
2016-09-23 21:22:21,490[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
2016-09-23 21:22:21,491[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32
2016-09-23 21:22:21,530[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /data/eclipse-che-4.4.2/tomcat/webapps/dashboard.war
2016-09-23 21:22:21,730[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /data/eclipse-che-4.4.2/tomcat/webapps/dashboard.war has finish
2016-09-23 21:22:21,731[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /data/eclipse-che-4.4.2/tomcat/webapps/ide.war
2016-09-23 21:22:21,807[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /data/eclipse-che-4.4.2/tomcat/webapps/ide.war has finished in
2016-09-23 21:22:21,808[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /data/eclipse-che-4.4.2/tomcat/webapps/swagger.war
2016-09-23 21:22:21,845[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /data/eclipse-che-4.4.2/tomcat/webapps/swagger.war has finished
2016-09-23 21:22:21,847[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /data/eclipse-che-4.4.2/tomcat/webapps/wsmaster.war
2016-09-23 21:22:23,509[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
2016-09-23 21:22:24,537[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /data/eclipse-che-4.4.2/tomcat/webapps/wsmaster.war has finishe
2016-09-23 21:22:24,538[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory /data/eclipse-che-4.4.2/tomcat/webapps/ROOT
2016-09-23 21:22:24,564[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory /data/eclipse-che-4.4.2/tomcat/webapps/ROOT has finished in 2
2016-09-23 21:22:24,566[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-8080"]
2016-09-23 21:22:24,571[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 3119 ms
2016-09-23 21:28:42,182[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 161]      - Creating machine [ws = workspace3i3o3ybkaeoswds7: env = wksp-g6yz: machine = ws-machine]
2016-09-23 21:28:45,421[kspaceManager-0]  [INFO ] [c.p.d.m.DockerInstanceProvider 578]  - Machine with id 'machinexkgxjbsycsiskla8' backed by container '035cdead27513124416d40e53278354ad758f6
2016-09-23 21:29:45,497[kspaceManager-0]  [ERROR] [.c.a.m.s.w.WsAgentLauncherImpl 103]  - Fail pinging ws agent. Workspace ID:workspace3i3o3ybkaeoswds7. Url:http://localhost:32815/wsagent/ext
2016-09-23 21:29:46,289[kspaceManager-0]  [ERROR] [.c.a.c.u.CompositeLineConsumer 47]   - An error occurred while writing line to the line consumer org.eclipse.che.api.core.util.FileLineConsu
java.io.IOException: Stream closed
        at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116) ~[na:1.8.0_102]
        at java.io.BufferedWriter.write(BufferedWriter.java:221) ~[na:1.8.0_102]
        at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_102]
        at org.eclipse.che.api.core.util.FileLineConsumer.writeLine(FileLineConsumer.java:38) ~[che-core-api-core-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:45) ~[che-core-api-core-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:408) [che-core-api-machine-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) [che-core-api-machine-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:165) [che-core-api-machine-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:551) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.4.2.jar:4.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
2016-09-23 21:29:46,290[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 567]    - Timeout reached. The Che server has been unable to verify that your workspace's agent has successfull
org.eclipse.che.api.machine.server.exception.MachineException: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the worksp
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:413) ~[che-core-api-machine-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) ~[che-core-api-machine-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:165) ~[che-core-api-machine-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
       at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:551) ~[che-core-api-workspace-4.4.2.jar:4.4.2]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.4.2.jar:4.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either
        at org.eclipse.che.api.machine.server.wsagent.WsAgentLauncherImpl.startWsAgent(WsAgentLauncherImpl.java:104) ~[che-core-api-machine-4.4.2.jar:4.4.2]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:383) ~[che-core-api-machine-4.4.2.jar:4.4.2]
        ... 10 common frames omitted

```

**Comment by TylerJewell** [comment]
@LeeAdcock - yep, the suspect line is this one:

```
2016-09-23 21:29:45,497[kspaceManager-0]  [ERROR] [.c.a.m.s.w.WsAgentLauncherImpl 103]  - Fail pinging ws agent. Workspace ID:workspace3i3o3ybkaeoswds7. Url:http://localhost:32815/wsagent/ext
```

This is now - just a configuration issue that has to do with how the Che server is configured to reach each workspace that it creates.  See this section on the docs about how to configure stuff so that the che server can reach the workspace.  https://eclipse-che.readme.io/docs/networking#connectivity.

Also, since you originally posted this, we have a really helpful Che CLI and launcher utility.  They do require other docker images to be downloaded, but if you can download those, they make it easy to configure and test these items.

**Comment by ghost** [comment]
@LeeAdcock Here's what you need to do:

`export CHE_DOCKER_MACHINE_HOST=$Public_EC2_IP`

Also, it looks like the server cannot reach the agent running in a container on localhost. That might be OS specific issue or some security settings.

Can you run the following test?

`docker run -d -p 80:80 nginx`
`curl -v localhost`

**Comment by TylerJewell** [comment]
Closing due to the question being open >60 days.  Ok to reopen with updated diagnostic.
