### ISSUE TITLE
Che Server Local Build - What's the right pattern

### ISSUE THREAD

**Issue by chaitu454** [eclipse-che/che#17660]
## Summary

Che Server Local build - What's the right pattern

## Relevant information

Hi Team,

I have been working some minor customisations to Che Server Code. As a result I need to build che server image from src code.

Steps I am following to do the same are -
1) Check out code from relevant branch or tag.
2) Do the changes in relevant file
3) Build code -
     a. cd che
     b. mvn -DskipTests=true -Dfindbugs.skip=true -Dmdep.analyze.skip=true -Dlicense.skip=true -Pnative clean install

As you can see I am skipping tests and certain processes to save build time still I am building all the modules under Che whether or not I changed them this is because of an **issue in assembly-wsmaster-war module** as it has an ant task to create build-info.properties file created and pushed into classes it's not happening if we build individual modules. 

Infact even in the above full build if any of the modules build fail ( I dont understand why they fail suddenly and in re-run they get build fine) , this file wont get created or pushed into the relevant war though other files in this module gets copied in. 

Irony is the build wont fail even if this file is not created or pushed in but in runtime che wont comeup as it tries to map these properties and can't find this file. Infact I have raised this issue earlier as well.

Hence I need to build the whole application every time even if I just added a Sysout. So here am I missing something or is this the only way to build. Please suggest.

**Comment by chaitu454** [comment]
Second, below is another intermittent issue with local build which happens randomly though I didnt touch anything related to logger . **Please help**

 Context=org.apache.naming.NamingContext@76c3fb7f environment={}
2020-08-20 04:40:22,734[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 175]  - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
java.lang.Error: Unresolved compilation problems: 
	The method bind(Class<ErrorRuntimeLogEventLogger>) from the type AbstractModule refers to the missing type ErrorRuntimeLogEventLogger
	ErrorRuntimeLogEventLogger cannot be resolved to a type

	at org.eclipse.che.api.logger.deploy.LoggerModule.configure(LoggerModule.java:21)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.AbstractModule.install(AbstractModule.java:103)
	at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:206)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:141)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:86)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by skabashnyuk** [comment]
Usually, in a simple case I do:
-  rebuild module with changes (plus dependant)
- rebuild whole assembly https://github.com/eclipse/che/tree/master/assembly
- Build che server image ./build.sh --dockerfile:Dockerfile in https://github.com/eclipse/che/tree/master/dockerfiles/che
 
If that is not helped I think you need to share you changes to get a more concrete answer.

**Comment by chaitu454** [comment]
@skabashnyuk 

Building the specific module is succeeding and definitely I am not changing anything in assembly modules.

Now in next step when I rebuild the assembly module that's when this buildinfo.properties file creation is missing intermittently. If I just rerun the build it gets created . Earlier I wasnt checking for this file till container spinup breaks now after build I am explicitly checking if this file is created in classes but this is tiresome .

build.sh I am just running with out any input which I think I am ok even if it is recreating the other images.

Further above mentioned Compile error is the recent find which is happening intermittently . **Please suggest**

**Comment by skabashnyuk** [comment]
maven version?
java version?

**Comment by chaitu454** [comment]
Chaitanyas-MacBook-Pro:che chaitanyayarrapragada$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/chaitanyayarrapragada/Downloads/Soft/Install/apache-maven-3.6.3
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"
Chaitanyas-MacBook-Pro:che chaitanyayarrapragada$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

**Comment by chaitu454** [comment]
Earlier builds with these same versions are working totally fine. This issue popped up since yesterday night where che container fails to spinup with above error and I have cross checked and this missing class is available in local classes I will check in war fail as well once again.
