### ISSUE TITLE
'Plugins' list is absent in IDE in CHE 'single-host' on k8s

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#17749]
### Describe the bug
* When CHE is installed on k8s with using **single-host** strategy there is absent **Plugins** list in IDE

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Prepare _patch-cr.yaml_ with setted _single-host_ value:
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: 'single-host'
    singleHostExposureType: 'gateway'
```
2. Install CHE using _chectl_:
```

chectl server:start --installer=operator --platform=minikube --che-operator-image=quay.io/lkrejci/che-operator:gateway --che-operator-cr-patch-yaml=<patch-cr.yaml>
```
3. Start workspace from _Get Started_ page on dashboard
4. In IDE select **Plugins**  (Go to **View** -> **Plugins**)

### Expected behavior
* The **Plugins** list should be present in IDE

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)
```
[ashmaraiev@localhost ~]$ minikube version
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1

[ashmaraiev@localhost ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots
![che-single-host-plugins-console-browser](https://user-images.githubusercontent.com/5408906/91574763-e7457b00-e94f-11ea-910c-8b1ab5383bec.png)

### Installation method
   - [x] chectl
```
[ashmaraiev@localhost tmp]$ ./chectl/bin/chectl server:start --platform=minikube -n che-single-host --che-operator-cr-patch-yaml=/home/ashmaraiev/CHE_PROJECTS/che-single-host-cr-patch.yaml
› Current Kubernetes context: 'minikube'
› Installer type is set to: 'operator'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che-single-host"...it is not
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Check Kubernetes version: Found v1.17.3.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.108.nip.io.
    ✔ Checking minikube version... 1.8.2
    ↓ Check if cluster accessible [skipped]
Eclipse Che logs will be available in '/tmp/chectl-logs/1598609877507'
  ✔ Start following logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
  ✔ 🏃‍  Running the Eclipse Che operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che-single-host)...done.
    ✔ Create ServiceAccount che-operator in namespace che-single-host...done.
    ✔ Create Role che-operator in namespace che-single-host...done.
    ✔ Create ClusterRole che-single-host-che-operator...done.
    ✔ Create RoleBinding che-operator in namespace che-single-host...done.
    ✔ Create ClusterRoleBinding che-single-host-che-operator...done.
    ✔ Create CRD checlusters.org.eclipse.che...It already exists.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che-single-host...done.
    ✔ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace che-single-host...done.
  ✔ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Keycloak pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Eclipse Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Retrieving Eclipse Che server URL... https://192.168.99.108.nip.io
    ✔ Eclipse Che status check
  ✔ Retrieving Keycloak admin credentials... admin:PlzZmc4z9Xag
  ✔ Retrieving Che self-signed CA certificate... is exported to /home/ashmaraiev/cheCA.crt
  ✔ Show important messages
    ✔ Autogenerated Keycloak credentials are: "admin:PlzZmc4z9Xag".
    ✔ ❗[MANUAL ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /home/ashmaraiev/cheCA.crt.
   Documentation how to add a CA certificate into a browser: https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-che-with-tls_installing-ch
e-in-tls-mode-with-self-signed-certificates
Command server:start has completed successfully.
```

 ```
[ashmaraiev@localhost tmp]$ ./chectl/bin/chectl -v
chectl/7.18.0 linux-x64 node-v10.22.0
```

### Environment
   - [x] my computer
       - [x] Linux

### Eclipse Che Logs
```
[ashmaraiev@localhost ~]$ kubectl get checluster -n che-single-host -o yaml
apiVersion: v1
items:
- apiVersion: org.eclipse.che/v1
  kind: CheCluster
  metadata:
    creationTimestamp: "2020-08-28T10:18:01Z"
    generation: 13
    name: eclipse-che
    namespace: che-single-host
    resourceVersion: "37829"
    selfLink: /apis/org.eclipse.che/v1/namespaces/che-single-host/checlusters/eclipse-che
    uid: 2f777db9-58ae-470c-bfdd-3539db978283
  spec:
    auth:
      externalIdentityProvider: false
      identityProviderClientId: che-public
      identityProviderPostgresSecret: che-identity-postgres-secret
      identityProviderRealm: che
      identityProviderSecret: che-identity-secret
      identityProviderURL: https://192.168.99.108.nip.io
      openShiftoAuth: true
      updateAdminPassword: false
    database:
      chePostgresDb: dbche
      chePostgresHostName: postgres
      chePostgresPort: "5432"
      chePostgresSecret: che-postgres-secret
      externalDb: false
    k8s:
      ingressDomain: 192.168.99.108.nip.io
      ingressStrategy: single-host
      tlsSecretName: che-tls
    metrics:
      enable: true
    server:
      allowUserDefinedWorkspaceNamespaces: false
      cheDebug: "false"
      cheFlavor: che
      cheHost: 192.168.99.108.nip.io
      cheLogLevel: INFO
      externalDevfileRegistry: false
      externalPluginRegistry: false
      gitSelfSignedCert: false
      selfSignedCert: false
      tlsSupport: true
    storage:
      preCreateSubPaths: true
      pvcClaimSize: 1Gi
      pvcStrategy: common
  status:
    cheClusterRunning: Available
    cheURL: https://192.168.99.108.nip.io
    cheVersion: 7.18.0
    dbProvisioned: true
    devfileRegistryURL: https://192.168.99.108.nip.io/devfile-registry
    keycloakProvisioned: true
    keycloakURL: https://192.168.99.108.nip.io
    openShiftoAuthProvisioned: false
    pluginRegistryURL: https://192.168.99.108.nip.io/plugin-registry/v3
kind: List
metadata:
  resourceVersion: ""
```

**Comment by artaleks9** [comment]
* The way to install CHE 'single-host' which is described is old variant.
I reinstalled CHE 'single-host' on 'minikube using the specific imige of 'che-operator' and 'patch-cr.yaml' (as a correct way -> https://github.com/eclipse/che/issues/16842#issuecomment-686960328) provided by 'platform-team' to re-check this bug, and it is still reproduced.
* CHE 'single-host' which is installed on OCP doesn't have this problem, 'Plugin list' is displayed as expected.

**Comment by mmorhun** [comment]
I did a quick investigation of this issue.
Seems, that the problem is on client (Che Theia) side. There are a lot of rrors in Che Theia logs, like (but for different plugins), here is the example for typescript plugin):
```
2020-09-21 08:40:34.581 root INFO Cannot get https://192.168.39.133.nip.io/v3/plugins/che-incubator/typescript/latest/ Params: Unable to load plugin metadata. unable to verify the first certificate
2020-09-21 08:40:34.581 root INFO Unable go get plugin metadata from https://192.168.39.133.nip.io/v3/plugins/che-incubator/typescript/latest/ 
2020-09-21 08:40:34.584 root INFO Unable to read plugin meta.yaml Params: https://192.168.39.133.nip.io/v3/plugins/che-incubator/typescript/latest/
2020-09-21 08:40:34.588 root ERROR Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) 
2020-09-21 08:40:34.592 root ERROR Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) 
``` 
Which actually means that wrong TLS certificate(s) was used or it wasn't used at all. This is easy to check using terminal in Che Theia container by running the following command:
```sh
curl -v --cacert /tmp/che/secret/ca.crt https://<che-host>/v3/plugins/che-incubator/typescript/latest/
```
which doesn't show such error.

Also there is second error: the wrong url to plugin metadata. As the logs show, there are attempts to query `https://192.168.39.133.nip.io/v3/plugins/che-incubator/typescript/latest/` where the correct url should be `https://192.168.39.133.nip.io/plugin-registry/v3/plugins/che-incubator/typescript/latest/`

**Comment by tolusha** [comment]
Plugin registry URL is defined as env variable in che-server
`CHE_WORKSPACE_PLUGIN__REGISTRY__URL: https://<host>/plugin-registry/v3`
It should be propagated into theia container and reused there.

**Comment by tolusha** [comment]
Request to `api/workspace/settings` returns all needed data
```json
{
  "supportedRecipeTypes": "kubernetes,no-environment",
  "che.workspace.auto_start": "true",
  "cheWorkspacePluginRegistryUrl": "https://192.168.99.101.nip.io/plugin-registry/v3",
  "cheWorkspaceDevfileRegistryUrl": "https://192.168.99.101.nip.io/devfile-registry",
  "che.workspace.storage.available_types": "persistent,ephemeral,async",
  "che.workspace.storage.preferred_type": "persistent"
}
```
