### ISSUE TITLE
.NET Core devfile E2E test is flaky on "Language server autocomplete validation" step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17754]
### Describe the bug
**.NET Core** devfile E2E test is flaky on _Language serve autocomplete validation_ step https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2160/console
```
92 passing (30m)
  3 pending
  3 failing

  1) .NET Core test
       Language server validation
         Suggestion invoking:
     TimeoutError: Wait timed out after 82807ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Editor.<anonymous> (/tmp/e2e/pageobjects/ide/Editor.ts:105:45)
      at Generator.next (<anonymous>)
      at /tmp/e2e/dist/pageobjects/ide/Editor.js:19:71
      at new Promise (<anonymous>)
      at __awaiter (/tmp/e2e/dist/pageobjects/ide/Editor.js:15:12)
      at Editor.waitSuggestionWithScrolling (/tmp/e2e/dist/pageobjects/ide/Editor.js:105:16)
      at Object.<anonymous> (/tmp/e2e/testsLibrary/LsTests.ts:48:22)
      at Generator.next (<anonymous>)
      at fulfilled (/tmp/e2e/dist/testsLibrary/LsTests.js:13:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) .NET Core test
       Language server validation
         Error highlighting:
     TimeoutError: Exceeded maximum visibility checkings attempts, problems with 'StaleElementReferenceError' of 'By(xpath, //div[contains(@style, 'top:418px')]//div[contains(@class, 'squiggly-error')])' element
      at DriverHelper.<anonymous> (/tmp/e2e/utils/DriverHelper.ts:145:15)
      at Generator.throw (<anonymous>)
      at rejected (/tmp/e2e/dist/utils/DriverHelper.js:17:65)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) .NET Core test
       Language server validation
         Autocomplete:
     TimeoutError: Wait timed out after 92753ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Editor.<anonymous> (/tmp/e2e/pageobjects/ide/Editor.ts:105:45)
      at Generator.next (<anonymous>)
      at /tmp/e2e/dist/pageobjects/ide/Editor.js:19:71
      at new Promise (<anonymous>)
      at __awaiter (/tmp/e2e/dist/pageobjects/ide/Editor.js:15:12)
      at Editor.waitSuggestionWithScrolling (/tmp/e2e/dist/pageobjects/ide/Editor.js:105:16)
      at Object.<anonymous> (/tmp/e2e/testsLibrary/LsTests.ts:57:22)
      at Generator.next (<anonymous>)
      at fulfilled (/tmp/e2e/dist/testsLibrary/LsTests.js:13:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

![screenshot-Suggestion_invoking](https://user-images.githubusercontent.com/1197777/91715657-c327ab00-eb96-11ea-9456-da3768189805.png)

### Che version

 - [ ] latest
 - [x] nightly (7.18.0-SNAPSHOT)
 - [ ] other: please specify

### Steps to reproduce
https://github.com/eclipse/che/blob/master/tests/e2e/tests/devfiles/DotNetCore.spec.ts#L52

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

**Comment by ScrewTSW** [comment]
Haven't seen this issue for a while, will have to go through the jobs to make sure and then we can probably close this issue

**Comment by ScrewTSW** [comment]
Confirmed, this issue does not seem to appear anymore, closing.
