### ISSUE TITLE
Java LS initialization error: "Promise rejection is not handled in two seconds: TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17864]
### Describe the bug
Eclipse Che nightly Happy path tests failed on "Java LS initialization" step https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2213/

#### Java LS logs 
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2213/artifact/logs-and-configs/workspace-logs/:
```
Proxyfing exports ws://localhost:2503 vscode.git/_model
{
  message: 'Starting Java server with: /usr/lib/jvm/default-jvm/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /tmp/vscode-unpacked/redhat.java.latest.ubhqfgpvxf.java-0.63.0-2222.vsix/extension/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/theia/home/theia/redhat.java/0.63.0/config_ss_linux -data /home/theia/home/theia/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2020-09-15 01:41:46.155'
}
{
  message: 'Starting Java server with: /usr/lib/jvm/default-jvm/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /tmp/vscode-unpacked/redhat.java.latest.ubhqfgpvxf.java-0.63.0-2222.vsix/extension/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/theia/home/theia/redhat.java/0.63.0/config_linux -data /home/theia/home/theia/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2020-09-15 01:41:46.181'
}
Remote plugin in vscode-javanyp: promise rejection is not handled in two seconds: TypeError: Cannot read property 'id' of undefined
Remote plugin in vscode-javanyp: promise rejection stack trace: TypeError: Cannot read property 'id' of undefined
    at e.$registerDefinitionProvider (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:1422238)
    at e.doInvokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:739824)
    at e.invokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:739557)
    at e.receiveRequest (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:738845)
    at e.receiveOneMessage (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:738332)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:736322
    at https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:740202
    at https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:3154706
    at e.invoke (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:3154925)
    at e.fire (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:3156980)
{
  message: '[Error - 1:42:12 AM] Sep 15, 2020 1:42:12 AM Initialization failed \n' +
    "Could not set the project description for 'spring-petclinic' because the project description file (.project) is out of sync with the file system.\n" +
    "org.eclipse.core.internal.resources.ResourceException(/spring-petclinic)[274]: java.lang.Exception: Could not set the project description for 'spring-petclinic' because the project description file (.project) is out of sync with the file system.\n" +
    '\tat org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)\n' +
    '\tat org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)\n' +
    '\tat org.eclipse.core.internal.resources.Project.setDescription(Project.java:1264)\n' +
    '\tat org.eclipse.m2e.core.project.configurator.AbstractProjectConfigurator.addNature(AbstractProjectConfigurator.java:179)\n' +
    '\tat org.eclipse.m2e.core.project.configurator.AbstractProjectConfigurator.addNature(AbstractProjectConfigurator.java:163)\n' +
    '\tat org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.addJavaNature(AbstractJavaProjectConfigurator.java:193)\n' +
    '\tat org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:146)\n' +
    '\tat org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:122)\n' +
    '\tat org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$2(ProjectConfigurationManager.java:509)\n' +
    '\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)\n' +
    '\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)\n' +
    '\tat org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:503)\n' +
    '\tat org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:294)\n' +
    '\tat org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$0(ProjectConfigurationManager.java:174)\n' +
    '\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)\n' +
    '\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)\n' +
    '\tat org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)\n' +
    '\tat org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1373)\n' +
    '\tat org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:144)\n' +
    '\tat org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:134)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:210)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:108)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:98)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:195)\n' +
    '\tat org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)\n' +
    '\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\n',
  level: 'info',
  timestamp: '2020-09-15 01:42:12.471'
}
PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/redhat.java.latest.fveagscvlg.vscjava.vscode-java-test-0.24.0.vsix/extension/main.js)
Remote plugin in vscode-javanyp: promise rejection is not handled in two seconds: TypeError: Cannot read property 'id' of undefined
Remote plugin in vscode-javanyp: promise rejection stack trace: TypeError: Cannot read property 'id' of undefined
    at e.$registerDefinitionProvider (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:1422238)
    at e.doInvokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:739824)
    at e.invokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:739557)
    at e.receiveRequest (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:738845)
    at e.receiveOneMessage (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:738332)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:736322
    at https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:740202
    at https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:3154706
    at e.invoke (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:3154925)
    at e.fire (https://static.developers.redhat.com/che/theia_artifacts/theia.744bb16ff737c55c6224.js:1:3156980)
```

#### Test logs:
```
  Validation of workspace start
          ▼ DriverHelper.navigateToUrl https://che-che.10.0.106.68.nip.io/dashboard/#/ide/admin/petclinic-dev-environment
01:38:36.154 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "chromeOptions": {
    "args": [
      "--no-sandbox",
      "--disable-web-security",
      "--allow-running-insecure-content",
      "--ignore-certificate-errors"
    ]
  }
}
01:38:36.156 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 85.0.4183.83 (94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}) on port 15860
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
01:38:37.749 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
01:38:37.808 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 4e48859f19e3079793f99e0d184ed96a (org.openqa.selenium.chrome.ChromeDriverService)
          ▼ MultiUserLoginPage.login
          ▼ CheLoginPage.waitEclipseCheLoginFormPage
          ▼ CheLoginPage.inputUserNameEclipseCheLoginPage username: "admin"
          ▼ CheLoginPage.inputPaswordEclipseCheLoginPage password: "admin"
          ▼ CheLoginPage.clickEclipseCheLoginButton
    ✓ Open workspace (8172ms)
          ▼ Ide.waitWorkspaceAndIde
          ▼ Ide.waitAndSwitchToIdeFrame
          ▼ Ide.waitIde
    ✓ Wait workspace running state (125335ms)
          ▼ ProjectTree.openProjectTreeContainer
          ▼ Ide.waitLeftToolbarButton
          ▼ Ide.waitAndClickLeftToolbarButton
          ▼ ProjectTree.waitProjectTreeContainer
          ▼ ProjectTree.waitProjectImported "petclinic" rootSubItem: "src"
          ▼ ProjectTree.expandItem "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
    ✓ Wait until project is imported (8741ms)

  Language server validation
          ▼ ProjectTree.expandPathAndOpenFile "petclinic/src/main/java/org/springframework/samples/petclinic" filename: PetClinicApplication.java
          ▼ ProjectTree.expandPath "petclinic/src/main/java/org/springframework/samples/petclinic"
          ▼ ProjectTree.expandItem "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
          ▼ ProjectTree.expandItem "petclinic/src"
          ▼ ProjectTree.waitItemExpanded "petclinic/src"
          ▼ ProjectTree.expandItem "petclinic/src/main"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
          ▼ ProjectTree.expandItem "petclinic/src/main/java"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework/samples"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework/samples"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework/samples/petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework/samples/petclinic"
          ▼ ProjectTree.clickOnItem "petclinic/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java"
          ▼ ProjectTree.waitItemSelected "petclinic/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java"
          ▼ Editor.waitEditorOpened "PetClinicApplication.java"
          ▼ Editor.waitTab "PetClinicApplication.java"
          ▼ Editor.selectTab "PetClinicApplication.java"
          ▼ Editor.waitTab "PetClinicApplication.java"
          ▼ Editor.clickOnTab "PetClinicApplication.java"
          ▼ Editor.waitTabFocused "PetClinicApplication.java"
          ▼ Ide.checkLsInitializationStart
          ▼ Ide.waitStatusBarContains "Activating Language Support for Java"
Known flakiness has occurred https://github.com/eclipse/che/issues/14944
          ▼ DriverHelper.reloadPage
          ▼ Ide.waitStatusBarContains "Activating Language Support for Java"
    1) Java LS initialization


  3 passing (6m)
  1 failing

  1) Language server validation
       Java LS initialization:
     TimeoutError: Exceeded maximum text obtaining attempts, from the 'By(css selector, div[id='theia-statusBar'])' element
      at DriverHelper.<anonymous> (/tmp/e2e/utils/DriverHelper.ts:619:15)
      at Generator.throw (<anonymous>)
      at rejected (/tmp/e2e/dist/utils/DriverHelper.js:17:65)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: <anonymous>
      at pollCondition (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2191:7
      at new ManagedPromise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at ControlFlow.promise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2505:12)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2190:22
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Ide.<anonymous> (/tmp/e2e/pageobjects/ide/Ide.ts:195:45)
      at Generator.next (<anonymous>)
      at /tmp/e2e/dist/pageobjects/ide/Ide.js:19:71
      at new Promise (<anonymous>)
      at __awaiter (/tmp/e2e/dist/pageobjects/ide/Ide.js:15:12)
      at Ide.waitStatusBarContains (/tmp/e2e/dist/pageobjects/ide/Ide.js:199:16)
      at Object.<anonymous> (/tmp/e2e/tests/e2e_happy_path/HappyPath.spec.ts:96:23)
      at Generator.next (<anonymous>)
      at fulfilled (/tmp/e2e/dist/tests/e2e_happy_path/HappyPath.spec.js:13:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Test scenario: https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Java_LS_initialization (4)](https://user-images.githubusercontent.com/1197777/93177713-e2e4d480-f73b-11ea-8e64-9fb0031fa12c.png)

### Screencast
https://youtu.be/DJSCdeL6vJo

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

**Comment by svor** [comment]
Probably it is because of https://github.com/eclipse/che-plugin-registry/pull/619. Looks like the message in the status bar "Activating Language Support for Java"  which comes from Java LS extension was blocked by the message from Java Test  Runner extension - "Activating Java Test Runner".
cc @ericwill

**Comment by ericwill** [comment]
> Probably it is because of [eclipse/che-plugin-registry#619](https://github.com/eclipse/che-plugin-registry/pull/619). Looks like the message in the status bar "Activating Language Support for Java" which comes from Java LS extension was blocked by the message from Java Test Runner extension - "Activating Java Test Runner".
> cc @ericwill

This is expected behaviour, it sounds like we need to adjust the test case to account for it also.

**Comment by dmytro-ndp** [comment]
@ericwill: am I right that an error in logs `Remote plugin in vscode-javanyp: promise rejection stack trace: TypeError: Cannot read property 'id' of undefined` could be ignored?

**Comment by ericwill** [comment]
> @ericwill: am I right that next error in logs could be ignored?:
> 
> > Remote plugin in vscode-javanyp: promise rejection stack trace: TypeError: Cannot read property 'id' of undefined

I'm not sure if it's directly related to the Java plugin. @svor can you please take a look?

**Comment by svor** [comment]
I still cannot reproduce this problem manually. 
Since we have a fix for Happy path tests https://github.com/eclipse/che/pull/17873 should we remove blocker label from this issue? @dmytro-ndp WDYT

**Comment by dmytro-ndp** [comment]
The issue wasn't beennreproduced during the last several weeks.

**Comment by RomanNikitenko** [comment]
I see this issue again for different PRs of che-theia, [here](https://github.com/eclipse-che/che-theia/pull/1108/checks?check_run_id=2612007814) and [here](https://github.com/eclipse-che/che-theia/pull/1106/checks?check_run_id=2608748664), for example.
