### ISSUE TITLE
Certificates are required for https connection

### ISSUE THREAD

**Issue by windyGex** [eclipse-che/che#1792]
Certificates are required for https connection

**Reproduction Steps:**

./bin/che.sh run

**Expected behavior:**

2016-07-18 19:09:36,883[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
Exception in thread "DockerInstanceStopDetector-0" java.lang.IllegalArgumentException: Certificates are required for https connection.
    at org.eclipse.che.plugin.docker.client.connection.TcpConnection.<init>(TcpConnection.java:41)
    at org.eclipse.che.plugin.docker.client.connection.DockerConnectionFactory.openConnection(DockerConnectionFactory.java:52)
    at org.eclipse.che.plugin.docker.client.DockerConnector.getEvents(DockerConnector.java:1024)
    at org.eclipse.che.plugin.docker.client.DockerConnector.getEvents(DockerConnector.java:999)
    at org.eclipse.che.plugin.docker.machine.DockerInstanceStopDetector.lambda$detectContainersEvents$0(DockerInstanceStopDetector.java:107)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Che version:**    4.4.2
**OS and version:** Mac osx  10.11.1
**Docker version:** Docker version 1.12.0-rc4  
**Che install:**    [ server (zip)]

**Comment by ddementieva** [comment]
Can you check if Docker is working OK by simply running `docker ps` in the Terminal?

Obviously, you've got issues with docker demon running in the Virtualbox.

**Comment by windyGex** [comment]
![image](https://cloud.githubusercontent.com/assets/197348/16935741/769842c6-4d94-11e6-8e63-b0c663aa820f.png)

Is right？

**Comment by ghost** [comment]
@windyGex is this your Mac terminal or you have logged in to the VirtualBox machine? @ddementieva has suggested that you run a random Docker command in your Mac terminal. 

For some reason, Che fails to auto detect DOCKER_HOST i.e. IP of the VM where Docker is running. Can you share output from `ifconfig`?

**Comment by ghost** [comment]
It's Docker Beta for Mac. OK, then. Can you follow recommendations here - https://eclipse-che.readme.io/docs/usage-docker-for-mac?

**Comment by windyGex** [comment]
Ok, I got it. Thx.
