### ISSUE TITLE
The "Terminal.getText" method failed because of the "NoSuchElementError" reason

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#17962]
### Describe the bug
The "Terminal.getText" method failed because of the "NoSuchElementError" reason.
But terminal with a proper title is present.
We should investigate and resolve this problem.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [ ] other: please specify

Error trace
```
09:11:30      NoSuchElementError: The terminal with title '1. Install dependencies (with composer)' has not been found.
09:11:30       at Terminal.getTerminalIndex (/tmp/e2e-codeready/node_modules/e2e/dist/pageobjects/ide/Terminal.js:123:15)
09:11:30       at <anonymous>
09:11:30       at process._tickCallback (internal/process/next_tick.js:188:7)
09:11:30   From: Task: <anonymous>
09:11:30       at pollCondition (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:2195:19)
09:11:30       at /tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:2191:7
09:11:30       at new ManagedPromise (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:1077:7)
09:11:30       at ControlFlow.promise (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:2505:12)
09:11:30       at /tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:2190:22
09:11:30       at TaskQueue.execute_ (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:3084:14)
09:11:30       at TaskQueue.executeNext_ (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:3067:27)
09:11:30       at asyncRun (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:2974:25)
09:11:30       at /tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:668:7
09:11:30       at <anonymous>
09:11:30       at process._tickCallback (internal/process/next_tick.js:188:7)
09:11:30   From: Task: <anonymous wait>
09:11:30       at scheduleWait (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:2188:20)
09:11:30       at ControlFlow.wait (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/promise.js:2517:12)
09:11:30       at thenableWebDriverProxy.wait (/tmp/e2e-codeready/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
09:11:30       at DriverHelper.waitUntilTrue (/tmp/e2e-codeready/node_modules/e2e/dist/utils/DriverHelper.js:509:27)
09:11:30       at Terminal.waitText (/tmp/e2e-codeready/node_modules/e2e/dist/pageobjects/ide/Terminal.js:101:33)
09:11:30       at <anonymous>
09:11:30       at process._tickCallback (internal/process/next_tick.js:188:7)
```
Screenshot:
![screenshot-Run_and_verify_application](https://user-images.githubusercontent.com/22724619/94258254-3eca0d00-ff35-11ea-8d36-a9f20fa83997.png)

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/17963
