### ISSUE TITLE
It's not possible to get access token for CHE with oAuth on OCP 3.11

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#18030]
### Describe the bug
* When Che with oAuth is installed on OCP 3.11 command getting access_token returns _null_.
* Thus  the _chectl:workspace_ commands can't be performed for this case.

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
* Che is installed with oAuth on OCP 3.11
* Login in the Che Dashboard (Note: it's important step, see the [doc](https://www.eclipse.org/che/docs/che-7/administration-guide/authenticating-users/#obtaining-the-token-from-openshift-token-through-keycloak_authenticating-to-the-che-server))
* Perform commands to get access_token (see [PR](https://github.com/che-incubator/chectl/pull/849)):
```
KEYCLOAK_URL="https://$(oc get routes/keycloak -n ${productNamespace} -o jsonpath='{.spec.host}')/auth"
OS_TOKEN=$(oc whoami --show-token)
AT=$(curl -k -X POST -d "client_id=che-public" -d "subject_token=${OS_TOKEN}" -d "subject_issuer=openshift-v3" --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:access_token" $KEYCLOAK_URL/realms/che/protocol/openid-connect/token | jq -r .access_token)
```
### Actual behavior
```
[ashmaraiev@localhost tmp]$ KEYCLOAK_URL=https://keycloak-aleks-che-oauth-test.apps.ocp311.crw/
[ashmaraiev@localhost tmp]$ echo $KEYCLOAK_URL
https://keycloak-aleks-che-oauth-test.apps.ocp311.crw/
[ashmaraiev@localhost tmp]$ OS_TOKEN=$(oc whoami --show-token)
[ashmaraiev@localhost tmp]$ echo $OS_TOKEN 
<some token>

[ashmaraiev@localhost tmp]$ ACCESS_TOKEN=$(curl -k -X POST -d client_id=che-public -d subject_token=$OS_TOKEN -d subject_issuer=openshift-v3 --data-urlencode grant_type=urn:ietf:params:oauth:grant-type:token-exchange --data-urlencode subject_token_type=urn:ietf:params:oauth:token-type:access_token https://keycloak-aleks-che-oauth-test.apps.ocp311.crw/auth/realms/che/protocol/openid-connect/token | jq -r .access_token)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   331  100    81  100   250     88    273 --:--:-- --:--:-- --:--:--   361
[ashmaraiev@localhost tmp]$ echo $ACCESS_TOKEN 
null
[ashmaraiev@localhost tmp]$ 
```

### Expected behavior
* Access_token should be a string value

### Runtime
   - [x] Openshift (include output of `oc version`)
```
[ashmaraiev@localhost ~]$ oc version
Client Version: 4.5.
```

### Installation method
   - [x] chectl

**Comment by tolusha** [comment]
Why did you use `subject_issuer=openshift-v4` ?

**Comment by tolusha** [comment]
If `AT=$(curl ..)` command prints null, pls provide the output the curl command itself

**Comment by artaleks9** [comment]
Fixed command, it was a copy / paste. Actually it is used `openshift-v3`

**Comment by tolusha** [comment]
I need the output just for `curl` command
And what does `oc whoami` prints ?

**Comment by artaleks9** [comment]
* All our clusters OCP when are installed immediately create os provider and users. OCP 3.11 is not exception.
```
- OCP 3.11 instance https://console.ocp311.crw:8443
Add to local /etc/resolv.conf file:
search crw
nameserver 10.0.106.95

< username / password >: 
developer/123 - cluster admin
user/crw4ever!    - regular user without cluster admin rights
admin/crw4ever!  - regular user with cluster admin rights

Login command:
oc login --server=https://console.ocp311.crw:8443 -u=admin -p=crw4ever\! --insecure-skip-tls-verify


```
 ```
[ashmaraiev@localhost ~]$ oc status
In project default on server https://console.ocp311.crw:8443

[ashmaraiev@localhost ~]$ oc whoami
admin

```
* What do you exactly mean about `I need the output just for curl command`?
What I can do for it?

**Comment by tolusha** [comment]
> What I can do for it?

Don't use `$()` and don't pipe the output to `jq` command

**Comment by artaleks9** [comment]
Done.
```
[ashmaraiev@localhost ~]$ curl -k -X POST -d "client_id=che-public" -d "subject_token=${OS_TOKEN}" -d "subject_issuer=openshift-v3" --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:access_token" https://keycloak-aleks-che-oauth-test.apps.ocp311.crw/auth/realms/che/protocol/openid-connect/token
[ashmaraiev@localhost ~]$
```

**Comment by tolusha** [comment]
```

13:51:07,423 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-4) Uncaught server error: java.lang.NullPointerException
--
  | at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.getJsonProperty(AbstractOAuth2IdentityProvider.java:357)
  | at org.keycloak.social.openshift.OpenshiftV3IdentityProvider.extractUserContext(OpenshiftV3IdentityProvider.java:61)
  | at org.keycloak.social.openshift.OpenshiftV3IdentityProvider.extractIdentityFromProfile(OpenshiftV3IdentityProvider.java:87)
  | at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.validateExternalTokenThroughUserInfo(AbstractOAuth2IdentityProvider.java:489)
  | at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.exchangeExternalUserInfoValidationOnly(AbstractOAuth2IdentityProvider.java:548)
  | at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.exchangeExternalImpl(AbstractOAuth2IdentityProvider.java:528)
  | at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.exchangeExternal(AbstractOAuth2IdentityProvider.java:519)
  | at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.exchangeExternalToken(TokenEndpoint.java:917)
  | at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.tokenExchange(TokenEndpoint.java:696)
  | at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:194)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)


```

**Comment by tolusha** [comment]
I would say It has never worked.
Investigation shows that there is and issue with keycloak which has been fixed in 7.0.x version.
Execution the following code [1] [2] leads to NPE since `metadata` field is retrieved twice in row. 
It isn't the case for OpenShift 4.x since we use a patched version of identity provider [3]

[1] https://github.com/keycloak/keycloak/blob/6.0.1/services/src/main/java/org/keycloak/social/openshift/OpenshiftV3IdentityProvider.java#L87
[2] https://github.com/keycloak/keycloak/blob/6.0.1/services/src/main/java/org/keycloak/social/openshift/OpenshiftV3IdentityProvider.java#L59
[3] https://github.com/che-incubator/KEYCLOAK-10169-OpenShift4-User-Provider/blob/master/src/main/java/org/keycloak/social/openshift/OpenshiftV4IdentityProvider.java

**Comment by dmytro-ndp** [comment]
This issue hasn't been reproduced in CRW 2.6.0 https://issues.redhat.com/browse/CRW-1509?focusedCommentId=15684137&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15684137

**Comment by tolusha** [comment]
Interesting. I will check, maybe rh-sso image has been updated since then.

**Comment by tolusha** [comment]
Not actual for CRW deployment but it is still an issue for Eclipse Che.
