### ISSUE TITLE
Git SSH flow E2E UI tests failed on 'Generate a SSH key' step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18063]
### Describe the bug
Git SSH flow E2E UI tests failed on 'Generate a SSH key' step because workspace wasn't ready at the time:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2343/
```
          ▼ TopMenu.selectOption "View"
          ▼ TopMenu.clickOnTopMenuButton "View"
          ▼ Ide.closeAllNotifications
          ▼ NotificationCenter.open
          ▼ NotificationCenter.clickIconOnStatusBar
          ▼ NotificationCenter.waitOpening
          ▼ NotificationCenter.closeAll
          ▼ NotificationCenter.clickCloseAllNotificationsButton
          ▼ NotificationCenter.waitClearNotificationsList
          ▼ TopMenu.clickOnSubmenuItem "Find Command..."
          ▼ QuickOpenContainer.typeAndSelectSuggestion
          ▼ QuickOpenContainer.clickOnContainerItem "SSH: generate key pair..."
          ▼ QuickOpenContainer.waitContainer
    1) Generate a SSH key


  1 passing (1m)
  1 failing

  1) Git with ssh workflow
       Generate a SSH key:
     TimeoutError: Exceeded maximum clicking attempts, the 'By(css selector, div[aria-label="SSH: generate key pair..., picker"])' element is not clickable
      at DriverHelper.waitAndClick (/tmp/e2e/utils/DriverHelper.ts:291:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Tests scenario https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e/GitSsh.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-10-07 10-13-29](https://user-images.githubusercontent.com/1197777/95299167-eaeceb80-0885-11eb-83db-a3e60076e0ef.png)

### Screencast
https://youtu.be/hsII-Al_-Ys

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by dmytro-ndp** [comment]
It's still actual in Eclipse Che 7.24.0-SNAPSHOT https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/3131/console
