### ISSUE TITLE
Can't build latest vscode-python extension 2020.5.86806 due to c++ version (flag -std=c++17 unsupported)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18080]
### Describe the bug

Trying to build https://github.com/microsoft/vscode-python 2020.5.86806

Have installed:
```
 gcc                x86_64    4.8.5-44.el7       rhel-7-server-os-rpms     16 M
 gcc-c++            x86_64    4.8.5-44.el7       rhel-7-server-os-rpms    7.2 M
 cpp                x86_64    4.8.5-44.el7       rhel-7-server-os-rpms    6.0 M
 libgcc             x86_64    4.8.5-44.el7       rhel-7-server-os-rpms    103 k
 libgomp            x86_64    4.8.5-44.el7       rhel-7-server-os-rpms    159 k
 libstdc++          x86_64    4.8.5-44.el7       rhel-7-server-os-rpms    306 k
 libstdc++-devel    x86_64    4.8.5-44.el7       rhel-7-server-os-rpms    1.5 M
```

But build fails due to:

```
gmake[1]: Leaving directory `/mnt/hudson_workspace/workspace/vscode-extensions-packaging/vscode-python/node_modules/zeromq/build/libzmq'
  TOUCH Release/obj.target/libzmq.stamp
  CXX(target) Release/obj.target/zeromq/src/context.o
g++: error: unrecognized command line option ‘-std=c++17’
make: *** [Release/obj.target/zeromq/src/context.o] Error 1
make: Leaving directory `/mnt/hudson_workspace/workspace/vscode-extensions-packaging/vscode-python/node_modules/zeromq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/hudson_workspace/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/mnt/hudson_workspace/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.18.2/bin/node" "/mnt/hudson_workspace/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/hudson_workspace/workspace/vscode-extensions-packaging/vscode-python/node_modules/zeromq
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
```
-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines_Next/job/vscode-extensions-packaging/234/console

Which seems to be similar to:

https://developercommunity.visualstudio.com/content/problem/664095/g-error-unrecognized-command-line-option-stdgnu17.html

So... seems like we need a newer version of gcc > 4.8.5 to solve this, eg., move to a RHEL8 dockerfile solution. 

Downstream: https://issues.redhat.com/browse/CRW-1235

**Comment by nickboldt** [comment]
Note that there's a newer version at https://github.com/microsoft/vscode-python/releases/tag/2020.9.114305 but that one also fails to build on RHEL7 for the same reason.

**Comment by nickboldt** [comment]
Suggestion: instead of building on the local RHEL7 node like this:

```
def buildVscodePython(branchToBuildPlugin, extensionFolder) {
    installNPM()
    // do we need any of these rpms too? llvm-toolset clang clang-libs clang-tools-extra git-clang-format
    sh "sudo yum -y install python36 python3-six python3-pip platform-python-pip \
        curl wget bzip2 sudo \
        gdb make cmake gcc gcc-c++"
    sh "sudo /usr/bin/python3 -m pip install --upgrade pip"
    buildNumber = branchToBuildPlugin.substring(branchToBuildPlugin.lastIndexOf('.') + 1)
    echo "${buildNumber}"
    sh "cd ${extensionFolder} && sudo npm install -g vsce gulp && npm ci && gulp updateBuildNumber --buildNumber ${buildNumber} && rm -rf node_modules"
    archiveSources(extensionFolder)
    sh "cd ${extensionFolder} && npm ci && gulp installPythonLibs && gulp prePublishBundle && vsce package"
}
```

we could provide a dockerfile that would do the same in a UBI8-based image, then extract the artifacts (as we do for the python lang server deps - https://github.com/redhat-developer/codeready-workspaces-deprecated/blob/crw-2.5-rhel-8/python/build.sh#L17-L31 ).

**Comment by nickboldt** [comment]
Obsoleted: https://github.com/redhat-developer/codeready-workspaces-vscode-extensions
