### ISSUE TITLE
[chectl] Failed to deploy several instance of Eclipse Che using `--installer operator`

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18115]
### Describe the bug
Failed to deploy several instance of Eclipse Che using `--installer operator`

### Che version
 - [x] nightly

### Steps to reproduce
1. chectl server:start  --platform minikube -n che1
2. chectl server:start  --platform minikube -n che2
keycloak pod failed to start for the second instance

### Expected behavior
Both instances are deployed succesfully.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
```
$ chectl server:start  --platform minikube -n <>
```
     * provide an output of `chectl version` command
```
$ chectl version
chectl/0.0.20201012-next.a9bbea6 linux-x64 node-v10.22.1
```
### Environment
   - [x] my computer
       - [x] Linux

### Eclipse Che Logs
```
Caused by: javax.resource.ResourceException: IJ031084: Unable to create connection
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:345)
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:352)
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287)
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1325)
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:499)
	at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:632)
	at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:604)
	at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624)
	... 48 more
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "keycloak"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:514)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.connect(Driver.java:256)
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:321)
	... 55 more
```

**Comment by sunix** [comment]
I thought it was the plan to avoid deploying several Che instance in the same k8s cluster. @ibuziuk ?

**Comment by tolusha** [comment]
```bash
$ minikube version
minikube version: v1.14.0
commit: b09ee50ec047410326a85435f4d99026f9c4f5c4
$ chectl version
chectl/7.21.0 linux-x64 node-v10.23.0
```
Can't reproduce anymore
