### ISSUE TITLE
On some project, Quarkus-java code completion is not working. Activating Java test runner is spinning forever.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18118]
### Describe the bug

![Selection_022](https://user-images.githubusercontent.com/650571/96104511-38e29e80-0ed9-11eb-9883-4b1d7fe541a5.png)

Quarkus-java code completion is not working. Activating Java test runner is spinning forever.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start the devfile located in https://github.com/sunix/quarkus-kubernetes-client-service 
2. Open a Java file like KubernetesClientService.java
3. See problems in the screenshot: no code completion, error markers works well, Activating Java Test Runner spinning forever

I couldn't reproduce in Quarkus default stack. I suspect it is the projects size that cause this issue.

### Runtime
   - [x] kubernetes GCP installation
   - [x] Openshift (Red Hat dogfooding instance)

**Comment by sunix** [comment]
I don't know if it is related but:
```
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/__lookupSetter__
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/isPrototypeOf
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/propertyIsEnumerable
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/toString
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/valueOf
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/__proto__
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/toLocaleString
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/get
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/apiVersion to 1.0
LOG:Proxyfing exports ws://localhost:2504 ms-kubernetes-tools.vscode-kubernetes-tools/clusterProviderRegistry
ERROR:Remote plugin in vscode-quarkusan8: promise rejection is not handled in two seconds: TypeError: Cannot read property 'id' of undefined
ERROR:Remote plugin in vscode-quarkusan8: promise rejection stack trace: TypeError: Cannot read property 'id' of undefined
    at e.$registerDefinitionProvider (https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:1422238)
    at e.doInvokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:739824)
    at e.invokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:739557)
    at e.receiveRequest (https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:738845)
    at e.receiveOneMessage (https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:738332)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:736322
    at https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:740202
    at https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:3154707
    at e.invoke (https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:3154926)
    at e.fire (https://static.developers.redhat.com/che/theia_artifacts/theia.5220196328ab49acba51.js:1:3156981)
LOG:PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/redhat.quarkus-java11.latest.upaeafavmf.vscode-java-debug-0.26.0.vsix/extension/dist/extension)
LOG:Debug configuration provider has been registered: java
LOG:PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/redhat.quarkus-java11.latest.nvoolddfat.vscode-quarkus-1.6.0-390.vsix/extension/dist/extension)

```

**Comment by sunix** [comment]
Closing this issue (maybe related to a lombok configuration that was setted in my user preferences)
