### ISSUE TITLE
Happy path tests failed on expanding "Explorer" tree step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18144]
Happy path tests failed on expanding "Explorer" tree step in Che-theia repo PR check:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1770/
![screenshot-Wait_for_workspace_readiness](https://user-images.githubusercontent.com/1197777/96584740-5489e280-12e7-11eb-9edd-34105623c91b.png)
```
    ✓ Open workspace (4046ms)
          ▼ Ide.waitAndSwitchToIdeFrame
          ▼ Ide.waitPreloaderVisible
          ▼ Ide.waitPreloaderAbsent
          ▼ Ide.waitIde
          ▼ ProjectTree.openProjectTreeContainer
          ▼ Ide.waitLeftToolbarButton
          ▼ Ide.waitAndClickLeftToolbarButton
          ▼ ProjectTree.waitProjectTreeContainer
          ▼ ProjectTree.waitProjectImported "petclinic" rootSubItem: "src"
          ▼ ProjectTree.expandItem "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
The 'petclinic' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic"
The 'petclinic' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic"
The 'petclinic' item has not been expanded, try again
    1) Wait for workspace readiness


  1 passing (1m)
  1 failing

  1) Validation of workspace start
       Wait for workspace readiness:
     TimeoutError: Wait timed out after 11648ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at ProjectTree.expandItem (/tmp/e2e/pageobjects/ide/ProjectTree.ts:147:45)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1771/
![screenshot-Java_LS_initialization](https://user-images.githubusercontent.com/1197777/96584578-1bea0900-12e7-11eb-8717-c2875b6936c7.png)

```
  Language server validation
          ▼ ProjectTree.expandPathAndOpenFile "petclinic/src/main/java/org/springframework/samples/petclinic" filename: PetClinicApplication.java
          ▼ ProjectTree.expandPath "petclinic/src/main/java/org/springframework/samples/petclinic"
          ▼ ProjectTree.expandItem "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
          ▼ ProjectTree.expandItem "petclinic/src"
          ▼ ProjectTree.waitItemExpanded "petclinic/src"
The 'petclinic/src' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src"
The 'petclinic/src' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src"
          ▼ ProjectTree.expandItem "petclinic/src/main"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
The 'petclinic/src/main' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
The 'petclinic/src/main' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
The 'petclinic/src/main' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
The 'petclinic/src/main' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
          ▼ ProjectTree.expandItem "petclinic/src/main/java"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
The 'petclinic/src/main/java' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
The 'petclinic/src/main/java' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
The 'petclinic/src/main/java' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
The 'petclinic/src/main/java' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
The 'petclinic/src/main/java' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
The 'petclinic/src/main/java' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
The 'petclinic/src/main/java' item has not been expanded, try again
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org"
The 'petclinic/src/main/java/org' item has not been expanded, try again
    1) Java LS initialization


  2 passing (4m)
  1 failing

  1) Language server validation
       Java LS initialization:
     TimeoutError: Wait timed out after 81291ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at ProjectTree.expandItem (/tmp/e2e/pageobjects/ide/ProjectTree.ts:147:45)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by RomanNikitenko** [comment]
Maybe related to https://github.com/eclipse/che/issues/18151

**Comment by rhopp** [comment]
The problem was not in tests. 
As a temporary solution, che-theia was pinned to specific commit in eclipse-theia (https://github.com/eclipse/che-theia/pull/886) to make thigs work, while investigation happens in https://github.com/eclipse/che/issues/18151
