### ISSUE TITLE
Go to Definition doesn't work in java stacks

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#18175]
### Describe the bug
Go to definition action is not active and Ctrl+F11 doesn't work as well in java stacks. In the java-plugin output console i see next errors:
```log
ERROR:Remote plugin in vscode-javaoq0: promise rejection stack trace: TypeError: Cannot read property 'id' of undefined
    at e.$registerDefinitionProvider (https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:1494974)
    at e.doInvokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:765542)
    at e.invokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:765275)
    at e.receiveRequest (https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:764563)
    at e.receiveOneMessage (https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:764050)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:762040
    at https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:765920
    at https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:3323503
    at e.invoke (https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:3323722)
    at e.fire (https://static.developers.redhat.com/che/theia_artifacts/theia.b9818e4da33d00c81a49.js:1:3325777)
``` 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to che.openshift.io
2. Create Java Maven workspace
3. Open HelloWorld.java
4. Wait when Java LS will be initialized
5. Go to line 10 column 45 and try to use Go to Definition feature

### Expected behavior
Go to Definition should be active and point to the definition of variable a

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![screenshot-che openshift io-2020 10 22-17_09_03](https://user-images.githubusercontent.com/1271546/96883642-5095c600-1489-11eb-988e-9ae8c5289bcc.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
@svor is this with che-theia next or latest?

**Comment by svor** [comment]
@tsmaeder with both
