### ISSUE TITLE
Fail to list namespaces when username contains non-DNS characters, which breaks workspace creation for that user

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18176]
### Describe the bug

When username contains some non-DNS characters (for example `@`), Che-server fails to list namespaces and we can't start a new workspace.

It's caused by https://github.com/eclipse/che/pull/18090 where we introduced search labeled namespaces as a first step. The default namespace labels property `che.infra.kubernetes.namespace.labels` contains `<username>` placeholder, so the get request fails completely, because labels can't have non-DNS characters at all.

❗ If we won't make it before the release, we should revert https://github.com/eclipse/che/pull/18090 to not change the configuration property that is already in.

### Che version
 - [x] nightly

### Steps to reproduce
1. have username with invalid characters, for example email
   1. I did that with openshift user, then using openshift oauth and manually added my user into keycloak
1. login with that user and try to create new workspace "Custom workspace" page.
1. You'll see no namespace there, and you can't start new workspace without namespace
1. See che-server logs for the exception

### Expected behavior

Email username must work as any other valid username.

### Proposed solution
Label namespaces without placeholders, only saying it's Che Workspace 
```
app.kubernetes.io/part-of: che.eclipse.org
app.kubernetes.io/component: workspace
```
Introduce second property to define annotation with `<username>` placeholder. Admin will then label the namespace with:
```
che.eclipse.org/username: <username>
```
We then request all che workspaces namespaces from kubernetes, and further filter it down by annotation in che code.

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots

![20201022_163854_888x288_scrot](https://user-images.githubusercontent.com/1160903/96887671-1a564780-1485-11eb-82a8-9be686fbf036.png)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

### Eclipse Che Logs

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.25.0.1/apis/project.openshift.io/v1/projects?labelSelector=che.eclipse.org%2Fusername%3Dtester%40tester.cz%2Capp.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspace. Message: unable to parse requirement: invalid label value: "tester@tester.cz": at key: "che.eclipse.org/username": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=unable to parse requirement: invalid label value: "tester@tester.cz": at key: "che.eclipse.org/username": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:621)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProjectFactory.findLabeledNamespaces(OpenShiftProjectFactory.java:198)
	... 51 common frames omitted
```

### Additional context

https://github.com/eclipse/che/pull/18090

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che/pull/18185 and https://github.com/eclipse/che-docs/pull/1659
