### ISSUE TITLE
Happy path e2e test failed on Java LS validation step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18193]
### Describe the bug
Happy path e2e test failed on Java LS validation step:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2584/

![screenshot-Java_LS_initialization (1)](https://user-images.githubusercontent.com/1197777/97155131-900c2d00-177d-11eb-8475-9e25d28e674f.png)
```
          ▼ MultiUserLoginPage.login
          ▼ CheLoginPage.waitEclipseCheLoginFormPage
          ▼ CheLoginPage.inputUserNameEclipseCheLoginPage username: "admin"
          ▼ CheLoginPage.inputPaswordEclipseCheLoginPage password: "admin"
          ▼ CheLoginPage.clickEclipseCheLoginButton
    ✓ Open workspace (4297ms)
          ▼ Ide.waitAndSwitchToIdeFrame
          ▼ Ide.waitPreloaderVisible
          ▼ Ide.waitPreloaderAbsent
          ▼ Ide.waitIde
          ▼ ProjectTree.openProjectTreeContainer
          ▼ Ide.waitLeftToolbarButton
          ▼ Ide.waitAndClickLeftToolbarButton
          ▼ ProjectTree.waitProjectTreeContainer
          ▼ ProjectTree.waitProjectImported "petclinic" rootSubItem: "src"
          ▼ ProjectTree.expandItem "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
    ✓ Wait for workspace readiness (67402ms)

  Language server validation
          ▼ ProjectTree.expandPathAndOpenFile "petclinic/src/main/java/org/springframework/samples/petclinic" filename: PetClinicApplication.java
          ▼ ProjectTree.expandPath "petclinic/src/main/java/org/springframework/samples/petclinic"
          ▼ ProjectTree.expandItem "petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic"
          ▼ ProjectTree.expandItem "petclinic/src"
          ▼ ProjectTree.waitItemExpanded "petclinic/src"
          ▼ ProjectTree.expandItem "petclinic/src/main"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
          ▼ ProjectTree.expandItem "petclinic/src/main/java"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework/samples"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework/samples"
          ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework/samples/petclinic"
          ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework/samples/petclinic"
          ▼ ProjectTree.clickOnItem "petclinic/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java"
          ▼ ProjectTree.waitItemSelected "petclinic/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java"
          ▼ Editor.waitEditorOpened "PetClinicApplication.java"
          ▼ Editor.waitTab "PetClinicApplication.java"
          ▼ Editor.selectTab "PetClinicApplication.java"
          ▼ Editor.waitTab "PetClinicApplication.java"
          ▼ Editor.clickOnTab "PetClinicApplication.java"
          ▼ Editor.waitTabFocused "PetClinicApplication.java"
          ▼ Ide.checkLsInitializationStart
          ▼ Ide.waitStatusBarContains "Activating Language Support for Java"
Known flakiness has occurred https://github.com/eclipse/che/issues/17864
          ▼ Ide.waitStatusBarContains "Activating Java Test Runner"
    1) Java LS initialization


  2 passing (5m)
  1 failing

  1) Language server validation
       Java LS initialization:
     TimeoutError: Wait timed out after 181107ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Ide.waitStatusBarContains (/tmp/e2e/pageobjects/ide/Ide.ts:214:45)
      at Context.test (/tmp/e2e/tests/e2e_happy_path/HappyPath.spec.ts:90:23)
      at <anonymous>
```

Test workspace devfile: https://github.com/eclipse/che/blob/60566a14a5c76b4d1b842daf17a9bee1e74b2f2a/tests/e2e/files/happy-path/happy-path-workspace.yaml

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Screencast
https://youtu.be/MzHjXG4rRSY

### Steps to reproduce
https://github.com/eclipse/che/blob/60566a14a5c76b4d1b842daf17a9bee1e74b2f2a/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Expected behavior
There is `Activating Java Test Runner` or `Activating Java Test Runner` messages in IDE status bar.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl/0.0.20201022-next.2bbd800 linux-x64 node-v10.22.1
```
chectl server:start --k8spodreadytimeout=180000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=custom-resource-patch.yaml --chenamespace=eclipse-che
```
where custom-resource-patch.yaml:
```
spec:
  server:
    cheImage: 'quay.io/eclipse/che-server'
    cheImageTag: 'nightly'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '-1'
  auth:
    updateAdminPassword: false
```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify

**Comment by svor** [comment]
Hello, it could be happened because `redhat/java` and `redhat/java11` plugins were updated to use latest VSCode java extension. To start Java LS initialization automatically we have to change tested devfile by adding a preference:
```yaml
preferences:
      java.server.launchMode: Standard
```
 like it was done here: https://github.com/eclipse/che-devfile-registry/pull/297/files#diff-c7c09a22f504c0bad1296d688b29f24ff78dd7cd55dd913765928bbc694b9050R17

**Comment by dmytro-ndp** [comment]
@svor: thank you for information!

**Comment by l0rd** [comment]
@svor if that's the default behavior can't we set it at the meta.yaml level?

**Comment by benoitf** [comment]
@l0rd https://github.com/eclipse/che/issues/17975
