### ISSUE TITLE
Issue setting up Che with Kind

### ISSUE THREAD

**Issue by Destreyf** [eclipse-che/che#18262]
### Describe the bug
Cannot deploy on kind using chectl.

Postgres seems to be failing, this has been mentioned (and closed) in the past.

https://github.com/eclipse/che/issues/14426

However I don't see a resolution in that, and following the instructions on the kind install page result in a similar permission failed error for postgres.  I tried with latest and nightly.

### Che version
 - [X] latest
 - [X] nightly
 - [ ] other: please specify

### Steps to reproduce
On a clean single node, setup a KinD cluster and try the steps in the KinD documentation.

### Expected behavior
I'd like to be able to use Che.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [X] other: kind using 1.9.1, kubectl

### Installation method
   - [X] chectl
     * chectl server:deploy --installer operator --platform k8s --domain 172.17.250.1.nip.io
     * pchectl/0.0.20201102-next.9304a68 linux-x64 node-v10.23.0 (latest stable same issue)
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [X] other: Self hosted VPS on Proxmox, clean debian 10 install with docker and kind installed.

### Eclipse Che Logs
`/root/.cache/chectl/error.log`
```
2020-11-02T18:44:06.546Z Error: Error: Failed to start a pod, reason: CrashLoopBackOff, message: back-off 10s restarting failed container=postgres pod=postgres-58576b74-ls6lw_che(44d4223d-99ab-4788-bc77-f29ee64e0646)
2020-11-02T18:44:06.546Z Installation failed. Error log: /root/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1604342594217
2020-11-02T18:44:06.546Z     at Object.error (/usr/local/lib/chectl/node_modules/@oclif/errors/lib/index.js:26:15)
2020-11-02T18:44:06.546Z     at Deploy.error (/usr/local/lib/chectl/node_modules/@oclif/command/lib/command.js:60:23)
2020-11-02T18:44:06.546Z     at Deploy.<anonymous> (/usr/local/lib/chectl/lib/commands/server/deploy.js:240:22)
2020-11-02T18:44:06.546Z     at Generator.next (<anonymous>)
2020-11-02T18:44:06.546Z     at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:112:62)
```
---
`/tmp/chectl-logs/1604342594217/che/postgres-58576b74-ls6lw/postgres.log`
```
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

**Comment by tolusha** [comment]
Could you have a look pls, it might help you.
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-kind/

**Comment by Destreyf** [comment]
That is the exact guide I used, it does not appear to work, the posters instance/pod never comes up due to a filesystem permission issue as referenced in the logs
