### ISSUE TITLE
Error while using mongodb extension on Eclipse Che 

### ISSUE THREAD

**Issue by abhsange** [eclipse-che/che#18315]
Eclipse Che : v 7.17.2 
VS Code extension link : https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode

Trying to use VS Code extension MongoDB extension on Eclipse Che, however while loading the extension getting below error 

```
Extension-Host:Could not load electron Cannot find module 'electron'
Require stack:
- /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js
- /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js
- /home/theia/node_modules/@eclipse-che/theia-remote/lib/node/plugin-host-custom.js
Extension-Host:TypeError: e.modules.indexOf is not a function
    at Object.isEnterprise (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:246:337965)
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:246:300589
    at m (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:9:367615)
    at handleCallback (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:1:4736)
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:89596
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:266740
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:281186
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:275549
    at e.exports.<anonymous> (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:58498)
    at e.exports.emit (events.js:315:20)
Extension-Host:TypeError: r.databases.map is not a function
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:246:302820
    at m (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:9:367615)
    at handleCallback (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:1:4736)
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:89596
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:266740
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:281186
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:275549
    at e.exports.<anonymous> (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:58498)
    at e.exports.emit (events.js:315:20)
    at e (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:282308)
Extension-Host:No tree item with id 'b31524c7-c8ad-413e-8518-684b97592421-1604932875438' found.
```

Is it issue with VSCode compatibility of Eclipse Che or extension ? How can it be resolved ?

**Comment by benoitf** [comment]
@abhsange I would say the dependency on Electron might be an issue

**Comment by abhsange** [comment]
@benoitf same version of extension (0.2.1) works correctly on VSCode without doing anything else. So I'm thinking whether issue is related to support by Che-Theia to run this VSCode extension or packaging of extension ?
