### ISSUE TITLE
7.20.1 -> 7.21.2 Rollout update failed initially and only succeed on the third attempt 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18387]
### Describe the bug

7.20.1 -> 7.21.2 Rollout update failed initially and only succeed on the third attempt 

logs from the failed pods https://gist.github.com/ibuziuk/87b9e238617aa7a2a351f57e34da3e82

Rollout update succed only on the third attempt

### Che version

 - 7.21.2

```
1) Tried proxying org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisionerProvider to support a circular dependency, but it is not an interface.
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisionerProvider<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>
    for the 3rd parameter of org.eclipse.che.workspace.infrastructure.kubernetes.provision.GatewayTlsProvisioner.<init>(GatewayTlsProvisioner.java:45)
  at org.eclipse.che.workspace.infrastructure.kubernetes.provision.GatewayTlsProvisioner.class(GatewayTlsProvisioner.java:45)
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.provision.GatewayTlsProvisioner<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisioner<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment> annotated with @com.google.inject.internal.Element(setName=,uniqueId=92, type=MAPBINDER, keyType=org.eclipse.che.workspace.infrastructure.kubernetes.server.WorkspaceExposureType)
  while locating java.util.Map<org.eclipse.che.workspace.infrastructure.kubernetes.server.WorkspaceExposureType, org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisioner<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>>
    for the 3rd parameter of org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisionerProvider.<init>(TlsProvisionerProvider.java:35)
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.provision.TlsProvisionerProvider<org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment>
    for the 3rd parameter of com.redhat.che.multitenant.RhCheInfraEnvironmentProvisioner.<init>(RhCheInfraEnvironmentProvisioner.java:110)
  at com.redhat.che.multitenant.RhCheInfraEnvironmentProvisioner.class(RhCheInfraEnvironmentProvisioner.java:67)
  while locating com.redhat.che.multitenant.RhCheInfraEnvironmentProvisioner
  while locating org.eclipse.che.workspace.infrastructure.openshift.OpenShiftEnvironmentProvisioner

1 error
at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
at com.google.inject.Guice.createInjector(Guice.java:87)
at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:141)
at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:86)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
"}

```

**Comment by ibuziuk** [comment]
Happed again during `7.22.0` promotion to staging (succeed only on the 4th restart)

**Comment by ibuziuk** [comment]
Closing as obsolete
