### ISSUE TITLE
Failure to start second workspace of a user on Openshift infrastructure

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#18536]
### Describe the bug
While I was working on a workspace start bug for Kubernetes infra, I discovered this problem.
If a user tries to start second workspace while the first one is still running, then the socond workspace failes to start.
The reason of the failure is that Che server tries to create `ca-certs` config map that already exists in the namespace (the configmap was created for the first workspace). The exception prevents second workspace from successful start.

### Che version
nightly

### Steps to reproduce
1. Deploy Eclipse Che on Openshift infrastructure (CRC possible too)
2. Allow starting several workspaces simultaneously by patching CR:
```yaml
spec:
  server:
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "10"
```
3. Start a workspace
4. Without stopping previous one, try to start second workspace.

### Expected behavior
It is possible to start as many workspaces as needed.

### Runtime
Openshift

### Installation method
chectl using operator installer

### Environment
 - my computer (Linux)
 - cluster bot

### Eclipse Che Logs

Second workspace of the user start log:
```log
Error: Failed to run the workspace: "Failure executing: POST at: https://172.25.0.1/api/v1/namespaces/myusername-che/configmaps. Message: configmaps "ca-certs" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=ca-certs, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "ca-certs" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
```

<details>
<summary>Che server logs</summary>

```log
2020-12-04 11:07:52,292[aceSharedPool-1]  [WARN ] [.c.w.i.k.n.KubernetesNamespace 193]  - Can't label the namespace due to lack of permissions. Grant cluster-wide permissions to `get` and `update` the `namespaces` to the `che` service account (Che operator might have already prepared a cluster role called `che-namespace-editor` for this, depending on its configuration). Alternatively, consider disabling the feature by setting `che.infra.kubernetes.namepsace.label` to `false`.
2020-12-04 11:07:55,751[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspacej47xvrinfedlnelf.
org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Failure executing: POST at: https://172.25.0.1/api/v1/namespaces/myusername-che/configmaps. Message: configmaps "ca-certs" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=ca-certs, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "ca-certs" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesConfigsMaps.create(KubernetesConfigsMaps.java:75)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.DeployBroker.execute(DeployBroker.java:98)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.PrepareStorage.execute(PrepareStorage.java:76)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.ListenBrokerEvents.execute(ListenBrokerEvents.java:63)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:129)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:90)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.provisionWorkspace(KubernetesInternalRuntime.java:288)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:204)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:969)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.25.0.1/api/v1/namespaces/myusername-che/configmaps. Message: configmaps "ca-certs" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=ca-certs, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "ca-certs" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:251)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:815)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:333)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesConfigsMaps.create(KubernetesConfigsMaps.java:73)
	... 16 common frames omitted
2020-12-04 11:07:55,945[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 995]   - Workspace 'myusername:golang-opaz6' with id 'workspacej47xvrinfedlnelf' start failed
```
</details>

### Additional context
This problem is not reproducible on Kubernetes infrastructure. The reason is [this condition](https://github.com/eclipse/che/blob/286459283ad2097d7c177df829033f785a2e21ea/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/KubernetesTrustedCAProvisioner.java#L117-L119). When second workspace starts on Kubernetes then both configmaps have the same data inside and a new config map isn't added to provisioner. In case of Openshift, they are always different. The reason is the `config.openshift.io/inject-trusted-cabundle=true` label which makes Openshift add `ca-bundle.crt` field into the config map. So, they are most of the time (except cluster proxy config has additional CAs and the field is propagated to the source config map by operator) different and provisioner adds the config map to be propagated. Later, when Kubernetes objects is creating from the configs it fails [here](https://github.com/eclipse/che/blob/5e72b9edc7dadf9a9d11597ebbd2b9416e9fc992/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesConfigsMaps.java#L75) (the invocation is [here](https://github.com/eclipse/che/blob/14cea1b912956549cd476db6d0dc70d770c64b01/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/DeployBroker.java#L98)) as config map with the same name already exists in the namespace.

**Comment by sleshchenko** [comment]
Faced the same when used multiple Che instances for the same user.

**Comment by nebula0248** [comment]
+1 I have the same issue. I tried both Eclipse Che and Red Hat Codeready Workspaces operators, and both have this issue.
