### ISSUE TITLE
Not able to start Theia based workspace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18552]
### Describe the bug
Not able to start Theia based workspace

### Che version

 - 7.23.0-SNAPSHOT
### Steps to reproduce
1. deploy latest che-server
2. Start workspace
```yam
apiVersion: 1.0.0
metadata:
  name: wksp-custom-zkuna
```
3. You'll see Theia's loading screen

### Expected behavior
Fully loaded workspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Знімок екрана 2020-12-07 о 15 55 51](https://user-images.githubusercontent.com/1614429/101364368-279b8a00-38ab-11eb-839a-d0f5bcd90053.png)

![Знімок екрана 2020-12-07 о 17 34 48](https://user-images.githubusercontent.com/1614429/101370829-a942e600-38b2-11eb-955a-754a2f6c92f4.png)

<img width="1680" alt="Знімок екрана 2020-12-07 о 18 00 42" src="https://user-images.githubusercontent.com/1614429/101373967-405d6d00-38b6-11eb-992c-efc6aa820e83.png">
<img width="1679" alt="Знімок екрана 2020-12-07 о 18 03 26" src="https://user-images.githubusercontent.com/1614429/101374200-8c101680-38b6-11eb-8df0-2acd999a8ec5.png">

### Installation method
 - chectl/7.22.2 darwin-x64 node-v10.23.0
- `chectl server:start --installer=operator   --platform=openshift  -n che`
### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
```
 at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:08.606 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:20.894 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:33.182 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:49.566 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:59:05.950 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:59:18.238 root ERROR Uncaught Exception:  Params: [object Object]                                                                                                                              │
│ 2020-12-07 13:59:26.430 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)
```

**Comment by azatsarynnyy** [comment]
I've just checked it on my local minikube with `cheimage=quay.io/eclipse/che-server:nightly`.
I don't see any unusual behavior.

**Comment by tsmaeder** [comment]
@skabashnyuk could we get the full devfile?

**Comment by azatsarynnyy** [comment]
> Start workspace
> apiVersion: 1.0.0
> metadata:
>   name: wksp-custom-zkuna
> 

I guess it is full.

**Comment by sparkoo** [comment]
I was able to run latest master on minikube

**Comment by skabashnyuk** [comment]
>I guess it is full.

Yes.

**Comment by skabashnyuk** [comment]
this issue about OpenShift 4.6

**Comment by skabashnyuk** [comment]
84f83abfc75911e10d309fad57721916eaaac472 - not working 
b562d092c6 - not working  Describe-1607362034692675000.yml
c366ed6a88 - working Describe-1607361391658619000.yml
8f7083b1d2f9f55d3e358cb18bb29b3db756263b - working



![Знімок екрана 2020-12-07 о 19 29 23](https://user-images.githubusercontent.com/1614429/101384116-ae0f9600-38c2-11eb-964a-a4e2238af056.png)

**Comment by tolusha** [comment]
We are investigating the issue.
To turn off internal network usage update the CR:
`spec.server.useInternalClusterSVCNames: false`

**Comment by azatsarynnyy** [comment]
fyi: the issue for better error message when Che API is not reachable from Che Theia https://github.com/eclipse/che/issues/18556

**Comment by tolusha** [comment]
I've tested on OpenShift 4.6 I couldn't reproduce the issue.
```bash
$ chectl version
chectl/0.0.20201204-next.4c50037 linux-x64 node-v10.23.0
```

The infrastructure in question had inconsistency of image versions:
- che-operator 7.22.2
- che-server 7.23.0-SNAPSHOT
- che-theia latest

**Comment by ibuziuk** [comment]
Hit the same issue against Hosted Che and the suggested solution was to add the internal links explicitly in the template that would point to the external one - https://github.com/redhat-developer/rh-che/pull/2027/files

This sounds like overkill. I would expect that if internal links are not specified the external communication will be used. Opened https://github.com/eclipse/che/issues/18643
