### ISSUE TITLE
Better error message when Che API is not reachable from Che Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18556]
### Is your task related to a problem? Please describe.
When Che Theia can't reach Che API, it reports the error messages something like the following ones:

<details>
<summary>error message</summary>
<pre>
at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:08.606 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:20.894 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:33.182 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:58:49.566 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:59:05.950 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)                                                                                 │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                      │
│ 2020-12-07 13:59:18.238 root ERROR Uncaught Exception:  Params: [object Object]                                                                                                                              │
│ 2020-12-07 13:59:26.430 root ERROR Error: Unable to get workspace containers. Cause: [object Object]                                                                                                         │
│     at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)                                               │
│     at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)                                                                                     │
│     at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)                                                                             │
│     at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)
</pre>
</details>

With such messages, it's hard to recognize the real problem without knowledge of Che Theia internals.

### Describe the solution you'd like
Add more details when logging the `Error: Unable to get workspace containers. Cause: [object Object]`.

### Describe alternatives you've considered
Show some warning to the user with a meaningful message.

**Comment by tsmaeder** [comment]
The root problem with many such problems, IMO, is that many components in Che-Theia try to reach the Che API when they are being constructed, for example in the constructor or in "post construct" method. That leads to the whole IDE startup process being interrupted.
I would propose as a rule that all UI components need to handle errors while being constructed and report errors through proper channels.

**Comment by ibuziuk** [comment]
Closing as obsolete - https://github.com/eclipse-che/che/issues/21771
