### ISSUE TITLE
Che-Theia build is failed sporadically within the HappyPath test jobs

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18575]
### Describe the bug

After two days of shutdown of HappyPath test jobs, we noticed today it started failing sporadically on Che-Theia PRs.

While there's a PR where HappyPath tests are passed successfully https://github.com/eclipse/che-theia/pull/947#issuecomment-741582368,
there're several PRs with the failed HappyPath test jobs: https://github.com/eclipse/che-theia/pull/945#issuecomment-741797732, https://github.com/eclipse/che-theia/pull/948#issuecomment-741781048, https://github.com/eclipse/che-theia/pull/778#issuecomment-741681045.

The error is related to an image build. It's the same in all the cases:
```
16:14:47 Step 27/38 : RUN find /che-theia-build -exec sh -c "chgrp 0 {}; chmod g+rwX {}" \; 2>log.txt &&     find /che-theia-build/plugins -name "*.sh" | xargs chmod +x
16:14:47  ---> Running in 7b1faecc48c6
16:15:10 BusyBox v1.31.1 () multi-call binary.
16:15:10 
16:15:10 Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
16:15:10 
16:15:10 Each MODE is one or more of the letters ugoa, one of the
16:15:10 symbols +-= and one or more of the letters rwxst
16:15:10 
16:15:10 	-R	Recurse
16:15:10 	-c	List changed files
16:15:10 	-v	List all files
16:15:10 	-f	Hide errors
16:15:10 The command '/bin/sh -c find /che-theia-build -exec sh -c "chgrp 0 {}; chmod g+rwX {}" \; 2>log.txt &&     find /che-theia-build/plugins -name "*.sh" | xargs chmod +x' returned a non-zero code: 123
16:15:10 Build step 'Execute shell' marked build as failure
```
Failing command: https://github.com/eclipse/che-theia/blob/fdf6fee29b1bc0f8aa0286a99f188fe54dcafe3c/dockerfiles/theia/Dockerfile#L119

[Successful build flow](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2066/consoleFull):
```
Step 27/38 : RUN find /che-theia-build -exec sh -c "chgrp 0 {}; chmod g+rwX {}" \; 2>log.txt &&     find /che-theia-build/plugins -name "*.sh" | xargs chmod +x
 ---> Running in 78e5548bdfb4
Removing intermediate container 78e5548bdfb4
 ---> 5a4fbf01748a
Step 28/38 : FROM node:12.20.0-alpine3.12 as runtime
 ---> 7d016f811d40
Step 29/38 : ENV USE_LOCAL_GIT=true     HOME=/home/theia     SHELL=/bin/bash     THEIA_DEFAULT_PLUGINS=local-dir:///default-theia-plugins     LOCAL_GIT_DIRECTORY=/usr     GIT_EXEC_PATH=/usr/libexec/git-core     PORT_PLUGIN_EXCLUDE_3130=TRUE     YARN_FLAGS=""
 ---> Running in e25a4d60679b
Removing intermediate container e25a4d60679b
 ---> c21fd1076d21
Step 30/38 : EXPOSE 3100 3130
 ---> Running in bee002d6d349
Removing intermediate container bee002d6d349
 ---> a1ffe9b61ea3
Step 31/38 : COPY --from=build-result /che-theia-build/plugins /default-theia-plugins
 ---> 68c1550fabf6
Step 32/38 : RUN apk add --update --no-cache sudo git bzip2 which bash curl openssh openssh-keygen less sshpass lsblk
 ---> Running in 92e8c41954c2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/27) Installing ncurses-terminfo-base (6.2_p20200523-r0)Successful build flow:
Step 27/38 : RUN find /che-theia-build -exec sh -c "chgrp 0 {}; chmod g+rwX {}" \; 2>log.txt &&     find /che-theia-build/plugins -name "*.sh" | xargs chmod +x
 ---> Running in 78e5548bdfb4
Removing intermediate container 78e5548bdfb4
 ---> 5a4fbf01748a
Step 28/38 : FROM node:12.20.0-alpine3.12 as runtime
 ---> 7d016f811d40
Step 29/38 : ENV USE_LOCAL_GIT=true     HOME=/home/theia     SHELL=/bin/bash     THEIA_DEFAULT_PLUGINS=local-dir:///default-theia-plugins     LOCAL_GIT_DIRECTORY=/usr     GIT_EXEC_PATH=/usr/libexec/git-core     PORT_PLUGIN_EXCLUDE_3130=TRUE     YARN_FLAGS=""
 ---> Running in e25a4d60679b
Removing intermediate container e25a4d60679b
 ---> c21fd1076d21
Step 30/38 : EXPOSE 3100 3130
 ---> Running in bee002d6d349
Removing intermediate container bee002d6d349
 ---> a1ffe9b61ea3
Step 31/38 : COPY --from=build-result /che-theia-build/plugins /default-theia-plugins
 ---> 68c1550fabf6
Step 32/38 : RUN apk add --update --no-cache sudo git bzip2 which bash curl openssh openssh-keygen less sshpass lsblk
 ---> Running in 92e8c41954c2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/27) Installing ncurses-terminfo-base (6.2_p20200523-r0)
...
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
I'm marking it as a `blocker` since we are not able to merge any Che-Theia PR.
The last PR where the tests passed today was https://github.com/eclipse/che-theia/pull/947#issuecomment-741582368

**Comment by azatsarynnyy** [comment]
Looks like it can't call `chmod`
https://github.com/eclipse/che-theia/blob/f0586a8b28f3b0ca8254cdb39f45b703bcc88c41/dockerfiles/theia/Dockerfile#L119

**Comment by azatsarynnyy** [comment]
It's also interesting that the same build has no issues when running on GitHub infra, with Actions.

**Comment by azatsarynnyy** [comment]
It seems the initial error has gone :man_shrugging: 
And now Jenkins can't clone the repo:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2085/console
```
21:30:22 ERROR: Error cloning remote repo 'origin'
21:30:22 hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/eclipse/che-theia +refs/heads/*:refs/remotes/origin/*" returned status code 128:
21:30:22 stdout: 
21:30:22 stderr: fatal: unable to access 'https://github.com/eclipse/che-theia/': Failed connect to github.com:443; Connection timed out
21:30:22 
21:30:22 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
21:30:22 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1735)
21:30:22 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
21:30:22 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:420)
21:30:22 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:629)
21:30:22 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
21:30:22 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
21:30:22 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
21:30:22 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
21:30:22 	at hudson.remoting.Request$2.run(Request.java:369)
21:30:22 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
21:30:22 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21:30:22 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:30:22 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:30:22 	at java.lang.Thread.run(Thread.java:748)
21:30:22 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to minikube-rhel7-24gb-26611
21:30:22 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
21:30:22 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
21:30:22 		at hudson.remoting.Channel.call(Channel.java:955)
21:30:22 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
21:30:22 		at sun.reflect.GeneratedMethodAccessor1176.invoke(Unknown Source)
21:30:22 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:30:22 		at java.lang.reflect.Method.invoke(Method.java:498)
21:30:22 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
21:30:22 		at com.sun.proxy.$Proxy129.execute(Unknown Source)
21:30:22 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
21:30:22 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
21:30:22 		at hudson.scm.SCM.checkout(SCM.java:504)
21:30:22 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
21:30:22 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
21:30:22 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
21:30:22 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
21:30:22 		at hudson.model.Run.execute(Run.java:1798)
21:30:22 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
21:30:22 		at hudson.model.ResourceController.execute(ResourceController.java:97)
21:30:22 		at hudson.model.Executor.run(Executor.java:429)
21:30:22 ERROR: Error cloning remote repo 'origin'
```

**Comment by azatsarynnyy** [comment]
It looks like everything is stabilized now. The tests are passes successfully on several Che-Theia PRs:
- https://github.com/eclipse/che-theia/pull/947#issuecomment-742433353
- https://github.com/eclipse/che-theia/pull/946#issuecomment-742435257
- https://github.com/eclipse/che-theia/pull/945#issuecomment-742410067

Most likely, it was a glitch on CI side. So, closing it.
