### ISSUE TITLE
Adapt Che-Theia to uptream changes

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#18618]
### Is your task related to a problem? Please describe.

It's impossible to start any workspace at the moment for `che-theia` which includes the last changes from upstream.
So we need some adaptation on `che-theia` side.

### Describe the solution you'd like

We need investigate which commit from upstream breaks `che-theia` and provide the corresponding fix.

### Additional context

Please see the video from test report for the PR without any changes https://github.com/eclipse/che-theia/pull/695#issuecomment-745209317

![server_theia](https://user-images.githubusercontent.com/5676062/102206768-c8a2ca00-3ed5-11eb-9e7b-a107b6b001d8.png)

**Comment by vzhukovs** [comment]
Need to check, probably it's because of https://github.com/eclipse-theia/theia/commit/ae35f9c1a4bf0127f8b15262422da93ad5a13ac0

**Comment by azatsarynnyy** [comment]
> Need to check, probably it's because of [eclipse-theia/theia@ae35f9c](https://github.com/eclipse-theia/theia/commit/ae35f9c1a4bf0127f8b15262422da93ad5a13ac0)

@vzhukovs please do. Thanks!

**Comment by azatsarynnyy** [comment]
If it's needed, pin Che-Theia to some previous commit SHA.
https://github.com/eclipse/che-theia/blob/d30da310a61eea1e1b8af0d4bfd2f3585e2ddfe9/build.include#L16

**Comment by azatsarynnyy** [comment]
I've set it `blocker` as it prevents us from consuming the latest upstream chnages.

**Comment by vzhukovs** [comment]
From Theia logs:

```
Failed to start the backend application.
Error: Cannot find module 'connect'
Require stack:
- /home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/plugin-service.js
- /home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-backend-module.js
- /home/theia/src-gen/backend/server.js
- /home/theia/src-gen/backend/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/plugin-service.js:79:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/plugin-service.js',
    '/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-backend-module.js',
    '/home/theia/src-gen/backend/server.js',
    '/home/theia/src-gen/backend/main.js'
  ]
}
/home/theia/node_modules/@theia/core/lib/node/main.js:58
    throw reason;
    ^

Error: Cannot find module 'connect'
Require stack:
- /home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/plugin-service.js
- /home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-backend-module.js
- /home/theia/src-gen/backend/server.js
- /home/theia/src-gen/backend/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/plugin-service.js:79:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/plugin-service.js',
    '/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-backend-module.js',
    '/home/theia/src-gen/backend/server.js',
    '/home/theia/src-gen/backend/main.js'
  ]
}
```

see, that with upstream commit https://github.com/eclipse-theia/theia/commit/143f589a2183adb469301612775773f2ad776723 we're missing the connect library. As far as we rebind [PluginApiContribution](https://github.com/eclipse/che-theia/blob/5d0751e354f773fdf84f55a38488f0df07abf082/extensions/eclipse-che-theia-plugin-ext/src/node/plugin-service.ts#L30) we need to adapt che-theia to use express library instead of connect.

**Comment by azatsarynnyy** [comment]
> we need to adapt che-theia to use express library instead of connect

It should be an easy fix. @vzhukovs please provide a PR
