### ISSUE TITLE
Error: Error: Failed to start a pod, reason: Completed

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18688]
### Describe the bug

`chectl server:deploy -a helm -p microk8s -b localhost`

```
  ✔ 🏃  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.4.2+g23dd3af
    ✔ Create Namespace (che)...does already exist.
    ✔ Check Eclipse Che TLS certificate...self-signed TLS certificate secret found
    ✔ Check Cluster Role Binding...done.
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Eclipse Che Helm Chart...done.
  ❯ ✅  Post installation checklist
    ❯ Devfile registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✖ Starting...failed
        → Failed to start a pod, reason: Completed
      Plugin registry pod bootstrap
      Eclipse Che pod bootstrap
      Eclipse Che status check
    Prepare post installation output
 ›   Error: Error: Failed to start a pod, reason: Completed
 ›   Command server:deploy failed. Error log: /home/charlesrod/.cache/chectl/error.log
```

`charlesrod@E560:~$ codium /home/charlesrod/.cache/chectl/error.log`

```
2020-12-22T19:33:09.333Z Error: Error: Failed to start a pod, reason: Completed
2020-12-22T19:33:09.333Z Command server:deploy failed. Error log: /home/charlesrod/.cache/chectl/error.log
2020-12-22T19:33:09.333Z     at Object.error (~/.local/share/chectl/client/7.23.1/node_modules/@oclif/errors/lib/index.js:26:15)
2020-12-22T19:33:09.333Z     at Deploy.error (~/.local/share/chectl/client/7.23.1/node_modules/@oclif/command/lib/command.js:60:23)
2020-12-22T19:33:09.333Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.23.1/lib/commands/server/deploy.js:208:22)
2020-12-22T19:33:09.333Z     at Generator.throw (<anonymous>)
2020-12-22T19:33:09.333Z     at rejected (~/.local/share/chectl/client/7.23.1/node_modules/tslib/tslib.js:113:69)
2020-12-22T19:33:09.333Z     at runMicrotasks (<anonymous>)
```

### Che version

 - [ x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ x ] other: (please specify) microk8s `installed: v1.20.0 (1864) 219MB classic`

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * `chectl server:deploy -a helm -p microk8s -b localhost`
     * provide an output of `chectl version` command
     * `chectl/7.23.1 linux-x64 node-v12.20.0`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context

screenshot of devfile

![image](https://user-images.githubusercontent.com/4656027/102926960-9e17ba80-445b-11eb-8aa6-55aba88a4a6f.png)

**Comment by gnoejuan** [comment]
Attempting another deploy (without deleting seems to be a non-starter

```
charlesrod@E560:~$ chectl server:deploy -a helm -p microk8s -b localhost
› Current Kubernetes context: 'microk8s'
  ✔ Verify Kubernetes API...OK
  ❯ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"
      ✔ Found running Eclipse Che deployment
      ✔ Found running plugin registry deployment
      ✔ Found running devfile registry deployment
    ✖ Check Eclipse Che server status
      → E_CHECK_CHE_STATUS_FAIL - Failed to check Eclipse Che status (URL: https://che-che.localhost). E_CHE_API_NOTFOUND - Endpoint: https://che-che.localhost/api/system/state - Message: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 N
…
 ›   Error: Error: E_CHECK_CHE_STATUS_FAIL - Failed to check Eclipse Che status (URL: https://che-che.localhost). E_CHE_API_NOTFOUND - Endpoint: https://che-che.localhost/api/system/state - Message: "<html>\r\n<head><title>404 Not 
 ›   Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.19.2</center>\r\n</body>\r\n</html>\r\n"
 ›   Command server:deploy failed. Error log: /home/charlesrod/.cache/chectl/error.log Eclipse Che logs: /tmp/chectl-logs/1608666480460```

but `chectl server:delete` then 'chectl server:deploy` allowed the deployment

**Comment by tolusha** [comment]
@gnoejuan 
`kubectl get pods -n che`

**Comment by gnoejuan** [comment]
Sorry, I think I should close this. Haven't encountered it since.
