### ISSUE TITLE
chectl server:deploy --installer helm throws error listen EACCES: permission denied \\.\pipe\notifierPipe-xxxx

### ISSUE THREAD

**Issue by mtsmfm** [eclipse-che/che#18702]
### Describe the bug

```
$ chectl server:deploy --platform=docker-desktop --domain 127.0.0.1.nip.io --installer helm
› Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Docker Desktop preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    ✔ Verify remote kubernetes status...done.
    ✔ Check Kubernetes version: Found v1.19.3.
    ✔ Verify if nginx ingress is installed
    ↓ Installing nginx ingress [skipped]
      → Ngninx ingress is already setup.
    ✔ Verify domain is set...set to 127.0.0.1.nip.io.
  ✔ Following Eclipse Che logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che server logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
    ✔ Start following namespace events...done
  ✔ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.4.2+g23dd3af
    ✔ Create Namespace (che)...does already exist.
    ✔ Check Eclipse Che TLS certificate...self-signed TLS certificate secret found
    ✔ Check Cluster Role Binding...does not exists.
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Eclipse Che Helm Chart...done.
  ❯ ✅  Post installation checklist
  ✔ ✅  Post installation checklist
    ✔ Devfile registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Plugin registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che status check...done
  ✔ Prepare post installation output...done
  ✔ Show important messages
    ✔ Eclipse Che 7.24.0-SNAPSHOT has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://che-che.127.0.0.1.nip.io
    ✔ Admin user login          : "admin:admin". NOTE: must change after first login.
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://plugin-registry-che.127.0.0.1.nip.io/v3
    ✔ Devfile Registry          : https://devfile-registry-che.127.0.0.1.nip.io
    ✔ -------------------------------------------------------------------------------
    ✔ -------------------------------------------------------------------------------
Command server:deploy has completed successfully in 01:09.
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied \\.\pipe\notifierPipe-<snip>
    at Server.setupListenHandle [as _listen2] (net.js:1299:21)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1461:5)
    at /usr/local/lib/chectl/node_modules/node-notifier/lib/utils.js:564:21
    at new Promise (<anonymous>)
    at Object.module.exports.createNamedPipe (/usr/local/lib/chectl/node_modules/node-notifier/lib/utils.js:555:10)
    at WindowsToaster.notifyRaw (/usr/local/lib/chectl/node_modules/node-notifier/notifiers/toaster.js:133:9)
    at Object.notifyCommandCompletedSuccessfully (/usr/local/lib/chectl/lib/util.js:140:14)
    at Deploy.<anonymous> (/usr/local/lib/chectl/lib/commands/server/deploy.js:208:20)
    at Generator.next (<anonymous>)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '\\\\.\\pipe\\notifierPipe-<snip>',
  port: -1
}
```

### Steps to reproduce

1. bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
2. chectl server:deploy --platform=docker-desktop --domain 127.0.0.1.nip.io --installer helm

### Expected behavior

It finishes without error

### Runtime

   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:53 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command

```
$ chectl version
chectl/0.0.20201222-next.284ac6e wsl-x64 node-v12.20.0
```

### Environment
   - [x] my computer
       - [x] Windows

### Additional context

It seems node-notifier doesn't work out of the box on WSL2

https://github.com/mikaelbr/node-notifier/issues/353

After running chmod, I confirmed `server:deploy` finishes successfully.
`$ sudo chmod +x /usr/local/lib/chectl/node_modules/node-notifier/vendor/snoreToast/snoretoast-x64.exe`

To be honest, showing notification on every command annoys me.
Commands which can be finished in a few seconds like `dashboard:open` and `server:status` don't need notification I think.

**Comment by tolusha** [comment]
> Commands which can be finished in a few seconds like dashboard:open and server:status don't need notification I think.

Agreed.

**Comment by svor** [comment]
@tolusha I set a severity as P1, feel free to change it if you have another think
