### ISSUE TITLE
[Telemetry] java.lang.NumberFormatException: null in the telemetry container during init

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18802]
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Create workspace with telemetry plugin e.g.

```
apiVersion: 1.0.0
metadata:
  name: test-woopra-plugin
projects:
  - name: nodejs-mongodb-sample
    source:
      location: 'https://github.com/che-samples/nodejs-mongodb-sample'
      type: git
      branch: master
components:
  - type: chePlugin
    reference: 'https://yaml-reference/meta.yaml'
    alias: woopra
```

### Runtime
OSD

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context
Logs:
```
2021-01-14 08:19:38,875 WARN  [org.ecl.che.inc.wor.tel.bas.AbstractAnalyticsManager] (main) the timestamp ( null ) has invalid format: java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at org.eclipse.che.incubator.workspace.telemetry.base.AbstractAnalyticsManager.getDateFromString(AbstractAnalyticsManager.java:252)
	at org.eclipse.che.incubator.workspace.telemetry.base.AbstractAnalyticsManager.<init>(AbstractAnalyticsManager.java:157)
	at com.redhat.che.workspace.services.telemetry.woopra.AnalyticsManager.<init>(AnalyticsManager.java:97)
	at com.redhat.che.workspace.services.telemetry.woopra.MainConfiguration.analyticsManager(MainConfiguration.java:34)
	at com.redhat.che.workspace.services.telemetry.woopra.MainConfiguration_ProducerMethod_analyticsManager_13e92053a40c6ae983552ef68c26e1dd30a10139_Bean.create(MainConfiguration_ProducerMethod_analyticsManager_13e92053a40c6ae983552ef68c26e1dd30a10139_Bean.zig:89)
	at com.redhat.che.workspace.services.telemetry.woopra.MainConfiguration_ProducerMethod_analyticsManager_13e92053a40c6ae983552ef68c26e1dd30a10139_Bean.get(MainConfiguration_ProducerMethod_analyticsManager_13e92053a40c6ae983552ef68c26e1dd30a10139_Bean.zig:113)
	at com.redhat.che.workspace.services.telemetry.woopra.MainConfiguration_ProducerMethod_analyticsManager_13e92053a40c6ae983552ef68c26e1dd30a10139_Bean.get(MainConfiguration_ProducerMethod_analyticsManager_13e92053a40c6ae983552ef68c26e1dd30a10139_Bean.zig:219)
	at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_Bean.create(TelemetryResource_Bean.zig:79)
	at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_Bean.create(TelemetryResource_Bean.zig:44)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:72)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:23)
	at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_ClientProxy.arc$delegate(TelemetryResource_ClientProxy.zig:199)
	at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_ClientProxy.arc_contextualInstance(TelemetryResource_ClientProxy.zig:21)
	at org.eclipse.che.incubator.workspace.telemetry.TelemetryResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(TelemetryResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:54)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent50.deploy_0(LifecycleEventsBuildStep$startupEvent50.zig:58)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent50.deploy(LifecycleEventsBuildStep$startupEvent50.zig:77)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:234)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runtime.Application.run(Application.java:218)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)

2021-01-14 08:19:38,884 INFO  [io.quarkus] (main) telemetry-woopra-plugin 0.0.1 (running on Quarkus 1.0.0.CR1) started in 0.054s. Listening on: http://0.0.0.0:4167
2021-01-14 08:19:38,884 INFO  [io.quarkus] (main) Profile prod activated.
2021-01-14 08:19:38,884 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb, smallrye-openapi, swagger-ui]
2021-01-14 08:19:57,202 INFO  [com.red.che.wor.ser.tel.woo.AnalyticsManager] (vert.x-worker-thread-0) Analytics Woopra Cookie for user 61c3c352-2189-40e2-a496-6da152bd41cb and workspace workspacevwcunwv8ts96d7me : 919c0d7677b0ea1997fb2295a4aaeb97
```

**Comment by ibuziuk** [comment]
Fixed in https://github.com/che-incubator/che-workspace-telemetry-client/pull/61
