### ISSUE TITLE
Clean log output from Resources Monitor Plugin

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#18841]
### Is your task related to a problem? Please describe.
In case if Resources Monitor plug-in cannot read workspace's pod information or connect to the Metrics server, or read metrics from the Metrics server, the plug-in throws exceptions into theia-ide container. The exception's message looks like:
```log
Extension-Host:Promise rejection not handled in one second: Error: Cannot connect to Metrics Server. Status code: 404. Error: 404 page not found
 , reason: Error: Cannot connect to Metrics Server. Status code: 404. Error: 404 page not found
Extension-Host:With stack trace: Error: Cannot connect to Metrics Server. Status code: 404. Error: 404 page not found
    at ResMon.<anonymous> (/tmp/theia-unpacked/eclipse_che_resource_monitor_plugin.theia/lib/resource-monitor-plugin.js:147:35)
    at step (/tmp/theia-unpacked/eclipse_che_resource_monitor_plugin.theia/lib/resource-monitor-plugin.js:42:23)
    at Object.next (/tmp/theia-unpacked/eclipse_che_resource_monitor_plugin.theia/lib/resource-monitor-plugin.js:23:53)
    at fulfilled (/tmp/theia-unpacked/eclipse_che_resource_monitor_plugin.theia/lib/resource-monitor-plugin.js:14:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Describe the solution you'd like
Since these exceptions are expected we have to catch them and don't show the message in the log.

### Additional context
Resources Monitor plugin PR: https://github.com/eclipse/che-theia/pull/919

**Comment by svor** [comment]
should be solved by https://github.com/eclipse-che/che-theia/pull/1089
