### ISSUE TITLE
Watch param behaves incorrectly with unsupport che server kubernetes api

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#18854]
### Describe the bug
Using the watch param directly through the kubernetes api and through the unsupported che server kubernetes api seems to have a couple of differences. When we setup the below example for testing the regular kubernetes api, everything works correctly and events are streamed. However, when we try to test through the unsupported API the request stays open for a few seconds, receives a response and then terminates.

### Che version

 - [X] latest (7.24.0)
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

First, to see how it should be behaving you can do:
```
kubectl proxy --port=8080
curl http://localhost:8080/apis/workspace.devfile.io/v1alpha2/namespaces/sample/devworkspaces?watch=true
```
and you should see that when the watch param is specified the connection stays open and waits for events to come through.

However when we try and do similar requests through the unsupported che server kubernetes api such as
```
TOKEN=$(INSERT YOUR TOKEN HERE)
curl -k -v -H "Authorization: Bearer $TOKEN" https://che-che.apps-crc.testing/api/unsupported/k8s/apis/workspace.devfile.io/v1alpha2/namespaces/sample/devworkspaces?watch=true
```
in a few seconds the response will terminate with:
```
* TLSv1.3 (IN), TLS alert, close notify (256):
* transfer closed with outstanding read data remaining
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (18) transfer closed with outstanding read data remaining
```

In order to test the examples above, you'll need to install Che and the [devworkspace-operator](https://github.com/devfile/devworkspace-operator) on the same cluster. Then create a new namespace called sample. Then apply a devworkspace custom resource: `oc apply -f samples/all-in-one-theia-nodejs.devworkspace.yaml`

### Expected behavior
When running:
```
TOKEN=$(INSERT YOUR TOKEN HERE)
curl -k -v -H "Authorization: Bearer $TOKEN" https://che-che.apps-crc.testing/api/unsupported/k8s/apis/workspace.devfile.io/v1alpha2/namespaces/sample/devworkspaces?watch=true
```
I'd expect that the request stays open so that we get a stream of events and not terminate as quickly

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [X] Openshift (include output of `oc version`) 
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

Openshift 4.6.6

### Installation method
   - [X] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [X] my computer
       - [ ] Windows
       - [X] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs

This is the error that happens right after the request terminates
```
2021-01-21 12:54:23,147[nio-8080-exec-3]  [ERROR] [o.a.c.c.C.[.[.[/api].[default] 175]  - Servlet.service() for servlet [default] in context with path [/api] threw exception
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:671)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:679)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
	at java.base/java.io.InputStream.read(Unknown Source)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:109)
	at org.everrest.core.impl.provider.InputStreamEntityProvider.writeTo(InputStreamEntityProvider.java:73)
	at org.everrest.core.impl.provider.InputStreamEntityProvider.writeTo(InputStreamEntityProvider.java:31)
	at org.everrest.core.impl.ContainerResponse$BodyWriter.writeTo(ContainerResponse.java:90)
	at org.everrest.core.servlet.ServletContainerResponseWriter.writeBody(ServletContainerResponseWriter.java:47)
	at org.everrest.core.impl.ContainerResponse.writeResponse(ContainerResponse.java:291)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:78)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:121)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at org.eclipse.che.core.metrics.ApiResponseMetricFilter.doFilter(ApiResponseMetricFilter.java:46)
	at org.eclipse.che.commons.logback.filter.IdentityIdLoggerFilter.doFilter(IdentityIdLoggerFilter.java:49)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:142)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter.doFilter(KeycloakEnvironmentInitializationFilter.java:99)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:76)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
```
### Additional context

For context, I'm trying to find a way for the dashboard to subscribe to devworkspace status events. Since, we aren't able to use websockets through the unsupported api I'm trying to get it to work using the browser [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). It works successfully why I use the kubectl proxy and create a request to that but not when I make the fetch request to the unsupported api

**Comment by sleshchenko** [comment]
Closing since there is no plan to fix it, instead we'll have the corresponding method on Dashboard backend
