### ISSUE TITLE
Debugging the back-end process seems to crash back-end plugin host process

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#18860]
### Describe the bug
Whenever I try to debug the plugin host process in a self-hosting scenario, the back end plugin-host process crashes immediately.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other:

### Steps to reproduce

1. Build che-theia
2. Run the theia back-end with `--inspect-break=...`
3. Observe: the plugin host process seems to crash, the connection to the host is closed
4. In the log, I find this stack trace:

```
Error: Cannot find module '/default-theia-plugins/vscode-builtin-js-debug/extension/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1147:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:74:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
} 
```

a cursory inspection of the source code of the vscode-builtin-js-debug extension reveals that this is some kind of bootloader script for auto-attach debug support. As I understand it, the file is supposed to be copied to the the theia storage area, but that does not seem to be the case here. The problem here is that /default-theia-plugins is a folder that only exists in the theia container. Loading stuff from there fails in other containers, obviously.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
The problem can be worked around by putting the following in your preferences:
```
   "debug.extensionHost.useV3": false,
   "debug.node.useV3": false
```
Note that this only worked for me after putting 'false' explicitly, even though the default when you open the prefs is "unchecked".
