### ISSUE TITLE
"Circular struture" errors when accepting "current change"

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#18921]
### Describe the bug
I get exceptions in the console of the che-theia container in a self-hosting workspace when I am resolving git conflicts in an editor and click the "Accept Incoming Change" link in the editor. Concretely, it's one of many changes in `yarn.lock`
The exception is:
```
2021-01-29 10:23:22.610 root ERROR TypeError: Converting circular structure to JSON
--> starting at object with constructor 'CommandRegistryImpl'
| property 'commandsConverter' -> object with constructor 'CommandsConverter'
--- property 'commands' closes the circle
at JSON.stringify (<anonymous>)
at Function.MessageFactory.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:363:166)
at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:190:46)
at Proxy.target.<computed> (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:164:38)
at SourceControlImpl.set (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/scm.js:332:24)
at /default-theia-plugins/vscode-git/extension/dist/main.js:1:73426
at /default-theia-plugins/vscode-git/extension/dist/main.js:1:4316
at /home/theia/node_modules/@theia/core/lib/common/event.js:176:33
at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:191:39)
at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:318:29)
```
The browser then goes on to complain that "A website is slowing down your browser" and the UI is unresponsive for a couple of seconds. Not sure that is related, though.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Merge any git conflict in the editor.

### Expected behavior
No exception.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl  `-p docker desktop`
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
The error is thrown because the git extension registers the "git.checkout" command on the `scm.SourceControl.statusBarCommands` array. This command has the `SourceControlImpl` instance as its first argument. Contrary to what Theia does, VS Code does not send command arguments over the wire: they remain in the plugin host. The original arguments are remembered in a map and a proxy command is sent over the wire that will invoke the original command with the original arguments.

**Comment by tsmaeder** [comment]
There seems to be the same code in Theia...analyzing why it has no effect...

**Comment by tsmaeder** [comment]
I believe this is actually an error condition in the git extensions that we're not handling gracefully: the `SyncStatusBar` returns a command that has an empty string as the `command` value. Since we're checking 
```
if (command.command && command.arguments && command.arguments.length > 0) {
```
before converting to a safe command (and "" evaluates to "falsy"), we're never converting the command to a safe command. I believe passing a command with an empty `command` is a programming error. 
However, looking at the code in the git extension, they seem to use the commands with no `command` field to update the UI of the toolbar (progress spinner, etc.). I guess we should be bug compatible with VS Code in this case.
