### ISSUE TITLE
Che-theia image build is broken

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#18960]
### Describe the bug

Che-theia image build is broken.
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Start the docker build of the `che-theia` image according to https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/README.md

See an error:
```
$ theia download:plugins
--- downloading plugins ---
+ vscode-builtin-docker: downloaded successfully 
+ vscode-builtin-java: downloaded successfully 
+ vscode-builtin-css: downloaded successfully 
+ vscode-builtin-json: downloaded successfully 
+ vscode-builtin-html: downloaded successfully 
+ vscode-github: downloaded successfully 
+ vscode-builtin-json-language-features: downloaded successfully 
+ vscode-git: downloaded successfully 
+ vscode-builtin-css-language-features: downloaded successfully 
+ vscode-references-view: downloaded successfully 
+ vscode-builtin-js-debug: downloaded successfully 
+ vscode-builtin-html-language-features: downloaded successfully 
x vscode-builtin-gulp: failed to download with: 404 Not Found
x vscode-builtin-groovy: failed to download with: 404 Not Found
x vscode-builtin-fsharp: failed to download with: 404 Not Found
x vscode-builtin-go: failed to download with: 404 Not Found
x vscode-builtin-debug-auto-launch: failed to download with: 404 Not Found
x vscode-builtin-bat: failed to download with: 404 Not Found
x vscode-builtin-markdown-language-features: failed to download with: 404 Not Found
x vscode-builtin-powershell: failed to download with: 404 Not Found
x vscode-builtin-log: failed to download with: 404 Not Found
x vscode-builtin-clojure: failed to download with: 404 Not Found
x vscode-builtin-cpp: failed to download with: 404 Not Found
x vscode-builtin-csharp: failed to download with: 404 Not Found
x vscode-builtin-coffeescript: failed to download with: 404 Not Found
x vscode-builtin-rust: failed to download with: 404 Not Found
x vscode-builtin-configuration-editing: failed to download with: 404 Not Found
x vscode-builtin-perl: failed to download with: 404 Not Found
x vscode-builtin-vb: failed to download with: 404 Not Found
x vscode-builtin-theme-solarized-dark: failed to download with: 404 Not Found
x vscode-builtin-jake: failed to download with: 404 Not Found
x vscode-builtin-grunt: failed to download with: 404 Not Found
x vscode-builtin-theme-solarized-light: failed to download with: 404 Not Found
x vscode-builtin-objective-c: failed to download with: 404 Not Found
x vscode-builtin-ini: failed to download with: 404 Not Found
x vscode-builtin-emmet: failed to download with: 404 Not Found
x vscode-builtin-handlebars: failed to download with: 404 Not Found
x vscode-builtin-less: failed to download with: 404 Not Found
x vscode-builtin-yaml: failed to download with: 404 Not Found
x vscode-builtin-xml: failed to download with: 404 Not Found
x vscode-builtin-icon-theme-seti: failed to download with: 404 Not Found
x vscode-builtin-javascript: failed to download with: 404 Not Found
x vscode-builtin-theme-monokai-dimmed: failed to download with: 404 Not Found
x vscode-builtin-make: failed to download with: 404 Not Found
x vscode-builtin-lua: failed to download with: 404 Not Found
x vscode-builtin-pug: failed to download with: 404 Not Found
x vscode-builtin-swift: failed to download with: 404 Not Found
x vscode-builtin-php: failed to download with: 404 Not Found
x vscode-builtin-merge-conflicts: failed to download with: 404 Not Found
x vscode-builtin-scss: failed to download with: 404 Not Found
x vscode-builtin-ruby: failed to download with: 404 Not Found
x vscode-builtin-python: failed to download with: 404 Not Found
x vscode-builtin-sql: failed to download with: 404 Not Found
x vscode-builtin-npm: failed to download with: 404 Not Found
x vscode-builtin-razor: failed to download with: 404 Not Found
x vscode-builtin-shaderlab: failed to download with: 404 Not Found
x vscode-builtin-hlsl: failed to download with: 404 Not Found
x vscode-builtin-theme-red: failed to download with: 404 Not Found
x vscode-builtin-typescript: failed to download with: 404 Not Found
x vscode-builtin-shellscript: failed to download with: 404 Not Found
x vscode-builtin-r: failed to download with: 404 Not Found
x vscode-builtin-theme-quietlight: failed to download with: 404 Not Found
x vscode-builtin-theme-monokai: failed to download with: 404 Not Found
x vscode-builtin-theme-abyss: failed to download with: 404 Not Found
x vscode-builtin-theme-kimbie-dark: failed to download with: 404 Not Found
x vscode-builtin-theme-tomorrow-night-blue: failed to download with: 404 Not Found
x vscode-builtin-markdown: failed to download with: 404 Not Found
x vscode-builtin-theme-defaults: failed to download with: 404 Not Found
Error: Errors downloading some plugins. To make these errors non fatal, re-run with --ignore-errors
    at Object.<anonymous> (/home/theia-dev/theia-source-code/dev-packages/cli/lib/download-plugins.js:114:31)
    at step (/home/theia-dev/theia-source-code/dev-packages/cli/lib/download-plugins.js:59:23)
    at Object.next (/home/theia-dev/theia-source-code/dev-packages/cli/lib/download-plugins.js:40:53)
    at fulfilled (/home/theia-dev/theia-source-code/dev-packages/cli/lib/download-plugins.js:31:58)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn ${YARN_FLAGS}' returned a non-zero code: 1
```
Most of the [plugins in che-theia](https://github.com/eclipse/che-theia/blob/master/generator/src/templates/theiaPlugins.json) have `1.44.2` or lower version which, is not available in the https://open-vsx.org/api/vscode any more. 
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by vinokurig** [comment]
Related issue: https://github.com/eclipse/che/issues/18933

**Comment by ericwill** [comment]
Based on this comment: https://github.com/eclipse/che/issues/18926#issuecomment-772827589

I believe this can be closed now.

**Comment by tsmaeder** [comment]
Relevant Theia issue: https://github.com/eclipse-theia/theia/issues/9014

**Comment by vinokurig** [comment]
The build is fixed.

**Comment by sunix** [comment]
> The build is fixed.

I confirm!
![Selection_199](https://user-images.githubusercontent.com/650571/106874564-ff2ae300-66d5-11eb-8ad0-bdc122016ff4.png)
