### ISSUE TITLE
Workspace fails to start due to Deployment name being too long

### ISSUE THREAD

**Issue by mhworth** [eclipse-che/che#19064]
### Describe the bug

When I try to create a workspace based upon a devfile that has a custom dockerfile, the generated name for the deployment exceeds the 63 character limit, causing the workspace creation to fail.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Create a space with a devfile with the same number of characters in the docker image as this one:
```
apiVersion: 1.0.0
metadata:
  generateName: wksp-
projects:
  - name: carta-work-tests
    clonePath: carta-work-tests
    source:
      type: git
      location: https://github.com/carta-healthcare/carta-work-tests
components:
  - type: dockerimage
    image: cartacr.azurecr.io/carta/platform:1.0.20
    memoryLimit: 1024Mi
    mountSources: true
    command: ['sleep', 'infinity']
```

### Expected behavior

I'd expect the workspace to start.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

Deployed on AKS/Azure

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know
 
Full command to install:
```
chectl server:deploy --multiuser --debug --platform=k8s --domain che.dev.carta.healthcare --k8spoderrorrechecktimeout 60000
```

Output of `chectl --version`:
```
chectl/0.0.20210212-next.00eb6b3 darwin-x64 node-v12.20.1
```

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [x] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs

```
2021-02-13 07:41:34,542[aceSharedPool-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 995]   - Workspace 'matt@carta.healthcare:wksp-kac99' with id 'workspacelk5bn7cxax557533' start failed
2021-02-13 07:41:34,623[ajor-endpoint-1]  [ERROR] [.e.c.a.c.j.c.RequestDispatcher 62]   - No corresponding to method 'unsubscribe' handler is registered
2021-02-13 07:57:47,277[nio-8080-exec-5]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.0.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-02-13 07:57:47,283[nio-8080-exec-5]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.0.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-02-13 07:57:58,007[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 364]    - Workspace 'workspace7fe2x24fn9wj1uyi' removed by user 'matt@carta.healthcare'
2021-02-13 07:58:01,951[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 364]    - Workspace 'workspacenavfa4z2psa48a6k' removed by user 'matt@carta.healthcare'
2021-02-13 07:59:17,744[nio-8080-exec-6]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.0.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-02-13 07:59:17,807[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'matt@carta.healthcare/python-test' with id 'workspacelk5bn7cxax557533' by user 'matt@carta.healthcare'
2021-02-13 07:59:17,860[aceSharedPool-7]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.0.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-02-13 07:59:17,926[aceSharedPool-7]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.0.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-02-13 08:00:10,252[aceSharedPool-7]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.0.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-02-13 08:00:39,873[aceSharedPool-7]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspacelk5bn7cxax557533.
org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Failure executing: POST at: https://10.0.0.1/apis/apps/v1/namespaces/matt-carta-healthcare-che-4tq7dv/deployments. Message: Deployment.apps "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20" is invalid: [spec.selector.matchLabels: Invalid value: "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20": must be no more than 63 characters, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"che.component.name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.deployment_name":"workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20", "che.original_name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.workspace_id":"workspacelk5bn7cxax557533", "deployment":"workspace"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: invalid label selector]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.selector.matchLabels, message=Invalid value: "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.selector, message=Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"che.component.name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.deployment_name":"workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20", "che.original_name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.workspace_id":"workspacelk5bn7cxax557533", "deployment":"workspace"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: invalid label selector, reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20" is invalid: [spec.selector.matchLabels: Invalid value: "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20": must be no more than 63 characters, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"che.component.name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.deployment_name":"workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20", "che.original_name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.workspace_id":"workspacelk5bn7cxax557533", "deployment":"workspace"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: invalid label selector], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.createDeployment(KubernetesDeployments.java:210)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.deploy(KubernetesDeployments.java:188)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.doStartMachine(KubernetesInternalRuntime.java:789)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.startMachines(KubernetesInternalRuntime.java:632)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:214)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:969)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.0.0.1/apis/apps/v1/namespaces/matt-carta-healthcare-che-4tq7dv/deployments. Message: Deployment.apps "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20" is invalid: [spec.selector.matchLabels: Invalid value: "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20": must be no more than 63 characters, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"che.component.name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.deployment_name":"workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20", "che.original_name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.workspace_id":"workspacelk5bn7cxax557533", "deployment":"workspace"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: invalid label selector]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.selector.matchLabels, message=Invalid value: "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.selector, message=Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"che.component.name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.deployment_name":"workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20", "che.original_name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.workspace_id":"workspacelk5bn7cxax557533", "deployment":"workspace"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: invalid label selector, reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20" is invalid: [spec.selector.matchLabels: Invalid value: "workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20": must be no more than 63 characters, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"che.component.name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.deployment_name":"workspacelk5bn7cxax557533.cartacr-azurecr-io-carta-platform-1-0-20", "che.original_name":"cartacr-azurecr-io-carta-platform-1-0-20", "che.workspace_id":"workspacelk5bn7cxax557533", "deployment":"workspace"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: invalid label selector], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:251)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:815)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:333)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.createDeployment(KubernetesDeployments.java:207)
	... 13 common frames omitted
2021-02-13 08:00:40,239[aceSharedPool-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 995]   - Workspace 'matt@carta.healthcare:python-test' with id 'workspacelk5bn7cxax557533' start failed
2021-02-13 08:00:40,297[ajor-endpoint-3]  [ERROR] [.e.c.a.c.j.c.RequestDispatcher 62]   - No corresponding to method 'unsubscribe' handler is registered
```

### Additional context

None to note.

**Comment by ibuziuk** [comment]
thanks for creating the issue. This is a known k8s / RFC-1123 label naming limitation. We probably need to improve the deployment names creation logic not to hit this limit on k8s end

**Comment by mhworth** [comment]
@ibuziuk Thanks for looking into it! Are there any workarounds for this right now? E.g. a way to fix the naming prefix? It appears that it generates the name from the image repository, so if there was some way to override the prefix to not be some.long.domain/long-repository-prefix/long-repository-name:long-tag, that would fix it I believe?
