### ISSUE TITLE
Happy path tests are failing on 'Validation of workspace build and run' step

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19085]
### Describe the bug

Happy path tests are failing on 'Validation of workspace build and run' step

```
11:48:37   1) Validation of workspace build and run
11:48:37        Run application:
11:48:37      TimeoutError: Wait timed out after 120415ms
11:48:37       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
11:48:37       at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
11:48:37       at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
11:48:37       at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
11:48:37       at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
11:48:37       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
11:48:37   From: Task: <anonymous wait>
11:48:37       at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
11:48:37       at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
11:48:37       at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
11:48:37       at Ide.waitApllicationIsReady (/tmp/e2e/pageobjects/ide/Ide.ts:310:45)
11:48:37       at Ide.waitNotificationAndOpenLink (/tmp/e2e/pageobjects/ide/Ide.ts:117:20)
11:48:37       at process._tickCallback (internal/process/next_tick.js:68:7)
11:48:37 
```
I don't know if it's a real bug detected by the tests or the result of an unstable test.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
I see this failure on different PRs of `che-theia`

### Expected behavior

The tests are happy.

### Runtime
I detected it on PR's check
Please see the tests reports:

- https://github.com/eclipse/che-theia/pull/994#issuecomment-780419357
- https://github.com/eclipse/che-theia/pull/778#issuecomment-780435869
- https://github.com/eclipse/che-theia/pull/695#issuecomment-780194350

**Comment by dmytro-ndp** [comment]
Should be fixed by https://github.com/eclipse/che/pull/19068
