### ISSUE TITLE
Che Server fail on workspace creation after execute chectl workspace:logs 

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#19258]
### Describe the bug

Che server fail running for example on running `chectl workspace:logs` command when workspace is in STARTING MODE.
Entire logs can be find:
    Minikube: https://github.com/che-incubator/chectl/pull/1127/checks?check_run_id=2075231207 (Download the artifacts to see the logs)
    
```log
2021-03-10 09:23:27,557[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspace8w7bxzci3vnhsl5k.
org.eclipse.che.api.workspace.server.spi.RuntimeStartInterruptedException: Runtime start for identity 'workspace: workspace8w7bxzci3vnhsl5k, environment: default, ownerId: 8d53da48-2430-493b-b158-841c28a19bd6' is interrupted
	at org.eclipse.che.workspace.infrastructure.kubernetes.StartSynchronizer.interrupt(StartSynchronizer.java:231)
	at org.eclipse.che.workspace.infrastructure.kubernetes.StartSynchronizer$RuntimeStartInterrupter.onEvent(StartSynchronizer.java:315)
	at org.eclipse.che.workspace.infrastructure.kubernetes.StartSynchronizer$RuntimeStartInterrupter.onEvent(StartSynchronizer.java:311)
	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:108)
	at org.eclipse.che.multiuser.api.distributed.WorkspaceStopPropagator.statusChanged(WorkspaceStopPropagator.java:50)
	at org.eclipse.che.multiuser.api.distributed.cache.JGroupsWorkspaceStatusCache$1.entrySet(JGroupsWorkspaceStatusCache.java:93)
	at org.jgroups.blocks.ReplicatedHashMap._replace(ReplicatedHashMap.java:403)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jgroups.blocks.MethodCall.invoke(MethodCall.java:127)
	at org.jgroups.blocks.RpcDispatcher.handle(RpcDispatcher.java:209)
	at org.jgroups.blocks.RequestCorrelator.handleRequest(RequestCorrelator.java:396)
	at org.jgroups.blocks.RequestCorrelator.dispatch(RequestCorrelator.java:357)
	at org.jgroups.blocks.RequestCorrelator.receiveMessageBatch(RequestCorrelator.java:327)
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:589)
	at org.jgroups.JChannel.up(JChannel.java:796)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:903)
	at org.jgroups.stack.Protocol.up(Protocol.java:338)
	at org.jgroups.stack.Protocol.up(Protocol.java:338)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:197)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:411)
	at org.jgroups.stack.Protocol.up(Protocol.java:338)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:296)
	at org.jgroups.protocols.pbcast.NAKACK2.deliverBatch(NAKACK2.java:952)
	at org.jgroups.protocols.pbcast.NAKACK2.removeAndDeliver(NAKACK2.java:886)
	at org.jgroups.protocols.pbcast.NAKACK2.handleMessages(NAKACK2.java:860)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:682)
	at org.jgroups.protocols.BARRIER.up(BARRIER.java:196)
	at org.jgroups.stack.Protocol.up(Protocol.java:338)
	at org.jgroups.protocols.FD.up(FD.java:281)
	at org.jgroups.stack.Protocol.up(Protocol.java:338)
	at org.jgroups.stack.Protocol.up(Protocol.java:338)
	at org.jgroups.stack.Protocol.up(Protocol.java:338)
	at org.jgroups.protocols.TP.passBatchUp(TP.java:1393)
	at org.jgroups.util.MaxOneThreadPerSender$BatchHandlerLoop.passBatchUp(MaxOneThreadPerSender.java:284)
	at org.jgroups.util.SubmitToThreadPool$BatchHandler.run(SubmitToThreadPool.java:136)
	at org.jgroups.util.MaxOneThreadPerSender$BatchHandlerLoop.run(MaxOneThreadPerSender.java:273)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```   
 
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
@flacatus that is just a log from interrupted workspaces. Is there a way to reproduce a bug?

**Comment by gazarenkov** [comment]
@flacatus @skabashnyuk is it still actual?

**Comment by skabashnyuk** [comment]
can't reproduce.
