### ISSUE TITLE
Stabilize E2E tests related to unexpected fail when start test workspace

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#19298]
### Is your task related to a problem? Please describe.
Several last launches on Che nightly jobs show unexpected fails of E2E tests related to start test workspace. This problem is observing to 'GitSsh flow', "OpenshiftConnector', 'Happy Path' ( here on Che single-host)

### Describe the solution you'd like
We need to investigate a reason of failing E2E tests and stabilize it.

### Additional context
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/eclipse-che/788/
![che-nightly-gitssh-e2e2](https://user-images.githubusercontent.com/5408906/111290914-4b5f3080-864f-11eb-9390-abff81b74271.png)

https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/eclipse-che/782/
![che-nightly-happy-path-e2e](https://user-images.githubusercontent.com/5408906/111290917-4bf7c700-864f-11eb-971d-2938ce267de6.png)

https://ci.centos.org/job/devtools-che-nightly-openshif-plugin-test/277/
![che-nightly-osconnector-e2e](https://user-images.githubusercontent.com/5408906/111290919-4c905d80-864f-11eb-9c78-607d97eb8586.png)

**Comment by dmytro-ndp** [comment]
One more workspace start timeout related failure to work around:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/dashboard-next-happy-path/452/
```
2021-03-16 08:47:40,394[nio-8080-exec-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'admin/java-maven-1brop' with id 'workspacerod9vgij2a8he1a4' by user 'admin'
2021-03-16 08:47:40,510[aceSharedPool-0]  [WARN ] [i.f.k.c.i.VersionUsageUtils 60]      - The client is using resource type 'ingresses' with unstable version 'v1beta1'
2021-03-16 08:47:40,933[aceSharedPool-0]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.96.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-03-16 08:47:41,605[aceSharedPool-0]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.96.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-03-16 08:47:50,215[aceSharedPool-0]  [WARN ] [k.n.KubernetesNamespaceFactory 635]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.96.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-03-16 08:55:40,524[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspacerod9vgij2a8he1a4.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Waiting for Kubernetes environment 'default' of the workspace'workspacerod9vgij2a8he1a4' reached timeout
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.waitMachines(KubernetesInternalRuntime.java:393)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:244)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:969)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
```
![screenshot-Wait_for_workspace_readiness (8)](https://user-images.githubusercontent.com/1197777/111297804-b6f8cc00-8656-11eb-82fb-3106db38edda.png)

**Comment by dmytro-ndp** [comment]
@artaleks9: according to screen cast of Git SSH Flow test it is failing because of unexpected refresh of web page while executing step "**Change commit and push**" (2:52 on video below):

https://user-images.githubusercontent.com/1197777/111357302-df51ec00-8691-11eb-951a-1881978d848f.mp4

**Comment by artaleks9** [comment]
@dmytro-ndp I investiged it and found that a problem is not with start (screenshot is a bit confused me/us),
E2E test tries to to stop and delete ws via API, but ws doesn't stop, continues run and test is fail.
And it that's all on this moment..need to continue work on it. Before that this functionality worked well.
```
Stopping workspace failed. URL used: api/workspace/workspacegfkgaa8u4qeai7bo
....
....
TimeoutError: The workspace was not stopped in 20000 ms. Currnet status is: RUNNING
19:38:36        at TestWorkspaceUtil.stopWorkspaceById (/tmp/e2e/utils/workspace/TestWorkspaceUtil.ts:171:23)
```

**Comment by artaleks9** [comment]
@dmytro-ndp For some reason this method doesn't work  as expected:

https://github.com/eclipse/che/blob/master/tests/e2e/utils/workspace/TestWorkspaceUtil.ts#L150

**Comment by dmytro-ndp** [comment]
Thanks for investigation. Looks like a different issue.

Openshift connector test has passed https://ci.centos.org/job/devtools-che-nightly-openshif-plugin-test/278/
IMHO https://github.com/eclipse/che/issues/19298 could be closed.

**Comment by artaleks9** [comment]
I agree.
