### ISSUE TITLE
Camel K stack mentioning fail to activate VS Code Camel K extension on Che 7.28 but is working

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19483]
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify 7.28.0

### Steps to reproduce

1. Create a Camel K stack
2. wait for the start, the VS Code Camel extension is not activating

```
ERROR:Activating extension 'Tooling for Apache Camel K by Red Hat' failed:TypeError: Cannot read property 'includes' of undefined
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by apupier** [comment]
nota, there is also this error but it is not a "real" problem. it just forbids to have Java completion which was missign Che feature to have tit working

```
ERROR:Remote plugin in vscode-camelk1qx: promise rejection is not handled in two seconds: Error: spawn mvn ENOENT
ERROR:Remote plugin in vscode-camelk1qx: promise rejection stack trace: Error: spawn mvn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 ```

**Comment by apupier** [comment]
what is strange is that all commands and menus are available. So woudl mean there is a "false" warnign that the extension cannot be activated?
