### ISSUE TITLE
Error launching task in IDE: Error starting process (ENOENT)

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#19528]
### Describe the bug
Happy path tests failed on launching task 'build-file-output' in IDE https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/4803/console:
```
            ‣ DriverHelper.waitVisibility By(css selector, li[title='build-file-output'] div.p-TabBar-tabIcon)
            ‣ DriverHelper.waitVisibility - Element is located and is visible.
  [ERROR] Task "build-file-output" failed.
    1) Build application
  [ERROR] CheReporter runner.on.fail: Validation of workspace build and run Build application failed after 2301ms


  8 passing (9m)
  1 pending
  1 failing

  1) Validation of workspace build and run
       Build application:
     Error: Task "build-file-output" failed.
      at driverHelper.getDriver.wait (/tmp/e2e/pageobjects/ide/Terminal.ts:179:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous>
      at pollCondition (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2191:7
      at new ManagedPromise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at ControlFlow.promise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2505:12)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2190:22
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: Timed out waiting for task build-file-output to succeed.
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Terminal.waitIconSuccess (/tmp/e2e/pageobjects/ide/Terminal.ts:172:45)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

[Che-theia container logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/4806/artifact/logs-and-configs/workspace-logs/theia-ide3qp.container.log/*view*/):
```
2021-04-08 08:35:27.525 process ERROR Error: ENOENT
    at EventEmitter.<anonymous> (/home/theia/node_modules/@theia/process/lib/node/terminal-process.js:88:33)
    at EventEmitter.emit (events.js:314:20)
    at UnixTerminal.Terminal.emit (/home/theia/node_modules/@theia/node-pty/lib/terminal.js:132:42)
    at /home/theia/node_modules/@theia/node-pty/lib/unixTerminal.js:117:23
    at processTicksAndRejections (internal/process/task_queues.js:79:11) 
2021-04-08 08:35:27.525 task ERROR Error occurred while creating task: Error: Error starting process (ENOENT) 
2021-04-08 08:35:27.531 process WARN This process was not registered or was already unregistered. [ID: 0] 
2021-04-08 08:35:27.693 root ERROR Error launching task 'build-file-output': Error starting process (ENOENT) Params: Error: Request 'run' failed
    at Proxy.<anonymous> (https://serverjxq69wfj-jwtproxy-server-4402.10.0.206.194.nip.io/theia.43ea6a7bbfd07c6aab07.js:1:1633372)
    at t.<anonymous> (https://serverjxq69wfj-jwtproxy-server-4402.10.0.206.194.nip.io/theia.43ea6a7bbfd07c6aab07.js:1:942820)
    at https://serverjxq69wfj-jwtproxy-server-4402.10.0.206.194.nip.io/theia.43ea6a7bbfd07c6aab07.js:1:942002
    at Object.next (https://serverjxq69wfj-jwtproxy-server-4402.10.0.206.194.nip.io/theia.43ea6a7bbfd07c6aab07.js:1:942107)
    at a (https://serverjxq69wfj-jwtproxy-server-4402.10.0.206.194.nip.io/theia.43ea6a7bbfd07c6aab07.js:1:940821)
Caused by: Error: Error starting process (ENOENT)
    at /home/theia/node_modules/@theia/task/lib/node/process/process-task-runner.js:137:77
    at /home/theia/node_modules/@theia/core/lib/common/event.js:176:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:191:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:318:29)
    at TerminalProcess.Process.emitOnError (/home/theia/node_modules/@theia/process/lib/node/process.js:161:27)
    at EventEmitter.<anonymous> (/home/theia/node_modules/@theia/process/lib/node/terminal-process.js:90:27)
    at EventEmitter.emit (events.js:314:20)
    at UnixTerminal.Terminal.emit (/home/theia/node_modules/@theia/node-pty/lib/terminal.js:132:42)
    at /home/theia/node_modules/@theia/node-pty/lib/unixTerminal.js:117:23
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy nightly Eclipse Che 7.29.0.
2. Create and start java maven workspace
3. Run build task.

### Expected behavior
Build task has been executed with logs inside terminal window.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Build_application](https://user-images.githubusercontent.com/1197777/113985832-3e4fee80-9855-11eb-86d7-61b0b1f4ee62.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Additional context
Related changes: https://github.com/eclipse-che/che-theia/pull/1071

**Comment by azatsarynnyy** [comment]
Fixed https://github.com/eclipse-che/che-theia/pull/1071#issuecomment-815849397
