### ISSUE TITLE
Consistent proxy configuration for all tools used by chectl needed

### ISSUE THREAD

**Issue by cb3zopp** [eclipse-che/che#19622]
### Describe the bug
C:\cloud> minikube start --addons=ingress --vm=true --memory=8192
* minikube v1.19.0 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
* Automatically selected the hyperv driver                                                                              
* Starting control plane node minikube in cluster minikube                                                              
* Creating hyperv VM (CPUs=2, Memory=8192MB, Disk=20000MB) ...
* Found network options:
  - HTTP_PROXY=185.46.212.88:80
  - HTTPS_PROXY=185.46.212.88:80
  - NO_PROXY=192.168.99.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12,10.113.41.0/24,172.0.0.0/8,127.0.0.1/32
  - http_proxy=185.46.212.88:80
  - https_proxy=185.46.212.88:80
  - no_proxy=192.168.99.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12,10.113.41.0/24,172.0.0.0/8,127.0.0.1/32
* Preparing Kubernetes v1.20.2 on Docker 20.10.4 ...
  - env HTTP_PROXY=185.46.212.88:80
  - env HTTPS_PROXY=185.46.212.88:80
  - env NO_PROXY=192.168.99.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12,10.113.41.0/24,172.0.0.0/8,127.0.0.1/32
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
  - Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
  - Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
  - Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
* Verifying ingress addon...
* Enabled addons: storage-provisioner, default-storageclass, ingress
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
PS C:\cloud> kubectl get po -A
NAMESPACE       NAME                                        READY   STATUS      RESTARTS   AGE
ingress-nginx   ingress-nginx-admission-create-hcdsd        0/1     Completed   0          68s
ingress-nginx   ingress-nginx-admission-patch-cmj5m         0/1     Completed   1          68s
ingress-nginx   ingress-nginx-controller-5d88495688-csffz   1/1     Running     0          68s
kube-system     coredns-74ff55c5b-jjclk                     1/1     Running     0          68s
kube-system     etcd-minikube                               0/1     Running     0          84s
kube-system     kube-apiserver-minikube                     1/1     Running     0          84s
kube-system     kube-controller-manager-minikube            0/1     Running     0          84s
kube-system     kube-proxy-54t4x                            1/1     Running     0          68s
kube-system     kube-scheduler-minikube                     1/1     Running     0          84s
kube-system     storage-provisioner                         1/1     Running     1          81s
PS C:\cloud> chectl server:deploy
› Installer type is set to: 'operator'
› Current Kubernetes context: 'minikube'
  × Verify Kubernetes API
    → Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint: https://172.26.112.56:8443/healthz
-…
    👀  Looking for an already existing Eclipse Che instance
 »   Error: Error: Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint:
 »   https://172.26.112.56:8443/healthz - Error message: getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes
 »   cluster is healthy - you can skip this check with '--skip-kubernetes-health-check' flag.
 »   Command server:deploy failed. Error log: C:\Users\cb3zopp\AppData\Local\chectl\error.log Eclipse Che logs:
 »   C:\Users\cb3zopp\AppData\Local\Temp\chectl-logs\1618830495341
PS C:\cloud> chectl server:deploy --skip-kubernetes-health-check
› Installer type is set to: 'operator'
› Current Kubernetes context: 'minikube'
  × Verify Kubernetes API...OK
    → Failed to connect to Kubernetes API, error: Error: tunneling socket could not be established, cause=getaddrinfo E
N…
    👀  Looking for an already existing Eclipse Che instance
 »   Error: Error: Failed to connect to Kubernetes API, error: Error: tunneling socket could not be established,
 »   cause=getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes cluster is healthy - you can skip this check
 »   with '--skip-kubernetes-health-check' flag.
 »   Command server:deploy failed. Error log: C:\Users\cb3zopp\AppData\Local\chectl\error.log Eclipse Che logs:
 »   C:\Users\cb3zopp\AppData\Local\Temp\chectl-logs\1618830557145

In an environment without proxies this works. But in Azure I have to use a company proxy.
My proxy configuration works for minikube and for edge but I guess there are tools (node.js?) used in checht that still have problems to work with proxies. Is there a way to set proxy/no_proxy for all chectl used tools?

### Che version
chectl/0.0.20210408-next.cf44212 win32-x64 node-v12.22.0
### Steps to reproduce
See commands above.

### Expected behavior
My proxy configuration works for minikube and for edge but I guess there are tools (node.js?) used in chectl that still have problems to work with proxies. Is there a way to set proxy/no_proxy for all chectl used tool?

Azure -> Win 10 PRO -> Hyper-V -> minikube -> chectl

### Eclipse Che Logs
Logfile:
2021-04-19T10:18:32.701Z Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80
2021-04-19T10:18:32.701Z     at ClientRequest.onError (C:/ProgramData/chectl/chectl/node_modules/tunnel-agent/index.js:177:17)
2021-04-19T10:21:14.540Z Error: Error: Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint: https://172.26.119.42:8443/healthz - Error message: getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes cluster is healthy - you can skip this check with '--skip-kubernetes-health-check' flag.
2021-04-19T10:21:14.540Z Command server:deploy failed. Error log: C:/Users/cb3zopp/AppData/Local/chectl/error.log Eclipse Che logs: C:/Users/cb3zopp/AppData/Local/Temp/chectl-logs/1618827666610
2021-04-19T10:21:14.540Z     at Object.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/errors/lib/index.js:26:15)
2021-04-19T10:21:14.540Z     at Deploy.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/command/lib/command.js:60:23)
2021-04-19T10:21:14.540Z     at Deploy.<anonymous> (C:/ProgramData/chectl/chectl/lib/commands/server/deploy.js:245:22)
2021-04-19T10:21:14.540Z     at Generator.throw (<anonymous>)
2021-04-19T10:21:14.540Z     at rejected (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:115:69)
2021-04-19T10:22:11.887Z Error: Error: Failed to connect to Kubernetes API, error: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes cluster is healthy - you can skip this check with '--skip-kubernetes-health-check' flag.
2021-04-19T10:22:11.887Z Command server:deploy failed. Error log: C:/Users/cb3zopp/AppData/Local/chectl/error.log Eclipse Che logs: C:/Users/cb3zopp/AppData/Local/Temp/chectl-logs/1618827724801
2021-04-19T10:22:11.887Z     at Object.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/errors/lib/index.js:26:15)
2021-04-19T10:22:11.887Z     at Deploy.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/command/lib/command.js:60:23)
2021-04-19T10:22:11.887Z     at Deploy.<anonymous> (C:/ProgramData/chectl/chectl/lib/commands/server/deploy.js:245:22)
2021-04-19T10:22:11.887Z     at Generator.throw (<anonymous>)
2021-04-19T10:22:11.887Z     at rejected (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:115:69)
2021-04-19T11:08:22.518Z Error: Error: Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint: https://172.26.112.56:8443/healthz - Error message: getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes cluster is healthy - you can skip this check with '--skip-kubernetes-health-check' flag.
2021-04-19T11:08:22.518Z Command server:deploy failed. Error log: C:/Users/cb3zopp/AppData/Local/chectl/error.log Eclipse Che logs: C:/Users/cb3zopp/AppData/Local/Temp/chectl-logs/1618830495341
2021-04-19T11:08:22.518Z     at Object.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/errors/lib/index.js:26:15)
2021-04-19T11:08:22.518Z     at Deploy.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/command/lib/command.js:60:23)
2021-04-19T11:08:22.518Z     at Deploy.<anonymous> (C:/ProgramData/chectl/chectl/lib/commands/server/deploy.js:245:22)
2021-04-19T11:08:22.518Z     at Generator.throw (<anonymous>)
2021-04-19T11:08:22.518Z     at rejected (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:115:69)
2021-04-19T11:09:24.335Z Error: Error: Failed to connect to Kubernetes API, error: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes cluster is healthy - you can skip this check with '--skip-kubernetes-health-check' flag.
2021-04-19T11:09:24.335Z Command server:deploy failed. Error log: C:/Users/cb3zopp/AppData/Local/chectl/error.log Eclipse Che logs: C:/Users/cb3zopp/AppData/Local/Temp/chectl-logs/1618830557145
2021-04-19T11:09:24.335Z     at Object.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/errors/lib/index.js:26:15)
2021-04-19T11:09:24.335Z     at Deploy.error (C:/ProgramData/chectl/chectl/node_modules/@oclif/command/lib/command.js:60:23)
2021-04-19T11:09:24.335Z     at Deploy.<anonymous> (C:/ProgramData/chectl/chectl/lib/commands/server/deploy.js:245:22)
2021-04-19T11:09:24.335Z     at Generator.throw (<anonymous>)
2021-04-19T11:09:24.335Z     at rejected (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:115:69)

**Comment by flacatus** [comment]
Hello @cb3zopp !
Thank you very much to open this issue!
Seems like there is a issue with your proxy configuration.

I was able to reproduce your issue with chectl following next steps:
1. Install squid server
2. configure HTTP_PROXY, HTTPS_PROXY,NO_PROXY for minikube like here: `https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/`
3. Run chectl and I got the same error like you:  `Error: tunneling socket could not be established`
I see chectl is trying to speak with Kubernetes API Server on port 8443 and my proxy denied connections to this port. When I enabled port 8443 in my proxy server chectl start to work normally.

I suggest you to:
1. Try to get your proxy logs and see if is blocking connection to port 8443
2. Configure your proxy to make connection to port 8443.

Screenshoot with my squid server logs:
![image](https://user-images.githubusercontent.com/59865209/116688284-c76ec700-a9b6-11eb-8969-c683d9d70ed3.png)
 
 First I got 403 but after configuring correctly the port in proxy server start to work normally.
 
 Thank you!

**Comment by cb3zopp** [comment]
Hello Flacatus,
1) my proxy-server is not between chectl and the minikube. chectl is running as kubectl too on a windows system and minikube is running on a Hyper-V container on local 172.x.x.x adresses. So everrything what I do with kubectl or minikube directly works with the above proxy configuration.
2) The proxy is a company proxy which I can't change. It is only used to reach the internet.
3) If you configure a tool to use a proxy it has to use 3 things: 
- an address/port for HTTP (set for kube with HTTP_PROXY),
- an address/port for HTTPS (set with HTTPS_PROXY)
- and an exlusion list for adresses which should not be sent to the proxy (set with NO_PROXY).
4) Because minikube runs localy I need to include it's adresses on the NO_PROXY-list (172.0.0.0/8)

I have eclipse che also running on a private system without a proxy - there is no problem.

I guess there is a software in chectl (node.js I think) that is not or not correct configured to use the proxy. Where does chectl take it's proxy config from? 
If it would take the config from the kubernets environment settings it would not try to connect on port 8443 - because port 80 is defined. It also would not try to use the proxy at all because the the local ip adresses are on the NO_PROXY list.

In any case I can't change the company's proxy config. chectl and all it's subtools have to take over a central defined proxy configuration.

**Comment by flacatus** [comment]
@cb3zopp Thank you for feedback!

Ok , I will investigate more deeper how chectl use proxy environments on windows.

**Comment by flacatus** [comment]
Hello @cb3zopp !

Can you try please to add to the NON_PROXY env the minikube_ip:8443?
In my case I added to Windows env and seems is working.
chectl command:
`chectl server:deploy --installer=operator --platform=minikube --skip-kubernetes-health-check`

Thank you!

**Comment by cb3zopp** [comment]
Which port range is missing? The cluster IP is 10.96.0.1 this should also be excluded via 10.96.0.0/12.
Why does minikube and cubectl work, but chectl doesn't.
Also minikube dashbord and other kubernetes deployments work.
Why do I get a hint to use --skip-kubernetes-health-check while I already use the flag.

**Comment by cb3zopp** [comment]
Which address do you exacly mean? The cluster adress is 10.96.0.1. This should be excluded from proxy with 10.96.0.0/12 for all ports. Bud I did add 10.96.0.1:8443 to the NO_PROXY env. It had no effect.
By the way minikube and kubectl work. I can deply and use other kybernetes loads and can use the Dashboard as well.

**Comment by flacatus** [comment]
@cb3zopp In your logs I see `https://172.26.119.42:8443/healthz` which I guess is your minikube ip..
Kubectl have different way to comunicate with minikube kubernetes api.

**Comment by cb3zopp** [comment]
I have no luck with this. I tried 172.0.0.0/8 (already in the config above). I also tried 172.26.0.0/16, 172.16.0.0/12 and 172.26.119.42 with and without port. No change of behavior.
