### ISSUE TITLE
Projector can't render some Markdown files

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19702]
### Is your task related to a problem? Please describe.
After cloning the Eclipse Theia repository in the IDEA Che Editor it opens the README.md file automatically, but there some issues with rendering the Markdown content. See the attached screenshot.

### Describe the solution you'd like
Probably, some required libs are missing in the IDEA image.

### Additional context

![image](https://user-images.githubusercontent.com/1636395/116424538-44c8f900-a84a-11eb-8258-c0b9de4fca8e.png)

<details>
	<summary>The container logs:</summary>
<pre>
Prevent workspace from unexpected shutdown
Copy default configuration
Wed Apr 28 15:14:19 UTC 2021 - Perform request: 'curl -X PUT  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNGJibTc2ZnVoOGhrOXg0cSJ9.eyJ3c2lkIjoid29ya3NwYWNlNGJibTc2ZnVoOGhrOXg0cSIsInVpZCI6IjYxMzc5ZjdjLTU3M2EtNDExYi05MDE0LTAwMGViNzlmNWY3YiIsImF1ZCI6IndvcmtzcGFjZTRiYm03NmZ1aDhoazl4NHEiLCJuYmYiOi0xLCJ1bmFtZSI6ImF6YXRzYXJ5bm55eSIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjUxMTU4ODQ3LCJpYXQiOjE2MTk2MjI4NDcsImp0aSI6IjgwMmRjNjFmLTg2NDMtNDFlNy05NDY2LWE5YWVjZWMxMzNhMiJ9.h3kZdnyhA2LgogVLaEMV6DIRccFm_NfS2qQgBZmPd4y0LqPrEADDa8Wny38nJJL_MOJOYfTFW0etym96qp-FbVLjxqjynkOAN_4rp1-QmVc_p2TBu7yREWDov3LB5a7VDVjVKT2rUyfDZTa_IP4PG-RMIxmJOD7MNSa-V0T_wkCg9_jzTf6fTEcbVkuSTbNWmA_M7t-C2dydPd_elWPjygSTgl6wVSq1f7gcFw_xtyUZ9_DEnq1pNp0JGwhQ6A11Ypx6WnMPOZZnsu9tzA-Hwri1gotGMlUcLB9OhEk2haIBJE6zkljdI35HZTb4BMR6PgVPZgn_5utot61oq3k19Q" https://codeready-codeready-workspaces-operator.apps.che-dev.x6e0.p1.openshiftapps.com/api/activity/workspace4bbm76fuh8hk9x4q'.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Found IDE: idea
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Wed Apr 28 15:14:19 UTC 2021 - Sleep for 1 minute.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[DEBUG] :: IdeState :: Starting attempts to attach IJ injector agent
[DEBUG] :: IdeState :: Starting attempts to initialize IDEA: fix AA and disable smooth scrolling (at start)
[INFO] :: ProjectorServer :: ProjectorServer is starting on host 0.0.0.0/0.0.0.0 and port 8887
[DEBUG] :: IdeState :: Starting attempts to Getting IDE colors
[INFO] :: ProjectorServer :: WebSocket SSL is disabled
[INFO] :: ProjectorServer :: Server started on host 0.0.0.0/0.0.0.0 and port 8887
[DEBUG] :: ProjectorServer :: Daemon thread starts
[DEBUG] :: IdeState :: Starting attempts to search for editors
Apr 28, 2021 3:14:21 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Apr 28, 2021 3:14:21 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/projector-user/.java/.userPrefs/prefs.xml
[INFO] :: ProjectorServer :: 127.0.0.1 connected.
[DEBUG] :: IdeState :: Starting attempts to set keymap to match user's OS (LINUX)
[DEBUG] :: IdeState :: "search for editors" is done
[DEBUG] :: IdeState :: "set keymap to match user's OS (LINUX)" is done
[DEBUG] :: util.agent.MiscKt :: dynamically attaching agent: jar=/tmp/projector-agent686014480112796984.jar, args=false;org.jetbrains.projector.server.core.ij.IjInjectorAgentInitializer;getIdeClassloader;org.jetbrains.projector.server.core.ij.md.MarkdownPanelMaker;createMarkdownHtmlPanel
[DEBUG] :: IjInjectorAgent :: IjInjectorAgent agentmain start, args=false;org.jetbrains.projector.server.core.ij.IjInjectorAgentInitializer;getIdeClassloader;org.jetbrains.projector.server.core.ij.md.MarkdownPanelMaker;createMarkdownHtmlPanel
[DEBUG] :: IjLigaturesDisablerTransformer :: agentmain start
[DEBUG] :: IjLigaturesDisablerTransformer :: Transforming fontprefs...
[DEBUG] :: IjLigaturesDisablerTransformer :: Transforming fontprefs...
[DEBUG] :: IjLigaturesDisablerTransformer :: agentmain finish
[DEBUG] :: IjMdTransformer :: IjMdTransformer agentmain start
[ERROR] :: IjMdTransformer :: Class retransform error :: java.lang.ClassNotFoundException: org.intellij.plugins.markdown.ui.preview.javafx.JavaFxHtmlPanelProvider PluginClassLoader[PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, path=/projector/ide/plugins/markdown, version=203.7717.56)] com.intellij.ide.plugins.cl.PluginClassLoader@72d1dd3a
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.jetbrains.projector.agent.ijInjector.IjMdTransformer$Companion.agentmain(IjMdTransformer.kt:148)
	at org.jetbrains.projector.agent.ijInjector.IjInjector.agentmain(IjInjector.kt:63)
	at org.jetbrains.projector.agent.ijInjector.IjInjectorAgent.agentmain(IjInjectorAgent.kt:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)

2021-04-28 15:15:01,870 [  40978]  ERROR -                IjMdTransformer - Class retransform error
java.lang.ClassNotFoundException: org.intellij.plugins.markdown.ui.preview.javafx.JavaFxHtmlPanelProvider PluginClassLoader[PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, path=/projector/ide/plugins/markdown, version=203.7717.56)] com.intellij.ide.plugins.cl.PluginClassLoader@72d1dd3a
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.jetbrains.projector.agent.ijInjector.IjMdTransformer$Companion.agentmain(IjMdTransformer.kt:148)
	at org.jetbrains.projector.agent.ijInjector.IjInjector.agentmain(IjInjector.kt:63)
	at org.jetbrains.projector.agent.ijInjector.IjInjectorAgent.agentmain(IjInjectorAgent.kt:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
2021-04-28 15:15:01,874 [  40982]  ERROR -                IjMdTransformer - IntelliJ IDEA 2020.3.3  Build #IC-203.7717.56
2021-04-28 15:15:02,056 [  41164]  ERROR -                IjMdTransformer - JDK: 11.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2021-04-28 15:15:02,058 [  41166]  ERROR -                IjMdTransformer - OS: Linux
[DEBUG] :: IjMdTransformer :: Transforming MdHtmlPanelProvider (JCEF Browser)...
[DEBUG] :: IjMdTransformer :: IjMdTransformer agentmain finish
[DEBUG] :: IjBrowserUtilTransformer :: agentmain start
[DEBUG] :: IjBrowserUtilTransformer :: Transforming BrowserUtil...
2021-04-28 15:15:02,388 [  41496]   WARN - pi.util.registry.RegistryValue - Attempt to load key 'lcd.contrast.value' for not yet loaded registry
[DEBUG] :: IjBrowserUtilTransformer :: Transforming BrowserUtil...
[DEBUG] :: SettingsInitializer :: Found IDEA aa: LCD HRGB antialiasing text mode
[DEBUG] :: IdeState :: "initialize IDEA: fix AA and disable smooth scrolling (at start)" is done
[DEBUG] :: IjBrowserUtilTransformer :: agentmain finish
[DEBUG] :: IjInjectorAgent :: IjInjectorAgent agentmain finish
[DEBUG] :: util.agent.MiscKt :: dynamically attaching agent is done: jar=/tmp/projector-agent686014480112796984.jar, args=false;org.jetbrains.projector.server.core.ij.IjInjectorAgentInitializer;getIdeClassloader;org.jetbrains.projector.server.core.ij.md.MarkdownPanelMaker;createMarkdownHtmlPanel
[DEBUG] :: IdeState :: "attach IJ injector agent" is done
2021-04-28 15:15:02,676 [  41784]   WARN - pi.util.registry.RegistryValue - Attempt to load key 'linux.row.height.disabled' for not yet loaded registry
2021-04-28 15:15:02,678 [  41786]   WARN - pi.util.registry.RegistryValue - Attempt to load key 'ide.disable.fractionalMetrics' for not yet loaded registry
[DEBUG] :: IdeState :: "Getting IDE colors" is done
Wed Apr 28 15:15:19 UTC 2021 - Perform request: 'curl -X PUT  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNGJibTc2ZnVoOGhrOXg0cSJ9.eyJ3c2lkIjoid29ya3NwYWNlNGJibTc2ZnVoOGhrOXg0cSIsInVpZCI6IjYxMzc5ZjdjLTU3M2EtNDExYi05MDE0LTAwMGViNzlmNWY3YiIsImF1ZCI6IndvcmtzcGFjZTRiYm03NmZ1aDhoazl4NHEiLCJuYmYiOi0xLCJ1bmFtZSI6ImF6YXRzYXJ5bm55eSIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjUxMTU4ODQ3LCJpYXQiOjE2MTk2MjI4NDcsImp0aSI6IjgwMmRjNjFmLTg2NDMtNDFlNy05NDY2LWE5YWVjZWMxMzNhMiJ9.h3kZdnyhA2LgogVLaEMV6DIRccFm_NfS2qQgBZmPd4y0LqPrEADDa8Wny38nJJL_MOJOYfTFW0etym96qp-FbVLjxqjynkOAN_4rp1-QmVc_p2TBu7yREWDov3LB5a7VDVjVKT2rUyfDZTa_IP4PG-RMIxmJOD7MNSa-V0T_wkCg9_jzTf6fTEcbVkuSTbNWmA_M7t-C2dydPd_elWPjygSTgl6wVSq1f7gcFw_xtyUZ9_DEnq1pNp0JGwhQ6A11Ypx6WnMPOZZnsu9tzA-Hwri1gotGMlUcLB9OhEk2haIBJE6zkljdI35HZTb4BMR6PgVPZgn_5utot61oq3k19Q" https://codeready-codeready-workspaces-operator.apps.che-dev.x6e0.p1.openshiftapps.com/api/activity/workspace4bbm76fuh8hk9x4q'.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Wed Apr 28 15:15:19 UTC 2021 - Sleep for 1 minute.
Wed Apr 28 15:16:19 UTC 2021 - Perform request: 'curl -X PUT  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNGJibTc2ZnVoOGhrOXg0cSJ9.eyJ3c2lkIjoid29ya3NwYWNlNGJibTc2ZnVoOGhrOXg0cSIsInVpZCI6IjYxMzc5ZjdjLTU3M2EtNDExYi05MDE0LTAwMGViNzlmNWY3YiIsImF1ZCI6IndvcmtzcGFjZTRiYm03NmZ1aDhoazl4NHEiLCJuYmYiOi0xLCJ1bmFtZSI6ImF6YXRzYXJ5bm55eSIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjUxMTU4ODQ3LCJpYXQiOjE2MTk2MjI4NDcsImp0aSI6IjgwMmRjNjFmLTg2NDMtNDFlNy05NDY2LWE5YWVjZWMxMzNhMiJ9.h3kZdnyhA2LgogVLaEMV6DIRccFm_NfS2qQgBZmPd4y0LqPrEADDa8Wny38nJJL_MOJOYfTFW0etym96qp-FbVLjxqjynkOAN_4rp1-QmVc_p2TBu7yREWDov3LB5a7VDVjVKT2rUyfDZTa_IP4PG-RMIxmJOD7MNSa-V0T_wkCg9_jzTf6fTEcbVkuSTbNWmA_M7t-C2dydPd_elWPjygSTgl6wVSq1f7gcFw_xtyUZ9_DEnq1pNp0JGwhQ6A11Ypx6WnMPOZZnsu9tzA-Hwri1gotGMlUcLB9OhEk2haIBJE6zkljdI35HZTb4BMR6PgVPZgn_5utot61oq3k19Q" https://codeready-codeready-workspaces-operator.apps.che-dev.x6e0.p1.openshiftapps.com/api/activity/workspace4bbm76fuh8hk9x4q'.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Wed Apr 28 15:16:19 UTC 2021 - Sleep for 1 minute.
[Fatal Error] :5:16: The entity name must immediately follow the '&' in the entity reference.
[ERROR] :: PanelDelegate :: Can't set HTML in Panel #1...
2021-04-28 15:16:24,463 [ 123571]  ERROR -                  PanelDelegate - Can't set HTML in Panel #1...
2021-04-28 15:16:24,463 [ 123571]  ERROR -                  PanelDelegate - IntelliJ IDEA 2020.3.3  Build #IC-203.7717.56
2021-04-28 15:16:24,464 [ 123572]  ERROR -                  PanelDelegate - JDK: 11.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2021-04-28 15:16:24,464 [ 123572]  ERROR -                  PanelDelegate - OS: Linux
2021-04-28 15:16:24,464 [ 123572]  ERROR -                  PanelDelegate - Last Action: Vcs.VcsClone
[Fatal Error] :5:16: The entity name must immediately follow the '&' in the entity reference.
[ERROR] :: PanelDelegate :: Can't set HTML in Panel #2...
2021-04-28 15:16:25,989 [ 125097]  ERROR -                  PanelDelegate - Can't set HTML in Panel #2...
2021-04-28 15:16:25,989 [ 125097]  ERROR -                  PanelDelegate - IntelliJ IDEA 2020.3.3  Build #IC-203.7717.56
2021-04-28 15:16:25,989 [ 125097]  ERROR -                  PanelDelegate - JDK: 11.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2021-04-28 15:16:25,989 [ 125097]  ERROR -                  PanelDelegate - OS: Linux
2021-04-28 15:16:25,989 [ 125097]  ERROR -                  PanelDelegate - Last Action: Vcs.VcsClone
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/projector/ide/projector-server/lib/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/projector/ide/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
</pre>
</details>

**Comment by vzhukovs** [comment]
Deep stacktrace:
```
2021-04-29 13:51:49,861 [6536216]  ERROR -                  PanelDelegate - Can't set HTML in Panel #4... 
org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 16; The entity name must immediately follow the '&' in the entity reference.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
        at org.jetbrains.projector.server.core.ij.md.LocalImagesInliner.inlineLocalImages(LocalImagesInliner.kt:53)
        at org.jetbrains.projector.server.core.ij.md.PanelDelegate.setHtml(PanelDelegate.kt:137)
        at org.jetbrains.projector.server.core.ij.md.PanelDelegate.setHtml(PanelDelegate.kt:152)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.intellij.plugins.markdown.ui.preview.ProjectorMarkdownHtmlPanel.setHtml(ProjectorMarkdownHtmlPanel.java)
        at org.intellij.plugins.markdown.ui.preview.MarkdownPreviewFileEditor.lambda$updateHtml$2(MarkdownPreviewFileEditor.java:315)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.Alarm$Request.runSafely(Alarm.java:376)
        at com.intellij.util.Alarm$Request.run(Alarm.java:362)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
        at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Some of markdown documents might have html tags and parser used in projector-client tries to parse the document and fetch img tags. And parsing fails if document contains unescaped chars `&` and '>'

**Comment by vzhukovs** [comment]
Fix will be provided into upstream.

**Comment by vzhukovs** [comment]
Related links:
- https://www.geeksforgeeks.org/escaping-xml-special-characters-in-java-string/
- https://stackoverflow.com/questions/32652424/entity-name-must-immediately-follow-the-in-the-entity-reference
- https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents/46637835#46637835

**Comment by azatsarynnyy** [comment]
Thanks Vlad for looking at it! We'll take it to the next sprint.

**Comment by vzhukovs** [comment]
Provided upstream PR: https://github.com/JetBrains/projector-client/pull/25
