### ISSUE TITLE
Happy path tests are failing on "Build application" step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#19886]
### Describe the bug

Eclipse Che Happy path tests are failing on "_Build application_" step:
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/47/console

Error log:
```
07:45:46            ▼ QuickOpenContainer.waitContainerDisappearance
07:45:46              ‣ DriverHelper.waitDisappearance By(xpath, //div[@class='monaco-quick-open-widget' and @aria-hidden='true'])
07:45:46              ‣ DriverHelper.waitDisappearanceBoolean By(xpath, //div[@class='monaco-quick-open-widget' and @aria-hidden='true'])
07:45:46              ‣ DriverHelper.isVisible By(xpath, //div[@class='monaco-quick-open-widget' and @aria-hidden='true'])
07:45:46              ‣ DriverHelper.waitAndClick - Polling timed out attempt #3, retrying with 1000ms timeout
07:45:46              ‣ DriverHelper.waitVisibility By(xpath, //div[@class='p-Menu-itemLabel' and text()='Go to Definition'])
07:45:46              ‣ DriverHelper.waitVisibility By(css selector, li[title='build-file-output'] div.p-TabBar-tabIcon)
07:45:47              ‣ DriverHelper.waitAndClick - Polling timed out attempt #4, retrying with 1000ms timeout
07:45:47              ‣ DriverHelper.waitVisibility By(xpath, //div[@class='p-Menu-itemLabel' and text()='Go to Definition'])
07:45:47              ‣ DriverHelper.waitVisibility - Polling timed out attempt #1, retrying with 1000ms timeout
07:45:48              ‣ DriverHelper.waitAndClick - Polling timed out attempt #5, retrying with 1000ms timeout
07:45:48              ‣ DriverHelper.waitVisibility By(xpath, //div[@class='p-Menu-itemLabel' and text()='Go to Definition'])
07:45:48              ‣ DriverHelper.waitVisibility - Polling timed out attempt #2, retrying with 1000ms timeout
07:45:49              ‣ DriverHelper.waitAndClick - Polling timed out attempt #6, retrying with 1000ms timeout
07:45:49              ‣ DriverHelper.waitVisibility By(xpath, //div[@class='p-Menu-itemLabel' and text()='Go to Definition'])
07:45:49              ‣ DriverHelper.waitVisibility - Polling timed out attempt #3, retrying with 1000ms timeout
07:45:50              ‣ DriverHelper.waitAndClick - Polling timed out attempt #7, retrying with 1000ms timeout
07:45:50              ‣ DriverHelper.waitVisibility By(xpath, //div[@class='p-Menu-itemLabel' and text()='Go to Definition'])
07:45:50              ‣ DriverHelper.waitVisibility - Polling timed out attempt #4, retrying with 1000ms timeout
07:45:51              ‣ DriverHelper.waitAndClick - Polling timed out attempt #8, retrying with 1000ms timeout
07:45:51              ‣ DriverHelper.waitVisibility By(xpath, //div[@class='p-Menu-itemLabel' and text()='Go to Definition'])
07:45:51              ‣ DriverHelper.waitVisibility - Polling timed out attempt #5, retrying with 1000ms timeout
07:45:51      1) Build application
07:45:51    [ERROR] CheReporter runner.on.fail: Validation of workspace build and run Build application failed after 10711ms
07:45:51  
07:45:51  
07:45:51    8 passing (8m)
07:45:51    1 pending
07:45:51    1 failing
07:45:51  
07:45:51    1) Validation of workspace build and run
07:45:51         Build application:
07:45:51       TimeoutError: Exceeded maximum visibility checkings attempts for 'By(css selector, li[title='build-file-output'] div.p-TabBar-tabIcon)' element, timeouted after 5000
07:45:51        at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:156:15)
07:45:51        at process._tickCallback (internal/process/next_tick.js:68:7)
```

![screenshot-Build_application (1)](https://user-images.githubusercontent.com/1197777/119937525-9670ba80-bf93-11eb-9865-703b95c8f6d8.png)

Screencast: 

https://user-images.githubusercontent.com/1197777/119937513-940e6080-bf93-11eb-8ea4-c95d8280e590.mp4

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run Happy path tests.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [x] other: CRW CCI

### Eclipse Che Logs
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/47/artifact/logs-and-configs/workspace-logs/

**Comment by dmytro-ndp** [comment]
Error has been reproduced again in che-theia PR check: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/156/artifact/che/tests/e2e/report/Validation_of_workspace_build_and_run_Build_application/screenshot-Build_application.png
