### ISSUE TITLE
Debug session failed to launch in workspace because of "No delegateCommandHandler for vscode java.startDebugSession" error

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#19880]
### Describe the bug
Happy path tests are failing because debug session can't start in Java Maven workspace: "**No delegateCommandHandler for vscode java.startDebugSession**" error:

![screenshot-Run_debug_and_check_application_stop_in_the_breakpoint (3)](https://user-images.githubusercontent.com/1197777/119823964-13515500-befe-11eb-8580-c1b87f749915.png)

Screencast: 
https://user-images.githubusercontent.com/1197777/119830373-dfc5f900-bf04-11eb-810a-2ef9afa8bd8d.mp4

Google console log
```
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'ms-vscode.js-debug' plugin contributes items to a menu with invalid identifier: debug/toolBar""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR [a93a34d3-6675-4b88-99e4-19ac8461ecff][ms-vscode.js-debug]: Failed to load 'views.jsBrowserBreakpoints' contribution." "TypeError: Cannot read property 'localeCompare' of undefined\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260054\n    at Array.sort (\u003Canonymous>)\n    at e.registerItem (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260015)\n    at e.registerView (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2381765)\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196281\n    at W (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3191924)\n    at r (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196231)\n    at oe (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196373)\n    at e.handleContributions (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196506)\n    at s (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2435075)""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.markdown-language-features' plugin contributes items to a menu with invalid identifier: editor/title/context""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscode.npm]: Failed to load 'views.npm' contribution." "TypeError: Cannot read property 'localeCompare' of undefined\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260054\n    at Array.sort (\u003Canonymous>)\n    at e.registerItem (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260015)\n    at e.registerView (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2381765)\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196281\n    at W (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3191924)\n    at r (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196231)\n    at oe (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196373)\n    at e.handleContributions (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196506)\n    at s (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2435075)""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: scm/sourceControl""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: scm/change/title""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: git.commit""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: git.changes""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: git.pullpush""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: git.branch""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: git.remotes""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscode.git' plugin contributes items to a menu with invalid identifier: git.stash""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR [a93a34d3-6675-4b88-99e4-19ac8461ecff][ms-vscode.references-view]: Failed to load 'viewContainers.references-view' contribution." "TypeError: Cannot read property 'localeCompare' of undefined\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260054\n    at Array.sort (\u003Canonymous>)\n    at e.registerItem (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260015)\n    at e.doRegisterViewContainer (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2380455)\n    at e.registerViewContainer (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2379565)\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3195916\n    at W (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3191924)\n    at r (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3195857)\n    at re (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196027)\n    at e.handleContributions (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196171)""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR [a93a34d3-6675-4b88-99e4-19ac8461ecff][ms-vscode.references-view]: Failed to load 'views.references-view.tree' contribution." "TypeError: Cannot read property 'localeCompare' of undefined\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260054\n    at Array.sort (\u003Canonymous>)\n    at e.registerItem (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260015)\n    at e.registerView (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2381765)\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196281\n    at W (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3191924)\n    at r (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196231)\n    at oe (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196373)\n    at e.handleContributions (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196506)\n    at s (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2435075)""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Preference name collision detected in the schema for property: [yaml]""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscjava.vscode-java-test]: Failed to load 'views.testExplorer' contribution." "TypeError: Cannot read property 'localeCompare' of undefined\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260054\n    at Array.sort (\u003Canonymous>)\n    at e.registerItem (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:260015)\n    at e.registerView (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2381765)\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196281\n    at W (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3191924)\n    at r (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196231)\n    at oe (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196373)\n    at e.handleContributions (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:3196506)\n    at s (https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:2435075)""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'vscjava.vscode-java-debug' plugin contributes items to a menu with invalid identifier: debug/toolBar""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'cpp' language is remapped from 'source.cpp.embedded.macro' to 'source.cpp' scope""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN a registered grammar configuration for 'cpp' language is overridden""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscode.html]: Language for 'source.smarty' not found.""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscode.markdown]: Language for 'meta.embedded.block.vs_net' not found.""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscode.markdown]: Language for 'meta.embedded.block.dosbatch' not found.""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscode.markdown]: Language for 'meta.embedded.block.coffee' not found.""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscode.markdown]: Language for 'meta.embedded.block.objc' not found.""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN [a93a34d3-6675-4b88-99e4-19ac8461ecff][vscode.markdown]: Language for 'meta.embedded.block.scala' not found.""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'php' language is remapped from 'source.php' to 'text.html.php' scope""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN a registered grammar configuration for 'php' language is overridden""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'yaml' language is remapped from 'source.yaml' to 'source.yaml' scope""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN a registered grammar configuration for 'yaml' language is overridden""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN 'java' language is remapped from 'source.java' to 'source.java' scope""
"WARNING" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root WARN a registered grammar configuration for 'java' language is overridden""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.""
"SEVERE" "" "https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.20.0/min/vs/editor/editor.main.js 30:600 Uncaught Error: There is no document for breakpointinput:vs.editor…@theia/plugin-ext/lib/plugin/languages.js:333:21)"
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms\n    at https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js:1:715830""
"SEVERE" "" "https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.20.0/min/vs/editor/editor.main.js 30:600 Uncaught Error: There is no document for breakpointinput:vs.editor…@theia/plugin-ext/lib/plugin/languages.js:333:21)"
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Notification handler 'connected' failed with message: Cannot read property 'apply' of undefined""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:2067405 Uncaught Error: No file system provider found for scheme https"
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "terminal ERROR Terminal error: command terminated with exit code 130""
"SEVERE" "" "https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.20.0/min/vs/editor/editor.main.js 30:600 Uncaught Error: There is no document for breakpointinput:vs.editor…@theia/plugin-ext/lib/plugin/languages.js:333:21)"
"SEVERE" "" "https://serverljv6xmfz-maven-container-server-8080.10.0.205.26.nip.io/oups - Failed to load resource: the server responded with a status of 500 ()"
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "terminal ERROR Terminal error: command terminated with exit code 130""
"SEVERE" "" "https://cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.20.0/min/vs/editor/editor.main.js 30:600 Uncaught Error: There is no document for breakpointinput:vs.editor…@theia/plugin-ext/lib/plugin/languages.js:333:21)"
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:4212411 "root ERROR Error starting the debug session" "Error: It is not possible to provide debug adapter executable.\n    at DebugExtImpl.\u003Canonymous> (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:723:39)\n    at step (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:33:23)\n    at Object.next (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:14:53)\n    at fulfilled (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)""
"SEVERE" "" "https://serveroughpe0j-jwtproxy-server-4402.10.0.205.26.nip.io/theia.b4a639ffda7450d06388.js 0:820794 Uncaught Error: It is not possible to provide debug adapter executable."
```

Workspace devfile: https://github.com/eclipse/che/blob/main/tests/e2e/files/happy-path/happy-path-workspace.yaml

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run Happy path E2E test.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [x] other: CRW Central CI

### Eclipse Che Logs
Workspace logs: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/40/artifact/logs-and-configs/workspace-logs/

### Additional context
https://github.com/microsoft/vscode-java-debug/issues/728#issuecomment-567757572

**Comment by dmytro-ndp** [comment]
There error has not been reproduced second time: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/43/consoleFull

**Comment by dmytro-ndp** [comment]
New occurrence of error: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/155/artifact/che/tests/e2e/report/Validation_of_debug_functionality_Run_debug_and_check_application_stop_in_the_breakpoint/

**Comment by vitaliy-guliy** [comment]
Have just checked it on local Che minikube deployment and on CRW.
Seems everything is working well

![Screenshot from 2021-07-30 11-26-01](https://user-images.githubusercontent.com/1655894/127633353-de3c7e20-fa89-45db-b854-e12df1fff52e.png)

![Screenshot from 2021-07-30 12-08-26](https://user-images.githubusercontent.com/1655894/127633361-f8c5a81c-1b96-47fa-a4ec-27a1e3feb789.png)

**Comment by svor** [comment]
I'm going to close this issue as we can not reproduce it. Please feel free to reopen if it happens again.

**Comment by dmytro-ndp** [comment]
It has been reproduced in Eclipse Che next: 
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-tests-pr-check/194/artifact/che/tests/e2e/report
![screenshot-Run_debug](https://user-images.githubusercontent.com/1197777/135636744-9081610b-aaae-4149-a06f-d57a85f7070b.png)
g
