### ISSUE TITLE
Sometimes the org.eclipse.che.api.project.server.Project Service Test fails during build of the CHE

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2006]
It happens rarely (in my case it has happened approximately just once out of 20 builds)

```
Tests run: 473, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 38.411 sec <<< FAILURE! - in TestSuite
testDeleteProjectsConcurrently(org.eclipse.che.api.project.server.ProjectServiceTest)  Time elapsed: 4.138 sec  <<< FAILURE!
java.lang.AssertionError: Error: Comparison method violates its general contract! expected [204] but found [500]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:494)
    at org.testng.Assert.assertEquals(Assert.java:123)
    at org.testng.Assert.assertEquals(Assert.java:370)
    at org.eclipse.che.api.project.server.ProjectServiceTest.testDeleteProjectsConcurrently(ProjectServiceTest.java:982)
```

**Expected behavior:** the test should pass always
**Observed behavior:** sometimes the test may fail

**Expected behavior:** after clicking on the fires item the Compare button should be enabked
**Observed behavior:** after clicking on the fires item the Compare button still disabled
**Che version:**    4.6.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Comment by dkulieshov** [comment]
Hi,

Seem like this output gives more info:

```
2016-07-28 11:26:26,023[FileTreeWatcher-0] [WARN ] [FileWatcherNotificationHandler 58]   - Error occurs while watching file events on /home/user/che/wsagent/che-core-api-project/target/fs: null
2016-07-28 11:26:27,213[main]             [INFO ] [.e.c.a.v.i.f.e.VfsEventService 62]   - Stopping virtual file system event service: LoEventService
2016-07-28 11:26:27,213[main]             [INFO ] [.e.c.a.v.i.f.e.VfsEventService 55]   - Starting virtual file system event service: LoEventService
2016-07-28 11:26:27,515[main]             [INFO ] [.e.c.a.v.i.f.e.VfsEventService 62]   - Stopping virtual file system event service: LoEventService
2016-07-28 11:26:27,572[main]             [ERROR] [o.e.c.a.p.s.ProjectManager 130]      - User limit of inotify instances reached or too many open files
2016-07-28 11:26:27,575[main]             [ERROR] [o.e.c.a.p.s.ProjectManager 130]      - User limit of inotify instances reached or too many open files
2016-07-28 11:26:27,576[main]             [ERROR] [o.e.c.a.p.s.ProjectManager 130]      - User limit of inotify instances reached or too many open files
2016-07-28 11:26:27,579[main]             [ERROR] [o.e.c.a.p.s.ProjectManager 130]      - User limit of inotify instances reached or too many open files
2016-07-28 11:26:27,580[main]             [ERROR] [o.e.c.a.p.s.ProjectManager 130]      - User limit of inotify instances reached or too many open files
2016-07-28 11:26:27,612[main]             [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-07-28 11:26:27,617[main]             [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-07-28 11:26:27,620[main]             [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-07-28 11:26:27,622[main]             [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-07-28 11:26:27,625[main]             [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-07-28 11:26:27,629[main]             [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
2016-07-28 11:26:27,632[main]             [INFO ] [o.e.c.a.core.util.FileCleaner 73]    - File cleaner is stopped
Tests run: 473, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 35.662 sec <<< FAILURE! - in TestSuite
testDeleteProjectsConcurrently(org.eclipse.che.api.project.server.ProjectServiceTest)  Time elapsed: 2.452 sec  <<< FAILURE!
java.lang.AssertionError: Error: Comparison method violates its general contract! expected [204] but found [500]
      at org.testng.Assert.fail(Assert.java:94)
      at org.testng.Assert.failNotEquals(Assert.java:494)
      at org.testng.Assert.assertEquals(Assert.java:123)
      at org.testng.Assert.assertEquals(Assert.java:370)
      at org.eclipse.che.api.project.server.ProjectServiceTest.testDeleteProjectsConcurrently(ProjectServiceTest.java:982)


Results :

Failed tests: 
ProjectServiceTest.testDeleteProjectsConcurrently:982 Error: Comparison method violates its general contract! expected [204] but found [500]

Tests run: 473, Failures: 1, Errors: 0, Skipped: 0
```

As I see `FileTreeWatcher` service drops down  because of 'User limit of inotify instances reached or too many open files' which I assume may lead to the following:
- `ProjectManager` becomes unstable -> `ProjectService` test fails with `500` response
- `FileTreeWatcher` service stops  -> file events are not caught until workspace restart (`FileTreeWatcher` restart)

**Comment by JamesDrummond** [comment]
@vparfonov @dkuleshov Please provide status label.
