### ISSUE TITLE
Plugins tests on the openshift-ci fail because of unable to get a token

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20117]
### Is your task related to a problem? Please describe.
Plugins tests on the openshift-ci fail because of unable to get a token

```
          ▼ PreferencesHandler.setConfirmExit to never

  Login test
          ▼ BrowserTabsUtil.navigateTo http://che-eclipse-che.apps.ci-op-yds1tf1h-d0452.origin-ci-int-aws.dev.rhcloud.com
Can not get bearer token. URL used: http://keycloak-eclipse-che.apps.ci-op-yds1tf1h-d0452.origin-ci-int-aws.dev.rhcloud.com/auth/realms/che/protocol/openid-connect/token
  [ERROR] PreferencesHandler.setPreferences failed to get user preferences
(node:200) UnhandledPromiseRejectionWarning: Error: Request failed with status code 405
    at createError (/tmp/e2e/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/tmp/e2e/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/tmp/e2e/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
          ▼ RegularUserOcpCheLoginPage.login
          ▼ OcpLoginPage.isIdentityProviderLinkVisible
          ▼ OcpLoginPage.clickOnLoginProviderTitle
          ▼ OcpLoginPage.waitOpenShiftLoginWelcomePage
          ▼ OcpLoginPage.enterUserNameOpenShift "user"
          ▼ OcpLoginPage.enterPasswordOpenShift "user"
          ▼ OcpLoginPage.clickOnLoginButton
          ▼ OcpLoginPage.waitDisappearanceOpenShiftLoginWelcomePage
          ▼ OcpLoginPage.isAuthorizeOpenShiftIdentityProviderPageVisible
          ▼ CheLoginPage.waitFirstBrokerLoginPage
          ▼ OcpLoginPage.isLinkAccountPageVisible
          ▼ TS_SELENIUM_LAUNCH_FULLSCREEN is set to true, maximizing window.
    ✓ Login (21551ms)

  The 'VscodeKubernetesPlugin' test
    Create workspace
          ▼ PreferencesHandler.setVscodeKubernetesPluginConfig
Can not get bearer token. URL used: http://keycloak-eclipse-che.apps.ci-op-yds1tf1h-d0452.origin-ci-int-aws.dev.rhcloud.com/auth/realms/che/protocol/openid-connect/token
  [ERROR] PreferencesHandler.setPreferences failed to get user preferences
      1) Set kubeconfig path
  [ERROR] CheReporter runner.on.fail: The 'VscodeKubernetesPlugin' test Create workspace Set kubeconfig path failed after 23ms


  1 passing (22s)
  1 failing

  1) The 'VscodeKubernetesPlugin' test
       Create workspace
         Set kubeconfig path:
     Error: Request failed with status code 405
      at createError (/tmp/e2e/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/tmp/e2e/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/tmp/e2e/node_modules/axios/lib/adapters/http.js:260:11)
      at IncomingMessage.emit (events.js:203:15)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Describe the solution you'd like

Investigate a reason and fix it.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse-che/che-plugin-registry/pull/998
