### ISSUE TITLE
Fail to start a workspace - method: GET, response code: 504, message: <html><body><h1>504 Gateway Time-out</h1>

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20110]
### Describe the bug
Some users are facing issues during a workspace startup on workspaces.openshift.com - ```Fail to start a workspace - method: GET, response code: 504, message: <html><body><h1>504 Gateway Time-out</h1>```

### Che version
7.30.2 / CRW 2.9

### Steps to reproduce

start a workspace on workspaces.openshift.com 

### Expected behavior
Workspace starts without any issues

### Runtime
   - workspaces.openshift.com

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/124938011-334d5b80-e008-11eb-8449-7747435c4c1a.png)

### Environment
OpenShift Dedicated 4.7.16

### Eclipse Che Logs
```
2021-07-08 13:15:34,018[aceSharedPool-9]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspacew8l4uv82crr92w3i.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Failed access: https://codeready-codeready-workspaces-operator.apps.sandbox-m2.ll9k.p1.openshiftapps.com/auth/realms/codeready/broker/openshift-v4/token?token, method: GET, response code: 504, message: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.personalizeConfig(IdentityProviderConfigFactory.java:211)
	at org.eclipse.che.workspace.infrastructure.openshift.multiuser.oauth.IdentityProviderConfigFactory.buildConfig(IdentityProviderConfigFactory.java:169)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.buildConfig(OpenShiftClientFactory.java:152)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftClientFactory.createOC(OpenShiftClientFactory.java:97)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.AbstractWorkspaceServiceAccount.prepare(AbstractWorkspaceServiceAccount.java:112)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProjectFactory.getOrCreate(OpenShiftProjectFactory.java:122)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProjectFactory.getOrCreate(OpenShiftProjectFactory.java:56)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:110)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:90)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.provisionWorkspace(KubernetesInternalRuntime.java:288)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:204)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:969)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by metlos** [comment]
This seems like a response coming from keycloak. I assume that Keycloak is configured with OpenShift OAuth and that Keycloak was unable to get a response from the OpenShift's OAuth endpoint in a timely manner. Would you be able to also attach the Keycloak logs?

**Comment by ibuziuk** [comment]
regardless of the root cause, why we are not doing the re-try?

**Comment by ibuziuk** [comment]
Closing. The issue was related to the networking issues on the infrastructure level
