### ISSUE TITLE
Creating Multiple workspaces in the same user account fails partially

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#20124]
## Summary
Creating multiple workspaces within a single user namespace fails partially.

## Relevant information

We have Eclipse Che deployed on IBM Kubernetes Service. We deployed eclipse che via Operatorhub. 

Che Version : 7.20.1
Deployment : Operator
Environment : IKS

We are using the concept of workspace pool. We have one account create 100 RUNNING workspaces, and as users login, we assign them one workspace from that pool. This avoids the creation of a  workspace at login time.  

Now while creating workspace in the pool, we see a lot of failures 
```
2021-07-12 14:22:20,494[ceSharedPool-21]  [WARN ] [.i.k.KubernetesInternalRuntime 255]  - Failed to start Kubernetes runtime of workspace workspacemu0459xdqarpb2ko.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Plugins installation process timed out
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.WaitBrokerResult.execute(WaitBrokerResult.java:75)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.DeployBroker.execute(DeployBroker.java:129)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.PrepareStorage.execute(PrepareStorage.java:76)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.brokerphases.ListenBrokerEvents.execute(ListenBrokerEvents.java:63)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.PluginBrokerManager.getTooling(PluginBrokerManager.java:129)
	at org.eclipse.che.workspace.infrastructure.kubernetes.wsplugins.SidecarToolingProvisioner.provision(SidecarToolingProvisioner.java:90)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.provisionWorkspace(KubernetesInternalRuntime.java:286)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:202)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:960)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)

```

If we trigger creation of 50 workspaces in one go, we see just 10 workspaces created and around 40 fail.  

Are there any settings to improve this performance of creating 100 workspaces in the same user account? 

We have the following custom properties set in checluster resource

 customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: "playground-dev-ws-<userid>"
      CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES: "ephemeral"
      CHE_WORKSPACE_STORAGE_PREFERRED__TYPE: "ephemeral"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "100"
      CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE: "1Gi"
      CHE_SYSTEM_SUPER__PRIVILEGED__MODE: "true"
      CHE_SYSTEM_ADMIN__NAME: "admin"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "0" #No Idle Timeout
      CHE_LIMITS_WORKSPACE_RUN_TIMEOUT: "0"  #No Run Timeout

**Comment by skabashnyuk** [comment]
Hello @pgirishibm can you please provide.
 -  enable debug mode on workspace startup and provide logs from failed workspace
 - full log from che-server
 - Events from k8s cluster. Especially failed.

>We are using the concept of workspace pool. We have one account create 100 RUNNING workspaces,

I would say that is antipattern of regular usage. Have you considered 1-3 workspaces per user? Why did you choose this way?

**Comment by pgirishibm** [comment]
> I would say that is antipattern of regular usage. Have you considered 1-3 workspaces per user? Why did you choose this way?

2 reasons for this
1.  We save the time for creating a new workspace when the user comes in for the first time.  Creating a workspace does take upto a  minute at times. 
2. Creating a workspace has an issue with the ingress reconnecting which ends up reloading all the workspaces for us.  https://github.com/eclipse/che/issues/19796

With the pool, we avoid the creation time and also avoid any new workspaces getting created. Inorder to refresh the workspace, we plan to do it during a maintenance period. 

I will get back with the logs very soon

**Comment by pgirishibm** [comment]
ah! by account i meant a single user.  Lets  say username pooladmin.  We have a component which creates workspaces in the pooladmin's  namespace. So a single user namespace would have 100 workspace pods created. and a workspace from that pooladmin namespace would be 'assigned' to any user who logs into eclipse che.

**Comment by skabashnyuk** [comment]
> So a single user namespace would have 100 workspace pods created. and a workspace from that pooladmin namespace would be 'assigned' to any user who logs into eclipse che.

Not sure you noticed that in the latest Che version all namespace strategies except "per-user" have been deprecated and removed. What is the reason for you not to use individual workspaces per user?

**Comment by pgirishibm** [comment]
> What is the reason for you not to use individual workspaces per user?

Because we need to  have a workspace ready in Running state before the user logs in. Without the pool, for a new user, we will have to create workspace  only during the first login  and the user will have to wait for the creation to complete before launching it.  We would like to improve on that new user experience.  Also as we mentioned earlier,  creation of a workspace is giving us a reloading issue  like the one mentioned in https://github.com/eclipse/che/issues/19796. so we have to have pre-created workspaces kept ready and no new workspaces getting created intermittently. 

Any better way you could suggest to handle this situation?

**Comment by skabashnyuk** [comment]
>Any better way you could suggest to handle this situation?

hard to say. If your users are not ok to have ~1minutes to start a workspace then most likely pool is a way to go. However, it would also mean that you building a completely different tool based on Eclipse Che. Especially in terms of authentication authorization.

**Comment by skabashnyuk** [comment]
@pgirishibm have you tried ```Gateway single-host on Kubernetes``` https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspace-exposure-strategies/#single-host-workspace-exposure-strategy_che  Using traefik as the main gateway might help in your case. WDYT?
