### ISSUE TITLE
Failed to start a workspace on OpenShift cluster

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#20122]
### Describe the bug

Failed to start a workspace on OpenShift cluster

### Che version

 - [x] nightly

### Steps to reproduce
1. Deploy Eclipse Che on openshift
2. Try to start a workspace

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots

N/A

### Installation method
   - [x] chectl

### Environment
   - [x] Cloud
       - [x] Amazon

### Eclipse Che Logs

```
org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Failure executing: POST at: https://172.30.0.1/apis/route.openshift.io/v1/namespaces/admin-che/routes. Message: Route.route.openshift.io "routek4kqa7yf" is invalid: spec.host: Invalid value: "route4wedm1.": host must conform to DNS 952 subdomain conventions. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.host, message=Invalid value: "route4wedm1.": host must conform to DNS 952 subdomain conventions, reason=FieldValueInvalid, additionalProperties={})], group=route.openshift.io, kind=Route, name=routek4kqa7yf, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Route.route.openshift.io "routek4kqa7yf" is invalid: spec.host: Invalid value: "route4wedm1.": host must conform to DNS 952 subdomain conventions, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftRoutes.create(OpenShiftRoutes.java:53)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInternalRuntime.createRoutes(OpenShiftInternalRuntime.java:166)
	at org.eclipse.che.workspace.infrastructure.openshift.OpenShiftInternalRuntime.startMachines(OpenShiftInternalRuntime.java:128)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:214)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:964)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/apis/route.openshift.io/v1/namespaces/admin-che/routes. Message: Route.route.openshift.io "routek4kqa7yf" is invalid: spec.host: Invalid value: "route4wedm1.": host must conform to DNS 952 subdomain conventions. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.host, message=Invalid value: "route4wedm1.": host must conform to DNS 952 subdomain conventions, reason=FieldValueInvalid, additionalProperties={})], group=route.openshift.io, kind=Route, name=routek4kqa7yf, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Route.route.openshift.io "routek4kqa7yf" is invalid: spec.host: Invalid value: "route4wedm1.": host must conform to DNS 952 subdomain conventions, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:639)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:578)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:543)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:504)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:292)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:893)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:372)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:86)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftRoutes.create(OpenShiftRoutes.java:51)
	... 12 common frames omitted
2021-07-12 13:19:47,747[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 990]   - Workspace '
```

**Comment by skabashnyuk** [comment]
Duplicate. Closing in favor of https://github.com/eclipse/che/issues/20072
