### ISSUE TITLE
In hosted-instance-log, "With stack trace: Error: Failed to show text document [object Object]" when starting workspace

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#20262]
### Describe the bug

When starting Java Maven workspace, there is this stack in hosted-instance-log:

```
Extension-Host:PLUGIN_HOST(44): PluginManagerExtImpl/loadPlugin(/default-theia-plugins/vscode-builtin-markdown-language-features/extension/dist/extension)
Extension-Host:Promise rejection not handled in one second: Error: Failed to show text document [object Object] , reason: Error: Failed to show text document [object Object]
Extension-Host:With stack trace: Error: Failed to show text document [object Object]
    at Object.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:300:43)
    at step (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:59:23)
    at Object.next (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:40:53)
    at fulfilled (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:31:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 ```

### Che version

7.32

### Steps to reproduce

1. create a "java Maven" workspace

### Expected behavior

no stacktrace

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by apupier** [comment]
exception at similar place than https://github.com/eclipse/che/issues/19485
