### ISSUE TITLE
The "VscodeValePlugin" unexpectedly fails on the openshift-ci

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20322]
### Is your task related to a problem? Please describe

The "VscodeValePlugin" unexpectedly fails on the openshift-ci
```    Check the "vale" plugin
          ▼ ProjectTree.expandPathAndOpenFile "che-docs/modules/administration-guide/partials" filename: assembly_authenticating-users.adoc
          ▼ ProjectTree.expandPath "che-docs/modules/administration-guide/partials"
          ▼ ProjectTree.expandItem "che-docs"
          ▼ ProjectTree.waitItemExpanded "che-docs"
          ▼ ProjectTree.expandItem "che-docs/modules"
          ▼ ProjectTree.waitItemExpanded "che-docs/modules"
          ▼ ProjectTree.expandItem "che-docs/modules/administration-guide"
          ▼ ProjectTree.waitItemExpanded "che-docs/modules/administration-guide"
          ▼ ProjectTree.expandItem "che-docs/modules/administration-guide/partials"
          ▼ ProjectTree.waitItemExpanded "che-docs/modules/administration-guide/partials"
The 'che-docs/modules/administration-guide/partials' item has not been expanded, try again
      1) Check warning in the editor appearance
  [ERROR] CheReporter runner.on.fail: The "VscodeValePlugin" userstory Check the "vale" plugin Check warning in the editor appearance failed after 34750ms


  4 passing (4m)
  1 failing

  1) The "VscodeValePlugin" userstory
       Check the "vale" plugin
         Check warning in the editor appearance:
     TimeoutError: Exceeded maximum gettin of the 'class' attribute attempts, from the 'By(css selector, div[data-node-id='/projects/che-docs:/projects/che-docs/modules/administration-guide/partials'])' element
      at DriverHelper.waitAndGetElementAttribute (/tmp/e2e/utils/DriverHelper.ts:345:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous>
      at Timeout.pollCondition [as _onTimeout] (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at ProjectTree.expandItem (/tmp/e2e/pageobjects/ide/ProjectTree.ts:147:45)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```

### Describe the solution you'd like

To find a reason and fix it

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/20358
