### ISSUE TITLE
The "GitHubPullRequestPlugin" unexpectedly fails on the openshift-ci

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20323]
### Is your task related to a problem? Please describe
The "GitHubPullRequestPlugin" unexpectedly fails on the openshift-ci

```
      ✓ Login to github (1461ms)
          ▼ GitOauthAppsSettings.openOauthApp
          ▼ GitOauthAppsSettings.clickOauthApp
      1) Open application settings
  [ERROR] CheReporter runner.on.fail: The 'GitHubPullRequestPlugin' test Setup github Open application settings failed after 20171ms


  2 passing (44s)
  1 failing

  1) The 'GitHubPullRequestPlugin' test
       Setup github
         Open application settings:
     TimeoutError: Exceeded maximum clicking attempts, the 'By(xpath, //div[@class='TableObject']//a[text()='eclipse-che'])' element is not clickable
      at DriverHelper.waitAndClick (/tmp/e2e/utils/DriverHelper.ts:301:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous>
      at pollCondition (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2191:7
      at new ManagedPromise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at ControlFlow.promise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2505:12)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2190:22
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at DriverHelper.waitUntilTrue (/tmp/e2e/utils/DriverHelper.ts:643:27)
      at GitOauthAppsSettings.openOauthApp (/tmp/e2e/pageobjects/third-parties/GitOauthAppsSettings.ts:57:33)
      at Context.test (/tmp/e2e/tests/plugins/GitHubPullRequestPlugin.spec.ts:61:40)
      at callFn (/tmp/e2e/node_modules/mocha/lib/runnable.js:395:21)
      at Test.Runnable.run (/tmp/e2e/node_modules/mocha/lib/runnable.js:382:7)
      at Runner.runTest (/tmp/e2e/node_modules/mocha/lib/runner.js:546:10)
      at /tmp/e2e/node_modules/mocha/lib/runner.js:672:12
      at next (/tmp/e2e/node_modules/mocha/lib/runner.js:455:14)
      at /tmp/e2e/node_modules/mocha/lib/runner.js:465:7
      at next (/tmp/e2e/node_modules/mocha/lib/runner.js:367:14)
      at Immediate.<anonymous> (/tmp/e2e/node_modules/mocha/lib/runner.js:433:5)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
```
### Describe the solution you'd like

To find a reason and fix it

**Comment by Ohrimenko1988** [comment]
Done: https://github.com/eclipse/che/pull/20434
