### ISSUE TITLE
The "VscodeKubernetesPlugin" unexpectedly fails on the openshift-ci

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20321]
### Is your task related to a problem? Please describe

The "VscodeKubernetesPlugin" unexpectedly fails on the openshift-ci

```
    Check the "Kubernetes" plugin
          ▼ KubernetesPlugin.openView
          ▼ LeftToolBar.selectView "Kubernetes"
          ▼ LeftToolBar.waitToolIcon "Kubernetes"
          ▼ LeftToolBar.isViewEnabled "Kubernetes"
          ▼ LeftToolBar.clickOnToolIcon "Kubernetes"
          ▼ LeftToolBar.waitViewSelected "Kubernetes"
      ✓ Check plugin is added to workspace (20110ms)
          ▼ KubernetesPlugin.waitListItemContains  /api-ocp46-crw-qe-com:6443/
      1) Check plugin basic functionality
  [ERROR] CheReporter runner.on.fail: The 'VscodeKubernetesPlugin' test Check the "Kubernetes" plugin Check plugin basic functionality failed after 241838ms


  5 passing (7m)
  1 failing

  1) The 'VscodeKubernetesPlugin' test
       Check the "Kubernetes" plugin
         Check plugin basic functionality:
     TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //div[@id='extension.vsKubernetesExplorer']//div[contains(text(), "/api-ocp46-crw-qe-com:6443/")])' element, timeouted after 240000
      at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:156:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```
### Describe the solution you'd like

To find a reason and fix it

**Comment by Ohrimenko1988** [comment]
Done: https://github.com/eclipse/che/pull/20344
