### ISSUE TITLE
Debug functionality doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#20332]
### Describe the bug

The debug session can not be started in NodeJS stack, probably the same problem exists for other stacks.

### Che version

7.34@latest

### Steps to reproduce

1. Create a workspace form NodeJS Express Web Application stack.
2. Run `download dependencies` command
3. Run `run the web app (debugging enabled)` command
4. Try to run debug configuration

### Expected behavior

Debug session successfully started

### Runtime

OpenShift

### Screenshots

![Screenshot from 2021-08-18 17-27-43](https://user-images.githubusercontent.com/1271546/129918207-da5793e7-f37f-41ea-871e-42cf4629db2d.png)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
Web browser logs:

VM223 theia.e83283efca1cd6bb5bb7.js:1 root ERROR Error starting the debug session TypeError: is_electron_1.default is not a function
    at Object.startDebugAdapter (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/plugin-debug-adapter-starter.js:44:48)
    at DebugExtImpl.<anonymous> (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:725:82)
    at step (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:33:23)
    at Object.next (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:14:53)
    at fulfilled (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
l.log @ VM223 theia.e83283efca1cd6bb5bb7.js:1
VM223 theia.e83283efca1cd6bb5bb7.js:1 Uncaught (in promise) TypeError: is_electron_1.default is not a function
    at Object.startDebugAdapter (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/plugin-debug-adapter-starter.js:44)
    at DebugExtImpl.<anonymous> (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:725)
    at step (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:33)
    at Object.next (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:14)
    at fulfilled (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:5)
    at processTicksAndRejections (/dashboard/internal/process/task_queues.js:97)
```

### Additional context

Related downstream tasks:
- https://issues.redhat.com/browse/CRW-2174
- https://issues.redhat.com/browse/CRW-1830

**Comment by svor** [comment]
works with che-theia:next

![Screenshot from 2021-08-18 17-50-07](https://user-images.githubusercontent.com/1271546/129920517-57e99470-a92c-4bf6-87d7-ae8073132963.png)
