### ISSUE TITLE
Che server throws NullPointerException if the user is kubeadmin

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20347]
### Describe the bug

When ~~deploying Che on OCP using update channel `stable-all-namespaces`~~ authenticating as kubeadmin on OCP the dashboard shows an error (c.f. screenshot) and the che-server log contains the following error:

```
[ERROR] [o.a.c.c.C.[.[.[/api].[default] 175]  - Servlet.service() for servlet [default] in context with path [/api] threw exception java.lang.NullPointerException: null
```

That's a known issue when Che uses Keycloak as identity provider but that's happening even when Che is configured with DevWorkspace enabled and Keycloak is not involved in authentication. 

### Che version

next (development version)

### Steps to reproduce

On a fresh OCP cluster (with only kubeadmin user) install Che operator and select the channel `stable-all-namespaces`. Then create a CheCluster custom resource using the default values.

### Expected behavior

I can access to Che user dashboard.

### Runtime

OpenShift

### Screenshots

<img width="807" alt="image" src="https://user-images.githubusercontent.com/606959/130524044-ece3ab6e-6380-4ba2-a663-a46de24136f1.png">

### Installation method

OperatorHub

### Environment

Amazon

### Eclipse Che Logs

```shell
2021-08-23 21:16:03,138[io-8080-exec-10]  [ERROR] [o.a.c.c.C.[.[.[/api].[default] 175]  - Servlet.service() for servlet [default] in context with path [/api] threw exception
java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.eclipse.che.multiuser.api.authentication.commons.SessionStore.getSession(SessionStore.java:36)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter$SessionCachedHttpRequest.getOrCreateSession(MultiUserEnvironmentInitializationFilter.java:100)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter$SessionCachedHttpRequest.getSession(MultiUserEnvironmentInitializationFilter.java:88)
	at org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:120)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1651)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by l0rd** [comment]
cc @flacatus

**Comment by sparkoo** [comment]
I can't reproduce. I was able to successfully login and start a workspace

![20210824_172907_673x426_scrot](https://user-images.githubusercontent.com/1160903/130647019-2f7f9dd5-44d1-4337-94c8-7038f6f2906e.png)

![20210824_173627_916x569_scrot](https://user-images.githubusercontent.com/1160903/130647045-f965d4ef-d349-4886-9a7f-8a786e46b0bc.png)

**Comment by l0rd** [comment]
I reproduce the error if I am logged in as kubeadmin. I think I was wrong assuming that it was related to the all-namespaces channel. 

The steps are:

- Open the openshift console and login as kubeadmin
- Go to the `installed operators -> eclipse che -> che cluster details` and click on the 'Eclipse Che URL'

There is no OpenShift login prompt (so I cannot login as `che` user) and I see the error above. This is a change with respect to when Che was configured to use Keycloak (the user was prompted to login again before accessing the dashboard).

These simple steps are the ones that users follow when trying Che for the first time on a fresh OpenShift cluster. It should work smoothly.

Summing this up:
- Since we got rid of Keycloak I am expecting that kubeadmin could be a valid Che user
- If using kubeadmin as valid Che user is still technically impossible we should at least provide a better message and ask the user to login as a valid OAuth user.

**Comment by sparkoo** [comment]
I'm testing on local CRC instance. When I click on Che link from openshift console, it shows openshift login prompt. I can login there as kubeadmin and it works as expected.


https://user-images.githubusercontent.com/1160903/130778602-e0b78fb7-5de2-4b88-965a-b6614055f62d.mp4

**Comment by tolusha** [comment]
@sparkoo 
`kubeadmin` is a valid user on CRC but not on OpenShift
