### ISSUE TITLE
che-theia git clone command with configured github oauth broken since 7.35.0

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#20356]
### Describe the bug

che-theia git clone command with configured github oauth broken since 7.35.0

### Che version

next (development version)

### Steps to reproduce

1. Configure github oauth using docs: https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/ .
2.  Login using github oauth.
3. Create new workspace. Wait when workspace is running.
4. In the che-theia editor: Ctrl/Cmd + shift + P, type `Git: clone`, press enter.

Actual result: che-theia do nothing.

### Expected behavior

Expected result: che-theia should show input field to get ssh/https link. User should paste copied own project ssh link, type Enter, che-theia should propose upload ssh key to github and clone this project without errors. For che-theia 7.34.0 this stuff works like expected.

### Runtime

OpenShift

### Installation method

chectl/latest, chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
Che-theia logs:

Extension-Host:Promise rejection not handled in one second: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'f'
    |     property '_onDidOpenRepository' -> object with constructor 'Emitter'
    |     property '_callbacks' -> object with constructor 'CallbackList'
    |     ...
    |     index 2 -> object with constructor 't.GitDecorations'
    --- property 'model' closes the circle , reason: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'f'
    |     property '_onDidOpenRepository' -> object with constructor 'Emitter'
    |     property '_callbacks' -> object with constructor 'CallbackList'
    |     ...
    |     index 2 -> object with constructor 't.GitDecorations'
    --- property 'model' closes the circle
Extension-Host:With stack trace: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'f'
    |     property '_onDidOpenRepository' -> object with constructor 'Emitter'
    |     property '_callbacks' -> object with constructor 'CallbackList'
    |     ...
    |     index 2 -> object with constructor 't.GitDecorations'
    --- property 'model' closes the circle
    at JSON.stringify (<anonymous>)
    at RPCProtocolImpl.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:299:152)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:194:36)
    at Proxy.target.<computed> (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:168:38)
    at QuickPickExt.QuickInputExt.dispatchUpdate (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:484:28)
    at QuickPickExt.QuickInputExt.update (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:473:18)
    at QuickPickExt.QuickInputExt.show (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:436:14)
    at QuickPickExt.show (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:787:31)
    at t (/default-theia-plugins/vscode-git/extension/dist/main.js:1:127183)
    at new Promise (<anonymous>)



In the logs(error parsing rpc object) /services websocket:

{
  "kind": "data",
  "id": 23,
  "content": "{\"jsonrpc\":\"2.0\",\"id\":309,\"method\":\"log\",\"params\":{\"data\":\"Extension-Host:With stack trace: TypeError: Converting circular structure to JSON\\n    --> starting at object with constructor 'f'\\n    |     property '_onDidOpenRepository' -> object with constructor 'Emitter'\\n    |     property '_callbacks' -> object with constructor 'CallbackList'\\n    |     ...\\n    |     index 2 -> object with constructor 't.GitDecorations'\\n    --- property 'model' closes the circle\\n    at JSON.stringify (<anonymous>)\\n    at RPCProtocolImpl.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:299:152)\\n    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:194:36)\\n    at Proxy.target.<computed> (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:168:38)\\n    at QuickPickExt.QuickInputExt.dispatchUpdate (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:484:28)\\n    at QuickPickExt.QuickInputExt.update (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:473:18)\\n    at QuickPickExt.QuickInputExt.show (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:436:14)\\n    at QuickPickExt.show (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/quick-open.js:787:31)\\n    at t (/default-theia-plugins/vscode-git/extension/dist/main.js:1:127183)\\n    at new Promise (<anonymous>)\",\"type\":1}}"
}
```

**Comment by disaster37** [comment]
Hi, the same behavior on 7.36.1 when set github-token-personal on user namespace.

**Comment by makambalaji** [comment]
Same issue is observed on 7.40.1

**Comment by azatsarynnyy** [comment]
@svor `Git: clone` is the Git Plug-in's command in Che-Theia, correct?

**Comment by svor** [comment]
> @svor `Git: clone` is the Git Plug-in's command in Che-Theia, correct?

@azatsarynnyy it comes for Git plugin. 
@vinokurig am I right that it should be fixed by https://github.com/eclipse/che/issues/20316?

**Comment by svor** [comment]
should be fixed now
