### ISSUE TITLE
 Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-keycloak:7.35.2".

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#20417]
### Describe the bug

deploy fails due to ImagePullBackOff

### Che version

other (please specify in additional context)

### Steps to reproduce

1. chectl server:deploy -a operator -p k8s --che-operator-cr-yaml='/home/charlesrod/Desktop/kube-files/che/che-cr.yaml' -b xxx.com

### Expected behavior

Successful deploy.

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
2021-09-05T07:10:03.285Z Cause: Error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-keycloak:7.35.2".
2021-09-05T07:10:03.285Z     at KubeTasks.<anonymous> (~/.local/share/chectl/client/7.35.2/lib/tasks/kube.js:69:39)
2021-09-05T07:10:03.285Z     at Generator.next (<anonymous>)
2021-09-05T07:10:03.285Z     at fulfilled (~/.local/share/chectl/client/7.35.2/node_modules/tslib/tslib.js:114:62)
2021-09-05T07:10:03.285Z     at runMicrotasks (<anonymous>)
```
```


### Additional context

Che not installed

k3s version v1.21.4+k3s1 (3e250fdb)

Keycloak logs: 

```
2021-09-05T07:10:03.285Z Cause: Error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-keycloak:7.35.2".
2021-09-05T07:10:03.285Z     at KubeTasks.<anonymous> (~/.local/share/chectl/client/7.35.2/lib/tasks/kube.js:69:39)
2021-09-05T07:10:03.285Z     at Generator.next (<anonymous>)
2021-09-05T07:10:03.285Z     at fulfilled (~/.local/share/chectl/client/7.35.2/node_modules/tslib/tslib.js:114:62)
2021-09-05T07:10:03.285Z     at runMicrotasks (<anonymous>)

```

**Comment by gnoejuan** [comment]
Lol, the keycloak container started while I was typing the issue.

Don't know if that's a desired functionality.

**Comment by tolusha** [comment]
Maybe it was some network issue.
Can we close it ?

**Comment by gnoejuan** [comment]
I believe we can, but chectl does give an error and ends. I `chectl server:delete -y` and redeploy and it worked.
