### ISSUE TITLE
Namespace strategies other than 'per user' is not supported anymore.

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#20415]
### Describe the bug

<details>
<summary>Che.yaml</summary>
<br>

```yaml
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: che
spec:
  auth:
    externalIdentityProvider: false
  database:
    externalDb: false
  server:
    selfSignedCert: false
    gitSelfSignedCert: false
    tlsSupport: true
    cheHost: xxx.com
    workspaceNamespaceDefault: <username>
  storage:
    pvcStrategy: 'unique'
    pvcClaimSize: '5Gi'
  k8s:
    ingressClass: traefik
    ingressDomain: xxx.com
  metrics:
    enable: false

```

</details>

After updating che.yaml with appropriate values, chectl still errors out.

### Che version

other (please specify in additional context)

### Steps to reproduce

1. Install with invalid che.yaml `chectl server:deploy -a operator -p k8s --che-operator-cr-yaml='/home/charlesrod/Desktop/kube-files/che/che-cr.yaml' -b xxx.com`
2. Update che.yaml
3. Attempt install again.

### Expected behavior

Chectl will install with new values. 

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
2021-09-05T06:28:23.166Z Error: Command server:deploy failed. Error log: /home/charlesrod/.cache/chectl/error.log.
2021-09-05T06:28:23.166Z     at newError (~/.local/share/chectl/client/7.35.2/lib/util.js:194:19)
2021-09-05T06:28:23.166Z     at Object.wrapCommandError (~/.local/share/chectl/client/7.35.2/lib/util.js:190:12)
2021-09-05T06:28:23.166Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.35.2/lib/commands/server/deploy.js:262:35)
2021-09-05T06:28:23.166Z     at Generator.throw (<anonymous>)
2021-09-05T06:28:23.166Z     at rejected (~/.local/share/chectl/client/7.35.2/node_modules/tslib/tslib.js:115:69)
2021-09-05T06:28:23.166Z Cause: Error: Eclipse Che operator failed, reason: InstallOrUpdateFailed, message: Namespace strategies other than 'per user' is not supported anymore. Using the <username> or <userid> placeholder is required in the 'spec.server.workspaceNamespaceDefault' field. The current value is: eclipse-che. Consider increasing error recheck timeout with --k8spoderrorrechecktimeout flag.
2021-09-05T06:28:23.166Z     at KubeTasks.<anonymous> (~/.local/share/chectl/client/7.35.2/lib/tasks/kube.js:35:35)
2021-09-05T06:28:23.166Z     at Generator.next (<anonymous>)
2021-09-05T06:28:23.166Z     at fulfilled (~/.local/share/chectl/client/7.35.2/node_modules/tslib/tslib.js:114:62)
```

### Additional context

chectl version
chectl/7.35.2 linux-x64 node-v12.22.6

Che not installed yet

k8s is running k3s

**Comment by gnoejuan** [comment]
This is fixed by running `chectl server:delete` before reattempting the deploy.
