### ISSUE TITLE
k3s: mkdir: cannot create directory '/var/lib/pgsql/data': Permission denied

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#20416]
### Describe the bug

`chectl server:deploy` fails when trying to start the postgresql container. 

### Che version

7.35@latest

### Steps to reproduce

1. Use k3s as base. 
2. `chectl server:deploy -a operator -p k8s --che-operator-cr-yaml='/home/charlesrod/Desktop/kube-files/che/che-cr.yaml' -b xxx.com`

### Expected behavior

To work

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

other (please specify in additional context)

### Eclipse Che Logs

```shell
2021-09-05T06:45:51.172Z Error: Command server:deploy failed. Error log: /home/charlesrod/.cache/chectl/error.log.
2021-09-05T06:45:51.172Z     at newError (~/.local/share/chectl/client/7.35.2/lib/util.js:194:19)
2021-09-05T06:45:51.172Z     at Object.wrapCommandError (~/.local/share/chectl/client/7.35.2/lib/util.js:190:12)
2021-09-05T06:45:51.172Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.35.2/lib/commands/server/deploy.js:262:35)
2021-09-05T06:45:51.172Z     at Generator.throw (<anonymous>)
2021-09-05T06:45:51.172Z     at rejected (~/.local/share/chectl/client/7.35.2/node_modules/tslib/tslib.js:115:69)
2021-09-05T06:45:51.172Z     at runMicrotasks (<anonymous>)
2021-09-05T06:45:51.172Z Cause: Error: Failed to start a pod, reason: Error, exitCode: 1
2021-09-05T06:45:51.172Z     at KubeTasks.<anonymous> (~/.local/share/chectl/client/7.35.2/lib/tasks/kube.js:110:35)
2021-09-05T06:45:51.172Z     at Generator.next (<anonymous>)
2021-09-05T06:45:51.172Z     at fulfilled (~/.local/share/chectl/client/7.35.2/node_modules/tslib/tslib.js:114:62)
2021-09-05T06:45:51.172Z     at runMicrotasks (<anonymous>)
```
```


### Additional context

k3s version v1.21.3+k3s1 (1d1f220f)

**Comment by gnoejuan** [comment]
https://githubmemory.com/repo/k3s-io/k3s/issues/3704

Looks like this can be fixed by either downgrading or, as of 17 days ago, upgrade k3s: https://github.com/k3s-io/k3s/releases/tag/v1.21.4%2Bk3s1 (via https://github.com/k3s-io/k3s/pull/3721 )
