### ISSUE TITLE
chectl prints error and workspace is not started on minikube v1.23

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#20431]
### Describe the bug

Eclipse Che is deployed successfully but chectl prints error at the end:
```
✖ Prepare post installation output
    → ERR_INGRESS_NO_EXIST - No ingress che,che-ingress in namespace eclipse-che
```

Eclipse Che is accessible, but workspace failed to start. See logs below.

### Che version

next (development version)

### Steps to reproduce

1.  deploy latest minikube 
```
sudo install minikube-linux-amd64 /usr/local/bin/minikube
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
```

2. deploy Eclipse Che
`chectl server:deploy --platform minikube`

### Expected behavior

Eclipse Che is deployed and workspace is started

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
2021-09-07 12:08:10,165[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspacefgk95bpruc369eq9.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Waiting for ingress 'ingresszb693vnd' reached timeout
    at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesIngresses.wait(KubernetesIngresses.java:129)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.createAndWaitReady(KubernetesInternalRuntime.java:938)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.createIngresses(KubernetesInternalRuntime.java:734)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.startMachines(KubernetesInternalRuntime.java:628)
    at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:214)
    at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:141)
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:964)
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
    at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.eclipse.che.commons.observability.CountedThreadFactory.lambda$newThread$0(CountedThreadFactory.java:75)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by tolusha** [comment]
Fixed by https://github.com/che-incubator/chectl/pull/1632
Besides this minikube v1.23 has issue with ngnix. Workaround before deploying Eclipse Che:

```bash
kubectl patch role/ingress-nginx  --type='json' -p='[{ "op": "add", "path": "/rules/-", "value": {"apiGroups":[""], "resourceNames":["ingress-controller-leader"], "resources":["configmaps"], "verbs":["get", "update"]} }]' -n ingress-nginx
kubectl rollout restart deployment/ingress-nginx-controller -n ingress-nginx
```
