### ISSUE TITLE
The "VscodeYamlPlugin" fails on the openshift CI nightly job

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20441]
### Is your task related to a problem? Please describe

The "VscodeYamlPlugin" fails on the openshift CI nightly job

Link to the job: https://prow.ci.openshift.org/?job=periodic-ci-eclipse-che-che-plugin-registry-main-v7-plugins-test-nightly

```
      1) Check autocomplete
  [ERROR] CheReporter runner.on.fail: The "VscodeYamlPlugin" userstory Check the "vscode-yaml" plugin Check autocomplete failed after 65869ms


  5 passing (4m)
  1 failing

  1) The "VscodeYamlPlugin" userstory
       Check the "vscode-yaml" plugin
         Check autocomplete:
     TimeoutError: Wait timed out after 65043ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: <anonymous wait>
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at Editor.waitSuggestionWithResettingCursor (/tmp/e2e/pageobjects/ide/Editor.ts:532:45)
      at Editor.waitSuggestion (/tmp/e2e/pageobjects/ide/Editor.ts:54:24)
      at Context.test (/tmp/e2e/tests/plugins/VscodeYamlPlugin.spec.ts:72:26)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```

### Describe the solution you'd like

We need to investigate a reason and fix it.

**Comment by Ohrimenko1988** [comment]
Done: https://github.com/eclipse/che/pull/20453

**Comment by Ohrimenko1988** [comment]
Done: https://github.com/eclipse/che/pull/20511
