### ISSUE TITLE
unzip:  cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP.

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2081]
Host is Ubuntu 16.04.  
Here's my docker run command:

> sudo mkdir -p /srv/che/jcarter/{lib, workspaces, storage}
> sudo chmod -R 777 /srv/che/jcarter
> 
> sudo docker run 
>    --net=host \
>    --restart always \
>    --name che \
>    --detach \
>    -v /var/run/docker.sock:/var/run/docker.sock:Z \
>    -v /srv/che/jcarter/lib:/home/user/che/lib-copy:Z \
>    -v /srv/che/jcarter/workspaces:/home/user/che/workspaces:Z \
>    -v /srv/che/jcarter/storage:/home/user/che/storage:Z \
>    codenvy/che

I get this error message when trying to launch a workspace: "unzip: cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP. ".  

Any ideas what's going on?

**Comment by TylerJewell** [comment]
Yes, the volume mount for the `lib-copy` was not typed properly.  You cannot use your own host for that - it has to be `/home/user/che/lib:/home/user/che/lib-copy`.  

We have a simpler way for starting the che-server coming in 4.6.  We have a hidden page to give it a go.  Can you try this syntax instead?

https://eclipse-che.readme.io/docs/usage-docker

**Comment by linuxd3v** [comment]
@TylerJewell 

Thanks. So you're saying that I cannot use `/srv/che/jcarter/{lib, workspaces, storage}` directories?  
And che will store all the containers and projects data in `/home/user/che` on my host?
Is there a way to avoid this? Im running bunch of dockers and my goal is keeping all the data for them in central location, ex: `/srv`

**Comment by TylerJewell** [comment]
No - I was just commenting on the `lib-copy` volume mount.  That one is for che's internal use.  The others can be mounted to other locations.

The new syntax that I showed you is preferred - as it handles the volume mounts and storage of all your configuration & workspace stuff through environment variables.  Much simpler to maintain.

**Comment by linuxd3v** [comment]
oki - got it to work doing something like this:

docker run \
    --rm -t \
    --name che-launcher-jc \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e CHE_PORT=3005 \
    -e CHE_CONF_FOLDER:/srv/che/jcarter \
    codenvy/che-launcher:nightly start

Thx

**Comment by linuxd3v** [comment]
Btw -> this project is just amazing.

**Comment by TylerJewell** [comment]
You may also want to add in CHE_DATA_FOLDER so that stuff that you care about inside of the Che container is saved to outside of it.  

Thanks for the compliments!  What are you going to use Che for?

**Comment by linuxd3v** [comment]
@TylerJewell So far I've just been researching for cloud IDEs our team could use so we could use remotely. Also I'm sick and tired of explaining team member how to install and configure things. lol  
We went from FTP'ing code to dev server, to vagrant to docker on each devs machine.  

But every one of them seems to have some issues. Like vagrant symlinks working on linux hosts and not windows hosts, files not syncing etc. Docker seemed  to be the best -> but has issues on windows & OSx hosts, and also remote work was challenging as we have tons of data that hard to mockup.  

Cloud IDE seems like the best solution.

**Comment by TylerJewell** [comment]
@loganto - we had a booth at Docker Con earlier this year, and we didn't know how people would react to us. We were overwhelmed with the number of opportunities that we developed. People told us that while Vagrant / Docker are good utilities for dev teams, there is a lot of inconsistency in how those utilities are launched by devs.  And that what Che is really doing for teams is providing a structured approach to getting the environment set up without the end user developer needing know many of the semantics underneath.

We'll be shipping docker compose support inside the workspace definition a bit later this quarter.  Also, multi-pane editor and tabbed console almost done. We'll also be working to make it possible so that we inject our agents into any dockerfile vs. what you have to do now which is add our agent stuff into the dockerfile.  So should be super smooth experience.

Also - we have a che up utility coming - like Vagrantfiles for Che.  Git clone a repo, "che up" it, and then we'll boot the Che server in the background and load the directory into Che as a custom workspace.

**Comment by sqs** [comment]
I am experiencing this issue when creating a workspace using the blank stack.

Logs are:

```

[default] [DOCKER] latest: Pulling from codenvy/ubuntu_jdk8 
[default] [DOCKER] Digest: sha256:a35671a53b6c1e722b5f681950f945da37179c5396bf67ee8f1bc49c6dffc543 
[default] [DOCKER] Status: Image is up to date for codenvy/ubuntu_jdk8:latest 
[default] [DOCKER] Step 1 : FROM codenvy/ubuntu_jdk8
[default] [DOCKER] ---> e9ebc40e9430
[STDERR] unzip:  cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP.
```

Other logs:

```
$ docker logs -f che-server

############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
#############################################################

2016-11-06 13:51:06,831[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32
2016-11-06 13:51:06,832[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC
2016-11-06 13:51:06,832[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0
2016-11-06 13:51:06,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2016-11-06 13:51:06,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.4.0-36-generic
2016-11-06 13:51:06,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2016-11-06 13:51:06,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
2016-11-06 13:51:06,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_92-internal-alpine-r1-b14
2016-11-06 13:51:06,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2016-11-06 13:51:06,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/tomcat
2016-11-06 13:51:06,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/tomcat
2016-11-06 13:51:06,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/tomcat/conf/logging.properties
2016-11-06 13:51:06,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2016-11-06 13:51:06,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
2016-11-06 13:51:06,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
2016-11-06 13:51:06,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
2016-11-06 13:51:06,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2016-11-06 13:51:06,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/user/che
2016-11-06 13:51:06,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/tomcat/logs/
2016-11-06 13:51:06,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2016-11-06 13:51:06,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2016-11-06 13:51:06,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2016-11-06 13:51:06,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2016-11-06 13:51:06,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/home/user/che/conf/
2016-11-06 13:51:06,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/tomcat/endorsed
2016-11-06 13:51:06,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/tomcat
2016-11-06 13:51:06,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/tomcat
2016-11-06 13:51:06,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/tomcat/temp
2016-11-06 13:51:06,905[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-8080"]
2016-11-06 13:51:06,914[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2016-11-06 13:51:06,916[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 281 ms
2016-11-06 13:51:06,954[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
2016-11-06 13:51:06,955[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
2016-11-06 13:51:06,955[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32
2016-11-06 13:51:07,003[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/ROOT.war
2016-11-06 13:51:07,780[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/ROOT.war has finished in 776 ms
2016-11-06 13:51:07,780[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/dashboard.war
2016-11-06 13:51:07,899[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/dashboard.war has finished in 119 ms
2016-11-06 13:51:07,899[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/swagger.war
2016-11-06 13:51:07,952[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/swagger.war has finished in 53 ms
2016-11-06 13:51:07,953[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/wsmaster.war
2016-11-06 13:51:09,445[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
2016-11-06 13:51:10,312[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/wsmaster.war has finished in 2,359 ms
2016-11-06 13:51:10,314[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-8080"]
2016-11-06 13:51:10,318[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 3401 ms
2016-11-06 13:51:31,571[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 820]    - Workspace 'che:wksp-gnyx' with id 'workspacei8jdjni9ydii8lzh' created by user 'che'
2016-11-06 13:51:34,339[kspaceManager-0]  [INFO ] [c.p.d.m.DockerInstanceProvider 591]  - Machine with id 'machine7cwi4o48agw8a5jv' backed by container '5d3adfe8aa1a277a8f003bea886abd09741eb10003d1571a571aad53dd8b2618' has been deployed on node 'localhost'
2016-11-06 13:52:34,380[kspaceManager-0]  [ERROR] [.c.a.a.s.w.WsAgentLauncherImpl 115]  - Fail pinging ws agent. Workspace ID:workspacei8jdjni9ydii8lzh. Url:http://localhost:32794/wsagent/ext/. Timestamp:{}
2016-11-06 13:52:34,688[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 666]    - Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:261) ~[che-core-api-workspace-4.7.2.jar:4.7.2]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:650) ~[che-core-api-workspace-4.7.2.jar:4.7.2]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.7.2.jar:4.7.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92-internal]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92-internal]
```

```
$ CHE_USER=1000 che start
WARNING: No swap limit support
INFO: ECLIPSE CHE: Found image codenvy/che-server:latest
INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 4.7.2
INFO: ECLIPSE CHE: Use: http://172.17.0.1:8080
INFO: ECLIPSE CHE: API: http://172.17.0.1:8080/swagger
```

Strangely, on my host FS, there is a directory (not file) named `/home/user/che/lib/ws-agent.zip`:

```
$ tree -p /home/user/che
/home/user/che
├── [drwxr-xr-x]  lib
│   ├── [drwxr-xr-x]  linux_amd64
│   │   └── [drwxr-xr-x]  terminal
│   └── [drwxr-xr-x]  ws-agent.zip
└── [drwxr-xr-x]  workspaces
    ├── [drwxr-xr-x]  default123
```

I would expect this `ws-agent.zip` file to be a file, not a directory.

If I remove the `ws-agent.zip` dir and retry creating the new workspace, it recreates that dir and fails with the same error.

**Comment by TylerJewell** [comment]
@sqs issue was due to a mismatch of the che-launcher and che-server. We got it fixed up offline, but his solution was different than the ones previously discussed above.
