### ISSUE TITLE
Compiling Che fails

### ISSUE THREAD

**Issue by gustaveherbst** [eclipse-che/che#2093]
I have attempted to compile Che multiple times but still get the same failure. I have tried to insure all dependencies have been met.

> mvn -DskipTests clean install

Results:

[INFO] Che Dashboard :: Web App ........................... FAILURE [02:35 min]
[INFO] Che IDE :: Parent .................................. SKIPPED
[INFO] Che Workspace Agent War Packaging .................. SKIPPED
[INFO] Che Assembly Workspace Agent Server ................ SKIPPED
[INFO] Che IDE :: Compiling GWT Application ............... SKIPPED
[INFO] Che IDE :: Compiling WS Master WAR ................. SKIPPED
[INFO] Che IDE :: Assemblies Tomcat ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42:51 min
[INFO] Finished at: 2016-08-10T19:55:23+00:00
[INFO] Final Memory: 542M/1724M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (compile) on project che-dashboard-war: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec failonerror="true" dir="/root/Development/che/dashboard" executable="bower">... @ 7:85 in /root/Development/che/dashboard/target/antrun/build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (compile) on project che-dashboard-war: An Ant BuildException has occured: exec returned: 1
around Ant part ...<exec failonerror="true" dir="/root/Development/che/dashboard" executable="bower">... @ 7:85 in /root/Development/che/dashboard/target/antrun/build-main.xml
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: exec returned: 1
around Ant part ...<exec failonerror="true" dir="/root/Development/che/dashboard" executable="bower">... @ 7:85 in /root/Development/che/dashboard/target/antrun/build-main.xml
    at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:342)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: /root/Development/che/dashboard/target/antrun/build-main.xml:7: exec returned: 1
    at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:643)
    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
    at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:313)
    ... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :che-dashboard-war

Can anyone point me in the right direction to resolve this. Thanks

**Comment by TylerJewell** [comment]
Sorry you ran into that issue.  The dashboard sub-module requires some extra utilities to be installed.  I wonder if this issue is because they are missing.  

The specifics of what are needed are here:
https://github.com/eclipse/che/tree/master/dashboard

You can optionally skip building the dashboard:

```
cd assembly
cd assembly-main
mvn clean install 
# This will pull all of the other modules from our nexus
```

You can optionally use our Docker container which has the software inside of it to compile code locally on your host:
https://github.com/eclipse/che/wiki/Development-Workflow#build-che-using-docker

Could you please point out the documentation that you were looking at?  I'd like to double check that we are providing clear guidance so others do not run into this issue.

**Comment by gustaveherbst** [comment]
Tyler thanks for replying. I have tried the docker container which is referenced above for building. However, that fails to build for some reason.

I can get it to build if I simply

cd che/assembly
mvn clean install

My question is, if I mvn clean install at the root
1. git clone
2. cd che
3. mvn clean install

This builds but fails at the Dashboard. I did follow the instructions for the dashboard referenced at : https://github.com/eclipse/che/tree/master/dashboard

This references user-dashboard but I assume it refers to "dashboad" directory. I follow the steps and gulp serve performs the tests just fine.

My question is, after this what steps should be followed? Should performing the build at the root (che) not work? By default I was thinking it should build everything needed which it seems to do until it gets to dashboard.

I will try to dig in to this more but I cannot find any recourse to resolve the error. I have installed gulp, bower, and follow the install. I have started with a clean VPS with 4G ram, both under Ubuntu 16

Thanks in advance

**Comment by DarkBlaez** [comment]
If I cd to dashboard per individual sub-module build this is the error that comes back

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.6.1:clean (default-clean) on project che-dashboard-war: Failed to clean project: Failed to delete /che/dashboard/bower_components/angular-material/angular-material-mocks.js -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.6.1:clean (default-clean) on project che-dashboard-war: Failed to clean project: Failed to delete /home/gary/Development/Codenvy/che/dashboard/bower_components/angular-material/angular-material-mocks.js
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to clean project: Failed to delete /home/gary/Development/Codenvy/che/dashboard/bower_components/angular-material/angular-material-mocks.js
	at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:202)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.io.IOException: Failed to delete /home/gary/Development/Codenvy/che/dashboard/bower_components/angular-material/angular-material-mocks.js
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:251)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:193)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:160)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:160)
	at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:118)
	at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:195)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[

**Comment by TylerJewell** [comment]
@ddementieva @benoitf @ashumilova - please check this thread.  It seems that our instructions for compiling the /dashboard module on GitHub are not complete.  Please provide some step by step instructions of what must be installed so that mvn clean install can be done in the /dashboard module.

@DarkBlaez - you should check out the docker container we have that will build it for you.  It will work in the mean time, and the dockerfile contains everything that we install to complete a build. So there is something in that container that you need to install that we must be missing in our docs.

https://github.com/eclipse/che/blob/master/dockerfiles/che-dev/Dockerfile

**Comment by gustaveherbst** [comment]
I will try and re-rerun the docoker file for building. The instructions around the use of the docker container for building should be clarified further. I assume that it gets run from the root of the source core to map it in with "$PWD" but that the volume can be changed to anywhere the source is being stored?

**Comment by TylerJewell** [comment]
For mac & linux - $PWD would be the root of the source tree, or the module you want to compile. So - essentially it is picking up the context of your location.

For windows - replace the $HOME and $PWD values:

```
# For Mac + Linux:
docker run -it --rm --name build-che 
           -v "$HOME/.m2:/home/user/.m2" 
           -v "$PWD":/home/user/che-build 
           -w /home/user/che-build 
           codenvy/che-dev 
           mvn -DskipTests=true 
               -Dfindbugs.skip=true
               -Dgwt.compiler.localWorkers=2 -T 1C 
               -Dskip-validate-sources 
               clean install

# For Windows, replace $HOME with maven repo directory.
# For Windows, replace $PWD with Che source code directory.
```

**Comment by gustaveherbst** [comment]
Tyler thanks for the assistance and direction. I was able to get the docker based build to work without issue. Greatly appreciate it.
