### ISSUE TITLE
Issue with Git Committing in 4.5.1

### ISSUE THREAD

**Issue by cstack89** [eclipse-che/che#2101]
A few days ago I ported an existing instance of Che to 4.5.1. It worked initially, but today when I booted up it downloaded a new docker container even though there was a snapshot. Now it's telling me I can't commit because my name and email are not set in the preferences area. I am able to start up the workspace and run other commands, but Git no longer works.  This is the error that shows up:

`2016-08-11 15:29:40,237[nio-4401-exec-9]  [ERROR] [o.e.c.a.g.LocalGitUserResolver 54]   - Failed access: http://che-host:9090/wsmaster/api/preferences?token, method: GET, response code: 404, message: There is no any resources matched to request path /preferences
org.eclipse.che.api.core.ServerException: Failed access: http://che-host:9090/wsmaster/api/preferences?token, method: GET, response code: 404, message: There is no any resources matched to request path /preferences
    at org.eclipse.che.RemotePreferenceDao.getPreferences(RemotePreferenceDao.java:88) ~[wsagent-local-4.5.1.jar:4.5.1]
    at org.eclipse.che.api.git.LocalGitUserResolver.getUser(LocalGitUserResolver.java:49) ~[che-core-api-git-4.5.1.jar:4.5.1]
    at org.eclipse.che.git.impl.jgit.JGitConnection.getUser(JGitConnection.java:1653) [che-core-git-impl-jgit-4.5.1.jar:4.5.1]
    at org.eclipse.che.git.impl.jgit.JGitConnection.commit(JGitConnection.java:528) [che-core-git-impl-jgit-4.5.1.jar:4.5.1]
    at org.eclipse.che.api.git.GitService.commit(GitService.java:177) [che-core-api-git-4.5.1.jar:4.5.1]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:154) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:141) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:289) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:280) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:205) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:95) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:64) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:134) [everrest-core-1.12.3.jar:na]
    at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:63) [everrest-core-1.12.3.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
    at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
    at org.eclipse.che.filters.AbstractEnvironmentInitializationFilter.doFilter(AbstractEnvironmentInitializationFilter.java:55) [wsagent-local-4.5.1.jar:4.5.1]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
    at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:301) [catalina.jar:8.0.32]
    at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169) [catalina.jar:8.0.32]
    at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59) [che-core-api-core-4.5.1.jar:4.5.1]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.32]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.32]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.32]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.32]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.32]
    at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.32]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [catalina.jar:8.0.32]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-coyote.jar:8.0.32]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-coyote.jar:8.0.32]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.32]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.32]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.32]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.io.IOException: Failed access: http://che-host:9090/wsmaster/api/preferences?token, method: GET, response code: 404, message: There is no any resources matched to request path /preferences
    at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:276) ~[che-core-api-core-4.5.1.jar:4.5.1]
    at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:155) ~[che-core-api-core-4.5.1.jar:4.5.1]
    at org.eclipse.che.RemotePreferenceDao.getPreferences(RemotePreferenceDao.java:85) ~[wsagent-local-4.5.1.jar:4.5.1]
    ... 48 common frames omitted`

I'm not sure if it's related, but after upgrading to 4.5.1 I can no longer access my workspace terminal from the command line either.  Here is the error from that:`WebSocket connection to 'ws://192.168.99.6:32778/pty' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Che version:**   4.5.1
**OS and version:**Centos 7 
**Docker version:** 1.12
**Che install:**    Server (zip) local  

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@cstack89 - hello chris. Thanks for reporting this issue.  This may have to do with the sequence of upgrading and the drag along of the underlying model.  Do you have the ability to a) down grade your docker image to the older version that was previously there, b) commit your source code / export ws if necessary, c) then upgrade to latest version followed by ws import and / or setting up a new workspace that imports your git code?

**Comment by cstack89** [comment]
I was able to use my old Che 4.4 server to commit the code. It's still not working properly either though, I was relying on the snapshot because I installed some other software which I know is bad practice. So I will work on creating my own container and stack. Not really sure why Git broke still though.

**Comment by ghost** [comment]
@cstack89 can you elaborate in `ported an existing instance of Che to 4.5.1.` please?

Have you tried to update username and email in Prefs?

**Comment by TylerJewell** [comment]
@cstack89 - can you please update the issue?  FYI, we are making the 4.7 release Monday - there are a number of git improvements in there.

**Comment by cstack89** [comment]
Really sorry for the delay, I've been out of the office a lot. 

My "Upgrade" was to download and unzip 4.5.1. I then copied my workspaces, and the storage files over to 4.5.1.

I had tried updating my username and email in Prefs. The correct values were there and if you don't change them you can't press save. So I'm thinking the workspace was looking at one file and the server was looking at another maybe?

I'm assuming the correct path for upgrade is to download the new version, export workspaces form the old one and import to the new one. Then download all projects from Git. I was just trying to get around this since I had installed mysql into my workspace.

**Comment by ghost** [comment]
@cstack89 the server cannot access your user prefs.  Can you give it a try with 4.6.2?

Your projects are in `/workspaces` and workspaces with user prefs are in `/storage`. You need to copy those to a new installation.

**Comment by cstack89** [comment]
@eivantsov I copied everything in /storage and /workspaces or at least I think I did. Unfortunately at this point it's been a while and the details are slipping. After the issues I went back to using 4.4 without my modified container so I'm not sure I can recreate the issue.

It seems like the method for launching Che has changed a lot as of 4.6 so I have not had time to dive in there yet.

**Comment by JamesDrummond** [comment]
@cstack89 Please let us know if there is anything we can do to resolve this issue. Many things have changed(for the better) with che 4.6 and now 4.7. You can always close this issue and reopen it when you have had time to test with the newer versions.

**Comment by cstack89** [comment]
I think it's best that I go ahead and do that. No time recently to experiment. Looking forward to checking out the new versions.
