### ISSUE TITLE
Cannot install eclipse-che with chectl next on OpenShift

### ISSUE THREAD

**Issue by dkwon17** [eclipse-che/che#21461]
### Describe the bug

I was trying to deploy eclipse che with chectl using the next channel.
Chectl was installed using `bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next`.

The command used to deploy eclipse che was:
```
chectl server:deploy -p openshift --che-operator-image=<my-che-operator-image>
```

After about of couple of minutes, I get this error message:
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/83611742/173451328-4ad501ca-c934-463b-bc7c-7a3bd8ae191f.png">

Here are error logs from `/Users/dakwon/Library/Caches/chectl/error.log`:
https://gist.githubusercontent.com/dkwon17/142ca33a5ab883b0e46ef34b176eec02/raw/b41a9da143bd265ce37f547d397968029ac98fab/chectl-error-log

### Che version

next (development version)

### Steps to reproduce

1. With an OpenShift cluster running, run:
```
chectl server:deploy -p openshift --che-operator-image=<my-che-operator-image>
```

### Expected behavior

`chectl server:deploy` should complete without errors.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS

### Additional context

Running `chectl server:delete -y` afterwards results in:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/83611742/173452289-56ab8f86-c18b-46a3-8af7-6defa71e92e6.png">

With these logs:
```
2022-06-13T21:57:24.474Z Error: Command server:delete failed. Error log: /Users/dakwon/Library/Caches/chectl/error.log. Eclipse Che logs: /var/folders/_4/9g51bpqn29vg6098lqhl07_40000gn/T/chectl-logs/1655157439181.
2022-06-13T21:57:24.474Z     at newError (~/chectl/lib/util.js:199:19)
2022-06-13T21:57:24.474Z     at Object.wrapCommandError (~/chectl/lib/util.js:195:12)
2022-06-13T21:57:24.474Z     at Delete.<anonymous> (~/chectl/lib/commands/server/delete.js:99:39)
2022-06-13T21:57:24.474Z     at Generator.throw (<anonymous>)
2022-06-13T21:57:24.474Z     at rejected (~/chectl/node_modules/tslib/tslib.js:115:69)
2022-06-13T21:57:24.474Z Cause: Error: Required parameter namespace was null or undefined when calling listNamespacedPod.
2022-06-13T21:57:24.474Z     at CoreV1Api.<anonymous> (~/chectl/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:9968:23)
2022-06-13T21:57:24.474Z     at Generator.next (<anonymous>)
2022-06-13T21:57:24.474Z     at ~/chectl/node_modules/@kubernetes/client-node/node_modules/tslib/tslib.js:115:75
2022-06-13T21:57:24.474Z     at new Promise (<anonymous>)
2022-06-13T21:57:24.474Z     at Object.__awaiter (~/chectl/node_modules/@kubernetes/client-node/node_modules/tslib/tslib.js:111:16)
2022-06-13T21:57:24.474Z     at CoreV1Api.listNamespacedPod (~/chectl/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:9952:24)
2022-06-13T21:57:24.474Z     at KubeHelper.<anonymous> (~/chectl/lib/api/kube.js:2162:42)
2022-06-13T21:57:24.474Z     at Generator.next (<anonymous>)
2022-06-13T21:57:24.474Z     at ~/chectl/node_modules/tslib/tslib.js:117:75
2022-06-13T21:57:24.474Z     at new Promise (<anonymous>)
```

**Comment by tolusha** [comment]
@dkwon17 
I fixed it yesterday. Pls, update chectl and try again.
https://github.com/che-incubator/chectl/pull/2144

**Comment by dkwon17** [comment]
@tolusha I see, thank you, I think there was an issue with my machine yesterday. I uninstalled chectl and installed it again, and it is working now
