### ISSUE TITLE
Error of automatic update of IM CLI: 'Could not generate DH keypair'

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#2195]
Updating version: 4.6.0-SNAPSHOT
Version of update: 4.7.0-SNAPSHOT

Error log:

```
2016-08-22 15:37:47,648 +0000 [ERROR] com.codenvy.im.cli.command.AbstractIMCommand.updateImCliClientIfNeeded(AbstractIMCommand.java:147) Fail of automatic update of IM CLI client. Error: java.lang.RuntimeException: Could not generate DH keypair
2016-08-22 15:37:47,741 +0000 [ERROR] com.codenvy.im.console.Console.printErrorAndExit(Console.java:163) java.lang.RuntimeException: Could not generate DH keypair
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1894)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1877)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1398)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)[:1.8.0_45]
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)[:1.8.0_45]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)[:1.8.0_45]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)[:1.8.0_45]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)[:1.8.0_45]
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)[:1.8.0_45]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)[:1.8.0_45]
    at com.codenvy.im.utils.HttpTransport.request(HttpTransport.java:237)
    at com.codenvy.im.utils.HttpTransport.request(HttpTransport.java:171)
    at com.codenvy.im.utils.HttpTransport.doGet(HttpTransport.java:109)
    at com.codenvy.im.utils.HttpTransport.doGet(HttpTransport.java:93)
    at com.codenvy.im.managers.DownloadManager.getAllUpdates(DownloadManager.java:402)
    at com.codenvy.im.facade.InstallationManagerFacade.getAllUpdates(InstallationManagerFacade.java:239)
    at com.codenvy.im.facade.InstallationManagerFacade.getAllUpdatesAfterInstalledVersion(InstallationManagerFacade.java:232)
    at com.codenvy.im.facade.IMArtifactLabeledFacade.getAllUpdatesAfterInstalledVersion(IMArtifactLabeledFacade.java:120)
    at com.codenvy.im.cli.command.VersionCommand.doExecuteCommand(VersionCommand.java:56)
    at com.codenvy.im.cli.command.AbstractIMCommand.execute(AbstractIMCommand.java:82)
    at com.codenvy.im.cli.command.AbstractIMCommand.execute(AbstractIMCommand.java:57)
    at com.codenvy.cli.command.builtin.AbsCommand.doExecute(AbsCommand.java:79)
    at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)[25:org.apache.karaf.shell.console:3.0.2]
    at Proxy527c5774_e9f3_44cb_aea3_2080de30d20f.execute(Unknown Source)[:]
    at Proxy527c5774_e9f3_44cb_aea3_2080de30d20f.execute(Unknown Source)[:]
    at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[25:org.apache.karaf.shell.console:3.0.2]
    at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)
    at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:203)
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:115)
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_45]
    at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)[26:org.apache.karaf.jaas.modules:3.0.2]
    at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:108)[25:org.apache.karaf.shell.console:3.0.2]
Caused by: java.lang.RuntimeException: Could not generate DH keypair
    at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:136)[:1.8.0_45]
    at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:693)[:1.8.0_45]
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264)[:1.8.0_45]
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)[:1.8.0_45]
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)[:1.8.0_45]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)[:1.8.0_45]
    ... 36 more
Caused by: java.security.NoSuchAlgorithmException: DiffieHellman KeyPairGenerator not available
    at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:218)[:1.8.0_45]
    at sun.security.ssl.JsseJce.getKeyPairGenerator(JsseJce.java:281)[:1.8.0_45]
    at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:125)[:1.8.0_45]
    ... 43 more
2016-08-22 15:37:47,867 +0000 [ERROR] com.codenvy.im.console.Console.printErrorAndExit(Console.java:181) {
  "message" : "java.lang.RuntimeException: Could not generate DH keypair",
  "status" : "ERROR"
}
```

This bug had been reproduced by _Fidelity_ and _Apptium_ customers.

**Comment by dmytro-ndp** [comment]
This issue is closed because of wrong repository.
