### ISSUE TITLE
Change the display language in the VS Code UI via Language Packs such as French or Chinese doesn't work

### ISSUE THREAD

**Issue by chris93111** [eclipse-che/che#21963]
### Summary

I try to change the language pack but they are no effect in vsc, the language is not present after install 

Anyone can confirm language pack is not compatible with che-code or they are solution ?

If i try to install manually the result is same but this error appear The 'ms-ceintl.vscode-language-pack-fr' extension is not available in CheCode for Web.

**Comment by l0rd** [comment]
I have tried to reproduce the problem using [French Language Pack for Visual Studio Code](https://open-vsx.org/extension/MS-CEINTL/vscode-language-pack-fr) and I confirm that after installing it [the display language was not changed and I could not change it using the command palette](https://code.visualstudio.com/docs/getstarted/locales):

![2023-01-30 21 38 32](https://user-images.githubusercontent.com/606959/215590167-20dc72a0-10fc-4aee-a630-626b7b7879b6.gif)

@azatsarynnyy any idea?

**Comment by azatsarynnyy** [comment]
When I choose `Configure Display Language` command in the Command Palette, the list is empty and there's an error in the browser's logs:
```
  ERR RequestService#request (browser) - error https://open-vsx.org/vscode/gallery/extensionquery Canceled: Canceled
    at S (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:10:1192)
    at https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:69:1232
    at g.invoke (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:145)
    at n.deliver (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:2029)
    at a.fire (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:1667)
    at R.cancel (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:17879)
    at D.cancel (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:18293)
    at https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:20854
    at g.invoke (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:145)
    at n.deliver (https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/workspace6641c5c16dfa43f3/tools/3100/oss-dev/static/out/vs/workbench/workbench.web.main.js:83:2029)
```

**Comment by azatsarynnyy** [comment]
I'm labeling it as a bug. We need to investigate it.

**Comment by azatsarynnyy** [comment]
And some related logs on the server:
```
File not found: /checode/checode-linux-libc/out/vs/workbench/workbench.web.main.nls.fr.js
```

**Comment by RomanNikitenko** [comment]
I investigated the current problem and I would say it's not about fixing a bug.

My understanding is:
- VS Code uses a translations service for this functionality
- it's configured in the `product.json` file => `extensionsGallery` section => `nlsBaseUrl` property
- that URL ^ is used to get localization items when a language is selected

Che Code uses https://open-vsx.org/vscode/gallery as extension gallery  and `nlsBaseUrl` property is not configured for the Che-Code.

So, I see at least the following tasks to get it working:
- translations service should be implemented and configured in the `product.json` file to serve Che Code
- a mechanism that generates localizations files in expected for VS Code amd module format
- additional investigation is required how to provide those localizations to VS Code (how VS Code consumes those localization items)

**Comment by RomanNikitenko** [comment]
Upstream issue: https://github.com/microsoft/vscode/issues/240359
