### ISSUE TITLE
aarch64 -  che-machine-exec PANI[0000] Unable to create manager. Unable to get service account info. 

### ISSUE THREAD

**Issue by pyy** [eclipse-che/che#22156]
### Describe the bug

Hello,
I'm compiling che-code on aarch64 (Ampere A1), for `che-machine-exec`, I cannot run it:

```
# CGO_ENABLED=0 GOOS=linux go build -mod=vendor -a -ldflags '-w -s' -a -installsuffix cgo -o che-machine-exec .
```

```
# ./che-machine-exec
INFO[0000] Default 'info' log level is applied          
PANI[0000] Error: Unable to create manager. Unable to get service account info. 
panic: (*logrus.Entry) 0x40002ea7e0

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log({0x40000d8000, 0x400026ff50, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
	/che-machine-exec/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2d0
github.com/sirupsen/logrus.(*Entry).Log(0x4000258b60, 0x0, {0x4000139cb8?, 0xf1fda0?, 0x12b7c5d?})
	/che-machine-exec/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
github.com/sirupsen/logrus.(*Logger).Log(0x40000d8000, 0x0, {0x4000139cb8, 0x1, 0x1})
	/che-machine-exec/vendor/github.com/sirupsen/logrus/logger.go:192 +0x64
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/che-machine-exec/vendor/github.com/sirupsen/logrus/logger.go:233
github.com/sirupsen/logrus.Panic(...)
	/che-machine-exec/vendor/github.com/sirupsen/logrus/exported.go:129
github.com/eclipse-che/che-machine-exec/exec.CreateExecManager()
	/che-machine-exec/exec/exec-manager-provider.go:64 +0x128
github.com/eclipse-che/che-machine-exec/exec.GetExecManager(...)
	/che-machine-exec/exec/exec-manager-provider.go:72
github.com/eclipse-che/che-machine-exec/api/jsonrpc.init()
	/che-machine-exec/api/jsonrpc/handlers.go:51 +0x30
```

https://github.com/eclipse-che/che-machine-exec issues submit brings me here.

### Che version

latest
next
also other versions

### Steps to reproduce

I also tried: `docker run --rm -it quay.io/eclipse/che-machine-exec:next sh` The same problem. 
Neither other version from quay.io/eclipse/che-machine-exec.

```
INFO[0000] Default 'info' log level is applied          
PANI[0000] Error: Unable to create manager. Unable to get service account info. 
panic: (*logrus.Entry) 0x400027e460

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log({0x400016c000, 0x40003c2960, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
	/che-machine-exec/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2d0
github.com/sirupsen/logrus.(*Entry).Log(0x400027e3f0, 0x0, {0x40000c5cb8?, 0xf1c9a0?, 0x12b727e?})
	/che-machine-exec/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
github.com/sirupsen/logrus.(*Logger).Log(0x400016c000, 0x0, {0x40000c5cb8, 0x1, 0x1})
	/che-machine-exec/vendor/github.com/sirupsen/logrus/logger.go:192 +0x64
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/che-machine-exec/vendor/github.com/sirupsen/logrus/logger.go:233
github.com/sirupsen/logrus.Panic(...)
	/che-machine-exec/vendor/github.com/sirupsen/logrus/exported.go:129
github.com/eclipse-che/che-machine-exec/exec.CreateExecManager()
	/che-machine-exec/exec/exec-manager-provider.go:64 +0x128
github.com/eclipse-che/che-machine-exec/exec.GetExecManager(...)
	/che-machine-exec/exec/exec-manager-provider.go:72
github.com/eclipse-che/che-machine-exec/api/jsonrpc.init()
	/che-machine-exec/api/jsonrpc/handlers.go:51 +0x30
```

### Expected behavior

eclipse-che.terminal works well on che-code.

### Runtime

Docker Linux

### Screenshots

OpenSUSE 15.4 + Docker

### Environment

Linux

### Additional context

che-code got error:
`Activating extension 'eclipse-che.terminal' failed: connect ECONNREFUSED 127.0.0.1:3333.`
`Cannot activate the 'Eclipse Che Devfile Commands' extension because its dependency 'Eclipse Che Terminal' failed to activate`

the I found that `che-machine-exec` was not working well. So I tried above methods to try to solve the problem.

**Comment by tolusha** [comment]
Both `che-machine-exec` and `che-theia` are removed from plugin and devfile registries (not used anymore) as a part of Sunset Che Theia [1] 

[1] https://github.com/eclipse/che/issues/21771

**Comment by ibuziuk** [comment]
Closing based on the comment above
