### ISSUE TITLE
failing to create new project

### ISSUE THREAD

**Issue by michael-basil** [eclipse-che/che#222]
I have Che running behind nginx here: https://che.xbasil.com with an SSL cert from let's encrypt.  I set it up according to the instructions here: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04.  

I downloaded Che here yesterday night: https://install.codenvycorp.com/che/eclipse-che-latest.tar.gz

When I create a new project step 2 (Start workspace master) hangs.  

Log detail below:

Using CATALINA_BASE:   /home/macadmin/eclipse-che/tomcat
Using CATALINA_HOME:   /home/macadmin/eclipse-che/tomcat
Using CATALINA_TMPDIR: /home/macadmin/eclipse-che/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-8-oracle/jre/
Using CLASSPATH:       /home/macadmin/eclipse-che/tomcat/conf/:/usr/lib/jvm/java-8-oracle/jre//lib/tools.jar:/home/macadmin/eclipse-che/tomcat/bin/bootstrap.jar:/home/macadmin/eclipse-che/tomcat/bin/tomcat-juli.jar
2016-01-25 17:11:42,714[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.28
2016-01-25 17:11:42,723[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 7 2015 18:25:21 UTC
2016-01-25 17:11:42,724[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.28.0
2016-01-25 17:11:42,725[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2016-01-25 17:11:42,744[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.16.0-4-amd64
2016-01-25 17:11:42,745[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2016-01-25 17:11:42,745[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-8-oracle/jre
2016-01-25 17:11:42,753[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_66-b17
2016-01-25 17:11:42,753[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2016-01-25 17:11:42,753[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/macadmin/eclipse-che/tomcat
2016-01-25 17:11:42,754[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/macadmin/eclipse-che/tomcat
2016-01-25 17:11:42,754[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/macadmin/eclipse-che/tomcat/conf/logging.properties
2016-01-25 17:11:42,755[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2016-01-25 17:11:42,763[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2016-01-25 17:11:42,764[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2016-01-25 17:11:42,765[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2016-01-25 17:11:42,772[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2016-01-25 17:11:42,773[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/home/macadmin/eclipse-che/conf/
2016-01-25 17:11:42,774[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/macadmin/eclipse-che
2016-01-25 17:11:42,775[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/macadmin/eclipse-che/tomcat/logs/
2016-01-25 17:11:42,782[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/macadmin/eclipse-che/tomcat/endorsed
2016-01-25 17:11:42,783[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/macadmin/eclipse-che/tomcat
2016-01-25 17:11:42,783[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/macadmin/eclipse-che/tomcat
2016-01-25 17:11:42,783[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/macadmin/eclipse-che/tomcat/temp
2016-01-25 17:11:43,240[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 424]  - Initializing ProtocolHandler ["http-nio-8080"]
2016-01-25 17:11:43,270[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2016-01-25 17:11:43,315[main]             [INFO ] [o.a.catalina.startup.Catalina 587]   - Initialization processed in 1664 ms
2016-01-25 17:11:43,524[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
2016-01-25 17:11:43,524[main]             [INFO ] [o.a.c.core.StandardService 433]      - Starting service Catalina
2016-01-25 17:11:43,525[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.28
2016-01-25 17:11:43,715[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/macadmin/eclipse-che/tomcat/webapps/ide.war
2016-01-25 17:11:55,089[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
2016-01-25 17:11:59,246[ost-startStop-1]  [INFO ] [.c.p.d.c.DockerRegistryChecker 43]   - Probing registry 'http://localhost:5000'
2016-01-25 17:11:59,304[ost-startStop-1]  [WARN ] [.c.p.d.c.DockerRegistryChecker 50]   - Docker registry http://localhost:5000 is not available, which means that you won't be able to save snapshots of your workspaces.
How to configure registry?
        Local registry  -> https://docs.docker.com/registry/
        Remote registry -> set up 'docker.registry.auth.*' properties
2016-01-25 17:12:00,281[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/macadmin/eclipse-che/tomcat/webapps/ide.war has finished in 16,564 ms
2016-01-25 17:12:00,288[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/macadmin/eclipse-che/tomcat/webapps/swagger.war
2016-01-25 17:12:00,405[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/macadmin/eclipse-che/tomcat/webapps/swagger.war has finished in 117 ms
2016-01-25 17:12:00,413[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/macadmin/eclipse-che/tomcat/webapps/dashboard.war
2016-01-25 17:12:00,504[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/macadmin/eclipse-che/tomcat/webapps/dashboard.war has finished in 90 ms
2016-01-25 17:12:00,509[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1036]       - Deploying web application directory /home/macadmin/eclipse-che/tomcat/webapps/ROOT
2016-01-25 17:12:00,686[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1152]       - Deployment of web application directory /home/macadmin/eclipse-che/tomcat/webapps/ROOT has finished in 177 ms
2016-01-25 17:12:00,707[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 469]  - Starting ProtocolHandler ["http-nio-8080"]
2016-01-25 17:12:00,737[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 17421 ms
2016-01-25 17:23:07,012[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 144]    - EVENT#workspace-created# WS#wksp-q58q# WS-ID#workspaceo0fuc44kamvqr8lp# USER#che#
2016-01-25 17:23:08,230[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = workspaceo0fuc44kamvqr8lp: env = wksp-q58q: machine = ws-machine]
2016-01-25 17:23:08,562[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Unable build docker based machine, Dockerfile found but it doesn't contain base image.
org.eclipse.che.api.machine.server.exception.MachineException: Unable build docker based machine, Dockerfile found but it doesn't contain base image.
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:395) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:336) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:167) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:451) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:319) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:145) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$9(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-beta-12.jar:4.0.0-beta-12]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
Caused by: org.eclipse.che.api.machine.server.exception.InvalidRecipeException: Unable build docker based machine, Dockerfile found but it doesn't contain base image.
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.parseRecipe(DockerInstanceProvider.java:263) ~[che-plugin-docker-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:216) ~[che-plugin-docker-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:359) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        ... 11 common frames omitted
2016-01-25 17:26:42,510[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 144]    - EVENT#workspace-created# WS#wksp-wre2# WS-ID#workspace8ofrg8mihqvawn3a# USER#che#
2016-01-25 17:26:43,707[kspaceManager-1]  [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = workspace8ofrg8mihqvawn3a: env = wksp-wre2: machine = ws-machine]
2016-01-25 17:26:45,350[kspaceManager-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Can't start machine ws-machine. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.eclipse.che.api.machine.server.exception.MachineException: Can't start machine ws-machine. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.eclipse.che.api.machine.server.MachineManager.getRecipeByLocation(MachineManager.java:982) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:292) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:167) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:451) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:319) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:145) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$9(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-beta-12.jar:4.0.0-beta-12]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-25 17:38:04,664[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 144]    - EVENT#workspace-created# WS#wksp-2455# WS-ID#workspaceegx08eud3u9bn0ye# USER#che#
2016-01-25 17:38:05,742[kspaceManager-2]  [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = workspaceegx08eud3u9bn0ye: env = wksp-2455: machine = ws-machine]
2016-01-25 17:38:06,024[kspaceManager-2]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Can't start machine ws-machine. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.eclipse.che.api.machine.server.exception.MachineException: Can't start machine ws-machine. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.eclipse.che.api.machine.server.MachineManager.getRecipeByLocation(MachineManager.java:982) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:292) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:167) ~[che-core-api-machine-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:451) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:319) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:145) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$9(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-beta-12.jar:4.0.0-beta-12]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-beta-12.jar:4.0.0-beta-12]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]

**Comment by ghost** [comment]
The log says that Che cannot recognize a Dockerfile that is used to build an image that is then run.

How did you create your workspace? What steps should we follow to reproduce it?

**Comment by michael-basil** [comment]
See the attached screenshots.

If you want you can reach out to me directly at mbasil@macfound.org and
I'll give you SSH access to the box.  It's isolated and I'm going to burn
it after the eval is complete.

mb

## 

_Michael Basil_
312-436-1083
linkedin http://www.linkedin.com/in/mikebasil

**Comment by michael-basil** [comment]
![Uploading Screenshot 2016-01-26 at 09.56.42.png…]()
![screenshot 2016-01-26 at 09 56 35](https://cloud.githubusercontent.com/assets/5545441/12586050/432b4604-c414-11e5-9be9-79f0cc34738d.png)
![Uploading Screenshot 2016-01-26 at 09.56.09.png…]()
![screenshot 2016-01-26 at 09 55 38](https://cloud.githubusercontent.com/assets/5545441/12586048/4327865e-c414-11e5-809b-37d31965af13.png)
![screenshot 2016-01-26 at 09 54 15](https://cloud.githubusercontent.com/assets/5545441/12586049/4327c182-c414-11e5-8891-955cc7525d33.png)

**Comment by ghost** [comment]
Have you tried it without https? Do you have such an opportunity?

**Comment by michael-basil** [comment]
It got further when I ran it directly from port 8080, but still failed.
![screenshot 2016-01-26 at 14 22 04](https://cloud.githubusercontent.com/assets/5545441/12593743/418553b6-c438-11e5-83df-96c198963967.png)

**Comment by michael-basil** [comment]
I'm trying the new beta download now

**Comment by ghost** [comment]
The screenshot says that the browser cannot connect to workspace agent.

When starting che, you need to pass server IP address -r:ip

So, ./che.sh -r:IP_COMES_HERE run

**Comment by michael-basil** [comment]
I have the default setup working now after a suggestion from Tyler.

I haven't re introduced nginx yet.

**Comment by ghost** [comment]
Closing issue after getting in touch with the @mbasil77
