### ISSUE TITLE
Trying to build and run Eclipse Che 4.6.x, I get java.lang.NoClassDefFoundError: org/objectweb/asm/MethodVisitor

### ISSUE THREAD

**Issue by mariosotil** [eclipse-che/che#2259]
I'm trying to build and Eclipse Che. This is what I get when I run in superdevmode:

```
Super Dev Mode starting up
   workDir: /var/folders/z2/j5w51lcn25n4j_643yzfmltw0000gn/T/gwt-codeserver-790397620201564297.tmp
   Job org.eclipse.che.ide.IDE_1_0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
      binding: locale=en
         [WARN] property 'locale' cannot be set to 'en'
         allowed values: default
         recovered with locale=default
      binding: user.agent=safari
      Compiling module org.eclipse.che.ide.IDE
java.lang.NoClassDefFoundError: org/objectweb/asm/MethodVisitor
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.getDeclaredMethod(Class.java:2128)
    at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1475)
    at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:72)
    at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:498)
    at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:472)
    at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
    at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:503)
    at com.google.gwt.dev.javac.CachedCompilationUnit.readObject(CachedCompilationUnit.java:204)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1714)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at com.google.gwt.dev.javac.CompilationUnitArchive.readObject(CompilationUnitArchive.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at com.google.gwt.dev.javac.CompilationUnitArchive.createFromStream(CompilationUnitArchive.java:59)
    at com.google.gwt.dev.javac.CompilationUnitArchive.createFromURL(CompilationUnitArchive.java:66)
    at com.google.gwt.dev.ArchivePreloader.preloadArchives(ArchivePreloader.java:62)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:246)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
    at com.google.gwt.dev.Compiler.run(Compiler.java:206)
    at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:333)
    at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:161)
    at com.google.gwt.dev.codeserver.Recompiler.precompile(Recompiler.java:99)
    at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:96)
    at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
    at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
    at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
    at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
    at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.MethodVisitor
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 67 more
```

This is **my configuration**:
- Mac OS X El Capitan
- Eclipse Che Developer with Eclipse Mars, configured with [yatta](https://marketplace.yatta.de/profiles/hub/iQBd)
- I configured Eclipse to use Maven 3.3.9 as external runtime
- I did checkout from the branch to `4.6.x` (commit 2f0e72a)
- I configured the project following this [Eclipse Che guide](https://eclipse-che.readme.io/docs/setup-che-workspace)
- Java 1.8.0_92
- I installed bower 1.7.9 and gulp 3.9.1

When **I build using maven** from an external console, I get a `build success` message.

```
$ mvn clean install

[...]

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Che Parent ......................................... SUCCESS [  2.764 s]
[INFO] Che Core Parent .................................... SUCCESS [  0.059 s]
[INFO] Che Core :: Commons :: Parent ...................... SUCCESS [  0.048 s]
[INFO] Che Core :: Commons :: Annotations ................. SUCCESS [  4.073 s]
[INFO] Che Core :: Commons :: Java API extension classes .. SUCCESS [  6.107 s]
[INFO] Che Core :: Commons :: Dependency Injecting ........ SUCCESS [  5.147 s]
[INFO] Che Core :: Commons :: Json helpers ................ SUCCESS [  3.289 s]
[INFO] Che Core :: Commons :: XML ......................... SUCCESS [  5.613 s]
[INFO] Che Core :: Commons :: Scheduler service ........... SUCCESS [  5.283 s]
[INFO] Che Core :: Commons :: Utilities for tests ......... SUCCESS [  3.157 s]
[INFO] Che Core :: API :: DTO ............................. SUCCESS [  8.687 s]
[INFO] Che Core :: API :: DTO Maven Plugin ................ SUCCESS [  3.945 s]
[INFO] Che Core :: API :: Core ............................ SUCCESS [ 17.536 s]
[INFO] Che Core :: API :: Model ........................... SUCCESS [  2.604 s]
[INFO] Che Master Parent .................................. SUCCESS [  0.036 s]
[INFO] Che Core :: API :: Authentication .................. SUCCESS [  7.302 s]
[INFO] Che Core :: API :: Machine :: Shared ............... SUCCESS [  5.928 s]
[INFO] Che Core :: API :: Workspace :: Shared ............. SUCCESS [  5.177 s]
[INFO] Che Core :: API :: Project Templates :: Shared ..... SUCCESS [  3.705 s]
[INFO] Che Core :: API :: Project Templates ............... SUCCESS [  3.259 s]
[INFO] Che Core :: API :: Machine ......................... SUCCESS [ 10.220 s]
[INFO] Che Core :: API :: Workspace ....................... SUCCESS [ 11.679 s]
[INFO] Che Core :: API :: User :: Shared .................. SUCCESS [  3.569 s]
[INFO] Che Core :: API :: User ............................ SUCCESS [  6.882 s]
[INFO] Che Core :: API :: Factory :: Shared ............... SUCCESS [  4.475 s]
[INFO] Che Core :: API :: Factory ......................... SUCCESS [  9.340 s]
[INFO] Che Core :: API :: SSH :: Shared ................... SUCCESS [  2.342 s]
[INFO] Che Core :: API :: SSH ............................. SUCCESS [  4.489 s]
[INFO] Che Core :: API :: Impl Local ...................... SUCCESS [  7.515 s]
[INFO] Che Agent Parent ................................... SUCCESS [  0.028 s]
[INFO] Che Core :: API :: Project Shared .................. SUCCESS [  5.697 s]
[INFO] Che Core :: API :: Agent ........................... SUCCESS [  5.250 s]
[INFO] Che Core :: API :: Project ......................... SUCCESS [ 50.220 s]
[INFO] Che Core :: API :: Git :: Shared ................... SUCCESS [  2.685 s]
[INFO] Che Core :: API :: Git ............................. SUCCESS [  9.994 s]
[INFO] Che Plugin :: Parent ............................... SUCCESS [  0.030 s]
[INFO] Che Plugin :: SSH Key :: Parent .................... SUCCESS [  0.027 s]
[INFO] Che Plugin :: SSH Key :: Server .................... SUCCESS [  3.380 s]
[INFO] Che Core :: Git Impl Native ........................ SUCCESS [ 48.161 s]
[INFO] Che Core :: Git Impl JGit .......................... SUCCESS [ 14.377 s]
[INFO] Che Core :: API :: Debug :: Shared ................. SUCCESS [  3.069 s]
[INFO] Che Core :: API :: Debug ........................... SUCCESS [  5.643 s]
[INFO] Che Core :: IDE .................................... SUCCESS [  0.031 s]
[INFO] Che Core :: Commons :: GWT ......................... SUCCESS [ 11.212 s]
[INFO] Che Core :: IDE :: API ............................. SUCCESS [ 24.773 s]
[INFO] Che Core :: IDE :: Generators ...................... SUCCESS [  3.789 s]
[INFO] Che Core :: IDE :: UI .............................. SUCCESS [ 12.711 s]
[INFO] Che Core :: IDE :: App ............................. SUCCESS [ 33.470 s]
[INFO] Che Core :: IDE :: TEMPLATES ....................... SUCCESS [  0.047 s]
[INFO] Che Core :: IDE :: STACKS .......................... SUCCESS [  0.063 s]
[INFO] Che Plugin ::  Product Info :: Client .............. SUCCESS [  2.256 s]
[INFO] Che Plugin :: Help :: Parent ....................... SUCCESS [  0.029 s]
[INFO] Che Plugin :: Help :: Client ....................... SUCCESS [  2.717 s]
[INFO] Che Plugin :: Docker :: Parent ..................... SUCCESS [  0.030 s]
[INFO] Che Plugin :: Docker :: Docker Client .............. SUCCESS [ 17.960 s]
[INFO] Che Plugin :: Docker :: Machine .................... SUCCESS [ 12.721 s]
[INFO] Che Plugin :: Web :: Parent ........................ SUCCESS [  0.027 s]
[INFO] Che Plugin :: Web :: File Types .................... SUCCESS [  3.203 s]
[INFO] Che Plugin :: Orion :: Parent ...................... SUCCESS [  0.028 s]
[INFO] Che Plugin :: Orion :: Editor ...................... SUCCESS [  8.741 s]
[INFO] Che Plugin :: Machine :: Parent .................... SUCCESS [  0.035 s]
[INFO] Che Plugin :: Machine .............................. SUCCESS [ 21.653 s]
[INFO] che-plugin-machine-ext-server ...................... SUCCESS [  4.394 s]
[INFO] Che Plugin :: Machine :: SSH Client ................ SUCCESS [  3.384 s]
[INFO] Che Plugin :: Debugger :: Parent ................... SUCCESS [  0.031 s]
[INFO] Che Plugin :: Debugger :: Extension Debugger IDE ... SUCCESS [ 10.157 s]
[INFO] Che Plugin :: Java :: Parent ....................... SUCCESS [  0.032 s]
[INFO] Che Plugin :: Java :: Extension JDT ................ SUCCESS [  0.035 s]
[INFO] Che Plugin :: Java :: Eclipse JFace ................ SUCCESS [  3.907 s]
[INFO] Che Plugin :: Java :: Eclipse JFace Text ........... SUCCESS [  4.004 s]
[INFO] Che Plugin :: Java :: org.eclipse.core.filesystem .. SUCCESS [  3.534 s]
[INFO] Che Plugin :: Java :: org.eclipse.core.resources ... SUCCESS [  7.021 s]
[INFO] Che Plugin :: Java :: org.eclipse.core.filebuffers . SUCCESS [  4.125 s]
[INFO] Che Plugin :: Java :: Eclipse Search ............... SUCCESS [  4.310 s]
[INFO] Che Plugin :: Java :: Eclipse IDE UI ............... SUCCESS [  3.571 s]
[INFO] Che Plugin :: Java :: Extension Java Shared ........ SUCCESS [ 12.273 s]
[INFO] Che Plugin :: Java :: Eclipse LTK Refactoring ...... SUCCESS [  8.298 s]
[INFO] Che Plugin :: Java :: Eclipse JDT UI ............... SUCCESS [ 52.703 s]
[INFO] Che Plugin :: Java :: Extension Java Server ........ SUCCESS [ 13.965 s]
[INFO] Che Plugin :: Java :: Plain ........................ SUCCESS [  0.030 s]
[INFO] Che Plugin :: Java :: Plain :: Shared .............. SUCCESS [  2.171 s]
[INFO] Che Plugin :: Java :: Plain :: IDE ................. SUCCESS [  3.399 s]
[INFO] Che Plugin :: Orion :: Compare Widget .............. SUCCESS [  2.912 s]
[INFO] Che Plugin :: Java :: Extension Java Client ........ SUCCESS [ 20.686 s]
[INFO] Che Plugin :: Java :: Plain :: Server .............. SUCCESS [  5.672 s]
[INFO] Che Plugin :: Java Debugger :: Parent .............. SUCCESS [  0.029 s]
[INFO] Che Plugin :: Java :: Java Debugger Server ......... SUCCESS [ 21.368 s]
[INFO] Che Plugin :: Java :: Java Debugger IDE ............ SUCCESS [  4.308 s]
[INFO] Che Plugin :: Maven :: Parent ...................... SUCCESS [  0.028 s]
[INFO] Che Plugin :: Maven :: Maven Server ................ SUCCESS [  0.027 s]
[INFO] Che Plugin :: Maven :: Maven Server API ............ SUCCESS [  3.655 s]
[INFO] Che Plugin :: Maven :: Maven Server Impl ........... SUCCESS [02:05 min]
[INFO] Che Plugin :: Maven :: Maven Tools ................. SUCCESS [  5.134 s]
[INFO] Che Plugin :: Maven :: Archetype Generator ......... SUCCESS [  4.543 s]
[INFO] Che Plugin :: Maven :: Extension Maven Shared ...... SUCCESS [  5.260 s]
[INFO] Che Plugin :: Maven :: Extension Maven Client ...... SUCCESS [  5.786 s]
[INFO] Che Plugin :: Maven :: Extension Maven Server ...... SUCCESS [01:35 min]
[INFO] Che Plugin :: GDB :: Parent ........................ SUCCESS [  0.028 s]
[INFO] Che Plugin :: GDB :: GDB Server .................... SUCCESS [  4.204 s]
[INFO] Che Plugin :: GDB :: GDB IDE ....................... SUCCESS [  4.032 s]
[INFO] Che Plugin :: SDK :: Parent ........................ SUCCESS [  0.026 s]
[INFO] Che Plugin :: SDK :: Plugins Development ........... SUCCESS [  3.128 s]
[INFO] Che Plugin :: SDK :: Local Env ..................... SUCCESS [  2.312 s]
[INFO] Che Plugin :: SDK :: Tools ......................... SUCCESS [  7.181 s]
[INFO] Che Plugin :: Git :: Parent ........................ SUCCESS [  0.029 s]
[INFO] Che Plugin :: Git :: Extension ..................... SUCCESS [ 14.336 s]
[INFO] Che Plugin :: Git :: Che credential provider ....... SUCCESS [  2.256 s]
[INFO] Che Plugin :: Github :: Parent ..................... SUCCESS [  0.086 s]
[INFO] Che Plugin :: Github :: OAuth2 ..................... SUCCESS [  2.860 s]
[INFO] Che Plugin :: Github :: Credential provider ........ SUCCESS [  2.290 s]
[INFO] Che Plugin :: Github :: Shared ..................... SUCCESS [  1.945 s]
[INFO] Che Plugin :: SSH Key :: Client .................... SUCCESS [  4.358 s]
[INFO] Che Plugin :: Github :: IDE ........................ SUCCESS [  7.410 s]
[INFO] Che Plugin :: Github :: Server ..................... SUCCESS [  5.892 s]
[INFO] Che Plugin :: Dashboard :: Parent .................. SUCCESS [  0.091 s]
[INFO] Che Plugin :: Dashboard :: Client .................. SUCCESS [  2.754 s]
[INFO] Che Plugin :: GWT :: Parent ........................ SUCCESS [  0.046 s]
[INFO] Che Plugin :: GWT .................................. SUCCESS [  3.555 s]
[INFO] Che Plugin :: Python :: Parent ..................... SUCCESS [  0.045 s]
[INFO] che-plugin-python-lang-shared ...................... SUCCESS [  2.312 s]
[INFO] Che Plugin :: Python :: Extension Server ........... SUCCESS [  2.637 s]
[INFO] Che Plugin :: Python :: IDE ........................ SUCCESS [  2.817 s]
[INFO] Che Plugin :: SVN :: Parent ........................ SUCCESS [  0.054 s]
[INFO] Che Plugin :: SVN :: Shared ........................ SUCCESS [  9.688 s]
[INFO] Che Plugin :: SVN :: Server ........................ SUCCESS [ 42.237 s]
[INFO] Che Plugin :: SVN :: IDE ........................... SUCCESS [  7.814 s]
[INFO] Che Plugin :: C/C++ :: Parent ...................... SUCCESS [  0.028 s]
[INFO] Che Plugin :: C/C++ :: Shared ...................... SUCCESS [  2.026 s]
[INFO] Che Plugin :: C/C++ :: Extension Server ............ SUCCESS [  2.208 s]
[INFO] Che Plugin :: C/C++ :: IDE ......................... SUCCESS [  2.806 s]
[INFO] Che Plugin :: NodeJs :: Parent ..................... SUCCESS [  0.029 s]
[INFO] Che Plugin :: NodeJs :: Extension Shared ........... SUCCESS [  2.314 s]
[INFO] Che Plugin :: NodeJs :: IDE ........................ SUCCESS [  2.732 s]
[INFO] Che Plugin :: NodeJs :: Extension Server ........... SUCCESS [  2.567 s]
[INFO] Che Plugin :: Ssh machine .......................... SUCCESS [  4.852 s]
[INFO] Che Sample :: Parent ............................... SUCCESS [  0.039 s]
[INFO] Che Sample :: Plugin JSON :: Parent ................ SUCCESS [  0.031 s]
[INFO] Che Sample :: Plugin JSON :: Shared ................ SUCCESS [  2.165 s]
[INFO] Che Sample :: Plugin JSON :: IDE ................... SUCCESS [  3.005 s]
[INFO] Che Sample :: Plugin JSON :: Server ................ SUCCESS [  2.642 s]
[INFO] Che Sample :: Plugin FileType :: Parent ............ SUCCESS [  0.045 s]
[INFO] Che Sample :: Plugin FileType :: IDE ............... SUCCESS [  2.311 s]
[INFO] Che Dashboard :: Web App ........................... SUCCESS [04:06 min]
[INFO] Che IDE :: Parent .................................. SUCCESS [  0.030 s]
[INFO] Che Workspace Agent War Packaging .................. SUCCESS [  5.217 s]
[INFO] Che Assembly Workspace Agent Server ................ SUCCESS [  0.794 s]
[INFO] Che IDE :: Compiling GWT Application ............... SUCCESS [05:02 min]
[INFO] Che IDE :: Compiling WS Master WAR ................. SUCCESS [  3.629 s]
[INFO] Che IDE :: Assemblies Tomcat ....................... SUCCESS [  8.546 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:15 min
[INFO] Finished at: 2016-08-29T21:19:48-04:00
[INFO] Final Memory: 348M/1788M
[INFO] ------------------------------------------------------------------------
```

Please, tell me if you need more information. I'll appreciate your help.

**EDIT:** superdevmode run configuration.

<img width="849" alt="screen shot 2016-08-30 at 12 46 07 am" src="https://cloud.githubusercontent.com/assets/9703991/18076375/5c258ea8-6e4b-11e6-8ceb-0a464a0eab00.png">
<img width="854" alt="screen shot 2016-08-30 at 12 46 40 am" src="https://cloud.githubusercontent.com/assets/9703991/18076376/5c2615a8-6e4b-11e6-879b-6be683b932d8.png">
<img width="851" alt="screen shot 2016-08-30 at 12 46 52 am" src="https://cloud.githubusercontent.com/assets/9703991/18076378/5c2b992e-6e4b-11e6-9782-928f2c2a7720.png">
<img width="849" alt="screen shot 2016-08-30 at 12 47 02 am" src="https://cloud.githubusercontent.com/assets/9703991/18076377/5c26e172-6e4b-11e6-8076-e7f40144d2a4.png">

**Comment by ghost** [comment]
@mariosotil can you share your super dev mode run configuration please?

**Comment by mariosotil** [comment]
@eivantsov Sure. I added it into the first comment.

**Comment by ddementieva** [comment]
@mariosotil Try to download GWT SDK 2.7.0 at http://www.gwtproject.org/download.html, unpack it and add `gwt-dev-2.7.0.jar` and `gwt-codeserver-2.7.0.jar` to the Classpath in your super dev mode Run Configurations from the unpacked archive.

**Comment by mariosotil** [comment]
@ddementieva It worked!  Just for documentation, this is my new classpath:

<img width="547" alt="screen shot 2016-08-30 at 8 29 33 am" src="https://cloud.githubusercontent.com/assets/9703991/18089086/0f4b5c02-6e8c-11e6-9fee-472c0c8dc602.png">

Thank you

**Comment by ghost** [comment]
@mariosotil yes, we have updated docs as well! thanks for reporting the issue.
