### ISSUE TITLE
I built Eclipse Che 4.8.0, but I get "LOADING: Error while Booting developer machine" when I try to run a Workspace

### ISSUE THREAD

**Issue by mariosotil** [eclipse-che/che#2271]
I'm trying to run Eclipse Che as a tomcat server, to develop extensions. 

I built the 4.8.0 version using maven with no problems. Also, I'm able to run the superdevmode. Even, I'm able to start the che server

```
$ cd ~/Documents/workspaces/my-eclipse-che-developer/che/assembly/assembly-main/target/eclipse-che-4.8.0-SNAPSHOT/eclipse-che-4.8.0-SNAPSHOT
$ bin/che.sh 
```

And I can open `http://localhost:8080/dashboard` and everything seems fine.

However, after I create a Workspace, when I open it, I see the message "LOADING: Error while Booting developer machine".  

![screen shot 2016-08-31 at 2 17 50 am](https://cloud.githubusercontent.com/assets/9703991/18118176/384afb86-6f21-11e6-839f-b0dea15badc6.png)

Is there something that I'm doing wrong?

This is **my configuration**:
- Mac OS X El Capitan
- Eclipse Che Developer with Eclipse Mars, configured with [yatta](https://marketplace.yatta.de/profiles/hub/iQBd)
- I configured Eclipse to use Maven 3.3.9 as external runtime
- I did checkout from the branch `master` (4.8.0-SNAPSHOT)
- I configured the project following this [Eclipse Che guide](https://eclipse-che.readme.io/docs/setup-che-workspace)
- Docker 1.12.0-a (build: 11213)
- Java 1.8.0_92
- I installed bower 1.7.9 and gulp 3.9.1
- Env variables

```
    export CHE_HOST_IP=127.0.0.1
    export CHE_HOSTNAME=localhost
    export CHE_CONF_FOLDER=/usr/local/opt/che
```
- `che.properties` at `/usr/local/opt/che`

```
#
# Copyright (c) 2012-2016 Codenvy, S.A.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Codenvy, S.A. - initial API and implementation
#

# workspace proxy configuration
http.proxy=
https.proxy=
no_proxy=

### Storage and user configuration
# The location where your workspaces (and their projects) are stored.
# This property works for Docker for Windows, Mac, and Linux.
# On virtualbox for windows, this property is ignored. Instead, they are stored at:
# c:\%userprofile%\AppData\Local\Eclipse Che\
che.workspace.storage=${che.home}/workspaces

# Your projects are synchronized from the Che server into the machine running each
# workspace. This is the directory in the machine where your projects are placed.
che.machine.projects.internal.storage=/projects

# Che stores various internal data objects as JSON on the file system.
che.conf.storage=${che.home}/storage

### Configuration of embedded templates and samples
# Folder that contains JSON files with code templates and samples
project.template_description.location_dir=${che.home}/templates

### Configuration of embedded stacks
#Path to predefined stacks json
che.stacks.default=${che.home}/stacks/stacks.json
#Path to folder with predefined stack icons
che.stacks.images.storage=${che.home}/stacks/images

### oAuth configuration. You can setup GitHub oAuth to automate authentication to remote
### repositories. You need to first register this application with GitHub oAuth.
# GitHub application client ID
oauth.github.clientid=NULL
oauth.github.clientsecret=NULL
oauth.github.authuri= https://github.com/login/oauth/authorize
oauth.github.tokenuri= https://github.com/login/oauth/access_token
oauth.github.redirecturis= http://localhost:${SERVER_PORT}/wsmaster/api/oauth/callback
auth.oauth.access_denied_error_page=/error-oauth

# Activates user self-service at the API level.
# Che has a single identity implementation, so this does not change the user experience.
# If true, enables user creation at API level
user.self.creation.allowed=false

# Remove locations where internal message bus events should be propagated to.
# For debugging - set to retrieve internal events from external clients.
notification.server.propagate_events=

# Che extensions can be scheduled executions on a time basis. 
# This configures the size of the thread pool allocated to extensions that are launched on
# a recurring schedule.
schedule.core_pool_size=10

### Docker is the default machine implementation within Che. Workspaces are powered by machines
### that are constructed when the workspace is started. The images used to generate containers
### for the machines can come from DockerHub or a private Docker registry.
machine.docker.registry=${CHE_REGISTRY_HOST}:5000
machine.docker.snapshot.registry_namespace=NULL
machine.docker.unused_containers_cleanup_period_min=60

### Docker registry auth config example. Note that you can configure many registries with different names.
#docker.registry.auth.your_registry_name.url=https://index.docker.io/v1/
#docker.registry.auth.your_registry_name.username=user-name
#docker.registry.auth.your_registry_name.password=user-password

docker.api.version=1.20
docker.connection.tcp.connection_timeout_ms=600000
docker.connection.tcp.read_timeout_ms=600000

### Machine configuration.  Machines power workspaces. This configures the Che behaviors that
### occur within the machine.

# This archive contains the server to run the workspace agent and any custom extensions.
# Che injects this archive into machines when they are booted or started.
machine.server.ext.archive=${che.home}/lib/ws-agent.zip

# The machine's log files are stored here
machine.logs.location=${che.logs.dir}/machine/logs

# Size of the machine by default.  What is used if RAM parameter not provided by user or API.
machine.default_mem_size_mb=1024

# When the workspace master launches a new workspace, Che performs checks of the internal Web 
# services. When Che gets a valid response, we know that the workspace agent is ready for use.
machine.ws_agent.max_start_time_ms=60000
machine.ws_agent.ping_delay_ms=2000
machine.ws_agent.ping_conn_timeout_ms=2000
machine.ws_agent.ping_timed_out_error_msg=Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.

# Hosts listed here will be added to /etc/hosts of each workspace machine.
# Add an entry here if you write a ws-agent extension that needs to communicate outside the machine
machine.docker.machine_extra_hosts=NULL

# This is the API endpoint of the workspace master running within the core Che server.
# This tells the workspace agent how to connect back to the Che server.
# che-host is a fake DNS hostname that Che creates for itself.
machine.docker.che_api.endpoint=http://che-host:${SERVER_PORT}/wsmaster/api

# If this is true, then we always pull an image from a registry even if we have an image cached
# locally. If false, Docker only pulls image if it does not exist locally.
machine.docker.pull_image=true

# If true, then all docker machines will start in privilege mode.
machine.docker.privilege_mode=false

# If the browser clients that are accessing Che are remote AND the configuration of Docker is an
# internal IP address or using Unix sockets, then remote browser clients will not be able to connect
# to the workspace. Set the Docker configuration so that Docker containers have an external IP 
# address and provide this host or IP address here.
machine.docker.local_node_host=NULL

# Allows to use registry for machine snapshots, you should set this property to {true},
# otherwise workspace snapshots would be saved locally.
machine.docker.snapshot_use_registry=false

# Allows to adjust machine swap memory by multiplication current machnine memory on provided value.
# default is -1 which means unlimited swap, if set multiplier value equal to 0.5 machine swap will be
# configured with size that equal to half of current machine memory, to disable swap set it to 0.
machine.docker.memory_swap_multiplier=-1

# URL path to api service.  
# Browser clients use this to initiate REST communications with workspace master
api.endpoint=http://localhost:${SERVER_PORT}/wsmaster/api

#### Everrest is a Java Web Services toolkit that manages JAX-RS & web socket communications
#### Users should rarely need to configure this.
# Disable asynchronous mechanism that is embedded in everrest.
org.everrest.asynchronous=false
# Quantity of asynchronous requests which may be processed at the same time
org.everrest.asynchronous.pool.size=20
# Size of queue. If asynchronous request can't be processed after consuming it will be added in queue.
org.everrest.asynchronous.queue.size=500
# Timeout in minutes for request. If after timeout request is not done or client did not come yet to get result of request it may be discarded.
org.everrest.asynchronous.job.timeout=10
# Size of cache for waiting, running and ended request.
org.everrest.asynchronous.cache.size=1024
# Path to asynchronous service
org.everrest.asynchronous.service.path=/async/

machine.ssh.connection_timeout_ms=3000
# The location of the Web Socket terminal used within the browser.
# This is copied into the machine and run from within it.
# Suffix helps differentiate archive for different architectures/OSes
machine.server.terminal.path_to_archive.linux_amd64=${che.home}/lib/linux_amd64/terminal
machine.server.terminal.path_to_archive.linux_arm7=${che.home}/lib/linux_arm7/terminal

# During the stop of the workspace automatically creates a snapshot if the value is {true},
# otherwise just stops the workspace.
workspace.runtime.auto_snapshot=true
# During the start of the workspace automatically restored it from a snapshot if the value is {true},
# otherwise just creates the new workspace.
workspace.runtime.auto_restore=true

# Reserved user names
user.reserved_names=

# java opts for dev machine
che.machine.java_opts=-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom
```

**EDIT:** I shut down my laptop and fire it up again before to get these screenshots.

If I started che with this command

```
$ bin/che.sh -d
```

or 

```
$ bin/che.sh -d -r:127.0.0.1
```

The IDE ends here

<img width="1063" alt="screen shot 2016-08-31 at 9 36 24 am" src="https://cloud.githubusercontent.com/assets/9703991/18130810/824017c0-6f5e-11e6-939b-3ecd1ef8474b.png">

**Comment by ddementieva** [comment]
@mariosotil Are there any logs in the IDE console during the workspace start? Also have you checked browser dev console for the errors?

Can you send a screenshot with IDE console logs and with browser dev console opened?

**Comment by mariosotil** [comment]
@ddementieva Hi. There are no logs in the IDE. As you can see on my last edition, the Processes windows stays empty.  Please, tell me if you need something more.

**Comment by ddementieva** [comment]
@mariosotil Are you using a simple docker or docker Toolbox? Can you run docker commands in your Terminal, e.g. docker images?

Can you run Che this way bin/che.sh and send server logs?

**Comment by mariosotil** [comment]
@ddementieva  I'm using a simple Docker. I installed it from the Stable Channel, from [Getting Started with Docker for Mac](https://docs.docker.com/docker-for-mac/). Do I have to use a Docker Toolbox?

The new window from this attempt:
<img width="1114" alt="screen shot 2016-08-31 at 10 16 00 am" src="https://cloud.githubusercontent.com/assets/9703991/18132241/064b18da-6f64-11e6-8256-416ccaa7a7f2.png">

**Comment by mariosotil** [comment]
@ddementieva I tried to use the Docker version of Eclipse Che on my laptop, using the CLI, and it has the same problem too. It can't pass from the "Initializing workspace". Maybe it helps to understand what is happening. These are the logs. 

```
$ che start
INFO: ECLIPSE CHE: Found image codenvy/che-launcher:latest
INFO: ECLIPSE CHE: Starting launcher
INFO: ECLIPSE CHE: ALREADY HAVE IMAGE codenvy/che-server:latest
INFO: ECLIPSE CHE: CONTAINER STARTING
INFO: ECLIPSE CHE: SERVER LOGS AT "docker logs -f che-server"
INFO: ECLIPSE CHE: SERVER BOOTING...
INFO: ECLIPSE CHE: BOOTED AND REACHABLE
INFO: ECLIPSE CHE: http://localhost:8080
$ docker logs -f che-server
2016-08-31 14:39:47,061[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32
2016-08-31 14:39:47,062[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC
2016-08-31 14:39:47,063[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0
2016-08-31 14:39:47,063[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2016-08-31 14:39:47,064[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.4.15-moby
2016-08-31 14:39:47,064[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2016-08-31 14:39:47,064[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
2016-08-31 14:39:47,065[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_92-internal-alpine-r1-b14
2016-08-31 14:39:47,065[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2016-08-31 14:39:47,065[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/tomcat
2016-08-31 14:39:47,065[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/tomcat
2016-08-31 14:39:47,066[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/tomcat/conf/logging.properties
2016-08-31 14:39:47,066[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2016-08-31 14:39:47,066[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
2016-08-31 14:39:47,067[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
2016-08-31 14:39:47,067[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
2016-08-31 14:39:47,067[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2016-08-31 14:39:47,067[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/user/che
2016-08-31 14:39:47,068[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/tomcat/logs/
2016-08-31 14:39:47,068[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2016-08-31 14:39:47,068[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2016-08-31 14:39:47,068[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2016-08-31 14:39:47,069[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2016-08-31 14:39:47,069[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/conf
2016-08-31 14:39:47,069[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/tomcat/endorsed
2016-08-31 14:39:47,070[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/tomcat
2016-08-31 14:39:47,070[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/tomcat
2016-08-31 14:39:47,070[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/tomcat/temp
2016-08-31 14:39:47,163[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-8080"]
2016-08-31 14:39:47,180[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2016-08-31 14:39:47,183[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 352 ms
2016-08-31 14:39:47,203[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
2016-08-31 14:39:47,203[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
2016-08-31 14:39:47,204[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32
2016-08-31 14:39:47,280[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/ROOT.war
2016-08-31 14:39:48,595[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/ROOT.war has finished in 1,314 ms
2016-08-31 14:39:48,596[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/dashboard.war
2016-08-31 14:39:48,718[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/dashboard.war has finished in 122 ms
2016-08-31 14:39:48,719[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/swagger.war
2016-08-31 14:39:48,781[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/swagger.war has finished in 62 ms
2016-08-31 14:39:48,782[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/wsmaster.war
2016-08-31 14:39:50,436[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
2016-08-31 14:39:51,763[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/wsmaster.war has finished in 2,981 ms
2016-08-31 14:39:51,765[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-8080"]
2016-08-31 14:39:51,771[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 4587 ms
2016-08-31 14:40:11,448[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 689]    - Workspace 'che:wksp-vdh6' with id 'workspacexur3i1t6n0hmoo3m' created by user 'che'
2016-08-31 14:40:20,846[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 162]      - Creating machine [ws = workspacexur3i1t6n0hmoo3m: env = default: machine = default]
2016-08-31 14:40:36,650[kspaceManager-0]  [INFO ] [c.p.d.m.DockerInstanceProvider 588]  - Machine with id 'machinebyyk8wgclcbs0vxd' backed by container 'b2590cf65eeb84175f05f362d6fb8a21298bd617bcdc587a7e0b70ac50033f63' has been deployed on node 'localhost'
2016-08-31 14:41:36,712[kspaceManager-0]  [ERROR] [.c.a.m.s.w.WsAgentLauncherImpl 106]  - Fail pinging ws agent. Workspace ID:workspacexur3i1t6n0hmoo3m. Url:http://127.0.0.1:32773/wsagent/ext/. Timestamp:{}
2016-08-31 14:41:37,215[kspaceManager-0]  [ERROR] [.c.a.c.u.CompositeLineConsumer 47]   - An error occurred while writing line to the line consumer org.eclipse.che.api.core.util.FileLineConsumer@32352842
java.io.IOException: Stream closed
    at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116) ~[na:1.8.0_92-internal]
    at java.io.BufferedWriter.write(BufferedWriter.java:221) ~[na:1.8.0_92-internal]
    at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_92-internal]
    at org.eclipse.che.api.core.util.FileLineConsumer.writeLine(FileLineConsumer.java:38) ~[che-core-api-core-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:45) ~[che-core-api-core-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:411) [che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:340) [che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:166) [che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:533) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.6.2.jar:4.6.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92-internal]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92-internal]
2016-08-31 14:41:37,217[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 549]    - Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
org.eclipse.che.api.machine.server.exception.MachineException: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
    at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:416) ~[che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:340) ~[che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:166) ~[che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startMachine(WorkspaceRuntimes.java:582) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startQueue(WorkspaceRuntimes.java:458) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:216) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:533) ~[che-core-api-workspace-4.6.2.jar:4.6.2]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.6.2.jar:4.6.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92-internal]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92-internal]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
    at org.eclipse.che.api.machine.server.wsagent.WsAgentLauncherImpl.startWsAgent(WsAgentLauncherImpl.java:107) ~[che-core-api-machine-4.6.2.jar:4.6.2]
    at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:386) ~[che-core-api-machine-4.6.2.jar:4.6.2]
    ... 10 common frames omitted


```

**Comment by TylerJewell** [comment]
Did you do the pre-reqs for Docker for Mac?

https://eclipse-che.readme.io/docs/usage-docker-server-for-mac#networking

```
# Grabs the IP address of the Xhyve VM
export DOCKER_VM_IP=$(docker run --rm --net host alpine sh -c "ip a show eth0" | \
                    grep 'inet ' | cut -d/ -f1 | awk '{ print $2}')

# Sets the loopback alias for this IP
# You will be asked for your root password
sudo ifconfig lo0 alias $DOCKER_VM_IP

# Prints the IP address
echo $DOCKER_VM_IP
```

**Comment by mariosotil** [comment]
@ddementieva @TylerJewell   I hadn't seen that page. Thank you so much. It worked. 

Just for documentation purposes, it was only necessary the steps from the 'Networking' section. The 'Running Che as a Docker Container' and 'Running Che as a Server' sections are not necessary.

**Comment by TylerJewell** [comment]
We just rewrote our getting started docs - and now we try to channel everyone into this page to start with.

https://eclipse-che.readme.io/v4.7/docs/che-getting-started
