### ISSUE TITLE
Linux: environment variables cause startup to fail

### ISSUE THREAD

**Issue by safarmer** [eclipse-che/che#229]
Che will not start on my linux machine due to some of the environment variables I have set. Specifically:

P4DIFF=bash -c "meld \${@/#:/--diff}" padding-to-occupy-argv0

the workaround is: P4DIFF= ./bin/che.sh run

The stack trace is:

1) An exception was caught and reported. Message: Property @/#:/--diff is not found as system property or environment variable.
  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.0.jar:na]
        at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0.jar:na]
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137) ~[everrest-integration-guice-1.10.0.jar:na]
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) ~[guice-servlet-4.0.jar:na]
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:84) ~[everrest-integration-guice-1.10.0.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738) [catalina.jar:8.0.28]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181) [catalina.jar:8.0.28]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.28]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.28]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.28]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.28]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.28]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798) [catalina.jar:8.0.28]
Caused by: org.eclipse.che.inject.ConfigurationException: Property @/#:/--diff is not found as system property or environment variable.
        at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:243) ~[che-core-commons-inject-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.inject.CheBootstrap$AbstractConfigurationModule.bindProperties(CheBootstrap.java:214) ~[che-core-commons-inject-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.inject.CheBootstrap$ExtConfiguration.configure(CheBootstrap.java:160) ~[che-core-commons-inject-4.0.0-beta-13.jar:4.0.0-beta-13]
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
        at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198) ~[guice-4.0.jar:na]
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0.jar:na]

**Comment by ghost** [comment]
Any steps to follow to reproduce this one? Definitely, cannot reproduce in a clean box.

**Comment by safarmer** [comment]
The following should be enough to cause the crash:
export P4DIFF=bash -c "meld \${@/#:/--diff}" padding-to-occupy-argv0
./bin/che.sh run

**Comment by ghost** [comment]
What is the purpose of this export? Is `export P4DIFF=bash -c "meld \${@/#:/--diff}" padding-to-occupy-argv0` one command? I cannot execute this export on Ubuntu 14

**Comment by safarmer** [comment]
This is so I can use meld rather than the default diff tool when using perforce. Here is the full excerpt from my .bashrc. I was missing some single quotes in the command I sent through.

```
export P4DIFF='bash -c "meld \${@/#:/--diff}" padding-to-occupy-argv0'
export P4MERGE='bash -c "chmod u+w \$1 ; meld \$2 \$1 \$3 ; cp \$1 \$4" padding-to-occupy-argv0'
```

**Comment by TylerJewell** [comment]
@eivantsov Update?

**Comment by ghost** [comment]
I was able to reproduce it. It certainly needs a detailed investigation to be able to say why this error occurs

**Comment by mshaposhnik** [comment]
Its because Che's wrapper over Guice always trying to resolve variables in **_${some.variable}_** form.
Example: _vfs.local.fs_index_root_dir=**${java.io.tmpdir}/fs-index**_
If he cant, it fails with the message above.

**Comment by safarmer** [comment]
The error I got was with an environment variable completely unrelated to Eclipse/Che. It seems that Eclipse is trying to find an environment variable based on part of an environment variable that is for Perforce that it was not able to parse correctly.

**Comment by mshaposhnik** [comment]
Yes, that's true. We will remove exception throwing in case if the system or environment property contain variable that can not be resolved.

**Comment by ghost** [comment]
This commit should fix it - https://github.com/eclipse/che/commit/ac3c8b90b2f042446e3ece3acbefcfe879806f53

I am closing the issue for now. Feel free to reopen if the issue persists.

**Comment by safarmer** [comment]
Does this also cover the case where a variable if valid but parsed wrong? The issue sender to be that eclipse was trying to resolve a value as a key? This seems like it would just hide the problem?
