### ISSUE TITLE
kubernetes 1.30.5 support

### ISSUE THREAD

**Issue by karatkep** [eclipse-che/che#23230]
### Summary

Dear Community,

Could you please help me verify if Eclipse Che 7.93.0 supports Kubernetes 1.30.5? The **che-dashboard** and **che** pods stopped working when our Kubernetes cluster was updated to version 1.30.5.

Here is a sample of the error in the **che-dashboard**:
```
ERROR[12:03:22 UTC]: [HTTP request failed[
    err: {
      "type": "le",
      "message": "HTTP request failed",
      "stack":
          HttpError: HTTP request failed
              at q._callback (/backend/server/backend.js:8:898957)
              at t._callback.t.callback.t.callback (/backend/server/backend.js:14:1087840)
              at q.emit (node:events:517:28)
              at q.<anonymous> (/backend/server/backend.js:14:1100418)
              at q.emit (node:events:517:28)
              at IncomingMessage.<anonymous> (/backend/server/backend.js:14:1099250)
              at Object.onceWrapper (node:events:631:28)
              at IncomingMessage.emit (node:events:529:35)
              at endReadableNT (node:internal/streams/readable:1400:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "response": {
        "statusCode": 401,
        "body": {
          "kind": "Status",
          "apiVersion": "v1",
          "metadata": {},
          "status": "Failure",
          "message": "Unauthorized",
          "reason": "Unauthorized",
          "code": 401
        },
        "headers": {
          "audit-id": "6b14e1b5-8a08-41a8-a093-5e00693737a6",
          "cache-control": "no-cache, private",
          "content-type": "application/json",
          "date": "Mon, 04 Nov 2024 12:03:21 GMT",
          "content-length": "129",
          "connection": "close"
        },
        "request": {
          "uri": {
            "protocol": "https:",
            "slashes": true,
            "auth": null,
            "host": "10.1.0.1:443",
            "port": "443",
            "hostname": "10.1.0.1",
            "hash": null,
            "search": null,
            "query": null,
            "pathname": "/apis/org.eclipse.che/v2/checlusters",
            "path": "/apis/org.eclipse.che/v2/checlusters",
            "href": "https://10.1.0.1:443/apis/org.eclipse.che/v2/checlusters"
          },
          "method": "GET",
          "headers": {
            "Accept": "application/json",
            "Authorization": "Bearer MASKED"
          }
        }
      },
      "body": {
        "type": "Object",
        "message": "Unauthorized",
        "stack":
            
        "kind": "Status",
        "apiVersion": "v1",
        "metadata": {},
        "status": "Failure",
        "reason": "Unauthorized",
        "code": 401
      },
      "statusCode": 401,
      "name": "HttpError"
    }
```
The same issue affects the **che** pod. It appears that both lost access to the Kubernetes API after the upgrade to version 1.30.5.

ServiceAccounts, Cluster Roles and Bindings are in place for both **che-dashboard** and **che** pods

**Comment by tolusha** [comment]
@karatkep 
Could you show che pod logs?

I've tried to reproduce on Minikube with Kubernetes 1.31.0, but no luck

**Comment by karatkep** [comment]
@tolusha 
According to the che logs, the che pod starts receiving 401 errors from the kube-api exactly one hour after the pod starts working/launches:

```
06-Nov-2024 08:26:02.136 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war] has finished in [2,488] ms
06-Nov-2024 08:26:02.138 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
06-Nov-2024 08:26:02.144 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [40907] milliseconds
2024-11-06 09:26:32,950[c4d-k5x9l-37628]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://10.1.0.1:443/api/v1, headers={Authorization=#MASKED:1868#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@6c199c1d] for cluster [RemoteSubscriptionChannel], namespace [eclipse-che], labels [app.kubernetes.io/component=che,app.kubernetes.io/instance=che,app.kubernetes.io/managed-by=che-operator,app.kubernetes.io/name=che,app.kubernetes.io/part-of=che.eclipse.org]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [java.io.IOException: Server returned HTTP response code: 401 for URL: https://10.1.0.1:443/api/v1/namespaces/eclipse-che/pods?labelSelector=app.kubernetes.io%2Fcomponent%3Dche%2Capp.kubernetes.io%2Finstance%3Dche%2Capp.kubernetes.io%2Fmanaged-by%3Dche-operator%2Capp.kubernetes.io%2Fname%3Dche%2Capp.kubernetes.io%2Fpart-of%3Dche.eclipse.org]]
2024-11-06 09:26:42,473[4c4d-k5x9l-3460]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://10.1.0.1:443/api/v1, headers={Authorization=#MASKED:1868#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@f31944b] for cluster [WorkspaceStateCache], namespace [eclipse-che], labels [app.kubernetes.io/component=che,app.kubernetes.io/instance=che,app.kubernetes.io/managed-by=che-operator,app.kubernetes.io/name=che,app.kubernetes.io/part-of=che.eclipse.org]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [java.io.IOException: Server returned HTTP response code: 401 for URL: https://10.1.0.1:443/api/v1/namespaces/eclipse-che/pods?labelSelector=app.kubernetes.io%2Fcomponent%3Dche%2Capp.kubernetes.io%2Finstance%3Dche%2Capp.kubernetes.io%2Fmanaged-by%3Dche-operator%2Capp.kubernetes.io%2Fname%3Dche%2Capp.kubernetes.io%2Fpart-of%3Dche.eclipse.org]]
2024-11-06 09:26:47,468[c4d-k5x9l-46003]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://10.1.0.1:443/api/v1, headers={Authorization=#MASKED:1868#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@5ed91d32] for cluster [WorkspaceLocks], namespace [eclipse-che], labels [app.kubernetes.io/component=che,app.kubernetes.io/instance=che,app.kubernetes.io/managed-by=che-operator,app.kubernetes.io/name=che,app.kubernetes.io/part-of=che.eclipse.org]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [java.io.IOException: Server returned HTTP response code: 401 for URL: https://10.1.0.1:443/api/v1/namespaces/eclipse-che/pods?labelSelector=app.kubernetes.io%2Fcomponent%3Dche%2Capp.kubernetes.io%2Finstance%3Dche%2Capp.kubernetes.io%2Fmanaged-by%3Dche-operator%2Capp.kubernetes.io%2Fname%3Dche%2Capp.kubernetes.io%2Fpart-of%3Dche.eclipse.org]]

```

**Comment by karatkep** [comment]
@tolusha, as I can see, the issue is that the token is not being refreshed. It is generated for 1 hour, and after that time, the che-dashboard continues to use it despite its expiration. Is there any way to prompt the che-dashboard to refresh it before using it for kube-api calls?

**Comment by tolusha** [comment]
@karatkep 
Could you share CheCluster CR? 
What OIDC provider do you use?

**Comment by karatkep** [comment]
@tolusha,
Yes, of course, I will provide the CheCluster CR. However, I don't think that the issue lies with the CheCluster CR or OIDC. The same version of Eclipse Che 7.93.0 was deployed in two identical AKS clusters (Kubernetes version 1.27.9), and everything was fine until one of the clusters was upgraded to 1.30.5. Immediately after this update, problems with the kube-api started. Reviewing the token used, for example, by the che-dashboard, I see that the expiration field "exp" is always the same and is in the past. From this, I conclude that for Kubernetes version 1.30.5, the token is not being updated.

**Comment by karatkep** [comment]
@tolusha, CheCluster CR is below. OIDC is Microsoft Entra ID, previously known as Azure Active Directory (Azure AD).
```
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  annotations:
    che.eclipse.org/checluster-defaults-cleanup: >-
      {"containers.resources":"true","spec.components.dashboard.headerMessage":"true","spec.components.pluginRegistry.openVSXURL":"true","spec.devEnvironments.defaultComponents":"true","spec.devEnvironments.defaultEditor":"true","spec.devEnvironments.disableContainerBuildCapabilities":"true"}
  finalizers:
    - checluster.che.eclipse.org
    - cluster-resources.finalizers.che.eclipse.org
    - cheGateway.clusterpermissions.finalizers.che.eclipse.org
    - dashboard.clusterpermissions.finalizers.che.eclipse.org
  name: eclipse-che
  namespace: eclipse-che
status:
  chePhase: Active
  cheURL: https://web-ide.nohost.com
  cheVersion: 7.93.0
  devfileRegistryURL: ''
  gatewayPhase: Established
  pluginRegistryURL: ''
  workspaceBaseDomain: web-ide.nohost.com
spec:
  components:
    cheServer:
      debug: false
      deployment:
        containers:
          - name: che
            resources:
              limits:
                cpu: '1'
      extraProperties:
        CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: >-
          app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,pod-security.kubernetes.io/enforce=baseline,pod-security.kubernetes.io/enforce-version=latest,pod-security.kubernetes.io/warn=baseline,pod-security.kubernetes.io/warn-version=latest
        CHE_OIDC_AUTH__SERVER__URL: >-
          https://login.microsoftonline.com/fakeuuid-0000-0000-0000-000000000000/v2.0/
        CHE_OIDC_EMAIL__CLAIM: unique_name
        CHE_OIDC_USERNAME__CLAIM: unique_name
      logLevel: INFO
    dashboard:
      deployment:
        containers:
          - env:
              - name: NODE_OPTIONS
                value: '--max-http-header-size=32768'
            resources:
              limits:
                cpu: '1'
      logLevel: ERROR
    devWorkspace: {}
    devfileRegistry:
      deployment:
        containers:
          - resources:
              limits:
                cpu: '1'
      disableInternalRegistry: true
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry:
      deployment:
        containers:
          - resources:
              limits:
                cpu: 500m
      disableInternalRegistry: true
  containerRegistry: {}
  devEnvironments:
    defaultNamespace:
      autoProvision: true
      template: <username>-che
    disableContainerBuildCapabilities: true
    gatewayContainer:
      resources:
        limits:
          cpu: '1'
    maxNumberOfWorkspacesPerUser: -1
    secondsOfInactivityBeforeIdling: 1800
    secondsOfRunBeforeIdling: -1
    security:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      podSecurityContext:
        runAsUser: 101
        seccompProfile:
          type: RuntimeDefault
    startTimeoutSeconds: 360
    storage:
      pvcStrategy: ephemeral
  gitServices: {}
  networking:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.org/websocket-services: che-gateway
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
        deployment:
          containers:
            - name: gateway
              resources:
                limits:
                  cpu: '1'
            - name: configbump
              resources:
                limits:
                  cpu: 500m
            - name: kube-rbac-proxy
              resources:
                limits:
                  cpu: '1'
            - env:
                - name: OAUTH2_PROXY_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: che-secret-key
                      name: che-secret-name
                - name: OAUTH2_PROXY_COOKIE_REFRESH
                  value: 1h0m0s
                - name: OAUTH2_PROXY_OIDC_GROUPS_CLAIM
                  value: name
                - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
                  value: 'true'
                - name: OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS
                  value: 'true'
                - name: OAUTH2_PROXY_EXTRA_JWT_ISSUERS
                  value: >-
                    https://sts.windows.net/fakeuuid-0000-0000-0000-000000000000/=6dae42f8-4368-4678-94ff-3960e28e3630
                - name: OAUTH2_PROXY_COOKIE_DOMAINS
                  value: web-ide.nohost.com
              name: oauth-proxy
              resources:
                limits:
                  cpu: '1'
      identityProviderURL: >-
        https://login.microsoftonline.com/fakeuuid-0000-0000-0000-000000000000/v2.0/
      identityToken: access_token
      oAuthClientName: fakeoaut-h000-0000-0000-000000000000
      oAuthScope: openid email profile 6dae42f8-4368-4678-94ff-3960e28e3630/user.read
    domain: web-ide.nohost.com
    tlsSecretName: che-tls

```

**Comment by karatkep** [comment]
@tolusha , @ibuziuk , We found the root cause of the issue. In Kubernetes 1.27.9, the token (located at the path var/run/secrets/kubernetes.io/serviceaccount/token) is issued for one year, although it is refreshed every hour (or more precisely every 50 minutes). At the same time, in Kubernetes 1.30.5, the token is issued for one hour and is also refreshed every 50 minutes. However, Che (che-dashboard, che, and most likely che-gateway) caches this token at startup and uses it. Consequently, in Kubernetes 1.27.9 there is no problem since the token is issued for one year, but in Kubernetes 1.30.5, the problem begins after the first hour from startup because the cached token is used.

**Comment by tolusha** [comment]
@karatkep 
So, if you restart all pods, Che will continue working, right?

**Comment by karatkep** [comment]
@tolusha
Correct, we need to restart the Che pods every hour to ensure they remain operational.

**Comment by karatkep** [comment]
@tolusha, @ibuziuk, 
Could you please share information and plans regarding this issue? Is everything clear and understandable? Were you able to reproduce it? Are you currently working on a resolution, or do you have plans to start working on it soon?

Just to be on the same page - there is absolutely no pressure from my side. I just want to understand the current status and plans regarding this issue. On my part, I have already used one of the possible workarounds and written a CronJob that restarts the necessary Che pods. If other Eclipse Che users are facing or will face the same issue, I am more than willing to share this workaround.

**Comment by ibuziuk** [comment]
@karatkep Thank you for the follow-up and investigation details - https://github.com/eclipse-che/che/issues/23230#issuecomment-2471679757 

I'm still wondering if the token lifetime is configurable on the k8s end in general? 
Do you happen to have the link to the Release Notes, docs, or commit where this change with the lifetime was introduced? Could it be some AKS config?

The issue has been planned for the next sprint (Nov 20 - Dec 10), however, so far @tolusha was not able to reproduce it on vanilla minikube.

@karatkep also contributions from the Community are most welcome if you would like to change or update the caching mechanism in the project ;-)

**Comment by karatkep** [comment]
@ibuziuk,
When I was researching this issue, I came across the documentation at https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#tokenrequest-api which contains detailed information about configuring token lifetime. Moreover, I conducted an experiment where I disabled the che-operator (so it wouldn’t interfere with making changes) and used the `expirationSeconds` to modify the lifetime of the token. I tried setting it to one day or 86400 seconds for the che-dashboard in the deployment. After restarting the che-dashboard pod, I confirmed that the lifetime of the token (located in /var/run/secrets/kubernetes.io/serviceaccount/token) had indeed changed.

P.S. But frankly speaking, I do not like the option of using a long-lived token - it contradicts security best practices. It seems to me that whoever made this change (token lifetime: 1y -> 1h), it is a step in the right direction to use short-lived tokens. And in my opinion, a well-written application should not cache the token indefinitely.

**Comment by vinokurig** [comment]
I managed to decrease the kubernetes token lifetime to 10 minutes and I confirm that there are Kubernetes connection failure warnings coming every second right after the token expiration time. However, since kubernetes updates the roken in every pod, I could not reproduce the dashboard error and all kubernetes related actions work fine even after the token expiration.
Currently I am working on jgroups-kubernetes che-server dependency update. This library throws the error to the che-server log after the token expires.

**Comment by vinokurig** [comment]
Unfortunately updating the `jgroups-kubernetes` dependency to latest did not solve the issue with `che-server` cyclic log warning, filed an [upstream issue.](https://github.com/jgroups-extras/jgroups-kubernetes/issues/239).
As for the dashboard log error I could not reproduce it with the refreshed kubernetes token, all dashboard kubernetes related actions work fine, e.g PAT token add/list.

**Comment by vinokurig** [comment]
@karatkep could you please elaborate more on what exactly does not work regardless the logs errors? Can you open dashboard page, navigate to user preferences?

**Comment by vinokurig** [comment]
To summarize:
* If kubernetes service account token is refreshed after expiration, all the functionality works as expected except the cyclic error in the che-server logs.
* The che-server logs error is caused by the `jgroups-kubernetes` dependency. The dependency is not used for the current functionality and can be removed as a leftover, however we should consider either to update the dependency, when a new version with the fix is available, or to remove the dependency as a leftover and chek that it does not break the current functionality.
* We are going to [update the fabric8 kubernetes client to latest](https://github.com/eclipse-che/che/issues/2327)

**Comment by ibuziuk** [comment]
@karatkep my understanding is that so far @vinokurig was not able to reproduce the error even with the short-lived token. Steps to reproduce would be highly appreciated.

Basically, all k8s interactions are happening using Fabric8-Kubernetes-Client for che-server and we plan to bump it to version 7.0.0 next sprint.
cc @manusa maybe you have some input on this situation? do we need to care about updating the token / `/var/run/secrets/kubernetes.io/serviceaccount/token`, or client handles the update under the hood - https://github.com/eclipse-che/che/issues/23230#issuecomment-2471679757 ?

**Comment by manusa** [comment]
> cc @manusa maybe you have some input on this situation? do we need to care about updating the token / `/var/run/secrets/kubernetes.io/serviceaccount/token`, or client handles the update under the hood - [#23230 (comment)](https://github.com/eclipse-che/che/issues/23230#issuecomment-2471679757) ?

I understand that the Kubernetes Client in use is [6.10.0](https://github.com/eclipse-che/che-server/blob/f9399787132d9e74dceca0d5c4f4ac70084da2d2/pom.xml#L70).

In this case, yes there's a TokenRefreshInterceptor that reloads the config in case there is an auth client error in the HTTP response.

https://github.com/fabric8io/kubernetes-client/blob/9101a2fa4a8f912ff6cda23e4d4b59895ccdc755/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java#L123-L126

The interceptor logic will work and reload the Config as long as the Config was not provided manually.
Does this ring any bell? Setting a breakpoint in the mentioned lines of code should allow you to debug what's going on the moment the authorization fails.

**Comment by karatkep** [comment]
Hello @ibuziuk, @vinokurig. Please allow me to gather more details regarding this case. I will share them later today or tomorrow.

**Comment by karatkep** [comment]
> @karatkep could you please elaborate more on what exactly does not work regardless the logs errors? Can you open dashboard page, navigate to user preferences?

@vinokurig, the dashboard issue arises when an user attempts to start the devworkspace. Please see the screenshot below:
![image](https://github.com/user-attachments/assets/5cdbe165-66df-49e2-8f8d-112a99581243)

The endpoint `/dashboard/api/devworkspace/running-workspaces-cluster-limit-exceeded` is failing to function because it attempts to call the Kubernetes API endpoint `/apis/org.eclipse.che/v2/checlusters`, but it returns a 401 error due to the token being expired.

**Comment by karatkep** [comment]
Hello @vinokurig, just wanted to check if you need anything else from my side to unblock your investigation.

**Comment by ibuziuk** [comment]
@karatkep could you please confirm that the issue is fixed with 7.97.0 release?

**Comment by karatkep** [comment]
@ibuziuk , We started receiving the `418 I'm a teapot` error as soon as we updated Eclipse Che to version 7.97.0 and stopped hourly restarts.

**Comment by tolusha** [comment]
@karatkep 
Could you provide che operator logs?
Did you get 418 immidiately or afte an hour ?

**Comment by vinokurig** [comment]
@karatkep 
> We started receiving the 418 I'm a teapot error as soon as we updated Eclipse Che to version 7.97.0 and stopped hourly restarts of che, che-gateway and che-dashboard pods.

Do you mean that Che stops working after an hour? Can you access Dashboard, start a workspace?

**Comment by vinokurig** [comment]
Did not see anything unusual after the service account token refresh in the `che-getaway` pod.

**Comment by karatkep** [comment]
Just to

> Did not see anything unusual after the service account token refresh in the `che-geteway` pod.

As I mentioned above, I see following error in `configbump` occurring 1h after the start:
```
E0111 13:29:19.199505       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: Unauthorized
```

**Comment by vinokurig** [comment]
@karatkep Can you access Dashboard, start a workspace having that?

**Comment by karatkep** [comment]
@vinokurig, yes, I can access the Dashboard, see all workspaces, and start a workspace. I am successfully redirected to the 'Starting workspace' page, but once all steps are completed, I am redirected to the IDE where I encounter a 418 error:
```
10.10.10.10:58724 - 1078721a6dfed6dfe08ac6caca30cd11 - Qwerty@qwe.com [2025/01/11 13:29:19] test-che.qwe.com GET / "/qwerty-qwe-com/test/3100/?tkn=eclipse-che" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" 418 0 0.001
```

**Comment by vinokurig** [comment]
Looks like this became an editor issue @dkwon17 WDYT?

**Comment by vinokurig** [comment]
Still can not reproduce, workspace starts even after the service account token refresh in the `che-gateway` pod.

**Comment by RomanNikitenko** [comment]
@karatkep 
could you share logs from editor's entrypoint?

OpenShift console => Workloads => Pods => Terminal for `tools` container => vi /checode/entrypoint-logs.txt

<img width="1161" alt="Image" src="https://github.com/user-attachments/assets/afaa5c74-2716-47ed-b231-47bacc6b0be6" />

**Comment by karatkep** [comment]
@RomanNikitenko, we use AKS (kubernetes). Could you please provide the name of the pod?

**Comment by RomanNikitenko** [comment]
@vinokurig 
do you have a running workspace on minikube to provide instructions how to find the pod?   

@karatkep 
About the container.
In my case it was `tools` as I started my workspace using devfile with `tools` container, see [here](https://github.com/RomanNikitenko/web-nodejs-sample/blob/main/devfile.yaml#L5).

In your case it could be another container name - it depends on your devfile and container that is used for starting editor (first container in your devfile or container with `controller.devfile.io/merge-contribution: true` attribute).

**Comment by vinokurig** [comment]
@karatkep to find the container logs you should select the user namespace:

![Image](https://github.com/user-attachments/assets/dd9b0902-4673-4a72-905a-022e4687eb2a)
then click the logs icon:

![Image](https://github.com/user-attachments/assets/555702cd-4084-4a3e-855a-ed3a7218a5bf)
and select the dev container:

![Image](https://github.com/user-attachments/assets/5d06a988-0e2a-4f8e-88e0-5af553322560)
