### ISSUE TITLE
Trying to build Eclipse Che 4.8.x on Ubuntu, I got exception "java.net.SocketException: Broken pipe"

### ISSUE THREAD

**Issue by mariosotil** [eclipse-che/che#2323]
I'm trying to build Eclipse 4.8.x in Ubuntu. The build fails on 

```
$ cd che
$ mvn -X clean install

[...]

2016-09-03 06:17:53,098[main]             [INFO ] [o.e.j.s.handler.ContextHandler 847]  - Stopped o.e.j.s.ServletContextHandler@1caa0244{/,null,UNAVAILABLE}
Tests run: 275, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.859 sec <<< FAILURE! - in TestSuite
stackIconShouldBeUploadedForUserOwner(org.eclipse.che.api.workspace.server.stack.StackServiceTest)  Time elapsed: 0.058 sec  <<< FAILURE!
java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:181)
        at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:115)
        at org.apache.http.entity.mime.content.FileBody.writeTo(FileBody.java:120)
        at org.apache.http.entity.mime.AbstractMultipartForm.doWriteTo(AbstractMultipartForm.java:150)
        at org.apache.http.entity.mime.AbstractMultipartForm.writeTo(AbstractMultipartForm.java:173)
        at org.apache.http.entity.mime.MultipartFormEntity.writeTo(MultipartFormEntity.java:97)
        at org.apache.http.entity.mime.MultipartEntity.writeTo(MultipartEntity.java:171)
        at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
        at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
        at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
        at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:265)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:203)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
        at com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:1764)
        at com.jayway.restassured.internal.http.HTTPBuilder.post(HTTPBuilder.java:333)
        at com.jayway.restassured.internal.http.HTTPBuilder$post$2.call(Unknown Source)
        at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1067)
        at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
        at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at com.jayway.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:31)
        at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
        at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:49)
        at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
        at com.jayway.restassured.internal.RequestSpecificationImpl.invokeFilterChain(RequestSpecificationImpl.groovy:956)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
        at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
        at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1414)
        at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
        at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
        at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:154)
        at com.jayway.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
        at org.eclipse.che.api.workspace.server.stack.StackServiceTest.stackIconShouldBeUploadedForUserOwner(StackServiceTest.java:578)

[...]

[INFO] Che Core :: API :: Workspace ....................... FAILURE [ 17.516 s]
```

The full log is here

[eclipse-che-ubuntu-build-log.zip](https://github.com/eclipse/che/files/453308/eclipse-che-ubuntu-build-log.zip)

**My computer's configuration** is
- Ubuntu 16.04.1
- Oracle Java 1.8.0_101
- Docker 1.12.1
- docker-machine 0.7.0 a650a40
- Maven 3.3.9
- Bower 1.7.9
- Gulp CLI version - 1.2.2
- I added the `gwt-dev` dependency, and removed all `provided` scopes on `assembly-ide-war/pom.xml` 

May you help me, please?

**Comment by mariosotil** [comment]
I installed Eclipse for Che Developers with Yatta, and I could build it. Sorry for bother you.

**Comment by mariosotil** [comment]
I found a workaround of this using 'Eclipse for Che Developers', but on second thought I will need to deploy Eclipse Che using maven only.

How could we build Eclipse Che using maven only? What am I missing?

**Comment by TylerJewell** [comment]
Can you checkout the `4.7.0` tag and rebuild?  The master code base is unstable right now due to a large number of merges over the past couple days.

**Comment by mariosotil** [comment]
I tried and the build failed again with the same error. I'm restarting the computer to try again.

**Comment by TylerJewell** [comment]
I am spinning up an Ubuntu image at digital ocean to take a look.

**Comment by TylerJewell** [comment]
@mariosotil - I did the following, and Che was good on Ubuntu.  I created a small image at digital ocean with Ubuntu 16 on it.

```
apt install default-jdk
apt install maven
apt install docker.io
git clone http://github.com/eclipse/che
cd che
git checkout 4.7.0
cd /assembly/assembly-main
mvn clean install

# I got a clean binary build at this point.
# Then I tested running Che
# First test - running Che using launcher
export CHE_VERSION=4.7.0
export CHE_HOST_IP=<ip-of-my-node>
git checkout master
./che.sh start

# This gave me Che running at http://<ip-of-my-node:8080>
# I stopped it and then tested running che with a local binary that I built instead
./che.sh stop
export CHE_LOCAL_BINARY=/root/che/assembly/assembly-main/target/eclipse-che-4.7.0/eclipse-che-4.7.0/
./che.sh start
### Che boots up and used the version that I just compiled.
```

**Comment by mariosotil** [comment]
Well, I restarted the computer and it seems like this time it's working... Right now, Maven is building `Che Dashboard :: Web App 4.7.0`. Let me wait until it finish to close this issue.

Meanwhile, quick question: why would Maven take so much time to build the Dashboard? It takes almost 15 minutes just in that step.  It seems like, every building, Maven downloads again the same libraries. This is that part of the log.

```
$ cd che
$ git checkout 4.7.0
$ mvn -X clean install

[...]
[...]

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Che Dashboard :: Web App 4.7.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ che-dashboard-war ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:parse-version (parse-version) @ che-dashboard-war ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ che-dashboard-war ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java-version) @ che-dashboard-war ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven-version) @ che-dashboard-war ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (distribution-management-used) @ che-dashboard-war ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (no-distribution-management-at-all) @ che-dashboard-war ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (dependency) @ che-dashboard-war ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (ban-bad-dependencies) @ che-dashboard-war ---
[INFO] 
[INFO] --- maven-sortpom-plugin:2.3.0:verify (default) @ che-dashboard-war ---
[INFO] Verifying file /home/ubuntu/eclipse-che/che/dashboard/pom.xml
[INFO] 
[INFO] --- license-maven-plugin:2.10:check (check-headers) @ che-dashboard-war ---
[INFO] Checking licenses...
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/assets/fonts/open-sans-latin.woff2
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/assets/fonts/open-sans-latin-ext.woff2
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/assets/images/icon-on-prem.png
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/assets/images/icon-saas.png
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/assets/svg/README.MD
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/assets/branding/product.json
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/app/colors/che-colors.json
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/app/colors/che-color.constant.js.template
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/app/colors/che-output-colors.constant.js.template
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/app/colors/che-output-colors.json
[WARNING] Unknown file extension: /home/ubuntu/eclipse-che/che/dashboard/src/app/proxy/proxy-settings.constant.js.template
[WARNING] Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ che-dashboard-war ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ubuntu/eclipse-che/che/dashboard/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ che-dashboard-war ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (compile) @ che-dashboard-war ---
[INFO] Executing tasks

main:
     [exec] npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
     [exec] npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
     [exec] npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
     [exec] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
     [exec] npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
     [exec] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
     [exec] npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
     [exec] npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
     [exec] WARN engine svg-pathdata@1.0.0: wanted: {"node":"0.10.*"} (current: {"node":"4.2.6","npm":"3.5.2"})
```

**Comment by TylerJewell** [comment]
We would have to get other people to take a look at the dashboard section.  The dashboard is written in JavaScript and EcmaScript, requiring a different configuration to build properly.  We have our che-dev docker container which has everything setup properly to do builds so that you do not have to reconfigure your system.

But you should not need to rebuild all modules.  You should only go into the module that you are customizing and build that with a mvn clean install.  And then if you want just an assembly, build the assembly to get the latest modules that you have built and any others from our nexus.

@ashumilova

**Comment by mariosotil** [comment]
Well, in short, it was necessary to change to 4.7.0 and restart the Ubuntu computer. Thank you for you help!
