### ISSUE TITLE
Java errors - RHEL 7.2 Maipo 

### ISSUE THREAD

**Issue by rdkapa** [eclipse-che/che#2486]
I installed che-server through Docker platform and when I want to start an workspace  I received the following message: " Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
"
I modified the value of machine.ws-agent.max_start_time_ms but the issue still persist. 

**Errors:**

2016-09-19 10:15:26,810[kspaceManager-0]  [ERROR] [.c.a.a.s.w.WsAgentLauncherImpl 115]  - Fail pinging ws agent. Workspace ID:workspace2444pky93gthru2u. Url:http://172.17.0.1:32805/wsagent/ext/. Timestamp:{}
2016-09-19 10:15:28,137[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 666]    - Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:261) ~[che-core-api-workspace-4.7.2.jar:4.7.2]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:650) ~[che-core-api-workspace-4.7.2.jar:4.7.2]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.7.2.jar:4.7.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92-internal]

**Che version:**    

INFO: ---------------------------------------
INFO: ---------    CLI DEBUG INFO    --------
INFO: ---------------------------------------
INFO:
INFO: ---------  PLATFORM INFO  -------------
INFO: CLI DEFAULT PROFILE       = not set
INFO: CHE_VERSION               = latest
INFO: CHE_UTILITY_VERSION       = nightly
INFO: DOCKER_INSTALL_TYPE       = native
INFO: DOCKER_HOST_IP            = 172.17.0.1
INFO: IS_NATIVE                 = YES
INFO: IS_WINDOWS                = NO
INFO: IS_DOCKER_FOR_WINDOWS     = NO
INFO: IS_DOCKER_FOR_MAC         = NO
INFO: IS_BOOT2DOCKER            = NO
INFO: HAS_DOCKER_FOR_WINDOWS_IP = NO
INFO: IS_MOBY_VM                = NO
INFO: HAS_CHE_ENV_VARIABLES     = NO
INFO: HAS_TEMP_CHE_PROPERTIES   = NO
INFO: HAS_INTERACTIVE           = YES
INFO: HAS_PSEUDO_TTY            = YES

**OS and version:** Red Hat Enterprise Linux Server release 7.2 (Maipo)
**Docker version:** 1.11.2-cs5  
**Che install:**   Docker container - image "codenvy/che-server:latest"

**Comment by TylerJewell** [comment]
It looks like you are having an issue with either the Che server connecting to the workspace agent, or the browser. Given the configuration of your system, there may be extra parameters you need to set to make these connections valid.  See:  https://eclipse-che.readme.io/docs/networking#connectivity

Also - you can run `che info --networking` for another set of tests.

**Comment by ghost** [comment]
@TylerJewell definitely not browser. It's server that fails to reach ws agent. There can be at least 2 reasons:
- ws agent never starts because it cannot reach wsmaster
- ws agent successfully starts but wsmaster indeed cannot reach it using docker0 network interface IP

I suspect this is RHEL specific issue. 

@rdkapa can you provide both ws agent and server logs?

**Comment by rdkapa** [comment]
```
This is the che info --networking export: 

[root@test ~]# che info --networking
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
INFO:
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: Browser             => Workspace Agent (Hostname)   : Connection succeeded
INFO: Browser             => Workspace Agent (External IP): Connection succeeded
INFO: Che Server          => Workspace Agent (External IP): Connection failed
INFO: Che Server          => Workspace Agent (Internal IP): Connection succeeded

And this  the server log:

Listening for transport dt_socket at address: 4403

Listening for transport dt_socket at address: 4403

2016-09-19 14:51:15,262[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32

2016-09-19 14:51:15,262[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32

2016-09-19 14:51:15,265[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC

2016-09-19 14:51:15,265[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC

2016-09-19 14:51:15,265[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0

2016-09-19 14:51:15,265[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0

2016-09-19 14:51:15,266[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux

2016-09-19 14:51:15,266[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux

2016-09-19 14:51:15,266[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-327.4.5.el7.x86_64

2016-09-19 14:51:15,266[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-327.4.5.el7.x86_64

2016-09-19 14:51:15,267[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64

2016-09-19 14:51:15,267[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64

2016-09-19 14:51:15,272[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_45/jre

2016-09-19 14:51:15,272[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_45/jre

2016-09-19 14:51:15,272[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_45-b14

2016-09-19 14:51:15,272[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_45-b14

2016-09-19 14:51:15,273[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation

2016-09-19 14:51:15,273[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation

2016-09-19 14:51:15,273[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent

2016-09-19 14:51:15,273[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent

2016-09-19 14:51:15,273[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent

2016-09-19 14:51:15,273[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent

2016-09-19 14:51:15,274[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties

2016-09-19 14:51:15,274[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties

2016-09-19 14:51:15,274[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager

2016-09-19 14:51:15,274[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager

2016-09-19 14:51:15,275[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m

2016-09-19 14:51:15,275[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m

2016-09-19 14:51:15,275[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m

2016-09-19 14:51:15,275[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m

2016-09-19 14:51:15,275[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom

2016-09-19 14:51:15,275[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom

2016-09-19 14:51:15,276[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs

2016-09-19 14:51:15,276[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs

2016-09-19 14:51:15,276[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n

2016-09-19 14:51:15,276[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n

2016-09-19 14:51:15,277[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote

2016-09-19 14:51:15,277[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote

2016-09-19 14:51:15,277[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false

2016-09-19 14:51:15,277[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false

2016-09-19 14:51:15,277[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false

2016-09-19 14:51:15,277[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent

2016-09-19 14:51:15,278[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent

2016-09-19 14:51:15,279[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp

2016-09-19 14:51:15,279[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp

2016-09-19 14:51:15,488[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-4401"]

2016-09-19 14:51:15,488[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-4401"]

2016-09-19 14:51:15,507[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read

2016-09-19 14:51:15,507[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read

2016-09-19 14:51:15,510[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 644 ms

2016-09-19 14:51:15,510[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 644 ms

2016-09-19 14:51:15,583[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server

2016-09-19 14:51:15,583[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server

2016-09-19 14:51:15,584[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina

2016-09-19 14:51:15,584[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina

2016-09-19 14:51:15,585[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32

2016-09-19 14:51:15,585[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32

2016-09-19 14:51:15,673[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/ws-agent/webapps/wsagent.war

2016-09-19 14:51:15,673[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/ws-agent/webapps/wsagent.war

Mon Sep 19 14:51:23 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started

Mon Sep 19 14:51:23 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started

2016-09-19 14:51:23,359[s polled Thread]  [INFO ] [o.e.c.p.m.server.rmi.RmiClient 130]  - Port/Name:5263/MavenRemoteServerImpl1896def0

2016-09-19 14:51:23,359[s polled Thread]  [INFO ] [o.e.c.p.m.server.rmi.RmiClient 130]  - Port/Name:5263/MavenRemoteServerImpl1896def0





2016-09-19 14:51:25,395[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.LoEventListener 48]   - Subscribing to event service: class org.eclipse.che.api.vfs.impl.file.event.LoEventListener

2016-09-19 14:51:25,395[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.LoEventListener 48]   - Subscribing to event service: class org.eclipse.che.api.vfs.impl.file.event.LoEventListener

2016-09-19 14:51:25,399[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 55]   - Starting virtual file system event service: LoEventService

2016-09-19 14:51:25,399[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 55]   - Starting virtual file system event service: LoEventService

2016-09-19 14:51:25,402[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 55]   - Starting virtual file system event service: HiEventService

2016-09-19 14:51:25,402[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 55]   - Starting virtual file system event service: HiEventService

2016-09-19 14:51:25,530[rest.WSClient-0]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/wsmaster/api/eventbus/?token=dummy_token. 

2016-09-19 14:51:25,530[rest.WSClient-0]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/wsmaster/api/eventbus/?token=dummy_token. 

2016-09-19 14:51:25,788[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/ws-agent/webapps/wsagent.war has finished in 10,113 ms

2016-09-19 14:51:25,788[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/ws-agent/webapps/wsagent.war has finished in 10,113 ms

2016-09-19 14:51:25,791[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory /home/user/che/ws-agent/webapps/ROOT

2016-09-19 14:51:25,791[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory /home/user/che/ws-agent/webapps/ROOT

2016-09-19 14:51:25,874[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory /home/user/che/ws-agent/webapps/ROOT has finished in 83 ms

2016-09-19 14:51:25,874[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory /home/user/che/ws-agent/webapps/ROOT has finished in 83 ms

2016-09-19 14:51:25,881[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-4401"]

2016-09-19 14:51:25,881[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-4401"]

2016-09-19 14:51:25,887[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 10375 ms

2016-09-19 14:51:25,887[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 10375 ms
```

**Comment by ghost** [comment]
@rdkapa can you run the following:

`export CHE_HOST_IP=${eth0_IP}` where `${eth0_IP}` is IP of your eth0 network interface. You may try 127.0.0.1 as well.

The start che again.

**Comment by rdkapa** [comment]
@eivantsov  

That`s work. 

Thank you!
