### ISSUE TITLE
"undefined" workspace name in modal dialog in case of error of starting workspace in Dashboard

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#2492]
**Reproduction Steps:**
1. Create workspace **workspace1** with _RAM_ out of system resources.
2. Start workspace.

**Expected behavior:**
Modal dialog with error message:

> Unable to start workspace. Error when trying to start the workspace: workspace1.

**Observed behavior:**
Modal dialog with **"undefined"** workspace name inside:

> Unable to start workspace. Error when trying to start the workspace: undefined.
> ![undefined-workspace-name_2016-09-19](https://cloud.githubusercontent.com/assets/1197777/18639469/b2da9674-7e9c-11e6-848b-54d95016b0ee.png)

WebSocket messages:

> {"headers":[{"name":"x-everrest-websocket-channel","value":"workspace:workspace8fn7wdpy7oqedsny:machines_statuses"},{"name":"x-everrest-websocket-message-type","value":"none"}],"responseCode":0,"body":"{\"machineId\":\"machinegewvl0lsmw21uin5\",\"eventType\":\"ERROR\",\"dev\":true,\"machineName\":\"dev-machine\",\"workspaceId\":\"workspace8fn7wdpy7oqedsny\"}"}
> 
> {"headers":[{"name":"x-everrest-websocket-channel","value":"workspace:workspace8fn7wdpy7oqedsny"},{"name":"x-everrest-websocket-message-type","value":"none"}],"responseCode":0,"body":"{\"error\":\"Start of environment default failed. Error: The system is out of resources. Please contact your system admin.\",\"eventType\":\"ERROR\",\"workspaceId\":\"workspace8fn7wdpy7oqedsny\"}"}

WS Master error log:

```
2016-09-29 08:59:01,919[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 634]    - Start of environment workspace1 failed. Error: The system is out of resources. Please contact your
 system admin.
org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: The system is out of resources. Please contact your system admin.
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:277) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:618) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$121/393050409.run(Unknown Source) [che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M3.jar:5.0.0-M3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.eclipse.che.api.core.ServerException: The system is out of resources. Please contact your system admin.
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:790) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:242) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:246) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        ... 6 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: The system is out of resources. Please contact your system admin.
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:879) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:725) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        ... 8 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: The system is out of resources. Please contact your system admin.
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:326) ~[che-plugin-docker-machine-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$8(CheEnvironmentEngine.java:699) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine$$Lambda$131/538914490.startMachine(Unknown Source) ~[na:na]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:827) ~[che-core-api-workspace-5.0.0-M3.jar:5.0.0-M3]
        ... 9 common frames omitted
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: The system is out of resources. Please contact your system admin.
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:153) ~[codenvy-machine-hosted-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:369) ~[che-plugin-docker-machine-5.0.0-M3.jar:5.0.0-M3]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:263) ~[che-plugin-docker-machine-5.0.0-M3.jar:5.0.0-M3]
        ... 12 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: The system is out of resources. Please contact your system admin.
        at com.codenvy.swarm.client.SwarmDockerConnector.decorateMessage(SwarmDockerConnector.java:104) ~[codenvy-machine-hosted-5.0.0-M3.jar:5.0.0-M3]
        at com.codenvy.swarm.client.SwarmDockerConnector.buildImage(SwarmDockerConnector.java:87) ~[codenvy-machine-hosted-5.0.0-M3.jar:5.0.0-M3]
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:142) ~[codenvy-machine-hosted-5.0.0-M3.jar:5.0.0-M3]
        ... 14 common frames omitted

```

**Che version:**     5.0.0-M1
**OS and version:** Ubuntu OS
**Che install:**    Codenvy on-prem

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
  It is 5.0.0-M1 specific problem.
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by olexii4** [comment]
2h
