### ISSUE TITLE
In Windows 10, sometimes workspaces hang when being stopped, and then when you start them again, they malfunction

### ISSUE THREAD

**Issue by jcao219** [eclipse-che/che#264]
Sometimes, it hangs when you stop a workspace.

So I restart the host computer, and I restart Che.

I'm able to successfully start the workspace, but it looks like this:

http://i.imgur.com/MVIXmzM.png

Notice no Output tab on the bottom, and the dropdown box of Run Commands doesn't work.

When I stop the workspace again, it succeeds.  Afterwards, if I restart the workspace, everything works normally.

**Comment by ghost** [comment]
Do you natively run Che on Windows or do you run it in a Docker container?

What are the steps to reproduce? It is possible that a Docker VM becomes unresponsive after some idle time.

**Comment by jcao219** [comment]
Natively.

The steps are:
1. Open a workspace.  Maybe do some work.
2. In the dashboard, close the workspace.  Often, it will not close, and you have to forcibly stop Che -- the CLI will show something like:

```
2016-02-03 05:31:21,874[kspaceManager-2]  [INFO ] [o.e.c.a.m.s.MachineManager 856]      - Destroying machine [ws = workspacedcsy2kzcis7uf18x: env = wksp-71o2: machine = ws-machine]
^CTerminate batch job (Y/N)? 2016-02-03 05:33:16,348[Thread-3]         [INFO ] [o.a.c.http11.Http11NioProtocol 484]  - Pausing ProtocolHandler ["http-nio-8080"]
2016-02-03 05:33:16,413[Thread-3]         [INFO ] [o.a.c.core.StandardService 495]      - Stopping service Catalina
2016-02-03 05:33:16,474[ost-startStop-2]  [INFO ] [o.e.c.a.core.util.FileCleaner 74]    - File cleaner is stopped
2016-02-03 05:33:16,482[ost-startStop-2]  [INFO ] [o.e.c.a.m.s.MachineManager 856]      - Destroying machine [ws = workspacedcsy2kzcis7uf18x: env = wksp-71o2: machine = ws-machine]

^CTerminate batch job (Y/N)? Y
```
1. Restart Che if needed, and re-open workspace.
2. Sometimes, the issue will occur.  If not, stop the workspace again and restart it.  The issue can usually be reproduced consistently.

After I successfully reproduce the issue, simply stopping the workspace again and restarting it will fix it.

**Comment by ghost** [comment]
I'll test it on Windows 10 and 8 and let you know if I manage to reproduce it.

**Comment by ghost** [comment]
Installed Java 1.8.0.71, maven 3.3.9, Docker ToolBox (1.9.1, build master : cef800b), VirtualBox (5.0.12 r104815), compiled Che, ran che.bat, create a workspace, stopped it, ran it again. Stopped Che server. Re-ran che.bat. Workspace and its projects are there.

Did you try to remove default machine and run che.bat? It will recreate the VM. If the issues persist I'll provide you with steps to get ws-agent logs and check health of docker containers inside a VM.

**Comment by jcao219** [comment]
I never removed the default machine.

The issue never seems to occur unless if I do a maven build.  After one or more maven builds, often the workspace will fail to stop and will just hang.

**Comment by TylerJewell** [comment]
@jcao219 In your statement above, you said "in the dashboard, close the workspace".  Can you elaborate on what this is?  Are you destroying it, or just stopping it?

**Comment by jcao219** [comment]
I just click Stop

**Comment by ghost** [comment]
This is what I did - stopping workspace both from Dashboard and IDE.

Take a look at this thread, maybe it is a fix for you as well - https://github.com/codenvy/che/issues/253

**Comment by jcao219** [comment]
Docker version 1.9.1, build a34a1d5

VirtualBox: Version 5.0.12 r104815

**Comment by jcao219** [comment]
My workplace now fails to start:

```
[STDOUT] 2016-02-04 08:45:51,824[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2016-02-04 08:45:51,844[main]             [INFO ] [o.a.catalina.startup.Catalina 587]   - Initialization processed in 6620 ms
[STDOUT] 2016-02-04 08:45:52,285[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
[STDOUT] 2016-02-04 08:45:52,286[main]             [INFO ] [o.a.c.core.StandardService 433]      - Starting service Catalina
[STDOUT] 2016-02-04 08:45:52,287[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.28
[STDOUT] 2016-02-04 08:45:52,976[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[ERROR] Workspace agent is not responding. Workspace workspacedcsy2kzcis7uf18x will be stopped
```

```
2016-02-04 03:49:35,096[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 17146 ms
2016-02-04 03:51:24,204[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 167]      - Creating machine [ws = workspacedcsy2kzcis7uf18x: env = wksp-71o2: machine = ws-machine]
2016-02-04 03:52:30,776[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Workspace agent is not responding. Workspace workspacedcsy2kzcis7uf18x will be stopped
org.eclipse.che.api.machine.server.exception.MachineException: Workspace agent is not responding. Workspace workspacedcsy2kzcis7uf18x will be stopped
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:396) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:168) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:451) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:319) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:145) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$9(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-beta-13.jar:4.0.0-beta-13]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Workspace agent is not responding. Workspace workspacedcsy2kzcis7uf18x will be stopped
        at org.eclipse.che.api.machine.server.WsAgentLauncherImpl.startWsAgent(WsAgentLauncherImpl.java:104) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50) ~[guice-4.0.jar:na]
        at com.sun.proxy.$Proxy52.startWsAgent(Unknown Source) ~[na:na]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:370) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        ... 11 common frames omitted
```

**Comment by ghost** [comment]
Can you provide ws-agent logs? You see them when a workspace boots.

What you can also do is go to `/conf/che.properties` and override the following property:

`machine.ws_agent.max_start_time_ms=60000`

Increase it and re run Che.

**Comment by jcao219** [comment]
```
[STDOUT] Archive:  /mnt/che/ws-agent.zip
[STDOUT]    creating: /home/user/che/ws-agent/conf/
[STDOUT]   inflating: /home/user/che/ws-agent/conf/server.xml  
[STDOUT]   inflating: /home/user/che/ws-agent/LICENSE-mit.txt  
[STDOUT]    creating: /home/user/che/ws-agent/bin/
[STDOUT]   inflating: /home/user/che/ws-agent/bin/setenv.sh  
[STDOUT]    creating: /home/user/che/ws-agent/endorsed/
[STDOUT]    creating: /home/user/che/ws-agent/lib/
[STDOUT]    creating: /home/user/che/ws-agent/logs/
[STDOUT]    creating: /home/user/che/ws-agent/temp/
[STDOUT]    creating: /home/user/che/ws-agent/work/
[STDOUT]   inflating: /home/user/che/ws-agent/bin/bootstrap.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/catalina.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/catalina.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/commons-daemon.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/configtest.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/configtest.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/daemon.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/digest.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/digest.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/setclasspath.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/setclasspath.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/shutdown.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/shutdown.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/startup.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/startup.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/tomcat-juli.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/tool-wrapper.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/tool-wrapper.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/version.bat  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/version.sh  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/catalina.policy  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/catalina.properties  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/context.xml  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/logback-access-localhost.xml  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/logback.xml  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/logging.properties  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/tomcat-users.xsd  
[STDOUT]   inflating: /home/user/che/ws-agent/conf/web.xml  
[STDOUT]   inflating: /home/user/che/ws-agent/endorsed/activation-1.1.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/endorsed/jul-to-slf4j-1.7.6.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/endorsed/log4j-over-slf4j-1.7.6.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/endorsed/logback-classic-1.1.2.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/endorsed/logback-core-1.1.2.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/endorsed/mail-1.4.4.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/endorsed/slf4j-api-1.7.6.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/annotations-api.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/catalina-ant.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/catalina-ha.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/catalina-storeconfig.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/catalina-tribes.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/catalina.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/ecj-4.4.2.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/el-api.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/jasper-el.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/jasper.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/jsp-api.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/logback-access-1.1.2.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/servlet-api.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-api.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-catalina-jmx-remote-8.0.28.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-coyote.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-dbcp.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-i18n-es.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-i18n-fr.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-i18n-ja.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-jdbc.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-jni.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-util-scan.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-util.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/tomcat-websocket.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/lib/websocket-api.jar  
[STDOUT]   inflating: /home/user/che/ws-agent/LICENSE  
[STDOUT]   inflating: /home/user/che/ws-agent/LICENSE-logback.txt  
[STDOUT]   inflating: /home/user/che/ws-agent/LICENSE-slf4j.txt  
[STDOUT]   inflating: /home/user/che/ws-agent/NOTICE  
[STDOUT]   inflating: /home/user/che/ws-agent/RELEASE-NOTES  
[STDOUT]   inflating: /home/user/che/ws-agent/RUNNING.txt  
[STDOUT]   inflating: /home/user/che/ws-agent/temp/safeToDelete.tmp  
[STDOUT]   inflating: /home/user/che/ws-agent/bin/setenv.bat  
[STDOUT]    creating: /home/user/che/ws-agent/webapps/
[STDOUT]   inflating: /home/user/che/ws-agent/webapps/ide.war  
[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2016-02-06 11:43:37,843[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.28
[STDOUT] 2016-02-06 11:43:37,847[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 7 2015 18:25:21 UTC
[STDOUT] 2016-02-06 11:43:37,848[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.28.0
[STDOUT] 2016-02-06 11:43:37,853[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2016-02-06 11:43:37,904[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.1.13-boot2docker
[STDOUT] 2016-02-06 11:43:37,928[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2016-02-06 11:43:37,963[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_45/jre
[STDOUT] 2016-02-06 11:43:37,963[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_45-b14
[STDOUT] 2016-02-06 11:43:37,964[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2016-02-06 11:43:37,964[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2016-02-06 11:43:37,965[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2016-02-06 11:43:38,003[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2016-02-06 11:43:38,007[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2016-02-06 11:43:38,012[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2016-02-06 11:43:38,058[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
[STDOUT] 2016-02-06 11:43:38,073[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2016-02-06 11:43:38,083[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2016-02-06 11:43:38,088[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2016-02-06 11:43:38,142[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2016-02-06 11:43:38,143[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2016-02-06 11:43:38,143[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2016-02-06 11:43:38,144[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2016-02-06 11:43:38,145[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2016-02-06 11:43:38,145[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2016-02-06 11:43:38,146[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2016-02-06 11:43:40,117[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 424]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-02-06 11:43:40,613[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2016-02-06 11:43:40,647[main]             [INFO ] [o.a.catalina.startup.Catalina 587]   - Initialization processed in 6473 ms
[STDOUT] 2016-02-06 11:43:41,082[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
[STDOUT] 2016-02-06 11:43:41,093[main]             [INFO ] [o.a.c.core.StandardService 433]      - Starting service Catalina
[STDOUT] 2016-02-06 11:43:41,105[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.28
[STDOUT] 2016-02-06 11:43:41,736[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[ERROR] Workspace agent is not responding. Workspace workspacedcsy2kzcis7uf18x will be stopped

```

**Comment by jcao219** [comment]
Alright, I restarted the virtual machine `default` and now I was able to get the workspace to start normally.  Let me try to reproduce the original issue.

I find that the biggest issue is, I'm not able to stop the workspace after I complete a `mvn install`.

-- Issue reproduced.  The starting-workspace page normally produces a log, but this time no log appeared.  I waited to see on the host machine's CLI the message that the Machine was created successfully.  Then, the workspace loaded normally.  Afterwards, I went back to the dashboard, and clicked on my project, and clicked Open in IDE, and the malfunctioning UI loaded (with only one tab on the bottom instead of three).

**Comment by jcao219** [comment]
Reproduced it again.  It's getting rarer, now that I've restarted the Virtual Machine.  I'll include a video.

https://youtu.be/hwh-FsDH9YY

It seems to happen whenever I change Chrome tabs during the loading of the workspace page.

**Comment by ghost** [comment]
Can you reproduce it in an incognito mode?

Also, you say you cannot stop a workspace, but I never saw you attempted to do so in the video.

Also, when you have a malfunctioning UI, try F5 to see if it fixes it.

You may also want to try the latest RC build to see if you can reproduce this weird behavior.

**Comment by ShivenGupta** [comment]
I am having the same exact problem. I can create a workspace, then I try stopping it. (By pressing "Stop"). This works. If I make a new Project and run it, then it also gets stuck at "Stopping" when clicking "Stop". The CMD window just reads "- Destroying machine". If i just close CMD, and restart Che, there are no workspaces in the "All Workspaces" section.

I do not think this is a problem with my system speed, because after increasing the CPU speed, che starts in 11000 ms.

**Comment by ghost** [comment]
@jcao219 can you still repeatedly reproduce the issue?

I have tried it on 2 Win machines (8 and 10) - cannot reproduce.
