### ISSUE TITLE
File is opening with error

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2729]
**Reproduction Steps:**
1. Create workspace from java stack and open it
2. Create project
3. Open any file

**Observed behavior:**
in dev-machine console:
`2016-10-07 10:03:49,425[nio-4401-exec-7]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2016-10-07 10:03:49
java.lang.NullPointerException: null
    at org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl.findServer(LanguageServerRegistryImpl.java:91) ~[che-core-api-languageserver-5.0.0-M5-SNAPSHOT.jar:5.0.0-M5-SNAPSHOT]
    at org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl.findServer(LanguageServerRegistryImpl.java:84) ~[che-core-api-languageserver-5.0.0-M5-SNAPSHOT.jar:5.0.0-M5-SNAPSHOT]
    at org.eclipse.che.api.languageserver.service.TextDocumentService.getServer(TextDocumentService.java:296) ~[che-core-api-languageserver-5.0.0-M5-SNAPSHOT.jar:5.0.0-M5-SNAPSHOT]
    at org.eclipse.che.api.languageserver.service.TextDocumentService.didOpen(TextDocumentService.java:267) ~[che-core-api-languageserver-5.0.0-M5-SNAPSHOT.jar:5.0.0-M5-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) ~[everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) ~[everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) ~[everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297) ~[everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233) ~[everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) ~[everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) ~[everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61) [everrest-core-1.13.1.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
    at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
    at org.eclipse.che.filters.EnvironmentInitializationFilter.doFilter(EnvironmentInitializationFilter.java:54) [wsagent-local-5.0.0-M5-SNAPSHOT.jar:5.0.0-M5-SNAPSHOT]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
    at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:301) [catalina.jar:8.0.32]
    at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169) [catalina.jar:8.0.32]
    at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59) [che-core-api-core-5.0.0-M5-SNAPSHOT.jar:5.0.0-M5-SNAPSHOT]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.32]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.32]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.32]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.32]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.32]
    at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.32]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [catalina.jar:8.0.32]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-coyote.jar:8.0.32]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-coyote.jar:8.0.32]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.32]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.32]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.32]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]`
![npe](https://cloud.githubusercontent.com/assets/8051404/19186888/12ff49c6-8c91-11e6-9ed5-25d60548d368.png)

**Che version:**   5.0.0-M5-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**   Docker container

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by riuvshin** [comment]
@vparfonov seems this is related to LS right?

**Comment by AndreyChizhikov** [comment]
@riuvshin Yes
