### ISSUE TITLE
Error "Certificates are required for https connection" in Eclipse Che 

### ISSUE THREAD

**Issue by mariosotil** [eclipse-che/che#2774]
Hi. I'm having a problem today. I have all the configuration needed for Mac (~/.bash_profile, $JAVA_HOME, etc.), I was working with Eclipse Che without problem since more than one month, and this afternoon it's broken with the same problem.

```
2016-10-12 21:00:15,091[ost-startStop-1]  [INFO ] [o.e.che.inject.CheBootstrap 182]     - Analyzing che.properties
Exception in thread "DockerInstanceStopDetector-0" java.lang.IllegalArgumentException: Certificates are required for https connection.
    at org.eclipse.che.plugin.docker.client.connection.TcpConnection.<init>(TcpConnection.java:41)
    at org.eclipse.che.plugin.docker.client.connection.DockerConnectionFactory.openConnection(DockerConnectionFactory.java:52)
    at org.eclipse.che.plugin.docker.client.DockerConnector.getEvents(DockerConnector.java:698)
    at org.eclipse.che.plugin.docker.machine.DockerInstanceStopDetector.lambda$detectContainersEvents$0(DockerInstanceStopDetector.java:113)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Environment:
- Mac OS X El Capitan
- Eclipse Che 4.7
- Docker Version 1.12.1 (build: 12133)
- VirtualBox 5.1.6 r110634 (Qt5.5.1)

**Comment by TylerJewell** [comment]
1. Can you provide the details of how you start Che either luanching container or CLI along with any che.properties configured or CHE_ environment variables set?
2. Is there a reason you are using vbox here as opposed to Docker for Mac?

**Comment by mariosotil** [comment]
I could solve it reinstalling Docker for Mac. It seems that something was broken because an update or who knows what :-( 

Anyway, thank you for your answer.
