### ISSUE TITLE
Specifying local docker image in stacks.json

### ISSUE THREAD

**Issue by SanthoshHari912** [eclipse-che/che#2806]
Am using Che as IDE Server. I want to add a custom stack through stacks.json. In the new json Object which I have added,  have specified a local docker image.

I have created a docker image locally say 'my_components', and in the json object have specified source as
 "source": {
   "type": "image",
   "origin": "my_components"
}

After restarting the CHE docker container. The dashboard is empty. If I remove the custom json Object from stacks.json it shows the default dashboard. Can some one guide me how do I specify a local docker images as source in stacks.json

Thanks
Santhosh

**Comment by TylerJewell** [comment]
Howdy - I think @ashumilova or @slemeur will assign someone to help take a look at this and answer your questions.  Also, you may want to try the nightly builds of Che - there is a stack editor in the dashboard that makes it easier to add / remove stacks.

https://eclipse-che.readme.io/v4.7/docs/stack

**Comment by slemeur** [comment]
@SanthoshHari912 Could you tell us a bit more?

What is the version of Che you are running? 
Could you give us the whole Stack JSON Object you registered please?

If you are on the nightly builds, you can read the following documentation:
https://eclipse-che.readme.io/v5.0/docs/stacks#section-configuring-stacks

**Comment by ghost** [comment]
@SanthoshHari912 Once you figure out how to add a stack, you need to set this property to false if you want to use a loacl docker image - https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L116

**Comment by SanthoshHari912** [comment]
@TylerJewell I tried pulling  codenvy/che-server:nightly for setting up Che Server and am not able to find Stacks Editor in Dashboard.

**Comment by SanthoshHari912** [comment]
@slemeur  , @eivantsov  Thank you pulling from the codenvy/che-server:nightly helped me to view the stack on dashboard. Stack Editor is very easy to edit as well.

Now I face some issues setting up the workspace agent. Where can I find the complete logs as in the editor am not able to get the complete log. 

Please guide me

Regards
Santhosh

**Comment by TylerJewell** [comment]
The logs for the workspace agent appear when the workspace is being loaded and there is a download link that shows up which lets you download those logs.  What our engineers do, however, is to `docker exec` into the container created by Che.  You can do something like `docker exec -it <container> /bin/bash` which will let you login to the container.  Or you can go into the terminal.  You can then find the Tomcat that is running the agent in that server and inspect its logs there, which I believe is in `/home/tomcat`.

**Comment by SanthoshHari912** [comment]
@TylerJewell Am facing errors since the ports are already in use. My Docker image has a tomcat with a js library.
Since che already has a tomcat , what would be the ideal way ,
1. To reuse the tomcat container in Che
2.  To create a new tomcat container (specific to the stack)
   In case if new container should be created can we control the ports in the dockerfile?

**Comment by TylerJewell** [comment]
You should probably create a new recipe that is a container that will be launched by Che.  When you create a new recipe you can add EXPOSE commands to the Dockerfile. Those ports will then be externally exposed and available.  If your internal servers bind themselves to those ports, then Docker provides a mapping of those services to the outside world.

**Comment by SanthoshHari912** [comment]
I always end up getting this error 
Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.

The docker image i have used locally has a tomcat image in it. I have changed the ports of Eclipse CHE from default to 9092.

In the  logs I get the following error

2016-10-24 10:18:48,248[kspaceManager-0]  [ERROR] [.c.a.w.s.l.WsAgentLauncherImpl 127]  - Fail pinging ws agent. Workspace ID:workspace8vr5fqxwzflpzut5. Url:http://10.60.25.96:32951/wsagent/ext/. Timestam
2016-10-24 10:18:49,040[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 636]    - Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your wo
org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:277) ~[che-core-api-workspace-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:620) ~[che-core-api-workspace-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92-internal]
Caused by: org.eclipse.che.api.core.ServerException: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the
        at org.eclipse.che.api.workspace.server.launcher.WsAgentLauncherImpl.launch(WsAgentLauncherImpl.java:128) ~[che-core-api-workspace-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:614) ~[che-core-api-workspace-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:288) ~[che-core-api-workspace-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:251) ~[che-core-api-workspace-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
        ... 5 common frames omitted

Can you tell me what is going wrong in my configuration ?

**Comment by SanthoshHari912** [comment]
@TylerJewel,@slemeur If the above problem is something do w.r.t https://eclipse-che.readme.io/docs/networking ,
can you provide me an example usage of these environmental variables?

**Comment by slemeur** [comment]
following up as part of #2879
