### ISSUE TITLE
Unexpected exceptions in the dev-machine console after importing not a maven project

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2822]
**Reproduction Steps:**
1. Import for example the github project: https://github.com/idexmai/pull-request-plugin-test.git
2. Configure as Blank in the Wizard
3. Open dev-machine console 

**Expected behavior:**
In the console should not be any exceptions
**Observed behavior:**
We have exception like: `
org.eclipse.che.api.project.server.type.ValueStorageException: pom.xml does not exist.
    at org.eclipse.che.plugin.maven.server.projecttype.MavenValueProviderFactory.readModel(MavenValueProviderFactory.java:55) ~[che-plugin-maven-server-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at org.eclipse.che.plugin.maven.server.projecttype.MavenValueProviderFactory$MavenValueProvider.getValues(MavenValueProviderFactory.java:81) ~[che-plugin-maven-server-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at org.eclipse.che.api.project.server.type.ProjectTypeDef.resolveSources(ProjectTypeDef.java:181) ~[che-core-api-project-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at org.eclipse.che.api.project.server.ProjectManager.estimateProject(ProjectManager.java:445) ~[che-core-api-project-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at org.eclipse.che.api.project.server.ProjectManager.resolveSources(ProjectManager.java:467) ~[che-core-api-project-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at org.eclipse.che.api.project.server.ProjectService.resolveSources(ProjectService.java:277) [che-core-api-project-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.13.1.jar:na]
    at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61) [everrest-core-1.13.1.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
    at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
    at com.codenvy.workspace.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:57) [codenvy-hosted-workspace-activity-agent-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
    at com.codenvy.machine.authentication.agent.MachineLoginFilter.doFilter(MachineLoginFilter.java:102) [codenvy-hosted-machine-authentication-agent-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
    at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436) [catalina.jar:8.0.37]
    at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177) [catalina.jar:8.0.37]
    at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59) [che-core-api-core-5.0.0-M6-SNAPSHOT.jar:5.0.0-M6-SNAPSHOT]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.37]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.37]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.37]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.37]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.37]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.37]
    at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.37]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.37]
    at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:503) [catalina.jar:8.0.37]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.37]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.37]
    at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.37]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.37]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [catalina.jar:8.0.37]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) [tomcat-coyote.jar:8.0.37]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) [tomcat-coyote.jar:8.0.37]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-coyote.jar:8.0.37]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-coyote.jar:8.0.37]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.37]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]`

**Codenvy version:**  5.0.0-M5-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS

**Comment by xiaowenben** [comment]
I got the same question,how to reslove?

**Comment by musienko-maxim** [comment]
In 5.6.0 cannot reproduce
