### ISSUE TITLE
Can't restart workspace after stopping it

### ISSUE THREAD

**Issue by binduwavell** [eclipse-che/che#286]
I have a workspace with a custom stack. I stopped it. Now I'm trying to start it and seeing the following log in the window where I ran `che.sh run -i`.

```
2016-02-08 00:19:05,985[spaceManager-11]  [INFO ] [o.e.c.a.m.s.MachineManager 167]      - Creating machine [ws = workspacenjfsirvsxhz55bas: env = gen-alfresco-ws: machine = ws-machine]
2016-02-08 00:19:05,990[spaceManager-11]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Can't start machine ws-machine. http://192.168.99.100:8080/ide/api/recipe/recipe7jnhxi6wjjbz6181/script
org.eclipse.che.api.machine.server.exception.MachineException: Can't start machine ws-machine. http://192.168.99.100:8080/ide/api/recipe/recipe7jnhxi6wjjbz6181/script
    at org.eclipse.che.api.machine.server.MachineManager.getRecipeByLocation(MachineManager.java:983) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:293) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:168) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:451) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:319) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:145) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$9(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-beta-13.jar:4.0.0-beta-13]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
```

Of course the workspace doesn't start at this point...

**Comment by binduwavell** [comment]
I tried stopping che and restarting it, I get the same error when I try to start my workspace even after the restart.

**Comment by TylerJewell** [comment]
This should be resolved by this PR.  The issues you are running into have to do with docker-in-docker and a limitation of the beta.

https://github.com/codenvy/che/pull/257

**Comment by binduwavell** [comment]
Is there anything I can do to get my install working again or do I have to delete my workspace and make a new one?

**Comment by TylerJewell** [comment]
@eivantsov would know more details, but you likely have to destroy the workspace right now.  The running Che as a Docker image is 100% experimental right now. There are numerous stability and security issues with running it this way, so please be careful.  I really encourage you to run Che as a native server if you can.

**Comment by binduwavell** [comment]
Cool, I'll switch over to running che as native, it was not clear to me from docs, etc that this was experimental (although I guess I should have figured it out based on reviewing open issues and seeing #257 ;) )

**Comment by binduwavell** [comment]
Per your suggestion I attempted to switch over to local che `bin/che.sh stop -i`, `bin/che.sh start`. I get the following error in the tomcat log:

```
2016-02-07 18:36:38,215[kspaceManager-0]  [INFO ] [o.e.c.a.m.s.MachineManager 167]      - Creating machine [ws = workspacen665hyxma47ylarb: env = gen-alf-ws1: machine = ws-machine]
2016-02-07 18:36:38,227[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Can't start machine ws-machine. Unexpected end of file from server
org.eclipse.che.api.machine.server.exception.MachineException: Can't start machine ws-machine. Unexpected end of file from server
        at org.eclipse.che.api.machine.server.MachineManager.getRecipeByLocation(MachineManager.java:983) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:293) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:168) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:451) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:319) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:145) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$9(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-beta-13.jar:4.0.0-beta-13]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
```

**Comment by binduwavell** [comment]
Used `docker-machine rm default` and then restarted che `bin/che.sh --debug run`. I seem to now be able to create and start workspaces again.

**Comment by ghost** [comment]
Are you running Che on a local machine or on a remote instance? If Che server is runnign remotely, you should add -r:$IP parameter to che.sh

**Comment by binduwavell** [comment]
I was running docker-in-docker. I'm now running locally.

**Comment by ghost** [comment]
@binduwavell can you still reproduce this issue?

**Comment by ghost** [comment]
@binduwavell I cannot reproduce it with the latest stable version. We have got rid of docker in docker btw, so it should be ok now. Feel free to reopen if you bump into this again.
