### ISSUE TITLE
Unable to connect to Analytics host on install.codenevycorp.com

### ISSUE THREAD

**Issue by mcrocker** [eclipse-che/che#2889]
After start-up of Eclipse Che, logs start producing UnknownHostExceptions. 

The fact that the application is unable to create projects and was only able to create a workspace once may or may not be related to this problem.

My guess is that install.codenvycorp.com disagrees with our corporate proxy since it seems to be an AWS dynamically defined name with many IP addresses.

Setting my http_proxy, https_proxy, HTTP_PROXY and HTTPS_PROXY environment variables didn't seem to help. Proxy works fine elsewhere in my system.

**Reproduction Steps:**
1. docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start
2. wait several minutes
3. docker logs che-server | less
4. See UnknownHostExceptions in the logs

**Expected behavior:**
1. Clean logs on start-up
2. Ability to create workspaces and projects,

**Observed behavior:**

Logs show:

2016-10-24 20:47:44,635[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 3896 ms
2016-10-24 20:47:48,859[ted-scheduler-0]  [ERROR] [a.d.WsMasterAnalyticsAddresser 37]   - Failed to send master analytics
java.net.UnknownHostException: install.codenvycorp.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_92-internal]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_92-internal]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_92-internal]
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_92-internal]
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:1.8.0_92-internal]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_92-internal]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_92-internal]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_92-internal]
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_92-internal]
    at org.eclipse.che.api.deploy.WsMasterAnalyticsAddresser.send(WsMasterAnalyticsAddresser.java:35) ~[classes/:4.7.2]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92-internal]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92-internal]
    at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:53) [che-core-commons-schedule-4.7.2.jar:4.7.2]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92-internal]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92-internal]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]
2016-10-24 21:47:48,724[ted-scheduler-1]  [ERROR] [a.d.WsMasterAnalyticsAddresser 37]   - Failed to send master analytics
java.net.UnknownHostException: install.codenvycorp.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_92-internal]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_92-internal]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_92-internal]
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_92-internal]
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:1.8.0_92-internal]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_92-internal]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_92-internal]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_92-internal]
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_92-internal]
    at org.eclipse.che.api.deploy.WsMasterAnalyticsAddresser.send(WsMasterAnalyticsAddresser.java:35) ~[classes/:4.7.2]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92-internal]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92-internal]
    at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:53) [che-core-commons-schedule-4.7.2.jar:4.7.2]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92-internal]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92-internal]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]
2016-10-24 22:47:48,724[ted-scheduler-2]  [ERROR] [a.d.WsMasterAnalyticsAddresser 37]   - Failed to send master analytics
java.net.UnknownHostException: install.codenvycorp.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_92-internal]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_92-internal]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_92-internal]
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_92-internal]
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:1.8.0_92-internal]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_92-internal]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_92-internal]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_92-internal]
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_92-internal]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_92-internal]
    at org.eclipse.che.api.deploy.WsMasterAnalyticsAddresser.send(WsMasterAnalyticsAddresser.java:35) ~[classes/:4.7.2]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92-internal]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92-internal]
    at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:53) [che-core-commons-schedule-4.7.2.jar:4.7.2]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92-internal]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92-internal]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92-internal]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]
2016-10-24 23:34:09,438[nio-8080-exec-6]  [INFO ] [.a.t.u.h.LegacyCookieProcessor 579]  - Cookies: Invalid cookie. Value not a token or quoted value
 Note: further occurrences of Cookie errors will be logged at DEBUG level.

[Describe observed behavior here]

**Che version:**    [doesn't say anywhere I can find! - latest?]  
**OS and version:** [Ubuntu 16.04]  
**Docker version:** [Docker version 1.11.2, build b9f10c9]  
**Che install:**    [docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start]   

**Additional information:**
- Problem started happening: immediately on the very first startup.
- Problem can be reliably reproduced: every time the docker image is started.

**Comment by TylerJewell** [comment]
You can ignore that error.  It should be suppressed and not reflective of anything not working.

**Comment by mcrocker** [comment]
Excellent. I was hoping that was the case.

Also, thanks for your quick response. I was reluctant to create this issue, but hopefully, a nice simple answer like this with a stack trace will make it easier for others to find it and not have to post it again.

**Comment by TylerJewell** [comment]
I am going to leave the issue open as our engineers should add logic to have it suppressed from output to avoid clutter.

**Comment by TylerJewell** [comment]
@skabashnyuk - please look at this and consider having someone take it for a couple minutes in the next sprint.  This exception should be suppressed, not flowing into the logs.
