### ISSUE TITLE
Issues with Language Servers

### ISSUE THREAD

**Issue by cdietrich** [eclipse-che/che#3127]
I am experimenting with Language Servers in Che (implemented with Xtext) and I came over following issues:

- The Client Misses to send the languageId to the Server in didOpen requests (as a temp solution i patched che to hardcode the id)
- If i use Content Assist the Calculated Offsets and Lines seem wrong thus Xtext answers with errors

**Reproduction Steps:**

- find my code here https://github.com/cdietrich/che/tree/xtext2
- start che and create a new PHP project
- create a mydsl file

**Expected behavior:**

everything works

**Actual Behaviour**

validation works (* after patching che), content assist not

content assist is not working
- have a look at xxx-* log to see the errors xtext sends

```
"message": "java.lang.IndexOutOfBoundsException: Position [\n line \u003d 2\n character \u003d 20\n] text was : Hello
name!\nHello Yyyyy from name!\nHello xxxx from \n\n"
```

- before i patched che regarding language id i got following error from xtext

```
Nov 18, 2016 8:02:12 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError                                      
SEVERE: The property 'languageId' must have a non-null value.                                                               
org.eclipse.lsp4j.jsonrpc.json.InvalidMessageException: The property 'languageId' must have a non-null value.               
        at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:41)      
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)               
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)                       
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)                
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                          
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                         
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                  
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                  
        at java.lang.Thread.run(Thread.java:745)
```

i am not sure what the state of the clientside impl is and if this is expected to work and if i miss a configuraton regarding the languageId (besides confuguring it in the module and adding the module to the war)

is there a easy possibility to debug this client side?

**Comment by tolusha** [comment]
@evidolob 
Could you have a look pls

**Comment by evidolob** [comment]
About languageId it's a bug. About Content Assist I need more time to investigate.

**Comment by cdietrich** [comment]
with completion i see other problems as well (incomplete messages in xtexts log, i dont know if this is related how i added to logging to xtext) but the very same server works fine in vscode

**Comment by cdietrich** [comment]
@evidolob is there an option to enable message logging on che side?

**Comment by cdietrich** [comment]
it looks like the client does not send didchanges when selecting from content assist

**Comment by cdietrich** [comment]
hmmm

if i type "H" in an empty document, then vscode sends

```
 "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "rangeLength": 0,
            "text": "H"
        }
    ]
```

and che sends

```
"contentChanges": [                                                                  
      {                                                                                  
        "range": {                                                                       
          "start": {                                                                     
            "line": 0,                                                                   
            "character": 0                                                               
          },                                                                             
          "end": {                                                                       
            "line": 0,                                                                   
            "character": 1                                                               
          }                                                                              
        },                                                                               
        "text": "H"    
```

**Comment by cdietrich** [comment]
if i fix this and use the same start and end positions for insertions it works fine

**Comment by cdietrich** [comment]
looks good. thx
