### ISSUE TITLE
Open create workspace failed.

### ISSUE THREAD

**Issue by mmjordan** [eclipse-che/che#3183]
[Short description of problem here]
I run Che inside a Docker container. But, when I clicked the "**Add Workspace**" button, the create-workspace page was note displayed. Only displayed : 
1: {{workspaceDetailsController.isCreationFlow ? 'New Workspace' : workspaceDetailsController.workspaceName}}

2: {{workspaceDetailsController.invalidWorkspace}}
**Reproduction Steps:**

1. [First Step]
Run che inside a Docker container with the default command:
docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:5.0.0-latest start
2. [Second Step]
Connect to che: http://192.168.99.104:8080
3. [Other Steps...]
Click"workspace->Add workspace".

**Expected behavior:**

[Describe expected behavior here]
create-workspace page displayed.
**Observed behavior:**

[Describe observed behavior here]
Only displayed : 
1: {{workspaceDetailsController.isCreationFlow ? 'New Workspace' : workspaceDetailsController.workspaceName}}

2: {{workspaceDetailsController.invalidWorkspace}}

**Che version:**    [eclipse/che:5.0.0-M7]   
**OS and version:** [Windows 7.1]   
**Docker version:** [1.12.3, build 6b644ec]   
**Che install:**    [Docker container]   

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

* Execption show in the browser console:
TypeError: this.usedNamesList.includes is not a function
    at e.a.value (http://192.168.99.104:8080/dashboard/scripts/app-d88f825ffd.js:2043:5367)
    at e.a.value (http://192.168.99.104:8080/dashboard/scripts/app-d88f825ffd.js:2043:2201)
    at new e (http://192.168.99.104:8080/dashboard/scripts/app-d88f825ffd.js:2043:1177)
    at i (http://192.168.99.104:8080/dashboard/scripts/vendor-ae4aa9ca8d.js:74:19553)
    at Object.o [as instantiate] (http://192.168.99.104:8080/dashboard/scripts/vendor-ae4aa9ca8d.js:74:19645)
    at http://192.168.99.104:8080/dashboard/scripts/vendor-ae4aa9ca8d.js:75:9704
    at link (http://192.168.99.104:8080/dashboard/scripts/vendor-ae4aa9ca8d.js:154:3904)
    at ie (http://192.168.99.104:8080/dashboard/scripts/vendor-ae4aa9ca8d.js:75:5563)
    at g (http://192.168.99.104:8080/dashboard/scripts/vendor-ae4aa9ca8d.js:74:31495)
    at s (http://192.168.99.104:8080/dashboard/scripts/vendor-ae4aa9ca8d.js:74:27685) <div id="main-content" role="main" ng-view="" layout="column" flex="" ng-show="waitingLoaded &amp;&amp; !showIDE" class="ng-scope" data-ng-animate="1">

**Comment by ashumilova** [comment]
Hi, @mmjordan - the error happens, because your browser version doesn't support that `includes` function. We will fix it by reworking such parts of code. And thank you for detailed error report.

**Comment by soonyou** [comment]
@ashumilova can I know which version of chrome and chromium the eclipse che can support?thanks

**Comment by ashumilova** [comment]
@soonyou do you still have that error? and what's your browser version? I am asking, cause we thought we fixed that error not tot depend on browser version.

**Comment by soonyou** [comment]
@ashumilova I using chromium Version 43.0.2357.81 Ubuntu 14.04 (64-bit), yes when I click workspaces>add workspace, it show me the error
