### ISSUE TITLE
Error pulling docker image of my workspace

### ISSUE THREAD

**Issue by mjitch** [eclipse-che/che#325]
All of a sudden I am facing an issue launching my workspace. My eclipse che fails to pull the docker image. My network is fine and I am not behind a firewall. I have tried it two different networks. Is there a problem with the repository?

Logs -

`016-02-15 14:35:54,234[kspaceManager-2]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Docker image build failed
org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:396) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:337) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:168) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:451) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:319) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:145) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:642) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$9(WorkspaceManager.java:613) ~[che-core-api-workspace-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-beta-13.jar:4.0.0-beta-13]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.buildImage(DockerInstanceProvider.java:305) ~[che-plugin-docker-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.createInstance(DockerInstanceProvider.java:221) ~[che-plugin-docker-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.api.machine.server.MachineManager.createInstance(MachineManager.java:360) ~[che-core-api-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        ... 11 common frames omitted
Caused by: java.io.IOException: Docker image build failed
        at org.eclipse.che.plugin.docker.client.DockerConnector.doBuildImage(DockerConnector.java:842) ~[che-plugin-docker-client-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:222) ~[che-plugin-docker-client-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:194) ~[che-plugin-docker-client-4.0.0-beta-13.jar:4.0.0-beta-13]
        at org.eclipse.che.plugin.docker.machine.DockerInstanceProvider.buildImage(DockerInstanceProvider.java:299) ~[che-plugin-docker-machine-4.0.0-beta-13.jar:4.0.0-beta-13]
        ... 13 common frames omitted`

Scr-shot -

![che_error1](https://cloud.githubusercontent.com/assets/12231623/13044161/8f5d335a-d3f2-11e5-8eaa-bb6a33324056.jpg)

**Comment by benoitf** [comment]
Hello,
what is your operating system ? On Windows or MacOS you should try to restart the docker-machine
$ docker-machine ls
$ docker-machine restart <name-of-the-machine>

(also we give --virtualbox-host-dns-resolver option to startup script)
https://github.com/boot2docker/boot2docker/issues/945

**Comment by ghost** [comment]
Yes, you should try sshing into your VM and run docker pull there (or do it from your WIndows console if you have the right env variables exported).

It is possible that Docker Hub was unavailable for a minute or so although I failed to find any downtime records at their status page.

**Comment by ghost** [comment]
Any update on this one? I failed to reproduce it using different connections and Che versions.

**Comment by mjitch** [comment]
Oh yes, looks like this was an issue with Windows 10 security upgrade. After running the security upgrades, I rebooted my machine, and it started working. Now, I can verify my other issue (custom maven). Thanks anyway!
