### ISSUE TITLE
Fail launching agent Terminal

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3275]
When I start a workspace I have an error 'Fail launching agent Terminal'

**Reproduction Steps:**
1. I have downloaded a fresh version of che
$ git clone https://github.com/eclipse/che.git

2. I have compiled the project
$ cd ~/che/ide/che-core-ide-stacks
$ mvn clean install
$ cd ~/che/ide/che-core-ide-templates
$ mvn clean install
$ cd ~/assembly/assembly-main
$ mvn clean install

3. I have set the enviromental variables: CHE_WORKSPACE_HTTP_PROXY, CHE_WORKSPACE_HTTPS_PROXY, CHE_WORKSPACE_NO_PROXY, CHE_ASSEMBLY, CHE_DATA

4. I have started the project
$ MSYS_NO_PATHCONV=1 docker run -e CHE_WORKSPACE_HTTP_PROXY -e CHE_WORKSPACE_HTTPS_PROXY -e CHE_WORKSPACE_NO_PROXY -e CHE_ASSEMBLY -e CHE_DATA --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:5.0.0-latest start

4. I have created a workspace and started it, but if failed to start.

**Expected behavior:**

When I use an Internet version (e.g. when I remove CHE_ASSEMBLY), then a workspace starts. 

**Observed behavior:**

However, when I use a local che, it throws an error.

**Che version:**    5.0.0-latest
**OS and version:**  Microsoft Windows [Version 10.0.10586]   
**Docker version:** Docker version 1.12.3, build 6b644ec  

**Additional information:**

The log from catalina-0.log

2016-12-05 11:52:54,462[spaceRuntimes-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 600]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacemh9p0q2oxddlzvxs
2016-12-05 11:54:55,448[spaceRuntimes-0]  [ERROR] [.a.a.s.l.AbstractAgentLauncher 95]   - Fail launching agent Terminal. Workspace ID:workspacemh9p0q2oxddlzvxs
2016-12-05 11:54:56,637[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 660]    - org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Fail launching agent Terminal. Workspace ID:workspacemh9p0q2oxddlzvxs
java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Fail launching agent Terminal. Workspace ID:workspacemh9p0q2oxddlzvxs
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_101]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:639) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Fail launching agent Terminal. Workspace ID:workspacemh9p0q2oxddlzvxs
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:665) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
	... 3 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Fail launching agent Terminal. Workspace ID:workspacemh9p0q2oxddlzvxs
	at org.eclipse.che.api.agent.server.launcher.AbstractAgentLauncher.launch(AbstractAgentLauncher.java:96) ~[che-core-api-agent-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:604) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:676) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:640) ~[che-core-api-workspace-5.0.0-M8-SNAPSHOT.jar:5.0.0-M8-SNAPSHOT]
	... 6 common frames omitted

* Problem started happening recently, didn't happen in an older version of Che: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
Hi Aleksei:

I see two things:
1. We are about to deprecate this version of the CLI in favor of a much simpler one.  Can you re-run your tests with this CLI.  https://github.com/eclipse/che/tree/master/docs.  Try it  with the "nightly" version please.

2. I don't understand what you were doing with the PROXY settings.  If you are behind a proxy, the values that you set would not change anything, and if you were behind a proxy, I would expect the product not to start with those values, so that was a head scratcher.

**Comment by aleksei-burlakov** [comment]
I tryed
`$ MSYS_NO_PATHCONV=1 docker run -e CHE_WORKSPACE_HTTP_PROXY -e CHE_WORKSPACE_HTTPS_PROXY -e CHE_WORKSPACE_NO_PROXY -e CHE_ASSEMBLY -e CHE_DATA --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:nightly start`
but it had no effect.  Then I tryed to repeat everything on Ubuntu, and the workspace started.
