### ISSUE TITLE
Che on a cloud server - Not able to create a workspace

### ISSUE THREAD

**Issue by pramodak** [eclipse-che/che#3576]
I am not able to create a workspace (my first workspace) after installing and opening che from the browser (I tried firefox and chrome browsers)

**Reproduction Steps:**
The cloud server where che is running has the public IP address as "10.39.89.244". I configured CHE_HOST_IP=10.39.89.244 and start che on the cloud server.

When I try creating a new workspace from the Che UI, I see an error as below.

```
Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
```

**Expected behavior:**

The workspace should be created

**Observed behavior:**

Issue with the workspace creation as mentioned above.

**Che version:**    5.0.0-latest
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.5 
**Che install:**    Docker container

**Additional information:**

The stack trace from the docker logs is as below.

```
2016-12-30 12:15:33,585[spaceRuntimes-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 600]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacedd3fi05pctss4py3
2016-12-30 12:15:35,739[spaceRuntimes-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 600]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacedd3fi05pctss4py3
2016-12-30 12:15:37,880[spaceRuntimes-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 600]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspacedd3fi05pctss4py3
2016-12-30 12:18:37,994[spaceRuntimes-1]  [ERROR] [.c.a.w.s.l.WsAgentLauncherImpl 127]  - Fail pinging ws agent. Workspace ID:workspacedd3fi05pctss4py3. Url:http://10.39.89.244:32829/api/. Timestamp:{}
2016-12-30 12:18:38,813[kspaceManager-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 660]    - org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_111]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$4(WorkspaceManager.java:639) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:665) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
        ... 3 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.workspace.server.launcher.WsAgentLauncherImpl.launch(WsAgentLauncherImpl.java:128) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:604) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:676) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:640) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        ... 6 common frames omitted
```
* Problem started happening recently, didn't happen in an older version of Che: No (First time issue - new user)
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@pramodak - this indicates that you have a networking configuration issue. The workspace is unable to make a connection back to the Che server, and the Che server is unable to ping the workspace.  There are configuration properties that you can alter that will change how workspaces connect back to the Che server.

First, we are in the middle of making our 5.0.0 release, so please use the following syntax for running Che:
https://github.com/eclipse/che/tree/master/docs/_docs/setup

Second, once you run Che with that syntax, it will install a che.env file that has various networking parameters in there that you can configure and then rerun Che. There is descriptions of the variables that you need to set to enable communication between the workspace and the Che server.

Please let us know how that goes.

**Comment by pramodak** [comment]
Thanks to both Tyler and Eugene for the comments.
I will try Tyler's suggestion and update this thread.

@eivantsov : I have opened the ephemeral port range (32768-65535 - both TCP/UDP) for the cloud server. I am not sure where to find the correct logs for workspace agent. In the dev-machine container, I see the following log. No errors as such.

```
user@736f35be4144:~/che/ws-agent/logs/2017/01/02$ ls -lrt
total 8
-rw-r--r-- 1 user user    0 Jan  2 07:40 localhost-access-0.log
-rw-r--r-- 1 user user 6354 Jan  2 07:40 catalina-0.log

user@736f35be4144:~/che/ws-agent/logs/2017/01/02$ cat catalina-0.log
2017-01-02 07:40:42,509[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.38
2017-01-02 07:40:42,511[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 6 2016 20:51:55 UTC
2017-01-02 07:40:42,511[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.38.0
2017-01-02 07:40:42,512[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2017-01-02 07:40:42,512[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.4.0-57-generic
2017-01-02 07:40:42,512[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2017-01-02 07:40:42,513[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_45/jre
2017-01-02 07:40:42,513[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_45-b14
2017-01-02 07:40:42,513[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2017-01-02 07:40:42,513[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
2017-01-02 07:40:42,513[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
2017-01-02 07:40:42,514[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
2017-01-02 07:40:42,514[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2017-01-02 07:40:42,514[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
2017-01-02 07:40:42,514[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
2017-01-02 07:40:42,524[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
2017-01-02 07:40:42,525[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
2017-01-02 07:40:42,525[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
2017-01-02 07:40:42,525[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2017-01-02 07:40:42,525[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
2017-01-02 07:40:42,525[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2017-01-02 07:40:42,526[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2017-01-02 07:40:42,526[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2017-01-02 07:40:42,526[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
2017-01-02 07:40:42,526[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
2017-01-02 07:40:42,526[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
2017-01-02 07:40:42,527[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
2017-01-02 07:40:42,528[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
2017-01-02 07:40:42,653[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 443]  - Initializing ProtocolHandler ["http-nio-4401"]
2017-01-02 07:40:42,669[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2017-01-02 07:40:42,673[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 428 ms
2017-01-02 07:40:42,704[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
2017-01-02 07:40:42,751[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
2017-01-02 07:40:42,752[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38
2017-01-02 07:40:42,830[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
2017-01-02 07:40:52,075[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.LoEventListener 48]   - Subscribing to event service: class org.eclipse.che.api.vfs.impl.file.event.LoEventListener
2017-01-02 07:40:52,083[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 58]   - Starting virtual file system event service: LoEventService
2017-01-02 07:40:52,084[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 58]   - Starting virtual file system event service: HiEventService
2017-01-02 07:40:52,271[rest.WSClient-0]  [INFO ] [.c.a.c.n.WSocketEventBusClient 227]  - Open connection to ws://che-host:8080/wsmaster/api/eventbus/?token=dummy_token.
2017-01-02 07:40:52,382[s polled Thread]  [INFO ] [o.e.c.p.m.server.rmi.RmiClient 130]  - Port/Name:9624/MavenRemoteServerImpl59309aa6

2017-01-02 07:40:54,061[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 11,230 ms
2017-01-02 07:40:54,064[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-4401"]
2017-01-02 07:40:54,068[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 11393 ms
```

**Comment by ghost** [comment]
@pramodak according to ws agent logs, it is able to reach ws-master but not vice versa.  It might be a security (firewall) or networking issue. Is firewall on?

**Comment by pramodak** [comment]
@eivantsov : I see that the ufw is inactive on the server where docker is running. 
$ sudo ufw status
Status: inactive

On the project container, ufw is not present.
Is there a log that I can see on the docker container or the workspace container to debug this issue further?

**Comment by ghost** [comment]
@pramodak even though you can access CHE at 10.39.89.244 Che server, running in a container, cannot reach a workspace agent that runs on the same host in a different container.

Can you try the following? **DO NOT** export `CHE_HOST_IP=10.39.89.244`, then start Che.

I expect that the workspace will be considered as running, but your browser won't be able to connect to it (expected). If this is the case, then there's some sort of a networking/security issue where connections from one container to another are blocked when 10.39.89.244 is used.

FYI, I cannot reproduce this one on a clean Ubuntu launched on Digital Ocean or Amazon.

**Comment by nishant-jain-94** [comment]
@TylerJewell  @eivantsov I am facing the same issue

@pramodak Did the problem fix for you

**Comment by TylerJewell** [comment]
@l0rd, @amisevsk --- adding you to this thread. Do any of the improvements from
https://github.com/eclipse/che/pull/2004

**Comment by ghost** [comment]
@TylerJewell that PR addresses a bit different problem. Here in this case server cannot reach ws agent, not client. I suspect this is either blocked port issue since the server uses an external IP to reach ws agent over ephemeral port range or some security restriction that prevents communication between Docker containers (which is unlikely since ws agent CAN reach workspace master)

**Comment by TylerJewell** [comment]
@eivantsov - RedHat has a pending PR which changes the routing of requests from server->agent and agent->server to use internal IP addresses.  But for the life of me that I cannot find it now.  Do you know where it is - could it be useful here?

**Comment by pramodak** [comment]
@eivantsov If I do not export CHE_HOST_IP, I get the following error.

`Our workspace agent is no longer responding. To fix the problem, verify you have a good network connection and restart the workspace.`

And the logs are as below.
```
[DOCKER] latest: Pulling from codenvy/ubuntu_jdk8 

[DOCKER] Digest: sha256:018f74a9a6f407f10c2815c39fb965f9dea8a1acb0f5cd2de7ef1ec32f133ed5 

[DOCKER] Status: Image is up to date for codenvy/ubuntu_jdk8:latest 

Listening for transport dt_socket at address: 4403

2017-01-09 08:22:19,353[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.38

2017-01-09 08:22:19,361[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 6 2016 20:51:55 UTC

2017-01-09 08:22:19,362[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.38.0

2017-01-09 08:22:19,363[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux

2017-01-09 08:22:19,363[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.4.0-57-generic

2017-01-09 08:22:19,363[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64

2017-01-09 08:22:19,363[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_45/jre

2017-01-09 08:22:19,364[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_45-b14

2017-01-09 08:22:19,365[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation

2017-01-09 08:22:19,365[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent

2017-01-09 08:22:19,366[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent

2017-01-09 08:22:19,368[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties

2017-01-09 08:22:19,369[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager

2017-01-09 08:22:19,371[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m

2017-01-09 08:22:19,371[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m

2017-01-09 08:22:19,371[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom

2017-01-09 08:22:19,372[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs

2017-01-09 08:22:19,377[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048

2017-01-09 08:22:19,378[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources

2017-01-09 08:22:19,378[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n

2017-01-09 08:22:19,378[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote

2017-01-09 08:22:19,378[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false

2017-01-09 08:22:19,379[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false

2017-01-09 08:22:19,381[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf

2017-01-09 08:22:19,381[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed

2017-01-09 08:22:19,381[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent

2017-01-09 08:22:19,382[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent

2017-01-09 08:22:19,383[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp

2017-01-09 08:22:19,505[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 443]  - Initializing ProtocolHandler ["http-nio-4401"]

2017-01-09 08:22:19,516[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read

2017-01-09 08:22:19,518[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 431 ms

2017-01-09 08:22:19,587[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server

2017-01-09 08:22:19,588[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina

2017-01-09 08:22:19,589[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38

2017-01-09 08:22:19,669[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war

2017-01-09 08:22:28,504[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.LoEventListener 48]   - Subscribing to event service: class org.eclipse.che.api.vfs.impl.file.event.LoEventListener

2017-01-09 08:22:28,508[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 58]   - Starting virtual file system event service: LoEventService

2017-01-09 08:22:28,511[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 58]   - Starting virtual file system event service: HiEventService

2017-01-09 08:22:28,705[rest.WSClient-0]  [INFO ] [.c.a.c.n.WSocketEventBusClient 227]  - Open connection to ws://che-host:8080/wsmaster/api/eventbus/?token=dummy_token. 

2017-01-09 08:22:28,800[s polled Thread]  [INFO ] [o.e.c.p.m.server.rmi.RmiClient 130]  - Port/Name:19889/MavenRemoteServerImpl31951f82

 

Mon Jan 09 08:22:30 UTC 2017 - [localhost-startStop-1] Product-specified preferences called before plugin is started

2017-01-09 08:22:30,559[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 10,889 ms

2017-01-09 08:22:30,562[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-4401"]

2017-01-09 08:22:30,571[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 11052 ms

2017-01-09 08:22:30,714[nio-4401-exec-3]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.

2017-01-09 08:22:30,715[nio-4401-exec-1]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.

2017-01-09 08:22:30,716[nio-4401-exec-2]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.
```
Let me check if I can fiddle around the network configuration to get it working.

**Comment by l0rd** [comment]
@TylerJewell I think you are talking about PR #3282 that fixes issue #2030 

@pramodak tips provided in [this comment](https://github.com/eclipse/che/issues/2030#issuecomment-237595865) may be helpful to confirm the nature of your problem

**Comment by ghost** [comment]
@pramodak can you run a simple test?

`docker run -d -p 32829:80 nginx`

Go to `10.39.89.244:32829` - you should see nginx welcome page

Then run:

`docker run -ti codenvy/ubuntu_jdk8 bash`

When inside a container:

`curl - v 10.39.89.244:32829`

Is this command successful for you? If not, then it is security issue with the VM.

**Comment by pramodak** [comment]
@eivantsov The curl command is not successful and there is a timeout error. So, it looks like a security issue with the VM which I need to debug further.

```
user@92168ec454a3:/projects$ time curl -v 10.39.89.244:32829
* Rebuilt URL to: 10.39.89.244:32829/
* Hostname was NOT found in DNS cache
*   Trying 10.39.89.244...
* connect to 10.39.89.244 port 32829 failed: Connection timed out
* Failed to connect to 10.39.89.244 port 32829: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to 10.39.89.244 port 32829: Connection timed out

real    2m7.175s
user    0m0.008s
sys     0m0.000s

```

**Comment by TylerJewell** [comment]
@pramodak - thanks for the investigation persistence.

**Comment by TylerJewell** [comment]
@pramodak - how did it go?

**Comment by ghost** [comment]
@pramodak any update please?

**Comment by pramodak** [comment]
Hi @eivantsov @TylerJewell,
Sorry, I could not spend time on this one.
I would like to close this discussion and get back to it when I have more information.
