### ISSUE TITLE
Can we deploy a custom war file into tomcat which is in che container

### ISSUE THREAD

**Issue by codergabs** [eclipse-che/che#3588]
[Short description of problem here]

I want to deploy some custom war file into tomcat which is in che container.
I don't see any ssh port enabled there, Is there any way to configure some port and make 
the war file transfer possible into the  home/user/che/tomcat/webapps/

My expectation is my custom war to co exist with 
 ROOT.war
dashboard.war
swagger.war
wsmaster.war

And I could see the username for che container is root,
what is it's default password

**Che version:**    5.0.0-M8 
**OS and version:** Windows 7

**Comment by ghost** [comment]
@codergabs do you want to hot deploy your custom war on the go?

**Comment by codergabs** [comment]
@eivanstov
Yes, Want to hot deploy,
Could put the war using volume into webapps.
But not hot deploying, and tomcat after stopping not starting as well.

**Comment by codergabs** [comment]
@eivantsov 
still couldn't find a way to ssh into the container.

**Comment by ghost** [comment]
sshd isn't running in che-server container.

Can you elaborate on what you are trying to achieve? Perhaps what you are looking for is a development mode for Eclipse Che. In this mode, your local binaries get mounted into che-server container, and all changes you do locally will take effect in a container as well.

**Comment by codergabs** [comment]
@eivantsov 
You are right I got the local binaries mounted.
Now i am facing another issue, The war is not hot deploying, and when i am trying to restart the tomcat, getting the following error


2017-01-04 08:22:51,752[ina-startStop-1]  [ERROR] [o.a.c.core.ContainerBase 917]        - A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/agent-binaries]]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_111]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:915) ~[catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871) [catalina.jar:8.0.38]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397) [catalina.jar:8.0.38]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/agent-binaries]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162) [catalina.jar:8.0.38]
        ... 6 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@5caf8c9c]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4969) ~[catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5099) ~[catalina.jar:8.0.38]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:8.0.38]
        ... 6 common frames omitted
Caused by: java.lang.IllegalArgumentException: The main resource set specified [/home/user/che/tomcat/webapps/${che.home}/lib] is not valid
        at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:730) ~[catalina.jar:8.0.38]
        at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:688) ~[catalina.jar:8.0.38]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:8.0.38]
        ... 9 common frames omitted

**Comment by codergabs** [comment]
@eivantsov ,
I got it, I was starting catalina instead of che, so some parameter set was missing.
I can deploy my war file now on restart.
To hot deploy probably need to change the server.xml right.

**Comment by TylerJewell** [comment]
Yes, that is correct.

**Comment by codergabs** [comment]
@eivantsov @TylerJewell 

Surprisingly one of my war file is giving following exception on deployment


Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_111]
        at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_111]
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_111]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_111]
        at java.util.jar.JarFile.<init>(JarFile.java:103) ~[na:1.8.0_111]

It is extracting on some other tomcat, but failing in the tomcat in che container,
Any pointers you guys have on this.
space is ok permission is 777, still failing.
Some sample war downloaded from web is working fine

**Comment by ghost** [comment]
@codergabs it'd be great to know when this exception occurs, what custom war you are trying to deploy, share code etc. Without this info there's little we can suggest.

**Comment by codergabs** [comment]
@eivantsov 

I have put the war file into webapps, when I am restarting che server, my expectation is 
the war file will be extracted, but it is not, and in log I can see the ZIPException.
My server.xml is autoDeploy false, which is default.

Sharing code will be little difficult for me.
It's a war file containing only js files and xml files no java code in that.
Can you please give me some guidelines what I can check to debug this issue.

the same custom war is getting deployed at other tomcat.
I remember it got deployed once in che tomcat, but I have remove the folder and war file, when I am trying to restart after copying the war file again, from then onwards it's giving this error not deploying.

regards,
Gourab

**Comment by ghost** [comment]
@codergabs does switching off auto deploy, then copying war and restarting Tomcat help?

**Comment by codergabs** [comment]
@eivantsov 
No, even then also it's throwing ZIPException.

**Comment by ghost** [comment]
Does 'chmod +r' make any difference?

Also, if you deploy it with a clean Tomcat, does it throw the same exception?

**Comment by codergabs** [comment]
@eivantsov 
chmod +r did not work.
In a clean tomcat on my windows machine, the same war do not throw this exception.
There it is working fine

**Comment by ghost** [comment]
Can you share the war itself? It does look like permissions issue.

**Comment by ghost** [comment]
I'd try to play with permissions for parent directories as well.

**Comment by codergabs** [comment]
@eivantsov 
retarting che container worked.
Strange!!!!

**Comment by ghost** [comment]
@codergabs should I close the issue?

**Comment by codergabs** [comment]
@eivantsov 
You can close the issue as I have got the workaround,

But I am intermittently getting the ZipException issue, not only in my installation ,
In another installation of my colleague as well. 
I just restart the container in that case.

Probably if I remove the extracted folder from /webapps and then restart the che tomcat
then it is not extracting again.
Although cannot confirm this reproduction step.

You may look into this for the product improvement perspective.

Thank You for your help.
