### ISSUE TITLE
assembly-ide-war build Error on enabling sample-plugin-nativeaccess

### ISSUE THREAD

**Issue by mutturajKaralatti** [eclipse-che/che#3810]
Enabled the sample-plugin-nativeaccess plug in as per https://github.com/eclipse/che/blob/master/samples/sample-plugin-nativeaccess/README.md
```
Build Error: 
[ERROR] Failed to execute goal on project assembly-ide-war: Could not resolve dependencies for project org.eclipse.che:assembly-ide-war:war:5.0.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.che.sample:che-sample-plugin-nativeaccess-ide:jar:5.0.0-SNAPSHOT: Failed to read artifact descriptor for org.eclipse.che.sample:che-sample-plugin-nativeaccess-ide:jar:5.0.0-SNAPSHOT: Failure to find org.eclipse.che.sample:che-sample-plugin-nativeaccess-parent:pom:5.0.0-SNAPSHOT in https://maven.codenvycorp.com/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of codenvy-public-repo has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project assembly-ide-war: Could not resolve dependencies for project org.eclipse.che:assembly-ide-war:war:5.0.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.che.sample:che-sample-plugin-nativeaccess-ide:jar:5.0.0-SNAPSHOT
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.eclipse.che:assembly-ide-war:war:5.0.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.che.sample:che-sample-plugin-nativeaccess-ide:jar:5.0.0-SNAPSHOT
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
```

Command:
```
 clean install -DskipTests -Dskip-validate-sources -Dgwt.compiler.localWorkers=4 -Dfindbugs.skip=true -X
```
Using eclipse Mars2 for building.

**Comment by TylerJewell** [comment]
@mutturajKaralatti - we released 5.1.0 this morning and when that happens, 5.0.0-SNAPSHOT is no longer a valid set of versions.  It looks like you need to update your repository and your plugin to the latest version in master.  We recommend that you check out a tagged version like 5.1.0 instead of working off master.
