### ISSUE TITLE
Debug Language Servers

### ISSUE THREAD

**Issue by cdietrich** [eclipse-che/che#3925]
How can i debug the messages sent from Che to Language Servers. For me it looks like the Issue from #3127 is there again. If i enable logging on my server i see following open request

```
SEVERE: The property 'languageId' must have a non-null value.                                                                                                                                                                   
org.eclipse.lsp4j.jsonrpc.json.InvalidMessageException: The property 'languageId' must have a non-null value.                                                                                                                   
        at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:41)                                                                                                          
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)                                                                                                                   
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)                                                                                                                           
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)                                                                                                                    
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                                                                                              
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                                             
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                                                                                                      
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                                                                                                      
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by cdietrich** [comment]
i managed to debug here

`DtoServerImpls$DidOpenTextDocumentParamsDTOImpl.fromJsonString(String) line: 4541	
`

```
{"text":"{\n    \n}", "textDocument":{"version":0, "languageId":null, "text":"{\n    \n}", "uri":"/web-php-simple/demo.json"}, "uri":"/web-php-simple/demo.json"}
```

the language id that is passed here is null.
where/how is that string produced. where can i find/debug the opposite end?

**Comment by TylerJewell** [comment]
@cdietrich - I would prefer that one of our systems engineers responded to this request, especially ones that work on our APIs.  But I can give you some starting pointers:

1. With the latest CLI, you can now append `--debug` to the end of your start string. This will launch the Che server with its debugging port on and JPDA.  This allows for direct debugging of the Che server itself.

2. The language server gets deployed inside of a workspace container, and it's running inside of a Tomcat that is inside of a ws-agent. I haven't spent time setting up debuggers for how to connect and debug the server-side code or agents that are running inside of the workspace container, so will need to get an engineer to comment and give specifics on that part.  I'm assuming that you found the agent and language server code in the repository and this is just about how to setup a debugger.

**Comment by TylerJewell** [comment]
@benoitf @skabashnyuk @tolusha - could one of you please offer some setup tips for how to configure and integrate a debugger for a Che server and also one for a running workspace?

Once we have some of these steps, I will add it into the development workflow wiki, as it's not there.

**Comment by cdietrich** [comment]
I can see the bad requests in the web console of my Firefox. Thus I assume the problem is somewhere on the client side. I see the behavior with the Json Lang server open requests as well

**Comment by TylerJewell** [comment]
Asking @evidolob about this as well, because while we have GWT super dev-mode very well documented in the docs, I am not sure we have provided specific steps on how to hook up a debugger for the GWT plugin, which is what is receiving the lang server messages.

**Comment by cdietrich** [comment]
it would be good to get some insides that i understand the intended logic.
where should the language id for the didOpen request come from.
at which point in chain is it injected into the request that is finally sent
to the actual language server.

Here is what i do (Steps to reproduce)

```
git clone https://github.com/eclipse/che.git
cd che
git checkout -b bug 5.1.2
//apply my changes see https://github.com/cdietrich/che/tree/bug
mvn clean install -Pfast
docker run -v /var/run/docker.sock:/var/run/docker.sock -e CHE_DEBUG_SERVER=true -e CHE_ASSEMBLY=/home/dietrich/che-bug/che/assembly/assembly-main/target/eclipse-che-5.1.2/eclipse-che-5.1.2/ codenvy/che-launcher:nightly start
```

go to browser, create php stack and project
lookup the remote debug port and start remote debugging (DidOpenTextDocumentParamsDTOImpl)
create mydsl file.
see the missing language id

it might be that i have a missconfig in my code somewhere as well

**Comment by TylerJewell** [comment]
For that request - we have this tutorial getting drafted this sprint and will publish late next week we hope.  You can follow this issue - https://github.com/eclipse/che-docs/issues/70

**Comment by cdietrich** [comment]
yes that would be nice. yet another question. by looking tightly a the started che dashboard i saw that it starts che 5.0.M8 and not 5.1.2 and i do not know why. do you have any idea what could cause this?

**Comment by cdietrich** [comment]
lol it was a damn brower cache thing. cleaning the brower cache and it worked fine

**Comment by cdietrich** [comment]
sorry for the noise
