### ISSUE TITLE
In some resize test cases xterm.js lose all rows (TypeError).

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#3958]
Logs:
INFO (org.eclipse.che.ide.websocket.ng.impl.MessagesReSender): Going to resend websocket messaged: [{"jsonrpc":"2.0","method":"process.getProcesses","id":"2","params":{"all":false}}]
_app-0.js:5405 INFO (org.eclipse.che.ide.websocket.ng.impl.MessagesReSender): Going to resend websocket messaged: [{"jsonrpc":"2.0","method":"track:project-tree","params":{"type":"START","path":"/"}}]
xterm.js:1214 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
   at r.refresh (xterm.js:1214)
   at xterm.js:1047
xterm.js:1214 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
   at r.refresh (xterm.js:1214)
   at xterm.js:1047
xterm.js:1214 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
   at r.refresh (xterm.js:1214)
   at xterm.js:1047
xterm.js:1214 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
   at r.refresh (xterm.js:1214)
   at xterm.js:1047
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1070 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at r.refresh (http://172.19.20.22:8080/_app/term/xterm.js:1:21680)
   at http://172.19.20.22:8080/_app/term/xterm.js:1:21424
xterm.js:1214 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
   at r.refresh (xterm.js:1214)
   at xterm.js:1047
_app-0.js:4139 WebSocket is already in CLOSING or CLOSED state.
_.Bl @ _app-0.js:4139
_app-0.js:4139 WebSocket is already in CLOSING or CLOSED state.
_.Bl @ _app-0.js:4139
_.Al @ _app-0.js:139
(anonymous) @ _app-0.js:139
(anonymous) @ _app-0.js:6821
_app-0.js:4139 WebSocket is already in CLOSING or CLOSED state.
_.Bl @ _app-0.js:4139
_app-0.js:4139 WebSocket is already in CLOSING or CLOSED state.
_.Bl @ _app-0.js:4139
_.Al @ _app-0.js:139
(anonymous) @ _app-0.js:139
(anonymous) @ _app-0.js:6821

**Comment by AndrienkoAleksandr** [comment]
Issue related and fixed by https://github.com/sourcelair/xterm.js/pull/525 . So I move this fix to our branch.

**Comment by AndrienkoAleksandr** [comment]
Fix applied https://github.com/eclipse/che/pull/3943/commits/e8a3495763214a97aaced1ba538164ac6882555f
