### ISSUE TITLE
superdevmode problem

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4231]
Hi, i'm following this guide to develop eclipse che plugin:
https://www.eclipse.org/che/docs/plugins/setup-che-workspace/index.html 
when i run superdevmode as they say in the guide i have this issue:
Super Dev Mode starting up
   workDir: /tmp/gwt-codeserver-3779897852857031087.tmp
   Loading inherited module 'org.eclipse.che.ide.IDE'
      [ERROR] Unable to find 'org/eclipse/che/ide/IDE.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

**Reproduction Steps: IDE Setup as they say in the guide**

**OS and version: Ubuntu 16.04**    

**Diagnostics:**
Super Dev Mode starting up
   workDir: /tmp/gwt-codeserver-3779897852857031087.tmp
   Loading inherited module 'org.eclipse.che.ide.IDE'
      [ERROR] Unable to find 'org/eclipse/che/ide/IDE.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

**Eclipse Che INFO:**
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
INFO: (che start): Eclipse Che is already running
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Ver: 5.0.0
INFO: (che start): Use: http://172.17.0.1:8080
INFO: (che start): API: http://172.17.0.1:8080/swagger

**Comment by tsmaeder** [comment]
I had the same problem and could solve it by rebuilding everything (mvn clean install in the che root dir) from the command line. The suspicion is that the m2e eclipse build interferes somehow.

**Comment by ahmedchemek** [comment]
@tsmaeder : i rebuilded everything by executing this command (mvn clean install in che root dir) but i have this log:
**[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.388 s
[INFO] Finished at: 2017-03-02T08:45:48+00:00
[INFO] Final Memory: 197M/828M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.6.1:clean (default-clean) on project che-parent: Failed to clean project: Failed to delete /projects/che/target/findbugs -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException**

**Comment by ahmedchemek** [comment]
@tsmaeder i run the same command on codenvy terminal and i have this log : 
**[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:39 min
[INFO] Finished at: 2017-03-02T08:49:30+00:00
[INFO] Final Memory: 235M/987M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project che-core-commons-lang: There are test failures.
[ERROR] 
[ERROR] Please refer to /projects/che/core/commons/che-core-commons-lang/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn  -rf :che-core-commons-lang**

**Comment by tsmaeder** [comment]
@ahmedchemek I really don't know, the failing tests should show up in the log somewhere above the build failure notice. In order to get things going, you might add -DskipTests to the command line to skip unit tests.

**Comment by ghost** [comment]
Has anyone encountered this problem? As I understood Che switched to GWT 2.8.0, I put appropriate GWT 2.8.0 jar-s on classpath but I get exception error. Same happens if I stick to GWT 2.7.0

com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3099)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:352)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:670)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.traverse(LocalDeclaration.java:307)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:347)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1379)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3058)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:141)
	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:985)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:339)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
	at com.google.gwt.dev.Compiler.run(Compiler.java:206)
	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:333)
	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:161)
	at com.google.gwt.dev.codeserver.Recompiler.precompile(Recompiler.java:99)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:96)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
Caused by: java.lang.NullPointerException
	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:99)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.pushNewExpression(GwtAstBuilder.java:2642)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:350)
	... 27 more

**Comment by bmicklea** [comment]
@grunf93 did you try rebuilding everything by executing a mvn clean install on the command line from the che root?

**Comment by slemeur** [comment]
@grunf93 Which IDE are you using?

**Comment by ghost** [comment]
@slemeur  Eclipse Neon
@bmicklea I did, but using flags for incremental build. I will try pure mvn clean install

**Comment by ghost** [comment]
@bmicklea It didn't help.

**Comment by slemeur** [comment]
@grunf93 Have you tried with the GWT Eclipse Plugin v3? (https://gwt-plugins.github.io/documentation/gwt-eclipse-plugin/Download.html)

**Comment by ghost** [comment]
@slemeur after a lot of trouble, I succeded in starting superdevmode it with gwt eclipse plugin. Thanks!
But now I have problem with dashboard I think, as ngTouch module. It won't load, as it's missing, and I am not sure if it has something to do with tests not passing for SVN server module, and for Dashboard while compiling.

**Comment by ghost** [comment]
@slemeur thanks for the tip. With quite a lot fiddling I made everything work.
Thanks for the help.
