### ISSUE TITLE
The Che server is unable to ping your workspace

### ISSUE THREAD

**Issue by kk580kk** [eclipse-che/che#4270]
I used bitnami one key install , and changed ip to static local network ip.

`cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
address 10.25.103.119
netmask 255.255.255.0
gateway 10.25.103.254
dns-nameservers 10.250.243.10 10.250.243.11`

when i started workspaces i got error 
` The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure`
 
and I can see log in '/home/bitnami/apps/eclipseche/che/tomcat/logs/2017/03/01/catalina-0.log'  like this

`
sudo tail -200f /home/bitnami/apps/eclipseche/che/tomcat/logs/2017/03/01/catalina-0.log 
2017-03-01 06:42:01,359[aceSharedPool-0]  [ERROR] [.c.a.w.s.l.WsAgentLauncherImpl 127]  - Fail pinging ws agent. Workspace ID:workspaceg634p0ayw6eggec9. Url:http://localhost:32829/api/. Timestamp:{}
2017-03-01 06:42:01,869[aceSharedPool-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 638]    - org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_121]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$startAsync$1(WorkspaceManager.java:623) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.0.jar:5.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:705) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:249) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0.jar:5.0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_121]
	... 3 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
	at org.eclipse.che.api.workspace.server.launcher.WsAgentLauncherImpl.launch(WsAgentLauncherImpl.java:128) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:633) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:716) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:674) ~[che-core-api-workspace-5.0.0.jar:5.0.0]
	... 6 common frames omitted`

**Comment by kk580kk** [comment]
I found this page and fix the firewall problem
http://serverfault.com/questions/129086/how-to-start-stop-iptables-on-ubuntu

`$ sudo ufw disable`

**Comment by TylerJewell** [comment]
We think you probably should contact Bitnami support for help here.  Bitnami packages the VM and controls the environment.  They customize Che to work within that environment.  So we are not able to diagnose what the root cause could be.

**Comment by kk580kk** [comment]
@TylerJewell  thanks for so fast response
I fixed the problem by 
`sudo ufw disable`

Just write here for helping others.

**Comment by TylerJewell** [comment]
Great - hope you enjoy the product.
