### ISSUE TITLE
GWT superdevmode in Intellij - Error on running the run configuration - java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/LifeCycle

### ISSUE THREAD

**Issue by elpddev** [eclipse-che/che#4423]
Che version: 5.4.1

- Run `mvn clean install -P fast` on the root project.
- Configure Intellij to run superdevmode.
- Run the run configuration

Result:
- Compile pass
- Run of superdevmode failed with the following error:

```bash
Super Dev Mode starting up
   workDir: /tmp/gwt-codeserver-5028683736529175493.tmp
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/LifeCycle
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.gwt.dev.codeserver.SourceHandler.<clinit>(SourceHandler.java:63)
	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:500)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:204)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:191)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:150)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:102)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:664)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:549)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:913)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:430)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.LifeCycle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
Disconnected from the target VM, address: '127.0.0.1:35884', transport: 'socket'

Process finished with exit code 1
```

**Comment by ghost** [comment]
@elpddev can you share a screenshot with your SDM config?

**Comment by elpddev** [comment]
This is the screenshot for the SDM run configuration.

![screenshot_20170315_092139](https://cloud.githubusercontent.com/assets/17731302/23937683/65110158-0961-11e7-893f-21583fb86941.png)

I forgot to mention, I also did the steps to configure the ide pom. Add the gwt-dev and remove `<scope>provided</scope>` from places in the pom.

```xml
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>${com.google.gwt.version}</version>
        </dependency>
```

**Comment by ghost** [comment]
@elpddev can you check if path to your GWT installation is a correct one at File > Project Structure - Facets?

**Comment by elpddev** [comment]
@eivantsov The installation path is correct from what I see. Points to the place I have downloaded and extrcted GWT sdk to.

**Comment by ghost** [comment]
What OS do you use?

**Comment by elpddev** [comment]
I am using kubuntu 16.04.

```bash
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

**Comment by ghost** [comment]
I am on Ubuntu 14. Same config, SDM works fine. Not sure I know what is wrong.

In facets, there are default and all.Is this path provided in both?

**Comment by ghost** [comment]
@elpddev any success with superdevmode?

**Comment by elpddev** [comment]
@eivantsov Thanks for the followup. Currently no change. Our current workflow is without superdevmode for now.

**Comment by ghost** [comment]
At this point I don't know how to help - your SDM config seems to be ok.

**Comment by TylerJewell** [comment]
I propose a live screen share.  That will be the only way to diagnose.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by vitaliy-guliy** [comment]
@elpddev  Have you tried to configure facets?
I have downloaded the gwt, unpacked it and configured the path in both tabs.

![facets](https://cloud.githubusercontent.com/assets/1655894/24400023/8dd5af52-13b7-11e7-8934-172b29a73189.png)

And this is my configuration of SDM

![superdev](https://cloud.githubusercontent.com/assets/1655894/24400114/e94f78ea-13b7-11e7-927e-d41c15765b48.png)

Also it could be helpful to close Idea, clean the cache
```
$ rm -rf ~/.IntelliJIdea14/system/gwt/*
```
Then open Idea, right click on the project and run `Maven > Reimport`

**Comment by ghost** [comment]
@elpddev I'd also try re-importing Che projects and setting up SDM again

**Comment by ghost** [comment]
@elpddev any success with re-importing and setting up SDM?

**Comment by elpddev** [comment]
Thanks for the follow up. Currently we gave up on that setup and continued with other priorities for the project development. When decided, we plan to upgrade the CHE version we started with 5.0.1 to the current one and then try again with SDM. Maybe that will help. Should I close for now the issue ?

**Comment by ghost** [comment]
I'm closing it, but feel free to reopen when you get your hands on SDM again.
