### ISSUE TITLE
Eclipse che Dashboard doesn't load

### ISSUE THREAD

**Issue by ahmed-jelassi11** [eclipse-che/che#4425]
After starting the CHE and going to the address http://localhost:8080/dashboard/#/ in browser , i got a blank black page without even loading.

**OS and version:**    
Linux Ubuntu 14.04 LTS
Eclipse Che : 5.2.2

**Diagnostics:** 
this is the browser console output:

Uncaught Error: [$injector:modulerr] Failed to instantiate module userDashboard due to:
Error: [$injector:modulerr] Failed to instantiate module ngTouch due to:
Error: [$injector:nomod] Module 'ngTouch' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=ngTouch
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:380
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:9978
    at t (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:9451)
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:9763
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18624
    at o (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:806)
    at p (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18472)
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18641
    at o (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:806)
    at p (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18472)
http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=ngTouch&p1=Error%3A….168.1.10%3A8080%2Fdashboard%2Fscripts%2Fvendor-24980a7dc6.js%3A74%3A18472)
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:380
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18900
    at o (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:806)
    at p (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18472)
    at http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18641
    at o (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:806)
    at p (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:18472)
    at et (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:20162)
    at s (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:7505)
    at ae (http://192.168.1.10:8080/dashboard/scripts/vendor-24980a7dc6.js:74:7815)
http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=userDashboard&p1=Er…2.168.1.10%3A8080%2Fdashboard%2Fscripts%2Fvendor-24980a7dc6.js%3A74%3A7815)

**i ran docker with this command :** 
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/ahmed/IdeaProjects/tmp/che5.2.2:/data -v /home/ahmed/IdeaProjects/che:/repo eclipse/che-cli:5.2.2 start --pull --debug

**This is the docker log :**
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using assembly and manifests from your local repository
INFO: (che cli): 5.2.2 - using docker 1.13.1 / native
WARN: Newer version '5.4.1' available
INFO: (che download): Pulling image eclipse/che-init:5.2.2

5.2.2: Pulling from eclipse/che-init

Digest: sha256:b7c255622fb7efb2603b32ada31481c837524b88f96b3f6cd945c77869f11309
Status: Image is up to date for eclipse/che-init:5.2.2

INFO: (che download): Pulling image eclipse/che-server:5.2.2

5.2.2: Pulling from eclipse/che-server
Digest: sha256:1c43b62a101e2122d77a0d619e0d618e8f18073cecd4e77bd4b3d1f15f29799a
Status: Image is up to date for eclipse/che-server:5.2.2

INFO: (che init): Installing configuration and bootstrap variables:
INFO: (che init):   CHE_HOST=192.168.1.10
INFO: (che init):   CHE_VERSION=5.2.2
INFO: (che init):   CHE_CONFIG=/home/ahmed/IdeaProjects/tmp/che5.2.2
INFO: (che init):   CHE_INSTANCE=/home/ahmed/IdeaProjects/tmp/che5.2.2/instance
INFO: (che init):   CHE_REPO=/home/ahmed/IdeaProjects/che
INFO: (che init):   CHE_ASSEMBLY=/home/ahmed/IdeaProjects/tmp/che5.2.2/instance/dev/che-tomcat
INFO: (che config): Generating che configuration...
Notice: Compiled catalog for 9f8657344024 in environment production in 0.48 seconds
Notice: /Stage[main]/Base/File[/opt/che/data]/ensure: created
Notice: /Stage[main]/Base/File[/opt/che/config]/ensure: created
Notice: /Stage[main]/Base/File[/opt/che/logs]/ensure: created
Notice: /Stage[main]/Base/File[/opt/che/templates]/ensure: created
Notice: /Stage[main]/Base/File[/opt/che/stacks]/ensure: created
Notice: /Stage[main]/Che/File[/opt/che/config/che.env]/ensure: defined content as '{md5}d55d8a22e904101d6b4aea9e098262b6'
Notice: /Stage[main]/Compose/Compose::Generate_compose_file[docker-compose-container.yml]/File[/opt/che/docker-compose-container.yml]/ensure: defined content as '{md5}30dca018448b7d8d15bce85e9e1895e1'
Notice: /Stage[main]/Compose/Compose::Generate_compose_file[docker-compose.yml]/File[/opt/che/docker-compose.yml]/ensure: defined content as '{md5}023267c3018161aeb5001a5bfe564856'
Notice: Applied catalog in 0.32 seconds
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che config): Copying local binaries to /home/ahmed/IdeaProjects/tmp/che5.2.2/instance/dev...
INFO: (che start): Preflight checks
WARNING: No swap limit support
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         port 8000 (debug):       [AVAILABLE]
         conn (browser => ws):    [OK]
         conn (server => ws):     [OK]

INFO: (che start): Starting containers...
Creating che
INFO: (che start): Services booting...
Found custom assembly...
Using embedded che.properties... Copying template to /home/ahmed/IdeaProjects/tmp/che5.2.2/instance/data/conf.
Listening for transport dt_socket at address: 8000
2017-03-14 20:35:23,566[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.38
2017-03-14 20:35:23,567[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 6 2016 20:51:55 UTC
2017-03-14 20:35:23,568[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.38.0
2017-03-14 20:35:23,568[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2017-03-14 20:35:23,569[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.4.0-64-generic
2017-03-14 20:35:23,569[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2017-03-14 20:35:23,570[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
2017-03-14 20:35:23,570[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_111-b14
2017-03-14 20:35:23,570[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2017-03-14 20:35:23,571[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /assembly/tomcat
2017-03-14 20:35:23,571[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /assembly/tomcat
2017-03-14 20:35:23,572[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/assembly/tomcat/conf/logging.properties
2017-03-14 20:35:23,573[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2017-03-14 20:35:23,573[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms512m
2017-03-14 20:35:23,573[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+HeapDumpOnOutOfMemoryError
2017-03-14 20:35:23,574[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseConcMarkSweepGC
2017-03-14 20:35:23,574[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+CMSParallelRemarkEnabled
2017-03-14 20:35:23,575[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseCMSInitiatingOccupancyOnly
2017-03-14 20:35:23,576[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+ScavengeBeforeFullGC
2017-03-14 20:35:23,576[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+CMSScavengeBeforeRemark
2017-03-14 20:35:23,577[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.docker.network=bridge
2017-03-14 20:35:23,577[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2017-03-14 20:35:23,578[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/assembly
2017-03-14 20:35:23,578[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/logs
2017-03-14 20:35:23,579[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=debug
2017-03-14 20:35:23,579[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
2017-03-14 20:35:23,579[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2017-03-14 20:35:23,579[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
2017-03-14 20:35:23,579[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2017-03-14 20:35:23,580[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2017-03-14 20:35:23,580[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2017-03-14 20:35:23,580[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/data/conf
2017-03-14 20:35:23,580[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/assembly/tomcat/endorsed
2017-03-14 20:35:23,581[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/assembly/tomcat
2017-03-14 20:35:23,582[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/assembly/tomcat
2017-03-14 20:35:23,582[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/assembly/tomcat/temp
2017-03-14 20:35:24,226[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 443]  - Initializing ProtocolHandler ["http-nio-8080"]
2017-03-14 20:35:24,385[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2017-03-14 20:35:24,390[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 10308 ms
2017-03-14 20:35:24,534[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
2017-03-14 20:35:24,535[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
2017-03-14 20:35:24,536[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38
2017-03-14 20:35:32,435[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /assembly/tomcat/webapps/swagger.war
2017-03-14 20:35:32,691[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /assembly/tomcat/webapps/swagger.war has finished in 247 ms
2017-03-14 20:35:32,739[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /assembly/tomcat/webapps/ROOT.war
2017-03-14 20:35:38,910[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /assembly/tomcat/webapps/ROOT.war has finished in 6,171 ms
2017-03-14 20:35:38,952[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /assembly/tomcat/webapps/docs.war
2017-03-14 20:35:42,003[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /assembly/tomcat/webapps/docs.war has finished in 3,051 ms
2017-03-14 20:35:42,051[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /assembly/tomcat/webapps/wsmaster.war
2017-03-14 20:36:04,038[ost-startStop-1]  [WARN ] [i.f.kubernetes.client.Config 286]    - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2017-03-14 20:36:06,887[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
2017-03-14 20:36:06,978[ost-startStop-1]  [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.0.3 by Boxfuse
2017-03-14 20:36:06,981[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
2017-03-14 20:36:07,069[ost-startStop-1]  [INFO ] [i.f.CustomSqlMigrationResolver 153]  - Searching for sql scripts in locations [classpath:che-schema]
2017-03-14 20:36:07,153[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 4 migrations (execution time 00:00.087s)
2017-03-14 20:36:07,184[ost-startStop-1]  [INFO ] [o.f.c.i.m.MetaDataTableImpl 44]      - Creating Metadata table: "PUBLIC"."schema_version"
2017-03-14 20:36:07,258[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "PUBLIC": << Empty Schema >>
2017-03-14 20:36:07,259[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.8.1 - 1__init.sql
2017-03-14 20:36:07,766[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.9.1 - 1__add_index_on_workspace_temporary.sql
2017-03-14 20:36:07,809[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.9.2 - 2__update_local_links_in_environments.sql
2017-03-14 20:36:07,890[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.2.0.1 - 1__increase_project_attributes_values_length.sql
2017-03-14 20:36:08,007[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Successfully applied 4 migrations to schema "PUBLIC" (execution time 00:00.826s).
2017-03-14 20:36:12,167[ted-scheduler-1]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
2017-03-14 20:36:13,116[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /assembly/tomcat/webapps/wsmaster.war has finished in 31,065 ms
2017-03-14 20:36:13,158[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /assembly/tomcat/webapps/dashboard.war
2017-03-14 20:36:14,002[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /assembly/tomcat/webapps/dashboard.war has finished in 843 ms
2017-03-14 20:36:14,039[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-8080"]
2017-03-14 20:36:14,071[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 49680 ms

**Comment by TylerJewell** [comment]
1. Does this happen in an incognito windows?
2. Does it also happen with eclipse/che:latest image?

**Comment by ahmed-jelassi11** [comment]
**1. It also happens in an in incognito window **

**2. when i used the eclipse/che latest it gave me this output :**
(che cli): /repo mounted - using assembly and manifests from your local repository
/scripts/base/startup_01_init.sh: line 278: /repo/dockerfiles/base/scripts/base/startup_03_pre_networking.sh: No such file or directory

**Comment by TylerJewell** [comment]
Wipe your images with `docker rmi` and re-run, you are getting some image conflicts.

**Comment by ahmed-jelassi11** [comment]
I wiped all the images but the problem is still there.
It Isn't something related to angular.js in the dashboard module ?

**Comment by TylerJewell** [comment]
No shouldn't be.  You are the first person who has reported such an issue. Is this chrome?

**Comment by ahmed-jelassi11** [comment]
I tried chome and firefox and it's the same issue in both.

**Comment by TylerJewell** [comment]
@ashumilova @slemeur @olexii4 --- any thoughts?  See the stack trace from the browser console listed above.  It even happens in Chrome.

**Comment by ghost** [comment]
@ahmed-jelassi11 I wonder if the latest version fixes it for you. Can you try the same with 5.4.1 tag?

Also, can you try not to mount your locally built che? Just drop this `-v`.

**Comment by tsmaeder** [comment]
Some people in our team (me included) have reported seeing this behaviour. The "fix" that seems to work is to pull the latest changes and to rebuild everything. It feels as if the build was not isolated, but depended on something on the internet?

**Comment by ashumilova** [comment]
yes, it depends on third-party stuff, and sometimes have problems with non-compatible transitive dependencies. In latest version should work, but if not - please share the console logs.

**Comment by ghost** [comment]
@tsmaeder that's why I asked if using built in binaries fixes the problem. If it does, then smth's wrong with the locally built binaries.

**Comment by tsmaeder** [comment]
@ashumilova which dependencies would that be?

**Comment by ashumilova** [comment]
https://github.com/eclipse/che/blob/master/dashboard/bower.json#L18 here we have material, that has transitive dependencies. To analyze the current state of dependencies that you have locally - need to execute: 
`bower-dependency-tree`
(https://www.npmjs.com/package/bower-dependency-tree)

**Comment by ahmed-jelassi11** [comment]
@eivantsov I checked out the 5.4.1 tag , built it and ran it and that does not fix the issue and when i didn't use the local binaries all worked fine.

**Comment by ahmed-jelassi11** [comment]
@ashumilova this is the `bower-dependency-tree` output:

+-- che-dashboard#4.0.0
    `-- (dependencies)
        +-- angular#1.4.8 (=1.4.8) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-animate#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-bootstrap#0.13.0 (=0.13.0)
            `-- (dependencies)
                +-- angular#1.6.3 (>=1.3.0) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
        +-- angular-charts#0.2.6 (=0.2.6)
            `-- (dependencies)
                +-- angular#1.6.3 (latest) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
                +-- d3#3.3.13 (~3.3.10)
            `-- (devDependencies)
                +-- angular-mocks#1.2.32 (~1.2.16) (truncated)
        +-- angular-cookies#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-dropdowns#1.0.0 (=1.0.0)
        +-- angular-file-upload#2.0.0 (=2.0.0)
            `-- (dependencies)
                +-- angular#1.2.32 (~1.2.11) (conflicts with ^1.3, >=1.3.0, =1.4.8, ^1.4.8, =1.6.3)
            `-- (devDependencies)
                +-- es5-shim#4.5.9 (>=3.4.0)
        +-- angular-filter#0.5.4 (=0.5.4)
            `-- (dependencies)
                +-- angular#1.6.3 (*) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
            `-- (devDependencies)
                +-- angular-mocks#1.6.3 (*)
                    `-- (dependencies)
                        +-- angular#1.6.3 (=1.6.3) (truncated)
        +-- angular-material#1.0.1 (=1.0.1)
            `-- (dependencies)
                +-- angular#1.6.3 (^1.4.8) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
                +-- angular-animate#1.4.8 (^1.4.8)
                    `-- (dependencies)
                        +-- angular#1.6.3 (=1.6.3) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
                +-- angular-aria#1.6.3 (^1.4.8)
                    `-- (dependencies)
                        +-- angular#1.6.3 (=1.6.3) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
                +-- angular-messages#1.4.8 (^1.4.8)
                    `-- (dependencies)
                        +-- angular#1.6.3 (=1.6.3) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
        +-- angular-messages#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-mocks#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-moment#0.9.0 (=0.9.0)
            `-- (dependencies)
                +-- angular#1.3.20 (>=1.0.0 <1.4.0) (conflicts with ~1.2.11, =1.4.8, ^1.4.8, =1.6.3)
                +-- moment#2.9.0 (>=2.8.0 <2.10.0)
            `-- (devDependencies)
                +-- angular-mocks#1.2.32 (=1.2.x)
                    `-- (dependencies)
                        +-- angular#1.2.32 (=1.2.32) (truncated)
                +-- moment-timezone#0.2.5 (=0.2.5)
                    `-- (dependencies)
                        +-- moment#2.17.1 (>= =2.6.0)
        +-- angular-resource#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-route#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-sanitize#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-touch#1.4.8 (=1.4.8)
            `-- (dependencies)
                +-- angular#1.4.8 (=1.4.8) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.6.3)
        +-- angular-ui-codemirror#0.3.0 (=0.3.0)
            `-- (dependencies)
                +-- angular#1.6.3 (^1.3) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
                +-- codemirror#5.19.0 (^5.0)
        +-- angular-uuid4#0.3.0 (=0.3.0)
            `-- (dependencies)
                +-- angular#1.6.3 (>0.9.0) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
            `-- (devDependencies)
                +-- angular-mocks#1.6.3 (>0.9.0) (truncated)
        +-- angular-websocket#1.0.9 (=1.0.9)
            `-- (dependencies)
                +-- angular#1.6.3 (*) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
            `-- (devDependencies)
                +-- angular#1.3.20 (~1.3.11) (truncated)
                +-- angular-mocks#1.3.20 (~1.3.11)
                    `-- (dependencies)
                        +-- angular#1.3.20 (=1.3.20) (truncated)
        +-- bootstrap-stylus#4.0.2 (=4.0.2)
        +-- codemirror#5.19.0 (=5.19.0)
        +-- font-awesome#4.5.0 (=4.5.0)
        +-- google-material-color#1.2.0 (=1.2.0)
        +-- jquery#2.1.3 (=2.1.3)
            `-- (devDependencies)
                +-- qunit#1.14.0 (=1.14.0)
                +-- requirejs#2.1.10 (=2.1.10)
                +-- sinon#1.8.1 (=1.8.1)
                +-- sizzle#2.1.1-jquery.2.1.2 (=2.1.1-jquery.2.1.2)
        +-- js-yaml#3.6.1 (=3.6.1)
        +-- jsonlint#1.6.0 (=1.6.0)
        +-- ng-clip#0.2.6 (=0.2.6)
            `-- (dependencies)
                +-- angular#1.6.3 (>=1.0.4) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
                +-- zeroclipboard#2.2.0 (~2.2.0)
        +-- ng-lodash#0.2.3 (=0.2.3)
            `-- (dependencies)
                +-- angular#1.6.3 (>=1.2) (truncated) (conflicts with >=1.0.0 <1.4.0, ~1.2.11, =1.4.8)
            `-- (devDependencies)
                +-- angular-mocks#1.6.3 (>=1.2) (truncated)
        +-- zeroclipboard#2.2.0 (=2.2.0) (truncated)

info: Packages with circular dependencies: []
info: Conflicting packages: [angular]

**Comment by ashumilova** [comment]
@ahmed-jelassi11 nothing suspicious from the output. 
1. Did you perform any changes in dashboard?
2. Can you share please following versions: 
`node --version`
`npm --version`

**Comment by ahmed-jelassi11** [comment]
@ashumilova I didn't make any changes in dashboard
`node version` : 4.4.6
`npm version` : 4.3.0

**Comment by vinu** [comment]
same here
fixed following this https://github.com/angular/material/issues/10475
seems the issue with a dependency with material? 

I added "angular-aria": "1.5.8" to the root node of the dependencies. bower.json

**Comment by ahmed-jelassi11** [comment]
@vinu thnaks for your help but this does not fix the issue

**Comment by ashumilova** [comment]
@ahmed-jelassi11 what command do you use to start Che?

**Comment by ahmed-jelassi11** [comment]
@ashumilova now that i upgraded my repo to the 5.4.1 version, i use this command to start Che
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/ahmed/tmp/che-5.4.1:/data -v /home/ahmed/IdeaProjects/che:/repo eclipse/che-cli:latest start --pull --debug`

**Comment by ashumilova** [comment]
@ahmed-jelassi11 can you, please, try 5.5.0, cause 5.4.1 doesn't include following : https://github.com/eclipse/che/blob/5.5.0/dashboard/bower.json#L12

and do you have any of your changes here - **/home/ahmed/IdeaProjects/che** ? 

also as one more workaround can try to skip dashboard build  `mvn -pl '!dashboard' clean install` to avoid your locally installed tools affect.

**Comment by ahmed-jelassi11** [comment]
@ashumilova The issue is now fixed using the 5.5.0 version and skipping the dashboard build
