### ISSUE TITLE
Restarting of workspace broke debug capability to step into dependent classes without sources

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4630]
**Reproduction Steps:**
1. Create and open workspace from java stack.
1. Import project https://github.com/dmytro-ndp/java-with-external-libs.git and configure it as maven project.
1. Restart workspace.
1. Open **SimpleLogger.java** file in editor.
1. Add command "**build and debug**" to the IDE: `mvn -f ${current.project.path} clean install && java -jar -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 ${current.project.path}/target/java-with-external-libs-1.0-SNAPSHOT-jar-with-dependencies.jar`
1. Set debug breakpoint to the line 13 with command `logbackLogger.info("Info from {}", "logbackLogger")`.
1. Execute command "**build and debug**".
1. Call top-menu command "_Run > Debug > Debug 'java-with-external-libs_".
1. Wait until execution is stopped at the breakpoint.
1. Goto _Debug Panel_ and call "**Step Into**" command.

**Expected behavior**
IDE opens decompiled class **Logger**.
![screenshot from 2017-03-29 19 41 58](https://cloud.githubusercontent.com/assets/1197777/24466149/7f09b2a0-14b8-11e7-8362-14fc91b79ad5.png)

**Actual wrong behavior**
IDE went further without opening class **Logger**.
There was error message in log of _ws-agent_:
```
2017-03-29 16:43:33,919[Thread-11]        [ERROR] [o.e.c.p.j.s.EventsCollector 43]      - Type with fully qualified name: ch.qos.logback.classic.Logger was not found
org.eclipse.che.api.debugger.server.exceptions.DebuggerException: Type with fully qualified name: ch.qos.logback.classic.Logger was not found
	at org.eclipse.che.plugin.jdb.server.utils.JavaDebuggerUtils.getLocation(JavaDebuggerUtils.java:76) ~[che-plugin-java-debugger-server-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
	at org.eclipse.che.plugin.jdb.server.JavaDebugger.processStepEvent(JavaDebugger.java:599) ~[che-plugin-java-debugger-server-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
	at org.eclipse.che.plugin.jdb.server.JavaDebugger.handleEvents(JavaDebugger.java:547) ~[che-plugin-java-debugger-server-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
	at org.eclipse.che.plugin.jdb.server.EventsCollector.run(EventsCollector.java:41) ~[che-plugin-java-debugger-server-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```
![screenshot from 2017-03-29 19 44 47](https://cloud.githubusercontent.com/assets/1197777/24466181/9bb2ee12-14b8-11e7-82a1-a1ad45dd21ad.png)

Executing of _Project Explorer_ context menu command "**Maven > Reimport**" fixed issue.

**Screencast**
![out](https://cloud.githubusercontent.com/assets/1197777/24466480/afbfcec4-14b9-11e7-92c4-da5fb21c125c.gif)

**Error reason**
This error was caused by wrong work of next code within the method [org.eclipse.che.plugin.jdb.server.utils.JavaDebuggerUtils#findTypeByFqn()](https://github.com/eclipse/che/blob/e3d59cd8f7f41edd4907da375510650f05c87d64/plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/utils/JavaDebuggerUtils.java#L124-L124) when **JavaDebugger.processStepEvent()** is requesting the type of place to go into:
```
        searchEngine.searchAllTypeNames(packages,
                                        names,
                                        scope,
                                        new TypeNameMatchRequestor() {
                                            @Override
                                            public void acceptTypeNameMatch(TypeNameMatch typeNameMatch) {
                                                result.add(typeNameMatch.getType());
                                            }
                                        },
                                        IJavaSearchConstants.WAIT_UNTIL_READY_TO_SEARCH,
                                        new NullProgressMonitor());
```

**Root problem**
Method [org.eclipse.jdt.internal.core.JavaModelManager#getDeltaState()](https://github.com/eclipse/che/blob/2c412147250a191aaa4d2a4f7dfd748fad13c979/plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/jdt/internal/core/JavaModelManager.java#L395-L395)
returns list without paths to maven dependency _/home/user/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar_.

Actual list of roots:
```{
  /java-with-external-libs/src/main/java=project=java-with-external-libs
path=/java-with-external-libs/src/main/java
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/cldrdata.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/cldrdata.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/nashorn.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/nashorn.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/localedata.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/localedata.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/rt.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/rt.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/jfxrt.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/jfxrt.jar
including=null
excluding=null,
  /java-with-external-libs/src/test/java=project=java-with-external-libs
path=/java-with-external-libs/src/test/java
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/dnsns.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/dnsns.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/sunjce_provider.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/sunjce_provider.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/zipfs.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/zipfs.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/sunpkcs11.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/sunpkcs11.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/sunec.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/sunec.jar
including=null
excluding=null
}
```

Correct list of roots ought to include maven dependencies as well:
```{
  /java-with-external-libs/src/main/java=project=java-with-external-libs
path=/java-with-external-libs/src/main/java
including=null
excluding=null,
  /home/user/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar=project=java-with-external-libs
path=/home/user/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/nashorn.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/nashorn.jar
including=null
excluding=null,
  /java-with-external-libs/src/test/java=project=java-with-external-libs
path=/java-with-external-libs/src/test/java
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/dnsns.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/dnsns.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/sunjce_provider.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/sunjce_provider.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/sunpkcs11.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/sunpkcs11.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/cldrdata.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/cldrdata.jar
including=null
excluding=null,
  /home/user/.m2/repository/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar=project=java-with-external-libs
path=/home/user/.m2/repository/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar
including=null
excluding=null,
  /home/user/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar=project=java-with-external-libs
path=/home/user/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/localedata.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/localedata.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/rt.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/rt.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/jfxrt.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/jfxrt.jar
including=null
excluding=null,
  /home/user/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar=project=java-with-external-libs
path=/home/user/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/zipfs.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/zipfs.jar
including=null
excluding=null,
  /opt/jdk1.8.0_45/jre/lib/ext/sunec.jar=project=java-with-external-libs
path=/opt/jdk1.8.0_45/jre/lib/ext/sunec.jar
including=null
excluding=null
}
```

**Selenium tests**
Temporary workaround (reimport of maven dependencies) should be removed from the [com.codenvy.ide.debugger.DebugExternalClassTest#setup](https://github.com/codenvy/qa/blob/ac955f14036b474d004fe81f3e9cc95e429162dd/src/test/java/com/codenvy/ide/debugger/DebugExternalClassTest.java#L116-L118) after the successful fix of this bug.

**Comment by dmytro-ndp** [comment]
Can't reproduce in Che Version: 5.9.0-SNAPSHOT, Revision: e9aafd7325a817dc, Build Time: 2017-04-14 09:37:59
