### ISSUE TITLE
Internal Server Error  during api request /api/factory/find

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4738]
During ```GET https://codenvy-stg.com/api/factory/find?name=replace&user=ivantsoft```
We have 
```
2017-04-07 11:13:14,480[nio-8080-exec-5]  [INFO ] [o.e.c.a.f.s.jpa.JpaFactoryDao 115]   - FactoryDao#getByAttributes #maxItems: 30 #skipCount: 0, #attributes: [{first=name, second=replace}, {first=user, second=ivantsoft}]                 
2017-04-07 11:13:14,499[nio-8080-exec-5]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-04-07 11:13:14                                                                                     
javax.persistence.RollbackException: Transaction "rolled back" because transaction was set to RollbackOnly.                                                                                                                                   
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:143) ~[eclipselink-2.6.2.jar:2.6.2.v20151217-774c696]                                                                     
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:75) ~[guice-persist-4.1.0.jar:na]                                                                                                          
        at org.eclipse.che.api.factory.server.FactoryManager.getByAttribute(FactoryManager.java:240) ~[che-core-api-factory-5.7.0.jar:5.7.0]                                                                                                  
        at org.eclipse.che.api.factory.server.FactoryService.getFactoryByAttribute(FactoryService.java:279) ~[che-core-api-factory-5.7.0.jar:5.7.0]                                                                                           
        at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[na:na]                                                                                                                                                             
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]                                                                                                                     
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]                                                                                                                                                          
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) ~[everrest-core-1.13.4.jar:na]                                                                                                      
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) ~[everrest-core-1.13.4.jar:na]                                                                                                       
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) ~[everrest-core-1.13.4.jar:na]                                                                                                               
        at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297) ~[everrest-core-1.13.4.jar:na]                                                                                                        
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233) ~[everrest-core-1.13.4.jar:na]                                                                                                                       
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) ~[everrest-core-1.13.4.jar:na]                                                                                                                       
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) ~[everrest-core-1.13.4.jar:na]                                                                                                                 
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.1
```

**Comment by ghost** [comment]
This issue can be still reproduced although this method is used differently by UserDashboard, thus, it occurs only when manually triggering the method.

**Comment by skabashnyuk** [comment]
No longer reproduced.
