### ISSUE TITLE
Unable to restart a workspace: [ERROR] [o.a.c.core.ContainerBase 728] - ContainerBase.addChild: start

### ISSUE THREAD

**Issue by emorency** [eclipse-che/che#4822]
Whenever I try to stop and restart a workspace I have the following error: 

```[STDOUT] 2017-04-17 19:11:18,166[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2017-04-17 19:11:18,242[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 443]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-04-17 19:11:18,253[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2017-04-17 19:11:18,255[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 362 ms
[STDOUT] 2017-04-17 19:11:18,325[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2017-04-17 19:11:18,326[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
[STDOUT] 2017-04-17 19:11:18,326[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38
[STDOUT] 2017-04-17 19:11:18,396[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] 2017-04-17 19:11:18,601[ost-startStop-1]  [ERROR] [o.a.c.core.ContainerBase 728]        - ContainerBase.addChild: start: 
[STDOUT] org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) [catalina.jar:8.0.38]
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
[STDOUT] 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[STDOUT] Caused by: java.lang.NullPointerException: null
[STDOUT] 	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:333) ~[tomcat-util-scan.jar:8.0.38]
[STDOUT] 	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:193) ~[tomcat-util-scan.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1898) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1131) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:783) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5213) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) ~[catalina.jar:8.0.38]
[STDOUT] 	... 10 common frames omitted
[STDOUT] 2017-04-17 19:11:18,609[ost-startStop-1]  [ERROR] [o.a.c.startup.HostConfig 943]        - Error deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) [catalina.jar:8.0.38]
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
[STDOUT] 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[STDOUT] 2017-04-17 19:11:18,613[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 216 ms
[STDOUT] 2017-04-17 19:11:18,618[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-04-17 19:11:18,635[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 379 ms
```

**Reproduction Steps:**

1. Add a new workspace, select Runtime Java or Blank or Python.
2. Save and Open Workspace
3. Stop workspace
4. Open workspace.

**OS and version:**    
I run Eclipse Che 5.8.0 on Linux CentOs 7.

**Diagnostics:** 
I run Eclipse Che with the following command: 
```
docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock -v /home/eclipseche/data:/data eclipse/che:5.8.0 start
```

**Comment by emorency** [comment]
When I open che logs (docker logs -f che), I have the following error: 

```
2017-04-17 19:54:05,927[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 775]    - Workspace 'che/wksp-hw4g' can't be started because: Fail launching agent Exec-agent. Workspace ID:workspacedw3bk1cfzbdqfa8d
```

**Comment by emorency** [comment]
Maybe related. When I re-open a workspace, I often have the following output and then an error message saying that  Exec-agent failed launching.

```
[STDOUT] 2017/04/18 14:24:43 remove /home/user/che/exec-agent/logs/1: directory not empty
```

![image](https://cloud.githubusercontent.com/assets/2565497/25136229/64740502-2422-11e7-8616-161bf7c53888.png)

Thanks !

**Comment by ghost** [comment]
Do you have SElinux enabled?

Also, can you try it again but with a slightly different volume mount:

`-v /home/eclipseche/data:/data:Z`

**Comment by emorency** [comment]
Yes, I have SELinux enabled. 

Tried with the new volume suggestion and by disabling SELinux but I still have issues when I try to re-open a workspace. Here is the full log (notice the [STDERR] rm: cannot remove '/home/user/che...)

```
[STDOUT] 2017/04/18 18:11:33 Exec-agent configuration
[STDOUT] 2017/04/18 18:11:33   Server
[STDOUT] 2017/04/18 18:11:33     - Address: :4412
[STDOUT] 2017/04/18 18:11:33     - Base path: ''
[STDOUT] 2017/04/18 18:11:33   Process executor
[STDOUT] 2017/04/18 18:11:33     - Logs dir: /home/user/che/exec-agent/logs
[STDOUT] 2017/04/18 18:11:33 
[STDOUT] 2017/04/18 18:11:33 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/04/18 18:11:33 Process Routes:
[STDOUT] 2017/04/18 18:11:33 ✓ Start Process ........................... POST   /process
[STDOUT] 2017/04/18 18:11:33 ✓ Get Process ............................. GET    /process/:pid
[STDOUT] 2017/04/18 18:11:33 ✓ Kill Process ............................ DELETE /process/:pid
[STDOUT] 2017/04/18 18:11:33 ✓ Get Process Logs ........................ GET    /process/:pid/logs
[STDOUT] 2017/04/18 18:11:33 ✓ Get Processes ........................... GET    /process
[STDOUT] 2017/04/18 18:11:33 
[STDOUT] 2017/04/18 18:11:33 Channel Routes:
[STDOUT] 2017/04/18 18:11:33 ✓ Connect to Exec-Agent(webscoket) ........ GET    /connect
[STDOUT] 2017/04/18 18:11:33 
[STDOUT] 2017/04/18 18:11:33 ⇩ Registered RPCRoutes:
[STDOUT] 
[STDOUT] 2017/04/18 18:11:33 Process Routes:
[STDOUT] 2017/04/18 18:11:33 ✓ process.start
[STDOUT] 2017/04/18 18:11:33 ✓ process.kill
[STDOUT] 2017/04/18 18:11:33 ✓ process.subscribe
[STDOUT] 2017/04/18 18:11:33 ✓ process.unsubscribe
[STDOUT] 2017/04/18 18:11:33 ✓ process.updateSubscriber
[STDOUT] 2017/04/18 18:11:33 ✓ process.getLogs
[STDOUT] 2017/04/18 18:11:33 ✓ process.getProcess
[STDOUT] 2017/04/18 18:11:33 ✓ process.getProcesses
[STDOUT] 2017/04/18 18:11:35 Terminal-agent configuration
[STDOUT] 2017/04/18 18:11:35   Server
[STDOUT] 2017/04/18 18:11:35     - Address: :4411
[STDOUT] 2017/04/18 18:11:35     - Base path: ''
[STDOUT] 2017/04/18 18:11:35   Terminal
[STDOUT] 2017/04/18 18:11:35     - Slave command: '/bin/bash'
[STDOUT] 2017/04/18 18:11:35     - Activity tracking enabled: false
[STDOUT] 2017/04/18 18:11:35 
[STDOUT] 2017/04/18 18:11:35 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/04/18 18:11:35 Terminal routes:
[STDOUT] 2017/04/18 18:11:35 ✓ Connect to pty(webscoket) ............... GET    /pty
[STDOUT] 2017/04/18 18:11:35 
[STDERR] rm: cannot remove '/home/user/che/ws-agent/bin': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/conf/Catalina': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/endorsed': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/lib': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/logs/2017/04/18': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/maven-server': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/temp/indexes': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/META-INF/maven/org.eclipse.che/assembly-wsagent-war': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/codenvy': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/org/eclipse/che/wsagent/server': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/work/Catalina/localhost': Directory not empty
[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2017-04-18 18:11:39,105[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.38
[STDOUT] 2017-04-18 18:11:39,108[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 6 2016 20:51:55 UTC
[STDOUT] 2017-04-18 18:11:39,108[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.38.0
[STDOUT] 2017-04-18 18:11:39,108[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2017-04-18 18:11:39,109[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-514.16.1.el7.x86_64
[STDOUT] 2017-04-18 18:11:39,109[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2017-04-18 18:11:39,109[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
[STDOUT] 2017-04-18 18:11:39,109[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13
[STDOUT] 2017-04-18 18:11:39,109[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2017-04-18 18:11:39,110[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2017-04-18 18:11:39,110[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2017-04-18 18:11:39,110[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2017-04-18 18:11:39,110[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2017-04-18 18:11:39,111[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2017-04-18 18:11:39,111[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
[STDOUT] 2017-04-18 18:11:39,111[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2017-04-18 18:11:39,111[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2017-04-18 18:11:39,111[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
[STDOUT] 2017-04-18 18:11:39,111[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
[STDOUT] 2017-04-18 18:11:39,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2017-04-18 18:11:39,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2017-04-18 18:11:39,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2017-04-18 18:11:39,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2017-04-18 18:11:39,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2017-04-18 18:11:39,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2017-04-18 18:11:39,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2017-04-18 18:11:39,113[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2017-04-18 18:11:39,113[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2017-04-18 18:11:39,207[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 443]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-04-18 18:11:39,219[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2017-04-18 18:11:39,230[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 415 ms
[STDOUT] 2017-04-18 18:11:39,251[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2017-04-18 18:11:39,252[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
[STDOUT] 2017-04-18 18:11:39,252[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38
[STDOUT] 2017-04-18 18:11:39,309[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] 2017-04-18 18:11:39,531[ost-startStop-1]  [ERROR] [o.a.c.core.ContainerBase 728]        - ContainerBase.addChild: start: 
[STDOUT] org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) [catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) [catalina.jar:8.0.38]
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
[STDOUT] 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[STDOUT] Caused by: java.lang.NullPointerException: null
[STDOUT] 	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:333) ~[tomcat-util-scan.jar:8.0.38]
[STDOUT] 	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:193) ~[tomcat-util-scan.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1898) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1131) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:783) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5213) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) ~[catalina.jar:8.0.38]
[STDOUT] 	... 10 common frames omitted
[STDOUT] 2017-04-18 18:11:39,532[ost-startStop-1]  [ERROR] [o.a.c.startup.HostConfig 943]        - Error deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) ~[catalina.jar:8.0.38]
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) [catalina.jar:8.0.38]
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
[STDOUT] 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[STDOUT] 2017-04-18 18:11:39,552[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 242 ms
[STDOUT] 2017-04-18 18:11:39,559[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-04-18 18:11:39,570[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 339 ms
```

**Comment by ghost** [comment]
@emorency can you tell more about your environment? Is `/home/eclipseche/data` by any chance NFC volume? Can you run `sudo chmod -R 777 /home/eclipseche/data` on your host ans try it again?

And what's your Docker version please?

**Comment by emorency** [comment]
This is a VM server. The hard disk is a vmfs volume.

Tried the chmod approach and re-opened the workspace, still the same errors (see https://github.com/eclipse/che/issues/4822#issuecomment-294935090).

`Docker version 17.04.0-ce, build 4845c56`

Thank you!

**Comment by ghost** [comment]
Can you stop Che, and re-start it with a mount that is not a vmfs volume? Just -v `/che-data:/data`.

**Comment by emorency** [comment]
I'm not sure that I can use another storage than a vmfs volume... The volume is not specific to this folder, the whole VM uses this vmfs volume.

**Comment by ghost** [comment]
Well, I tried a clean CentOS instance and as expected it worked for me. My suspicion is that vmfs is the trouble maker here. Can you run a simple test?

```
docker run --name test -d -v /nonexistingvolume:/data/test alpine tail -f /dev/null
docker exec -ti test sh
cd /data/test
touch newfile
exit
docker stop test
docker start test
docker exec -ti test sh
cd /data/test
rm newfile
```
Can you delete the file you have created?

**Comment by TylerJewell** [comment]
While it is not directly related to this specific issue, watching this thread had me think more about this issue - https://github.com/eclipse/che/issues/3936.  We are going to investigate this issue in our next sprint.  While not a perfect answer to this particular problem, if we solve this, then it would be a partial solution for you as well.

**Comment by ghost** [comment]
But a named volume is a directory on a filesystem, somewhere deep in /var/lib/docker. I doubt it will solve this particular issue where the entire VM filesystems is a vmfs volume mounted into another filesystem.

Let's see if the test I proposed returns positive results.

**Comment by TylerJewell** [comment]
I don't want to take away from this particular user's objective.  But the idea behind named data volumes is that the admin of the system can then take direct control using docker syntax on where to move the physical volume that maps to /data to, as opposed to us forcing it upon them during the system boot.  And since it would be done virtually to start with (some limitations on what you can control) it at least gets the system booted for testing while admin explores their longer term storage requirements.

**Comment by emorency** [comment]
The creation/deletion of the file worked... I was able to delete the file after a stop/start.

**Comment by ghost** [comment]
Can you run the same test but this time delete a directory that contains a file?

**Comment by ghost** [comment]
And please provide output from `docker info`

**Comment by emorency** [comment]
Trying to delete a non-empty folder fails.

```
/ # rm -r /data/test
rm: can't remove '/data/test': Resource busy
```

docker info: 
```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 59
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702GiB
Name: .......
ID: IVOJ:ZWOV:LHKV:O42H:7IUX:YJGJ:TVO6:7SG7:CDNJ:UYMM:VRIH:VS6A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
```

**Comment by ghost** [comment]
Resource is busy is expected. 

What is alarming though:

> WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
>          Reformat the filesystem with ftype=1 to enable d_type support.
>          Running without d_type support will not be supported in future releases.

Here's a thread that is rather close to what we're trying to solve: https://github.com/moby/moby/issues/31321

**Comment by emorency** [comment]
Yes, thanks for pointing that out! I'll look into it.

**Comment by ghost** [comment]
@emorency any update or progress made?

**Comment by ghost** [comment]
Closed due to inactivity. Feel free to reopen if the provided suggestions never helped.
