### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5034]
We're getting the below error on a "Blank" project type, shortly after opening the workspace. Any thoughts?

```
[STDOUT] 2017-05-10 10:06:52,939[nio-4401-exec-9]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-05-10 10:06:52
[STDOUT] java.lang.NullPointerException: null
[STDOUT] 	at org.eclipse.che.plugin.composer.server.projecttype.ComposerValueProviderFactory$ComposerValueProvider.getValues(ComposerValueProviderFactory.java:58)
[STDOUT] 	at org.eclipse.che.api.project.server.type.ProjectTypeDef.resolveSources(ProjectTypeDef.java:188)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectManager.estimateProject(ProjectManager.java:542)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectManager.resolveSources(ProjectManager.java:563)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectService.resolveSources(ProjectService.java:315)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDOUT] 	at java.lang.reflect.Method.invoke(Method.java:498)
[STDOUT] 	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
[STDOUT] 	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
[STDOUT] 	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
[STDOUT] 	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
[STDOUT] 	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
[STDOUT] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
[STDOUT] 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
[STDOUT] 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
[STDOUT] 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
[STDOUT] 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
[STDOUT] 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
[STDOUT] 	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:290)
[STDOUT] 	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:157)
[STDOUT] 	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)
[STDOUT] 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
[STDOUT] 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
[STDOUT] 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
[STDOUT] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
[STDOUT] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
[STDOUT] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
[STDOUT] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
[STDOUT] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
[STDOUT] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
[STDOUT] 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
[STDOUT] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
[STDOUT] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
[STDOUT] 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
[STDOUT] 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
[STDOUT] 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
[STDOUT] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
[STDOUT] 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
```

`eclipse/che-server:nightly`

**Comment by ghost** [comment]
@davidwindell perhaps you may provide some steps to reproduce?

**Comment by davidwindell** [comment]
@eivantsov I was able to reproduce by creating a blank PHP project and then creating this file in the project:

https://raw.githubusercontent.com/aws/aws-sdk-php/master/src/data/iam/2010-05-08/api-2.json.php

I wouldn't expect the json scanner to fail hard on syntax issues? (or scan.json.php files for that matter either)

**Comment by gazarenkov** [comment]
Let's assign it to @vparfonov he can sort it out and assign, it looks like a simple issue around exceptional situation processing:
`model.get("name").getAsString();`

where apparently either model or "name" element is null
