### ISSUE TITLE
Import recursively a project does not work (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#5178]
**Reproduction Steps:**

* Open the IDE, go to 'Workspace' > 'ImportProject' (e.g._https://github.com/idexmai/ProjectGitSubmodule.git_)
* Set on the checkbox 'Import recursively'
* Try to import the project

**Expected behavior:**
* the project should be imported

**Observed behavior:**
* import does not work

**Che version:** 5.11.0
**OS and version:** Ubuntu 14.04
**Docker version:** 1.13
**Che install:** Docker container 

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment: 
![imoprt_recursively](https://cloud.githubusercontent.com/assets/5408906/26362013/664148b6-3fe5-11e7-964c-7cd84e48caa8.png)

**Comment by riuvshin** [comment]
in ws agent logs: 
```[STDOUT] 2017-05-24 10:48:24,619[y Machine API-0]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-05-24 10:48:24
[STDOUT] org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown 480cc834e2eca744a6131fd383ce2e4bc202548f
[STDOUT] 	at org.eclipse.jgit.api.SubmoduleUpdateCommand.call(SubmoduleUpdateCommand.java:211)
[STDOUT] 	at org.eclipse.jgit.api.CloneCommand.cloneSubmodules(CloneCommand.java:274)
[STDOUT] 	at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:261)
[STDOUT] 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:137)
[STDOUT] 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:84)
[STDOUT] 	at org.eclipse.che.git.impl.jgit.JGitConnection.executeRemoteCommand(JGitConnection.java:1772)
[STDOUT] 	at org.eclipse.che.git.impl.jgit.JGitConnection.clone(JGitConnection.java:517)
[STDOUT] 	at org.eclipse.che.api.git.GitProjectImporter.cloneRepository(GitProjectImporter.java:250)
[STDOUT] 	at org.eclipse.che.api.git.GitProjectImporter.importSources(GitProjectImporter.java:185)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectManager.doImportProject(ProjectManager.java:492)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectManager.importProject(ProjectManager.java:462)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectService.importProject(ProjectService.java:354)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDOUT] 	at java.lang.reflect.Method.invoke(Method.java:498)
[STDOUT] 	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
[STDOUT] 	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
[STDOUT] 	at org.everrest.core.impl.method.MethodInvokerDecorator.invokeMethod(MethodInvokerDecorator.java:39)
[STDOUT] 	at org.eclipse.che.everrest.WebSocketMethodInvokerDecorator.invokeMethod(WebSocketMethodInvokerDecorator.java:51)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
[STDOUT] 	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
[STDOUT] 	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
[STDOUT] 	at org.everrest.websockets.WS2RESTAdapter$1.run(WS2RESTAdapter.java:141)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
[STDOUT] Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 480cc834e2eca744a6131fd383ce2e4bc202548f
[STDOUT] 	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145)
[STDOUT] 	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:226)
[STDOUT] 	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
[STDOUT] 	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
[STDOUT] 	at org.eclipse.jgit.api.SubmoduleUpdateCommand.call(SubmoduleUpdateCommand.java:175)
[STDOUT] 	... 29 common frames omitted
[STDOUT] 2017-05-24 10:48:28,910[ted-scheduler-1]  [ERROR] [o.e.c.a.v.w.FileWatcherService 199]  - Can't register dir /projects/ProjectGitSubmodule in file watch service
[STDOUT] java.nio.file.NoSuchFileException: /projects/ProjectGitSubmodule
[STDOUT] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[STDOUT] 	at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
[STDOUT] 	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
[STDOUT] 2017-05-24 10:48:28,914[ted-scheduler-1]  [ERROR] [o.e.c.a.v.w.FileWatcherService 199]  - Can't register dir /projects/ProjectGitSubmodule/Repo_For_Test in file watch service
[STDOUT] java.nio.file.NoSuchFileException: /projects/ProjectGitSubmodule/Repo_For_Test
[STDOUT] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[STDOUT] 	at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
[STDOUT] 	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
[STDOUT] 2017-05-24 10:48:28,917[ted-scheduler-1]  [ERROR] [o.e.c.a.v.w.FileWatcherService 199]  - Can't register dir /projects/ProjectGitSubmodule/.git in file watch service
[STDOUT] java.nio.file.NoSuchFileException: /projects/ProjectGitSubmodule/.git
[STDOUT] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[STDOUT] 	at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
[STDOUT] 	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)```

**Comment by riuvshin** [comment]
@artaleks9 It seems your test project is broken. because I can clone this multi module project without any issue https://github.com/jamesward/maven-multi-module-example

**Comment by vinokurig** [comment]
One of the submodules in the cloned project has invalid clone url
