### ISSUE TITLE
CHE-614 Max size of message queue exceeded during starting workspace in Che

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#522]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-614
Reporter:  Vitaliy Parfonov
Description: {noformat}
java.io.IOException: Max size of message queue exceeded
        at org.everrest.websockets.message.MessageSender.send(MessageSender.java:65) ~[everrest-websockets-1.12.0.jar:na]
        at org.everrest.websockets.message.MessageSender.send(MessageSender.java:48) ~[everrest-websockets-1.12.0.jar:na]
        at org.everrest.websockets.WSConnectionImpl.sendMessage(WSConnectionImpl.java:174) ~[everrest-websockets-1.12.0.jar:na]
        at org.everrest.websockets.WSConnectionContext.sendMessage(WSConnectionContext.java:63) ~[everrest-websockets-1.12.0.jar:na]
        at org.eclipse.che.api.core.util.WebsocketLineConsumer.writeLine(WebsocketLineConsumer.java:41) ~[che-core-api-core-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:45) [che-core-api-core-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:44) [che-plugin-docker-machine-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:26) [che-plugin-docker-machine-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.LogMessagePumper.start(LogMessagePumper.java:75) [che-plugin-docker-client-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.plugin.docker.client.DockerConnector.startExec(DockerConnector.java:570) [che-plugin-docker-client-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.plugin.docker.machine.DockerProcess.start(DockerProcess.java:144) [che-plugin-docker-machine-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager.lambda$exec$4(MachineManager.java:645) [che-core-api-machine-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.api.machine.server.MachineManager$$Lambda$54/1966846577.run(Unknown Source) [che-core-api-machine-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
{noformat}

**Comment by skabashnyuk** [comment]
https://github.com/eclipse/che-dependencies/pull/2
