### ISSUE TITLE
How To Start Eclipse Che 5.10 or onwards in a VM Environment

### ISSUE THREAD

**Issue by imveejay** [eclipse-che/che#5244]
Trying to startup Eclipse Che Version 5.10 or onwards in Docker installed in a VM Environment using the command below:

docker run -it --rm -e CHE_PORT=18080 -v /var/run/docker.sock:/var/run/docker.sock -v ~/eclipse-che:/data eclipse/che start

I manage to startup Eclipse Che but there is an issue when creating a workspace.

**OS and version:**    
VM OS Version: Linux version 3.10.0-514.16.1.el7.x86_64 
(builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Apr 12 15:04:24 UTC 2017

**Comment by ghost** [comment]
@imveejay provide more details on

`I manage to startup Eclipse Che but there is an issue when creating a workspace.
`

**Comment by imveejay** [comment]
@eivantsov 
I start Eclipse Che using the command below:
**docker run -it --rm -e CHE_PORT=18080 -v /var/run/docker.sock:/var/run/docker.sock -v ~/che5.11:/data eclipse/che:5.11.2 start**


After I create a workspace:

Error when starting agent
Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment 'default' failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.

Logs:
2017-05-31 08:30:36,314[aceSharedPool-0]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 127]   - Fail pinging ws agent with http://192.168.208.61:33114/api/ url in workspace1j2q312mifx8nkk1 workspace in machine0hul1kd8321medax machine on localhost node.
2017-05-31 08:30:40,773[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:132)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:819)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:268)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:712)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:977)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:941)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ghost** [comment]
Is the ephemeral port range opened in your VM?

**Comment by imveejay** [comment]
@eivantsov  yes

**Comment by ghost** [comment]
The problem is that Che server fails to reach ws agent at `http://192.168.208.61:33114/api/`.

Can you run a simple test?

`docker run -d nginx -p 33117:80`

In your browser, go to 192.168.208.61:33117, you should see nginx welcome page

Then:

`docker run -ti appropriate/curl sh`
`curl -v 192.168.208.61:33117`

Can you reach nginx from `curl` container?

**Comment by imveejay** [comment]
@eivantsov 

Run Command:
docker run -d nginx -p 33117:80

Output:
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
ff3d52d8f55f: Pull complete
226f4ec56ba3: Pull complete
53d7dd52b97d: Pull complete
Digest: sha256:41ad9967ea448d7c2b203c699b429abe1ed5af331cd92533900c6d77490e0268
Status: Downloaded newer image for nginx:latest
e5ed304dc35d3421acbda4ca06ef4b01153e56f10c8a8e7ade4491fdfa34de3d
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"-p\": executable file not found in $PATH".

**Comment by ghost** [comment]
Sorry, it should be this command: 
`docker run -d -p 33117:80 nginx`

**Comment by imveejay** [comment]
@eivantsov 

COMMAND:
docker run -ti appropriate/curl sh

OUTPUT:
/ # curl -v 192.168.208.61:33117
* Rebuilt URL to: 192.168.208.61:33117/
*   Trying 192.168.208.61...
* TCP_NODELAY set
* connect to 192.168.208.61 port 33117 failed: Host is unreachable
* Failed to connect to 192.168.208.61 port 33117: Host is unreachable
* Closing connection 0
curl: (7) Failed to connect to 192.168.208.61 port 33117: Host is unreachable
docker run -ti appropriate/curl sh
/ # curl -v 192.168.208.61:33117
* Rebuilt URL to: 192.168.208.61:33117/
*   Trying 192.168.208.61...
* TCP_NODELAY set
* connect to 192.168.208.61 port 33117 failed: Host is unreachable
* Failed to connect to 192.168.208.61 port 33117: Host is unreachable
* Closing connection 0
curl: (7) Failed to connect to 192.168.208.61 port 33117: Host is unreachable

**Comment by ghost** [comment]
This is the problem. Containers on your host cannot communicate with one another (as you can see, Che isn't involved here).

Maybe you may want to disable firewall or play with iptables.

**Comment by imveejay** [comment]
@eivantsov but for other projects that i did, i manage to communicate containers. for example, i connected a wildfly container to a mysql container.

Am I missing any flag or property on this command:
docker run -it --rm -e CHE_PORT=18080 -v /var/run/docker.sock:/var/run/docker.sock -v ~/eclipse-che:/data eclipse/che start ??

**Comment by ghost** [comment]
No, you do not miss anything. You have run a test with just nginx and curl containers where they cannot communicate using an external IP. For wildfly and mysql, you probably use internal IPs.

**Comment by imveejay** [comment]
@eivantsov 

you mentioned in this article https://github.com/eclipse/che/issues/1226

![image](https://cloud.githubusercontent.com/assets/29058984/26624006/2641e7fa-4622-11e7-8f88-86a5e6b5fc99.png)

that is why I asked if I'm missed something.

**Comment by ghost** [comment]
Che CLI runs in a Docker container, and it auto detects IP. Is 192.168.208.61 correct in your case?

**Comment by imveejay** [comment]
yes.

**Comment by ghost** [comment]
You need to make sure that the nginx-curl test runs ok. The problem is that when a connection is initiated from a container, using external IP, connection fails.

What you can try is:

in `~/eclipse-che/che.env`

```
CHE_HOST=$internal_ip // it can be docker0
CHE_DOCKER_IP_EXTERNAL=192.168.208.61

```

Restart Che. 

You may also skip editing file, and pass those as envs in your docker run syntax (-e)

**Comment by imveejay** [comment]
@eivantsov 

I tried adding those envs in the docker run syntax and below are the output:

INFO: (che start): Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 18080 (http):        [AVAILABLE]
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]


INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (***.**.0.0): Connection failed
INFO: (che network): Server  => Workspace Agent (External IP): Connection failed
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded

**Comment by ghost** [comment]
@imveejay did you use `docker0` IP in `CHE_HOST`?

Once again, everything that involves the ephemeral port range and communication between containers using an external IP is blocked in your VM.

**Comment by imveejay** [comment]
yes. i got the docker0 IP using 'info --bundle' during docker run.

**Comment by thyeun** [comment]
@imveejay, this is related with your CHE_HOST ip, you need to open the che.env file, and change the CHE_HOST ip with the correct docker0 ip address

an example, if your docker0 ip = 123.123.123.123, than your CHE_HOST ip will be 123.123.123.123

hope you get what i trying yo explain here (i hv the same issue before).

**Comment by ghost** [comment]
@imveejay I will repeat it again - the problem is that Docker containers on your host cannot communicate with each other using an external IP. You need to investigate what network/firewall rules impose such restrictions. Once nginx-curl test passed, Che will run flawlessly. 

Here's iptables config that is used for Codenvy (which is based on Eclipse Che):

```
*filter
:FORWARD ACCEPT
:INPUT DROP
:OUTPUT ACCEPT
:I-ICMP -
:f2b-SSH - [0:0]
-A INPUT -p tcp -m tcp --dport 22                                                -j f2b-SSH
-A INPUT                -m state --state ESTABLISHED,RELATED                     -j ACCEPT
-A INPUT        -i lo   -m state --state NEW                                     -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 22                          -j ACCEPT
-A INPUT         -m state --state NEW -p tcp -m tcp -s 172.16.0.0/12 --dport 25  -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 80                          -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 443                         -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 2379                          -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 2181                          -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 5000                          -j ACCEPT
-A INPUT         -m state --state NEW -p tcp -s 0.0.0.0/0 --dport 2375    -j ACCEPT
-A INPUT         -m state --state NEW -p tcp -s 0.0.0.0/0 --dport 23750   -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 10050                       -j ACCEPT
-A INPUT         -m state --state NEW -p tcp --dport 32768:65535                 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 4789 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 7946 -j ACCEPT
-A INPUT -m state --state NEW -m udp -p udp --dport 7946 -j ACCEPT
-A INPUT         -m state --state NEW -p icmp                                    -j I-ICMP
-A INPUT         -p tcp -m multiport --dports 135,136,137,138,139,445,1433       -j DROP
-A INPUT         -p udp -m multiport --dports 135,136,137,138,139,445,1433       -j DROP
#-A INPUT                                                                        -j LOG
# ------------------------------------------
-A I-ICMP       -m length --length 550:65535                                     -j REJECT --reject-with icmp-admin-prohibited
-A I-ICMP -m hashlimit --hashlimit-name ICMP --hashlimit-mode srcip --hashlimit 10/s --hashlimit-burst 32 --hashlimit-htable-expire 120000 --hashlimit-htable-max 512 -j ACCEPT
-A I-ICMP                                                                        -j LOG --log-prefix "-DDoS ICMP-"
-A I-ICMP                                                                        -j DROP
COMMIT
```

**Comment by thyeun** [comment]
@imveejay forgot to mention, i dont think that 192.168.208.61 is your correct docker0 ip address, try to double check again your docker0 ip address

**Comment by ghost** [comment]
It should be 172.17.x.x smth like that

**Comment by thyeun** [comment]
@eivantsov yes, always start with 172.X.X.X

**Comment by imveejay** [comment]
I think it is already a network config issue. These are the changes that I made in che.env
![image](https://cloud.githubusercontent.com/assets/29058984/26669370/2c2da8d4-46e0-11e7-8160-887c3ae297d6.png)

![image](https://cloud.githubusercontent.com/assets/29058984/26669397/471c19b4-46e0-11e7-9ef9-0677bb1ca046.png)

**Comment by ghost** [comment]
Start Che with `--skip:preflight`

**Comment by ghost** [comment]
Closing due to inactivity. Feel free to reopen if the issue persists.
