### ISSUE TITLE
How to deploy an application built on top of che without using source code repo?

### ISSUE THREAD

**Issue by SanthoshHari912** [eclipse-che/che#5370]
Hello,

 Am playing around with Eclipse Che. I have the following usecase.
1.Deploy a WAR file in to che server's IDE container. The WAR file has UI + services that interact with Che Workspace server.
2. Am starting the che docker container in the following way
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v /c/Users/myuser/che_data:/data \
            -v /c/Users/myuser/che:/repo \
            -e CHE_LOCAL_BINARY=/c/Users/myuser/che/assembly/assembly-main/target/eclipse-che-5.8.1/eclipse-che-5.8.1 \
            eclipse/che:5.8.1 start \
             
In case if am not specifying the repo( the sources), there's a problem starting the docker container. Do we need the sources to build the container ? Are the che_local_binary is not sufficient for the docker container to start up? 

What would be an ideal way to deploy the che for production ?

Also I want to know is there a way, I could get access to the tomcat container of the che server to deploy WAR files.

Regards
Santhosh

**Comment by vnea** [comment]
Hello,

You should use [Archetype](https://www.eclipse.org/che/docs/assemblies/archetype/index.html) to generate, build and run a custom assembly.
You can have more information about Archetype in this [issue](https://github.com/eclipse/che/issues/5054).

But for the moment you may be able to run your custom CHE assembly with this [command](https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#run) (the second one of the link) if you just want to debug:
```bash
# DON'T FORGET TO REPLACE WITH YOUR DATA
docker run -it --rm --name run-che \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /c/Users/myuser/che_data:/data \
           -v /c/Users/myuser/che/assembly/assembly-main/target/eclipse-che-5.8.1/eclipse-che-5.8.1:/assembly \
              eclipse/che:5.8.1 start --skip:nightly"
```

For production mode, just follow [this guide](https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#production-mode).

**Comment by TylerJewell** [comment]
@SanthoshHari912 - we do not allow engineers to deploy WAR files into the Che Tomcat directly. We do that by design to enforce that developers follow a good development workflow by working with Docker images. We used to have our internal engineers to only start the Tomcat server, but when doing that they were introducing issues that they were unaware of that only appear when running the Dockerized version.

I think your particular issue is that if you mount `:/repo`, then that always uses the source repository.  You should use that or `CHE_LOCAL_BINARY`, but not both together.

**Comment by ghost** [comment]
@SanthoshHari912 you may build your own Che CLI that injects your custom built binaries into che-server image - https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#production-mode

**Comment by SanthoshHari912** [comment]
Thank you for the suggestion guys !! @TylerJewell : I have both the requirements 
1. I don't want to deploy the sources on production 
2. Am deploying angular based webapp into the tomcat . Here the UI is based on the App I write and I utilize the workspace from the workspace server.  
The usecase here is to create a platform(based on che) which enables the user to customize their UI based on their needs and utilize the workspace infrastructure from Che.
For the same, the user ll be writing a JS based web app which will contact the Che workspace server through REST APIs. So if there is a provision to deploy the webapps directly on tomcat container in the docker image it will be helpful.

If I give CHE_LOCAL_BINARY without mount:/repo,  I don't see the log for the copying the local binaries to the che_local_binary location and I assume the docker image is not picking up the local binary properly.

I haven't tried Archetype yet, but it will be very helpful if am able to use only che_local_binary for production without implementing archetype.

**Comment by SanthoshHari912** [comment]
@vnea The command suggestion using assembly starts the container but I get the error log given below. It doesn't open the UI dashboard, am just seeing the loading icon.

I tried copying the assembly main target folder alone to a specific location in host machine and mounted only that.

When I tried to follow the suggestion as it is in the command (ie referring the assembly from the repo mount) it worked without any issues. But I want to use only binaries and not sources for production deployment


**********************************************Error Log********************************************************

1) Invocation error of method void org.eclipse.che.api.workspace.server.TemporaryWorkspaceRemover.initialize() on org.eclipse.che.api.workspace.server.TemporaryWorkspaceRemover@37520b23
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:101)
  while locating org.eclipse.che.api.workspace.server.TemporaryWorkspaceRemover
Caused by: java.lang.NullPointerException
        at com.google.inject.persist.jpa.JpaPersistService.begin(JpaPersistService.java:77)
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:53)
        at org.eclipse.che.api.workspace.server.TemporaryWorkspaceRemover.removeTemporaryWs(TemporaryWorkspaceRemover.java:68)
        at org.eclipse.che.api.workspace.server.TemporaryWorkspaceRemover.initialize(TemporaryWorkspaceRemover.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44)
        at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2) Invocation error of method public void org.eclipse.che.api.machine.server.recipe.RecipeLoader.start() throws org.eclipse.che.api.core.ServerException on org.eclipse.che.api.machine.server.recipe.
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:130)
  while locating org.eclipse.che.api.machine.server.recipe.RecipeLoader
Caused by: org.eclipse.che.api.core.ServerException
        at org.eclipse.che.api.machine.server.jpa.JpaRecipeDao.update(JpaRecipeDao.java:77)
        at org.eclipse.che.api.machine.server.recipe.RecipeLoader.start(RecipeLoader.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44)
        at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.google.inject.persist.jpa.JpaPersistService.begin(JpaPersistService.java:77)
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:53)
        at org.eclipse.che.api.machine.server.jpa.JpaRecipeDao.update(JpaRecipeDao.java:75)
        ... 38 more

3) Invocation error of method public void org.eclipse.che.api.user.server.CheUserCreator.createCheUser() throws org.eclipse.che.api.core.ServerException on org.eclipse.che.api.user.server.CheUserCre
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:86)
  while locating org.eclipse.che.api.user.server.CheUserCreator
Caused by: java.lang.NullPointerException
        at com.google.inject.persist.jpa.JpaPersistService.begin(JpaPersistService.java:77)
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:53)
        at org.eclipse.che.api.user.server.UserManager.getById(UserManager.java:147)
        at org.eclipse.che.api.user.server.CheUserCreator.createCheUser(CheUserCreator.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44)
        at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

4) Error injecting constructor, org.eclipse.che.core.db.schema.SchemaInitializationException: Validate failed: Migration checksum mismatch for migration 5.0.0.8.1
-> Applied to database : 618804818
-> Resolved locally    : -1703201590
  at org.eclipse.che.core.db.DBInitializer.<init>(DBInitializer.java:50)
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:69)
  while locating org.eclipse.che.core.db.DBInitializer
Caused by: org.eclipse.che.core.db.schema.SchemaInitializationException: Validate failed: Migration checksum mismatch for migration 5.0.0.8.1
-> Applied to database : 618804818
-> Resolved locally    : -1703201590
        at org.eclipse.che.core.db.schema.impl.flyway.FlywaySchemaInitializer.init(FlywaySchemaInitializer.java:118)
        at org.eclipse.che.core.db.DBInitializer.<init>(DBInitializer.java:52)
        at org.eclipse.che.core.db.DBInitializer$$FastClassByGuice$$411a5c44.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration 5.0.0.8.1
-> Applied to database : 618804818
-> Resolved locally    : -1703201590
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1008)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:921)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at org.eclipse.che.core.db.schema.impl.flyway.FlywaySchemaInitializer.init(FlywaySchemaInitializer.java:116)
        ... 34 more

5) Error injecting constructor, org.eclipse.che.core.db.schema.SchemaInitializationException: Validate failed: Migration checksum mismatch for migration 5.0.0.8.1
-> Applied to database : 618804818
-> Resolved locally    : -1703201590
  at org.eclipse.che.core.db.DBInitializer.<init>(DBInitializer.java:50)
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:69)
  while locating org.eclipse.che.core.db.DBInitializer
    for the 4th parameter of org.eclipse.che.api.workspace.server.stack.StackLoader.<init>(StackLoader.java:62)
  at org.eclipse.che.api.deploy.WsMasterModule.configure(WsMasterModule.java:99)
  while locating org.eclipse.che.api.workspace.server.stack.StackLoader
Caused by: org.eclipse.che.core.db.schema.SchemaInitializationException: Validate failed: Migration checksum mismatch for migration 5.0.0.8.1
-> Applied to database : 618804818
-> Resolved locally    : -1703201590
        at org.eclipse.che.core.db.schema.impl.flyway.FlywaySchemaInitializer.init(FlywaySchemaInitializer.java:118)
        at org.eclipse.che.core.db.DBInitializer.<init>(DBInitializer.java:52)
        at org.eclipse.che.core.db.DBInitializer$$FastClassByGuice$$411a5c44.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration 5.0.0.8.1
-> Applied to database : 618804818
-> Resolved locally    : -1703201590
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1008)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:921)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at org.eclipse.che.core.db.schema.impl.flyway.FlywaySchemaInitializer.init(FlywaySchemaInitializer.java:116)
        ... 44 more

5 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184) ~[guice-4.1.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[guice-4.1.0.jar:na]
        at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:na]
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140) ~[everrest-integration-guice-1.13.4.jar:na]
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) ~[guice-servlet-4.1.0.jar:na]
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85) ~[everrest-integration-guice-1.13.4.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314) [catalina.jar:8.0.38]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.38]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) [catalina.jar:8.0.38]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) [catalina.jar:8.0.38]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
2017-06-15 09:36:12,630[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[.[/wsmaster] 4859]      - Exception sending context initialized event to listener instance of class org.eclipse.che.everrest.ServerCon
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-20.0.jar:na]
        at org.everrest.core.impl.RequestDispatcher.<init>(RequestDispatcher.java:84) ~[everrest-core-1.13.4.jar:na]
        at org.eclipse.che.everrest.ServerContainerInitializeListener.getEverrestProcessor(ServerContainerInitializeListener.java:166) ~[che-core-api-core-5.8.1.jar:5.8.1]
        at org.eclipse.che.everrest.ServerContainerInitializeListener.createWsServerEndpointConfig(ServerContainerInitializeListener.java:124) ~[che-core-api-core-5.8.1.jar:5.8.1]
        at org.eclipse.che.everrest.ServerContainerInitializeListener.contextInitialized(ServerContainerInitializeListener.java:92) ~[che-core-api-core-5.8.1.jar:5.8.1]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314) [catalina.jar:8.0.38]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.38]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) [catalina.jar:8.0.38]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) [catalina.jar:8.0.38]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]

**Comment by SanthoshHari912** [comment]
The error  log is due to data folder cleanup and now its working fine.
@vnea But any other WAR files deployed in tomcat container  other than the standard set of WARS from che (in the assembly's tomcat) is ignored and not getting deployed

I have included a custom WAR file in C:\temp\eclipse-che-5.8.1\tomcat\webapps (mounted for assembly) for the above config discussed

**Comment by vnea** [comment]
@SanthoshHari912 Sorry, I don't know why. I think the CHE team will help you.

**Comment by SanthoshHari912** [comment]
Closing the issue as the answers in https://github.com/eclipse/che/issues/5401 were convincing and worked !!
