### ISSUE TITLE
[Regression] Language servers are not started after creating related workspaces

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5547]
Steps to reproduce:
1. Go to Dashboard and select .Net stack. Create the workspace from the stack.
2. Go to the workspace. Crate project   -> aspnet-web-simple.
3. Open the Program.cs file
4. Set cursor in the position 16:27 
5. Erase ```Build;```
**Expected result:** After opening editor should appears message about starting LS. The editor should show error marker in the line#16. 
**Actual result:** There is no any message about init LS. The error marker is absent. Autocomplete does not work
**Additional information:** After opening Program.cs file i've invoked ps ax command in the terminal and i did not see the process related with LS. We did the similar usecases with other language servers and get the same result.

**Comment by vparfonov** [comment]
Exception in dev-machine console:

```
 java.util.concurrent.CompletionException: org.eclipse.che.api.languageserver.exception.LanguageServerException: Can't initialize Language Server org.eclipse.che.plugin.csharp.languageserver on file:///projects/asp. Can't start CSharp language server
[STDOUT] 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
[STDOUT] 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
[STDOUT] 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
[STDOUT] 	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669)
[STDOUT] 	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1989)
[STDOUT] 	at org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl.initialize(LanguageServerRegistryImpl.java:119)
[STDOUT] 	at org.eclipse.che.api.languageserver.service.LanguageServerInitializationHandler.lambda$new$0(LanguageServerInitializationHandler.java:33)
[STDOUT] 	at org.eclipse.che.api.languageserver.service.LanguageServerInitializationHandler$$Lambda$95/2069616510.apply(Unknown Source)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToOne.lambda$withFunction$0(FunctionConfiguratorOneToOne.java:75)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToOne$$Lambda$59/128274294.apply(Unknown Source)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:282)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$900(RequestHandlerManager.java:269)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:182)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:53)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver$$Lambda$140/1552190470.run(Unknown Source)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
[STDOUT] Caused by: org.eclipse.che.api.languageserver.exception.LanguageServerException: Can't initialize Language Server org.eclipse.che.plugin.csharp.languageserver on file:///projects/asp. Can't start CSharp language server
[STDOUT] 	at org.eclipse.che.api.languageserver.registry.ServerInitializerImpl.initialize(ServerInitializerImpl.java:85)
[STDOUT] 	... 15 common frames omitted
[STDOUT] Caused by: org.eclipse.che.api.languageserver.exception.LanguageServerException: Can't start CSharp language server
[STDOUT] 	at org.eclipse.che.plugin.csharp.languageserver.CSharpLanguageServerLauncher.restoreDependencies(CSharpLanguageServerLauncher.java:77)
[STDOUT] 	at org.eclipse.che.plugin.csharp.languageserver.CSharpLanguageServerLauncher.startLanguageServerProcess(CSharpLanguageServerLauncher.java:52)
[STDOUT] 	at org.eclipse.che.api.languageserver.launcher.LanguageServerLauncherTemplate.launch(LanguageServerLauncherTemplate.java:32)
[STDOUT] 	at org.eclipse.che.api.languageserver.registry.ServerInitializerImpl.initialize(ServerInitializerImpl.java:82)
[STDOUT] 	... 15 common frames omitted
[STDOUT] Caused by: java.io.IOException: Cannot run program "dotnet" (in directory "file:/projects/asp"): error=2, No such file or directory
[STDOUT] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[STDOUT] 	at org.eclipse.che.plugin.csharp.languageserver.CSharpLanguageServerLauncher.restoreDependencies(CSharpLanguageServerLauncher.java:69)
[STDOUT] 	... 18 common frames omitted
[STDOUT] Caused by: java.io.IOException: error=2, No such file or directory
[STDOUT] 	at java.lang.UNIXProcess.forkAndExec(Native Method)
[STDOUT] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
[STDOUT] 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[STDOUT] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[STDOUT] 	... 19 common frames omitted
```
