### ISSUE TITLE
Workspace is not started correctly sometimes

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#5621]
Looks like we have some circular dependencies and it leads to case when Workspace can not start correctly.
The problem is can not  reproduced permanently, but happens very often last time.

**Che version:** 5.15.0
**OS and version:**   Fedora 25
![start_workspace](https://user-images.githubusercontent.com/5676062/28116864-a5c0656c-6713-11e7-8ac8-34b01371f89d.png)

**Diagnostics:** 
```[STDOUT] Wed Jul 12 11:53:02 UTC 2017 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2017-07-12 11:53:03,077[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4733]    - Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CheBootstrap
[STDOUT] com.google.inject.CreationException: Unable to create injector, see the following errors:
[STDOUT] 
[STDOUT] 1) Invocation error of method public void org.eclipse.che.api.project.server.ProjectRegistry.initProjects() throws org.eclipse.che.api.core.ConflictException,org.eclipse.che.api.core.NotFoundException,org.eclipse.che.api.core.ServerException,org.eclipse.che.api.core.ForbiddenException on org.eclipse.che.api.project.server.ProjectRegistry@70e29853
[STDOUT]   at org.eclipse.che.api.project.server.ProjectApiModule.configure(ProjectApiModule.java:75) (via modules: org.eclipse.che.wsagent.server.WsAgentModule -> org.eclipse.che.api.project.server.ProjectApiModule)
[STDOUT]   while locating org.eclipse.che.api.project.server.ProjectRegistry
[STDOUT]     for the 3rd parameter of org.eclipse.che.api.project.server.ProjectManager.<init>(ProjectManager.java:97)
[STDOUT]   at org.eclipse.che.api.project.server.ProjectManager.class(ProjectManager.java:74)
[STDOUT]   while locating org.eclipse.che.api.project.server.ProjectManager
[STDOUT]     for the 1st parameter of org.eclipse.che.plugin.testing.phpunit.server.PHPUnitTestRunner.<init>(PHPUnitTestRunner.java:52)
[STDOUT]   while locating org.eclipse.che.plugin.testing.phpunit.server.PHPUnitTestRunner
[STDOUT]   while locating org.eclipse.che.api.testing.server.framework.TestRunner annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=64, type=MULTIBINDER, keyType=)
[STDOUT]   at org.eclipse.che.api.testing.server.inject.TestGuiceModule.configure(TestGuiceModule.java:28) (via modules: org.eclipse.che.api.testing.server.inject.TestGuiceModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
[STDOUT]   while locating java.util.Set<org.eclipse.che.api.testing.server.framework.TestRunner>
[STDOUT]     for the 1st parameter of org.eclipse.che.api.testing.server.framework.TestFrameworkRegistry.<init>(TestFrameworkRegistry.java:35)
[STDOUT]   at org.eclipse.che.api.testing.server.framework.TestFrameworkRegistry.class(TestFrameworkRegistry.java:32)
[STDOUT]   while locating org.eclipse.che.api.testing.server.framework.TestFrameworkRegistry
[STDOUT]     for the 2nd parameter of org.eclipse.che.api.testing.server.TestingRPCService.<init>(TestingRPCService.java:45)
[STDOUT]   at org.eclipse.che.api.testing.server.inject.TestGuiceModule.configure(TestGuiceModule.java:29)
[STDOUT]   while locating org.eclipse.che.api.testing.server.TestingRPCService
[STDOUT] 
[STDOUT] 1 error
[STDOUT] 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[STDOUT] 	at com.google.inject.Guice.createInjector(Guice.java:99)
[STDOUT] 	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
[STDOUT] 	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
[STDOUT] 	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
[STDOUT] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
[STDOUT] 
[STDOUT] 1) Tried proxying org.eclipse.che.api.project.server.ProjectManager to support a circular dependency, but it is not an interface.
[STDOUT]   at org.eclipse.che.api.project.server.ProjectManager.class(ProjectManager.java:74)
[STDOUT]   while locating org.eclipse.che.api.project.server.ProjectManager
[STDOUT] 
[STDOUT] 1 error
[STDOUT] 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
[STDOUT] 	at org.eclipse.che.core.internal.resources.Workspace.getProjectsRoot(Workspace.java:119)
[STDOUT] 	at org.eclipse.che.core.internal.resources.Workspace.getAbsoluteWorkspacePath(Workspace.java:146)
[STDOUT] 	at org.eclipse.che.core.internal.resources.Resource.getLocation(Resource.java:390)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.core.project.MavenProject.getPom(MavenProject.java:311)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.core.project.MavenProject.read(MavenProject.java:195)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.core.project.MavenProject.read(MavenProject.java:190)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.internalUpdate(MavenProjectManager.java:199)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.internalAddMavenProject(MavenProjectManager.java:170)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.update(MavenProjectManager.java:143)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.update(MavenWorkspace.java:159)
[STDOUT] 	at org.eclipse.che.plugin.maven.server.projecttype.handler.MavenProjectInitHandler.initializeClasspath(MavenProjectInitHandler.java:45)
[STDOUT] 	at org.eclipse.che.plugin.java.server.projecttype.AbstractJavaInitHandler.onProjectInitialized(AbstractJavaInitHandler.java:60)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectRegistry.fireInit(ProjectRegistry.java:403)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectRegistry.fireInitHandlers(ProjectRegistry.java:389)
[STDOUT] 	at org.eclipse.che.api.project.server.ProjectRegistry.initProjects(ProjectRegistry.java:97)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDOUT] 	at java.lang.reflect.Method.invoke(Method.java:498)
[STDOUT] 	at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44)
[STDOUT] 	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
[STDOUT] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[STDOUT] 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
[STDOUT] 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
[STDOUT] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[STDOUT] 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
[STDOUT] 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
[STDOUT] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
[STDOUT] 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
[STDOUT] 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[STDOUT] 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
[STDOUT] 	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:375)
[STDOUT] 	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:258)
[STDOUT] 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
[STDOUT] 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
[STDOUT] 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
[STDOUT] 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
[STDOUT] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[STDOUT] 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
[STDOUT] 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
[STDOUT] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[STDOUT] 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
[STDOUT] 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
[STDOUT] 	... 18 common frames omitted
[STDOUT] 2017-07-12 11:53:03,104[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4733]    - Exception sending context initialized event to listener instance of class org.eclipse.che.everrest.ServerContainerInitializeListener
[STDOUT] java.lang.NullPointerException: null
[STDOUT] 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.<init>(RequestDispatcher.java:84)
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.getEverrestProcessor(ServerContainerInitializeListener.java:166)
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.createWsServerEndpointConfig(ServerContainerInitializeListener.java:124)
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.contextInitialized(ServerContainerInitializeListener.java:92)
[STDOUT] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] 2017-07-12 11:53:03,105[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4733]    - Exception sending context initialized event to listener instance of class com.codenvy.wsagent.server.SetSessionPathListener
[STDOUT] java.lang.NullPointerException: null
[STDOUT] 	at com.codenvy.wsagent.server.SetSessionPathListener.contextInitialized(SetSessionPathListener.java:54)
[STDOUT] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] 2017-07-12 11:53:03,109[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5190]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
[STDOUT] 2017-07-12 11:53:03,114[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5241]     - Context [] startup failed due to previous errors
[STDOUT] 2017-07-12 11:53:03,187[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 11,145 ms
[STDOUT] 2017-07-12 11:53:03,190[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-4401]
[STDOUT] 2017-07-12 11:53:03,203[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 11341 ms
[STDERR] 
[STDERR] Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Maven Executor - 0```

**Comment by SkorikSergey** [comment]
**Steps for reproduce on CHE:**

- Create and start a workspace from the **Java** stack with web-spring project
- Start the project's "build and run" command, wait BUILD SUCCESS message.
- Stop the workspace with snapshot and start again by "Start" button

We get error stack trace like above

**Comment by SkorikSergey** [comment]
Sorry, closed by mistake.
