### ISSUE TITLE
Workspace lost server connection (websocket)  after an inactivity period 

### ISSUE THREAD

**Issue by STRULLU** [eclipse-che/che#5842]
Hello I have upgrade Che to 5.15 this week. Since this upgrade, my workspaces lost the connection with the Che server after a short (several minutes) period on inactivity. I need to start again the workspace.  Che  Server is local to my dev machine, no http proxy.
Any feedback about this behaviour?
Many thanks. 
Laurent

**Comment by garagatyi** [comment]
@mkuznyetsov please, take a look

**Comment by ghost** [comment]
@STRULLU can you share server logs please - `docker logs -f che`

And a screenshot of what you see in a workspace helps too (with browser dev console opened if possible).

**Comment by ghost** [comment]
I have got the following in logs. Cannot reproduce reliably though, but it looks like server stops the workspace due to a lost connection to it:

```
2017-07-29 10:23:06,988[AgentLauncher-3]  [ERROR] [sicWebSocketMessageTransmitter 58]   - Error while trying to send a message to a basic websocket remote endpoint
java.io.IOException: java.io.IOException: Broken pipe
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:315)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
	at org.eclipse.che.api.core.websocket.impl.BasicWebSocketMessageTransmitter.transmit(BasicWebSocketMessageTransmitter.java:56)
	at org.eclipse.che.api.core.jsonrpc.commons.transmission.SendConfiguratorFromOne.transmitNotification(SendConfiguratorFromOne.java:219)
	at org.eclipse.che.api.core.jsonrpc.commons.transmission.SendConfiguratorFromOne.sendAndSkipResult(SendConfiguratorFromOne.java:64)
	at org.eclipse.che.api.core.util.JsonRpcMessageConsumer.lambda$consume$0(JsonRpcMessageConsumer.java:41)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.che.api.core.util.JsonRpcMessageConsumer.consume(JsonRpcMessageConsumer.java:37)
	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl$1.writeLine(MachineProviderImpl.java:319)
	at org.eclipse.che.api.core.util.CompositeLineConsumer.writeLine(CompositeLineConsumer.java:72)
	at org.eclipse.che.api.agent.server.launcher.AbstractAgentLauncher$1.writeLine(AbstractAgentLauncher.java:81)
	at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:44)
	at org.eclipse.che.plugin.docker.machine.LogMessagePrinter.process(LogMessagePrinter.java:26)
	at org.eclipse.che.plugin.docker.client.LogMessagePumper.start(LogMessagePumper.java:80)
	at org.eclipse.che.plugin.docker.client.DockerConnector.startExec(DockerConnector.java:586)
	at org.eclipse.che.plugin.docker.machine.DockerProcess.start(DockerProcess.java:112)
	at org.eclipse.che.api.agent.server.launcher.AbstractAgentLauncher.lambda$start$0(AbstractAgentLauncher.java:128)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1238)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:670)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:607)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:597)
	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:95)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:494)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	... 22 common frames omitted

```

**Comment by STRULLU** [comment]
Hello, thanks for the support. As requested the logs information.

![snapshot -che](https://user-images.githubusercontent.com/29689995/28780275-71965c86-7606-11e7-9c4b-0207a9e40d4f.png)

docker logs:
2017-07-31 12:15:46,944[ted-scheduler-8]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
2017-07-31 12:15:46,945[ted-scheduler-8]  [ERROR] [o.e.c.p.d.c.DockerConnector 1364]    - Docker response doesn't contain any data, though it was expected to contain some.
2017-07-31 12:15:46,945[ted-scheduler-8]  [ERROR] [ockerAbandonedResourcesCleaner 184]  - Failed to get list of docker networks
java.io.IOException: Internal server error. Unexpected response body received from Docker.
        at org.eclipse.che.plugin.docker.client.DockerConnector.parseResponseStreamAndClose(DockerConnector.java:1365)
        at org.eclipse.che.plugin.docker.client.DockerConnector.getNetworks(DockerConnector.java:1180)
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.cleanNetworks(DockerAbandonedResourcesCleaner.java:165)
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.run(DockerAbandonedResourcesCleaner.java:92)
        at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-07-31 12:19:49,101[ool-12-thread-1]  [WARN ] [i.f.kubernetes.client.Config 299]    - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2017-07-31 12:19:49,350[ool-12-thread-1]  [ERROR] [o.e.c.a.c.n.EventService 108]        - An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:199)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.idleCheServer(OpenShiftConnector.java:256)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.access$000(OpenShiftConnector.java:162)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector$1.onEvent(OpenShiftConnector.java:246)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector$1.onEvent(OpenShiftConnector.java:242)
        at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:106)
        at org.eclipse.che.api.workspace.server.idle.ServerIdleDetector.run(ServerIdleDetector.java:95)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unexpected response code for CONNECT: 503
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:357)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:196)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:144)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
        at okhttp3.RealCall.execute(RealCall.java:63)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:228)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:711)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:192)
        ... 13 common frames omitted
2017-07-31 13:15:46,948[ted-scheduler-9]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
2017-07-31 13:15:46,952[ted-scheduler-9]  [ERROR] [o.e.c.p.d.c.DockerConnector 1364]    - Docker response doesn't contain any data, though it was expected to contain some.
2017-07-31 13:15:46,953[ted-scheduler-9]  [ERROR] [ockerAbandonedResourcesCleaner 184]  - Failed to get list of docker networks
java.io.IOException: Internal server error. Unexpected response body received from Docker.
        at org.eclipse.che.plugin.docker.client.DockerConnector.parseResponseStreamAndClose(DockerConnector.java:1365)
        at org.eclipse.che.plugin.docker.client.DockerConnector.getNetworks(DockerConnector.java:1180)
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.cleanNetworks(DockerAbandonedResourcesCleaner.java:165)
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.run(DockerAbandonedResourcesCleaner.java:92)
        at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ghost** [comment]
@STRULLU what's your Docker version?

**Comment by STRULLU** [comment]
docker -v
Docker version 17.03.1-ce, build c6d412e

**Comment by ghost** [comment]
@STRULLU have you tried restarting Docker? It looks like it feels unwell.

**Comment by STRULLU** [comment]
@mkuznyetsov I had the same problem last week, I restarted my docker deamon yesterday morning and same behavior this week.  Docker works fine for my other applications (jenkins, python, ...). I have just restarted the che server container : b47209e42b04        eclipse/che-server:5.15.0   "/entrypoint.sh"    7 days ago          Up 12 seconds             8000/tcp, 8080/tcp, 0.0.0.0:9000->9000/tcp   che-9000. 
I use Chrome Version 59.0.3071.104 (Build officiel) (64 bits). I can try with firefox to see if the connection is lost also. Thanks

**Comment by ghost** [comment]
@STRULLU the logs you have shared indicate a different problem...

Can you share that part of the server log where workspace is stopped?

Also, do you run one Che server on the host?

**Comment by STRULLU** [comment]
@mkuznyetsov ok, the problem (disconnection) seams to come from the webapp side  no? I try to get some log from the console.

**Comment by mkuznyetsov** [comment]
@STRULLU not quite sure if it's related to activity tracking, can we see full logs of Che server (using ```docker logs -f che```), from the moment when your workspaces get shutdown in that case?

Also, can it be that you have two Che server instances running at the same time?

**Comment by STRULLU** [comment]
@mkuznyetsov: the full che server docker logs in attachment. 
Only one instance of che server docker container is running.
[che.zip](https://github.com/eclipse/che/files/1190015/che.zip).
I started the workspace with firefox, waiting the problem.

**Comment by STRULLU** [comment]
@mkuznyetsov: Same behaviour with Firefox 
The Windows standby on my PC is deactivated. 

Firefox console.log
```
WARNING (org.eclipse.che.ide.websocket.impl.DelayableWebSocketConnection): Closing connection that is not opened. _app-0.js:16144:95
Firefox ne peut établir de connexion avec le serveur à l’adresse ws://10.193.71.192:32769/connect.  wksp-python:16246:24
WARNING (org.eclipse.che.ide.websocket.impl.BasicWebSocketEndpoint): Error occurred for endpoint ws://10.193.71.192:32769/connect  _app-0.js:16144:95
Firefox ne peut établir de connexion avec le serveur à l’adresse ws://10.193.71.192:32772/websocket/1619560489.  wksp-python:16246:24
WARNING (org.eclipse.che.ide.websocket.impl.BasicWebSocketEndpoint): Error occurred for endpoint ws://10.193.71.192:32772/websocket/1619560489  _app-0.js:16144:95
Firefox ne peut établir de connexion avec le serveur à l’adresse ws://10.193.71.192:32772/api/ws.
```

_

**Comment by mkuznyetsov** [comment]
@STRULLU workspaces are being shutdown after 60 minutes since last activity (by default).
Workspace activity is any keyboard+mouse activity in IDE, as well as any HTTP requests on ws-agent. I just found that keyboard+mouse activity is not being tracked in Che, I'll be fixing it now.

**Comment by STRULLU** [comment]
Hello thanks for the support.
Should be interesting to be able to setup or switch off the IDE shutdown strategy in the che configuration file. I want to keep alive my opened terminals in my workspaces so no shutdown on inactivity for me.

**Comment by mkuznyetsov** [comment]
I'll expose configuration variable to che.env so you can set idle time to "0", thus workspaces will not be stopped automatically.

**Comment by mkuznyetsov** [comment]
Hi. about your case.

You can add in your `che.env` following line
CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS=0
And this will disable the automatic shutdown of inactive workspaces

I just merged a PR
https://github.com/eclipse/che/pull/5896
where this environment variable has been documented, and added to default `che.env`, and it goes to 5.17 version of Che
