### ISSUE TITLE
 Run QA in multiuser branch and figure out what should be done to adapt QA to multiuser branch

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5930]
Run QA in multi-user branch and figure out what should be done to adapt QA to multiuser branch

**Comment by dmytro-ndp** [comment]
[Test report](https://github.com/codenvy/qa/files/1251104/report1503586820.zip):
```
[TEST] =========== RUN OPTIONS ===========================
[TEST] Mode                : grid
[TEST] Tests inclusion     : stable and unstable tests
[TEST] Rerun failing tests : false
[TEST] ===================================================
[TEST] Product Protocol : http
[TEST] Product Host     : 172.17.0.1
[TEST] Tests            : -DrunSuite=/tmp/CheSuite.xml
[TEST] Threads          : 4
[TEST] Web browser      : GOOGLE_CHROME
[TEST] Web driver ver   : 2.31
[TEST] Web driver port  : 4444
[TEST] Additional opts  : -Dgrid.mode=true  
[TEST] ===================================================

Failed tests: 
  AddSshKeyForGitHubTest.generateKey:72 » Timeout Expected condition failed: wai...
  KeyBindingsTest.dialogAboutKeyBindingTest:114 expected [true] but found [false]
  CreateAndDeleteProjectsTest.createAndDeleteProjectTest:98 » Timeout Expected c...
  CheckLaravelStackTest.checkLaravelStack:73 » Timeout Expected condition failed...
  ChangeVariableWithEvaluatingTest.changeVariableTest:140 » Timeout Expected con...
  DebugExternalClassTest.shouldDebugJreClass:139 » Timeout Expected condition fa...
  InnerClassAndLambdaDebuggingTest.shouldDebugInnerClass:148 » Timeout Expected ...
  InnerClassAndLambdaDebuggingTest.shouldDebugMethodLocalInnerClass:136 » Timeout
  InnerClassAndLambdaDebuggingTest.shouldDebugStaticInnerClass:160 » Timeout Exp...
  MultimoduleProjectDebuggingTest.shouldDebugStaticMethod:182 » Timeout Expected...
  MultimoduleProjectDebuggingTest.shouldGoIntoConstructor:130 » Timeout Expected...
  PhpProjectDebuggingTest.shouldDebugCliPhpScriptFromFirstLine:139 » Timeout Exp...
  PhpProjectDebuggingTest.shouldDebugWebPhpScriptFromNonDefaultPortAndNotFromFirstLine:183 » Timeout
  StepIntoStepOverStepReturnWithChangeVariableTest.changeVariableTest:133 » Timeout
  CheckRestoringOfSplitEditor.checkRestoringStateSplittedEditor:93->checkSplitdEditorAfterRefreshing:108 » Timeout
  AutocompleteFeaturesInEditorTest.createJavaSpringProjectAndTestEditor:176 » Timeout
  AutocompleteProposalJavaDocTest.shouldReflectChangesInJavaDoc:161 » StaleElementReference
  AutocompleteProposalJavaDocTest.shouldWorkAroundAbsentSourcesOfExternalLib:192 » StaleElementReference
  FormatterTest.formatterTest:114 » StaleElementReference stale element referenc...
  CheckBitnamiCodeIgniterFactory.checkCodeigniterUrl:52 » Timeout Expected condi...
  CheckBitnamiLaravelFactoryTest.checkLaravelUrl:53 » Timeout Expected condition...
  CheckBitnamiSwiftFactory.checkSwiftUrl:51 » Timeout Expected condition failed:...
  CheckFactoryWithMultiModuleTest.checkFactoryProcessing:72 » Timeout Expected c...
  CheckFactoryWithPerClickCreatePolicyTest.checkFactoryAcceptingWithPerClickPolicy:61 » Timeout
  CheckFactoryWithPerUserCreatePolicyTest.checkFactoryAcceptingWithPerUserPolicy:63 » Timeout
  CheckFactoryWithSvnCVSTest.checkFactoryProcessing:104 » Timeout Expected condi...
  CheckOpenFileFeatureTest.checkOpenFileFeatureTest:92 » Timeout Expected condit...
  CheckRunCommandFeatureTest.checkRunCommandFeatureTest:94 » Timeout Expected co...
  CreateFactoryFromUiWithKeepDirTest.createFactoryFromUiWithKeepDirTest:96->setUpModuleForFactory:119->createFactoryAndSwitchToWs:142 » Timeout
  CreateNamedFactoryFromDashBoard.createFactoryFromDashBoard:84 » WebDriver unkn...
  DirectUrlFactoryWithRootFolder.factoryWithDirectUrlWithRootFolder:87 » Timeout
  CheckDeletingProjectByApiTest.shouldDeleteProjectsAndCheckDeleting:49->deleteAndWaitProjectNotExistByApi:62 » NotFound
  CheckFileWatcherExcludeFeatureTest.checkIsNotExcludeOperationEventAboutIgnoreFile:189 » Timeout
  RefactoringFeatureTest.checkRefactorFilesFromIde:99->checkWatching:114 » Timeout
  CheckoutReferenceTest.checkCheckoutReference:88->importProjectFromRemoteRepo:175 » Timeout
  CheckoutToRemoteBranchTest.checkoutToRemoteBranchTest:106->importProjectFromRemoteRepo:248 » Timeout
  FetchUpdatesAndMergeRemoteBranchIntoLocalTest.fetchUpdatesAndMergeRemoteBranch:110->importProjectFromRemoteRepo:245 » Timeout
  GitPullTest.pullTest:93 » Timeout Expected condition failed: waiting for eleme...
  ImportProjectIntoSpecifiedBranchTest.prepare:72 » Timeout Expected condition f...
  ImportRecursiveSubmoduleTest.prepare:69 » Timeout Expected condition failed: w...
  PullRequestPluginTest.setUp:111 » Timeout Expected condition failed: waiting f...
  PullRequestPluginWithForkTest.setUp:97 » Timeout Expected condition failed: wa...
  PushChangeNotUpdatedRepoTest.pushNoneUpdateTest:95->cloneProject:206 » Timeout
  PushingChangesTest.pushChangesTest:107 » Timeout Expected condition failed: wa...
  WorkingWithPullConflictsTest.pullConflictsTest:115->importProjectFromRemoteRepo:216 » Timeout
  CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbar:80 » Timeout Exp...
  CheckIntelligenceCommandFromToolbarTest.launchClonedWepAppTest:71 » Timeout Ex...
  CommandsEditorTest.checkComamandsEditor:124 » Timeout Expected condition faile...
  CheckMainFeatureForLanguageTest.checkLaunchingCodeserver:57 » Timeout Expected...
  CheckMacrosFeatureTest.checkMacrosFeature:70 » Timeout Expected condition fail...
  FindTextFeatureTest.checkFindByFileMask:306 » Timeout Expected condition faile...
  FindTextFeatureTest.checkFindIntoSelectedPath:272 » Timeout Expected condition...
  FindTextFeatureTest.checkFindTextBasic:217 » Timeout Expected condition failed...
  FindTextFeatureTest.checkFindWholeWordOnly:246 » Timeout Expected condition fa...
  FindTextFeatureTest.checkRecentlyCreatedFiles:170 » Timeout Expected condition...
  NavigateToFileTest.checkFunctionNavigateFile:113 » Timeout Expected condition ...
  NavigateToFileTest.checkNavigateFileFunctionWithJustCreatedFiles:158 » Timeout
  ConfigureSomeSourceFoldersTest.checkConfigureClasspathPlainJavaProject:77 » Timeout
  PlainJavaProjectConfigureClasspathTest.checkConfigureClasspathPlainJavaProject:102 » Timeout
  MoveItemsTest.checkMoveItem0:104 » WebDriver unknown error: Element <div class...
  MoveItemsTest.checkMoveItem5:207 » WebDriver unknown error: Element <div class...
  MoveJavaFileInNewSourceFolderTest.checkMoveJavaClassInNewSourceFolder:81 » Timeout
  RenamePackageTest.checkTest3:381 » Timeout Expected condition failed: waiting ...
  RenamePackageTest.checkTest4:420 » Timeout Expected condition failed: waiting ...
  RenamePackageTest.checkTestDisableImport11:631 » StaleElementReference stale e...
  RenamePackageTest.checkTestHierarchical9_1:595 » StaleElementReference stale e...
  RenamePackageTest.checkTestPackageRenameWithResource12:683 » Timeout Expected ...
  CommitTest.commitTest:73 » Timeout Expected condition failed: waiting for visi...
  CopyTest.svnCopyTest:71 » Timeout Expected condition failed: waiting for visib...
  DiffViewTest.checkDiffView:93 » Timeout Expected condition failed: waiting for...
  LockFileTest.lockFileTest:69 » Timeout Expected condition failed: waiting for ...
  PropertiesTest.propertiesTest:71 » Timeout Expected condition failed: waiting ...
  SvnUpdateTest.svnUpdateTest:69 » Timeout Expected condition failed: waiting fo...
  UpdateToRevisionTest.updateToRevisionTest:71 » Timeout Expected condition fail...
  SwaggerTest.checkNameProjectTest:43 » UnhandledAlert unexpected alert open: {A...
  JavaTestPluginJunit4Test.shouldExecuteJUnit4MethodWithDifferentStatuses:140 » Timeout
  JavaTestPluginTestNgTest.shouldExecuteTestMethodsSuccessfully:154 Actual message was: [TestNG] Running:  /home/user/che/ws-agent/temp/che-testng-suite.xmlexpected [false] but found [true]
java.lang.AssertionError: expected [false] but found [true]
 at org.testng.Assert.fail(Assert.java:94)
 at org.testng.Assert.failNotEquals(Assert.java:494)
 at org.testng.Assert.assertFalse(Assert.java:63)
 at org.testng.Assert.assertFalse(Assert.java:73)
 at org.eclipse.che.examples.AppAnotherTest.shouldFailOfAppAnother(AppAnotherTest.java:31)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
 at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
 at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
 at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
 at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
 at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
 at org.testng.TestRunner.privateRun(TestRunner.java:767)
 at org.testng.TestRunner.run(TestRunner.java:617)
 at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
 at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
 at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
 at org.testng.SuiteRunner.run(SuiteRunner.java:254)
 at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
 at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
 at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
 at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
 at org.testng.TestNG.run(TestNG.java:1057)
 at org.testng.CheTestNG.run(CheTestNG.java:35)
 at org.testng.CheTestNGLauncher.main(CheTestNGLauncher.java:41)===============================================Default SuiteTotal tests run: 1, Failures: 1, Skips: 0=============================================== expected [true] but found [false]
  ProjectStateAfterRenameWorkspaceTest.checkProjectAfterRenameWs:91 » Timeout Ex...
  WorkingWithNodeWsTest.checkNodeJsWsAndRunApp:109 » WebDriver chrome not reacha...

Tests run: 503, Failures: 79, Errors: 0, Skipped: 16
```

Found issues:
- Multiuser Che Dashboard displays broken icons (https://github.com/eclipse/che/issues/6069)
- 401 error when opening project from Multiuser Che Dashboard (https://github.com/eclipse/che/issues/6070)
- Add ability to logout from Multiuser Che Dashboard (https://github.com/eclipse/che/issues/6073)
- 403 error page instead of GitHub authorization page in Multiuser Che (https://github.com/eclipse/che/issues/6093)

**Comment by dmytro-ndp** [comment]
(continue of found issues list)
- It's impossible to import SVN-project in Multiuser Che (#6127)
- Swagger is inaccessible in Multiuser Che (#6128)

**Comment by dmytro-ndp** [comment]
Pull request with changes in selenium tests could be found [here](https://github.com/eclipse/che/pull/6227).

[Fresh test report](https://github.com/eclipse/che/files/1295374/report1505177718.zip): 
- Multiuser Che version in branch https://github.com/eclipse/che/commit/d17c80ef6d23d0dfd08bc8e07296c342a3981ae1 
- Total time: 05:20 h on two threads.
- Tests run: 511, Failures: 87, Errors: 0, Skipped: 30
```
AddSshKeyForGitHubTest.generateKey:72 » Timeout Expected condition failed: wai...
KeyBindingsTest.dialogAboutKeyBindingTest:114 expected [true] but found [false]
KeyBindingsTest.enterKeyCombinationTest:78 » Timeout Expected condition failed...
OrganizeImportsTest.organizeImportsTest:87 » Timeout Expected condition failed...
CreateAndDeleteProjectsTest.createAndDeleteProjectTest:98 » Timeout Expected c...
CheckCodeigniterStackTest.checkCodeigniterStack:72 » Timeout Expected conditio...
DebugExternalClassTest.shouldDebugJreClass:139 » Timeout Expected condition fa...
InnerClassAndLambdaDebuggingTest.shouldDebugInnerClass:148 » Timeout Expected ...
InnerClassAndLambdaDebuggingTest.shouldDebugMethodLocalInnerClass:136 » Timeout
InnerClassAndLambdaDebuggingTest.shouldDebugStaticInnerClass:160 » Timeout Exp...
MultimoduleProjectDebuggingTest.shouldDebugStaticMethod:182 » Timeout Expected...
MultimoduleProjectDebuggingTest.shouldGoIntoConstructor:130 » Timeout Expected...
NodeJsDebugTest.debugNodeJsTest:87->checkEvaluationFeatures:133 » Timeout Expe...
PhpProjectDebuggingTest.shouldDebugCliPhpScriptFromFirstLine:139 » Timeout Exp...
PhpProjectDebuggingTest.shouldDebugWebPhpScriptFromNonDefaultPortAndNotFromFirstLine:183 » Timeout
CheckRestoringOfSplitEditor.checkRestoringStateSplittedEditor:93->checkSplitdEditorAfterRefreshing:108 » Timeout
AutocompleteFeaturesInEditorTest.createJavaSpringProjectAndTestEditor:176 » Timeout
AutocompleteProposalJavaDocTest.shouldDisplayJavaDocOfJreClass:175->verifyJavaDoc:218
AutocompleteProposalJavaDocTest.shouldWorkAroundAbsentSourcesOfExternalLib:210 » StaleElementReference
FormatterTest.formatterTest:114 expected
CheckBitnamiCodeIgniterFactory.checkCodeigniterUrl:52 » Timeout Expected condi...
CheckBitnamiLaravelFactoryTest.checkLaravelUrl:50 » Timeout Expected condition...
CheckBitnamiSwiftFactory.checkSwiftUrl:51 » Timeout Expected condition failed:...
CheckFactoryWithSvnCVSTest.checkFactoryProcessing:104 » Timeout Expected condi...
DirectUrlFactoryWithRootFolder.factoryWithDirectUrlWithRootFolder:86 » WebDriver
CheckDeletingProjectByApiTest.shouldDeleteProjectsAndCheckDeleting:49->deleteAndWaitProjectNotExistByApi:62 » NotFound
CheckFileWatcherExcludeFeatureTest.checkIsNotExcludeOperationEventAboutIgnoreFile:189 » Timeout
EditFilesWithTabsTest.setUp » Configuration Guice configuration errors:
RefactoringFeatureTest.setUp » Configuration Guice configuration errors:
RemoveFilesWithActiveTabs.setUp » Configuration Guice configuration errors:
UpdateFilesWithoutIDE.setUp » Configuration Guice configuration errors:
CheckoutReferenceTest.checkCheckoutReference:88->importProjectFromRemoteRepo:175 » Timeout
CheckoutToRemoteBranchTest.checkoutToRemoteBranchTest:106->importProjectFromRemoteRepo:248 » Timeout
FetchUpdatesAndMergeRemoteBranchIntoLocalTest.fetchUpdatesAndMergeRemoteBranch:110->importProjectFromRemoteRepo:245 » Timeout
GitPullTest.pullTest:93 » Timeout Expected condition failed: waiting for eleme...
ImportProjectIntoSpecifiedBranchTest.prepare:72 » Timeout Expected condition f...
ImportRecursiveSubmoduleTest.prepare:69 » Timeout Expected condition failed: w...
PullRequestPluginTest.setUp:111 » Timeout Expected condition failed: waiting f...
PullRequestPluginWithForkTest.setUp:97 » Timeout Expected condition failed: wa...
PushChangeNotUpdatedRepoTest.pushNoneUpdateTest:95->cloneProject:206 » Timeout
PushingChangesTest.pushChangesTest:107 » Timeout Expected condition failed: wa...
WorkingWithPullConflictsTest.pullConflictsTest:115->importProjectFromRemoteRepo:216 » Timeout
CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbar:88 » NoSuchElement
CommandsEditorTest.checkComamandsEditor:124 » Timeout Expected condition faile...
MacrosCommandsEditorTest.checkCommandMacrosIntoCommandLine:62 » Timeout Expect...
MacrosCommandsEditorTest.checkCommandMacrosIntoPreviewUrl:112 » Timeout Expect...
CheckMainFeatureForLanguageTest.checkLaunchingCodeserver:57 » Timeout Expected...
CheckMavenPluginTest.mavenStatusBarShouldDisplayResolvingProjectMessage:72 » Timeout
FindTextFeatureTest.checkFindByFileMask:306 » Timeout Expected condition faile...
FindTextFeatureTest.checkFindIntoSelectedPath:272 » Timeout Expected condition...
FindTextFeatureTest.checkFindTextBasic:217 » Timeout Expected condition failed...
FindTextFeatureTest.checkFindWholeWordOnly:246 » Timeout Expected condition fa...
FindTextFeatureTest.checkRecentlyCreatedFiles:170 » Timeout Expected condition...
NavigateToFileTest.checkFunctionNavigateFile:110->selectFileFromNavigate:176 » Timeout
NavigateToFileTest.checkNavigateFileFunctionWithJustCreatedFiles:155->selectFileFromNavigate:176 » Timeout
Eclipse0121Test.test0121:53 » Timeout Expected condition failed: waiting for v...
ConfigureSomeSourceFoldersTest.checkConfigureClasspathPlainJavaProject:77 » Timeout
PlainJavaProjectConfigureClasspathTest.checkConfigureClasspathPlainJavaProject:102 » Timeout
CheckAutoSaveForFileWhichAlreadyExistTest.saveDialogForChangedFiles:68 » Timeout
DeleteFilesTest.deleteFileTest:87 » Timeout Expected condition failed: waiting...
RenameStaticMethodsTest.setup:80 » Timeout Expected condition failed: waiting ...
FailMoveItemTest.prepare:59 » Timeout Expected condition failed: waiting for v...
MoveJavaClassToSubpackageTest.checkProjectTreeAfterMoveJavaFile:62 » WebDriver
MoveJavaFileInNewSourceFolderTest.checkMoveJavaClassInNewSourceFolder:81 » Timeout
RenamePackageTest.checkTest0:289 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTest1:316 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTest2:326 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTest3:380 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTest4:399 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTest5:464 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTest6:490 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTest7:503 » Timeout Expected condition failed: waiting ...
RenamePackageTest.checkTestHierarchical9_1:595 » StaleElementReference stale e...
RenamePackageTest.checkTestPackageRenameWithResource12:683 » Timeout Expected ...
TestAnnotationsTest.testAnnotation1:70 » Timeout Expected condition failed: wa...
CommitTest.commitTest:73 » Timeout Expected condition failed: waiting for visi...
CopyTest.svnCopyTest:71 » Timeout Expected condition failed: waiting for visib...
DiffViewTest.checkDiffView:93 » Timeout Expected condition failed: waiting for...
LockFileTest.lockFileTest:69 » Timeout Expected condition failed: waiting for ...
PropertiesTest.propertiesTest:71 » Timeout Expected condition failed: waiting ...
SvnUpdateTest.svnUpdateTest:69 » Timeout Expected condition failed: waiting fo...
UpdateToRevisionTest.updateToRevisionTest:71 » Timeout Expected condition fail...
SwaggerTest.checkNameProjectTest:43 » Timeout Expected condition failed: waiti...
JavaTestPluginJunit4Test.shouldExecuteJUnit4MethodWithDifferentStatuses:140 » Timeout
JavaTestPluginTestNgTest.shouldExecuteTestClassSuccessfully:124 » Timeout Expe...
JavaTestPluginTestNgTest.shouldExecuteTestMethodsSuccessfully:148 » Timeout Ex...
ProjectStateAfterRenameWorkspaceTest.checkProjectAfterRenameWs:91 » Timeout Ex...
```

### Short analysis:
#### Error in test framework:
- OrganizeImportsTest.organizeImportsTest:87
- EditFilesWithTabsTest.setUp
- RefactoringFeatureTest.setUp
- RemoveFilesWithActiveTabs.setUp
- UpdateFilesWithoutIDE.setUp
- MacrosCommandsEditorTest.checkCommandMacrosIntoCommandLine:62
- MacrosCommandsEditorTest.checkCommandMacrosIntoPreviewUrl:112
- ConfigureSomeSourceFoldersTest.checkConfigureClasspathPlainJavaProject:77
- CheckAutoSaveForFileWhichAlreadyExistTest.saveDialogForChangedFiles:68
- DeleteFilesTest.deleteFileTest:87
- TestAnnotationsTest.testAnnotation1:70

#### Issue https://github.com/eclipse/che/issues/6070
CreateAndDeleteProjectsTest.createAndDeleteProjectTest:98	
#### Issue https://github.com/eclipse/che/issues/6093
AddSshKeyForGitHubTest.generateKey:72

_Note_: use **--multiuser** parameter to run tests on Multiuser Che
Also there should be next properties somewhere accessible for selenium test:
>che.admin.name=admin
>che.admin.password=admin

**Comment by Ohrimenko1988** [comment]
We have several differences between "master" and "che-multiuser" branches in the tests:

- CreateAndDeleteProjectsTest
- DebugExternalClassTest
- InnerClassAndLambdaDebuggingTest
- ProjectStateAfterRefreshTest
- ProjectStateAfterWorkspaceRestartTest
- StepIntoStepOverStepReturnWithChangeVariableTest

Issues https://github.com/eclipse/che/issues/6289 and https://github.com/eclipse/che/issues/6070 (reasons of fails) were fixed and changes in the current "master" now. So it`s looks like we need to merge the actual "master" branch to the "che-multiuser" branch.

**Comment by Ohrimenko1988** [comment]
We need to move existing organization selenium tests from codenvy-codenvy to the che-multiuser branch, 
according to the new functionality - "organizations" in the che-multiuser branch.
https://github.com/eclipse/che/issues/6391

**Comment by Ohrimenko1988** [comment]
In this issue https://github.com/eclipse/che/issues/5802 I have commented all found bugs in the "organizations" functionality in the "che-multiuser" branch.
At current time we have three bugs:
 - A number of organizations on the admin dashboard is not shown
 - User is not shown in the organization members list after adding to it (but user is in organization)
 - User`s first name and last name are configured but in organizations members list they are not displayed

**Comment by Ohrimenko1988** [comment]
Merged to the master
