### ISSUE TITLE
Unsupported major.minor version 52.0 while running TestNG Tests

### ISSUE THREAD

**Issue by robbirob** [eclipse-che/che#6095]
I've tried  to run  TestNG-Tests with Che-GUI. I have Java 7 Installed on my dev-machine because my project demands it. 

I get:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/testng/CheTestNGLauncher : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Test suite is empty.
```

Is there a possibility to run these test in GUI with JDK7 installed?

**OS and version:**    

Linux Mint 18.1

**Diagnostics:** 
```
WARNING: No swap limit support
INFO: (che cli): 5.16.0 - using docker 17.06.1-ce / native
WARN: Newer version '5.17.0' available

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:5.16.0
 Version:        5.16.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /data
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.16.0
 CHE_HOST:       10.131.200.11
 CHE_INSTANCE:   /data/instance
 CHE_CONFIG:     /data
 CHE_BACKUP:     /data/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   10.131.200.11
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.16.0
 IMAGE_CHE=eclipse/che-server:5.16.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.16.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.16.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.16.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.16.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.16.0
che.env:
 CHE_HOST=10.131.200.11
 CHE_SINGLE_PORT=false
```

**Comment by ghost** [comment]
@robbirob ws-agent, as well as its components require JDK 1.8+.

**Comment by robbirob** [comment]
I there a way i can provide Java8 to Che and still use Java7 in my project?

**Comment by ghost** [comment]
@robbirob there's no such possibility. Che testing framework does not detect `JAVA_HOME` or sets it. Testing frameworks like TestNG or JUnit do it on their own.

What's your TestNG version? Maybe it's incompatible with Java 7. Can you run test with the same Java version and this project elsewhere (locally using a different IDE)

**Comment by robbirob** [comment]
The Tests are running fine in Eclipse, and are running fine even in Eclipse Che Terminal with "mvn clean test" or "mvn clean install". Just using Che-GUI with _Test_->_Run TestNG Test_ gives me that Error.

**Comment by ghost** [comment]
@robbirob yes, this is a bug since JAVA_HOME set for ws-agent should be used: https://github.com/eclipse/che/blob/master/plugins/plugin-testing-java/plugin-testing-testng/che-plugin-testing-testng-server/src/main/java/org/eclipse/che/plugin/testing/testng/server/TestNGRunner.java#L107

This will be fixed both for JUnit and TestNg runners

**Comment by riuvshin** [comment]
@eivantsov should we close this issue?

**Comment by ghost** [comment]
Yes
