### ISSUE TITLE
ERROR exception o.e.c.a.c.j.c.RequestDispatcher 

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#6152]
Got this exception:
```
2017-09-05 12:34:21,121[equestProcessor]  [ERROR] [.e.c.a.c.j.c.RequestDispatcher 61]   - No corresponding to method 'event:environment-output:un-subscribe-by-machine-name' handler is registered
```
Followed by:
```
2017-09-05 12:34:21,129[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: null
java.lang.NullPointerException: null
	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcComposer.composeOne(GsonJsonRpcComposer.java:29)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToNoneHandler.handle(RequestHandlerManager.java:328)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToNoneHandler.access$1500(RequestHandlerManager.java:318)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:228)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:55)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Reproduction Steps:**
Don't know

**OS and version:**    
Centos 7.3 Codenvy 5.17.0

**Comment by skryzhny** [comment]
Also got similar exception for another module:
```
2017-09-08 11:27:20,560[equestProcessor]  [ERROR] [.e.c.a.c.j.c.RequestDispatcher 61]   - No corresponding to method 'event:ws-agent-output:un-subscribe' handler is registered
```
