### ISSUE TITLE
Project import fails on 'spi' branch

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#6159]
Can not import project neither manually nor by defining it in workspace config for workspaces created from `spi` branch:

![image](https://user-images.githubusercontent.com/1461122/30125754-c62ff0d6-9339-11e7-9a58-b32ee342c513.png)

`2017-09-06 17:21:52,941[nio-4401-exec-1]  [WARN ] [c.s.o.RemoteOAuthTokenProvider 73]   - Exception on token retrieval, message : Unsupported OAuth provider github
2017-09-06 17:21:53,654[nio-4401-exec-1]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error occurred, error time: 2017-09-06 17:21:53
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:169)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:118)
org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /projects/che-starter/.git failed
	at org.eclipse.che.api.git.GitProjectImporter.cloneRepository(GitProjectImporter.java:247)
	at org.eclipse.che.git.impl.jgit.JGitConnection.clone(JGitConnection.java:566)
	at org.eclipse.che.git.impl.jgit.JGitConnection.executeRemoteCommand(JGitConnection.java:1965)
	at org.eclipse.che.api.project.server.ProjectManager.doImportProject(ProjectManager.java:532)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:84)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:134)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at org.eclipse.che.api.project.server.ProjectManager.importProject(ProjectManager.java:496)
	at org.eclipse.che.api.git.GitProjectImporter.importSources(GitProjectImporter.java:178)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at org.eclipse.che.api.project.server.ProjectService.importProject(ProjectService.java:406)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:161)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:290)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.plugin.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:52)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Creating directories for /projects/che-starter/.git failed
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:288)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:115)
	... 55 common frames omitted
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:370)`

**Comment by gorkem** [comment]
@ibuziuk Do you have the CHE_OAUTH_GITHUB_* environment variables set?

**Comment by ibuziuk** [comment]
@gorkem nope, but I have never set it before as I recall. I was expecting that project import would work OOTB

**Comment by gorkem** [comment]
@ibuziuk agreed, it is a git clone, is should not require an authentication for public repos.

**Comment by garagatyi** [comment]
I believe it is not a problem with OAuth, but rather FS permission problem. OAuth error has the warn level, so it is not critical.
@ibuziuk can you dig into FS permissions problem and provide more details? 
BTW can you provide workspace configuration?

**Comment by ghost** [comment]
@ibuziuk I just started a workspace using a single pod OpenShift stack and can import projects. And yes, oAuth message is just a warning and it should not mess with JGit trying to clone a repo.

**Comment by ibuziuk** [comment]
@garagatyi I have used the workspace config from here - https://github.com/redhat-developer/rh-che/blob/master/howtos/spi.adoc#create-workspace-using-openshift-stack
will try to provide more details soon

**Comment by ghost** [comment]
@ibuziuk do check permissions. Can you mkdir or touch there in the terminal?

**Comment by ibuziuk** [comment]
@eivantsov yup, looks like permission issue - getting permission denied for mkdir / touch commands. UID info:
uid=1000050000(user) gid=0(root) groups=0(root),10(wheel),100(users),1000050000

**Comment by ghost** [comment]
`ls -la` in `/projects` please

**Comment by ibuziuk** [comment]
@eivantsov 
`total 8
drwxr-xr-x  2 root root 4096 Sep  7 07:54 .
drwxr-xr-x 54 root root 4096 Sep  7 07:54 ..
`

**Comment by ghost** [comment]
What are OpenShift and Minishift versions?

**Comment by ibuziuk** [comment]
oc v3.5.5.19
minishift v1.3.0

**Comment by ghost** [comment]
It is a bug in k8s that's fixed in 1.6. Looks like you handled that in Openshift Connector with pre-create paths workaround. Update your Minishift to 1.4.

**Comment by ibuziuk** [comment]
@eivantsov oh, true - updating. I remember that @akorneta told me about this problem on f2f and it was decided that for spi there is no need in such workaround for obsolete versions

**Comment by ghost** [comment]
@ibuziuk so should this issue be closed then?

**Comment by ibuziuk** [comment]
@eivantsov lemme verify if against the following setup and I will close:
- minishift v1.5.0
- oc v3.6.0

I also think that we probably need to update rh-che[1] & che[2] instructions to clarify that minishift 1.4 and above is the expected environment.
@l0rd WDYT ?

[1] https://github.com/redhat-developer/rh-che#how-to-deploy-or-roll-update-che-on-openshift-container-platform-minishift-or-osio
[2] https://www.eclipse.org/che/docs/setup/openshift/index.html

**Comment by l0rd** [comment]
@ibuziuk OpenShiftConnector should work with previous versions of minishift too (with the double mount trick) right?

**Comment by ibuziuk** [comment]
@l0rd true, but with `spi` in place minishift 1.3 and below are not going to be supported. So, probably makes sense to update docs only once spi is merged

**Comment by gorkem** [comment]
Is this a minishift limitation or openshift limitation? I think we should document the mininum supported openshift version.

**Comment by ghost** [comment]
It's k8s limitation
