### ISSUE TITLE
Workspace freezes since 5.17.0

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#6208]
Since 5.17.0 every workspace on Codenvy has the issue that it starts freezing at some point. I normaly experience it first when not being able to save files any more.

The issue starts when the following requests freeze at (pending):

![screenshot 2017-09-11 at 11 27 02 - display 3](https://user-images.githubusercontent.com/5741245/30268112-f2baa5ac-96e4-11e7-8cbd-c3d74c17cad1.png)

After a while (most likely because of the reached limit of pending requests) all request are stuck at (pending) state. (These are file-save-requests triggered by me)

![screenshot 2017-09-11 at 11 28 02 - display 3](https://user-images.githubusercontent.com/5741245/30268164-273032ac-96e5-11e7-9496-56fe6df3ac2b.png)

If waiting longer the Workspace will crash and ask you to restart at some time.

**Comment by garagatyi** [comment]
@vparfonov can you take a look on this issue?

**Comment by vparfonov** [comment]
Should be fixed here: https://github.com/eclipse/che/pull/6175

**Comment by sunix** [comment]
I'm also experimenting a lot of IDE (browser) freezes, with the last Che nightly, still have freezes today

**Comment by vparfonov** [comment]
@sunix Can you add your steps for reproducing

**Comment by monaka** [comment]
@sunix Possibly #6311 is same.

**Comment by sunix** [comment]
@vparfonov hard to give steps to reproduce ... it happens to me randomly all the time,
When saving file most of the time, looks like it's related to the file watchers and sync but it's hard to tell

**Comment by monaka** [comment]
@sunix Is it possible to open the process manager on the host OS ?
Values of CPU and memory usage in your browser will be some good hints.

**Comment by ghost** [comment]
@vparfonov I can reliably reproduce it. Looks like requests to project api are timed out sometimes for big projects.

**Comment by ghost** [comment]
Also, seeing lots of:

```
[STDOUT] 2017-09-19 05:41:16,621[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: Can't find IClasspathEntry for path /che/core/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoTemplate.java
[STDOUT] java.lang.RuntimeException: Can't find IClasspathEntry for path /che/core/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoTemplate.java
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.getRuntimeException(AbstractJavaTestRunner.java:257)
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.findCompilationUnitByPath(AbstractJavaTestRunner.java:178)
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.detectTests(AbstractJavaTestRunner.java:80)
[STDOUT] 	at org.eclipse.che.api.testing.server.TestingRPCService.handleTestDetection(TestingRPCService.java:95)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] 2017-09-19 05:41:16,621[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: Can't find IClasspathEntry for path /che/core/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoTemplate.java
[STDOUT] java.lang.RuntimeException: Can't find IClasspathEntry for path /che/core/che-core-api-dto/src/main/java/org/eclipse/che/dto/generator/DtoTemplate.java
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.getRuntimeException(AbstractJavaTestRunner.java:257)
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.findCompilationUnitByPath(AbstractJavaTestRunner.java:178)
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.detectTests(AbstractJavaTestRunner.java:80)
[STDOUT] 	at org.eclipse.che.api.testing.server.TestingRPCService.handleTestDetection(TestingRPCService.java:95)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
```
I also observed that after the IDE freezes it returns to life after dev machine spits out this log.

Also, there's a question why request to project tree is made after each file save.

**Comment by sunix** [comment]
maybe related to https://github.com/eclipse/che/issues/6308

**Comment by ghost** [comment]
@sunix definitely related

**Comment by vparfonov** [comment]
Here temporary workaround fix https://github.com/eclipse/che/pull/6341 . 
@vinokurig @tolusha plase take a look and take to the nearest sprint this isuee
