### ISSUE TITLE
After rename project, context menu for project node fails with Exception.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#6223]
**Reproduction Steps:**
1. Create some project from template.
2. Open project.
3. Rename project with help context menu for example.
4. Click on the project by "Right" mouse button.
Expected result: context menu should appear.
Actual result: context menu didn't appear(after refresh page context menu works again). There is exception in the development console :
_app-0.js:2340 Tue Sep 12 09:45:57 GMT+300 2017 com.google.gwt.logging.client.LogConfiguration
SEVERE: (TypeError) : Cannot read property 'a' of null
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'a' of null
	at Unknown.Emm(PHPRunContainerTestAction.java:91)
	at Unknown.Qbf(AbstractPerspectiveAction.java:112)
	at Unknown.Ubf(AbstractPerspectiveAction.java:91)
	at Unknown.Rkk(Utils.java:133)
	at Unknown.Skk(Utils.java:76)
	at Unknown.Ujk(PopupMenu.java:224)
	at Unknown._jk(PopupMenu.java:153)
	at Unknown.ceh(ContextMenu.java:99)
	at Unknown.vej(ProjectExplorerViewImpl.java:115)
	at Unknown.cgk(Tree.java:1500)
	at Unknown.px(SchedulerImpl.java:50)
	at Unknown.gx(SchedulerImpl.java:347)
	at Unknown.tx(SchedulerImpl.java:78)
	at Unknown.nx(SchedulerImpl.java:141)
	at Unknown.Uw(Impl.java:239)
	at Unknown.Xw(Impl.java:291)
	at Unknown.anonymous(Impl.java:77)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.Kck(NodeLoader.java:329)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.NH(EventBus.java:69)
	at Unknown.qck(SimpleEventBus.java:57)
	at Unknown.rck(NodeLoader.java:329)
	at Unknown.Kck(NodeLoader.java:399)
	at Unknown.Mck(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)

**OS and version:**    
Fedora 25;
CHE version: 5.18.0-SNAPSHOT

**Comment by SkorikSergey** [comment]
Not reproduced in CHE 6.0.5-SNAPSHOT.
