### ISSUE TITLE
OpenShift infrastructure: add TLS support of routes

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#6258]
Currently OpenShift infrastructure does not support TLS which is one of the things that prevents 'spi' to be working on osio. In order to enable TLS the following steps need to be done:
- Having property `che.infra.openshift.secure.routes` for enabling TLS during route creation
- Implement `URLRewriter` which would pick suitable protocol depending on `che.infra.openshift.secure.routes` property
- On OSIO custom router is used which completely ignores the 'host' field and assumes that routes host is supposed to have the following format `$NAME.$NAMESPACE` where:
$NAME = route name
$NAMESPACE = namespace where route has been created.
In theory this supposed to work OOTB, since while route creation the 'host' is not used while route creation, but it still fails for me on osio (looks like there is extra 'che-' path in the route which results in 503 error during workspace creation)

**Comment by ibuziuk** [comment]
Currently can not start workspace on osio. Fails with the following message:
`WebSocket connection to 'wss://servers-app-main-server-4401-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com/wsagent?clientId=1312596289' failed: Error during WebSocket handshake: Unexpected response code: 503`

**Comment by garagatyi** [comment]
@ibuziuk do you think we should use TLS for user's application too?

**Comment by ibuziuk** [comment]
![image](https://user-images.githubusercontent.com/1461122/30420071-c9509d92-9938-11e7-8580-6aa6bc4edd43.png)
yeah, all the routes including those that would be used by user's app would be secure

**Comment by garagatyi** [comment]
What if user's application is not configured to use https behind the proxy that sends http traffic instead of https?

**Comment by ibuziuk** [comment]
@garagatyi could you provide some example where enabling TLS for route that is used for apps preview will break it? Basically, for routes `insecureEdgeTerminationPolicy` *Redirect* is used which would redirect http requests to https (in our rhche stacks run / debug commands are using http scheme but once user is trying to open it in the browser there would be force redirect to https)

**Comment by ibuziuk** [comment]
![image](https://user-images.githubusercontent.com/1461122/30441882-00e38ac0-997b-11e7-8620-c19980e729f4.png)
Was able to start workspace on prod cluster with tls enabled, but for some reason ws-agent dies after a few seconds after workspace startup with the following error:

```
2017-09-14 16:30:12,577[en Executor - 0]  [ERROR] [.e.c.p.m.s.c.MavenTaskExecutor 82]   - java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.che.plugin.maven.server.MavenServerWrapper.customize(MavenServerWrapper.java:82)
java.lang.RuntimeException: java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.resolveMavenProject(MavenProjectManager.java:122)
	at org.eclipse.che.plugin.maven.server.MavenServerWrapper.perform(MavenServerWrapper.java:148)
	at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor.lambda$runTask$0(MavenTaskExecutor.java:65)
	at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor.doRunTasks(MavenTaskExecutor.java:80)
	java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.che.plugin.maven.server.core.MavenProjectResolveTask.perform(MavenProjectResolveTask.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
	java.net.ConnectException: Connection refused (Connection refused)
Caused by: java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	at org.eclipse.che.plugin.maven.server.MavenServerManager$2.create(MavenServerManager.java:111)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.proxy.$Proxy74.createServer(Unknown Source)
	... 8 common frames omitted
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at org.eclipse.che.plugin.maven.server.MavenServerWrapper.perform(MavenServerWrapper.java:141)
	at org.eclipse.che.plugin.maven.server.MavenServerWrapper.customizeMaven(MavenServerWrapper.java:45)
	at org.eclipse.che.plugin.maven.server.rmi.RmiObjectWrapper.getOrCreateWrappedObject(RmiObjectWrapper.java:27)
	at org.eclipse.che.plugin.maven.server.MavenServerManager$2.create(MavenServerManager.java:96)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.<init>(Socket.java:211)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	... 19 common frames omitted
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
/bin/bash: line 278:   214 Killed                  ~/che/ws-agent/bin/catalina.sh jpda run
```
This happens on prod cluster regardless of tls setup

**Comment by ibuziuk** [comment]
@garagatyi @akorneta @sleshchenko guys, maybe you have some ideas about this failure during resolving maven project ?

**Comment by garagatyi** [comment]
@ibuziuk  about TLS. Some app servers such as Tomcat should be configured to work correctly behind a reverse proxy that converts HTTPS traffic to HTTP and passes it to an app server. Without such configuration, Tomcat will work incorrectly in certain situations. 
And it actually can be the reason why ws-agent is killed. In case we can not ping ws-agent we stop the container forcefully and from the inside of the container, it is killing. The reason why we might not be able to ping ws-agent can be lack of that configuration for reverse proxied secure traffic. [Here](https://github.com/eclipse/che/blob/master/assembly/assembly-main/src/assembly/tomcat/conf/server.xml#L154-L154) is the configuration of Che master that is configured to support reverse proxy.  And [here](https://github.com/eclipse/che/blob/master/assembly/assembly-wsagent-server/src/assembly/server.xml#L139) is the configuration of ws-agent Tomcat where the needed valve is not configured. And [here](https://github.com/codenvy/codenvy/blob/8a1bdba9b1b4b371396449a56bbbac0ca9f68531/assembly/assembly-wsagent-server/src/assembly/server.xml#L143-L143) is the same configuration of ws-agent in Codenvy where we actually used a reverse proxy that converts HTTPS to HTTP.
Another reason of killed ws-agent can be OOM of the ws-agent container.

I hope this will help.

**Comment by ibuziuk** [comment]
@garagatyi thanks for the pointer! (just a bit funny that there is no such problem for OpenShiftConnector)

**Comment by garagatyi** [comment]
@ibuziuk Maybe it is not the case, I have just suggested possible reasons. And I don't know why it is not a problem in case of OpenShiftConnector.

**Comment by ibuziuk** [comment]
Finally figured out what is wrong with ws-agent and this is actually coupled with OOM. By default the following amount of resources are provided for pod on prod cluster:
```
    Limits:
      cpu:      1
      memory:   512Mi
    Requests:
      cpu:      60m
      memory:   307Mi
```
After specifying sufficient amount of memory in pod spec workspace is staring just fine and the UX is pretty much the same to what we have on osio right now:

```
  apiVersion: v1
  kind: Pod
  metadata:
    name: app
  spec:
    containers:
        image: rhche/centos_jdk8:latest
        name: main
        resources:
          limits:
            memory: "2000Mi"
          requests:
            memory: "1500Mi"
        ports:
            containerPort: 8080
            protocol: TCP
```

**Comment by garagatyi** [comment]
@ibuziuk Haven't you fixed this issue already?

**Comment by ibuziuk** [comment]
@garagatyi yeah, just forgot to close ;-)
