### ISSUE TITLE
SPI: OpenShiftClient configuration properties

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#6306]
```
che.infra.openshift.master_url=
che.infra.openshift.username=
che.infra.openshift.password=
che.infra.openshift.trust_certs=false
```
Not sure if we really need all those properties. Basically, those are useful if che-server is running via Docker as described in the doc [1], but IMO the dev environment for "openshift" infrastructure should be minishift (e.g. both che-server & workspaces are running there and for this scenario all those properties are not needed). For multi tenat che-server we would probably need to define some config during OpenShiftClient creation but for now it is difficult to say how would it look like (probably it would be smth. that is used in che-starter [2]). My proposal is removing all this properties and using default constructor during OpenShiftClient creation

[1] https://github.com/redhat-developer/rh-che/blob/master/howtos/spi.adoc
[2] https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/openshift/OpenShiftClientWrapper.java#L70

**Comment by ibuziuk** [comment]
@akorneta @sleshchenko @garagatyi does it make sense for you, guys?

**Comment by sleshchenko** [comment]
It'd do my life more difficult =) Because for me it is faster and easier to update che on docker.
I'm OK to remove them if it is needed but I think why should we remove an ability to use OpenShift spi on che-server that is running on docker but not on OpenShift instance.

So I'd remove them a bit later when we will have the ability to configure OpenShift instance like via config file. 
And now I'd inject `doTrustCerts` as optional Boolean, make it empty by default, and use default config for OpenShift client creation. Looks like a creation from default config should work the same as creation from default constructor.
@ibuziuk WDYT?

**Comment by akorneta** [comment]
As for me, it is not a critical issue till we're developing the spi and in most case my environment for che it's a docker + minishift backend for workspaces. But in far future, it may make sense.

**Comment by ibuziuk** [comment]
@sleshchenko @akorneta thanks for feedback. If you think running che server via docker is very handy during active development phase, lets keep this properties.

> And now I'd inject doTrustCerts as optional Boolean, make it empty by default, and use default config for OpenShift client creation. Looks like a creation from default config should work the same as creation from default constructor.

Sounds great!

**Comment by ibuziuk** [comment]
> Looks like a creation from default config should work the same as creation from default constructor.

@sleshchenko unfortunately this is not the case, using config in constructor results in the following error on prod cluster:

```

Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
--
  | at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)
  | at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:199)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.get(OpenShiftProject.java:92)
  | ... 52 common frames omitted
  | Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  | at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
  | at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
  | at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
  | at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
  | at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
  | at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
  | at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
  | at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
  | at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
  | at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
  | at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:267)
  | at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
  | at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
  | at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
  | at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
  | at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
  | at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:64)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  | at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
  | at okhttp3.RealCall.execute(RealCall.java:63)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:228)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:711)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:192)
  | ... 53 common frames omitted
  | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  | at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
  | at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
  | at sun.security.validator.Validator.validate(Validator.java:260)
  | at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
  | at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
  | at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
  | at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
  | ... 87 common frames omitted
  | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  | at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
  | at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
  | at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
  | at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
  | ... 93 common frames omitted

```
What about adding new property `che.infra.openshift.use_default_client` ?

**Comment by sleshchenko** [comment]
@ibuziuk Take a look https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java#L99
I believe using of `OpenShiftConfigBuilder` instead of creating `Config` will work the same as creating a client with the default constructor.

If not, I propose to check if all configuration parameters are missed(null or empty) then create a client with the default constructor. In this way, we don't need additional configuration parameters.

I prefer the first way, I hope it will work. Please check it.

**Comment by ibuziuk** [comment]
@sleshchenko yeah, `configBuilder` should probably do the trick.

**Comment by ibuziuk** [comment]
PR is merged https://github.com/eclipse/che/pull/6498
Closing
