### ISSUE TITLE
Fail pinging ws agent

### ISSUE THREAD

**Issue by DustFinger001** [eclipse-che/che#6327]
I got an error "Fail pinging ws agent with http://localhost:32774/api" when run a workspace .

here is my che server log:

2017-09-19 02:40:38,381[aceSharedPool-0]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 132]   - Fail pinging ws agent with http://localhost:32774/api/ url in workspaceq0o35wjai24vne15 workspace in machinefhm574fk9h9tr02v machine on localhost node.
2017-09-19 02:40:39,946[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
	at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:138)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:681)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:262)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Is localhost right host for workspace machine ?

The che version i used is  'eclipse/che-server:nightly'

And there is a problem (i thought) i found when running this image:
ERROR: user root does OK have write permissions to /conf
Using embedded che.properties... Copying template to /conf/che.properties

Plz help ,  thx .

**Comment by DustFinger001** [comment]
Has solved this problem，should add paramters (-e CHE_HOST... -e CHE_PORT...) ;  see this PR https://github.com/eclipse/che-docs/pull/137
