### ISSUE TITLE
[REGRESSION] "Reveal Resources" feature does not working

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6336]
**Reproduction Steps:**
- Run "Java" stack with default spring project
- Open java class 
- Click twice on project root folder and close project explorer tree
- Set cursor to the opened java class in the editor field
- Go to the "Edit" -> "Reveal Resource"
- Pay attention that java class does not found in the project explorer

**Expected behavior:**
After used "Reveal Resource" feature the java class will be found in the project explorer, and project explorer tree will be expanded to this item

**Observed behavior:**
Java class does not found and project tree does not expanded

**OS and version:**    
Che 5.18.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**
Tue Sep 19 11:03:54 GMT+300 2017 com.google.gwt.logging.client.LogConfiguration
SEVERE: (TypeError) : Cannot read property 'e' of null
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'e' of null
	at Unknown.yij(RevealResourceAction.java:66)
	at Unknown.i1j(PopupMenu.java:562)
	at Unknown.x1j(PopupMenu.java:719)
	at Unknown.BBd(DOM.java:1481)
	at Unknown.gDd(DOMImplStandard.java:317)
	at Unknown.hq(Impl.java:239)
	at Unknown.kq(Impl.java:291)
	at Unknown.anonymous(Impl.java:77)
	at Unknown.aB(EventBus.java:69)
	at Unknown.CVj(SimpleEventBus.java:57)
	at Unknown.DVj(NodeLoader.java:329)
	at Unknown.WVj(NodeLoader.java:399)
	at Unknown.YVj(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.aB(EventBus.java:69)
	at Unknown.CVj(SimpleEventBus.java:57)
	at Unknown.DVj(NodeLoader.java:329)
	at Unknown.WVj(NodeLoader.java:399)
	at Unknown.YVj(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.aB(EventBus.java:69)
	at Unknown.CVj(SimpleEventBus.java:57)
	at Unknown.DVj(NodeLoader.java:329)
	at Unknown.WVj(NodeLoader.java:399)
	at Unknown.YVj(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.aB(EventBus.java:69)
	at Unknown.CVj(SimpleEventBus.java:57)
	at Unknown.DVj(NodeLoader.java:329)
	at Unknown.WVj(NodeLoader.java:399)
	at Unknown.YVj(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.aB(EventBus.java:69)
	at Unknown.CVj(SimpleEventBus.java:57)
	at Unknown.DVj(NodeLoader.java:329)
	at Unknown.WVj(NodeLoader.java:399)
	at Unknown.YVj(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)
	at Unknown.aB(EventBus.java:69)
	at Unknown.CVj(SimpleEventBus.java:57)
	at Unknown.DVj(NodeLoader.java:329)
	at Unknown.WVj(NodeLoader.java:399)
	at Unknown.YVj(NodeLoader.java:391)
	at Unknown.anonymous(JsPromise.java:118)

**Comment by riuvshin** [comment]
@vparfonov @ashumilova please take a look
