### ISSUE TITLE
Investigate ProjectExplorer selenium page object to be able to locate displaying items constantly

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6524]
There are methods of ProjectExplorer selenium page object which works unstable and this causes unexpected failures of tests because of time has run out limit on waiting on visibility of test project item in project explorer of IDE:

**Update!** Issue https://github.com/eclipse/che/issues/7227 should partly fix the problem.

#### org.eclipse.che.selenium.editor.ContextMenuEditorTest#prepare
```
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //div[@path='/ContextMenuEditorTestgrjb']/div (tried for 20 second(s) with 500 MILLISECONDS interval)Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitVisibleItem(ProjectExplorer.java:226)
at org.eclipse.che.selenium.editor.ContextMenuEditorTest.prepare(ContextMenuEditorTest.java:134)
```
![org eclipse che selenium editor contextmenueditortest checkrefactoring_585i35k8](https://user-images.githubusercontent.com/1197777/31077253-871e1236-a786-11e7-95e5-9a9e765ab151.png)

#### org.eclipse.che.selenium.assistant.CheckFindActionFeatureInCheTest#setUp
```
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //div[@path='/CheckFindActionFeatureInCheTestmnnr']/div (tried for 20 second(s) with 500 MILLISECONDS interval)Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
at org.eclipse.che.selenium.core.SeleniumWebDriver.findElement(SeleniumWebDriver.java:108)
at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitVisibleItem(ProjectExplorer.java:226)
at org.eclipse.che.selenium.assistant.CheckFindActionFeatureInCheTest.setUp
```
![org eclipse che selenium assistant checkfindactionfeatureinchetest checksearchactionsforallitemstest_4mu1ohp8](https://user-images.githubusercontent.com/1197777/31078632-95835ec6-a78b-11e7-9002-e57f59b9c4f2.png)

#### [org.eclipse.che.selenium.git.KeepDirectoryGitImportTest::keepDirectoryImportFromGitHub()](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test/109/testReport/junit/org.eclipse.che.selenium.git/KeepDirectoryGitImportTest/keepDirectoryImportFromGitHub/)
```
  org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
...
Command duration or timeout: 31 milliseconds
...
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.openItemByPath(ProjectExplorer.java:421)
	at org.eclipse.che.selenium.git.KeepDirectoryGitImportTest.keepDirectoryImportFromGitHub(KeepDirectoryGitImportTest.java:164)
```
![org eclipse che selenium git keepdirectorygitimporttest keepdirectoryimportfromgithub_bk3nr393](https://user-images.githubusercontent.com/1197777/32794368-53176c82-c971-11e7-992f-97a3d55b4d19.png)

Html dump can be found [here](https://gist.github.com/dmytro-ndp/d30a5eb8d18d777c321f038ab12c2b41).

#### [org.eclipse.che.selenium.git.PullRequestPluginWithForkTest::createPullRequest()](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test/109/testReport/junit/org.eclipse.che.selenium.git/PullRequestPluginWithForkTest/createPullRequest/)
```
      org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
...
Command duration or timeout: 28 milliseconds
...
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.openItemByPath(ProjectExplorer.java:421)
	at org.eclipse.che.selenium.git.PullRequestPluginWithForkTest.createPullRequest(PullRequestPluginWithForkTest.java:128)
```
![org eclipse che selenium git pullrequestpluginwithforktest createpullrequest_c7s0or5v](https://user-images.githubusercontent.com/1197777/32795125-76c6af6a-c973-11e7-9d47-4c46cf6413e2.png)

Html dump can be found [here](https://gist.github.com/dmytro-ndp/380b046c7c90e752d1fd94575024c829).

**_Possible solution_**: perform "click" operation on web element by using JavaScriptExecutor:
```javascript
JavascriptExecutor executor = (JavascriptExecutor)driver;
executor.executeScript("arguments[0].click();", element);
```

#### [org.eclipse.che.selenium.git.CheckoutBranchTest#checkoutBranchTest()](https://ci.codenvycorp.com/view/qa/job/che-multiuser-integration-tests-che6/lastCompletedBuild/testReport/org.eclipse.che.selenium.git/CheckoutBranchTest/checkoutBranchTest/)

```
      org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
...
Command duration or timeout: 35 milliseconds
...
	at org.openqa.selenium.interactions.DoubleClickAction.perform(DoubleClickAction.java:39)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:373)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.openItemByVisibleNameInExplorer(ProjectExplorer.java:473)
	at org.eclipse.che.selenium.git.CheckoutBranchTest.checkoutBranchTest(CheckoutBranchTest.java:152)
```

![org eclipse che selenium git checkoutbranchtest checkoutbranchtest_gcj8ke43](https://user-images.githubusercontent.com/1197777/32835563-3b801846-ca0f-11e7-801e-c4924816542f.png)

Html dump can be found [here](https://gist.github.com/dmytro-ndp/7a898ec9bcedadbe32d2e936a802fa90).

**OS and version:**    
5.19.0-SNAPSHOT, 5.21.0-SNAPSHOT,

**Diagnostics:**

**Comment by dmytro-ndp** [comment]
Close, because it are duplicated by https://github.com/eclipse/che/issues/7605.
