### ISSUE TITLE
After delete folder .git and refresh page can't open project at all.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#6695]
### Reproduction Steps
1. Create project Spring from template.
2. Open project.
3. Display hidden files by "Project -> Show/Hide Hidden Files". Remove folder ".git".
4. Refresh page.
5. Try to open project in the project explorer.
Actual behavior: can't open project in the dev console exception: 
Uncaught (in promise) Error: org.eclipse.che.api.promises.client.FunctionException: org.eclipse.che.plugin.pullrequest.client.vcs.hosting.NoVcsHostingServiceImplementationException: No implementation of the VcsHostingService for the current project
    at ZZe.jp [as ho] (_app-0.js:403:71)
    at ZZe.mp [as jo] (_app-0.js:403:494)
    at ZZe.rp (_app-0.js:406:275)
    at new ZZe (_app-0.js:5130:232)
    at Sxl (_app-0.js:19343:594)
    at Txl.Uxl [as wm] (_app-0.js:19345:68)
    at eval (_app-0.js:5147:129)
    at <anonymous>
Expected behavior: project should be open without any problems.

**OS and version:**    
Fedora 25
**Diagnostics:** 
CHE versiion: 5.19.0-SNAPSHOT

**Comment by AndrienkoAleksandr** [comment]
Seems related to changing or can be fixed in the pull request https://github.com/eclipse/che/pull/6696

**Comment by RomanNikitenko** [comment]
@AndrienkoAleksandr my changes are not merged yet, but I've checked and unfortunately my pull request doesn't fix this issue.

**Comment by tolusha** [comment]
```
Throwable.java:121 Uncaught (in promise) Error: org.eclipse.che.api.promises.client.FunctionException: org.eclipse.che.plugin.pullrequest.client.vcs.hosting.NoVcsHostingServiceImplementationException: No implementation of the VcsHostingService for the current project
    at FunctionException.createError (Throwable.java:121)
    at FunctionException.initializeBackingError (Throwable.java:113)
    at FunctionException.Throwable_3 (Throwable.java:81)
    at FunctionException.Exception_3 (Exception.java:37)
    at new FunctionException (FunctionException.java:24)
    at VcsHostingServiceProvider$1.apply_1099 [as apply_95] (VcsHostingServiceProvider.java:79)
    at VcsHostingServiceProvider$1.apply_1098 [as apply_2] (VcsHostingServiceProvider.java:69)
    at JsPromise.java:70
    at <anonymous>
```

**Comment by tolusha** [comment]
The root of the issue
https://github.com/eclipse/che/blob/4a07971bab2c5e0ec98d5718120b0cf840af5f0a/wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusProvider.java#L108

GitStatusProvider.java fails but rather should send some status.
