### ISSUE TITLE
ERROR: java.lang.IllegalArgumentException: Environment should not be null

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#6798]
Got many of errors in log like:
```
2017-10-18 10:03:01,224[io-8080-exec-42]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error occurred, error time: 2017-10-18 10:03:01
java.lang.IllegalArgumentException: Environment should not be null
	at org.eclipse.che.api.environment.server.EnvironmentParser.checkNotNull(EnvironmentParser.java:158)
	at org.eclipse.che.api.environment.server.EnvironmentParser.parse(EnvironmentParser.java:65)
	at org.eclipse.che.multiuser.resource.api.usage.tracker.EnvironmentRamCalculator.calculate(EnvironmentRamCalculator.java:45)
	at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager.checkRamResourcesAvailability(LimitsCheckingWorkspaceManager.java:221)
	at org.eclipse.che.multiuser.resource.api.workspace.LimitsCheckingWorkspaceManager.startWorkspace(LimitsCheckingWorkspaceManager.java:139)
	at com.codenvy.api.workspace.SystemRamCheckingWorkspaceManager.lambda$startWorkspace$0(SystemRamCheckingWorkspaceManager.java:98)
	at com.codenvy.api.workspace.SystemRamCheckingWorkspaceManager.checkSystemRamLimitAndPropagateStart(SystemRamCheckingWorkspaceManager.java:163)
	at com.codenvy.api.workspace.SystemRamCheckingWorkspaceManager.checkSystemRamLimitAndPropagateLimitedThroughputStart(SystemRamCheckingWorkspaceManager.java:139)
	at com.codenvy.api.workspace.SystemRamCheckingWorkspaceManager.startWorkspace(SystemRamCheckingWorkspaceManager.java:97)
	at org.eclipse.che.multiuser.machine.authentication.server.interceptor.MachineTokenInterceptor.invoke(MachineTokenInterceptor.java:34)
	at org.eclipse.che.api.workspace.server.WorkspaceService.startById(WorkspaceService.java:354)
	at sun.reflect.GeneratedMethodAccessor218.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:419)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.catalina.filters.RestCsrfPreventionFilter.doFilter(RestCsrfPreventionFilter.java:113)
	at com.codenvy.auth.sso.client.CodenvyCsrfFilter.doFilter(CodenvyCsrfFilter.java:59)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.codenvy.auth.sso.client.DefaultTokenHandler.handleValidToken(DefaultTokenHandler.java:66)
	at com.codenvy.api.permission.server.PermissionTokenHandler.handleValidToken(PermissionTokenHandler.java:56)
	at com.codenvy.auth.sso.client.LoginFilter.doFilter(LoginFilter.java:111)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```
It looks like this need to be not 500 type error and shown to user in UI or returned in response to API call with non 500 status. But not in system logs.

**OS and version:**    Codenvy 5.19.0-SaaS

**Comment by sleshchenko** [comment]
@skryzhny @artaleks9 Looks like we can close this issue as `won't fix` since it is not reproducible on latest Che version. WDYT?

**Comment by skryzhny** [comment]
I also can't see it on codenvy v5.22.2
