### ISSUE TITLE
Cant change running port

### ISSUE THREAD

**Issue by ShashankaNataraj** [eclipse-che/che#686]
`sh che.sh -p:9080` throws the following error:

```
2016-03-11 14:26:37,096[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 610]    - Can't start machine ws-machine. Machine recipe downloading failed. Recipe url http://localhost:8080/ide/api/recipe/recipe001h0j05th2kqgd5/script. http://localhost:8080/ide/api/recipe/recipe001h0j05th2kqgd5/script
org.eclipse.che.api.machine.server.exception.MachineException: Can't start machine ws-machine. Machine recipe downloading failed. Recipe url http://localhost:8080/ide/api/recipe/recipe001h0j05th2kqgd5/script. http://localhost:8080/ide/api/recipe/recipe001h0j05th2kqgd5/script
    at org.eclipse.che.api.machine.server.MachineManager.getRecipeByLocation(MachineManager.java:965) ~[che-core-api-machine-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:292) ~[che-core-api-machine-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:167) ~[che-core-api-machine-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.createMachine(RuntimeWorkspaceRegistry.java:421) ~[che-core-api-workspace-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.startEnvironment(RuntimeWorkspaceRegistry.java:320) ~[che-core-api-workspace-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.api.workspace.server.RuntimeWorkspaceRegistry.start(RuntimeWorkspaceRegistry.java:146) ~[che-core-api-workspace-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.performSyncStart(WorkspaceManager.java:637) ~[che-core-api-workspace-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:608) ~[che-core-api-workspace-4.0.0-RC11.jar:4.0.0-RC11]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.0.0-RC11.jar:4.0.0-RC11]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
```

Why exactly cant che use a custom port?

**Comment by garagatyi** [comment]
Have you started/stopped Che before with default (8080) port?

**Comment by ghost** [comment]
Can you elaborate on your use case? OS. Local installation or a VM etc?

`http://localhost:8080/ide/api/recipe/` means that ports hasn't been changed but you can access Che at localhost:9080?

I failed to reproduce it on a local Ubuntu machine.

**Comment by ShashankaNataraj** [comment]
@garagatyi  yes I did  start it with 8080 port before but had to stop it as I have apache using that port now.

@eivantsov Im on OSX el captain. Trying to run the docker image, which runs fine on 8080 port. Its just that I have the port being used by a webserver and wanted to use it on a separate port.

Yes che starts and I can access it too on `localhost:9080`. When I go to dashboard, and click on "open in IDE" on my project, I get the error I posted above on the console. and it gets stuck here on the browser:
<img width="327" alt="screen shot 2016-03-11 at 2 52 29 pm" src="https://cloud.githubusercontent.com/assets/650317/13698265/f0661f2c-e798-11e5-8f6f-ded75b991584.png">

**Comment by garagatyi** [comment]
have you started workspace when Che was running on 8080?
If so did you get this error on start of the same workspace?
If so try create new workspace - it should work. Previous workspace saved link to local storage of recipes that was located on 8080 when Che was on 8080.

**Comment by ghost** [comment]
A new workspace should be ok in this case.

**Comment by ShashankaNataraj** [comment]
@garagatyi Yes I did start the workspace when che was running on 8080. Let me see if creating a new workspace works and get back to you.

**Comment by ShashankaNataraj** [comment]
That works folks!

@eivantsov @garagatyi Thanks a bunch!
