### ISSUE TITLE
Cannot clone git project eclipse/che from a Che factory

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#6869]
### Description
 
got this error in the wsagent logs:

```
2017-10-20 10:12:46,939[io-4401-exec-10]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error occurred, error time: 2017-10-20 
10:12:46                                                                                                                                         
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /projects/che/.git/refs/remotes/origin/<D0><A1>HE-5335.lock
       at sun.nio.fs.UnixPath.encode(UnixPath.java:147)                                                                                         
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)                                                                                          
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)                                                                            
        at java.io.File.toPath(File.java:2234)                                                                                                   
        at org.eclipse.jgit.util.FileUtils.rename(FileUtils.java:261)                                                                            
        at org.eclipse.jgit.internal.storage.file.LockFile.commit(LockFile.java:457)                                                             
        at org.eclipse.jgit.internal.storage.file.RefDirectoryUpdate.doUpdate(RefDirectoryUpdate.java:122)                                       
        at org.eclipse.jgit.lib.RefUpdate$1.execute(RefUpdate.java:517)                                                                          
        at org.eclipse.jgit.lib.RefUpdate.updateImpl(RefUpdate.java:640)                                                                         
        at org.eclipse.jgit.lib.RefUpdate.update(RefUpdate.java:512)                                                                             
        at org.eclipse.jgit.lib.BatchRefUpdate.execute(BatchRefUpdate.java:354)                                                                  
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:224)                                                             
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)                                                                
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179)                                                                       
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)                                                                         
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:201)                                                                        
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)                                                                         
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:84)                                                                          
        at org.eclipse.che.git.impl.jgit.JGitConnection.executeRemoteCommand(JGitConnection.java:2121)                                           
        at org.eclipse.che.git.impl.jgit.JGitConnection.clone(JGitConnection.java:595)                                                           
        at org.eclipse.che.api.git.GitProjectImporter.cloneRepository(GitProjectImporter.java:247)                                               
        at org.eclipse.che.api.git.GitProjectImporter.importSources(GitProjectImporter.java:178)                                                 
        at org.eclipse.che.api.project.server.ProjectManager.doImportProject(ProjectManager.java:522)                                            
        at org.eclipse.che.api.project.server.ProjectManager.importProject(ProjectManager.java:486)                                              
        at org.eclipse.che.api.project.server.ProjectService.importProject(ProjectService.java:405)                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                           
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                         
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)           
```

It looks like the branch `CHE-5335` is not well encoded. We can find back the branch in Github UI by searching for `HE-5335` (without the first C letter)
https://github.com/eclipse/che/branches/all?utf8=%E2%9C%93&query=HE-5335

### Reproduction Steps

Create a workspace from a factory that clone eclipse/che project. The workspace is created but it cannot clone eclipse/che

**OS and version:**    

**Diagnostics:**

**Comment by sunix** [comment]
@vinokurig do you mind if I remove this branch ? CHE-5335 ? to see if it fix this issue ...

**Comment by vinokurig** [comment]
@sunix I removed the branch

**Comment by sunix** [comment]
Removing the branch is fixing the issue, thanks however should we keep that open ? it might  happen in other projects.

**Comment by skabashnyuk** [comment]
Shall we test with new jgit 4.9 https://github.com/eclipse/che/issues/6884?

**Comment by sunix** [comment]
up got the same issue when cloning teletype

import project > https://github.com/atom/teletype.git
and ....
```
2017-11-18 14:38:27,757[nio-4401-exec-3]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error occurred, error time: 2017-11-18 14:38:27
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /projects/teletype/.git/refs/remotes/origin/?
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.io.File.toPath(File.java:2234)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.scanRef(RefDirectory.java:1113)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:109)
	at org.eclipse.jgit.util.FS.lastModified(FS.java:298)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.readRef(RefDirectory.java:1085)
	at org.eclipse.jgit.util.FileUtils.lastModified(FileUtils.java:647)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:225)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.lib.BatchRefUpdate.execute(BatchRefUpdate.java:611)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.pack(RefDirectory.java:699)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:239)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:304)
	at org.eclipse.che.git.impl.jgit.JGitConnection.executeRemoteCommand(JGitConnection.java:2113)
	at org.eclipse.che.git.impl.jgit.JGitConnection.clone(JGitConnection.java:594)
	at org.eclipse.jgit.internal.storage.file.PackedBatchRefUpdate.execute(PackedBatchRefUpdate.java:172)
	at org.eclipse.che.api.git.GitProjectImporter.cloneRepository(GitProjectImporter.java:248)
	at org.eclipse.che.api.git.GitProjectImporter.importSources(GitProjectImporter.java:179)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:201)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.pack(RefDirectory.java:727)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at org.eclipse.che.api.project.server.ProjectService.importProject(ProjectService.java:405)
	at org.eclipse.che.api.project.server.ProjectManager.importProject(ProjectManager.java:486)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1236)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at org.eclipse.che.api.project.server.ProjectManager.doImportProject(ProjectManager.java:522)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:161)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.eclipse.che.plugin.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:52)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:290)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(.....
................
```

**Comment by vinokurig** [comment]
I have successfully cloned  https://github.com/atom/teletype.git

**Comment by sunix** [comment]
interesting maybe stack related:

https://stackoverflow.com/questions/22413421/git-error-malformed-input-or-input-contains-unmappable-chacraters

**Comment by vinokurig** [comment]
Can not reproduce
