### ISSUE TITLE
ServerException in time of injection of default user in selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6952]
### Description
There is an error of injection of default user in selenium tests of Che 6:
```
[ERROR] 1) Error injecting constructor, org.eclipse.che.api.core.ServerException: java.io.IOException
[ERROR] at org.eclipse.che.selenium.core.user.TestUserImpl.<init>(TestUserImpl.java:86)
[ERROR] while locating org.eclipse.che.selenium.core.user.TestUserImpl annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=1)
[ERROR] at org.eclipse.che.selenium.core.user.CheDefaultTestUser.<init>(CheDefaultTestUser.java:36)
[ERROR] at org.eclipse.che.selenium.core.user.CheDefaultTestUser.class(CheDefaultTestUser.java:36)
[ERROR] while locating org.eclipse.che.selenium.core.user.CheDefaultTestUser
[ERROR] while locating org.eclipse.che.selenium.core.user.TestUser
[ERROR] for the 4th parameter of org.eclipse.che.selenium.core.workspace.TestWorkspaceProviderImpl.<init>(TestWorkspaceProviderImpl.java:62)
[ERROR] at org.eclipse.che.selenium.core.workspace.TestWorkspaceProviderImpl.class(TestWorkspaceProviderImpl.java:41)
[ERROR] while locating org.eclipse.che.selenium.core.workspace.TestWorkspaceProviderImpl
[ERROR] at org.eclipse.che.selenium.core.CheSeleniumSuiteModule.configure(CheSeleniumSuiteModule.java:83)
[ERROR] while locating org.eclipse.che.selenium.core.workspace.TestWorkspaceProvider
```

**The problem**: there is out-dated path to _Che Rest API_ [using in tests](https://github.com/eclipse/che/blob/5.19.0/selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/provider/CheTestApiEndpointUrlProvider.java#L33): **/wsmaster/api/**.

**OS and version:**    
Che 6

**Comment by dmytro-ndp** [comment]
This error had already been fixed by another PR: https://github.com/eclipse/che/pull/6917
