### ISSUE TITLE
Selenium tests of Git functionality failed when run simultaneously 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#7018]
### Description
There is [org.eclipse.che.selenium.git](https://github.com/eclipse/che/tree/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git)  tests which influence each other when run simulteniously in several threads, for example for execution _[che-integration-tests:85](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/85/consoleText)_:
```
2017-10-25 22:44:27,221[pool-1-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 177]  - Dependencies injection in org.eclipse.che.selenium.git.CheckoutReferenceTest
2017-10-25 22:44:27,472[onPool-worker-0]  [INFO ] [c.c.TestWorkspaceServiceClient 204]  - Workspace name='workspace615es7' and id='workspaceuhx1ft0mptyzzu31' created
2017-10-25 22:44:34,622[pool-1-thread-3]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 222]  - Processing @PreDestroy annotation in org.eclipse.che.selenium.git.AmendCommitTest
2017-10-25 22:44:34,645[pool-1-thread-3]  [INFO ] [c.c.TestWorkspaceServiceClient 151]  - Workspace name='workspacewjcj4f', id='workspaceieu4zjy5ebrnlg85', username='che' removed
2017-10-25 22:44:34,728[pool-1-thread-3]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 177]  - Dependencies injection in org.eclipse.che.selenium.git.CheckoutToRemoteBranchTest
2017-10-25 22:44:35,312[onPool-worker-1]  [INFO ] [c.c.TestWorkspaceServiceClient 204]  - Workspace name='workspace2gfqcn' and id='workspaces1aoi1wegacrgtia' created
2017-10-25 22:44:52,498[onPool-worker-0]  [INFO ] [o.e.c.s.c.w.TestWorkspaceImpl 64]    - Workspace name='workspace615es7' id='workspaceuhx1ft0mptyzzu31' started.
Oct 25, 2017 10:44:52 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Oct 25, 2017 10:44:52 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
2017-10-25 22:44:57,223[onPool-worker-3]  [INFO ] [o.e.c.s.c.w.TestWorkspaceImpl 64]    - Workspace name='workspacegwwdhl' id='workspace60ts6742sgkdtnrh' started.
Oct 25, 2017 10:44:57 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Oct 25, 2017 10:44:57 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
2017-10-25 22:45:30,362[onPool-worker-1]  [INFO ] [o.e.c.s.c.w.TestWorkspaceImpl 64]    - Workspace name='workspace2gfqcn' id='workspaces1aoi1wegacrgtia' started.
Oct 25, 2017 10:45:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Oct 25, 2017 10:45:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
2017-10-25 22:49:12,278[pool-1-thread-1]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 214]  - Expected condition failed: waiting for element to no longer be visible: By.id: gwt-debug-importProjectWizard-window (tried for 240 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to no longer be visible: By.id: gwt-debug-importProjectWizard-window (tried for 240 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.ImportProjectFromLocation.waitMainFormIsClosed(ImportProjectFromLocation.java:150)
	at org.eclipse.che.selenium.pageobject.ImportProjectFromLocation.clickImportBtn(ImportProjectFromLocation.java:209)
	at org.eclipse.che.selenium.pageobject.ImportProjectFromLocation.waitAndTypeImporterAsGitInfo(ImportProjectFromLocation.java:248)
	at org.eclipse.che.selenium.git.CheckoutReferenceTest.importProjectFromRemoteRepo(CheckoutReferenceTest.java:175)
	at org.eclipse.che.selenium.git.CheckoutReferenceTest.checkCheckoutReference(CheckoutReferenceTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-25 22:49:12,586[pool-1-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 222]  - Processing @PreDestroy annotation in org.eclipse.che.selenium.git.CheckoutReferenceTest
```
There was an error of importing of project from GitHub in test [CheckoutReferenceTest/checkCheckoutReference](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/85/testReport/junit/org.eclipse.che.selenium.git/CheckoutReferenceTest/checkCheckoutReference/)

![org eclipse che selenium git checkoutreferencetest checkcheckoutreference_7ooyr2ei](https://user-images.githubusercontent.com/1197777/32065000-2a82206a-ba84-11e7-91d3-f53aba2ea832.png)

### Git-related tests which revoke grants to access to github:
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportProjectIntoSpecifiedBranchTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/ImportRecursiveSubmoduleTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/KeepDirectoryGitImportTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PullRequestPluginWithForkTest.java

Those tests remove "IDE SSH Key" from github.com when removing all grants `gitHubClientService.deleteAllGrants(gitHubUsername, gitHubPassword)`.

### Git-related tests which rewrite ssh-key for github
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutReferenceTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/CheckoutToRemoteBranchWhichAlreadyHasLinkedLocalBranchTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/FetchUpdatesAndMergeRemoteBranchIntoLocalTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushChangeNotUpdatedRepoTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/PushingChangesTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/RevertCommitTest.java
- che-selenium-test/src/test/java/org/eclipse/che/selenium/git/WorkingWithPullConflictsTest.java

### [Eventually failing tests which are related to Git](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/94/testReport/org.eclipse.che.selenium.git/)
- org.eclipse.che.selenium.git.CheckoutReferenceTest.checkCheckoutReference
- org.eclipse.che.selenium.git.CheckoutToRemoteBranchTest.checkoutToRemoteBranchTest
-
 org.eclipse.che.selenium.git.FetchUpdatesAndMergeRemoteBranchIntoLocalTest.fetchUpdatesAndMergeRemoteBranch
- org.eclipse.che.selenium.git.GitPullTest.pullTest

Command to generate fingerprint of ssh-key: `ssh-keygen -E md5 -l -f public_key.pub`

**_Update_**: the same error here [in job 94](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/94/consoleText).
Log fragment can be found [here](https://gist.github.com/dmytro-ndp/89473f912736f103b70ba3350451ecd5).

**_Update_**: another error **"Auth fail"** which happened [in test GitPullTest.pullTest](https://ci.codenvycorp.com/view/qa/job/release-che-integration-tests/41/testReport/junit/org.eclipse.che.selenium.git/GitPullTest/pullTest/) in time of pulling changes from the github:
![org eclipse che selenium git gitpulltest pulltest_meyxlx4a](https://user-images.githubusercontent.com/1197777/32281467-90b2e1a6-bf27-11e7-92f9-8720d71efd41.png)
There was **ImportRecursiveSubmoduleTest** executing in parallel to **GitPullTest**.

**_Update_**: error of sequential execution of git-related tests has been found as well, for example - the ["Auth fail" error in the **PullRequestTest** here](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test/83/testReport/junit/org.eclipse.che.selenium.git/GitPullTest/pullTest/).
The problem is the [TestGitHubServiceClient::**deleteAllGrants()**](https://github.com/eclipse/che/blob/5.20.0/selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestGitHubServiceClient.java#L180) method removes ssh-key on github.com but further execution of test can fail and, as a result, old ssh-key at the _Eclipse Che_ side can remain and in time of execution of next git-test that ssh-key will not been rewritten. 

**OS and version:**    
Eclipse Che 5.20.0

**Diagnostics:**

**Comment by dmytro-ndp** [comment]
The error didn't reproduce during the 7 sequential [executions on CI](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/87/) (jobs 87-93) after other daily jobs which are executing Git-tests had been obtained separate Git-user for testing.

**Comment by dmytro-ndp** [comment]
The proper way to run tests from **Git-package** sequentially is to change parallel execution to in suite to be `parallel="tests"`, that means that all test classes described in _\<test>_ section of _suite xml_ will be executed in one thread, and then extract test classes from **Git-package** into separate _\<test>_ section.
