### ISSUE TITLE
[CHE 6] A workspace fails to start if project from astro-splash template is created there

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7105]
### Description
A workspace fails to start if project from astro-splash template is created there

### Reproduction Steps
1. Create workspace from Java stack.
2. Start the created workspace and create a project from `astro-splash` template.
3. Stop workspace.
4. Try to start workspace.
Expected:
Workspace starts successfully.
Actual:
Workspace reaches timeout of a start. Workspace agent has the following errors logs in the output:
```
2) Invocation error of method public void org.eclipse.che.api.project.server.ProjectRegistry.initProjects() throws org.eclipse.che.api.core.ConflictException,org.eclipse.che.api.core.NotFoundException,org.eclipse.che.api.core.ServerException,org.eclipse.che.api.core.ForbiddenException on org.eclipse.che.api.project.server.ProjectRegistry@c4a12be
 
	... 71 more
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
Caused by: java.io.IOException: error=2, No such file or directory
	at org.eclipse.che.plugin.composer.server.executor.ComposerCommandExecutor.execute(ComposerCommandExecutor.java:62)
	at org.eclipse.che.plugin.composer.server.projecttype.ComposerProjectInitializer.onProjectInitialized(ComposerProjectInitializer.java:43)
Caused by: org.eclipse.che.api.core.ServerException: java.io.IOException: Cannot run program "composer" (in directory "/projects/astro-splash"): error=2, No such file or directory
  while locating org.eclipse.che.api.project.server.ProjectRegistry
	... 69 more
Caused by: java.io.IOException: Cannot run program "composer" (in directory "/projects/astro-splash"): error=2, No such file or directory
    for the 4th parameter of org.eclipse.che.api.project.server.ProjectManager.<init>(ProjectManager.java:101)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
See attachment:
![astro-sample](https://user-images.githubusercontent.com/5887312/32222825-73cafd60-be43-11e7-8f2e-a9c109c34158.gif)

**Comment by SkorikSergey** [comment]
Cannot reproduce this issue. Project import from **astro-splash** template failed with error:
![selection_257](https://user-images.githubusercontent.com/7760565/39867752-1a1dc344-545f-11e8-8f96-603b241934e0.png)

**Additional information:**

<details>
<summary>Failed HTTP request</summary>

curl 'http://router6qhdq2e-eclipse-che.172.19.20.28.nip.io/api/project/batch?clientId=1882273520' -H 'Origin: http://che-eclipse-che.172.19.20.28.nip.io' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8,ru;q=0.7' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: http://che-eclipse-che.172.19.20.28.nip.io/che/wksp-d85b?uid=795622' -H 'Connection: keep-alive' --data-binary '[{"name":"a5", "attributes":{"language":["php"]}, "type":"composer", "source":{"location":"https://github.com/kaloyan-raev/astrosplash.git", "type":"git", "parameters":{}}, "path":"/a5", "options":{}, "description":null, "problems":[], "mixins":[], "links":[]}]' --compressed

Response:
```
{"message":"Internal Server Error occurred, error time: 2018-05-10 11:28:47"}
```

</details>

<details>
<summary>Workspace agent logs </summary>

<pre>
2018-05-10 11:21:07,606[nio-4401-exec-6]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error occurred, error time: 2018-05-10 11:2
1:07
com.google.gson.JsonSyntaxException: java.io.IOException: Is a directory
        at com.google.gson.Gson.fromJson(Gson.java:903)
        at com.google.gson.Gson.fromJson(Gson.java:826)
        at org.eclipse.che.plugin.composer.server.projecttype.ComposerValueProviderFactory$ComposerValueProvider.readModel(ComposerValueProviderFacto
ry.java:74)
        at org.eclipse.che.plugin.composer.server.projecttype.ComposerValueProviderFactory$ComposerValueProvider.getValues(ComposerValueProviderFacto
ry.java:60)
        at org.eclipse.che.api.project.server.impl.RegisteredProject.initAttributes(RegisteredProject.java:152)
        at org.eclipse.che.api.project.server.impl.RegisteredProject.<init>(RegisteredProject.java:119)
        at org.eclipse.che.api.project.server.impl.RegisteredProject$$FastClassByGuice$$b4fa812c.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
        at com.sun.proxy.$Proxy26.create(Unknown Source)
        at org.eclipse.che.api.project.server.impl.ProjectConfigRegistry.put(ProjectConfigRegistry.java:64)
        at org.eclipse.che.api.project.server.impl.ExecutiveProjectManager.update(ExecutiveProjectManager.java:183)
        at org.eclipse.che.api.project.server.impl.SynchronizingProjectManager.update(SynchronizingProjectManager.java:123)
        at org.eclipse.che.api.project.server.impl.ValidatingProjectManager.update(ValidatingProjectManager.java:177)
        at org.eclipse.che.api.project.server.impl.ProjectServiceApi.createBatchProjects(ProjectServiceApi.java:193)
        at org.eclipse.che.api.project.server.ProjectService.createBatchProjects(ProjectService.java:201)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
        at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
        at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        ...
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Is a directory
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read1(BufferedReader.java:212)
<\pre>

</details>

**Comment by SkorikSergey** [comment]
Not actual
