### ISSUE TITLE
Multiple User Che failed to Load Dashboard in Docker in CentOS in Oracle Virtual Box with all ports open

### ISSUE THREAD

**Issue by ramur** [eclipse-che/che#7238]
### Description
Trying to setup Multiple user configuration of Eclipse Che through Docker in CentOS 7 which is under Oracle VirtualBox with all ports open in firewalld. 
Using the below command

sudo docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=10.0.2.15 -e CHE_KEYCLOAK_AUTH-SERVER-URL=http://10.0.2.15:5050/auth 
  -e CHE_KEYCLOAK_REALM=che -e CHE_KEYCLOAK_CLIENT__ID=che-public 
  -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start

All containers are starting and I could login and change the admin password. After changing the admin password, could not see my dashboard. I can access the keycloak admin screens.

### Reproduction Steps

Accessing the url : http://10.0.2.15:8080/dashboard and login using admin

**Javascript Console Error:**
Firefox can’t establish a connection to the server at ws://10.0.2.15:8080/wsmaster/websocket?token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMjNGc3kzRlI5dnRUZms3TGlkX1lQOGU0cDNoY0psM20wQTRnckIzNnJJIn0.eyJqdGkiOiI3MWU3M2U3ZS1iNzBkLTQzNjktYTY4ZS0wYjlmZTZmMzYwZGIiLCJleHAiOjE1MTAxMjA3MjgsIm5iZiI6MCwiaWF0IjoxNTEwMTIwNDI4LCJpc3...

**Network Error**
403 Error for accessing APIs : http://10.0.2.15:8080/api/workspace/settings
Response: 403 error with HTML message : "Access to the specified resource has been forbidden."

### Environment
CentOS 7 - running under Oracle VirtualBox with all ports open in firewalld
Docker latest version

**Diagnostics:** 

The following error trace occurs:

2017-11-08 05:45:33,916[nio-8080-exec-2]  [ERROR] [s.KeycloakAuthenticationFilter 149]  - Exception during retrieval of the Keycloak realm public key
java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)

...

2017-11-08 05:45:35,954[nio-8080-exec-3]  [INFO ] [s.KeycloakAuthenticationFilter 136]  - Pulling realm public key from URL : http://10.0.2.15:5050/auth/realms/che
2017-11-08 05:45:35,957[nio-8080-exec-3]  [ERROR] [s.KeycloakAuthenticationFilter 149]  - Exception during retrieval of the Keycloak realm public key
java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
...

2017-11-08 05:45:35,958[nio-8080-exec-3]  [ERROR] [s.KeycloakAuthenticationFilter 118]  - Failed verifying the JWT token after public key update
java.lang.IllegalArgumentException: signing key cannot be null.
        at io.jsonwebtoken.lang.Assert.notNull(Assert.java:85)
        at io.jsonwebtoken.impl.DefaultJwtParser.setSigningKey(DefaultJwtParser.java:157)
        at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:94)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:60)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:419)
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)

**Comment by ghost** [comment]
@ramur can you create a user and log in as a user?

**Comment by ramur** [comment]
@eivantsov I could create new user and login, and could not see the Dashboard. 403 error

**Comment by ghost** [comment]
@ramur can you try it this way?

`sudo docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=10.0.2.15 -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser1:/data eclipse/che start`

**Comment by benoitf** [comment]
@ramur in the command line `-e CHE_KEYCLOAK_AUTH-SERVER-URL=http://10.0.2.15:5050/auth` is invalid, property name is `CHE_KEYCLOAK_AUTH__SERVER__URL`

**Comment by ghost** [comment]
@ramur just having CHE_HOST is enough, the cli will auto configure other envs.

**Comment by ramur** [comment]
@eivantsov Thank you, I will check and let you know. 
@benoitf Thank you for correcting.

**Comment by ramur** [comment]
@eivantsov, I still facing the same problem.  Since this couldn't work, I have added those parameters. Now I tried this, no luck. Not sure what mistake I am doing.

**Comment by ghost** [comment]
@ramur can you not set CHE_HOST at all? Let CLI auto detect it. What is your OS?

**Comment by ramur** [comment]
@eivantsov, I am still facing the same problem. Since this syntax didn't work I have added those parameters.

**Comment by ghost** [comment]
`docker run -it -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser2:/data eclipse/che start`

Share output from this command.

**Comment by ramur** [comment]
OS is CentOS running in Oracle Virtual box. I will try this method and will let you know. Since I am out of office now,  I will send reply after an hour or so.

**Comment by ghost** [comment]
@ramur the problem is newtorking, or at least it does look like it is:

```
2017-11-08 05:45:33,916[nio-8080-exec-2] [ERROR] [s.KeycloakAuthenticationFilter 149] - Exception during retrieval of the Keycloak realm public key
java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
```

**Comment by ramur** [comment]
@eivantsov, yes. I logged in che server via docker exec and try to ping key cloak server and vice versa. Worked. But not sure. I will try and let you know.

**Comment by ghost** [comment]
So you were able to get to  `http://10.0.2.15:5050/auth/realms/che` from within Che server container?

**Comment by ramur** [comment]
@elvantsov, really sorry, I made some blunder, while I checked the ping command from che container, I did not try and realized, port 5050 still not open in the host machine, which was creating the problem. Now after that hint of connecting the http://10.0.2.15:5050/auth/realms/che, I realized that mistake. Really sorry for the same. It is working now. I could see the Dashboard.

**Comment by ramur** [comment]
@elvantsov, Thank you very much for the patience and support.
