### ISSUE TITLE
Unable to start a workspace after compiling Che

### ISSUE THREAD

**Issue by thejaay** [eclipse-che/che#726]
Hello,

Now that I'm quite familiar with Che I've decided to take a look on the latest implemented feature (and maybe contribute if I have some free time). I have been able to run Che and try every features available (creating workspace, projects, Git ...) on the version downloaded straight from eclipse website (eclipse-che-4.0.0-RC3).
Unfortunately when cloning code from Git things are not going as good, when creating a new workspace it get stuck at step 2/4 and no docker commands are issued as it does normally (pulling docker image and so on)

Che version : master
Che directory : /opt/eclipse/eclipse-che-build/che/
Java : 1.8.0_73
docker : 1.10.1
maven : 3.3.3
Environment : Virutla server (vmware) running Debian 3.16.7-ckt20-1+deb8u3

Building step : 

```
cd /opt/eclipse/eclipse-che-build/
git clone https://github.com/eclipse/che.git
cd assembly 
mvn clean install
```

=> Build succeeded

Running : 

```
cd assembly-main/target/eclipse-che-4.0.0-RC14-SNAPSHOT/eclipse-che-4.0.0-RC14-SNAPSHOT/bin
./che.sh -s:uid -r:myserver.net (<= exact same command I'm running with RC3 wich is working, I'm not using an IP in the -r arg but a DNS wich seems to work fine on RC3 )
```

I've tried to build with tag `4.0.0-RC9` with the same result

Thank for your help

**Comment by ghost** [comment]
Can you share server logs?

**Comment by thejaay** [comment]
I'm running che as root, then try to create a new project from PHP stack (I'm on 4.0.0-RC9 tag)

```
############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
#############################################################

Using CATALINA_BASE:   /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat
Using CATALINA_HOME:   /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat
Using CATALINA_TMPDIR: /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/temp
Using JRE_HOME:        /opt/jdk/jdk1.8.0_73/
Using CLASSPATH:       /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/conf/:/opt/jdk/jdk1.8.0_73//lib/tools.jar:/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/bin/bootstrap.jar:/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/bin/tomcat-juli.jar
2016-03-16 14:37:10,831[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.29
2016-03-16 14:37:10,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Nov 20 2015 09:18:00 UTC
2016-03-16 14:37:10,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.29.0
2016-03-16 14:37:10,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2016-03-16 14:37:10,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.16.0-4-amd64
2016-03-16 14:37:10,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2016-03-16 14:37:10,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk/jdk1.8.0_73/jre
2016-03-16 14:37:10,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_73-b02
2016-03-16 14:37:10,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2016-03-16 14:37:10,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat
2016-03-16 14:37:10,834[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat
2016-03-16 14:37:10,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/conf/logging.properties
2016-03-16 14:37:10,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2016-03-16 14:37:10,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
2016-03-16 14:37:10,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
2016-03-16 14:37:10,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
2016-03-16 14:37:10,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2016-03-16 14:37:10,837[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9
2016-03-16 14:37:10,838[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/logs/
2016-03-16 14:37:10,838[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2016-03-16 14:37:10,838[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2016-03-16 14:37:10,838[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2016-03-16 14:37:10,838[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/conf/
2016-03-16 14:37:10,839[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/endorsed
2016-03-16 14:37:10,839[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat
2016-03-16 14:37:10,839[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat
2016-03-16 14:37:10,839[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/temp
2016-03-16 14:37:10,953[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-8080"]
2016-03-16 14:37:10,965[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
2016-03-16 14:37:10,967[main]             [INFO ] [o.a.catalina.startup.Catalina 587]   - Initialization processed in 327 ms
2016-03-16 14:37:10,984[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - L'Ã©couteur distant JMX a configurÃ© le rÃ©pertoire sur le port 32001 et le serveur sur le port 32101 pour le serveur Platform
2016-03-16 14:37:10,985[main]             [INFO ] [o.a.c.core.StandardService 433]      - DÃ©marrage du service Catalina
2016-03-16 14:37:10,985[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.29
2016-03-16 14:37:11,023[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - DÃ©ploiement de l'archive /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/dashboard.war de l'application web
2016-03-16 14:37:11,217[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/dashboard.war has finished in 193 ms
2016-03-16 14:37:11,218[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - DÃ©ploiement de l'archive /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/ide.war de l'application web
2016-03-16 14:37:13,550[ost-startStop-1]  [WARN ] [p.DockerExtConfBindingProvider 51]   - DockerExtConfBindingProvider
2016-03-16 14:37:14,329[ost-startStop-1]  [INFO ] [.c.p.d.c.DockerRegistryChecker 43]   - Probing registry 'http://localhost:5000'
2016-03-16 14:37:14,340[ost-startStop-1]  [INFO ] [.c.p.d.c.DockerRegistryChecker 48]   - Probe of registry 'http://localhost:5000' succeed with HTTP response code '200'
2016-03-16 14:37:14,631[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/ide.war has finished in 3Â 413 ms
2016-03-16 14:37:14,635[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - DÃ©ploiement de l'archive /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/swagger.war de l'application web
2016-03-16 14:37:14,667[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/swagger.war has finished in 32 ms
2016-03-16 14:37:14,668[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1036]       - DÃ©ploiement du rÃ©pertoire /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/ROOT de l'application web
2016-03-16 14:37:14,697[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1152]       - Deployment of web application directory /opt/eclipse/eclipse-che-build/che/assembly/assembly-main/target/eclipse-che-4.0.0-RC9/eclipse-che-4.0.0-RC9/tomcat/webapps/ROOT has finished in 29 ms
2016-03-16 14:37:14,704[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-8080"]
2016-03-16 14:37:14,712[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 3745 ms
2016-03-16 14:38:21,553[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 140]    - EVENT#workspace-created# WS#wksp-m1ri# WS-ID#workspaceo0lt3ta2hn60l7op# USER#che#
```

After that it show nothing more and stay stuck in my browser at 

```
2 / 4
web-php-simple : Start workspace master
```

No error happen in the log so I can't really go further sorry

**Comment by TylerJewell** [comment]
If you run Che as root, you should be presented with a friendly error message when you attempt to create a new workspace, as this will fail.  The reason is that Che inherits the properties of the user. This means that when you create a workspace, the projects that are created as root are mounted into the workspace.  But the user in the workspace is UID=1000 and will not have the right permissions to modify the project files.  So we should be presenting an error message saying that you cannot get into the workspace because che was run as root user.  Did that not happen?

**Comment by ghost** [comment]
@thejaay  used `-s:uid`

So, workspace has been created ok.

Make sure the ephemeral port range is opened for inbound connections for your server. It's -r that causes the issue. You may want to open Chrome dev console and take a look at websocket connections that browser initiates.

**Comment by thejaay** [comment]
@eivantsov The port range opened is all application port for Che (32768-65535) like said above, I had no problem accessing and creating new workspace with RC3.
I have tried the following : analyzing traffic for both my instalaltion (RC3 and RC9), here are my results after hitting create project button (PHP stack)
RC3
![image](https://cloud.githubusercontent.com/assets/4380207/13815794/4309018a-eb8c-11e5-8720-5d5860cd4ffe.png)

RC9
![image](https://cloud.githubusercontent.com/assets/4380207/13815835/6a15f760-eb8c-11e5-97f7-f376aad2274b.png)

As a side note I am behind a proxy (that's why I get some HTTP 407 error)

PS: Websocket seems not to work with a proxy on Chrome (Version 49.0.2623.87 m) so I am using Firefox (I both can access internet with as proxy is already configured properly)

**Comment by ghost** [comment]
You need to figure out why websocket connections to ports 327.... are blocked.As soon, and those connections are successful, the IDE will be loaded.

**Comment by ghost** [comment]
Also, can you skip Dashboard and go to http://domain.com/ide/$workspaceName

A workspace should start and chances are that we grabs some logs from workspace agent. If it starts OK and can ping master, then it's your browser that cannot connect to workspace agent and terminal. If server logs say that workspace has been created, it means that Che server has successfully connected to workspace agent.

**Comment by thejaay** [comment]
I will try to get as much informations as I can and provide them to you. I am not able to get into the workspace, it is asking me to create a new workspace named after the one I'm trying to access

EDIT
The connexion to websocket is OK with RC3 but I definitely think that the proxy is messing up somewhere. I will try it from home and tell you my results (that's still not explain why it was working with the previous version)

**Comment by ghost** [comment]
OK, when you are stuck, if you run docker ps, do you see a workspace container? If it is up for long, then it's your local client (browser) that cannot connect to it. At least, I think so )

**Comment by thejaay** [comment]
@eivantsov OK so I've tried to run Che tag 4.0.0-RC13 from home, I got now an error during step 3 when creating a project, here is the log

```
[STDERR] /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2016-03-16 21:25:37,462[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.29
[STDOUT] 2016-03-16 21:25:37,464[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Nov 20 2015 09:18:00 UTC
[STDOUT] 2016-03-16 21:25:37,464[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.29.0
[STDOUT] 2016-03-16 21:25:37,465[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2016-03-16 21:25:37,465[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.16.0-4-amd64
[STDOUT] 2016-03-16 21:25:37,465[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2016-03-16 21:25:37,470[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jre1.8.0_65
[STDOUT] 2016-03-16 21:25:37,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_65-b17
[STDOUT] 2016-03-16 21:25:37,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2016-03-16 21:25:37,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2016-03-16 21:25:37,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2016-03-16 21:25:37,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2016-03-16 21:25:37,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2016-03-16 21:25:37,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2016-03-16 21:25:37,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
[STDOUT] 2016-03-16 21:25:37,474[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2016-03-16 21:25:37,474[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2016-03-16 21:25:37,474[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2016-03-16 21:25:37,474[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2016-03-16 21:25:37,474[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2016-03-16 21:25:37,474[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2016-03-16 21:25:37,474[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2016-03-16 21:25:37,475[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2016-03-16 21:25:37,475[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2016-03-16 21:25:37,476[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2016-03-16 21:25:37,476[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2016-03-16 21:25:37,589[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-03-16 21:25:37,597[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2016-03-16 21:25:37,599[main]             [INFO ] [o.a.catalina.startup.Catalina 587]   - Initialization processed in 382 ms
[STDOUT] 2016-03-16 21:25:37,654[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2016-03-16 21:25:37,658[main]             [INFO ] [o.a.c.core.StandardService 433]      - Starting service Catalina
[STDOUT] 2016-03-16 21:25:37,659[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.29
[STDOUT] 2016-03-16 21:25:37,704[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[STDOUT] Wed Mar 16 21:25:42 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2016-03-16 21:25:42,070[rrest.WSClient1]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/ide/api/eventbus/?token=dummy_token. 
[STDOUT] 2016-03-16 21:25:42,227[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ide.war has finished in 4,523 ms
[STDOUT] 2016-03-16 21:25:42,234[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-03-16 21:25:42,237[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 4637 ms
[STDOUT] 2016-03-16 21:25:42,369[nio-4401-exec-1]  [WARN ] [i.ContainerResponse$BodyWriter 90]   - Client has aborted connection. Response writing omitted.
[STDOUT] 2016-03-16 21:25:54,344[nio-4401-exec-6]  [ERROR] [c.s.o.RemoteOAuthTokenProvider 75]   - Exception on token retrieval, message : OAuth token for user che was not found
[STDOUT] 2016-03-16 21:25:55,108[nio-4401-exec-6]  [ERROR] [c.s.o.RemoteOAuthTokenProvider 75]   - Exception on token retrieval, message : OAuth token for user che was not found
[STDOUT] 2016-03-16 21:25:55,353[nio-4401-exec-6]  [INFO ] [o.e.c.a.c.u.ContentTypeGuesser 55]   - Successfully load content types from jar:file:/home/user/che/ws-agent/webapps/ide/WEB-INF/lib/che-core-api-core-4.0.0-RC13.jar!/content-types.properties
[STDOUT] 2016-03-16 21:25:56,500[nio-4401-exec-8]  [WARN ] [.c.a.p.s.DefaultProjectManager 817]  - pom.xml does not exist.
[STDOUT] org.eclipse.che.api.project.server.ValueStorageException: pom.xml does not exist.
[STDOUT]    at org.eclipse.che.ide.extension.maven.server.projecttype.MavenValueProviderFactory.readModel(MavenValueProviderFactory.java:59) ~[che-plugin-java-ext-maven-4.0.0-RC13.jar:4.0.0-RC13]
[STDOUT]    at org.eclipse.che.ide.extension.maven.server.projecttype.MavenValueProviderFactory$MavenValueProvider.getValues(MavenValueProviderFactory.java:102) ~[che-plugin-java-ext-maven-4.0.0-RC13.jar:4.0.0-RC13]
[STDOUT]    at org.eclipse.che.api.project.server.type.Variable.getValue(Variable.java:52) ~[che-core-api-project-4.0.0-RC13.jar:4.0.0-RC13]
[STDOUT]    at org.eclipse.che.api.project.server.DefaultProjectManager.estimateProject(DefaultProjectManager.java:785) ~[che-core-api-project-4.0.0-RC13.jar:4.0.0-RC13]
[STDOUT]    at org.eclipse.che.api.project.server.DefaultProjectManager.resolveSources(DefaultProjectManager.java:805) ~[che-core-api-project-4.0.0-RC13.jar:4.0.0-RC13]
[STDOUT]    at org.eclipse.che.api.project.server.ProjectService.resolveSources(ProjectService.java:465) [che-core-api-project-4.0.0-RC13.jar:4.0.0-RC13]
[STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
[STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
[STDOUT]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
[STDOUT]    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
[STDOUT]    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:154) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:141) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:289) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:280) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:205) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:95) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:64) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:134) [everrest-core-1.12.1.jar:na]
[STDOUT]    at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:63) [everrest-core-1.12.1.jar:na]
[STDOUT]    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
[STDOUT]    at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.0.jar:na]
[STDOUT]    at org.eclipse.che.env.local.server.SingleEnvironmentFilter.doFilter(SingleEnvironmentFilter.java:93) [che-plugin-sdk-env-local-4.0.0-RC13.jar:4.0.0-RC13]
[STDOUT]    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [guice-servlet-4.0.jar:na]
[STDOUT]    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [guice-servlet-4.0.jar:na]
[STDOUT]    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.29]
[STDOUT]    at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
[STDOUT]    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-coyote.jar:8.0.29]
[STDOUT]    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-coyote.jar:8.0.29]
[STDOUT]    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.29]
[STDOUT]    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.29]
[STDOUT]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
[STDOUT]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
[STDOUT]    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.29]
[STDOUT]    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

After that I am not able to access the project but the workspace is created and running. It's like I am missing a pom.xml but I don't understand why Maven things are there

**Comment by ghost** [comment]
No pom.xml is a known bug, but it should not prevent you from accessing the IDE. Where exactly are you stuck now? You should still see Open in IDE button at this point.

If a workspace is running, you may access it at /ide/${ws-name}. Again, it never hurts to open browser's dev console and take a look at websocket connections.

Also, you may just create a workspace without a project, and then import it from within the IDE.

**Comment by thejaay** [comment]
@eivantsov Things are working perfectly on the latest version of master. Problem must've been on my side, issue can be closed
