### ISSUE TITLE
Unexpected failing selenium tests from TestRunnerPlugin package

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7338]
### Description
* Sometimes on CI server we have unexpected status a test that has been run by TestRunnerPlugin. For example: we have test that should be failed. But in the tree with project tests result - we have test with "uncertain status". (grey color) see screenshot:
![org eclipse che selenium testrunner javatestpluginjunit4test shouldexecutejunit4testclasswithdifferentstatuses_0ujootu7](https://user-images.githubusercontent.com/1640058/32731475-97497dd0-c892-11e7-9cf2-c6f60b31a1da.png)
* It happens randomly only CI in multithread selenium mode. 

**OS and version:**   Ci-server, che-selenium integration tests

**Comment by musienko-maxim** [comment]
This issue can be resolved after implementation language servers for tests. We should clarify what we will do.

**Comment by tolusha** [comment]
```
2017/12/27 14:26:59 Start new terminal.
	at org.eclipse.che.commons.lang.execution.ProcessHandler$$Lambda$160/1760472966.accept(Unknown Source)
	... 29 common frames omitted
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at org.eclipse.che.api.testing.server.framework.TestMessagesOutputTransmitter.processLine(TestMessagesOutputTransmitter.java:65)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.eclipse.che.commons.lang.execution.OutputReader.lambda$start$0(OutputReader.java:51)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 149 path $
	at org.eclipse.che.commons.lang.execution.OutputReader.doStart(OutputReader.java:70)
	at org.eclipse.che.api.testing.server.framework.TestMessagesOutputTransmitter.process(TestMessagesOutputTransmitter.java:105)
	... 15 common frames omitted
	at org.eclipse.che.api.testing.server.framework.LineSplitter.process(LineSplitter.java:43)
	at org.eclipse.che.commons.lang.execution.ProcessHandler.notifyOnText(ProcessHandler.java:173)
	at org.eclipse.che.api.testing.server.framework.TestMessagesOutputTransmitter.access$100(TestMessagesOutputTransmitter.java:23)
	... 20 common frames omitted
	at com.sun.proxy.$Proxy79.onText(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.eclipse.che.api.testing.server.messages.ServerTestingMessage.internalParse(ServerTestingMessage.java:74)
	at org.eclipse.che.commons.lang.execution.OutputReader.consumeLine(OutputReader.java:114)
	at org.eclipse.che.commons.lang.execution.OutputReader.readIfAvailable(OutputReader.java:104)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 149 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at org.eclipse.che.commons.lang.execution.OutputReader.processRead(OutputReader.java:123)
Caused by: java.lang.reflect.InvocationTargetException: null
	at org.eclipse.che.api.testing.server.framework.LineSplitter.processLine(LineSplitter.java:59)
	at org.eclipse.che.commons.lang.execution.ProcessHandler.lambda$createNotifier$0(ProcessHandler.java:63)
	at org.eclipse.che.api.testing.server.messages.ServerTestingMessage.internalParse(ServerTestingMessage.java:88)
	at org.eclipse.che.api.testing.server.framework.TestMessagesOutputTransmitter.processTestingMessage(TestMessagesOutputTransmitter.java:81)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at org.eclipse.che.api.testing.server.messages.ServerTestingMessage.parse(ServerTestingMessage.java:62)
	at org.eclipse.che.api.testing.server.framework.TestMessagesOutputTransmitter$1.onText(TestMessagesOutputTransmitter.java:47)
	... 31 common frames omitted
	at org.eclipse.che.commons.lang.execution.ProcessHandler$$Lambda$158/876153175.invoke(Unknown Source)
Caused by: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 149 path $
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.eclipse.che.api.testing.server.framework.TestMessagesOutputTransmitter$$Lambda$231/680933829.consume(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.eclipse.che.commons.lang.execution.OutputReader$$Lambda$161/1671649745.run(Unknown Source)
	at org.eclipse.che.commons.lang.execution.ProcessHandler.lambda$createStdOutReader$4(ProcessHandler.java:181)
2017-12-27 14:35:50,054[s polled Thread]  [ERROR] [o.e.c.c.l.e.OutputReader 81]         - null
java.lang.reflect.UndeclaredThrowableException: null
```

**Comment by tolusha** [comment]
```
{"name":"testStarted", "attributes":{"name":"shouldSuccessOfAppOne", "location":"java:test://org.eclipse.che.examples.AppOneTest.shouldSuccessOfAppOne"}}>@@<{"name":"testFinished", "attributes":{"name":"shouldSuccessOfAppOne", "duration":"3"}}
```

```
{"name":"suiteTreeEnded", "attributes":{"name":"org.eclipse.che.examples.AppOneTest", "location":"java:test://org.eclipse.che.examples.AppOneTest"}}>@@<{"name":"testSuiteStarted", "attributes":{"name":"org.eclipse.che.examples.AppOneTest", "location":"java:test://org.eclipse.che.examples.AppOneTest"}}
```

```
{"name":"testStarted", "attributes":{"name":"shouldFailOfAppOne", "location":"java:test://org.eclipse.che.examples.AppOneTest.shouldFailOfAppOne"}}>@@<{"name":"testFailed", "attributes":{"name":"shouldFailOfAppOne", "message":"null", "details":"java.lang.AssertionError!n	at org.junit.Assert.fail(Assert.java:86)!n	at org.junit.Assert.assertTrue(Assert.java:41)!n	at org.junit.Assert.assertFalse(Assert.java:64)!n	at org.junit.Assert.assertFalse(Assert.java:74)!n	at org.eclipse.che.examples.AppOneTest.shouldFailOfAppOne(AppOneTest.java:33)!n	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)!n	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)!n	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)!n	at java.lang.reflect.Method.invoke(Method.java:497)!n	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)!n	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)!n	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)!n	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)!n	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)!n	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)!n	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)!n	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)!n	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)!n	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)!n	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)!n	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)!n	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)!n	at org.eclipse.che.junit.junit4.JUnit4TestReference.run(JUnit4TestReference.java:50)!n	at org.eclipse.che.junit.junit4.CheJUnitCoreRunner.run(CheJUnitCoreRunner.java:56)!n	at org.eclipse.che.junit.junit4.CheJUnitLauncher.main(CheJUnitLauncher.java:29)!n", "duration":"1"}}
```
