### ISSUE TITLE
No error notification for test stacks

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#7498]
### Description

Currently, I am trying to write my own [runtime recipe](https://www.eclipse.org/che/docs/devops/runtime-recipes/index.html) and the recipe fails. 

My "issue" is there appears to be no indication without pulling up `docker logs -f che` except for a never ending blinking che logo.

I believe this is a problem because I assumed the loading would stop after ' java -jar BuildTools.jar' finished executing, which takes 10-30 minutes depending on the computer. After concluding an hour was enough patience, I checked the logs.

### Reproduction Steps

Below is the dockerfile inheriting from an Eclipse Che Base Image [1](https://www.eclipse.org/che/docs/devops/runtime-recipes/index.html#inherit-from-an-eclipse-che-base-image)

`FROM eclipse/ubuntu_jdk8`
`EXPOSE 25565 9000`
`RUN curl -s "https://get.sdkman.io" | bash && \
 source "$HOME/.sdkman/bin/sdkman-init.sh" && \
 sdk install springboot && \
 cd /projects && wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && \
 git config --global --unset core.autocrlf && \
 java -jar BuildTools.jar`

- Click "Test"

- Resulting screenshot:

![image](https://user-images.githubusercontent.com/4656027/33079064-341f5e1a-ce9a-11e7-8a44-aa9f8a3e4798.png)

- Result from 'docker logs -f che`

> 2017-11-21 14:36:52,178[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 430]    - Workspace 'che/test-wksp-sjze' with id 'workspacee3w741x2nmt1rzj7' created by user 'che'
2017-11-21 14:36:52,210[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 238]   - Starting workspace 'che/test-wksp-sjze' with id 'workspacee3w741x2nmt1rzj7' by user 'che'
2017-11-21 14:36:55,828[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 291]   - Workspace 'che:test-wksp-sjze' with id 'workspacee3w741x2nmt1rzj7' start failed
2017-11-21 14:36:55,838[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 301]   - Docker image build failed. Image id not found in build output.
org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Docker image build failed. Image id not found in build output.
	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.buildImage(DockerMachineStarter.java:324)
	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.prepareImage(DockerMachineStarter.java:270)
	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.startContainer(DockerMachineStarter.java:224)
	at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.startMachine(DockerInternalRuntime.java:301)
	at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.internalStart(DockerInternalRuntime.java:199)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:103)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:275)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.che.infrastructure.docker.client.exception.DockerException: Docker image build failed. Image id not found in build output.
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.buildImage(DockerConnector.java:905)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.buildImage(DockerConnector.java:816)
	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.buildImage(DockerMachineStarter.java:322)
	... 11 common frames omitted
^C

**OS and version:**    

`lsb_release -a`

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial

`docker run eclipse/che:6.0.0-M1 version`

> INFO: (che cli): 6.0.0-M1 - using docker 17.05.0-ce / native
> WARN: Newer version '6.0.0-M1' available
> 
> Your CLI version is '6.0.0-M1'.
> Your installed version is '6.0.0-M1'.

**Diagnostics:** 

Above

**Comment by ghost** [comment]
@gnoejuan it should be ok in the latest che6 nightly:

![image](https://user-images.githubusercontent.com/5337267/33256616-7531cf3a-d35b-11e7-94de-18b27bd84982.png)

Please note that this branch is in active development, especially when it comes to workspace loading flow.

**Comment by ghost** [comment]
Closing as cannot reproduce in Che6.
