### ISSUE TITLE
"ForbiddenException: API rate limit exceeded" in selenium tests of github related features

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#7695]
### Description
We have selenium tests of github-related features which run by using dedicated github account **chepullreq2** on pullrequests job. Sometimes they fail because of error: `org.eclipse.che.api.core.ForbiddenException: API rate limit exceeded for chepullreq2.`

#### Stack Trace
```
      org.eclipse.che.api.core.ForbiddenException: API rate limit exceeded for chepullreq2.
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:247)
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:152)
        at org.eclipse.che.selenium.core.client.TestGitHubServiceClient.getAllGrants(TestGitHubServiceClient.java:176)
        at org.eclipse.che.selenium.core.client.TestGitHubServiceClient.deleteAllGrants(TestGitHubServiceClient.java:185)
        at org.eclipse.che.selenium.git.KeepDirectoryGitImportTest.prepare(KeepDirectoryGitImportTest.java:81)
```

Test report: https://ci.codenvycorp.com/job/che-pullrequests-test/180/Selenium_tests_report/failsafe-report.html#Failure_Details

Test report: https://ci.codenvycorp.com/job/che-pullrequests-test/206/Selenium_tests_report/failsafe-report.html#Failure_Details

Test report: https://ci.codenvycorp.com/job/che-pullrequests-test/189/Selenium_tests_report/failsafe-report.html#Failure_Details

**_The reason of error_**:  is the Gihub account **chepullreq2** which is used in the test has been flagged
![screenshot from 2017-12-07 17-11-07](https://user-images.githubusercontent.com/1197777/33722083-adecb0ce-db71-11e7-8d8a-2bf26a7d9df1.png)

and, as a result, it has limit rates of unauthorized user:
```javascript
{"resources":
 {
 "core":
  {"limit":60,"remaining":58,"reset":1512662606},
 "search":
  {"limit":10,"remaining":10,"reset":1512659067},
 "graphql":
  {"limit":0,"remaining":0,"reset":1512662607}
 },
 "rate":
  {"limit":60,"remaining":58,"reset":1512662606}
 }
```

**OS and version:**    
Eclipse Che 6.0.0-M3-SNAPSHOT

Rate Limit Documentation page: https://developer.github.com/v3/rate_limit/

**Comment by dmytro-ndp** [comment]
I contacted github.com support to the unflag the account.

**Comment by dmytro-ndp** [comment]
Request to support of github.com helped, and account "**chepullreq2**" was unflagged.
An answer from support:
> Hey there,
> Sorry about that! Sometimes our spam-detecting systems miss the mark and you were accidentally flagged in the process. I've gone ahead and removed the flag and you shouldn't see that message again.

I have also added contact information into the other test accounts chepullreq1, chepullreq3 in hope to avoid same problem with they.

-----
Minimal observed _remaining API rate_ for non-flagged github account [during execution of selenium tests on Che6](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test/214/consoleText) was **4788**:
```javascript
{"resources":
  {"core":
     {"limit":5000,"remaining":4788,"reset":1512658019},
   "search":
     {"limit":30,"remaining":30,"reset":1512658054},
   "graphql":
     {"limit":5000,"remaining":5000,"reset":1512661594}
  },
  "rate":{"limit":5000,"remaining":4788,"reset":1512658019}
}
```
