### ISSUE TITLE
Print selenium test statistics in the test log during the tests execution

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#7719]
### Description
Sometimes it is useful to know the current progress of selenium tests executing. 
For example, it could help to stop test execution in case of significant regression, or if there is too big latency at the product side.

As a variant, we can print such statistics in test log at the start of each test:
```
Start of test org.eclipse.che.selenium.miscellaneous.DialogAboutTest#dialogAboutTest
Executed tests: 120
Failed tests: 2
```

**Comment by vzhukovs** [comment]
It would be better to print to log one message after or before test run smth like:
`Test count: %d, current test: %d, passed: %d, failed: %d. Test name: %s`

**Comment by skabashnyuk** [comment]
@vzhukovskii  I think ```Test count``` may be an unknown value.  You can't count it until all test would be execute. First of all because of ```DataProviders```

**Comment by vzhukovs** [comment]
@skabashnyuk ok, then test count can be omitted

**Comment by dmytro-ndp** [comment]
<details>
 <summary>An example of logs:</summary>
 <pre>
2018-02-21 20:01:06,134[main]             [INFO ] [.e.c.s.c.i.SeleniumTestHandler 203]  - Starting suite 'Multi-thread Eclipse Che tests' with 2 test methods.
2018-02-21 20:01:06,168[pool-1-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 161]  - Starting test #1 NavigateToFileTest.shouldNavigateToFileForFirstProject. Passed: 0, failed: 0, skipped: 0.
2018-02-21 20:01:06,174[pool-1-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 236]  - Dependencies injection in org.eclipse.che.selenium.miscellaneous.NavigateToFileTest
2018-02-21 20:01:06,236[pool-1-thread-1]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 287]  - Test org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileForFirstProject failed because error: ------ shouldNavigateToFileForFirstProject
2018-02-21 20:01:06,256[pool-1-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 161]  - Starting test #2 NavigateToFileTest.shouldNavigateToFileForFirstProject (run 2). Passed: 0, failed: 1, skipped: 0.
2018-02-21 20:01:06,257[pool-1-thread-1]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 287]  - Test org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileForFirstProject (run 2) failed because error: ------ shouldNavigateToFileForFirstProject
2018-02-21 20:01:06,260[pool-1-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 161]  - Starting test #3 NavigateToFileTest.shouldNavigateToFileForFirstProject (run 3). Passed: 0, failed: 2, skipped: 0.
2018-02-21 20:01:06,261[pool-1-thread-1]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 287]  - Test org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileForFirstProject (run 3) failed because error: ------ shouldNavigateToFileForFirstProject
2018-02-21 20:01:06,265[pool-1-thread-1]  [INFO ] [.e.c.s.c.i.SeleniumTestHandler 161]  - Starting test #4 NavigateToFileTest.shouldNotDisplayHiddenFilesAndFoldersInDropDown. Passed: 0, failed: 3, skipped: 0.
2018-02-21 20:01:06,331[main]             [INFO ] [.e.c.s.c.i.SeleniumTestHandler 487]  - Cleaning up test environment...
2018-02-21 20:01:06,332[main]             [INFO ] [.e.c.s.c.i.SeleniumTestHandler 339]  - Processing @PreDestroy annotation in org.eclipse.che.selenium.miscellaneous.NavigateToFileTest
[ERROR] Tests run: 5, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 7.255 s <<< FAILURE! - in TestSuite
[ERROR] shouldNavigateToFileForFirstProject(org.eclipse.che.selenium.miscellaneous.NavigateToFileTest)  Time elapsed: 0.082 s  <<< FAILURE!
java.lang.AssertionError: ------ shouldNavigateToFileForFirstProject
	at org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileForFirstProject(NavigateToFileTest.java:65)

[ERROR] shouldNavigateToFileForFirstProject(org.eclipse.che.selenium.miscellaneous.NavigateToFileTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: ------ shouldNavigateToFileForFirstProject
	at org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileForFirstProject(NavigateToFileTest.java:65)

[ERROR] shouldNavigateToFileForFirstProject(org.eclipse.che.selenium.miscellaneous.NavigateToFileTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: ------ shouldNavigateToFileForFirstProject
	at org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileForFirstProject(NavigateToFileTest.java:65)

[ERROR] tearDown(org.eclipse.che.selenium.miscellaneous.NavigateToFileTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: ------ tearDown
	at org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.tearDown(NavigateToFileTest.java:72)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileForFirstProject(org.eclipse.che.selenium.miscellaneous.NavigateToFileTest)
[ERROR]   Run 1: NavigateToFileTest.shouldNavigateToFileForFirstProject:65 ------ shouldNavigateToFileForFirstProject
[ERROR]   Run 2: NavigateToFileTest.shouldNavigateToFileForFirstProject:65 ------ shouldNavigateToFileForFirstProject
[ERROR]   Run 3: NavigateToFileTest.shouldNavigateToFileForFirstProject:65 ------ shouldNavigateToFileForFirstProject
[INFO] 
[ERROR]   NavigateToFileTest.tearDown:72 ------ tearDown
[INFO] 
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0
 </pre>
</details>

**Comment by vzhukovskii** [comment]
Sounds good
