### ISSUE TITLE
Unexpected fails in the "factory" package

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7940]
We have unexpected fails in the "factory" package in the next tests:

**DirectUrlFactoryWithSpecificBranch**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for presence of element located by: By.xpath: //div[@path='/gitPullTest']/div[contains(concat(' ', normalize-space(@class), ' '), ' selected')] (tried for 20 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.factory.DirectUrlFactoryWithSpecificBranch.factoryWithDirectUrlWithSpecificBranch(DirectUrlFactoryWithSpecificBranch.java:79)
```
![111](https://user-images.githubusercontent.com/22724619/34146407-8bfba170-e4a2-11e7-8190-409f734c6703.png)

 **CreateNamedFactoryFromDashBoard**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for presence of element located by: By.xpath: //div[@path='/CreateNamedFactoryFromDashBoard']/div[contains(concat(' ', normalize-space(@class), ' '), ' selected')] (tried for 20 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.factory.CreateNamedFactoryFromDashBoard.createFactoryFromDashBoard(CreateNamedFactoryFromDashBoard.java:97)
```
![222](https://user-images.githubusercontent.com/22724619/34146477-dd5c9ab0-e4a2-11e7-8e23-1ed3c905d1c6.png)

**CreateFactoryFromUiWithKeepDirTest**

```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for presence of element located by: By.xpath: //div[@path='/FactoryFromUiWithKeepDirTests5']/div[contains(concat(' ', normalize-space(@class), ' '), ' selected')] (tried for 20 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.factory.CreateFactoryFromUiWithKeepDirTest.createFactoryAndSwitchToWs(CreateFactoryFromUiWithKeepDirTest.java:150)
	at org.eclipse.che.selenium.factory.CreateFactoryFromUiWithKeepDirTest.setUpModuleForFactory(CreateFactoryFromUiWithKeepDirTest.java:121)
	at org.eclipse.che.selenium.factory.CreateFactoryFromUiWithKeepDirTest.createFactoryFromUiWithKeepDirTest(CreateFactoryFromUiWithKeepDirTest.java:98)
```

![333](https://user-images.githubusercontent.com/22724619/34146538-24f07f40-e4a3-11e7-9459-f10ae2bcedb1.png)

**Report with problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6/119/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Related to issue https://github.com/eclipse/che/issues/7959

**Comment by Ohrimenko1988** [comment]
For this problem was created issue https://github.com/eclipse/che/issues/7959 . So when this issue will be fixed the tests will be completed successfully.
Try/catch blocks with this issue was added to this three tests.  
https://github.com/eclipse/che/pull/7982
