### ISSUE TITLE
Adding a custom dns resolver in che.env breaks composefile

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7986]
Steps to reproduce:

1. Add `CHE_DNS_RESOLVERS=172.19.20.192` to che.env
2. Restart Che

docker-compose up fails because dns is adde on the service level in yaml

```
  che:
    image: eclipse/che-server:nightly
    mem_limit: 750m
    memswap_limit: 0
    env_file:
      - '/home/eugene/Documents/che-e2/instance/config/che.env'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/home/eugene/Documents/che-e2/instance/data:/data'
      - '/home/eugene/Documents/che-e2/instance/logs:/logs'
      - '/home/eugene/Documents/che-e2/instance/config/che:/conf'
    ports:
      - '8080:8080'
    restart: always
    container_name: che
  dns:
    - 172.19.20.192

```

**Comment by ghost** [comment]
+1, as I am also having this issue. I am behind a proxy, and I can't seem to `git clone` within the Eclipse Che workspace on our enterprise repository or even a personal Github repository. The proxies come in fine as environment variables, but that doesn't seem to be the factor, so I would like to try to test a DNS configuration.

**Edit**: I'm also overriding the default message with `--fast`
```
INFO: We could not resolve DockerHub using DNS.
INFO: Either we cannot reach the Internet or Docker's DNS resolver needs a modification.
```
Despite configuring a proxy and setting DNS within `docker 17.09.1-ce / docker4mac`. I have used my proxy settings to pull/run images fine, so I don't think this is the issue, but it's good to note.

**Comment by ghost** [comment]
@james-r-smith it is not the same issue. You need to configure proxy in Che. Maybe these docs can help https://www.eclipse.org/che/docs/setup/getting-started/index.html#proxy-installation

**Comment by qianlei90** [comment]
@eivantsov Any solution? I have to use custom dns resolver in our internal network. It's all ok when I deploy che with helm, using nip.io.  But it get an error when I change to a domain that can only be resolved by our dns:

```
2018-05-30 08:07:44,262[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4752] - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-ant-colony.che.ant-colony.cn/auth/realms/che/.well-known/openid-configuration
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:61)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:48)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.dao.KeycloakProfileDao.<init>(KeycloakProfileDao.java:46)
  while locating org.eclipse.che.multiuser.keycloak.server.dao.KeycloakProfileDao
  while locating org.eclipse.che.api.user.server.spi.ProfileDao
    for the 2nd parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.<init>(KeycloakUserManager.java:56)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.class(KeycloakUserManager.java:56)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager
  while locating org.eclipse.che.multiuser.api.account.personal.PersonalAccountUserManager
  while locating org.eclipse.che.api.user.server.UserManager
Caused by: java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-ant-colony.che.ant-colony.cn/auth/realms/che/.well-known/openid-configuration
        at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:95)
        at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings$$FastClassByGuice$$e0d0786b.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)

...

```

**Comment by eivantsov** [comment]
@qianlei90 the problem is that this enpoint should be resolved in your cluster. I recommend to open a new issue with more information.

**Comment by qianlei90** [comment]
@eivantsov tks, I found the problem.
just a reminder for someone who has the same problem as mine, to resolve your domain, add your dns to kube-dns:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"yourdomain.com": ["your dns server"]}
```

for details, see [official doc](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configure-stub-domain-and-upstream-dns-servers).

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.
