### ISSUE TITLE
Unexpected fail of CheckIntelligenceCommandFromToolbarTest selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8019]
We have unexpected fail of CheckIntelligenceCommandFromToolbarTest selenium test. It looks like preview URL does not work.
*Log:*
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for text ('This site can’t be reached') to be present in element found by By.tagName: body (tried for 1 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkTestAppAndReturnToIde(CheckIntelligenceCommandFromToolbarTest.java:122)
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbar(CheckIntelligenceCommandFromToolbarTest.java:98)
```
*Report with reproduced problem:*
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/62/Selenium_tests_report/

*Screenshot:*
![bbbb](https://user-images.githubusercontent.com/22724619/34292443-9f008b6e-e709-11e7-847a-91ca31f83df5.png)

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8063
