### ISSUE TITLE
Selenium test report doesn't reflect failed tests with error "session deleted because of page crash from tab crashed"

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8100]
### Description
**PullRequestPluginTest#checkFactoryOnGitHub()** test fails sometimes on CI (for example https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/62/consoleText) but it absent in the list of the test in test report https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/62/Selenium_tests_report/

The problem is: the test record **TEST-org.eclipse.che.selenium.git.PullRequestPluginTest.xml** was absent in the https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/ws/selenium/che-selenium-test/target/failsafe-reports/junitreports/ directory.

Error details:
```
2017-12-23 01:34:08,126[pool-1-thread-1]  [WARN ] [o.o.s.s.ui.ExpectedConditions 899]   - WebDriverException thrown by findElement(By.xpath: //h1//a[text()='che6osio'])
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from tab crashed
  (Session info: chrome=56.0.2924.87)
...
*** Element info: {Using=xpath, value=//h1//a[text()='che6osio']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at org.eclipse.che.selenium.core.SeleniumWebDriver.findElement(SeleniumWebDriver.java:108)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at org.eclipse.che.selenium.git.PullRequestPluginTest.checkGitHubUserPage(PullRequestPluginTest.java:240)
	at org.eclipse.che.selenium.git.PullRequestPluginTest.checkFactoryOnGitHub(PullRequestPluginTest.java:217)
```

Last time it was in the report - https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/57/testReport/junit/org.eclipse.che.selenium.git/PullRequestPluginTest/checkFactoryOnGitHub/

The same situation is with **[GitCompareTest#checkGitCompareTest()](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/124/consoleText)** which failed but completely absent in test report https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/124/testReport/junit/org.eclipse.che.selenium.git/:
```
2017-12-23 22:57:11,179[pool-2-thread-1]  [WARN ] [o.o.s.s.ui.ExpectedConditions 899]   - WebDriverException thrown by findElement(By.id: gwt-debug-loader-panel)
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from tab crashed
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.16.1.el7.x86_64 x86_64) 
...
*** Element info: {Using=id, value=gwt-debug-loader-panel}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:417)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at org.eclipse.che.selenium.core.SeleniumWebDriver.findElement(SeleniumWebDriver.java:108)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:582)
	at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:578)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at org.eclipse.che.selenium.pageobject.Loader.waitOnClosed(Loader.java:55)
	at org.eclipse.che.selenium.git.GitCompareTest.checkGitCompareTest(GitCompareTest.java:213)
```
This issue is related to #7887

**Comment by dmytro-ndp** [comment]
Issue has fixed by #7887
