### ISSUE TITLE
Unexpected fail CheckIntelligenceCommandFromToolbarTest selenium test (White screen)

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8168]
We have unexpected fail CheckIntelligenceCommandFromToolbarTest selenium test. In the screenshot we can see a white screen, usually it happens when workspace cannot start, but workspace is started.  It looks like something wrong with tests groups which provided to the "@BeforeClass" method. We need to investigate and resolve this problem.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.id: gwt-debug-projectTree (tried for 120 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbar(CheckIntelligenceCommandFromToolbarTest.java:98)
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbarOnDocker(CheckIntelligenceCommandFromToolbarTest.java:86)
```
**Screenshot:**

![ccc](https://user-images.githubusercontent.com/22724619/34556855-c27284ee-f140-11e7-8599-44439842f108.png)

**Report with reproduced problem:**

https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/136/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8175
