### ISSUE TITLE
Unexpected fail of CheckIntelligenceCommandFromToolbarTest selenium test (Preview button)

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8190]
We have unexpected fail of CheckIntelligenceCommandFromToolbarTest selenium test. It looks like something went wrong with preview link button in the commands toolbar. We need to investigate and resolve this problem.

**Log:**
```
org.openqa.selenium.WebDriverException: 
unknown error: Element <div class="gwt-Label" style="margin-bottom: 0px;">...</div> is not clickable at point (1770, 41). Other element would receive the click: <div id="gwt-debug-partSwitcher" class="GIWAMGHBGGC">...</div>
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.16.1.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 95 milliseconds
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: '4d6c8145682c', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.QN9rfl}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 36a5977c11e1c11ff1961c6bb993328f
Command duration or timeout: 649 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=true, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.QN9rfl}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=true, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=de93284d-603e-451b-8158-86d72cfd6c4d, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: de93284d-603e-451b-8158-86d72cfd6c4d
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbar(CheckIntelligenceCommandFromToolbarTest.java:112)
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbarOnDocker(CheckIntelligenceCommandFromToolbarTest.java:86)
```

**Screenshot:**

![aaa](https://user-images.githubusercontent.com/22724619/34602215-9de6b844-f207-11e7-8efd-4017f7ff87b5.png)

**Report with reproduced problem:**

https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/137/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8195

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8212
