### ISSUE TITLE
Unexpected fail of CheckAutocompleteFeaturesInTheTestFolderTest selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8242]
We have unexpected fail of CheckAutocompleteFeaturesInTheTestFolderTest selenium test. It looks like something went wrong in the method which read text from java-doc popup. We need to investigate and resolve this problem.
**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of all elements located by By.xpath: //div[@id='gwt-debug-multiSplitPanel-tabsPanel']//div[text()='Test'] (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.editor.autocomplete.CheckAutocompleteFeaturesInTheTestFolderTest.checkOpenDeclaration(CheckAutocompleteFeaturesInTheTestFolderTest.java:76)
	at org.eclipse.che.selenium.editor.autocomplete.CheckAutocompleteFeaturesInTheTestFolderTest.checkAutocompleteFeaturesInTheTestFolderTest(CheckAutocompleteFeaturesInTheTestFolderTest.java:65)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/job/che-pullrequests-test/327/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8247
