### ISSUE TITLE
The Che server is unable to ping your workspace. 

### ISSUE THREAD

**Issue by vhp1360** [eclipse-che/che#8290]
Hello,
I tried to run Che server on CentOS7 with 
`
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vatani/Che/backup:/tmp/offline -v ~/.che-multiuser:/data -e CHE_HOST=a.a.a.a -e CHE_DOCKER_IP_EXTERNAL=a.a.a.a -e CHE_DOCKER_MACHINE_HOST=a.a.a.a eclipse/che start --offline --fast
`
but I got the below error message:
> Could not start workspace Test1. Reason: Start of environment 'default' failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.

the error from docker logs -f che is :

> 2018-01-14 11:58:27,732[aceSharedPool-1]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 147]   - Fail pinging ws agent with http://a.a.a.a:32925/api/ url in workspacefltsmi5tob5jpgdr workspace in machineb9qgrg0sdz3fzydh machine on localhost node.
2018-01-14 11:58:31,623[aceSharedPool-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:153)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:681)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:800)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
2018-01-14 11:59:20,950[aceSharedPool-2]  [INFO ] [m.BaseServerEvaluationStrategy 141]  - cheWorkspacesRoutingSuffixProvider = null
2018-01-14 11:59:20,951[aceSharedPool-2]  [INFO ] [m.BaseServerEvaluationStrategy 141]  - cheWorkspacesRoutingSuffixProvider = null
2018-01-14 11:59:20,952[aceSharedPool-2]  [INFO ] [m.BaseServerEvaluationStrategy 141]  - cheWorkspacesRoutingSuffixProvider = org.eclipse.che.plugin.docker.client.WorkspacesRoutingSuffixProvider@2500762
2018-01-14 11:59:20,952[aceSharedPool-2]  [INFO ] [m.BaseServerEvaluationStrategy 141]  - cheWorkspacesRoutingSuffixProvider = org.eclipse.che.plugin.docker.client.WorkspacesRoutingSuffixProvider@2500762
2018-01-14 11:59:20,953[aceSharedPool-2]  [INFO ] [m.BaseServerEvaluationStrategy 141]  - cheWorkspacesRoutingSuffixProvider = org.eclipse.che.plugin.docker.client.WorkspacesRoutingSuffixProvider@2500762
2018-01-14 11:59:21,032[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspacefltsmi5tob5jpgdr
2018-01-14 11:59:23,303[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacefltsmi5tob5jpgdr
2018-01-14 11:59:25,583[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspacefltsmi5tob5jpgdr

and from _http://a.a.a.a:8080/dashboard/#/ide/che/Test1_ in browser:

> [DOCKER] latest: Pulling from eclipse/ubuntu_python 
[DOCKER] Digest: sha256:68a662c6d0d2c72d7ce14c074bb4ae7333f6f4e803687c928a9d52760ccb12f4 
[DOCKER] Status: Image is up to date for eclipse/ubuntu_python:latest 
[STDOUT] 2018/01/14 11:59:21 Exec-agent configuration
[STDOUT] 2018/01/14 11:59:21   Server
[STDOUT] 2018/01/14 11:59:21     - Address: :4412
[STDOUT] 2018/01/14 11:59:21     - Base path: ''
[STDOUT] 2018/01/14 11:59:21   Process executor
[STDOUT] 2018/01/14 11:59:21     - Logs dir: /home/user/che/exec-agent/logs
[STDOUT] 2018/01/14 11:59:21 
[STDOUT] 2018/01/14 11:59:21 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2018/01/14 11:59:21 Process Routes:
[STDOUT] 2018/01/14 11:59:21 ✓ Start Process ........................... POST   /process
[STDOUT] 2018/01/14 11:59:21 ✓ Get Process ............................. GET    /process/:pid
[STDOUT] 2018/01/14 11:59:21 ✓ Kill Process ............................ DELETE /process/:pid
[STDOUT] 2018/01/14 11:59:21 ✓ Get Process Logs ........................ GET    /process/:pid/logs
[STDOUT] 2018/01/14 11:59:21 ✓ Get Processes ........................... GET    /process
[STDOUT] 2018/01/14 11:59:21 
[STDOUT] 2018/01/14 11:59:21 Exec-Agent WebSocket routes:
[STDOUT] 2018/01/14 11:59:21 ✓ Connect to Exec-Agent(websocket) ........ GET    /connect
[STDOUT] 2018/01/14 11:59:21 
[STDOUT] 2018/01/14 11:59:21 ⇩ Registered RPCRoutes:
[STDOUT] 
[STDOUT] 2018/01/14 11:59:21 Process Routes:
[STDOUT] 2018/01/14 11:59:21 ✓ process.start
[STDOUT] 2018/01/14 11:59:21 ✓ process.kill
[STDOUT] 2018/01/14 11:59:21 ✓ process.subscribe
[STDOUT] 2018/01/14 11:59:21 ✓ process.unsubscribe
[STDOUT] 2018/01/14 11:59:21 ✓ process.updateSubscriber
[STDOUT] 2018/01/14 11:59:21 ✓ process.getLogs
[STDOUT] 2018/01/14 11:59:21 ✓ process.getProcess
[STDOUT] 2018/01/14 11:59:21 ✓ process.getProcesses
[STDOUT] 2018/01/14 11:59:23 Terminal-agent configuration
[STDOUT] 2018/01/14 11:59:23   Server
[STDOUT] 2018/01/14 11:59:23     - Address: :4411
[STDOUT] 2018/01/14 11:59:23     - Base path: ''
[STDOUT] 2018/01/14 11:59:23   Terminal
[STDOUT] 2018/01/14 11:59:23     - Slave command: ''
[STDOUT] 2018/01/14 11:59:23     - Activity tracking enabled: true
[STDOUT] 2018/01/14 11:59:23   Workspace master server
[STDOUT] 2018/01/14 11:59:23     - API endpoint: http://che-host:8080/wsmaster/api
[STDOUT] 2018/01/14 11:59:23 
[STDOUT] 2018/01/14 11:59:23 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2018/01/14 11:59:23 Terminal routes:
[STDOUT] 2018/01/14 11:59:23 ✓ Connect to pty(websocket) ............... GET    /pty
[STDOUT] 2018/01/14 11:59:23 
[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2018-01-14 11:59:27,316[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.11
[STDOUT] 2018-01-14 11:59:27,320[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Jan 10 2017 21:02:52 UTC
[STDOUT] 2018-01-14 11:59:27,320[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.11.0
[STDOUT] 2018-01-14 11:59:27,320[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2018-01-14 11:59:27,321[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-693.11.1.el7.x86_64
[STDOUT] 2018-01-14 11:59:27,321[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2018-01-14 11:59:27,321[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
[STDOUT] 2018-01-14 11:59:27,321[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
[STDOUT] 2018-01-14 11:59:27,322[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2018-01-14 11:59:27,322[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2018-01-14 11:59:27,322[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2018-01-14 11:59:27,322[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2018-01-14 11:59:27,323[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2018-01-14 11:59:27,323[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2018-01-14 11:59:27,323[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
[STDOUT] 2018-01-14 11:59:27,323[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2018-01-14 11:59:27,324[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2018-01-14 11:59:27,324[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
[STDOUT] 2018-01-14 11:59:27,324[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/che/ws-agent/conf/tomcat-logger.xml
[STDOUT] 2018-01-14 11:59:27,324[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
[STDOUT] 2018-01-14 11:59:27,324[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
[STDOUT] 2018-01-14 11:59:27,324[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2018-01-14 11:59:27,325[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2018-01-14 11:59:27,325[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2018-01-14 11:59:27,325[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2018-01-14 11:59:27,325[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2018-01-14 11:59:27,325[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2018-01-14 11:59:27,326[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2018-01-14 11:59:27,326[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2018-01-14 11:59:27,386[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 525]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2018-01-14 11:59:27,397[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
[STDOUT] 2018-01-14 11:59:27,399[main]             [INFO ] [o.a.catalina.startup.Catalina 617]   - Initialization processed in 414 ms
[STDOUT] 2018-01-14 11:59:27,458[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2018-01-14 11:59:27,459[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service Catalina
[STDOUT] 2018-01-14 11:59:27,459[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.11
[STDOUT] 2018-01-14 11:59:27,599[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] 2018-01-14 11:59:31,093[ost-startStop-1]  [WARN ] [o.e.c.w.s.WsAgentURLProvider 73]     - Network is unreachable (connect failed)
[STDOUT] 2018-01-14 11:59:31,170[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4733]    - Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CheBootstrap
[STDOUT] com.google.inject.CreationException: Unable to create injector, see the following errors:
[STDOUT] 
[STDOUT] 1) Error in custom provider, java.lang.RuntimeException: Failed to configure wsagent endpoint
[STDOUT]   while locating org.eclipse.che.wsagent.server.WsAgentURLProvider
[STDOUT]   while locating java.lang.String annotated with @com.google.inject.name.Named(value=wsagent.endpoint)
[STDOUT]     for the 1st parameter of org.eclipse.che.plugin.java.server.rest.JavadocUrlProviderImpl.<init>(JavadocUrlProviderImpl.java:30)
[STDOUT]   at org.eclipse.che.plugin.java.server.rest.JavadocUrlProviderImpl.class(JavadocUrlProviderImpl.java:30)
[STDOUT]   while locating org.eclipse.che.plugin.java.server.rest.JavadocUrlProviderImpl
[STDOUT]   while locating org.eclipse.che.JavadocUrlProvider
[STDOUT]     for field at org.eclipse.che.jdt.rest.UrlContextProvider.provider(UrlContextProvider.java:16)
[STDOUT] 
[STDOUT] 1 error
[STDOUT] 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[STDOUT] 	at com.google.inject.Guice.createInjector(Guice.java:99)
[STDOUT] 	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
[STDOUT] 	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
[STDOUT] 	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
[STDOUT] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] Caused by: java.lang.RuntimeException: Failed to configure wsagent endpoint
[STDOUT] 	at org.eclipse.che.wsagent.server.WsAgentURLProvider.get(WsAgentURLProvider.java:74)
[STDOUT] 	at org.eclipse.che.wsagent.server.WsAgentURLProvider.get(WsAgentURLProvider.java:33)
[STDOUT] 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
[STDOUT] 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
[STDOUT] 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
[STDOUT] 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[STDOUT] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
[STDOUT] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
[STDOUT] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[STDOUT] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[STDOUT] 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
[STDOUT] 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[STDOUT] 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
[STDOUT] 	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
[STDOUT] 	at com.google.inject.internal.InjectionRequestProcessor$StaticInjection$1.call(InjectionRequestProcessor.java:123)
[STDOUT] 	at com.google.inject.internal.InjectionRequestProcessor$StaticInjection$1.call(InjectionRequestProcessor.java:117)
[STDOUT] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
[STDOUT] 	at com.google.inject.internal.InjectionRequestProcessor$StaticInjection.injectMembers(InjectionRequestProcessor.java:117)
[STDOUT] 	at com.google.inject.internal.InjectionRequestProcessor.injectMembers(InjectionRequestProcessor.java:79)
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:171)
[STDOUT] 	... 18 common frames omitted
[STDOUT] 2018-01-14 11:59:31,211[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4733]    - Exception sending context initialized event to listener instance of class org.eclipse.che.everrest.ServerContainerInitializeListener
[STDOUT] java.lang.NullPointerException: null
[STDOUT] 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.<init>(RequestDispatcher.java:84)
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.getEverrestProcessor(ServerContainerInitializeListener.java:195)
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.createWsServerEndpointConfig(ServerContainerInitializeListener.java:137)
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.contextInitialized(ServerContainerInitializeListener.java:96)
[STDOUT] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] 2018-01-14 11:59:31,211[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5190]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
[STDOUT] 2018-01-14 11:59:31,214[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5241]     - Context [] startup failed due to previous errors
[STDOUT] 2018-01-14 11:59:31,232[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 3,632 ms
[STDOUT] 2018-01-14 11:59:31,236[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-4401]
[STDOUT] 2018-01-14 11:59:31,247[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 3847 ms

could you please guide me in this regard?

Thanks.

**Comment by ghost** [comment]
@vhp1360 can you share some more info about your environment and why you use `CHE_DOCKER_MACHINE_HOST`? The error looks like it has been caused by some network failures.

**Comment by vhp1360** [comment]
OK! what shall I share?
regarding `CHE_DOCKER_MACHINE_HOST`, I add it after I faced this problem and I found it in githubing :-)

**Comment by ghost** [comment]
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vatani/Che/backup:/tmp/offline -v ~/.che-multiuser1:/data eclipse/che start
```
Can you give it a try this way?

**Comment by vhp1360** [comment]
Hi,
very sorry for late.
I did it and it didn't do anything.
in command prompt:
> WARN: Bound 'eclipse/che' to 'eclipse/che:5.22.1'
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
INFO: (che cli): 5.22.1 - using docker 17.05.0-ce / native
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Starting containers...
INFO: (che start): Services booting...
INFO: (che start): Server logs at "docker logs -f che"

and nothing in _docker logs -f che_

**Comment by vhp1360** [comment]
Hello dears,
is there any update , please?

**Comment by ghost** [comment]
@vhp1360 when you say that `docker logs -f che` produce no output, do you mean the command just hangs? 

Also, can you try with `:nightly` tag and append `--pull` to your run command?

**Comment by vhp1360** [comment]
thanks for reply.
NO, not hang.
regarding 
> Also, can you try with :nightly tag and append --pull to your run command?

I don't know what is :nightly.

do I need to install kubernet?

**Comment by ghost** [comment]
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock  -v ~/.che-multiuser_nightly:/data eclipse/che:nightly start --pull`

**Comment by vhp1360** [comment]
thanks,
but I guessed there is another reason because my previous code did not work too,
let me try on it, please confirm: do I need to install kubernet or not?

**Comment by ghost** [comment]
@vhp1360 no you do not need Kubernetes

**Comment by vhp1360** [comment]
Hello again, :-)
could you please confirm: should I install kubernet or not?

**Comment by vhp1360** [comment]
kindly, please keep in touch that I'm still involved with this issue and I encountered a higher problem.
one container and different behaviour in different OS, I opened [ticket](https://github.com/moby/moby/issues/36287) and I'm waiting.

regards.

**Comment by eivantsov** [comment]
@vhp1360 is this still an issue with the latest nightly tag?

**Comment by vhp1360** [comment]
@eivantsov ,
unfortunately, I have not tested the latest version yet.

**Comment by eivantsov** [comment]
Closing due to inactivity
