### ISSUE TITLE
Unexpected fail of CheckIntelligenceCommandFromToolbarTest selenium test (not expected text in the page body)

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8324]
### Description
We have unexpected fail of CheckIntelligenceCommandFromToolbarTest selenium test. It looks like something changed in the page and expected text is not actual now. We need to investigate and resolve this problem.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for text ('This site can’t be reached') to be present in element found by By.tagName: body (tried for 1 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkTestAppAndReturnToIde(CheckIntelligenceCommandFromToolbarTest.java:130)
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbar(CheckIntelligenceCommandFromToolbarTest.java:104)
	at org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest.checkButtonsOnToolbarOnDocker(CheckIntelligenceCommandFromToolbarTest.java:87)
```

**Screenshot:**
![org eclipse che selenium intelligencecommand checkintelligencecommandfromtoolbartest checkbuttonsontoolbarondocker_bdeqejcb](https://user-images.githubusercontent.com/22724619/35032532-dc4cb720-fb6f-11e7-85fc-455cb79ba13f.png)

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/150/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8331
