### ISSUE TITLE
che-mount/che-action does not work with keycloak auth

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#8380]
### Description
It doesn't look like remote mount/actions work anymore since the keycloak upgrades.

### Reproduction Steps
```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/che:/data eclipse/che:nightly action list-workspaces --url http://my.che-server.com --user test --password test
WARNING: No swap limit support
INFO: (che cli): nightly - using docker 17.04.0-ce / native
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che
Digest: sha256:aec6d88bb2cc095f563a377edbd77789d0fa208adaf6a0dc67721d5d8b0e3428
Status: Image is up to date for eclipse/che:nightly

INFO: (che action/list-workspaces): Authenticating as test on "*:80".
ERROR: (che action/list-workspaces): <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.23</h3></body></html>
```

**Comment by davidwindell** [comment]
Thanks @eivantsov, it's now broken with another error:

```
INFO: (che action/list-workspaces): Authenticating as test on "my.che-server.com:5050".
undefined:1
{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMjNGc3kzRlI5dnRUZms3TGlkX1lQOGU0cDNoY0psM20wQTRnckIzNnJJIn0.eyJqdGkiOiI2ZWMwNGIwYi00Mzg1LTRhMzEtOWVjNC1iMDkwNmVlZTg4MGQiLsdfsdfsdfltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjY1NmZlNTA5LWFkYWQtNGRmMS1iYWY1LWM1NWI5NmM0YjVjOCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2Rldi5lZGdlLXNlcnZlcnMuY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ1bWFfYXV0aG9yaXphdGlvbiIssdfjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJuYW1lIjoiVGVzdCBUZXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCIsImdpdmVuX25hbWUiOiJUZXN0IiwiZmFtaWx5X25hbWUiOiJUZXN0IiwiZW1haWwiOiJob3N0bWFzdGVyQG91dGVyZWRnZXVrLmNvbSJ9.PxVj54x7aJUJjRXJ

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.res.on (/che-lib/api/wsmaster/auth/auth-data.js:147:43)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Any thoughts?

**Comment by ghost** [comment]
Worked for me with a default Keycloak container that CLI runs.  Is this how response JSON look like in your case? I mean without closing `"}`

**Comment by ghost** [comment]
Also, can you run the following curl command to get a token?

```
curl --data "grant_type=password&client_id=che-public&username=admin&password=admin" http://172.19.20.180:5050/auth/realms/che/protocol/openid-connect/token
```
Replace username and pass with actual credentials, as well as client id and realm if appropriate

**Comment by davidwindell** [comment]
Looks like curl returns a good token:

```
$ curl --data "grant_type=password&client_id=che-public&username=test&password=test" http://my.che-server.com:5050/auth/realms/che/protocol/openid-connect/token
{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMjNGc3kzRlI5dnRUZms3TGlkX1lQOGU0cDNoY0psM20wQTRnckIzNnJJIn0.eyJqdGkiOiI2MjUyNjAyMi1mZjdhLTQ5YTEtYWM4Yy1iZGJkOWZmMTMzZTciLCJleHAiOjE1MTY2MjM0MzIsIm5iZiI6MCwiaWF0IjoxNTE2NjIzMTMyLCJpc3MiOiJodHRwOi8vZGV2LmVkZ2Utc2VydmVycy5jb206NTA1MC9hdXRoL3JlYWxtcy9jaGUiLCJhdWQiOiJjaGUtcHVibGljIiwic3ViIjoiNTg5MDc0NmYtZDRiMC00NjJkLTgzMGQtMzQyODI1OWQwMDljIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY2hlLXB1YmxpYyIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6ImMyYjkxMDcyLTMyNjktNDM2MS1iNTc2LTAyMTZhODA2YmFiMCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2Rldi5lZGdlLXNlcnZlcnMuY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ1bWFfYXV0aG9yaXphdGlvbiIsInVzZXIiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJuYW1lIjoiVGVzdCBUZXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCIsImdpdmVuX25hbWUiOiJUZXN0IiwiZmFtaWx5X25hbWUiOiJUZXN0IiwiZW1haWwiOiJob3N0bWFzdGVyQG91dGVyZWRnZXVrLmNvbSJ9.VVeevmuXC_Wx9D7Z8GKI27F5oYcm2UAowiwXXAnrp0JvNvQJ79EDmphOK0Ou-kcjVP0JXwUxj-0yJ1jCGdWl9a51xGrfkpGAv1PrZX1tRE5gaYcIGLtX5MxxXBKdi9gK0D7OFEPbbClFC42K2T2Cf6BlI6TSmFRwCtES_yxczk6yhFAU-FC2mK4O3f83UQTPt_gmSOxuA5AzfY1hukokJLRlXnbjMI4SwsK_FMHPBiwguk6AcE_H9BX6XUtKye5cZ-ZOYl-HW7grHXiBczSHpdhDSz7vNW2HOAFxgPSnfUdeM4Fp81iiZAo7UcW5WbPsXqe3boYdPGOLbO-io1Vmgw","expires_in":300,"refresh_expires_in":86400,"refresh_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMjNGc3kzRlI5dnRUZms3TGlkX1lQOGU0cDNoY0psM20wQTRnckIzNnJJIn0.eyJqdGkiOiI0YTgxZDRhNi1hYzE2LTRhMzYtYTRjOS0wMmUzZmU5ZDczYTQiLCJleHAiOjE1MTY3MDk1MzIsIm5iZiI6MCwiaWF0IjoxNTE2NjIzMTMyLCJpc3MiOiJodHRwOi8vZGV2LmVkZ2Utc2VydmVycy5jb206NTA1MC9hdXRoL3JlYWxtcy9jaGUiLCJhdWQiOiJjaGUtcHVibGljIiwic3ViIjoiNTg5MDc0NmYtZDRiMC00NjJkLTgzMGQtMzQyODI1OWQwMDljIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImNoZS1wdWJsaWMiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJjMmI5MTA3Mi0zMjY5LTQzNjEtYjU3Ni0wMjE2YTgwNmJhYjAiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidW1hX2F1dGhvcml6YXRpb24iLCJ1c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fX0.gCQpg4ZXyNTJRD4csTrKzeYJDOB4-Q76lEa_8XzRheNhpJUHvAPmjmS2TAj6i1Pc29I6RZrEUxTxk04dysj7hFkCIcT1IDZSnBKdxXLjdv3HLHMHtjC8DtIJggFUShlneRBdcjChmSSW5dNCcqYL-1evc-TXC9Y0tNQejZGIAAgR76PuEOeiMCfnu66zgW7MAFciDgYcTgA-piLjBaKxOlV3noX7144p4mni4J7M-0ALbmPV81M4YOnVSqIGGCj1hgowXgHJC6DMAlfLKoSMfah_NPjM0wVySkSjoQJ7JqtBg3yQDimOP5ScAZ1B8gz9_b5BqVpdCxVflr-J11mRSg","token_type":"bearer","not-before-policy":0,"session_state":"c2b91072-3269-4361-b576-0216a806bab0"}
```

**Comment by ghost** [comment]
@davidwindell is this 100% reproducable with che action?

**Comment by davidwindell** [comment]
My bad, I didn't put `/auth` after the CHE_KEYCLOAK_AUTH_SERVER_URL. 

Is it possible for che-action to lookup the keycloak URL from the remote che-server **or** perhaps it might be an idea to set a sane default to the `--url` i.e. if `--url http://my.che-server.com` is specified along with multiuser mode but no `CHE_KEYCLOAK_AUTH_SERVER_URL` is set, default to the url and `:5050/auth`?

**Comment by davidwindell** [comment]
Actually, scratch that, it's stopped working again :confused: same error and partial JSON

**Comment by davidwindell** [comment]
Ok so after further testing, this seems to work sometimes and then a few minutes later the exact same command fails.

**Comment by davidwindell** [comment]
Also, the sync command isn't working at all, it doesn't look to be taking into account the `--url` flag

```
$ docker run -it --rm -e CHE_MULTIUSER=true -e CHE_KEYCLOAK_AUTH_SERVER_URL=http://my.che-server.com:5050/auth -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/che:/data -v /tmp/sync:/sync eclipse/che:nightly sync my-workspace-name --url http://my.che-server.com --user test --password test --unison-verbose
WARNING: No swap limit support
INFO: (che cli): nightly - using docker 17.04.0-ce / native
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che
Digest: sha256:aec6d88bb2cc095f563a377edbd77789d0fa208adaf6a0dc67721d5d8b0e3428
Status: Image is up to date for eclipse/che:nightly

INFO: (che mount): Starting sync process to /tmp/sync
<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.23</h3></body></html>
---------------------------------------
!!!
!!! ERROR: Error when trying to get workspace data for workspace named david-zebreco
!!!
---------------------------------------
List of workspaces are:
ERROR: (Eclipse Che action/list-workspaces): Unable to connect to the remote host 172.17.0.1 on port 8080. Please check the server is listening and that there is no network issue to reach this host. Full error: Error: connect ECONNREFUSED 172.17.0.1:8080
```

**Comment by ghost** [comment]
@davidwindell I have spotted another problem with missing envs - sync calls another docker image, che action is called in entrypoint - without any envs that indicate it's a multi user Che https://github.com/eclipse/che/blob/master/dockerfiles/mount/entrypoint.sh#L113

**Comment by davidwindell** [comment]
Can we elevate this to a bug?

**Comment by ghost** [comment]
I'll create two separate bugs

**Comment by davidwindell** [comment]
@eivantsov can you link the bugs in for me?

**Comment by davidwindell** [comment]
It looks like it should be using `${CHE_HOST}/api/keycloak/settings` to avoid having to pass `CHE_KEYCLOAK_AUTH_SERVER_URL` through

**Comment by ghost** [comment]
https://github.com/eclipse/che/issues/8569

Closing this one. Please follow the above issue
