### ISSUE TITLE
Unexpected fail of DeleteProjectsTest selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8400]
We have unexpected fail of DeleteProjectsTest selenium test. It looks like some error text is present in the terminal after deleting the project. We need to investigate and resolve this problem.

**Log:**
```
java.lang.AssertionError: Error message is present in console
	at org.eclipse.che.selenium.projectexplorer.DeleteProjectsTest.checkErrorMessageNotPresentInConsole(DeleteProjectsTest.java:140)
	at org.eclipse.che.selenium.projectexplorer.DeleteProjectsTest.shouldDeleteProjectByContextMenu(DeleteProjectsTest.java:83)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/153/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8402
