### ISSUE TITLE
Quick documentation is broken when use java language server

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#8467]
### Reproduction Steps
1. Open a workspace with a java project
2. Set cursor into some class name
3. Invoke Quick Documentation (`Ctrl + q`)

![screenshot from 2018-01-26 10-55-08](https://user-images.githubusercontent.com/15607393/35432032-74449a2a-0287-11e8-81a3-e3ca19cc9ce0.png)

<details>
 <summary>Stack trace in dev-machine log</summary>

```
java.lang.NullPointerException: null
	at org.eclipse.che.jdt.JavadocFinder.findJavadoc(JavadocFinder.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at org.eclipse.che.plugin.java.server.rest.JavadocService.findJavadoc(JavadocService.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:423)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.plugin.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:52)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
```
</details>

**Comment by tsmaeder** [comment]
Hmh...can we just invoke the hover on "quick documentation".

**Comment by mmorhun** [comment]
Yes, we can
![screenshot from 2018-01-26 11-21-43](https://user-images.githubusercontent.com/15607393/35433178-1ef25e8c-028b-11e8-8c8b-f8fbe759f532.png)

**Comment by tolusha** [comment]
https://github.com/eclipse/che/blob/2c2bd6637c8169018e2b33397f9d738bbf82a0b1/plugins/plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/plugin/java/server/rest/JavadocService.java#L30

It is used to discover javadoc

**Comment by tolusha** [comment]
It is postponed since we haven't decided the best way to implement the task.

Here is the response, when textDocument/hover is invoked
```
{  
   "jsonrpc":"2.0",
   "id":"15",
   "result":{  
      "contents":[  
         {  
            "language":"java",
            "value":"void java.io.PrintStream.println(String x)"
         },
         "Prints a String and then terminate the line. This method behaves as though it invokes `print(String)` and then `println()`.\n\n *  **Parameters:**\n    \n     *  **x** The `String` to be printed."
      ]
   }
}
```

if we have kind of links here we would reuse `textDocument/hover` for javadoc compiling by adding real links to service which would return nested javadoc.

**Comment by tsmaeder** [comment]
We can fix this by fixing https://github.com/eclipse/eclipse.jdt.ls/issues/76 and then using the hover.

**Comment by tsmaeder** [comment]
So the plan is this:
0. Investigate if 3. is possible :-)
1. fix issue https://github.com/eclipse/eclipse.jdt.ls/issues/76 
2. Show hover on quick docs
3. Fix our LSP hover widget to be able to open the links we get from jdt.ls
