### ISSUE TITLE
Sometimes  Selenium cannot open workspace page after invocation of the straight URL and login.

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8468]
### Description
Selenium cannot open workspace page after invocation of the straight URL and login. It looks like something went wrong with user credentials which were used for workspace creation. We need to investigate and 

**Log:**
```
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: gwt-debug-projectTree (tried for 120 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.editor.autocomplete.FormatterTest.formatterTest(FormatterTest.java:102)
Caused by: org.openqa.selenium.NoSuchElementException: 
no such element: Unable to locate element: {"method":"id","selector":"gwt-debug-projectTree"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.16.1.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 22 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: '82fc916612ef', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.1tHrW7}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: db9dbd3ed9f9930b8f001fa12b153553
*** Element info: {Using=id, value=gwt-debug-projectTree}
Command duration or timeout: 390 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=true, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.1tHrW7}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=true, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=3c3ef535-592d-405c-8c96-884c2927cff1, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 3c3ef535-592d-405c-8c96-884c2927cff1
*** Element info: {Using=id, value=gwt-debug-projectTree}
	at org.eclipse.che.selenium.editor.autocomplete.FormatterTest.formatterTest(FormatterTest.java:102)
```

**Screenshot:**

![formattertest](https://user-images.githubusercontent.com/22724619/35431945-2669b736-0287-11e8-8511-6046a49500fe.png)

**Report with reproduced problem:**

https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/121/Selenium_tests_report/

**Related test:**

FormatterTest

**Comment by Ohrimenko1988** [comment]
### Browser logs 
```
05:54:42 2018-02-19 03:54:42,835[pool-2-thread-2]  [INFO ] [o.e.c.s.c.u.BrowserLogsUtil 49]      - SEVERE http://che-eclipse-che.172.30.3.7.nip.io/_app/8BD013947EC4E9FFA31C03B595699804.cache.js - Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
05:54:42 2018-02-19 03:54:42,836[pool-2-thread-2]  [INFO ] [o.e.c.s.c.u.BrowserLogsUtil 49]      - SEVERE http://che-eclipse-che.172.30.3.7.nip.io/user1519001862/workspace36hdb9 337:32 "Unable to load IDE JavaScript"
05:54:42 2018-02-19 03:54:42,836[pool-2-thread-2]  [INFO ] [o.e.c.s.c.u.BrowserLogsUtil 49]      - SEVERE http://che-eclipse-che.172.30.3.7.nip.io/_app/_app.nocache.js - Failed to load resource: net::ERR_CONNECTION_REFUSED
```

**Comment by Ohrimenko1988** [comment]
Maybe related with: https://github.com/eclipse/che/issues/8788

**Comment by Ohrimenko1988** [comment]
No longer reproducing
