### ISSUE TITLE
Network configuration docker-local not working

### ISSUE THREAD

**Issue by gorootde** [eclipse-che/che#8478]
### Description
When running che-multiuser with `CHE_DOCKER_SERVER__EVALUATION__STRATEGY=docker-local` che-server is not able to ping the workspace agent.

It seems like the root cause is that che-server tries to reach the workspace via `http://localhost:<publishedPort>/api/` which is not reachable from the perspective of the che-server container. This URL works perfectly fine when accessing the URL from the host.

According to the documentation in `che.env` I would assume when using `docker-local`, that the che-server would use `http://<internalWorkspaceContainerId>:<exposedPort>/api/`

I have tested the following connections:
- On host system `curl -v http://localhost:<publishedWorkspacePort>/api/` --> Works
- In running che-server `curl -v http://localhost:<publishedWorkspacePort>/api/` --> Connection Refused
- In running che-server `curl -v http://<workspaceIP>:<publishedWorkspacePort>/api/` --> Connection Refused
- In running che-server `curl -v http://<workspaceIP>:<exposedWorkspacePort>/api/` --> Works
- Connection from workspace to che works as well.

This setup is relevant when running che-server behind a reverse proxy.

### Reproduction Steps

1. Manually change che-server container configuration to not publish `8080` (only expose it)
2. Set  `CHE_DOCKER_SERVER__EVALUATION__STRATEGY=docker-local` 
2. Start up a workspace
3. Wait for the che-server workspace-ping timeout

**OS and version:**    
Che 5.22.1 (Multiuser)

**Diagnostics:** 
```

 Fail pinging ws agent with http://localhost:32926/api/ url in workspacep5i57q442zmmlxf6 workspace in machinexbjdz66b5n9iq6su machine on localhost node.
2018-01-26 11:52:50,948[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:153)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:681)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:800)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)



```

**Comment by ghost** [comment]
@gorootde what do you try to achieve with setting this strategy? FYI, it has been deprecated  in 6.x version. Can you please elaborate on your network setup? Maybe there's some solution in 6.x version already.

**Comment by ghost** [comment]
@gorootde any update on this one? You may try `:nightly` tag - but once again strategies have been deprecated.

**Comment by eivantsov** [comment]
Closed as network strategies are deprecated in 6.x.

Please give it a try with 6.x version and reopen if necessary
