### ISSUE TITLE
Remote build context in compose file fails

### ISSUE THREAD

**Issue by jgroom33** [eclipse-che/che#8568]
### Description
Remote build context of compose file fails

### Reproduction Steps
Build Stack from Recipe. Composefile:

```
services:
 dev-machine:
  build:
   context: https://github.com/eclipse/che-dockerfiles.git#master:recipes/ubuntu_jre
```

Stack Test result:
org.eclipse.che.api.promises.client.OperationException: Can not get workspace: Workspace with name 'test-wksp-mmcq' in namespace 'jgroom' doesn't exist

**OS and version:**    
Ubuntu 16.04
Linux ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
eclipse/che:6.0.0
Docker version 17.12.0-ce, build c97c6d6

**Diagnostics:** 
LOGS:
2018-02-02 02:34:39,782[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 461]    - Workspace 'jgroom/test-wksp-oali' with id 'workspacelcdzm0df7xloe4td' created by user 'jgroom'
2018-02-02 02:34:39,989[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 228]   - Starting workspace 'jgroom/test-wksp-oali' with id 'workspacelcdzm0df7xloe4td' by user 'jgroom'
2018-02-02 02:34:40,646[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 284]   - Workspace 'jgroom:test-wksp-oali' with id 'workspacelcdzm0df7xloe4td' start failed
2018-02-02 02:34:40,650[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 294]   - Error response from docker API, status: 500, message: stat /var/lib/docker/tmp/docker-build-git533109516/recipes/ubuntu_jre: no such file or directory

org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Error response from docker API, status: 500, message: stat /var/lib/docker/tmp/docker-build-git533109516/recipes/ubuntu_jre: no such file or directory

        at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.buildImage(DockerMachineStarter.java:316)
        at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.prepareImage(DockerMachineStarter.java:262)
        at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.startContainer(DockerMachineStarter.java:216)
        at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.startMachine(DockerInternalRuntime.java:298)
        at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.internalStart(DockerInternalRuntime.java:200)
        at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:109)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:265)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:29)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.infrastructure.docker.client.exception.DockerException: Error response from docker API, status: 500, message: stat /var/lib/docker/tmp/docker-build-git533109516/recipes/ubuntu_jre: no such file or directory

        at org.eclipse.che.infrastructure.docker.client.DockerConnector.getDockerException(DockerConnector.java:1518)
        at org.eclipse.che.infrastructure.docker.client.DockerConnector.buildImage(DockerConnector.java:867)
        at org.eclipse.che.infrastructure.docker.client.DockerConnector.buildImage(DockerConnector.java:804)
        at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.buildImage(DockerMachineStarter.java:314)
        ... 11 common frames omitted

**Comment by ghost** [comment]
@jgroom33 it's just documentation referencing old repo structure. 

https://github.com/eclipse/che-dockerfiles/tree/master/recipes You may pick `ubuntu_jdk8`

Here's docs PR - https://github.com/eclipse/che-docs/pull/349

**Comment by jgroom33** [comment]
Thank you.
