### ISSUE TITLE
Che server is unable to ping your workspace, RHEL7, Browser => Workspace Agent (localhost): Connection failed

### ISSUE THREAD

**Issue by bucs-fan813** [eclipse-che/che#8595]
### Description
I m connecting to an AWS RHEL7 EC2 Instance running eclipse che 5.17

I have disabled SELinux: `setenforce 0`

And have the IPTABLES and AWS Securiry groups wide open

**Command**:
`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/tmp:/data my_private_registry/eclipse/che start`

**Output**:
```
INFO: (che start): Booted and reachable
INFO: (che start): Ver: 5.17.0
INFO: (che start): Use: http://{external_ip}:8080
INFO: (che start): Use: http://{external_ip}:8080/swagger
```

**Command**:
`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/tstuser/software/docker:/data eclipse/che info --network`

**Output**:
```
INFO: ---------------------------------------
INFO: -------- CONNECTIVITY TEST --------
INFO: ---------------------------------------
INFO: (che network): eclipse/che-ip:5.17.0: {external_ip}
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent ({external_ip}): Connection succeeded
INFO: (che network): Server => Workspace Agent (External IP): Connection succeeded
INFO: (che network): Server => Workspace Agent (Internal IP): Connection succeeded
```

**Command:**
`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/data {private_registry}/eclipse/che info`

**Output**:
```
WARN: Bound '{private_registry}/eclipse/che' to '{private_registry}/eclipse/che:5.17.0'
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_wa                   rn_on_loop_devices=true` to suppress this warning.
INFO: (che cli): 5.17.0 - using docker 1.12.6 / native
WARN: (che cli): 'CHE_HOST={EXTERNAL_IP}' is != discovered IP '{ETH0_IP}'
WARN: Unable to retrieve version list from public Docker Hub for image named {private_registry}/eclipse/che.
WARN: Diagnose with 'docker run -it appropriate/curl -s https://hub.docker.com/v2/repositories/{private_registry}/eclipse/che/tags/'.
WARN: Use '--skip:network' to ignore this check.

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          {private_registry}/eclipse/che
 Version:        5.17.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /tmp
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.17.0
 CHE_HOST:       {EXTERNAL_IP}
 CHE_INSTANCE:   /tmp/instance
 CHE_CONFIG:     /tmp
 CHE_BACKUP:     /tmp/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   {ETH0_IP}
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.17.0
 IMAGE_CHE=eclipse/che-server:5.17.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.17.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.17.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.17.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.17.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.17.0
che.env:
 CHE_HOST={EXTERNAL_IP}
 CHE_DOCKER_IP={DOCKER0_IP}
 CHE_DOCKER_IP_EXTERNAL={EXTERNAL_IP}
 CHE_SINGLE_PORT=false
```
**From the CHE CLI output window when trying to launch a LAMP stack and `docker logs che`:**
```
2018-02-05 10:48:36,719[ted-scheduler-9]  [INFO ] [ockerAbandonedResourcesCleaner 126]  - List containers registered in the api: []
2018-02-05 10:48:36,727[ted-scheduler-9]  [ERROR] [o.e.c.p.d.c.DockerConnector 1417]    - Docker response doesn't contain any data, though it was expected to contain some.
2018-02-05 10:48:36,727[ted-scheduler-9]  [ERROR] [ockerAbandonedResourcesCleaner 201]  - Failed to get list of docker networks
java.io.IOException: Internal server error. Unexpected response body received from Docker.
        at org.eclipse.che.plugin.docker.client.DockerConnector.parseResponseStreamAndClose(DockerConnector.java:1419)
        at org.eclipse.che.plugin.docker.client.DockerConnector.getNetworks(DockerConnector.java:1225)
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.cleanNetworks(DockerAbandonedResourcesCleaner.java:180)
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.run(DockerAbandonedResourcesCleaner.java:93)
        at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:45)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-02-05 12:40:14,024[nio-8080-exec-4]  [INFO ] [o.e.c.a.f.s.jpa.JpaFactoryDao 111]   - FactoryDao#getByAttributes #maxItems: 15 #skipCount: 0, #attributes: [{first=creator.userId, second=che}]
2018-02-05 12:40:21,120[aceSharedPool-3]  [WARN ] [.e.c.p.d.m.MachineProviderImpl 564]  - Failed to check image eclipse/php availability. Cause: Error response from docker API, status: 500, message: Invalid filter 'reference'
2018-02-05 12:40:22,608[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspaceqg6flza7ifnxy2l9
2018-02-05 12:40:24,791[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspaceqg6flza7ifnxy2l9
2018-02-05 12:40:26,942[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspaceqg6flza7ifnxy2l9
```

and

`Could not start workspace lamp_stack_test. Reason: Start of environment 'default' failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.`

### Reproduction Steps
**AWS Security Groups**
![sg_inbound](https://user-images.githubusercontent.com/7397288/36265067-65106b78-123c-11e8-9d87-c93b4721d9dd.PNG)
![sg_outbound](https://user-images.githubusercontent.com/7397288/36265068-65414054-123c-11e8-839c-3cd98d5b3dcf.PNG)

**OS and version:**    
RHEL7.7 (Maipo)
**Diagnostics:** 

Coming Soon

### Referenced
#4021
#4034
#3849
#6243 
#2030
#8290
#3736
#973
#1272
#1226

**Comment by ghost** [comment]
@bucs-fan813 can you confirm the ephemeral port range isn't filtered?

You may want to give it a go with `--fast` flag so that CLI skips pre and postflight checks. Then, when you start a workspace, open browser console and take a look at failed requests.

**Comment by bucs-fan813** [comment]
I have tried the `--fast` flag for several commands. Starting CHE is no longer a problem, starting a workspace within CHE is now the issue. I am almost certain CHE is trying to pull docker images from get.docker.com.
When I run `grep -R docker.com /var/lib/docker/*` I get several entries from config.v2.json files, devicemapper/imagedb/content/sha256/{HASH} that contain:
`DOCKER_BUCKET=get.docker.com` or `ENV DOCKER_BUCKET=get.docker.com`

I've tried adding the following to my /etc/hosts file but it has not worked yet:
`x.x.x.x docker.com get.docker.com`

**Comment by eivantsov** [comment]
@bucs-fan813 Che pulls images from DockerHub.

What is the exact issue?

**Comment by carloreggiani** [comment]
I'm exactly in the same situation, both on a linux server in my LAN (all network open) and a linux server on Azure (multiuser config).

Tryed also to set CHE_DOCKER_IP_EXTERNAL parameter with the same CHE_HOST.

Not easy to understand where is the problem!

Thanks for any support

Carlo

**Comment by eivantsov** [comment]
@carloreggiani if Che server is unable to reach a workspace agent, it means that the ephemeral port range is filtered. What is your CHE_HOST? A public Azure IP?

**Comment by carloreggiani** [comment]
ARGHHH the problem was our proxy configured in the browser! 
Now is working fine for the internal LAN server.

For Azure we have a site2site VPN:  I'll check our VPN configuration with my network admins.

Thanks!

Carlo
