### ISSUE TITLE
Unexpected fail of CheckBasicFunctionalityInCommandsExplorerTest selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8689]
### Description
We have unexpected fail of CheckBasicFunctionalityInCommandsExplorerTest selenium test. It looks like something went wrong with run of intelligence command. We need to investigate and resolve this problem.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //div[@id='gwt-debug-editorPartStack-contentPanel']//div[@active]//div[@class='textviewContent' and @contenteditable='true']' (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.intelligencecommand.CheckBasicFunctionalityInCommandsExplorerTest.commandsBuilder(CheckBasicFunctionalityInCommandsExplorerTest.java:106)
	at org.eclipse.che.selenium.intelligencecommand.CheckBasicFunctionalityInCommandsExplorerTest.shouldCreateDifferentTypesCommandsInDifferentGoals(CheckBasicFunctionalityInCommandsExplorerTest.java:61)
```

**Screenshot:**

![ddd](https://user-images.githubusercontent.com/22724619/36023153-2bdff4ce-0d94-11e8-9ced-cfef9d4775b1.png)

**Report with reproduced problem:**

https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/112/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8692
