### ISSUE TITLE
Unexpected fail of ShowHintsCommandTest selenium test

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8770]
### Description
We have unexpected fail of ShowHintsCommandTest selenium test. It looks like something went wrong with method which checks that error marker is present. We need to investigate and resolve this problem.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.xpath: //div[@class='ruler overview']/div[@class='annotationOverview error'] (tried for 20 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.editor.autocomplete.ShowHintsCommandTest.waitErrorMarkerInPosition(ShowHintsCommandTest.java:130)
	at org.eclipse.che.selenium.editor.autocomplete.ShowHintsCommandTest.checkShowHintsCommand(ShowHintsCommandTest.java:89)
```

**Screenshot:**

![ggggg](https://user-images.githubusercontent.com/22724619/36204202-f7217336-1192-11e8-842b-c5bc3108bde3.png)

**Report with reproduced problem:**

https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/117/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8772
