### ISSUE TITLE
Question: What's the Che server equivalent for 6.x ?

### ISSUE THREAD

**Issue by mikarinneoracle** [eclipse-che/che#8771]
### Description
Hi,
on Oracle cloud container classic we can run eClipse Che 5.x using the following YAML:
version: 2
services:
  che:
    image: 'eclipse/che-server:5.21.0'
    command: start
    ports:
      - '80:8080/tcp'
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp:/data'
    environment:
      - 'CHE_IP={{hostip_for_interface .HostIPs "public_ip"}}'
      - 'occs:availability=per-pool'
      - 'occs:scheduler=random'

Is there an equivalent for 6.x yet ? I.e. Che server and it's config params ?

### Reproduction Steps
**OS and version:**    
**Diagnostics:**

**Comment by eivantsov** [comment]
`eclipse/che-server:${CHE_6_TAG}`
`CHE_HOST` instead of `CHE_IP`

**Comment by mikarinneoracle** [comment]
Otherwise good but cannot launch terminal.

Log:
2018-02-20T08:56:38.450030831Z 2018-02-20 08:56:38,449[ost-startStop-1]  [WARN ] [.c.i.d.c.DockerRegistryChecker 58]   - Docker registry http://localhost:5000 is not available, which means that you won't be able to save snapshots of your workspaces.
2018-02-20T08:56:38.450047998Z How to configure registry?
2018-02-20T08:56:38.450052021Z 	Local registry  -> https://docs.docker.com/registry/
2018-02-20T08:56:38.450068616Z 	Remote registry -> set up 'che.docker.registry.auth.*' properties
2018-02-20T08:56:38.459380459Z 2018-02-20 08:56:38,458[ted-scheduler-1]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
2018-02-20T08:56:38.469467408Z 2018-02-20 08:56:38,469[ted-scheduler-1]  [ERROR] [o.e.c.i.d.c.DockerConnector 1498]    - Docker response doesn't contain any data, though it was expected to contain some.
2018-02-20T08:56:38.477323338Z 2018-02-20 08:56:38,476[ted-scheduler-1]  [ERROR] [ockerAbandonedResourcesCleaner 200]  - Failed to get list of docker networks
2018-02-20T08:56:38.477339598Z java.io.IOException: Internal server error. Unexpected response body received from Docker.
2018-02-20T08:56:38.477343564Z 	at org.eclipse.che.infrastructure.docker.client.DockerConnector.parseResponseStreamAndClose(DockerConnector.java:1500)
2018-02-20T08:56:38.477349995Z 	at org.eclipse.che.infrastructure.docker.client.DockerConnector.getNetworks(DockerConnector.java:1238)
2018-02-20T08:56:38.477354044Z 	at org.eclipse.che.workspace.infrastructure.docker.monit.DockerAbandonedResourcesCleaner.cleanNetworks(DockerAbandonedResourcesCleaner.java:179)
2018-02-20T08:56:38.477357607Z 	at org.eclipse.che.workspace.infrastructure.docker.monit.DockerAbandonedResourcesCleaner.run(DockerAbandonedResourcesCleaner.java:85)
2018-02-20T08:56:38.477360590Z 	at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:45)
2018-02-20T08:56:38.477363751Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-02-20T08:56:38.477366633Z 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2018-02-20T08:56:38.477369430Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2018-02-20T08:56:38.477372421Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2018-02-20T08:56:38.477375259Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2018-02-20T08:56:38.477378008Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2018-02-20T08:56:38.477382106Z 	at java.lang.Thread.run(Thread.java:748)
2018-02-20T08:56:38.769971377Z 2018-02-20 08:56:38,769[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [5,974] ms
2018-02-20T08:56:38.770743045Z 2018-02-20 08:56:38,770[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/dashboard.war]
2018-02-20T08:56:39.073316943Z 2018-02-20 08:56:39,072[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/dashboard.war] has finished in [302] ms
2018-02-20T08:56:39.074989088Z 2018-02-20 08:56:39,074[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war]
2018-02-20T08:56:39.323201236Z 2018-02-20 08:56:39,322[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war] has finished in [248] ms
2018-02-20T08:56:39.325241513Z 2018-02-20 08:56:39,324[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
2018-02-20T08:56:39.408012806Z 2018-02-20 08:56:39,407[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war] has finished in [83] ms
2018-02-20T08:56:39.412781879Z 2018-02-20 08:56:39,412[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-8080"]
2018-02-20T08:56:39.429892207Z 2018-02-20 08:56:39,429[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 8399 ms
2018-02-20T08:57:16.806326913Z 2018-02-20 08:57:16,805[nio-8080-exec-4]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 461]    - Workspace 'che/wksp-mcac' with id 'workspacejxlb98qiy9tvdwsr' created by user 'che'
2018-02-20T08:57:31.466527204Z 2018-02-20 08:57:31,465[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 228]   - Starting workspace 'che/wksp-mcac' with id 'workspacejxlb98qiy9tvdwsr' by user 'che'
2018-02-20T08:57:31.618809051Z 2018-02-20 08:57:31,618[aceSharedPool-0]  [WARN ] [e.c.w.i.d.DockerMachineStarter 384]  - Failed to check image eclipse/ubuntu_jdk8 availability. Cause: Error response from docker API, status: 500, message: Invalid filter 'reference'
2018-02-20T08:57:31.618838994Z 
2018-02-20T08:57:31.618845983Z org.eclipse.che.infrastructure.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Invalid filter 'reference'
2018-02-20T08:57:31.618852371Z 
2018-02-20T08:57:31.618858034Z 	at org.eclipse.che.infrastructure.docker.client.DockerConnector.getDockerException(DockerConnector.java:1518)
2018-02-20T08:57:31.618864195Z 	at org.eclipse.che.infrastructure.docker.client.DockerConnector.listImages(DockerConnector.java:239)
2018-02-20T08:57:31.618872053Z 	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.isDockerImageExistLocally(DockerMachineStarter.java:379)
2018-02-20T08:57:31.618879861Z 	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.pullImage(DockerMachineStarter.java:352)
2018-02-20T08:57:31.618885958Z 	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.prepareImage(DockerMachineStarter.java:264)
2018-02-20T08:57:31.618891812Z 	at org.eclipse.che.workspace.infrastructure.docker.DockerMachineStarter.startContainer(DockerMachineStarter.java:216)
2018-02-20T08:57:31.618897696Z 	at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.startMachine(DockerInternalRuntime.java:297)
2018-02-20T08:57:31.618903442Z 	at org.eclipse.che.workspace.infrastructure.docker.DockerInternalRuntime.internalStart(DockerInternalRuntime.java:199)
2018-02-20T08:57:31.618909166Z 	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:109)
2018-02-20T08:57:31.618914628Z 	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:265)
2018-02-20T08:57:31.618928012Z 	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:37)
2018-02-20T08:57:31.618934500Z 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
2018-02-20T08:57:31.618940328Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2018-02-20T08:57:31.618945801Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2018-02-20T08:57:31.618951259Z 	at java.lang.Thread.run(Thread.java:748)
2018-02-20T08:58:20.597997310Z 2018-02-20 08:58:20,597[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 268]   - Workspace 'che:wksp-mcac' with id 'workspacejxlb98qiy9tvdwsr' started by user 'che'

**Comment by eivantsov** [comment]
What's your Docker version?

**Comment by mikarinneoracle** [comment]
v1.12.6 on Oracle Linux 6

**Comment by eivantsov** [comment]
@mikarinneoracle any chance to upgrade Docker? This is a know issue and Che 6 officially supports Docker 17+

**Comment by mikarinneoracle** [comment]
Ok, thanks. At the moment no but 5.x works fine.
