### ISSUE TITLE
[REGRESSION] Error/Warning markers are not displayed in the editor

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8812]
### Reproduction steps:
1) Run default java stack with default spring project
2) Open "GreetingController" java class
3) Do any changes which should be marked by error markers
4) Pay attention to the screen

**Screenshot:**

![fdfdgfdg](https://user-images.githubusercontent.com/22724619/36298187-80b687fe-12ff-11e8-882b-24fda4820db5.png)

There was problem with web socket:
```
2018/02/16 08:13:36 Start new terminal.
2018/02/16 08:13:39 Failed to send websocket message: , due to occurred error websocket: close sent
2018/02/16 08:13:39 Error occurs on sending ping message to websocket. websocket: close sent
```

**OS and version:**    
Che 6.2.0 ; Chrome 63.0 ; Fedora 25

**Comment by dmytro-ndp** [comment]
There was no token in WebSocket URL in Che: `ws://172.19.20.13:32802/wsagent?token=`
It might be caused by commit https://github.com/eclipse/che/commit/48d516cad50ac3b1f908f6d4067a329c41937dea

**Comment by dmytro-ndp** [comment]
It seems [my comment above](https://github.com/eclipse/che/issues/8812#issuecomment-366174057) was wrong and the problem was with handling change editor content requests:
```java
2018-02-16 10:50:08,162[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: null
java.lang.StringIndexOutOfBoundsException: null
	at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:760)
	at java.lang.StringBuilder.delete(StringBuilder.java:244)
	at org.eclipse.che.api.editor.server.impl.EditorWorkingCopy.applyChanges(EditorWorkingCopy.java:138)
	at org.eclipse.che.api.editor.server.impl.EditorWorkingCopyManager.onEditorContentUpdated(EditorWorkingCopyManager.java:114)
	at org.eclipse.che.api.editor.server.impl.EditorChangesTracker.lambda$configureHandler$0(EditorChangesTracker.java:43)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
![screenshot from 2018-02-16 12-55-04](https://user-images.githubusercontent.com/1197777/36304723-5a241178-1319-11e8-9670-886e2bbbdb21.png)

**Comment by sunix** [comment]
@vparfonov could you reapply https://github.com/eclipse/che/commit/523b823dc991e6b7d4b955f61f29adf4c86923ad ? i don't see how this is related to this issue

**Comment by vparfonov** [comment]
@sunix But related some how, you can easy check it. Try to open any Java class and try to use codeassistant.

**Comment by sunix** [comment]
@vparfonov whatever java class codeassistant is broken, shouldn't it be fixed in Java class codeassistant ? couldn't we investigate what was really wrong ?
