### ISSUE TITLE
Unexpected fail of selenium tests from organization package

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8828]
### Description
We have unexpected fail of selenium tests from **organization** package. The tests fail when trying     
 to get a number of organizations. We need investigate and resolve this problem.

**Failed tests:** selenium test from org.eclipse.che.selenium.dashboard.organization package.

**Log:**
```
java.lang.NullPointerException
	at org.eclipse.che.selenium.dashboard.organization.DeleteOrganizationByBulkTest.setUp(DeleteOrganizationByBulkTest.java:59)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/122/Selenium_tests_report/

**Screenshot:**
![org eclipse che selenium dashboard organization deleteorganizationinlisttest testorganizationdeletionfromlist_as4nwllf](https://user-images.githubusercontent.com/7760565/36368639-e1498496-1560-11e8-95e7-124b1f0f48f6.png)

**Comment by dmytro-ndp** [comment]
FYI: stack trace:
```java
java.lang.NullPointerException
	at org.eclipse.che.selenium.core.client.TestOrganizationServiceClient.lambda$getAll$0(TestOrganizationServiceClient.java:56)
	at java.util.Collection.removeIf(Collection.java:414)
	at org.eclipse.che.selenium.core.client.TestOrganizationServiceClient.getAll(TestOrganizationServiceClient.java:56)
	at org.eclipse.che.selenium.core.client.TestOrganizationServiceClient.getAllRoot(TestOrganizationServiceClient.java:49)
	at org.eclipse.che.selenium.dashboard.organization.DeleteOrganizationByBulkTest.setUp(DeleteOrganizationByBulkTest.java:59)
```

**Comment by dmytro-ndp** [comment]
According to the log file, the only one test passed from those which **TestOrganizationServiceClient.getAllRoot()** are using - org.eclipse.che.selenium.dashboard.organization.CreateOrganizationTest

**Comment by SkorikSergey** [comment]
Fixed.
