### ISSUE TITLE
Need to improve logging of errors when user trying to make pull request to the same branch on github

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#886]
I'm getting next errors on my mail because logback set to send all logs with levell ERROR to my mail:
`2016-03-26 22:29:11,157[o-8080-exec-114]  [ERROR] [o.e.c.i.e.g.s.r.GitHubService 239]   - Creating  pull request fail
java.io.IOException: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between master and master"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
        at org.kohsuke.github.Requester.handleApiError(Requester.java:496) ~[github-api-1.67.jar:na]
        at org.kohsuke.github.Requester._to(Requester.java:245) ~[github-api-1.67.jar:na]
        at org.kohsuke.github.Requester.to(Requester.java:191) ~[github-api-1.67.jar:na]
        at org.kohsuke.github.GHRepository.createPullRequest(GHRepository.java:590) ~[github-api-1.67.jar:na]
        at org.eclipse.che.ide.ext.github.server.rest.GitHubService.createPullRequest(GitHubService.java:235) ~[che-plugin-github-ext-github-3.14.1.jar:3.14.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:154) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:141) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:289) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:280) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:205) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:95) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:64) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:134) [everrest-core-1.12.0.jar:na]
        at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:63) [everrest-core-1.12.0.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.0.jar:na]
        at com.codenvy.workspace.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:59) [codenvy-hosted-workspace-events-3.14.1.jar:3.14.1]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.0.jar:na]
        at com.codenvy.auth.sso.client.TemporaryTenantSharingFilter.doFilter(TemporaryTenantSharingFilter.java:136) [cloud-ide-filters-3.14.1.1.jar:3.14.1]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.0.jar:na]
        at com.codenvy.auth.sso.client.DefaultTokenHandler.handleValidToken(DefaultTokenHandler.java:68) [codenvy-hosted-sso-client-3.14.1.jar:3.14.1]
        at com.codenvy.auth.sso.client.LoginFilter.doFilter(LoginFilter.java:129) [codenvy-hosted-sso-client-3.14.1.jar:3.14.1]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [guice-servlet-4.0.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [guice-servlet-4.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.21]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.21]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.21]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.21]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.21]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.21]
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.21]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.21]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.21]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.21]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-coyote.jar:8.0.21]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.21]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517) [tomcat-coyote.jar:8.0.21]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474) [tomcat-coyote.jar:8.0.21]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.21]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/hspaans/hercules/pulls
        at sun.reflect.GeneratedConstructorAccessor76.newInstance(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884) ~[na:1.8.0_45]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_45]
        at org.kohsuke.github.Requester.parse(Requester.java:451) ~[github-api-1.67.jar:na]
        at org.kohsuke.github.Requester._to(Requester.java:224) ~[github-api-1.67.jar:na]
        ... 53 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/hspaans/hercules/pulls
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_45]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_45]
        at org.kohsuke.github.Requester.parse(Requester.java:447) ~[github-api-1.67.jar:na]
        ... 54 common frames omitted` 

It shouldn't have level of ERROR.
Also we need to display info about this to user, probably with good explanation.

**Comment by ddementieva** [comment]
(Comment by Sergii Kabashniuk)

Easy to do. Will take to the next sprint
