### ISSUE TITLE
Cannot launch jdt.ls as sidecar

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#8874]
Current implementation (branch #5730_java_ls_poc) implies that an installer has to be switched on. There's no way to test jdt.ls as a sidecar.

```
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.updateWorkspace(JavaLanguageServerExtensionService.java:657)
java.lang.IllegalStateException: org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.doGetOne(JavaLanguageServerExtensionService.java:749)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.lambda$getOrInitLanguageServer$2(JavaLanguageServerExtensionService.java:779)
Caused by: org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
	at org.eclipse.che.plugin.java.languageserver.WorkspaceSynchronizer.lambda$syncronizerWorkspaceAsync$0(WorkspaceSynchronizer.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.executeCommand(JavaLanguageServerExtensionService.java:762)
	at java.lang.Thread.run(Thread.java:748)
2018-02-22 09:19:56,475[kspaceUpdater-0]  [ERROR] [LanguageServerExtensionService 664]  - org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 8 common frames omitted
2018-02-22 09:19:56,492[kspaceUpdater-0]  [ERROR] [.c.p.j.l.WorkspaceSynchronizer 58]   - Workspace updated. Result code: '1', message: 'org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.'. Added projects: '[file:///projects/greeter]', removed projects: '[]'
2018-02-22 09:19:56,521[kspaceUpdater-0]  [INFO ] [l.r.LanguageServerRegistryImpl 175]  - required to launch for thread 35: []
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.executeCommand(JavaLanguageServerExtensionService.java:760)
2018-02-22 09:19:56,533[kspaceUpdater-0]  [INFO ] [l.r.LanguageServerRegistryImpl 175]  - required to launch for thread 35: []
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.eclipse.che.plugin.java.languageserver.WorkspaceSynchronizer.lambda$syncronizerWorkspaceAsync$0(WorkspaceSynchronizer.java:54)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.executeCommand(JavaLanguageServerExtensionService.java:762)
java.lang.IllegalStateException: org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
2018-02-22 09:19:56,541[kspaceUpdater-0]  [ERROR] [LanguageServerExtensionService 664]  - org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.getOrInitLanguageServer(JavaLanguageServerExtensionService.java:777)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.executeCommand(JavaLanguageServerExtensionService.java:760)
Caused by: org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.lambda$getOrInitLanguageServer$2(JavaLanguageServerExtensionService.java:779)
	... 8 common frames omitted
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.getOrInitLanguageServer(JavaLanguageServerExtensionService.java:777)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.doGetOne(JavaLanguageServerExtensionService.java:749)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.executeCommand(JavaLanguageServerExtensionService.java:762)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.updateWorkspace(JavaLanguageServerExtensionService.java:657)
2018-02-22 09:19:56,577[kspaceUpdater-0]  [ERROR] [LanguageServerExtensionService 664]  - org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
2018-02-22 09:19:56,576[kspaceUpdater-0]  [INFO ] [l.r.LanguageServerRegistryImpl 175]  - required to launch for thread 35: []
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.lang.IllegalStateException: org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.updateWorkspace(JavaLanguageServerExtensionService.java:657)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.doGetOne(JavaLanguageServerExtensionService.java:749)
2018-02-22 09:19:56,556[kspaceUpdater-0]  [INFO ] [l.r.LanguageServerRegistryImpl 175]  - required to launch for thread 35: []
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.getOrInitLanguageServer(JavaLanguageServerExtensionService.java:777)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at org.eclipse.che.plugin.java.languageserver.WorkspaceSynchronizer.lambda$syncronizerWorkspaceAsync$0(WorkspaceSynchronizer.java:54)
Caused by: org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.
2018-02-22 09:19:56,586[kspaceUpdater-0]  [INFO ] [l.r.LanguageServerRegistryImpl 175]  - required to launch for thread 35: []
2018-02-22 09:19:56,577[kspaceUpdater-0]  [ERROR] [.c.p.j.l.WorkspaceSynchronizer 58]   - Workspace updated. Result code: '1', message: 'org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.'. Added projects: '[file:///projects/spring]', removed projects: '[]'
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.lambda$getOrInitLanguageServer$2(JavaLanguageServerExtensionService.java:779)
	... 8 common frames omitted
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.executeCommand(JavaLanguageServerExtensionService.java:760)
	at java.util.Optional.orElseThrow(Optional.java:290)
2018-02-22 09:19:56,543[kspaceUpdater-0]  [ERROR] [.c.p.j.l.WorkspaceSynchronizer 58]   - Workspace updated. Result code: '1', message: 'org.eclipse.che.api.languageserver.exception.LanguageServerException: Unexpected error. Language server not found after initialization.'. Added projects: '[file:///projects/spring]', removed projects: '[]'
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tsmaeder** [comment]
Why is this a p1 bug?

**Comment by eivantsov** [comment]
I meant P2, sorry.

But definitely a bug.

**Comment by tsmaeder** [comment]
Could you expand a bit what you were trying to do to get the above stack trace? I'm aware that we don't have a sidecar jdt.ls yet, but I don't have the context otherwise.

**Comment by eivantsov** [comment]
I created a workspace without jdt.ls installer and this produced the above error.

What am I trying to achieve? Run jdt.ls as a sidecar in a Che workspace.

**Comment by tsmaeder** [comment]
There is documentation on how to add a LS as a sidecar here: https://www.eclipse.org/che/docs/6/che/docs/language-servers.html#ls-sidecars
I think there are two parts to this task:
1. Build and publish a docker image of che-ls-jdt as part of the build process
2. Update the java launcher to connect to the sidecar instead of launching jdt.ls itself
It would be nice to have some way to set the memory limits on jdt.ls per workspace.

**Comment by eivantsov** [comment]
@JPinkney it's `eivantsov/jdtls`

language server starts in CMD via socat there. I can connect to this LS using a local client, when the language server runs in a Docker container.

**Comment by tsmaeder** [comment]
There are a couple of things to heed here:
1. We have extra wrapping code around the LanguageServer instance we create for jdt.ls. So we can't do the "instantiation by configuration". The idea instead is to refactor SocketLanguageServerLauncher so that JavaLanguageServerLauncher can derive from it. Server url will be read from machine configuration.
2. ~/.m2 and ~/che/ls-java/data need are used to store state between runs and need to be added as volumes in workpace configs where we use jdt.ls
