### ISSUE TITLE
Study possible ways to replicate HTTP sessions (Tomcat based)

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#8923]
### Description
To enable parallel run of several master instances we need to synchonize state of the HTTP sessions to avoid unstable behavior.

Docs:
[1] https://tomcat.apache.org/tomcat-8.0-doc/cluster-howto.html

**Comment by mshaposhnik** [comment]
The following error appears when Tomcat tries to send session state:
```

2018-02-23 14:40:45,865[nio-8080-exec-4]  [ERROR] [.a.c.t.t.AbstractReplicatedMap 477]  - Unable to diff object. Will replicate the entire object instead.
--
  | java.io.NotSerializableException: org.eclipse.che.multiuser.api.permission.server.PermissionCheckerImpl
  | at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
  | at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
  | at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
  | at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
  | at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
  | at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
  | at org.apache.catalina.ha.session.DeltaRequest$AttributeInfo.writeExternal(DeltaRequest.java:401)
  | at org.apache.catalina.ha.session.DeltaRequest.writeExternal(DeltaRequest.java:294)
  | at org.apache.catalina.ha.session.DeltaRequest.serialize(DeltaRequest.java:308)
  | at org.apache.catalina.ha.session.DeltaSession.getDiff(DeltaSession.java:138)
  | at org.apache.catalina.tribes.tipis.AbstractReplicatedMap.replicate(AbstractReplicatedMap.java:472)
  | at org.apache.catalina.ha.session.BackupManager.requestCompleted(BackupManager.java:98)
  | at org.apache.catalina.ha.tcp.ReplicationValve.send(ReplicationValve.java:523)
  | at org.apache.catalina.ha.tcp.ReplicationValve.sendMessage(ReplicationValve.java:511)
  | at org.apache.catalina.ha.tcp.ReplicationValve.sendSessionReplicationMessage(ReplicationValve.java:493)
  | at org.apache.catalina.ha.tcp.ReplicationValve.sendReplicationMessage(ReplicationValve.java:404)
  | at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:333)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by skabashnyuk** [comment]
we want to avoid http session replication.
