### ISSUE TITLE
Make it possible to build Eclipse Che on CI qa-experimental jobs

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9021]
### Description
We have CI jobs https://ci.codenvycorp.com/view/qa-experimental/ to conduct investigation on unstable selenium tests of _Eclipse Che_ and so on. But there is impossible to build _Eclipse Che_ itself to run tests on it:
```
16:47:12 [INFO] ------ (linux_arm5) org.codehaus.mojo:exec-maven-plugin:1.6.0:exec
16:47:12 go: cannot find GOROOT directory: /usr/local/go
16:47:12 [ERROR] Command execution failed.
16:47:12 org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
16:47:12     at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
16:47:12     at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
16:47:12     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
16:47:12     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
16:47:12     at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
16:47:12     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
16:47:12     at com.soebes.maven.plugins.iterator.IteratorMojo.executeMojo(IteratorMojo.java:406)
16:47:12     at com.soebes.maven.plugins.iterator.IteratorMojo.handlePluginExecution(IteratorMojo.java:305)
16:47:12     at com.soebes.maven.plugins.iterator.IteratorMojo.execute(IteratorMojo.java:235)
16:47:12     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
16:47:12     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
16:47:12     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
16:47:12     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
16:47:12     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
16:47:12     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
16:47:12     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
16:47:12     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
16:47:12     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
16:47:12     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
16:47:12     at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
16:47:12     at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
16:47:12     at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
16:47:12     at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
16:47:12     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:47:12     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:47:12     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:47:12     at java.lang.reflect.Method.invoke(Method.java:498)
16:47:12     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
16:47:12     at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
16:47:12     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
16:47:12     at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by riuvshin** [comment]
Done
