### ISSUE TITLE
Unexpected fail of RenameWorkspaceTest selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#9086]
### Description
We have unexpected fail of **RenameWorkspaceTest** selenium test. The test fails while checking that workspace name is valid after renaming.  We should clarify reason and fix it.

**Log:**
```
java.lang.AssertionError: expected [false] but found [true]
	at org.eclipse.che.selenium.dashboard.RenameWorkspaceTest.renameWorkspace(RenameWorkspaceTest.java:97)
	at org.eclipse.che.selenium.dashboard.RenameWorkspaceTest.renameNameWorkspaceTest(RenameWorkspaceTest.java:89)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/145/Selenium_tests_report/

**Comment by SkorikSergey** [comment]
Done https://github.com/eclipse/che/pull/9087.
