### ISSUE TITLE
Sometimes rebuild Theia with plugins applied by env THEIA_PLUGINS fails

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#9095]
### Description
Sometimes rebuild Theia with plugins applied by env THEIA_PLUGINS fails:
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning @theia/typescript > @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@theia/extension-manager > @theia/application-package > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[4/4] Building fresh packages...
[6/7] ⠐ find-git-repositories: CXX(target) Release/obj.target/findGitRepos/src/FindGitRepos.o
[2/7] ⠐ electron
[3/7] ⠐ node-pty:    ^~~~
[4/7] ⠐ nsfw:    ^~~~
error /home/user/default/theia/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 

More: 
yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: /home/theia/node_modules/vscode-ripgrep: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c node ./lib/postinstall.js
  Directory: /home/theia/node_modules/vscode-ripgrep
  Output:
  Downloading ripgrep failed: Error: Request failed with code 401
      at ProcessTermError.MessageError (/opt/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/opt/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/opt/yarn/lib/cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Socket.stream.socket.on (internal/child_process.js:346:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:567:12)

**Comment by AndrienkoAleksandr** [comment]
Seems can be fixed by https://github.com/eclipse/che/issues/9095 need more deep check.

**Comment by eivantsov** [comment]
@AndrienkoAleksandr can you verify that GITHUB_TOKEN env is there in your Theia container?

**Comment by mmorhun** [comment]
The problem with vscode-ripgrep downloading ban still remains. But it cannot be fixed on Che side.
