### ISSUE TITLE
Unexpected fail of TransitiveDependencyTest in the selenium tests

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9258]
### Description
We have unexpected fail of TransitiveDependencyTest in the selenium tests, it looks like something went wrong with a method which checks dependency present. We need to investigate and fix this problem.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for visibility of element located by By.xpath: //div[@path='/TransitiveDependencyTest3']/div (tried for 120 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.eclipse.che.selenium.projectexplorer.dependencies.TransitiveDependencyTest.transitiveDependencyTest(TransitiveDependencyTest.java:67)
Caused by: org.openqa.selenium.NoSuchElementException: 
no such element: Unable to locate element: {"method":"xpath","selector":"//div[@path='/TransitiveDependencyTest3']/div"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.16.1.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 17 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: '850ee14b5bf0', ip: '172.24.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.5lrLia}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: f32a984baa6f2f4130646714811d03ef
*** Element info: {Using=xpath, value=//div[@path='/TransitiveDependencyTest3']/div}
Command duration or timeout: 453 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=true, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.5lrLia}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=true, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=c94443a5-4a25-4c63-8341-4b2681adcead, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: c94443a5-4a25-4c63-8341-4b2681adcead
*** Element info: {Using=xpath, value=//div[@path='/TransitiveDependencyTest3']/div}
	at org.eclipse.che.selenium.projectexplorer.dependencies.TransitiveDependencyTest.transitiveDependencyTest(TransitiveDependencyTest.java:67)
Caused by: org.openqa.selenium.remote.ScreenshotException: 
Screen shot has been taken
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: SeleniumWebDriver
	at org.eclipse.che.selenium.projectexplorer.dependencies.TransitiveDependencyTest.transitiveDependencyTest(TransitiveDependencyTest.java:67)
```

**Report with reproduced problem:**

https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/92/Selenium_tests_report/

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/9261
