### ISSUE TITLE
Recipe type compose: external registry not honored

### ISSUE THREAD

**Issue by jgroom33** [eclipse-che/che#9348]
### Description
Private docker repository is not being accessed.
User is configured for Administration access to private registry

### Reproduction Steps
Configure user for private registry access (Administration)
Create factory that requires pull from registry
launch workspace
Workspace fails to launch with:  unauthorized: The client does not have permission for manifest

**OS and version:**    
Ubuntu 16.04
Che 6.3 (upgraded from 6.1)

**Diagnostics:** 
<details>
2018-04-05 18:46:44,897[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 294]   - Can't create machine from image. Cause: Error response from docker API, status: 500, message: unauthorized: The client does not have permission for manifest

org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Can't create machine from image. Cause: Error response from docker API, status: 500, message: unauthorized: The client does not have permission for manifest

        at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.pullImage(ParallelDockerImagesBuilder.java:285)
        at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.prepareImage(ParallelDockerImagesBuilder.java:178)
        at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.lambda$null$0(ParallelDockerImagesBuilder.java:126)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.infrastructure.docker.client.exception.DockerException: Error response from docker API, status: 500, message: unauthorized: The client does not have permission for manifest

        at org.eclipse.che.infrastructure.docker.client.DockerConnector.getDockerException(DockerConnector.java:1518)
        at org.eclipse.che.infrastructure.docker.client.DockerConnector.pull(DockerConnector.java:1121)
        at org.eclipse.che.infrastructure.docker.client.DockerConnector.pull(DockerConnector.java:1094)
        at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.pullImage(ParallelDockerImagesBuilder.java:273)
        ... 6 common frames omitted
</details>

**Comment by eivantsov** [comment]
@jgroom33 does it help if you set `-e CHE_DOCKER_ALWAYS__PULL__IMAGE` to `false`?

**Comment by jgroom33** [comment]
@eivantsov I've seen the following behavior regarding CHE_DOCKER_ALWAYS__PULL__IMAGE:
1. start che with false
2. modify to true
3. change has no impact

1. start che with true (default)
2. modify to false
3. change has no impact
4. upgrade che
5. Administration settings no longer honored

**Comment by jgroom33** [comment]
I've tried both methods of registry config:

Using Administration setting (this method worked while the environment was on 6.1)

Setting config params to use AUTH.  I've not been able to get this method to function (presumed because we're using artifactory which appears to require reverse proxy)

**Comment by eivantsov** [comment]
```
2018-04-06 13:32:03,315[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 293]   - Can't create machine from image. Cause: Error response from docker API, status: 404, message: pull access denied for eivantsov/private24, repository does not exist or may require 'docker login'

org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Can't create machine from image. Cause: Error response from docker API, status: 404, message: pull access denied for eivantsov/private24, repository does not exist or may require 'docker login'
```
A bit different error...

**Comment by jgroom33** [comment]
I saw that error directly after the upgrade.  I tried deleting/re-adding the registry auth in Administration and did not see the error again.  (though it may be because I also have modified CHE_DOCKER_ALWAYS__PULL__IMAGE to false)

**Comment by eivantsov** [comment]
This is how DockerHub worked for me. Give it a try with editing che.env and restarting
```
CHE_DOCKER_REGISTRY_AUTH_dockerhub_URL=https://index.docker.io/v1/
CHE_DOCKER_REGISTRY_AUTH_dockerhub_USERNAME=xxx
CHE_DOCKER_REGISTRY_AUTH_dockerhub_PASSWORD=xxx
```

**Comment by jgroom33** [comment]
What is the goal of the suggested modification? The current behavior allows pulling from public registries. Does the above registry have private images?

**Comment by eivantsov** [comment]
Docker Hub? Yes, you can have 1 private registry for free

**Comment by jgroom33** [comment]
I narrowed the problem down to using a compose in the factory.  Private images in a compose recipe do not pull
 
```json
        "recipe": {
          "type": "compose",
          "content": "services:\n dev-machine:\n  image: 'private/image:latest'\n",
          "contentType": "application/x-yaml"
        }
```

**Comment by doreplado** [comment]
Was there any workaround for this or can you just not use compose based recipes at this point?

**Comment by jgroom33** [comment]
Don't use compose recipes

**Comment by doreplado** [comment]
I was able to work around this by editing /home/user/eclipse-che/tomcat/webapps/api/WEB-INF/classes/che/che.properties in the Che container. 

For whatever reason, when using the docker install, modifying the che.env doesn't interpolate the values into the application classes properties.
