### ISSUE TITLE
Plugin deployment error

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#9425]
### Description
I create plugin ws by following this guide https://www.eclipse.org/che/docs/che-in-che-quickstart.html. But I take contantly errors and never run plugin ws.

### Reproduction Steps
Follow the instructions in https://www.eclipse.org/che/docs/che-in-che-quickstart.html

**OS and version:**    
Single and multi user che using boot2docker in both Macos 
and Ubuntu 16.04 

**Diagnostics:** 
![screen shot 2018-04-13 at 3 48 31 pm](https://user-images.githubusercontent.com/176122/38740955-6aca9426-3f41-11e8-8da4-0a78c0426681.png)

**Comment by cenkce** [comment]
Tocat server error :

1) Invocation error of method public void org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.initialize() throws org.eclipse.che.api.core.ConflictException,org.eclipse.che.api.core.NotFoundException,org.eclipse.che.api.core.ServerException,org.eclipse.che.api.core.ForbiddenException on org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer@66ed04c7
  at org.eclipse.che.api.project.server.ProjectApiModule.configure(ProjectApiModule.java:60) (via modules: org.eclipse.che.wsagent.server.WsAgentModule -> org.eclipse.che.api.project.server.ProjectApiModule)
  while locating org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer
 
1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.rmi.RemoteException: Can't start maven server; nested exception is: 
	java.lang.Exception: Error: Could not find or load main class org.eclipse.che.maven.server.MavenServerMain
 
	at org.eclipse.che.plugin.maven.server.MavenServerManager.perform(MavenServerManager.java:244)
	at org.eclipse.che.plugin.maven.server.MavenServerManager.applyProfiles(MavenServerManager.java:145)
	at org.eclipse.che.plugin.maven.server.core.project.MavenModelReader.readModel(MavenModelReader.java:136)
	at org.eclipse.che.plugin.maven.server.core.project.MavenModelReader.readMavenProject(MavenModelReader.java:117)
	at org.eclipse.che.plugin.maven.server.core.project.MavenProject.read(MavenProject.java:214)
	at org.eclipse.che.plugin.maven.server.core.project.MavenProject.read(MavenProject.java:209)
	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.internalUpdate(MavenProjectManager.java:205)
	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.internalAddMavenProject(MavenProjectManager.java:171)
	at org.eclipse.che.plugin.maven.server.core.MavenProjectManager.update(MavenProjectManager.java:145)
	at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.update(MavenWorkspace.java:179)
	at org.eclipse.che.plugin.maven.server.projecttype.handler.MavenProjectInitHandler.initializeClasspath(MavenProjectInitHandler.java:41)
	at org.eclipse.che.plugin.java.server.projecttype.AbstractJavaInitHandler.onProjectInitialized(AbstractJavaInitHandler.java:61)
	at org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.firePostInitializationHandlers(OnWorkspaceStartProjectInitializer.java:90)
	at org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.initialize(OnWorkspaceStartProjectInitializer.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:46)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 18 common frames omitted
Caused by: java.rmi.RemoteException: Can't start maven server; nested exception is: 
	java.lang.Exception: Error: Could not find or load main class org.eclipse.che.maven.server.MavenServerMain
 
	at org.eclipse.che.plugin.maven.server.MavenServerManager.create(MavenServerManager.java:163)
	at org.eclipse.che.plugin.maven.server.MavenServerManager.create(MavenServerManager.java:47)
	at org.eclipse.che.plugin.maven.server.rmi.RmiObjectWrapper.getOrCreateWrappedObject(RmiObjectWrapper.java:27)
	at org.eclipse.che.plugin.maven.server.MavenServerManager.lambda$applyProfiles$4(MavenServerManager.java:147)
	at org.eclipse.che.plugin.maven.server.MavenServerManager.perform(MavenServerManager.java:238)
	... 50 common frames omitted
Caused by: java.lang.Exception: Error: Could not find or load main class org.eclipse.che.maven.server.MavenServerMain
 
	at org.eclipse.che.plugin.maven.server.rmi.RmiClient.acquire(RmiClient.java:66)
	at org.eclipse.che.plugin.maven.server.MavenServerManager.create(MavenServerManager.java:161)
	... 54 common frames omitted

**Comment by gorkem** [comment]
@eivantsov Can you check the che-in-che tutorial is still valid?

**Comment by andrew-mclachlan** [comment]
Following instructions on https://www.eclipse.org/che/docs/che-in-che-quickstart.html using Che 6.4.0  and encountering the same error. Instructions don't work.
