### ISSUE TITLE
Unable to start che-server use CHE_INFRA_KUBERNETES_SERVER__STRATEGY 

### ISSUE THREAD

**Issue by LarryZhangy** [eclipse-che/che#9428]
### Description
when i want to test single-host strategy to run che on kubernetes. che-server unable to startup.

### Reproduction Steps
create che-server by yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
  name: che
data:
  CHE_HOST: <domain>
  CHE_PORT: "8080"
  CHE_API: https://<domain>/api
  CHE_WEBSOCKET_ENDPOINT:  wss://<domain>/api/websocket
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: https://<domain>/agent-binaries/linux_amd64/bootstrapper/bootstrapper
  CHE_DEBUG_SERVER: "true"
  CHE_INFRASTRUCTURE_ACTIVE: "kubernetes"
  CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: <domain>
  CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_MASTER__URL: ""
  CHE_INFRA_KUBERNETES_OAUTH__TOKEN: ""
  CHE_INFRA_KUBERNETES_PASSWORD: ""
  CHE_INFRA_KUBERNETES_USERNAME: ""
  CHE_INFRA_KUBERNETES_NAMESPACE: larry
  CHE_INFRA_KUBERNETES_TLS__ENABLED: "true"
  CHE_INFRA_KUBERNETES_TLS__SECRET: larry-che-tls
  CHE_KEYCLOAK_AUTH__SERVER__URL: <domain>/auth
  CHE_KEYCLOAK_CLIENT__ID: "che-public"
  CHE_KEYCLOAK_REALM: "che"
  CHE_INFRA_KUBERNETES_NAMESPACE: ""
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "false"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: "common"
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "false"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "0"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "0"
  CHE_LOCAL_CONF_DIR: /etc/conf
  CHE_LOGS_DIR: /data/logs
  CHE_LOG_LEVEL: "INFO"
  CHE_MULTIUSER: "true"
  CHE_OAUTH_GITHUB_CLIENTID: ""
  CHE_OAUTH_GITHUB_CLIENTSECRET: ""
  CHE_PREDEFINED_STACKS_RELOAD__ON__START: "false"
  JAVA_OPTS: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m "
  CHE_WORKSPACE_AUTO_START: "false"
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": "nginx", "nginx.ingress.kubernetes.io/rewrite-target": "/","nginx.ingress.kubernetes.io/ssl-redirect": "true","nginx.ingress.kubernetes.io/proxy-connect-timeout": "3600","nginx.ingress.kubernetes.io/proxy-read-timeout": "3600"}'
  CHE_INFRA_KUBERNETES_SERVER__STRATEGY: "single-host"
  CHE_LOGS_APPENDERS_IMPL: "plaintext
```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: che
  name: che
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: che
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: che
    spec:
      initContainers:
      - name: wait-for-postgres-and-keycloak
        image: <my>/alphine:3.5
        command: ["sh", "-c", "pg_adresses_length=0 ; kc_adresses_length=0 ; until [ $pg_adresses_length -gt 0 -a $kc_adresses_length -gt 0 ]; do echo waiting for postgres to be ready...; sleep 2; endpoints=`curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"     https://kubernetes.default.svc/api/v1/namespaces/$POD_NAMESPACE/endpoints/postgres`; pg_adresses_length=`echo $endpoints | jq -r \".subsets[]?.addresses // [] | length\"`; endpoints=`curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"     https://kubernetes.default.svc/api/v1/namespaces/$POD_NAMESPACE/endpoints/keycloak`; kc_adresses_length=`echo $endpoints | jq -r \".subsets[]?.addresses // [] | length\"` ; done;"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      containers:
      - env:
        - name: CHE_HOST
          valueFrom:
            configMapKeyRef:
              key: CHE_HOST
              name: che
        - name: CHE_PORT
          valueFrom:
            configMapKeyRef:
              key: CHE_PORT
              name: che
        - name: CHE_API
          valueFrom:
            configMapKeyRef:
              key: CHE_API
              name: che
        - name: CHE_WEBSOCKET_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: CHE_WEBSOCKET_ENDPOINT
              name: che
        - name: CHE_DEBUG_SERVER
          valueFrom:
            configMapKeyRef:
              key: CHE_DEBUG_SERVER
              name: che
        - name: CHE_INFRASTRUCTURE_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRASTRUCTURE_ACTIVE
              name: che
        - name: CHE_INFRA_KUBERNETES_INGRESS_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_INGRESS_DOMAIN
              name: che
        - name: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
              name: che
        - name: CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN
              name: che
        - name: CHE_INFRA_KUBERNETES_MASTER__URL
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_MASTER__URL
              name: che
        - name: CHE_INFRA_KUBERNETES_OAUTH__TOKEN
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_OAUTH__TOKEN
              name: che
        - name: CHE_INFRA_KUBERNETES_PVC_STRATEGY
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_PVC_STRATEGY
              name: che
        - name: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
              name: che
        - name: CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER
              name: che
        - name: CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP
              name: che
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              key: JAVA_OPTS
              name: che
        - name: CHE_INFRA_KUBERNETES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_PASSWORD
              name: che
        - name: CHE_INFRA_KUBERNETES_TRUST__CERTS
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_TRUST__CERTS
              name: che
        - name: CHE_INFRA_KUBERNETES_USERNAME
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_USERNAME
              name: che
        - name: CHE_KEYCLOAK_AUTH__SERVER__URL
          valueFrom:
            configMapKeyRef:
              key: CHE_KEYCLOAK_AUTH__SERVER__URL
              name: che
        - name: CHE_KEYCLOAK_CLIENT__ID
          valueFrom:
            configMapKeyRef:
              key: CHE_KEYCLOAK_CLIENT__ID
              name: che
        - name: CHE_KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              key: CHE_KEYCLOAK_REALM
              name: che
        - name: CHE_INFRA_KUBERNETES_TLS__ENABLED
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_TLS__ENABLED
              name: che
        - name: CHE_INFRA_KUBERNETES_TLS__SECRET
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_TLS__SECRET
              name: che
        - name: CHE_INFRA_KUBERNETES_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_NAMESPACE
              name: che
        - name: CHE_LOCAL_CONF_DIR
          valueFrom:
            configMapKeyRef:
              key: CHE_LOCAL_CONF_DIR
              name: che
        - name: CHE_LOGS_DIR
          valueFrom:
            configMapKeyRef:
              key: CHE_LOGS_DIR
              name: che
        - name: CHE_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: CHE_LOG_LEVEL
              name: che
        - name: CHE_MULTIUSER
          valueFrom:
            configMapKeyRef:
              key: CHE_MULTIUSER
              name: che
        - name: CHE_OAUTH_GITHUB_CLIENTID
          valueFrom:
            configMapKeyRef:
              key: CHE_OAUTH_GITHUB_CLIENTID
              name: che
        - name: CHE_OAUTH_GITHUB_CLIENTSECRET
          valueFrom:
            configMapKeyRef:
              key: CHE_OAUTH_GITHUB_CLIENTSECRET
              name: che
        - name: CHE_PREDEFINED_STACKS_RELOAD__ON__START
          valueFrom:
            configMapKeyRef:
              key: CHE_PREDEFINED_STACKS_RELOAD__ON__START
              name: che
        - name: CHE_WORKSPACE_AUTO_START
          valueFrom:
            configMapKeyRef:
              key: CHE_WORKSPACE_AUTO_START
              name: che
        - name: CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON
              name: che
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CHE_INFRA_KUBERNETES_SERVER__STRATEGY
          valueFrom:
            configMapKeyRef:
              key: CHE_INFRA_KUBERNETES_SERVER__STRATEGY
              name: che
        - name: CHE_LOGS_APPENDERS_IMPL
          valueFrom:
            configMapKeyRef:
              key: CHE_LOGS_APPENDERS_IMPL
              name: che
        image: eclipse/che-server:nightly
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/system/state
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: che
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8000
          name: http-debug
        - containerPort: 8888
          name: jgroups-ping
        readinessProbe:
          httpGet:
            path: /api/system/state
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 60
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 256Mi
```

**OS and version:**    

**Diagnostics:** 
Logs:
```
Listening for transport dt_socket at address: 8000
2018-04-15 05:21:13,385[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.23
2018-04-15 05:21:13,388[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Sep 28 2017 10:30:11 UTC
2018-04-15 05:21:13,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.23.0
2018-04-15 05:21:13,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2018-04-15 05:21:13,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-327.55.58.94.h9.x86_64
2018-04-15 05:21:13,389[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2018-04-15 05:21:13,390[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
2018-04-15 05:21:13,390[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_131-b11
2018-04-15 05:21:13,390[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2018-04-15 05:21:13,391[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/eclipse-che/tomcat
2018-04-15 05:21:13,391[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/eclipse-che/tomcat
2018-04-15 05:21:13,391[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/eclipse-che//tomcat/conf/logging.properties
2018-04-15 05:21:13,391[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2018-04-15 05:21:13,392[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxRAMFraction=2
2018-04-15 05:21:13,392[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseParallelGC
2018-04-15 05:21:13,392[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MinHeapFreeRatio=10
2018-04-15 05:21:13,392[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxHeapFreeRatio=20
2018-04-15 05:21:13,393[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:GCTimeRatio=4
2018-04-15 05:21:13,393[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:AdaptiveSizePolicyWeight=90
2018-04-15 05:21:13,393[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UnlockExperimentalVMOptions
2018-04-15 05:21:13,393[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseCGroupMemoryLimitForHeap
2018-04-15 05:21:13,394[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dsun.zip.disableMemoryMapping=true
2018-04-15 05:21:13,394[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms20m
2018-04-15 05:21:13,394[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.docker.network=bridge
2018-04-15 05:21:13,394[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2018-04-15 05:21:13,395[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/user/eclipse-che/
2018-04-15 05:21:13,395[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/data/logs
2018-04-15 05:21:13,395[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2018-04-15 05:21:13,395[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/eclipse-che//tomcat/conf/tomcat-logger.xml
2018-04-15 05:21:13,395[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
2018-04-15 05:21:13,396[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2018-04-15 05:21:13,396[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
2018-04-15 05:21:13,396[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2018-04-15 05:21:13,396[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2018-04-15 05:21:13,396[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2018-04-15 05:21:13,397[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/etc/conf
2018-04-15 05:21:13,397[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/eclipse-che//tomcat
2018-04-15 05:21:13,397[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/eclipse-che//tomcat
2018-04-15 05:21:13,397[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/eclipse-che//tomcat/temp
2018-04-15 05:21:13,493[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 573]  - Initializing ProtocolHandler ["http-nio-8080"]
2018-04-15 05:21:13,510[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
2018-04-15 05:21:13,512[main]             [INFO ] [o.a.catalina.startup.Catalina 632]   - Initialization processed in 458 ms
2018-04-15 05:21:13,578[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port [32001] and the server on port [32101] for the [Platform] server
2018-04-15 05:21:13,579[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service [Catalina]
2018-04-15 05:21:13,579[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.23
2018-04-15 05:21:14,225[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war]
2018-04-15 05:21:15,392[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war] has finished in [1,166] ms
2018-04-15 05:21:15,394[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/api.war]
2018-04-15 05:21:16,228[ost-startStop-1]  [INFO ] [.e.c.c.d.JNDIDataSourceFactory 59]   - This=org.eclipse.che.core.db.postgresql.PostgreSQLJndiDataSourceFactory@7dce75d9 obj=ResourceRef[className=javax.sql.DataSource,factoryClassLocation=null,factoryClassName=org.apache.naming.factory.ResourceFactory,{type=scope,content=Shareable},{type=auth,content=Container},{type=singleton,content=true},{type=factory,content=org.eclipse.che.api.CommonJndiDataSourceFactory}] name=che Context=org.apache.naming.NamingContext@7953a1f4 environment={}
2018-04-15 05:21:18,634[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4752] - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) org.eclipse.che.workspace.infrastructure.kubernetes.server.ExternalServerExposerStrategy<T> cannot be used as a key; It is not fully specified.
  at org.eclipse.che.workspace.infrastructure.kubernetes.provision.server.ServersConverter.<init>(ServersConverter.java:45)
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.provision.server.ServersConverter
    for the 3rd parameter of org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesEnvironmentProvisioner.<init>(KubernetesEnvironmentProvisioner.java:67)
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesEnvironmentProvisioner
    for the 3rd parameter of org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructure.<init>(KubernetesInfrastructure.java:51)
  at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfraModule.configure(KubernetesInfraModule.java:63) (via modules: org.eclipse.che.api.deploy.WsMasterModule -> org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfraModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2018-04-15 05:21:18,634[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5208]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
2018-04-15 05:21:18,635[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5259]     - Context [/api] startup failed due to previous errors
2018-04-15 05:21:18,667[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [3,272] ms
2018-04-15 05:21:18,671[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/dashboard.war]
2018-04-15 05:21:18,936[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/dashboard.war] has finished in [265] ms
2018-04-15 05:21:18,937[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war]
2018-04-15 05:21:19,170[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war] has finished in [233] ms
2018-04-15 05:21:19,171[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
2018-04-15 05:21:19,252[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war] has finished in [81] ms
2018-04-15 05:21:19,253[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/workspace-loader.war]
2018-04-15 05:21:19,318[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/workspace-loader.war] has finished in [64] ms
2018-04-15 05:21:19,323[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-8080"]
2018-04-15 05:21:19,335[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 5821 ms

```

**Comment by LarryZhangy** [comment]
@guydaichs

**Comment by LarryZhangy** [comment]
/kind/bug

**Comment by guydaichs** [comment]
@LarryZhangy - the yaml file is outdated. Please use the helm charts to deploy che, until it is updated.

**Comment by LarryZhangy** [comment]
@guydaichs I copy yam from master branch of che. In my env i can't install che by helm. could you tell me how  i can get yaml file from helm charts of che? Thank you very much!

**Comment by guydaichs** [comment]
@LarryZhangy - my mistake. The issue also reproduces with a helm deployment, and your yaml looks up-to-date.  

This may be related to https://github.com/eclipse/che/commit/88a37ca2039a53fb35c7a3c6dc6efa8369aa06a2.
@garagatyi -  can you have a look?

**Comment by LarryZhangy** [comment]
@guydaichs Thanks your help!

**Comment by garagatyi** [comment]
@slemeur we have broken kubernetes infra for the time being. Should we mark this issue as a blocker?

**Comment by slemeur** [comment]
it should be a blocker yes.

**Comment by garagatyi** [comment]
Fixed in https://github.com/eclipse/che/pull/9446. Sorry for not notifying in time!
