### ISSUE TITLE
Not able to run eclipse/che-theia-* plugins in Che Theia stack

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9481]
### Description
I was trying to run our theia plugins in Theia stack 
<img width="1074" alt="2018-04-18 14 03 37" src="https://user-images.githubusercontent.com/1614429/38928847-2072d91c-4313-11e8-9bd0-c3168538412c.png">

but I've got.
<img width="939" alt="2018-04-18 14 15 58" src="https://user-images.githubusercontent.com/1614429/38928854-22ad4758-4313-11e8-8b86-77504c1db879.png">
Next time I have
```
Loading...
[DOCKER] nightly: Pulling from eclipse/che-theia 
[DOCKER] Digest: sha256:635a3b7ab5b3e8833d9eebc12b68180f79c6c21073285c465b94f7e8d833c154 
[DOCKER] Status: Image is up to date for eclipse/che-theia:nightly 
[DOCKER] nightly: Pulling from eclipse/che-dev 
[DOCKER] Digest: sha256:3eb2c355a4c888316c4778d3cb1d738d85cb5dc12e6e725b974cb6f7f6cab8cf 
[DOCKER] Status: Image is up to date for eclipse/che-dev:nightly 
Building plugin: github-extension
warning package.json: No license field
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
warning package.json: No license field
warning package.json: No license field
Plugins set changed. Rebuilding Theia...
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["@theia/outline-view@latest"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v1/npm-@theia/outline-view-0.3.7-e9e8967852ed99c01a889901bad4e23715932ede" as pattern ["@theia/outline-view@^0.3.7"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/markers@latest"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v1/npm-@theia/markers-0.3.7-55a1f9c91dd2b58de6ef3452e64c965feedf8620" as pattern ["@theia/markers@^0.3.7"]. This could result in non-deterministic behavior, skipping.
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@theia/extension-manager > @theia/application-package > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 13.79s.
yarn run v1.5.1
$ /home/theia/node_modules/.bin/theia build
Hash: e057e5bae5fbdf61a069
Version: webpack 2.7.0
Time: 8988ms
                                                                                  Asset     Size  Chunks                    Chunk Names
                                          vs/basic-languages/src/monaco.contribution.js  4.97 kB          [emitted]         
node_modules/@theia/core/src/browser/icons/spinner.e817279537a0417d042f62fbb1b99eea.gif  44.1 kB          [emitted]         
                                                 e19892df121e7f85c61754c54bbb7951.woff2  49.8 kB          [emitted]         
                                                 11d1a2390613abf202bfd2ebbd5c4500.woff2  90.7 kB          [emitted]         
                                                 af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]         
                                                 0a32a80243e05284a5d741c5dc093f31.woff2  24.4 kB          [emitted]         
                                                 de59a97248b44599e6747a27a943f738.woff2  20.2 kB          [emitted]         
                                                  fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]         
                                                   674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]         
                                                   912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]  
                                                   b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]         
                                                                              bundle.js   6.1 MB       0  [emitted]  [big]  main
                                                                          bundle.js.map  7.58 MB       0  [emitted]         main
                                                                             require.js  86.5 kB          [emitted]         
                                                             vs/language/css/cssMode.js    21 kB          [emitted]         
                                                 vs/language/css/monaco.contribution.js  2.31 kB          [emitted]         
                                                           vs/language/json/jsonMode.js  36.5 kB          [emitted]         
                                                            vs/language/css/monaco.d.ts  1.98 kB          [emitted]         
                                                           vs/language/css/cssWorker.js   477 kB          [emitted]  [big]  
                                                vs/language/json/monaco.contribution.js  1.82 kB          [emitted]         
                                                           vs/language/json/monaco.d.ts  1.71 kB          [emitted]         
                                                         vs/language/json/jsonWorker.js    93 kB          [emitted]         
                                                           vs/language/html/htmlMode.js  19.3 kB          [emitted]         
                                                vs/language/html/monaco.contribution.js  2.35 kB          [emitted]         
                                                           vs/language/html/monaco.d.ts  1.83 kB          [emitted]         
                                                         vs/language/html/htmlWorker.js   113 kB          [emitted]         
                                                          vs/basic-languages/src/bat.js  2.11 kB          [emitted]         
                                                       vs/basic-languages/src/coffee.js  3.88 kB          [emitted]         
                                                       vs/basic-languages/src/csharp.js  4.83 kB          [emitted]         
                                                          vs/basic-languages/src/cpp.js  4.69 kB          [emitted]         
                                                          vs/basic-languages/src/css.js  4.73 kB          [emitted]         
                                                   vs/basic-languages/src/dockerfile.js  2.37 kB          [emitted]         
                                                       vs/basic-languages/src/fsharp.js  3.15 kB          [emitted]         
                                                           vs/basic-languages/src/go.js  3.04 kB          [emitted]         
                                                   vs/basic-languages/src/handlebars.js  6.52 kB          [emitted]         
                                                         vs/basic-languages/src/html.js   4.8 kB          [emitted]         
                                                          vs/basic-languages/src/ini.js  1.48 kB          [emitted]         
                                                         vs/basic-languages/src/less.js  4.14 kB          [emitted]         
                                                         vs/basic-languages/src/java.js  3.19 kB          [emitted]         
                                                     vs/basic-languages/src/markdown.js  3.58 kB          [emitted]         
                                                   cf2aabacdc2b3a5768b03545cb1d8330.svg  21.5 kB          [emitted]         
                                                          vs/basic-languages/src/lua.js   2.5 kB          [emitted]         
                                                        vs/basic-languages/src/msdax.js  5.29 kB          [emitted]         
                                                  vs/basic-languages/src/objective-c.js  2.79 kB          [emitted]         
                                                          vs/basic-languages/src/php.js  8.31 kB          [emitted]         
                                                     vs/basic-languages/src/postiats.js  8.24 kB          [emitted]         
                                                   vs/basic-languages/src/powershell.js  3.56 kB          [emitted]         
                                                          vs/basic-languages/src/pug.js  5.19 kB          [emitted]         
                                                       vs/basic-languages/src/python.js   3.3 kB          [emitted]         
                                                            vs/basic-languages/src/r.js  3.21 kB          [emitted]         
                                                        vs/basic-languages/src/razor.js  8.84 kB          [emitted]         
                                                         vs/basic-languages/src/ruby.js   8.5 kB          [emitted]         
                                                         vs/basic-languages/src/scss.js  6.65 kB          [emitted]         
                                                           vs/basic-languages/src/sb.js  2.21 kB          [emitted]         
                                                          vs/basic-languages/src/sql.js  18.6 kB          [emitted]         
                                                     vs/basic-languages/src/solidity.js    19 kB          [emitted]         
                                                        vs/basic-languages/src/swift.js  4.51 kB          [emitted]         
                                                           vs/basic-languages/src/vb.js  5.98 kB          [emitted]         
                                                         vs/basic-languages/src/yaml.js  3.87 kB          [emitted]         
                                                          vs/basic-languages/src/xml.js  2.12 kB          [emitted]         
                                 vs/editor/contrib/suggest/browser/media/String_16x.svg  4.74 kB          [emitted]         
                         vs/editor/contrib/suggest/browser/media/String_inverse_16x.svg  4.74 kB          [emitted]         
                                                              vs/editor/editor.main.css   172 kB          [emitted]         
                                                           vs/base/worker/workerMain.js   152 kB          [emitted]         
                                                        vs/editor/editor.main.nls.fr.js  31.2 kB          [emitted]         
                                                        vs/editor/editor.main.nls.de.js  28.1 kB          [emitted]         
                                                        vs/editor/editor.main.nls.es.js    29 kB          [emitted]         
                                                        vs/editor/editor.main.nls.hu.js  31.1 kB          [emitted]         
                                                           vs/editor/editor.main.nls.js  24.3 kB          [emitted]         
                                                        vs/editor/editor.main.nls.ko.js  28.6 kB          [emitted]         
                                                     vs/editor/editor.main.nls.pt-br.js  27.8 kB          [emitted]         
                                                        vs/editor/editor.main.nls.it.js    30 kB          [emitted]         
                                                        vs/editor/editor.main.nls.tr.js    28 kB          [emitted]         
                                                     vs/editor/editor.main.nls.zh-cn.js  22.6 kB          [emitted]         
                                                     vs/editor/editor.main.nls.zh-tw.js  23.1 kB          [emitted]         
                               vs/editor/standalone/browser/quickOpen/symbol-sprite.svg  20.7 kB          [emitted]         
                                                                           vs/loader.js  28.9 kB          [emitted]         
                                                        vs/editor/editor.main.nls.ja.js  31.8 kB          [emitted]         
                                                        vs/editor/editor.main.nls.ru.js    44 kB          [emitted]         
                                                               vs/editor/editor.main.js  1.81 MB          [emitted]  [big]  
   [0] ./~/inversify/lib/inversify.js 2.5 kB {0} [built]
   [2] ./~/@theia/core/lib/browser/index.js 1.18 kB {0} [built]
 [370] ./~/@theia/markers/lib/browser/problem/problem-frontend-module.js 2.52 kB {0} [built]
 [371] ./~/@theia/monaco/lib/browser/monaco-browser-module.js 809 bytes {0} [built]
 [372] ./~/@theia/navigator/lib/browser/navigator-frontend-module.js 2.21 kB {0} [built]
 [373] ./~/@theia/outline-view/lib/browser/outline-view-frontend-module.js 2.35 kB {0} [built]
 [374] ./~/@theia/output/lib/browser/output-frontend-module.js 1.83 kB {0} [built]
 [375] ./~/@theia/preferences/lib/browser/preference-frontend-module.js 1.38 kB {0} [built]
 [376] ./~/@theia/terminal/lib/browser/terminal-frontend-module.js 4.35 kB {0} [built]
 [377] ./~/@theia/typescript/lib/browser/typescript-frontend-module.js 1.77 kB {0} [built]
 [378] ./~/@theia/userstorage/lib/browser/user-storage-frontend-module.js 973 bytes {0} [built]
 [379] ./~/che-theia-ssh-extension/lib/browser/ssh-frontend-module.js 1.3 kB {0} [built]
 [380] ./~/github-extension/lib/browser/github-frontend-module.js 919 bytes {0} [built]
 [381] ./~/reflect-metadata/Reflect.js 52.3 kB {0} [built] [1 warning]
 [710] ./src-gen/frontend/index.js 3.74 kB {0} [built]
    + 733 hidden modules
WARNING in ./~/reflect-metadata/Reflect.js
(Emitted value instead of an instance of Error) Cannot find source file 'Reflect.ts': Error: Can't resolve './Reflect.ts' in '/home/theia/node_modules/reflect-metadata'
 @ ./src-gen/frontend/index.js 2:0-27
WARNING in ./~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression
WARNING in ./~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression
WARNING in ./~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression
Done in 10.29s.
yarn run v1.5.1
$ /home/theia/node_modules/.bin/theia start /projects --hostname=0.0.0.0 --port=3000
Starting server worker...
Server worker has been started. [ID: 1 | PID: 1057]
Failed to start the backend application.
{ Error: Cannot find module '@octokit/rest'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object. (/home/theia/node_modules/github-extension/lib/node/github-service-impl.js:62:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
/home/theia/node_modules/@theia/core/lib/node/cluster/main.js:49
    throw reason;
    ^
Error: Cannot find module '@octokit/rest'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object. (/home/theia/node_modules/github-extension/lib/node/github-service-impl.js:62:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Server worker has been disconnected. [ID: 1 | PID: 1057]
Server worker has been stopped. [ID: 1 | PID: 1057]
```

**Comment by mmorhun** [comment]
This is problem of the github extension.

**Comment by mmorhun** [comment]
@vinokurig take a look please

**Comment by skabashnyuk** [comment]
@ashumilova @vinokurig  what are the state of this issue?

**Comment by vinokurig** [comment]
Can not reproduce

**Comment by skabashnyuk** [comment]
ok. let me check.

**Comment by skabashnyuk** [comment]
I continue reproducing this issue.
I've got

```
arning package.json: No license field
warning package.json: No license field
Plugins set changed. Rebuilding Theia...
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["@theia/outline-view@latest"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v1/npm-@theia/outline-view-0.3.7-e9e8967852ed99c01a889901bad4e23715932ede" as pattern ["@theia/outline-view@^0.3.7"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/markers@latest"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v1/npm-@theia/markers-0.3.7-55a1f9c91dd2b58de6ef3452e64c965feedf8620" as pattern ["@theia/markers@^0.3.7"]. This could result in non-deterministic behavior, skipping.
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@theia/extension-manager > @theia/application-package > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 15.84s.
yarn run v1.5.1
$ /home/theia/node_modules/.bin/theia build
Hash: e057e5bae5fbdf61a069
Version: webpack 2.7.0
Time: 10038ms
                                                                                  Asset     Size  Chunks                    Chunk Names
                                                          vs/basic-languages/src/lua.js   2.5 kB          [emitted]
node_modules/@theia/core/src/browser/icons/spinner.e817279537a0417d042f62fbb1b99eea.gif  44.1 kB          [emitted]
                                                 e19892df121e7f85c61754c54bbb7951.woff2  49.8 kB          [emitted]
                                                 11d1a2390613abf202bfd2ebbd5c4500.woff2  90.7 kB          [emitted]
                                                 af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
                                                 0a32a80243e05284a5d741c5dc093f31.woff2  24.4 kB          [emitted]
                                                 de59a97248b44599e6747a27a943f738.woff2  20.2 kB          [emitted]
                                                  fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
                                                   674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
                                                   912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
                                                   b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
                                                                              bundle.js   6.1 MB       0  [emitted]  [big]  main
                                                                          bundle.js.map  7.58 MB       0  [emitted]         main
                                                                             require.js  86.5 kB          [emitted]
                                                             vs/language/css/cssMode.js    21 kB          [emitted]
                                                 vs/language/css/monaco.contribution.js  2.31 kB          [emitted]
                                                            vs/language/css/monaco.d.ts  1.98 kB          [emitted]
                                                           vs/language/json/jsonMode.js  36.5 kB          [emitted]
                                                         vs/language/json/jsonWorker.js    93 kB          [emitted]
                                                vs/language/json/monaco.contribution.js  1.82 kB          [emitted]
                                                           vs/language/json/monaco.d.ts  1.71 kB          [emitted]
                                                           vs/language/html/htmlMode.js  19.3 kB          [emitted]
                                                           vs/language/css/cssWorker.js   477 kB          [emitted]  [big]
                                                vs/language/html/monaco.contribution.js  2.35 kB          [emitted]
                                                           vs/language/html/monaco.d.ts  1.83 kB          [emitted]
                                                         vs/language/html/htmlWorker.js   113 kB          [emitted]
                                                          vs/basic-languages/src/bat.js  2.11 kB          [emitted]
                                                       vs/basic-languages/src/coffee.js  3.88 kB          [emitted]
                                                          vs/basic-languages/src/cpp.js  4.69 kB          [emitted]
                                                          vs/basic-languages/src/css.js  4.73 kB          [emitted]
                                                       vs/basic-languages/src/csharp.js  4.83 kB          [emitted]
                                                   vs/basic-languages/src/dockerfile.js  2.37 kB          [emitted]
                                                       vs/basic-languages/src/fsharp.js  3.15 kB          [emitted]
                                                           vs/basic-languages/src/go.js  3.04 kB          [emitted]
                                                   vs/basic-languages/src/handlebars.js  6.52 kB          [emitted]
                                                         vs/basic-languages/src/html.js   4.8 kB          [emitted]
                                                         vs/basic-languages/src/less.js  4.14 kB          [emitted]
                                                         vs/basic-languages/src/java.js  3.19 kB          [emitted]
                                                          vs/basic-languages/src/ini.js  1.48 kB          [emitted]
                                                     vs/basic-languages/src/markdown.js  3.58 kB          [emitted]
                                                   cf2aabacdc2b3a5768b03545cb1d8330.svg  21.5 kB          [emitted]
                                          vs/basic-languages/src/monaco.contribution.js  4.97 kB          [emitted]
                                                        vs/basic-languages/src/msdax.js  5.29 kB          [emitted]
                                                  vs/basic-languages/src/objective-c.js  2.79 kB          [emitted]
                                                          vs/basic-languages/src/php.js  8.31 kB          [emitted]
                                                     vs/basic-languages/src/postiats.js  8.24 kB          [emitted]
                                                   vs/basic-languages/src/powershell.js  3.56 kB          [emitted]
                                                       vs/basic-languages/src/python.js   3.3 kB          [emitted]
                                                          vs/basic-languages/src/pug.js  5.19 kB          [emitted]
                                                            vs/basic-languages/src/r.js  3.21 kB          [emitted]
                                                        vs/basic-languages/src/razor.js  8.84 kB          [emitted]
                                                         vs/basic-languages/src/ruby.js   8.5 kB          [emitted]
                                                           vs/basic-languages/src/sb.js  2.21 kB          [emitted]
                                                         vs/basic-languages/src/scss.js  6.65 kB          [emitted]
                                                     vs/basic-languages/src/solidity.js    19 kB          [emitted]
                                                          vs/basic-languages/src/sql.js  18.6 kB          [emitted]
                                                        vs/basic-languages/src/swift.js  4.51 kB          [emitted]
                                                           vs/basic-languages/src/vb.js  5.98 kB          [emitted]
                                                          vs/basic-languages/src/xml.js  2.12 kB          [emitted]
                                                         vs/basic-languages/src/yaml.js  3.87 kB          [emitted]
                                 vs/editor/contrib/suggest/browser/media/String_16x.svg  4.74 kB          [emitted]
                         vs/editor/contrib/suggest/browser/media/String_inverse_16x.svg  4.74 kB          [emitted]
                                                           vs/base/worker/workerMain.js   152 kB          [emitted]
                                                              vs/editor/editor.main.css   172 kB          [emitted]
                                                        vs/editor/editor.main.nls.es.js    29 kB          [emitted]
                                                        vs/editor/editor.main.nls.de.js  28.1 kB          [emitted]
                                                        vs/editor/editor.main.nls.fr.js  31.2 kB          [emitted]
                                                        vs/editor/editor.main.nls.hu.js  31.1 kB          [emitted]
                                                        vs/editor/editor.main.nls.it.js    30 kB          [emitted]
                                                        vs/editor/editor.main.nls.ja.js  31.8 kB          [emitted]
                                                           vs/editor/editor.main.nls.js  24.3 kB          [emitted]
                                                        vs/editor/editor.main.nls.ko.js  28.6 kB          [emitted]
                                                     vs/editor/editor.main.nls.pt-br.js  27.8 kB          [emitted]
                                                        vs/editor/editor.main.nls.ru.js    44 kB          [emitted]
                                                        vs/editor/editor.main.nls.tr.js    28 kB          [emitted]
                                                     vs/editor/editor.main.nls.zh-tw.js  23.1 kB          [emitted]
                                                     vs/editor/editor.main.nls.zh-cn.js  22.6 kB          [emitted]
                               vs/editor/standalone/browser/quickOpen/symbol-sprite.svg  20.7 kB          [emitted]
                                                                           vs/loader.js  28.9 kB          [emitted]
                                                               vs/editor/editor.main.js  1.81 MB          [emitted]  [big]
   [0] ./~/inversify/lib/inversify.js 2.5 kB {0} [built]
   [2] ./~/@theia/core/lib/browser/index.js 1.18 kB {0} [built]
 [370] ./~/@theia/markers/lib/browser/problem/problem-frontend-module.js 2.52 kB {0} [built]
 [371] ./~/@theia/monaco/lib/browser/monaco-browser-module.js 809 bytes {0} [built]
 [372] ./~/@theia/navigator/lib/browser/navigator-frontend-module.js 2.21 kB {0} [built]
 [373] ./~/@theia/outline-view/lib/browser/outline-view-frontend-module.js 2.35 kB {0} [built]
 [374] ./~/@theia/output/lib/browser/output-frontend-module.js 1.83 kB {0} [built]
 [375] ./~/@theia/preferences/lib/browser/preference-frontend-module.js 1.38 kB {0} [built]
 [376] ./~/@theia/terminal/lib/browser/terminal-frontend-module.js 4.35 kB {0} [built]
 [377] ./~/@theia/typescript/lib/browser/typescript-frontend-module.js 1.77 kB {0} [built]
 [378] ./~/@theia/userstorage/lib/browser/user-storage-frontend-module.js 973 bytes {0} [built]
 [379] ./~/che-theia-ssh-extension/lib/browser/ssh-frontend-module.js 1.3 kB {0} [built]
 [380] ./~/github-extension/lib/browser/github-frontend-module.js 919 bytes {0} [built]
 [381] ./~/reflect-metadata/Reflect.js 52.3 kB {0} [built] [1 warning]
 [710] ./src-gen/frontend/index.js 3.74 kB {0} [built]
    + 733 hidden modules

WARNING in ./~/reflect-metadata/Reflect.js
(Emitted value instead of an instance of Error) Cannot find source file 'Reflect.ts': Error: Can't resolve './Reflect.ts' in '/home/theia/node_modules/reflect-metadata'
 @ ./src-gen/frontend/index.js 2:0-27

WARNING in ./~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

Done in 11.69s.
yarn run v1.5.1
$ /home/theia/node_modules/.bin/theia start /projects --hostname=0.0.0.0 --port=3000
Starting server worker...

Server worker has been started. [ID: 1 | PID: 1071]

Failed to start the backend application.

{ Error: Cannot find module '@octokit/rest'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/theia/node_modules/github-extension/lib/node/github-service-impl.js:62:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }

/home/theia/node_modules/@theia/core/lib/node/cluster/main.js:49
    throw reason;
    ^

Error: Cannot find module '@octokit/rest'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/theia/node_modules/github-extension/lib/node/github-service-impl.js:62:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Server worker has been disconnected. [ID: 1 | PID: 1071]

Server worker has been stopped. [ID: 1 | PID: 1071]

```

**Comment by skabashnyuk** [comment]
<details>
<summary>my ws-config</summary>

```
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "theia": {
          "attributes": {},
          "servers": {
            "theia": {
              "attributes": {
                "type": "ide"
              },
              "port": "3000",
              "protocol": "http"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            },
            "theia": {
              "path": "/home/theia"
            }
          },
          "installers": [],
          "env": {
            "THEIA_PLUGINS": "github-extension:https://github.com/eclipse/che-theia-github-plugin.git"
          }
        },
        "dev-machine": {
          "attributes": {},
          "servers": {
            "theia-dev": {
              "attributes": {},
              "port": "3030",
              "protocol": "http"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {}
        }
      },
      "recipe": {
        "type": "compose",
        "content": "services:\n theia:\n  image: 'eclipse/che-theia:nightly'\n  mem_limit: 1073741824\n dev-machine:\n  image: 'eclipse/che-dev:nightly'\n  mem_limit: 2147483648\n  depends_on:\n   - theia\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "name": "wksp-theia",
  "projects": [],
  "commands": [],
  "links": []
}
```
</details>

**Comment by eivantsov** [comment]
@skabashnyuk @vinokurig I confirm the issue. Same output for me.

@vinokurig can you identify Theia version in the image you have?

**Comment by vinokurig** [comment]
Reproduced the issue after destroy and restart CHE

**Comment by eivantsov** [comment]
@vinokurig I wonder if it's cause by 0.3.8 version of Theia that we currently have in `eclipse/che-theia:nightly` image.

**Comment by vinokurig** [comment]
Couldn't start the plugin locally.  I'll investigate it ASAP.

**Comment by vinokurig** [comment]
I've fixed the issue with running the plugin locally by updating Theia dependencies to latest.
The problem is that the workspace with the plugin hangs on loading. @ashumilova I guess this is caused by version difference of the Theia in the image (0.3.7) and Theia in the plugin dependencies (0.3.10).
