### ISSUE TITLE
Connection refused in language server sidecar after following instructions 

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#9544]
### Description
I've been following https://www.eclipse.org/che/docs/language-servers.html#ls-sidecars to try and test out the typescript ls in a sidecar to try and see how it works. However, I am getting connection refuse when I start the workspace and the LS is started.

I've built the file shown in the ls-sidecars document and uploaded it to jpinkney/typescriptls1.

I'm doing this on latest version of che on docker.

My environment config is:
```
{
  "environments": {
    "default": {
      "recipe": {
        "contentType": "text/x-yaml",
        "type": "compose",
        "content": "services:\n typescript-ls-machine:\n  image: jpinkney/typescriptls1\n  mem_limit: 1073741824\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n   - typescript-ls-machine\n"
      },
      "machines": {
        "typescript-ls-machine": {
          "env": {},
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "attributes": {
            "memoryLimitBytes": "2147483648"
          }
        },
        "dev-machine": {
          "env": {},
          "servers": {
            "ls2": {
              "attributes": {
                "internal": "true",
                "type": "ls",
                "config": "{\"id\":\"tsls\", \"languageIds\":[typescript]}"
              },
              "protocol": "tcp",
              "port": "4417"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent"
          ],
          "attributes": {
            "memoryLimitBytes": "2147483648"
          }
        }
      }
    }
  },
  "projects": [
    {
      "source": {
        "location": "https://github.com/Microsoft/TypeScriptSamples.git",
        "type": "git",
        "parameters": {
          "convertToTopLevelProject": "true",
          "keepVcs": "false",
          "keepDir": "greeter"
        }
      },
      "links": [],
      "mixins": [],
      "problems": [],
      "name": "test",
      "type": "typescript",
      "path": "/test",
      "attributes": {}
    }
  ],
  "commands": [],
  "defaultEnv": "default",
  "name": "wksp-ymqi",
  "links": []
}
```

**Diagnostics:** 
```
2018-04-25 16:58:37,097[equestProcessor]  [ERROR] [l.r.LanguageServerRegistryImpl 157]  - Error launching language server org.eclipse.che.api.languageserver.remote.SocketLsLauncherProvider$SocketLanguageServerLauncher@22443841
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669)
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997)
	at org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl.initialize(LanguageServerRegistryImpl.java:137)
	at org.eclipse.che.api.languageserver.service.LanguageServerInitializationHandler.lambda$new$0(LanguageServerInitializationHandler.java:37)
	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToOne.lambda$withFunction$0(FunctionConfiguratorOneToOne.java:75)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
Caused by: org.eclipse.che.api.languageserver.exception.LanguageServerException: Can't initialize Language Server tsls on file:///projects/test. Can't launch language server for project: file:///projects/test
	at org.eclipse.che.api.languageserver.registry.ServerInitializerImpl.initialize(ServerInitializerImpl.java:111)
	at org.eclipse.che.api.languageserver.remote.SocketLsLauncherProvider$SocketLanguageServerLauncher.launch(SocketLsLauncherProvider.java:121)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	... 12 common frames omitted
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Caused by: org.eclipse.che.api.languageserver.exception.LanguageServerException: Can't launch language server for project: file:///projects/test
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.api.languageserver.remote.SocketLsLauncherProvider$SocketLanguageServerLauncher.launch(SocketLsLauncherProvider.java:132)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl.initialize(LanguageServerRegistryImpl.java:136)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	... 11 common frames omitted
java.util.concurrent.CompletionException: org.eclipse.che.api.languageserver.exception.LanguageServerException: Can't initialize Language Server tsls on file:///projects/test. Can't launch language server for project: file:///projects/test
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.Socket.<init>(Socket.java:211)
	at java.net.Socket.<init>(Socket.java:434)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
	at java.net.Socket.connect(Socket.java:538)
	... 13 common frames omitted
	at org.eclipse.che.api.languageserver.registry.ServerInitializerImpl.initialize(ServerInitializerImpl.java:102)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
```

**Comment by JPinkney** [comment]
Closing.

I found out 
```
    "ls2": {
              "attributes": {
                "internal": "true",
                "type": "ls",
                "config": "{\"id\":\"tsls\", \"languageIds\":[typescript]}"
              },
              "protocol": "tcp",
              "port": "4417"
            }
```

was supposed to go in the typescript machine.
