### ISSUE TITLE
Creation of the pull request by pull request plugin was failed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9548]
### Description
Selenium test **org.eclipse.che.selenium.git.PullRequestPluginWithForkTest.createPullRequest** fails at line with command `pullRequestPanel.waitMessage(PULL_REQUEST_CREATED)` sometimes because of server side error:
> [o.e.c.p.g.s.rest.GitHubService 307]  - Creating  pull request fail
org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

<details>
 <summary>full error log of ws-agent</summary>
 <pre>
2018-04-26 20:25:52,518[nio-4401-exec-3]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error occurred, error time: 2018-04-26 20:25:52
java.lang.NullPointerException: null
	at org.eclipse.jgit.transport.RefSpec.<init>(RefSpec.java:163)
	at org.eclipse.jgit.transport.RefSpec.<init>(RefSpec.java:226)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.che.git.impl.jgit.JGitConnection.push(JGitConnection.java:1469)
	at org.eclipse.che.api.git.GitService.push(GitService.java:405)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.workspace.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:52)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.machine.authentication.agent.MachineLoginFilter.doFilter(MachineLoginFilter.java:84)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:294)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:161)
	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2018-04-26 20:25:53,130[nio-4401-exec-6]  [ERROR] [o.e.c.p.g.s.rest.GitHubService 307]  - Creating  pull request fail
org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:690)
	at org.kohsuke.github.Requester._to(Requester.java:293)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GHRepository.createPullRequest(GHRepository.java:737)
	at org.eclipse.che.plugin.github.server.rest.GitHubService.createPullRequest(GitHubService.java:302)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.che.workspace.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:52)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.multiuser.machine.authentication.agent.MachineLoginFilter.doFilter(MachineLoginFilter.java:84)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:294)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:161)
	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 422, message: 'Unprocessable Entity' for URL: https://api.github.com/repos/iedexmain1/EclipseCheTestRepo-tkbai/pulls
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	... 50 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/iedexmain1/EclipseCheTestRepo-tkbai/pulls
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.kohsuke.github.Requester.parse(Requester.java:612)
	... 52 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/iedexmain1/EclipseCheTestRepo-tkbai/pulls
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	... 52 common frames omitted
 </pre>
</details>

Next reaction of client on error were observed:

#### Pull request panel is opened and it displays "Creation of the pull request failed. Contribution is interrupted." message instead of "Your pull request has been created."

![org eclipse che selenium git pullrequestpluginwithforktest createpullrequest_k9yj8tg4](https://user-images.githubusercontent.com/1197777/39314518-163d0880-497d-11e8-9d24-172f265b4414.png)

![pull-fork-bug-2](https://user-images.githubusercontent.com/1197777/39314606-4ff4e39a-497d-11e8-8422-b412d9535cf1.png)
![pull-fork-bug-1](https://user-images.githubusercontent.com/1197777/39314607-5013f2e4-497d-11e8-8d5d-efdefe177266.png)
![pull-fork-bug-3](https://user-images.githubusercontent.com/1197777/39314608-503157d0-497d-11e8-9520-05baa26cce4a.png)

Webdriver log fragment
```
172.17.42.1 - - [25/Apr/2018:20:47:47 +0000] "GET /api/project/tree/?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:47 +0000] "GET /api/project/tree/pull-request-plugin-fork-test?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:48 +0000] "GET /api/github/repositories/iedexmain1/EclipseCheTestRepo-5dolm HTTP/1.1" 200 697
172.17.42.1 - - [25/Apr/2018:20:47:48 +0000] "OPTIONS /api/github/pullrequests/iedexmain1/EclipseCheTestRepo-5dolm?head=chepullreq3:undefined HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:48 +0000] "GET /api/github/pullrequests/iedexmain1/EclipseCheTestRepo-5dolm?head=chepullreq3:undefined HTTP/1.1" 200 19
172.17.42.1 - - [25/Apr/2018:20:47:48 +0000] "OPTIONS /api/github/forks/iedexmain1/EclipseCheTestRepo-5dolm HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:48 +0000] "GET /api/github/forks/iedexmain1/EclipseCheTestRepo-5dolm HTTP/1.1" 200 19
172.17.42.1 - - [25/Apr/2018:20:47:49 +0000] "OPTIONS /api/github/createfork/iedexmain1/EclipseCheTestRepo-5dolm HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "GET /api/github/createfork/iedexmain1/EclipseCheTestRepo-5dolm HTTP/1.1" 200 1410
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "OPTIONS /api/git/remote?projectPath=/pull-request-plugin-fork-test&verbose=false HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "GET /api/git/remote?projectPath=/pull-request-plugin-fork-test&verbose=false HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "OPTIONS /api/git/remote?projectPath=/pull-request-plugin-fork-test HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "PUT /api/git/remote?projectPath=/pull-request-plugin-fork-test HTTP/1.1" 204 -
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "OPTIONS /api/github/pullrequests/chepullreq3/EclipseCheTestRepo-5dolm?head=chepullreq3:undefined HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "GET /api/github/pullrequests/chepullreq3/EclipseCheTestRepo-5dolm?head=chepullreq3:undefined HTTP/1.1" 200 19
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "OPTIONS /api/git/push?projectPath=/pull-request-plugin-fork-test HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:53 +0000] "POST /api/git/push?projectPath=/pull-request-plugin-fork-test HTTP/1.1" 500 -
172.17.42.1 - - [25/Apr/2018:20:47:54 +0000] "OPTIONS /api/github/pullrequest/iedexmain1/EclipseCheTestRepo-5dolm HTTP/1.1" 200 -
172.17.42.1 - - [25/Apr/2018:20:47:54 +0000] "POST /api/github/pullrequest/iedexmain1/EclipseCheTestRepo-5dolm HTTP/1.1" 500 -
172.17.42.1 - - [25/Apr/2018:20:47:55 +0000] "GET /api/liveness HTTP/1.1" 200 -
```

#### Pull request panel is closed
![org eclipse che selenium git pullrequestplugintest createpullrequest_x71bscwg](https://user-images.githubusercontent.com/1197777/39520230-87801494-4e12-11e8-8d76-d56fcb42bd6a.png)

**OS and version:**    
- Eclipse Che 6.5.0-SNAPSHOT Multiuser on OCP
- [che-integration-tests-multiuser-master-ocp job on CI](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/195/testReport/)

**Comment by vparfonov** [comment]
fixed in https://github.com/eclipse/che/issues/9987
