### ISSUE TITLE
Unable to install Eclipse che on docker

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#9580]
I'm trying to install Eclipse che multi-user on a centos machine. I run this command : 
`
docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=myadress -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che:6.4.1 start`

But I got this error 

```
Unable to find image 'eclipse/che:6.4.1' locally
Trying to pull repository docker.io/eclipse/che ...
6.4.1: Pulling from docker.io/eclipse/che
Digest: sha256:79594c5813bd176ef94f54fe2a4fa3dff0e1f385bc33ebd950fa4ea45f27943d
Status: Downloaded newer image for docker.io/eclipse/che:6.4.1
INFO: Welcome to Eclipse Che!
INFO:
INFO: We could not resolve DockerHub using DNS.
INFO: Either we cannot reach the Internet or Docker's DNS resolver needs a modification.
INFO:
INFO: You can:
INFO:   1. Modify Docker's DNS settings.
INFO:      a. Docker for Windows & Mac have GUIs for this.
INFO:      b. Typically setting DNS to 8.8.8.8 fixes resolver issues.
INFO:   2. Does your network require Docker to use a proxy?
INFO:      a. Docker for Windows & Mac have GUIs to set proxies.
INFO:   3. Verify that you have access to DockerHub.
INFO:      a. Try 'curl --head hub.docker.com'
INFO:   4. Skip networking checks.
INFO:      a. Add '--fast' to any command
```

I don't really know why I got this error. I setted the Docker DNS file to 8.8.8.8 but still got the same problem. Please do you have any idea to help me installing Che ? Thanks

**Comment by eivantsov** [comment]
@KOSSOKO this is where it fails.

Can you run any container with curl and this to execute this command manually?

**Comment by KOSSOKO** [comment]
@eivantsov it was a firewall problem. I added some exceptions about docker in my firewall rules, and I now able to run the command but now, I have this error about postgres


```
docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=10.29.150.153 -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start
WARN: Bound 'eclipse/che' to 'eclipse/che:6.4.1'
INFO: (che cli): 6.4.1 - using docker 18.04.0-ce / native
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [OK]
         conn (server => ws):     [OK]

INFO: (che start): Starting containers...
ERROR: Error during 'compose up' - printing 30 line tail of /root/.che-multiuser/cli.log:
 CHE_HOST_CONFIG_MANIFESTS_FOLDER=/root/.che-multiuser/instance/manifests
 CHE_HOST_CONFIG_MODULES_FOLDER=/root/.che-multiuser/instance/modules
-CHE_HOST_ENV=
+CHE_HOST_ENV=10.29.150.153
 CHE_HOST_INSTANCE=/root/.che-multiuser/instance
 CHE_HOST_LOCAL=10.29.150.153
 CHE_HOST_OFFLINE_FOLDER=/root/.che-multiuser/backup

Notice: /Stage[main]/Che/File[/opt/che/config/che/che.env]/content: content changed '{md5}d3a6b27ffbc2d05117045e13cbfdd05d' to '{md5}9fad41811b5cb88d1f532e9ff8b5346e'
Notice: Applied catalog in 0.28 seconds
INFO: (che config):  Customizing docker-compose for running in a container
INFO: (che start):  Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
eef65215b69b86f2d03d36417f3181250162003196bd75ce8231111f88aaa2ca
/usr/bin/curl  "-I localhost:32768/alpine-release -s -o /dev/null --connect-timeout 5 --write-out %{http_code}"
28
/usr/bin/curl  "-I 10.29.150.153:32768/alpine-release -s -o /dev/null --connect-timeout 5 --write-out %{http_code}"
         conn (browser => ws):    [OK]
         conn (server => ws):     [OK]
fakeagent-8080

INFO: (che start):  Starting containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p="che" up -d >> "/data/cli.log" 2>&1
Starting che_postgres_1

ERROR: for postgres  Cannot start service postgres: Unknown runtime specified docker-runc
Encountered errors while bringing up the project.
ERROR: Error during 'compose up' - printing 30 line tail of /root/.che-multiuser/cli.log:
```

**Comment by eivantsov** [comment]
I'd remove old containers `docker rm -f $(docker ps -a -q)` and give it a try again

**Comment by KOSSOKO** [comment]
@eivantsov  you are totally right. Thanks. I removed all old containers but when I installed from scratch, I got these errors during the install 

```

2018-05-02 14:38:01,628[ost-startStop-1]  [INFO ] [o.e.c.m.k.s.KeycloakSettings 82]     - Retrieving OpenId configuration from endpoint: http://10.29.150.153:5050/auth/realms/che/.well-known/openid-configuration
2018-05-02 14:38:02,768[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4752] - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://10.29.150.153:5050/auth/realms/che/.well-known/openid-configuration
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:61)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:48)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.dao.KeycloakProfileDao.<init>(KeycloakProfileDao.java:46)
  while locating org.eclipse.che.multiuser.keycloak.server.dao.KeycloakProfileDao
  while locating org.eclipse.che.api.user.server.spi.ProfileDao
    for the 2nd parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.<init>(KeycloakUserManager.java:56)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.class(KeycloakUserManager.java:56)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager
  while locating org.eclipse.che.multiuser.api.account.personal.PersonalAccountUserManager
  while locating org.eclipse.che.api.user.server.UserManager
Caused by: java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://10.29.150.153:5050/auth/realms/che/.well-known/openid-configuration
        at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:95)
        at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings$$FastClassByGuice$$e0d0786b.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
```

**Comment by eivantsov** [comment]
@KOSSOKO has Keycloak started OK? Can you check container logs? Looks like it is but Che cannot reach it from within own container. can you make sure port 5050 is open?

**Comment by KOSSOKO** [comment]
@eivantsov when i run docker ps I have 

```
09f396551a11        eclipse/che-server:6.4.1                 "/entrypoint.sh"         12 minutes ago      Up 12 minutes             8000/tcp, 0.0.0.0:8080->8080/tcp                               che
7a687c6fd3bd        jboss/keycloak-openshift:3.3.0.CR2-3     "start-keycloak.sh -…"   12 minutes ago      Up 12 minutes (healthy)   0.0.0.0:5050->8080/tcp                                         che_keycloak_1

```
In don't know how to check if the port is open

in the logs of keycloak, i have no errors 
```

docker logs che_keycloak_1
[KEYCLOAK DOCKER IMAGE] Using the external postgres database
15:00:28,846 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.0.Final
15:00:28,918 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
15:00:29,051 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) starting
15:00:29,118 INFO  [org.jboss.vfs] (MSC service thread 1-5) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
15:00:30,903 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:00:30,988 INFO  [org.wildfly.security] (Controller Boot Thread) ELY00001: WildFly Elytron version 1.1.1.Final
15:00:31,003 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:00:31,174 INFO  [org.jboss.as.patching] (MSC service thread 1-6) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
15:00:31,188 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
15:00:31,277 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
15:00:31,279 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) started in 2427ms - Started 67 of 81 services (25 services are lazy, passive or on-demand)
The batch executed successfully
15:00:31,437 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) stopped in 13ms
15:00:32,449 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.0.Final
15:00:32,522 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
15:00:32,651 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) starting
15:00:32,701 INFO  [org.jboss.vfs] (MSC service thread 1-8) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
15:00:34,447 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:00:34,539 INFO  [org.wildfly.security] (Controller Boot Thread) ELY00001: WildFly Elytron version 1.1.1.Final
15:00:34,552 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:00:34,711 INFO  [org.jboss.as.patching] (MSC service thread 1-2) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
15:00:34,720 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-6) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
15:00:34,843 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
15:00:34,845 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) started in 2389ms - Started 67 of 86 services (30 services are lazy, passive or on-demand)
The batch executed successfully
15:00:35,045 INFO  [org.jboss.as] (MSC service thread 1-4) WFLYSRV0050: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) stopped in 14ms
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/keycloak

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

15:00:35,875 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.0.Final
15:00:36,176 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
15:00:36,325 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) starting
15:00:36,380 INFO  [org.jboss.vfs] (MSC service thread 1-4) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
15:00:37,899 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:00:37,959 INFO  [org.wildfly.security] (ServerService Thread Pool -- 12) ELY00001: WildFly Elytron version 1.1.1.Final
15:00:37,965 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 3) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
15:00:38,122 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
15:00:38,146 INFO  [org.xnio] (MSC service thread 1-3) XNIO version 3.5.1.Final
15:00:38,154 INFO  [org.xnio.nio] (MSC service thread 1-3) XNIO NIO Implementation Version 3.5.1.Final
15:00:38,197 INFO  [org.jboss.remoting] (MSC service thread 1-3) JBoss Remoting version 5.0.0.Final
15:00:38,221 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 32) WFLYIO001: Worker 'default' has auto-configured to 8 core threads with 64 task threads based on your 4 available processors
15:00:38,230 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 34) WFLYRS0016: RESTEasy version 3.0.24.Final
15:00:38,231 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 28) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
15:00:38,233 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 33) WFLYCLINF0001: Activating Infinispan subsystem.
15:00:38,245 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 28) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 42.1)
15:00:38,293 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 41) WFLYNAM0001: Activating Naming Subsystem
15:00:38,303 INFO  [org.jboss.as.connector] (MSC service thread 1-3) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.4.6.Final)
15:00:38,303 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-7) WFLYJCA0018: Started Driver service with driver-name = postgresql
15:00:38,303 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-8) WFLYJCA0018: Started Driver service with driver-name = h2
15:00:38,365 INFO  [org.jboss.as.jsf] (ServerService Thread Pool -- 39) WFLYJSF0007: Activated the following JSF Implementations: [main]
15:00:38,374 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 46) WFLYSEC0002: Activating Security Subsystem
15:00:38,391 INFO  [org.jboss.as.security] (MSC service thread 1-2) WFLYSEC0001: Current PicketBox version=5.0.2.Final
15:00:38,396 INFO  [org.jboss.as.naming] (MSC service thread 1-8) WFLYNAM0003: Starting Naming Service
15:00:38,397 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-8) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
15:00:38,404 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 47) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments running multiple servers. Please make sure the attribute value is unique.
15:00:38,484 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0003: Undertow 1.4.18.Final starting
15:00:38,529 INFO  [org.jboss.as.ejb3] (MSC service thread 1-5) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 64 (per class), which is derived from thread worker pool sizing.
15:00:38,530 INFO  [org.jboss.as.ejb3] (MSC service thread 1-6) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 16 (per class), which is derived from the number of CPUs on this host.
15:00:38,693 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 48) WFLYUT0014: Creating file handler for path '/opt/jboss/keycloak/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
15:00:38,701 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0012: Started server default-server.
15:00:38,703 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0018: Host default-host starting
15:00:38,805 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0006: Undertow HTTP listener default listening on 0.0.0.0:8080
15:00:38,848 INFO  [org.jboss.as.ejb3] (MSC service thread 1-1) WFLYEJB0493: EJB subsystem suspension complete
15:00:38,939 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
15:00:38,942 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0001: Bound data source [java:jboss/datasources/KeycloakDS]
15:00:39,005 INFO  [org.jboss.as.patching] (MSC service thread 1-7) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
15:00:39,027 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
15:00:39,051 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
15:00:39,064 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-5) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/keycloak/standalone/deployments
15:00:39,120 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTPS listener https listening on 0.0.0.0:8443
15:00:39,829 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-4) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.8.Final
15:00:40,230 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 51) WFLYCLINF0002: Started actionTokens cache from keycloak container
15:00:40,239 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 54) WFLYCLINF0002: Started work cache from keycloak container
15:00:40,241 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 50) WFLYCLINF0002: Started sessions cache from keycloak container
15:00:40,240 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 52) WFLYCLINF0002: Started loginFailures cache from keycloak container
15:00:40,241 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 53) WFLYCLINF0002: Started users cache from keycloak container
15:00:40,240 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 57) WFLYCLINF0002: Started realms cache from keycloak container
15:00:40,240 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 58) WFLYCLINF0002: Started keys cache from keycloak container
15:00:40,240 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 56) WFLYCLINF0002: Started authenticationSessions cache from keycloak container
15:00:40,240 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 59) WFLYCLINF0002: Started offlineSessions cache from keycloak container
15:00:40,239 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 55) WFLYCLINF0002: Started authorization cache from keycloak container
15:00:40,254 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 60) WFLYCLINF0002: Started client-mappings cache from ejb container
15:00:41,277 INFO  [org.keycloak.services] (ServerService Thread Pool -- 60) KC-SERVICES0001: Loading config from standalone.xml or domain.xml
15:00:41,593 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 60) WFLYCLINF0002: Started realmRevisions cache from keycloak container
15:00:41,597 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 60) WFLYCLINF0002: Started userRevisions cache from keycloak container
15:00:41,602 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 60) WFLYCLINF0002: Started authorizationRevisions cache from keycloak container
15:00:41,602 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (ServerService Thread Pool -- 60) Node name: 7a687c6fd3bd, Site name: null
15:00:43,783 INFO  [org.hibernate.jpa.internal.util.LogHelper] (ServerService Thread Pool -- 60) HHH000204: Processing PersistenceUnitInfo [
        name: keycloak-default
        ...]
15:00:43,841 INFO  [org.hibernate.Version] (ServerService Thread Pool -- 60) HHH000412: Hibernate Core {5.1.10.Final}
15:00:43,843 INFO  [org.hibernate.cfg.Environment] (ServerService Thread Pool -- 60) HHH000206: hibernate.properties not found
15:00:43,844 INFO  [org.hibernate.cfg.Environment] (ServerService Thread Pool -- 60) HHH000021: Bytecode provider name : javassist
15:00:43,879 INFO  [org.hibernate.annotations.common.Version] (ServerService Thread Pool -- 60) HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
15:00:44,208 INFO  [org.hibernate.dialect.Dialect] (ServerService Thread Pool -- 60) HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL94Dialect
15:00:44,381 INFO  [org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl] (ServerService Thread Pool -- 60) HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
15:00:44,383 INFO  [org.hibernate.type.BasicTypeRegistry] (ServerService Thread Pool -- 60) HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@319f606c
15:00:44,388 INFO  [org.hibernate.envers.boot.internal.EnversServiceImpl] (ServerService Thread Pool -- 60) Envers integration enabled? : true
15:00:44,927 INFO  [org.hibernate.validator.internal.util.Version] (ServerService Thread Pool -- 60) HV000001: Hibernate Validator 5.3.5.Final
15:00:45,727 INFO  [org.hibernate.hql.internal.QueryTranslatorFactoryInitiator] (ServerService Thread Pool -- 60) HHH000397: Using ASTQueryTranslatorFactory
15:00:46,658 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (ServerService Thread Pool -- 60) Importing from directory /opt/jboss/keycloak/realms
15:00:46,900 INFO  [org.keycloak.services] (ServerService Thread Pool -- 60) KC-SERVICES0030: Full model import requested. Strategy: IGNORE_EXISTING
15:00:47,067 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 60) Realm 'master' already exists. Import skipped
15:00:47,167 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 60) Realm 'che' already exists. Import skipped
15:00:47,186 INFO  [org.keycloak.services] (ServerService Thread Pool -- 60) KC-SERVICES0032: Import finished successfully
15:00:47,252 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.keycloak.services.resources.KeycloakApplication
15:00:47,254 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002200: Adding class resource org.keycloak.services.resources.JsResource from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,254 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002200: Adding class resource org.keycloak.services.resources.ThemeResource from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,254 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002205: Adding provider class org.keycloak.services.filters.KeycloakTransactionCommitter from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,254 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002210: Adding provider singleton org.keycloak.services.util.ObjectMapperResolver from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,255 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RobotsResource from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,255 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.admin.AdminRoot from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,255 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RealmsResource from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,256 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.ServerVersionResource from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,256 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 60) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.WelcomeResource from Application class org.keycloak.services.resources.KeycloakApplication
15:00:47,342 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 60) WFLYUT0021: Registered web context: '/auth' for server 'default-server'
15:00:47,358 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 49) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
15:00:47,453 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
15:00:47,455 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
15:00:47,455 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
15:00:47,456 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) started in 12003ms - Started 537 of 859 services (570 services are lazy, passive or on-demand)
```

**Comment by eivantsov** [comment]
Must be port issue. Keycloak started ok.

There's tons of info online on how to manage ports on different OS

**Comment by KOSSOKO** [comment]
@eivantsov thanks a lot. Problem solved. the port 5050 were blocked in my iptables

**Comment by gorkem** [comment]
Super Eugene saves the day. Closing
