### ISSUE TITLE
Clangd does not work on Fedora and RHEL

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9603]
Not sure whose fault is this:

On RHEL 7.4, with llvm-toolset-extra **5.0.1** (which includes clangd), initialization of a language server happens but with errors:

```
          "documentFormattingProvider": true,
          "codeActionProvider": true,
          "documentOnTypeFormattingProvider": {"firstTriggerCharacter":"}","moreTriggerCharacter":[]},
          "textDocumentSync": 1,
          "documentRangeFormattingProvider": true,
--> {"jsonrpc":"2.0","id":"1","result":{"capabilities":{
<-- {"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":226,"rootPath":"/projects/c-simple-console","rootUri":"file:///projects/c-simple-console","capabilities":{"workspace":{"applyEdit":false,"workspaceEdit":{},"didChangeConfiguration":{},"didChangeWatchedFiles":{},"symbol":{},"executeCommand":{}},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":false,"didSave":true},"completion":{"completionItem":{}},"hover":{},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{},"formatting":{},"rangeFormatting":{},"onTypeFormatting":{},"definition":{},"codeAction":{},"codeLens":{},"documentLink":{},"rename":{}}},"clientName":"EclipseChe"}}
        }}}
          "completionProvider": {"resolveProvider": false, "triggerCharacters": [".",">"]},
          "definitionProvider": true
2018-05-03 18:08:05,273[pool-9-thread-1]  [INFO ] [.c.a.l.r.ServerInitializerImpl 123]  - Initialized Language Server org.eclipse.che.plugin.clangd.languageserver on project file:///projects/c-simple-console
Failed to decode DidOpenTextDocumentParams!
<-- {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///projects/c-simple-console/Hello.c","languageId":"clangd","version":0,"text":"#include \u003cstdio.h\u003e\n\nint main() {\n    printf(\"Hello World\\n\");\n    return 0;\n    .\n}"},"text":"#include \u003cstdio.h\u003e\n\nint main() {\n    printf(\"Hello World\\n\");\n    return 0;\n    .\n}"}}
<-- {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":1,"uri":"file:///projects/c-simple-console/Hello.c"},"uri":"file:///projects/c-simple-console/Hello.c","contentChanges":[{"text":"#include \u003cstdio.h\u003e\n\nint main() {\n    printf(\"Hello World\\n\");\n    return 0;\n    \n}"}]}}
Failed to decode DidChangeTextDocumentParams!
Notification ignored.
<-- {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///projects/c-simple-console/Hello.c"}}}
<-- {"jsonrpc":"2.0","id":"2","method":"textDocument/completion","params":{"textDocument":{"uri":"file:///projects/c-simple-console/Hello.c"},"uri":"file:///projects/c-simple-console/Hello.c","position":{"line":5,"character":4}}}
/home/jboss/che/ls-clangd/launch.sh: line 1:   358 Segmentation fault      (core dumped) clangd
2018-05-03 18:11:12,904[equestProcessor]  [INFO ] [o.e.c.a.l.util.OperationUtil 49]     - Exception occurred in op
	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToOne.lambda$withFunction$0(FunctionConfiguratorOneToOne.java:75)
	at org.eclipse.che.api.languageserver.util.OperationUtil.doInSequence(OperationUtil.java:41)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.sendCancelNotification(RemoteEndpoint.java:136)
Caused by: java.lang.RuntimeException: java.io.IOException: Stream closed
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:102)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at org.eclipse.che.api.languageserver.util.OperationUtil.doInParallel(OperationUtil.java:114)
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:65)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint$1.cancel(RemoteEndpoint.java:115)
	at org.eclipse.che.api.languageserver.service.TextDocumentService$2.lambda$start$0(TextDocumentService.java:281)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	... 11 common frames omitted
	at java.io.OutputStream.write(OutputStream.java:116)
Caused by: java.io.IOException: Stream closed
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
	at org.eclipse.che.api.languageserver.service.TextDocumentService.completion(TextDocumentService.java:294)
```

When tested on Debian and Ubuntu, where llvm version is 6.0, everything works as expected:

```
<-- {"id":"1","jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{},"codeLens":{},"completion":{"completionItem":{}},"definition":{},"documentHighlight":{},"documentLink":{},"documentSymbol":{},"formatting":{},"hover":{},"onTypeFormatting":{},"rangeFormatting":{},"references":{},"rename":{},"signatureHelp":{},"synchronization":{"didSave":true,"willSave":true,"willSaveWaitUntil":false}},"workspace":{"applyEdit":false,"didChangeConfiguration":{},"didChangeWatchedFiles":{},"executeCommand":{},"symbol":{},"workspaceEdit":{}}},"clientName":"EclipseChe","processId":198,"rootPath":"/projects/c","rootUri":"file:///projects/c"}}
 
--> {"id":"1","jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",">",":"]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix"]},"renameProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":1}}}
2018-05-03 18:06:05,029[pool-9-thread-1]  [INFO ] [.c.a.l.r.ServerInitializerImpl 123]  - Initialized Language Server org.eclipse.che.plugin.clangd.languageserver on project file:///projects/c
<-- {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"text":"#include <stdio.h>\n\nint main() {\n    printf(\"Hello World\\n\");\n    return 0;\n}","textDocument":{"languageId":"clangd","text":"#include <stdio.h>\n\nint main() {\n    printf(\"Hello World\\n\");\n    return 0;\n}","uri":"file:///projects/c/Hello.c","version":0}}}
 
Failed to find compilation database for /projects/c/Hello.c
Opened file /projects/c/Hello.c with command [/projects/c] clang /projects/c/Hello.c -resource-dir=/usr/lib/llvm-6.0/bin/../lib/clang/6.0.1
Premble for file /projects/c/Hello.c cannot be reused. Attempting to rebuild it.
Built preamble of size 266880 for file /projects/c/Hello.c
--> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///projects/c/Hello.c"}}
 
<-- {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"#include <stdio.h>\n\nint main() {\n    printf(\"Hello World\\n\");\n    return 0;\n    \n}"}],"textDocument":{"uri":"file:///projects/c/Hello.c","version":1},"uri":"file:///projects/c/Hello.c"}}
Reusing preamble for file /projects/c/Hello.c
--> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///projects/c/Hello.c"}}
<-- {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///projects/c/Hello.c"}}}
 
Error -32601: method not found
 
<-- {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"#include <stdio.h>\n\nint main() {\n    printf(\"Hello World\\n\");\n    return 0;\n    .\n}"}],"textDocument":{"uri":"file:///projects/c/Hello.c","version":2},"uri":"file:///projects/c/Hello.c"}}
Reusing preamble for file /projects/c/Hello.c
--> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"expected expression","range":{"end":{"character":5,"line":5},"start":{"character":4,"line":5}},"severity":1}],"uri":"file:///projects/c/Hello.c"}}
 
Error -32601: method not found
<-- {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///projects/c/Hello.c"}}}
```

**Comment by eivantsov** [comment]
Registered bugzilla issue - https://bugzilla.redhat.com/show_bug.cgi?id=1574653

Looks like clangd in llvm 6.0 package is ok (tested with Fedora 28 and clangd from llvm-tools-extra) package.
