### ISSUE TITLE
[hot_update] Find way to avoid errors in the moment when Che server pending HTTP requests during update

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#9624]
### Description
Workspace agent needs somehow communicate with Che Server. And it uses Che Server Route URL for requests. But during Rolling Update there may be some hanging requests (for about few minutes) when OpenShift Router picks up the new Che Server. As result Workspace Agent fails to start when it requests Che Server during switching Che Servers. Logs are attached.

Possible way is to find out unavailbility time and increase request timeout times on agent. 

<details>
<summary>WsAgentLogs</summary>

<pre>
018-04-26 15:48:09,020[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.23
2018-04-26 15:48:09,111[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/che/ws-agent/webapps/ROOT.war]
2018-04-26 15:48:43,050[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4752]    - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Invocation error of method public void org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.initialize() throws org.eclipse.che.api.core.ConflictException,org.eclipse.che.api.core.NotFoundException,org.eclipse.che.api.core.ServerException,org.eclipse.che.api.core.ForbiddenException on org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer@1e57ace0
  at org.eclipse.che.api.project.server.ProjectApiModule.configure(ProjectApiModule.java:60) (via modules: org.eclipse.che.wsagent.server.WsAgentModule -> org.eclipse.che.api.project.server.ProjectApiModule)
  while locating org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer
1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
        at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ServerException: java.io.IOException: Failed access: http://che-eclipse-che.172.19.20.43.nip.io/api/workspace/workspace74g0awl999pk64t9?token, method: GET, response code: 504, message: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
        at org.eclipse.che.api.project.server.impl.WorkspaceProjectSynchronizer.workspaceDto(WorkspaceProjectSynchronizer.java:224)
        at org.eclipse.che.api.project.server.impl.WorkspaceProjectSynchronizer.getAll(WorkspaceProjectSynchronizer.java:128)
        at org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.initializeRegisteredProjects(OnWorkspaceStartProjectInitializer.java:63)
        at org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.initialize(OnWorkspaceStartProjectInitializer.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:46)
        at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        ... 18 common frames omitted
Caused by: java.io.IOException: Failed access: http://che-eclipse-che.172.19.20.43.nip.io/api/workspace/workspace74g0awl999pk64t9?token, method: GET, response code: 504, message: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:284)
        at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:163)
        at org.eclipse.che.api.project.server.impl.WorkspaceProjectSynchronizer.workspaceDto(WorkspaceProjectSynchronizer.java:221)
        ... 40 common frames omitted
2018-04-26 15:48:43,051[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5208]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
2018-04-26 15:48:43,053[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5259]     - Context [] startup failed due to previous errors
2018-04-26 15:48:43,067[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/che/ws-agent/webapps/ROOT.war] has finished in [33,955] ms
2018-04-26 15:48:43,069[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-4401"]
2018-04-26 15:48:43,077[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 34108 ms
</pre>
</details>

**Comment by mshaposhnik** [comment]
I have written the script which GET-s the workspace every 0.1 s and logs the full request time.
During update, there is always single 5-6 sec outage when 000 status code returned, and then API resumes normally. Never saw 504 responses.
