### ISSUE TITLE
Failing of a build of Theia in Theia image produces an invalid image

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#9649]
### Description
I'm trying to build Che Theia image with hardcoded 0.3.7 Theia dependencies and see an error in the build of image. But docker completes build succesfully. And this image is invalid and produces next output on start:
<details>

```
cp: can't stat '/home/default/theia/src-gen': No such file or directory
child_process.js:644
    throw err;
    ^
 Error: Command failed: cp -r /home/default/theia/node_modules /home/theia &amp;&amp; cp -r /home/default/theia/src-gen /home/theia &amp;&amp; cp -r /home/default/theia/lib /home/theia &amp;&amp; cp /home/default/theia/yarn.lock /home/default/theia/package.json /home/theia
cp: can't stat '/home/default/theia/src-gen': No such file or directory
     at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at copyDefaultTheiaBuild (/theia_launcher/theia_launcher.js:64:8)
    at prepareTheia (/theia_launcher/theia_launcher.js:33:9)
    at Object.&lt;anonymous&gt; (/theia_launcher/theia_launcher.js:22:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
</details>

Here is the output of build:
<details>

```
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
warning @theia/typescript > @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
warning vscode-base-languageclient@0.0.1-alpha.5: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
csuccess Saved lockfile.
Done in 28.57s.
yarn run v1.5.1
$ /home/default/theia/node_modules/.bin/theia build
Uncaught Exception:  TypeError: application_package_1.ApplicationPackageManager is not a constructor
TypeError: application_package_1.ApplicationPackageManager is not a constructor
    at Object.<anonymous> (/home/default/theia/node_modules/@theia/cli/lib/theia.js:79:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/default/theia/node_modules/@theia/cli/bin/theia:2:1)
    at Module._compile (module.js:652:30)
Done in 0.35s.
 ---> 460f6985bc20
Removing intermediate container 94c644cf2171
Step 9/13 : ADD src/main.js /theia_launcher/theia_launcher.js
 ---> 0eef3d1b0904
Step 10/13 : EXPOSE 3000
 ---> Running in 5b16e52f66e5
 ---> 13796e0bc657
Removing intermediate container 5b16e52f66e5
Step 11/13 : ARG GITHUB_TOKEN=d5800cbe07acefc27f8a8ba53d18cc7bd5c10c29
 ---> Running in 34bc9f1e4ec8
 ---> 71f652b5c35b
Removing intermediate container 34bc9f1e4ec8
Step 12/13 : ENV USE_LOCAL_GIT true GITHUB_TOKEN ${GITHUB_TOKEN}
 ---> Running in 106d87583aba
 ---> 450322d3c981
Removing intermediate container 106d87583aba
Step 13/13 : ENTRYPOINT node /theia_launcher/theia_launcher.js
 ---> Running in 9ca32548da2a
 ---> 5a897521bb12
Removing intermediate container 9ca32548da2a
Successfully built 5a897521bb12
Successfully tagged eclipse/che-theia:nightly
Build of eclipse/che-theia:nightly [OK]
Script run successfully: eclipse/che-theia:nightly
```
</details>

Looks like we might need more checks in the dockerfile to ensure that build is trully successful. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@riuvshin @eivantsov

**Comment by eivantsov** [comment]
https://github.com/eclipse/che/pull/9684
