### ISSUE TITLE
[Kuebernetes] Unable to start che multi-user with TLS-enabled

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#9674]
### Description

When a mutli-user che is set up on kubernetes with tls-enabled using the instructions (here)[https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che#tls-enabled], I'm unable to access the dashboard.

A valid certificate is served when accessing the URLs.

The initial login screen works along with the request for change of password but from there the dashboard does not load **since all requests to the path /api fail with an internal server error (500)**

<img width="1440" alt="screen shot 2018-05-10 at 11 50 46 pm" src="https://user-images.githubusercontent.com/16825130/39905281-232c7462-54fa-11e8-9041-34d23a7c13d2.png">

The server logs look like this:

```

2018-05-10 18:11:26,476[nio-8080-exec-5]  [ERROR] [o.a.c.c.C.[.[.[/api].[default] 245]  - Servlet.service() for servlet [default] in context with path [/api] threw exception
io.jsonwebtoken.JwtException: Error during the retrieval of the public key during JWT token validation
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$1.resolveSigningKey(KeycloakAuthenticationFilter.java:99)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:316)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:105)
	at org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:128)
	at org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:49)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:423)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.auth0.jwk.SigningKeyNotFoundException: Failed to get key with kid e23Fsy3FR9vtTfk7Lid_YP8e4p3hcJl3m0A4grB36rI
	at com.auth0.jwk.GuavaCachedJwkProvider.get(GuavaCachedJwkProvider.java:53)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.getJwtPublicKey(KeycloakAuthenticationFilter.java:143)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.access$000(KeycloakAuthenticationFilter.java:48)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter$1.resolveSigningKey(KeycloakAuthenticationFilter.java:97)
	... 29 common frames omitted
Caused by: java.util.concurrent.ExecutionException: com.auth0.jwk.SigningKeyNotFoundException: Cannot obtain jwks from url http://che-fullstack.che1.mydomain.com/auth/realms/che/protocol/openid-connect/certs

```

This is the response to curl GET requests to ```http(s)://che-fullstack.che1.mydomain.com/auth/realms/che/protocol/openid-connect/certs```

<img width="1440" alt="screen shot 2018-05-11 at 9 18 07 am" src="https://user-images.githubusercontent.com/16825130/39905811-da03befa-54fc-11e8-9851-ac6125de7c77.png">

Keycloak dashboard or login page  at (https://che-fullstack.che1.mydomain.com/auth/admin/master/console/) does not load due to `Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.` errors.

<img width="1440" alt="screen shot 2018-05-11 at 9 10 11 am" src="https://user-images.githubusercontent.com/16825130/39906226-f744d2d6-54fe-11e8-8475-818f43730cad.png">

### Reproduction Steps

1. Set up Che multi-user with tls-enabled according to the instructions at https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che#tls-enabled
2. Try to log into Che dashboard
3. Try to log into Keycloak console

**OS and version:**
Che-Nightly

**Comment by mjshashank** [comment]
Duplicate of #9429 
Got it working through the same solution as mentioned in #9429, closing issue now.
