### ISSUE TITLE
Unable to pull docker image from authenticated private registry using user provided credentials (docker - single user)

### ISSUE THREAD

**Issue by sclarke353** [eclipse-che/che#9697]
### Description

Hi, i couldn't find any reference to this in the Che 6 documentation but in Che 5 (docker - single user) it was possible to provide docker registry credentials in Administration which could be used to pull a stack image from a private authenticated docker registry on workspace creation but that no longer works in Che 6.

The docker credentials are not being retrieved from the preferences when pulling the image.

### Reproduction Steps
- Run Che on Docker in Single User mode.
- Enter private Docker registry credentials in Administration.
- Create a stack and reference an image from the private repo in the recipe.
- Create a Workspace and select that stack.

**OS and version:** 
macOS 10.12.6
Docker for Mac 17.09.1-ce-mac42 (21090)

**Diagnostics:** 
From the Logs (docker reg url edited) running che:nightly (6.6.0-SNAPSHOT)
```
2018-05-14 11:48:39,418[aceSharedPool-2]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 379]   - Can't create machine from image. Cause: Error response from docker API, status: 500, message: Get https://corp-repo/v2/tag/manifests/latest: unauthorized: BAD_CREDENTIAL

org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: Can't create machine from image. Cause: Error response from docker API, status: 500, message: Get https://corp-repo/v2/tag/manifests/latest: unauthorized: BAD_CREDENTIAL

	at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.pullImage(ParallelDockerImagesBuilder.java:285)
	at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.prepareImage(ParallelDockerImagesBuilder.java:178)
	at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.lambda$prepareImages$0(ParallelDockerImagesBuilder.java:126)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.infrastructure.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Get https://corp-repo/v2/tag/manifests/latest: unauthorized: BAD_CREDENTIAL

	at org.eclipse.che.infrastructure.docker.client.DockerConnector.getDockerException(DockerConnector.java:1528)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.pull(DockerConnector.java:1131)
	at org.eclipse.che.infrastructure.docker.client.DockerConnector.pull(DockerConnector.java:1104)
	at org.eclipse.che.workspace.infrastructure.docker.ParallelDockerImagesBuilder.pullImage(ParallelDockerImagesBuilder.java:273)
	... 6 common frames omitted
```

Verified that the registry credentials are stored correctly by decoding the response from
http://localhost:8080/api/preferences?filter=dockerCredentials

Added some logging to:  **org.eclipse.che.infrastructure.docker.client.UserSpecificDockerRegistryCredentialsProvider** and **encodedCredentials** in the following snippet is null. The userId passed to the preference manager is  0000-00-0000 (anonymous user).
```
  public AuthConfigs getCredentials() {
    ...
    String encodedCredentials =
        preferenceManager
            .find(
                EnvironmentContext.getCurrent().getSubject().getUserId(),
                DOCKER_REGISTRY_CREDENTIALS_KEY)
            .get(DOCKER_REGISTRY_CREDENTIALS_KEY);
      String credentials =
          encodedCredentials != null
              ? new String(Base64.getDecoder().decode(encodedCredentials), "UTF-8")
              : "{}";
      ...
  }
```
Modifying che.env and adding the credentials does work
https://www.eclipse.org/che/docs/docker-config.html#private-images

**Comment by eivantsov** [comment]
@sclarke353 che.env worked for me - tried DockerHub.

**Comment by sclarke353** [comment]
Hi @eivantsov, yeah che.env works for me as well. This is just to see if it should work with user provided credentials in administration as well when run in docker single user.

**Comment by sln1803** [comment]
just to add.. If the userid returned from
```
EnvironmentContext.getCurrent().getSubject().getUserId()
```
 is **che** in this scenario it will work.

**Comment by sclarke353** [comment]
just to add.. If the userid returned from

EnvironmentContext.getCurrent().getSubject().getUserId()
is che in this scenario it will work.

(edit - had used old login when commenting)

**Comment by eivantsov** [comment]
Closed due to inactivity.
