### ISSUE TITLE
Wait until Che is available by default when deploying it on OCP 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9761]
### Description
Script **ocp.sh** doesn't wait until **Che** is available by default when deploying _Eclipse Che_ on OCP: we need to use dedicated parameter `--wait-che`, or to set environment variable `WAIT_FOR_CHE=true`. 
As a result, user which is running Eclipse Che on OCP firstly receives message in output:
> deploymentconfig "che" updated
[INFO]: Che successfully deployed and will be soon available at http://che-eclipse-che.172.05.0.1.nip.io 

and than can stack on waiting _Che_ availability because of, for example, there is **firewall** service doesn't allow connection with _Che_:
```
Caused by: java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-eclipse-che.172.05.0.1.nip.io/auth/realms/che/.well-known/openid-configuration
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:95)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings$$FastClassByGuice$$e0d0786b.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
...
Caused by: java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
```
So, I propose waiting until Che is available by default and show an error instantly if it isn't available in time.

**OS and version:**    
Eclipse Che 6.6.0-SNAPSHOT Multiuser on OCP

**Comment by eivantsov** [comment]
@dmytro-ndp yes, adding smth like 

```
DEFAULT_WAIT_FOR_CHE="true"
export WAIT_FOR_CHE=${WAIT_FOR_CHE:-${DEFAULT_WAIT_FOR_CHE}}
```

And it makes sense to add it to deploy_che.sh script rather than `ocp.sh` as deploy script can be used without ocp.sh at all, provided that you have a running OpenShift cluster.
