### ISSUE TITLE
Formatting for python editor does not apply properly in a workspace with enabled python LS

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9854]
### Reproduction Steps
* Create a workspace based on Default Python Stack stack
* Enable Python language server installer if it need
* Create  `web-python2.7-simple` project from wizard
* Open `main.py` file
*  Change content from file something like that:
```python
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return       "Hello World!"

if __name__ ==      "__main__":
    app.run                 (host='0.0.0.0', port=8080,  debug=True)
```
* Apply Edit -> Format
**Expected result:**  The content should be formatted according to settings in language server. 
**Actual result:** The formatting is not applied
**OS and version:**   Fedora 28, Chrome browser v.  66.0.33, CHE single-docker, 6.6.0-SNAPSHOT, 72e350bc51a99348
**Diagnostics:** 
**Data from websocket frames:**
![selection_002](https://user-images.githubusercontent.com/1640058/40671412-81a1ddba-6374-11e8-8ef9-7b1d626ed818.png)
**Exceptions from javascript console:**
```javascript
(org.eclipse.che.plugin.languageserver.ide.editor.LanguageServerFormatter): 
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'start' of undefined
	at Unknown.phh(OrionEditorOverlay.java:72)
	at Unknown.zbh(OrionDocument.java:216)
	at Unknown.sml(LanguageServerFormatter.java:174)
	at Unknown.Bml(LanguageServerFormatter.java:147)
	at Unknown.Dml(LanguageServerFormatter.java:146)
	at Unknown.anonymous(JsPromise.java:116)
	at Unknown.$B(StringValidator.java:66)
	at Unknown.ZB(StringValidator.java:49)
	at Unknown.LB(RequestBuilder.java:292)
	at Unknown.fTk(AsyncRequest.java:72)
	at Unknown.jTk(MachineAsyncRequestFactory.java:129)
	at Unknown.anonymous(JsPromise.java:116)
	at Unknown.TA(EventBus.java:69)
	at Unknown.ark(SimpleEventBus.java:57)
	at Unknown.brk(NodeLoader.java:306)
	at Unknown.drk(NodeLoader.java:374)
	at Unknown.yrk(NodeLoader.java:366)
	at Unknown.anonymous(JsPromise.java:116)
	at Unknown.TA(EventBus.java:69)
	at Unknown.ark(SimpleEventBus.java:57)
	at Unknown.brk(NodeLoader.java:306)
	at Unknown.drk(NodeLoader.java:374)
	at Unknown.yrk(NodeLoader.java:366)
	at Unknown.anonymous(JsPromise.java:116)
	at Unknown.TA(EventBus.java:69)
	at Unknown.ark(SimpleEventBus.java:57)
	at Unknown.brk(NodeLoader.java:306)
	at Unknown.drk(NodeLoader.java:374)
	at Unknown.yrk(NodeLoader.java:36
```

**Comment by musienko-maxim** [comment]
**Also we have tested formatting with other language server and got next reults:**
The LS with disabled formatter feature:
* PHP language server 
* JSON language server
* Yaml language server 
* Camel language server
* Go language server
----
The LS where formatter works:
* Clang language server
* Type script language server
