### ISSUE TITLE
Zend stack: Errors when creating composer project type, command failures

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9937]
## Usecase 1

1. Create a workspace from Zend stack. Choose any sample from the list.

Workspace agent fails to start with the trace below:

```
2018-06-05 11:16:58,691[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4752]    - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:
 
1) Invocation error of method public void org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.initialize() throws org.eclipse.che.api.core.ConflictException,org.eclipse.che.api.core.NotFoundException,org.eclipse.che.api.core.ServerException,org.eclipse.che.api.core.ForbiddenException on org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer@23f0b2c
  at org.eclipse.che.api.project.server.ProjectApiModule.configure(ProjectApiModule.java:61) (via modules: org.eclipse.che.wsagent.server.WsAgentModule -> org.eclipse.che.api.project.server.ProjectApiModule)
  while locating org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer
1 error
 
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ServerException: java.io.IOException: Cannot run program "composer" (in directory "/projects/astro-splash"): error=2, No such file or directory
	at org.eclipse.che.plugin.composer.server.projecttype.ComposerProjectInitializer.onProjectInitialized(ComposerProjectInitializer.java:47)
	at org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.firePostInitializationHandlers(OnWorkspaceStartProjectInitializer.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:46)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.eclipse.che.api.project.server.impl.OnWorkspaceStartProjectInitializer.initialize(OnWorkspaceStartProjectInitializer.java:60)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 18 common frames omitted
Caused by: java.io.IOException: Cannot run program "composer" (in directory "/projects/astro-splash"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.eclipse.che.plugin.composer.server.executor.ComposerCommandExecutor.execute(ComposerCommandExecutor.java:62)
	at org.eclipse.che.plugin.composer.server.projecttype.ComposerProjectInitializer.onProjectInitialized(ComposerProjectInitializer.java:45)
	... 39 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 41 common frames omitted
```

## Use case 2

1. Create a workspace form Zend stack. Do not select any projects in User Dashboard
2. When in the IDE, go to Workspace > Create a project > astro-splash

![image](https://user-images.githubusercontent.com/5337267/40973157-e04bd72e-68cb-11e8-802f-f0128ac319d5.png)

```
2018-06-05 11:22:16,489[nio-4401-exec-8]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 46]   - Internal Server Error occurred, error time: 2018-06-05 11:22:16
	at com.google.gson.Gson.fromJson(Gson.java:826)
	at org.eclipse.che.plugin.composer.server.projecttype.ComposerValueProviderFactory$ComposerValueProvider.readModel(ComposerValueProviderFactory.java:75)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at org.eclipse.che.api.project.server.impl.RegisteredProjectImpl$$FastClassByGuice$$c460e16c.newInstance(<generated>)
	at org.eclipse.che.plugin.composer.server.projecttype.ComposerValueProviderFactory$ComposerValueProvider.getValues(ComposerValueProviderFactory.java:60)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at org.eclipse.che.api.project.server.impl.RegisteredProjectImpl.<init>(RegisteredProjectImpl.java:120)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at org.eclipse.che.api.project.server.impl.RegisteredProjectImpl.initAttributes(RegisteredProjectImpl.java:153)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.gson.Gson.fromJson(Gson.java:903)
com.google.gson.JsonSyntaxException: java.io.IOException: Is a directory
	at org.eclipse.che.api.project.server.impl.SynchronizingProjectManager.update(SynchronizingProjectManager.java:124)
	at org.eclipse.che.api.project.server.impl.ProjectServiceApi.createBatchProjects(ProjectServiceApi.java:195)
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306)
	at com.sun.proxy.$Proxy27.create(Unknown Source)
	at org.eclipse.che.api.project.server.impl.ExecutiveProjectManager.update(ExecutiveProjectManager.java:172)
	at org.eclipse.che.api.project.server.impl.InmemoryProjectRegistry.put(InmemoryProjectRegistry.java:73)
	at org.eclipse.che.api.project.server.ProjectService.createBatchProjects(ProjectService.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at org.eclipse.che.api.project.server.impl.ValidatingProjectManager.update(ValidatingProjectManager.java:178)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140)
	at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:161)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.eclipse.che.EnvironmentInitializationFilter.doFilter(EnvironmentInitializationFilter.java:44)
	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:294)
	at org.eclipse.che.workspace.activity.LastAccessTimeFilter.doFilter(LastAccessTimeFilter.java:52)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62)
	at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120)
	at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
	at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1576)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.Gson.fromJson(Gson.java:884)
	... 68 common frames omitted
	at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128)
	at org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:59)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
```

Once such a workspace is stopped, it cannot be started because of usecase #1 ie when a project is saved to workspace config.

Even though the workspace has started there are other issues, not related to wsagent project service failures. For instance, commands do not work:

![image](https://user-images.githubusercontent.com/5337267/40973282-5ee49576-68cc-11e8-8eda-c9ce8ff78313.png)

**Comment by slemeur** [comment]
@kaloyan-raev @bartlomiej-laczkowski Is that something you could give a look at?
